### ISSUE TITLE
Fixed-position navbar obscures start of content of in-page fragment links

### ISSUE THREAD

**Issue by ShellyInyo** [twbs/bootstrap#17565] opened 2015-09-10 21:54 UTC
The fixed navbar is not compatible with in page bookmark links as clicking on a link that's supposed to take you to another point on a page causes that point on the page to be at the top of the viewport and as a result, the fixed navbar covers it. I'm able to duplicate this issue using BS3's fixed navbar example page.

Example: https://jsfiddle.net/sd5nhnhg/

**Comment by cvrebert** [comment] 2015-09-10 23:08
Duplicate of #1768, although personally I agree we should try to address this somehow.
Retargeting at Bootstrap v4.

**Comment by matt-hernandez** [comment] 2015-09-17 16:03
I have a fiddle that shows a possible fix by attaching a callback to the body. I'm open to criticism.

https://jsfiddle.net/a_matt_appeared/92ce7ne6/

**Comment by mdo** [comment] 2016-07-28 02:43
Closing this as we currently have no plans to write generic JS to address this for in v4.

**Closed by mdo** 2016-07-28 02:43 UTC
Labels: feature, js, v4
