### ISSUE TITLE
.bg-primary buries links (colour matches link colour)

### ISSUE THREAD

**Issue by CriseX** [twbs/bootstrap#16526] opened 2015-05-24 12:39 UTC
The end result is rather obvious, noticed this while I was looking for a good solid bg color for the whole page.

I assume this is not intended since .bg-primary goes out of its way to change the overall font color, which is curious since none of the other classes in this set behave in this way.

**Comment by cvrebert** [comment] 2015-05-24 19:12
Duplicate of #12860.

**Closed by cvrebert** 2015-05-24 19:12 UTC
Labels: css
