### ISSUE TITLE
.container within navbar undoes ability to use flexbox positioning

### ISSUE THREAD

**Issue by henwen** [twbs/bootstrap#21708] opened 2017-01-13 16:36 UTC
A stated goal of the Alpha6 `.navbar` is the ability to use flexbox to position items within. 

This works fine for elements that are immediate children of `.navbar` (the flex parent). However, when a `.container` is placed within `.navbar` (a common pattern), flexbox positioning is no longer an option because `.container` is not `display: flex`. 

One could manually add `d-flex` but that seems unintuitive when `display: flex` is presented as the assumed display context for navbars.

**Comment by davidtmiller** [comment] 2017-01-13 20:48
+1 I am seeing the same issue.

The left and right margins that are set to the container class are having some strange interaction with the navbar.

- Mac OS 10.12.2
- Chrome

Here is the issue in action:
![v4-alpha getbootstrap com- iphone 6 plus 1](https://cloud.githubusercontent.com/assets/8400627/21944968/c7386104-d9a6-11e6-9033-75786d68bda4.png)

If you go into the inspector and disable `margin-left: auto` and `margin-right: auto` on the `.container` class then things go back to normal on mobile, but this isn't a fix because it messes up the alignment of the container on larger screens where the container width is less than the screen width.

Here's what it looks like on mobile with the margins disabled though:
![v4-alpha getbootstrap com- iphone 6 plus 2](https://cloud.githubusercontent.com/assets/8400627/21945086/6316037e-d9a7-11e6-9f2e-4f8eac1a58b8.png)

It looks like if you disable the auto margins at <576px then the problem is remedied, but I'm not sure if there would be other consequences of doing so.

**Comment by henwen** [comment] 2017-01-13 20:56
@davidtmiller I believe you're experiencing [this issue](https://github.com/twbs/bootstrap/issues/21590), which also seems related to `container` being the only flex item within the navbar flex parent.

**Comment by davidtmiller** [comment] 2017-01-13 20:58
@henwen Yep that's the one...thanks!

**Comment by davidtmiller** [comment] 2017-01-13 21:10
Fixes in #21605

**Comment by vanduynslagerp** [comment] 2017-01-14 07:41
@davidtmiller, I think this is a different issue. What @henwen  report is that `.navbar` is `display: flex` and allow to position its content with flex, while `.container` is not `display: flex`.

Is it your actual issue @henwen ?

Although,  a `.container` within a `.navbar` is `display: flex`, but only at a breakpoint in which the navbar is expanded (i.e. no toggle button and all item visible). See [_navbar.scss#L155](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L155).

Indeed, a `.container` within a `.navbar` is not `display: flex` when the menu is collapsible (nav-item non visible in the top bar, toggle button visible).

Is what you trying to achieve is to position with flex the content of the container when the navbar is collapsible ?

**Comment by henwen** [comment] 2017-01-16 16:46
@vanduynslagerp yep, that's my actual issue, and it's the case regardless of whether the navbar is collapsible or not.

**Comment by mdo** [comment] 2017-01-21 22:38
I believe the container issue was fixed with #21722.

**Closed by mdo** 2017-01-21 22:38 UTC
Labels: css, v4
