### ISSUE TITLE
nav-tabs class active 2 times

### ISSUE THREAD

**Issue by incubux** [twbs/bootstrap#23946] opened 2017-09-13 20:23 UTC
sorry, I found the error, was in bootstrap 4 beta, does not disable and activates the active class in the nav-tabs correctly, then displays the contents of other tabs each one is selected a new one, thanks for your time

**Comment by Johann-S** [comment] 2017-09-14 07:51
IMO it's already in our dev dist files, but please submit a live example in a CodePen 👍

**Comment by Iworb** [comment] 2017-09-14 09:57
Well, I've met this behaviour too, but it works well in jsfiddle/codepen, but not in the project. I double checked about conflicts and found nothing and like topic author my problem is that 'active' class was not removed when tab switched. But if you try to switch tabs about 2-3 times for each one - it "repairs" it behaviour. I coul make a gif if you want to see what happening, but imo it won't help to determine where problem is.

**Comment by Johann-S** [comment] 2017-09-14 10:29
We had an issue with nested tabs, that's why I think this issue is already fixed but I have to be sure

**Comment by Iworb** [comment] 2017-09-14 10:58
It wasn't nested in my case.
![video_2017-09-14_135603](https://user-images.githubusercontent.com/6623262/30426448-c11fa746-9954-11e7-823a-56a7b3a4fc0e.gif)

**Comment by s4uron** [comment] 2017-09-14 12:47
Here you go:
https://jsfiddle.net/jw6vwv25/13/
But only the first time the "active" class from the first / initial item is not removed.
Regards :)

**Comment by Johann-S** [comment] 2017-09-14 12:58
sorry but I don't see your issue in your JSFiddle @s4uron the `active` class is removed each time
but here I want a live reproduction from @incubux

**Comment by browner12** [comment] 2017-09-14 12:59
can confirm, running BS4 Beta 1, and this happens when you have nested tabs.

If you only use one layer of tabs it all works fine.

https://github.com/twbs/bootstrap/pull/23087

**Comment by s4uron** [comment] 2017-09-14 13:07
@Johann-S which browser are you using? Tested with FF 55.0.3 and Chrome 60.0.3112.113.
1. Load the page
2. Switch to "Sent Notifications:"
3. Switch back to "Received Notifications:"
4. Voila: Both tables showing
![grafik](https://user-images.githubusercontent.com/3169056/30431257-529bdd62-995e-11e7-947d-edf236aca05e.png)

**Comment by Johann-S** [comment] 2017-09-14 13:23
ok saw it, but will be fixed in our next release see my CodePen which use our last dist file : https://codepen.io/Johann-S/pen/boNOdx

**Comment by browner12** [comment] 2017-09-14 13:30
i hate to be "that guy" but do we have a timeline for next release? I hope we don't get to the same point where it takes a bunch of people complaining to finally force the first Beta.

**Comment by Johann-S** [comment] 2017-09-14 13:34
Nobody forced us to ship the first beta, we shipped release when we think it's the good time, and they are no timeline for our next release, we are just volonteers which improve Bootstrap on their free-time but we hope to ship a new release soon

**Comment by s4uron** [comment] 2017-09-14 13:37
Works with https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.min.js 👍

**Comment by browner12** [comment] 2017-09-14 13:41
sorry, 'force' wasn't the right word, but there was definitely some frustration before the first Beta release. I think all people are looking for is a clear line of communication, or even just a road map on the things that need to be completed before the next release.

thanks for all you do!

**Comment by Johann-S** [comment] 2017-09-14 13:43
To track our progression until the next release you can use our project board see : https://github.com/twbs/bootstrap/projects/4

**Comment by incubux** [comment] 2017-09-14 22:45
Thanks to everyone for answering, I see that several people know what I mean, and so, codepen works well but not in my project, what Iworb says is true, the only way I managed to solve it was with this code
        $('a[data-toggle="tab"]').on('hidden.bs.tab', (e) => {
            var target = $(e.currentTarget).attr("href") // activated tab
            $(target).removeClass('active');
        });

**Comment by Johann-S** [comment] 2017-09-15 04:50
@incubux can you make a Codepen which reproduce the issue ? Without that we cannot make a fix

**Comment by incubux** [comment] 2017-09-15 04:56
it is exactly as he explained it Iworb and s4uron

**Comment by Johann-S** [comment] 2017-09-15 04:58
So I'll cose that issue because s4uron use case is already fixed 👍

**Closed by Johann-S** 2017-09-15 04:58 UTC
Labels: awaiting reply, js, v4
