### ISSUE TITLE
CSS files missing from bower.json

### ISSUE THREAD

**Issue by abrararies** [twbs/bootstrap#16712] opened 2015-06-26 07:15 UTC
The css files (to be injected) are missing from the "main" array in the bower.json (ver 3.3.5)

This is how it looks now
....
],
  "homepage": "http://getbootstrap.com",
  "license": "MIT",
  "moduleType": "globals",
  "main": [
    "less/bootstrap.less",
    "dist/js/bootstrap.js"
  ],
....

This was how it used to look
....
"homepage": "http://getbootstrap.com",
  "main": [
    "less/bootstrap.less",
    "dist/css/bootstrap.css",
    "dist/js/bootstrap.js",
    "dist/fonts/glyphicons-halflings-regular.eot",
    "dist/fonts/glyphicons-halflings-regular.svg",
    "dist/fonts/glyphicons-halflings-regular.ttf",
    "dist/fonts/glyphicons-halflings-regular.woff",
    "dist/fonts/glyphicons-halflings-regular.woff2"
  ],
....

Am I missing something here? There should be css files defined in there.
As far as I know, grunt or gulp use the main array to inject files into the project.

**Comment by cvrebert** [comment] 2015-06-26 08:49
Duplicate of #16663.

**Closed by cvrebert** 2015-06-26 08:49 UTC
