### ISSUE TITLE
"Choose file..." not being replaced with selected file name on File Input field (BS5-alpha2)

### ISSUE THREAD

**Issue by MontyHu** [twbs/bootstrap#31864] opened 2020-10-10 06:33 UTC
In Bootstrap v5, alpha 2, using the new File Input won't display the file name selected. I used this sample code from the v5 documentation: 

```
<div class="form-file">
  <input type="file" class="form-file-input" id="image_homepage" name="image_homepage">
  <label class="form-file-label" for="image_homepage">
    <span class="form-file-text">Choose file...</span>
    <span class="form-file-button">Browse</span>
  </label>
</div>
```

When I click on "Choose file..." then select a file, the form-file-text still shows "Choose file..." instead of being replaced with the name of the file chosen. This same issue is present in the file input sample on the Bootstrap 5 documentation site. https://v5.getbootstrap.com/docs/5.0/forms/file/

Hopefully this can be fixed to show the file name selected just like the standard HTML file input field.

**Comment by XhmikosR** [comment] 2020-10-12 06:13
Duplicate of #30265.

**Closed by XhmikosR** 2020-10-12 06:13 UTC
Labels: duplicate
