### ISSUE TITLE
without 2 rows in textarea height:auto with .form-group-lg in css

### ISSUE THREAD

**Issue by rubenscd** [twbs/bootstrap#15938] opened 2015-02-26 13:02 UTC
in
```
line:2759    textarea.form-group-lg .form-control,
line:2760    select[multiple].form-group-lg .form-control {
line:2761        height: auto;
line:2762    }
```
would be ?
```
line:2759   .form-group-lg textarea .form-control,
line:2760   .form-group-lg select[multiple] .form-control {
```
or ?
```
line:2759    textarea.form-group-lg.form-control,
line:2760    select[multiple].form-group-lg.form-control {
```

**Comment by kkirsche** [comment] 2015-02-26 18:46
I'm sorry but I don't understand what was said. Could you reword your issue so maybe I could better understand?

**Comment by mdo** [comment] 2015-02-26 19:19
He's pointing out the bug in our CSS where some improper nesting lead to the wrong compiled code. Dupe of #15074.

**Closed by mdo** 2015-02-26 19:19 UTC

**Comment by kkirsche** [comment] 2015-02-26 19:21
Ah ok. Thanks for the clarification there @mdo :smiley:
