### ISSUE TITLE
Navs don't work with ids containing '.'

### ISSUE THREAD

**Issue by azol** [twbs/bootstrap#21437] opened 2016-12-26 10:38 UTC
tested on v4.0.0-alpha.5

    
    <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#home" role="tab">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#profile.period" role="tab">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#messages" role="tab">Messages</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#settings" role="tab">Settings</a>
      </li>
    </ul>

    
    <div class="tab-content">
      <div class="tab-pane active" id="home" role="tabpanel">1</div>
      <div class="tab-pane" id="profile.period" role="tabpanel">2</div>
      <div class="tab-pane" id="messages" role="tabpanel">3</div>
      <div class="tab-pane" id="settings" role="tabpanel">4</div>
    </div>

profile.period -- doesn't work as expected, although period is a valid  ID: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

**Comment by mdo** [comment] 2016-12-26 21:49
Dupe of #18641 it seems.

**Closed by mdo** 2016-12-26 21:49 UTC
Labels: js, v4
