### ISSUE TITLE
Restore .glyphicon-door and .glyphicon-key in Bootstrap

### ISSUE THREAD

**Issue by PowerGamer1** [twbs/bootstrap#19846] opened 2016-05-05 07:24 UTC
@mdo, @cvrebert 
The `.glyphicon-door` and `.glyphicon-key` symbols were temporary disabled in Bootstrap due to their Unicode code points falling outside the BMP (see https://github.com/twbs/bootstrap/issues/15419). Since then both symbols have been reassigned to a BMP in the latest (1.9.2 as of this post) Glyphicons font: to UTF+E207 and UTF+E208 respectively (see http://glyphicons.com/). Can these icons be restored for use in bootstrap now please?

**Comment by mdo** [comment] 2016-05-08 21:49
Closing as dupe of #19836.

**Closed by mdo** 2016-05-08 21:49 UTC
Labels: css, v3
