### ISSUE TITLE
BS4 Documentation JS Error

### ISSUE THREAD

**Issue by swashcap** [twbs/bootstrap#18422] opened 2015-12-03 23:26 UTC
I get the following JS error on nearly all of the Bootstrap 4 Documentation pages:

```js
Uncaught ReferenceError: se is not defined
  (anonymous function) @ jekyll-search.js:1
```

* Browser: Chrome  47.0.2526.73
* OS: OS X 10.11.1
* URL: <http://v4-alpha.getbootstrap.com/getting-started/introduction/>

The file in question, [_jekyll-search.js_ on the `v4-dev` branch](https://github.com/twbs/bootstrap/blob/v4-dev/docs/assets/js/vendor/jekyll-search.js), does not appear to have `-se` appended like the live version. Could be a build step artifact?

**Comment by swashcap** [comment] 2015-12-03 23:31
I get a slightly different error, (but could be considered related) on the new v4 home page:

```js
Uncaught ReferenceError: se is not defined
  (anonymous function) @ jekyll-search.js:1
Uncaught Error: SimpleJekyllSearch --- You must specify a searchInputthrowError
  throwError @ jekyll-search.js:1
  validateOptions @ jekyll-search.js:1
  SimpleJekyllSearch.self.init @ jekyll-search.js:1
  (anonymous function) @ (index):228
```

* URL: <http://v4-alpha.getbootstrap.com/>

**Comment by swashcap** [comment] 2015-12-03 23:47
Confirmed that this issue doesn’t appear on the latest `v4-dev` (8a1685fdee8f01f041184948cf20dede54a2f4b3) when building the documentation locally.

¯\\\_(ツ)_/¯

**Comment by cvrebert** [comment] 2015-12-04 02:10
Duplicate of #17200. Please search more in the future. Thanks.

**Closed by cvrebert** 2015-12-04 02:10 UTC
Labels: docs, js, v4
