### ISSUE TITLE
navbar-fixed-top causes font styling changes in Safari 8

### ISSUE THREAD

**Issue by edwehrman** [twbs/bootstrap#16253] opened 2015-04-07 19:40 UTC
http://jsbin.com/sehozemoda/3/

Possible bug with Safari...
It seems like any JS action in a navbar-fixed-top causes font changes to occur. Does not happen in Chrome.

![screen shot 2015-04-07 at 12 40 02 pm](https://cloud.githubusercontent.com/assets/3008055/7031827/3c6f9a96-dd23-11e4-8dc3-68825bfd4cf7.png)
![screen shot 2015-04-07 at 12 40 09 pm](https://cloud.githubusercontent.com/assets/3008055/7031826/3c6d9520-dd23-11e4-887f-e96e4b83f094.png)

This is found with the base Bootstrap files downloaded today...

**Comment by edwehrman** [comment] 2015-04-07 20:22
Also, this is found with base Bootstrap downloaded today...

**Comment by cvrebert** [comment] 2015-04-08 00:25
Duplicate of #15199.

**Closed by cvrebert** 2015-04-08 00:25 UTC
Labels: confirmed, css
