### ISSUE TITLE
IE8 missing caret in dropdown

### ISSUE THREAD

**Issue by knbcoder** [twbs/bootstrap#16450] opened 2015-05-08 18:59 UTC
We first noticed this in our build but it seems to be an issue here as well, if you pull up the following page in IE8 the carets are gone, from what I've seen this goes for any item that is a dropdown. http://getbootstrap.com/javascript/#dropdowns

It's only happening in IE8 for us, anyone else notice this?

![image](https://cloud.githubusercontent.com/assets/12353403/7543479/3fae4eda-f58a-11e4-95d2-b7e6d7c6a326.png)

**Comment by cvrebert** [comment] 2015-05-08 20:01
Duplicate of #16172. Please search more next time!

**Closed by cvrebert** 2015-05-08 20:01 UTC
