### ISSUE TITLE
Checkout Example + Username field + Input Group + Border Right Radius

### ISSUE THREAD

**Issue by PerseusTheGreat** [twbs/bootstrap#26425] opened 2018-04-30 15:49 UTC
Hi,
In [Checkout](http://getbootstrap.com/docs/4.1/examples/checkout/) example page, there is a **`Username`** field.
As you know, it wrapped by **`div.input-group`**.
But, right border of input element has no rounded corners.
This situation also exists in [Official Docs / Components / Forms / Validation / Custom styles](http://getbootstrap.com/docs/4.1/components/forms/#custom-styles).

Image 1 - [Checkout](http://getbootstrap.com/docs/4.1/examples/checkout/) example page:
![checkout](https://user-images.githubusercontent.com/5496125/39436428-3305d5e4-4cb3-11e8-8bf1-fdd4fe4790e9.png)

Image 2 - [Official Docs / Components / Forms / Validation / Custom styles](http://getbootstrap.com/docs/4.1/components/forms/#custom-styles):
![forms](https://user-images.githubusercontent.com/5496125/39436446-3782d446-4cb3-11e8-95e5-8033b0bd15a1.png)

I am using:
- Windows 10 x64 - Ver. 1709 (OS build 16299.402)
- Microsoft Edge 16 (41.16299.402.0, EdgeHTML 16.16299)
- Microsoft Internet Explorer 11 (11.402.16299.0, Update 11.0.60)
- Mozilla Firefox 59.0.2 (64 bit)
- Google Chrome 66.0.3359.139 (Official Build) (64-bit)

So, please consider.
Thanks in advance.

**Comment by mdo** [comment] 2018-04-30 15:57
Duplicate of #25110.

**Closed by mdo** 2018-04-30 15:57 UTC
