### ISSUE TITLE
Click event won't work with data-bs-toggle

### ISSUE THREAD

**Issue by tguimmaraess** [twbs/bootstrap#33273] opened 2021-03-05 18:46 UTC
I'm not sure if someone else is running into this same issue, but it seems like onclick/click event doesn't work when I have data-bs-toggle in a `p` tag for example.

This don't work:

```
<p onclick="showAlert()" data-bs-toggle="dropdown">Show alert</p>

function showAlert(){
  alert("Alert");
}
```
But this works:

```
<p onclick="showAlert()">Show alert</p>

function showAlert(){
  alert("Alert");
}
```
Is there any way to access the click event with javascript and keep data-bs-toggle="dropdown"?

**Comment by rohit2sharma95** [comment] 2021-03-05 19:28
Thanks for reporting the issue @tguimmaraess
But it is a duplicate of #30267

**Closed by rohit2sharma95** 2021-03-05 19:28 UTC
Labels: duplicate

**Comment by rohit2sharma95** [comment] 2021-03-05 19:44
NVM, it may not be a duplicate actually but that's not the proper way of using `data-bs-toggle="dropdown"`

**Comment by tguimmaraess** [comment] 2021-03-05 21:43
You closed my issue without providing any details...I'm using `data-bs-toggle="dropdown"` in the proper way it's just that click events don't work with `data-bs-toggle`

**Comment by tguimmaraess** [comment] 2021-03-05 21:50
Thano you but that's just an example.  Dropdown is working but I need to add a click event too and it's not working.

**Comment by amdora** [comment] 2022-10-04 19:48
@tguimmaraess I am also having the same issue, have you found any solutions ???
