### ISSUE TITLE
Tippy tooltips integrate better with Bootstrap than Bootstrap tooltips

### ISSUE THREAD

**Issue by mcandre** [twbs/bootstrap#29220] opened 2019-08-06 19:42 UTC
Maybe Bootstrap should adopt Tippy tooltips, which integrate better with Bootstrap components such as modals, than Bootstrap tooltips! Tippy is also based on Popper, but resolves a lot of kinks around delay timers.

https://atomiks.github.io/tippyjs/customizing-tooltips/

**Comment by mdo** [comment] 2020-04-21 19:07
Thoughts from @Johann-S and @patrickhlauke on this one?

**Comment by patrickhlauke** [comment] 2020-05-04 00:14
at a very high level/quick test, these seem to be ok ... at least the docs say the right things about accessibility, for the most part

**Comment by XhmikosR** [comment] 2020-11-21 20:28
Closing as the issue is too vague.

**Closed by XhmikosR** 2020-11-21 20:28 UTC
Labels: js
