### ISSUE TITLE
Change dropdown menu position above (up) dropdown button if there are no enough space to the bottom of window

### ISSUE THREAD

**Issue by Mevrael** [twbs/bootstrap#19450] opened 2016-03-09 10:07 UTC
Like native selects are displayed at top of the input when height between input and window bottom corner is too small to show select items.

bs4 dropdown js should check for this condition too, if you have dropdown in footer, some options are otuside of screen. Below is my code you can adapt to your version.

```es6

document.addEventListener('DOMContentLoaded', () => {
    document.getElementsByClassName('dropdown').forEach((el) => {
        // get toggle button
        let btn = el.getElementsByClassName('dropdown-toggle')[0];
        // get menu
        let menu = el.getElementsByClassName('dropdown-menu')[0];

        // is dropdown menu style top changed
        let changed = false;

        // original dropdown menu style top
        let original_top = menu.style.top;

        // add event listener when dropdown toggles 'open' class
        new MutationObserver(function(mutations) {
            if (mutations[0].attributeName === 'class') {
                if (el.classList.contains('open')) {
                    // dropdown opened

                    // get space between btn bottom and window bottom corner
                    let height_to_end = window.innerHeight - btn.getBoundingClientRect().bottom;

                    // get menu height when it becomes visible in browser
                    let menu_height = menu.offsetHeight;
                    menu_height += 5;

                    // if menu_height > height_to_end - display menu up not down
                    if (menu_height > height_to_end) {
                        menu.style.top = '-' + menu_height + 'px';
                        changed = true;
                    }
                } else {
                    // dropdown closed

                    if (changed) {
                        // restore style only if it was changed
                        menu.style.top = original_top;
                        changed = false;
                    }
                }
            }
        }).observe(el, { attributes: true });
    });
});
```

**Comment by cvrebert** [comment] 2016-03-09 10:08
Approximate duplicate of #17167.

**Closed by cvrebert** 2016-03-09 10:08 UTC
Labels: feature, js, v4

**Comment by Mevrael** [comment] 2016-03-09 10:14
Not exactly the same, if you have right aligned dropdown there is `.dropdown-menu-right` for this, but you can't figure out how many items and how much space (y) to the end of viewport you will have.

However, since this option will require additional JS and checking coordinates, it could also check for x spacing and `.dropdown-menu-right` could be removed then.
