### ISSUE TITLE
Responsive Sidebar

### ISSUE THREAD

**Issue by vigneshksaithal** [twbs/bootstrap#32322] opened 2020-12-03 10:45 UTC
Why?
On mobiles, sidebar is more comfortable and in web apps we require fixed sidebars.

Ideas:
1. The navbar should be closed by default for mobile devices.
2. And it should be fixed(left/right) for destop sites.

**Comment by devhoussam** [comment] 2020-12-03 11:45
good idea

**Comment by XhmikosR** [comment] 2020-12-03 16:15
Duplicate of #24718

**Closed by XhmikosR** 2020-12-03 16:15 UTC
Labels: feature
