### ISSUE TITLE
Nav mobile button moves/messes layout when clicked, to the top and left

### ISSUE THREAD

**Issue by tomasts248** [twbs/bootstrap#32536] opened 2020-12-18 23:00 UTC
This is the original position: 
![151308_18122020](https://user-images.githubusercontent.com/32283036/102646785-6d760f00-4143-11eb-911d-27c2ce7c82dc.jpg)
and this is what happens when clicking the button
![151319_18122020](https://user-images.githubusercontent.com/32283036/102646859-8a124700-4143-11eb-852c-347fd7e3661e.jpg)
here is the code:
```
<nav class="navbar navbar-expand-lg navbar-light zbg-light" role="navigation">
	    
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContentMobile" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse text-center" id="navbarSupportedContentMobile">

				<ul class="navbar-nav">
                                    <!-- nav walker code -->

**Comment by mdo** [comment] 2020-12-18 23:03
Duplicate of #32532.

**Closed by mdo** 2020-12-18 23:03 UTC

**Comment by tomasts248** [comment] 2020-12-18 23:07
I would prefer to close the other post, since I get no replies at all there.
