### ISSUE TITLE
Responsive utility classes overlapping near breakpoint (ref: #20902)

### ISSUE THREAD

**Issue by bobrinch** [twbs/bootstrap#21031] opened 2016-10-27 20:37 UTC
Raised issue (#20902) has been closed, but I have some more input to help you reproduce the problem. Thus I have created this new issue with additional information. Hope that is alright.

It seems to me, that the responsive utility classes overlap at the breakpoints. If for example I have:

```
<div class="hidden-lg-down">
   This is XL
</div>
<div class="hidden-md-down hidden-xl-up">
   This is LG
</div>
```

Then, when making the browser the exact width of the breakpoint between xl and lg, I see both texts 

"This is XL" and "This is LG".

Same for LG-MD, MD-XS.

I am using Google Chrome latest version on Windows 7.

**Follow up:**

Please have a look at this JS Bin:

https://jsbin.com/sabedowija/edit?html,console,output

If you make the Output window exactly 1199 pixels in width, you will see:

This is XL
This is LG

You can also see it from the attached image below.

![styling-issue](https://cloud.githubusercontent.com/assets/4650307/19784377/d5013dae-9c95-11e6-8be6-2c701acefff1.png)

**Comment by mdo** [comment] 2016-10-27 21:04
This has to be some odd pixel rounding. I can't reproduce it in that example in Safari and Chrome on macOS. Any kind of browser zooming going on here or anything?

**Comment by bobrinch** [comment] 2016-10-28 05:53
I have no zooming set in the browser (Chrome/Windows).

By the way, I just checked with Firefox/Windows, and it also has the same issue when window is 1199 pixel in width.

**Comment by Piernas** [comment] 2016-11-16 13:00
I can reproduce this on Bootstrap 3.3.7. This code:

`<div class="container">
  <div class="row">
  <div class="visible-xs">XTRA-SMALL</div>
  <div class="visible-sm">SMALL</div>
  <div class="visible-md">MEDIUM</div>
  <div class="visible-lg">LARGE</div>
</div>`

doesn't work at 767px, 991px or 1199px width. Same happens with hidden-**

**Comment by mdo** [comment] 2016-11-28 21:51
Regrettably closing as a can't fix. We can't really do anything about this given the media queries don't have any overlapping boundaries—they go from 1px to the next. Overlapping them would create a brand new set  problems for us.

**Closed by mdo** 2016-11-28 21:51 UTC
Labels: css, v4
