### ISSUE TITLE
Can we add sm, md, lg & large to .no-gutters?

### ISSUE THREAD

**Issue by brettalton** [twbs/bootstrap#26249] opened 2018-04-10 17:57 UTC
I find when I'm making websites that I'll often want `.no-gutters` only on small screens, to keep a 3 column grid on small devices. This is dependent on the design of course, but I find it useful.

Can we look at adding `.no-gutters-sm`, `.no-gutters-md`, `.no-gutters-lg` and `.no-gutters-xl` to use this Bootstrap-specific property with breakpoints?

Current: https://getbootstrap.com/docs/4.0/layout/grid/#no-gutters
Notation with breakpoints: https://getbootstrap.com/docs/4.0/utilities/spacing/#notation

**Comment by LarryAzevedo** [comment] 2018-04-30 16:09
Technically, Bootstrap does **not** need the `.no-gutters` class.  You could just use the [spacing classes](https://getbootstrap.com/docs/4.0/utilities/spacing/).  But I know what you're saying, it's easier to just have to type into one class attribute.

**Comment by XhmikosR** [comment] 2018-05-22 22:46
Duplicate of #26249

**Closed by XhmikosR** 2018-05-22 22:46 UTC
Labels: css, feature, v4

**Comment by kailynnelson** [comment] 2019-10-28 23:31
> Technically, Bootstrap does **not** need the `.no-gutters` class. You could just use the [spacing classes](https://getbootstrap.com/docs/4.0/utilities/spacing/). But I know what you're saying... it's easier to just type into one class attribute.

@LarryAzevedo, I've used your solution before in most cases. But we have a case where we want to keep gutters on most screens, but then only on sm hide the gutters. Instead of using a media query and setting margin-left: 0; and margin-right: 0; I'd like to use a Bootstrap class.

**Comment by martinkariuki7** [comment] 2019-11-26 14:49
Yes! Please add this :)

**Comment by pepebe** [comment] 2020-04-23 15:48
Jumping on the bandwagon. I also don't see how spacing classes can solve the problem with the needed negative margin on the row element as there is not css class available putting a negative margin on an element.

**Comment by ffoodd** [comment] 2020-04-23 15:56
@pepebe You may want to look closer at the documentation: https://getbootstrap.com/docs/4.4/utilities/spacing/#negative-margin

**Comment by pepebe** [comment] 2020-04-24 15:36
@ffoodd Totally missed that one. Thanks!

```
.mt-n1 {
  margin-top: -0.25rem !important;
}
```

**Comment by ProxyJoshua** [comment] 2020-07-15 18:11
u could use 
`<div class="px-0 px-sm-3"></div>`
p3=1rem
