### ISSUE TITLE
v4 btn-group with data-toggle="buttons" eats events

### ISSUE THREAD

**Issue by pg1671** [twbs/bootstrap#20770] opened 2016-09-22 22:29 UTC
With version 4 alpha 4 if you use a btn-group with data-toggle="buttons" any events fired cannot be handled outside the control.

The behaviour works correctly if you switch the v4 javascript for v3.

markup is:
```
<div class="btn-group" data-toggle="buttons">
    <label class="btn btn-primary active">
        <input type="radio" name="pricingperiod" id="monthly" autocomplete="off"> Monthly
    </label>
    <label class="btn btn-primary">
        <input type="radio" name="pricingperiod" id="yearly" autocomplete="off"> Annual
    </label>
</div>
```

I am using backbone events and am checking for a change:
            "change input[type=radio]": "onPeriod"

Which never gets handled under v4 but does under v3.

**Comment by cvrebert** [comment] 2016-09-23 05:03
Duplicate of #17599.

**Closed by cvrebert** 2016-09-23 05:03 UTC
