### ISSUE TITLE
BootstrapCDN (CSS) link on homepage covered with scrollbar. Can't copy the link.

### ISSUE THREAD

**Issue by Kerrys7777** [twbs/bootstrap#28498] opened 2019-03-14 22:44 UTC
I go to the BS Homepage to grab the CSS CDN path but it is covered with the horizontal scrollbar (caused by overflow x) so I can't highlight the text to copy and paste it. I am on Mac with Chrome browser.

Could you please add some padding to:
```
.highlight pre {
    padding: 2rem 0;
}
```

Thanks,
<img width="780" alt="screenshot-issue-cant-highlight-cdn-link-path" src="https://user-images.githubusercontent.com/13267982/54396397-ef334000-4706-11e9-8094-667c2700abbd.png">
Kerry

**Comment by XhmikosR** [comment] 2019-03-16 17:51
I think this is a "recent" regression. I'll have to check git log to pinpoint this.

**Comment by Kerrys7777** [comment] 2019-03-18 11:41
Hi XhmikosR,
I think this defect has been evident for a fair while but it made me angry enough (the other day) to log the minor issue. Hehe.
Thanks again,
Kerry

**Comment by XhmikosR** [comment] 2019-03-18 11:53
@mdo @MartijnCuppens since you guys are on macOS, can you check this? For me it doesn't happen on Windows with Chrome nor Firefox.

**Comment by patrickhlauke** [comment] 2019-03-18 12:24
I can confirm this - Safari and Firefox are fine, but Chrome's scrollbar (triggered by the `overflow: auto` when hovering the thing/trying to select) is horrid and indeed blocks actual text selection.

**Comment by patrickhlauke** [comment] 2019-03-18 12:26
could either add more vertical padding (just to appease Chrome/macOS), turn this into a read-only text input with no borders (not tested, but that SHOULD work i think), or add an explicit "Copy" button next to it...

**Comment by MartijnCuppens** [comment] 2019-03-18 12:30
Yup, I can confirm. Adding a copy button (like we did here: https://getbootstrap.com/docs/4.3/getting-started/introduction/) could indeed help us out.

**Comment by XhmikosR** [comment] 2019-03-18 12:40
I think not adding a copy button in the homepage snippets was done on purpose, though. Not my choice, probably @mdo's, so he might know why :P

**Comment by mdo** [comment] 2020-05-14 06:37
Fixed in v4.5.0.

**Closed by mdo** 2020-05-14 06:37 UTC
Labels: docs, v4, v5
