### ISSUE TITLE
A problem with floating labels

### ISSUE THREAD

**Issue by ale-lit** [twbs/bootstrap#36620] opened 2022-06-21 15:08 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When filling in the field for several lines, there is an overlap of the label

https://getbootstrap.com/docs/5.2/forms/floating-labels/#textareas

![изображение](https://user-images.githubusercontent.com/91823697/174834222-0f10fb51-8f8e-4c83-b84e-717107ea57da.png)

![изображение](https://user-images.githubusercontent.com/91823697/174834663-470b9998-7a47-45ec-9035-90f6580619df.png)

### Reduced test cases

https://getbootstrap.com/docs/5.2/forms/floating-labels/#textareas

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.2

**Comment by alecpl** [comment] 2022-06-22 18:07
Duplicate of #32800.

**Comment by julien-deramond** [comment] 2022-06-22 18:13
Indeed this is a duplicate. Thanks @alecpl. @ale-lit, thanks for reporting this issue, you can subscribe to #32800 to follow the topic. I'm closing this one.

**Closed by julien-deramond** 2022-06-22 18:13 UTC
