### ISSUE TITLE
Add Scrollbar Customisation to docs

### ISSUE THREAD

**Issue by EWZPraktikant** [twbs/bootstrap#38925] opened 2023-07-18 10:37 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Please make the documentation more clear on how to style Scrollbars.

You could add a Subheadline to https://getbootstrap.com/docs/5.3/utilities/overflow/ at the very end of the page that tells you how to style the scrollbar.

### Motivation and context

I recently looked for a way to style my scrollbars with Bootstrap, but I couldn't find anything. Not even the search function in the documentation was giving me anything. Maybe I just didn't see it or missed it somehow, but all I could find was this: https://github.com/twbs/bootstrap/issues/37710

I think it could help others with the same problem, find a faster sollution then I did.

**Comment by julien-deramond** [comment] 2023-07-18 11:08
Closing it as a duplicate of https://github.com/twbs/bootstrap/issues/31100. We'll double-check in v6 when we change our browser support whether it can be done.

**Closed by julien-deramond** 2023-07-18 11:08 UTC
Labels: feature
