### ISSUE TITLE
Error of tooltip bootstrap v5.0.0-beta1 (not load in the first hover and error when hovering in & out many times

### ISSUE THREAD

**Issue by phangia2712** [twbs/bootstrap#32982] opened 2021-02-04 09:49 UTC
I using Chrome lastest in Window 10, i meet the error when using tooltop for span tag:
- Hover in the first time, tootip not load.
- Hover in & out on span many times, position of tooltip show wrong.

This is my code:
`<span id="job-help-tooltip" class="help-icon" title="<strong>#Detailed description of an Add Job</strong>
                            <span>
                            Machine learning jobs can be created based on multiple pre-made scenarios. Recommended for beginner users.
                            </span>
                            <span>
                            Advanced users can personalize/optimize machine learning tasks by entering algorithms and plurals themselves.</span>"></span>`

`var exampleEl = document.getElementById('job-help-tooltip')
        var tooltip = new bootstrap.Tooltip(exampleEl, {
            container: 'body',
            html: true,
            placement: 'top',
            trigger: 'hover',
            customClass: 'job-help-tooltip',
        })`

See video below:
https://www.awesomescreenshot.com/video/2633512?key=45489ef7e53240dfe3ac0a4bbaa230b1

**Comment by Didldu-Florian** [comment] 2021-02-04 11:49
Same here

**Comment by rohit2sharma95** [comment] 2021-02-06 13:26
@phangia2712 Can you please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link. :slightly_smiling_face:

**Comment by filiplikavcan** [comment] 2021-02-08 16:19
@rohit2sharma95  https://jsbin.com/qegopeneti/edit?html,js,output

Tested on:
- Chrome Version 88.0.4324.146 (Official Build) (x86_64) on macOS(11.1 (20C69))
- Safari Version 14.0.2 (16610.3.7.1.9) on macOS(11.1 (20C69))

In addition to @phangia2712 report sometimes the tooltip stops working at all (nothing shows when hovering over).

**Comment by henryschmieder** [comment] 2021-02-08 22:55
same here

**Comment by mznet** [comment] 2021-02-09 02:26
In addition to @filiplikavcan comment, this case can be easily reproduced wherever there is a tooltip component even on [Tooltip example docs](https://getbootstrap.com/docs/5.0/components/tooltips/#examples). As hovering in & out "fast" few times, it can be reproduced.

![Feb-09-2021 11-24-18](https://user-images.githubusercontent.com/9622730/107307172-8ce94280-6ac9-11eb-8084-b9a76a9d5962.gif)

**Comment by XhmikosR** [comment] 2021-02-09 12:55
Duplicate of #32372

**Closed by XhmikosR** 2021-02-09 12:55 UTC
Labels: awaiting-reply
