### ISSUE TITLE
Include source js files in package (v4)

### ISSUE THREAD

**Issue by saviomd** [twbs/bootstrap#19075] opened 2016-02-03 14:04 UTC
If i use bootstrap v4alpha2 as an npm dependency, the pre-concatenated js files don't exist.
(this worked in 3.3.6 and I used it to build a custom js file with only the modules I needed)

From what I can see, the folder structure changed from v3 to v4, so this line in package.json (69 in v3 and 76 in v4):
```
"js/*.js",
```
should be
```
"js/dist/*.js",
```

**Comment by cvrebert** [comment] 2016-02-03 20:14
Duplicate of #18934.

**Closed by cvrebert** 2016-02-03 20:14 UTC
