### ISSUE TITLE
Printing in IE11 and Firefox is blank after page 1

### ISSUE THREAD

**Issue by DM2489** [twbs/bootstrap#26781] opened 2018-06-29 13:24 UTC
Printing in IE11 is broken after the first page, displaying no content.

Chrome:
![chrome-1](https://user-images.githubusercontent.com/40390596/42094539-0183a13a-7ba8-11e8-9a32-f25bfa9540ea.PNG)
![chrome-2](https://user-images.githubusercontent.com/40390596/42094536-013eca2e-7ba8-11e8-9ee8-9d209f3160c0.PNG)

IE11: 
![ie11-1](https://user-images.githubusercontent.com/40390596/42094537-01557238-7ba8-11e8-9bb2-c53e7a05c5a5.PNG)
![ie11-2](https://user-images.githubusercontent.com/40390596/42094538-016e9f92-7ba8-11e8-8f98-3e97ae90b7f1.PNG)

**Comment by stephenhillier** [comment] 2018-06-29 17:50
I came here to post the same issue, as our users reported not being able to print using IE. In addition to Internet Explorer, I also have this issue in Firefox 60 on Mac OSX: I can reproduce it on my end by trying to print https://getbootstrap.com/docs/4.1/getting-started/introduction/

**Comment by DM2489** [comment] 2018-07-02 10:28
I think this issue is linked to https://github.com/twbs/bootstrap/issues/23489.

**Comment by DM2489** [comment] 2018-07-20 15:10
Anyone?

**Comment by DM2489** [comment] 2018-08-01 12:52
@mdo Can this be looked into, pretty please?

**Comment by DM2489** [comment] 2018-12-03 10:53
This is still an issue. Can someone assist please?

**Comment by daniele-athome** [comment] 2019-08-16 14:01
> 
> 
> I'm having the same issue! It is caused by `display: flex;`
> 
> So you'll need to add d-print-block to all your flex elements, or add something like this in an **@ print** media selector:
> 
> ```
>   .row,
>   .any-custom-class-that-uses-flex {
>     display: block !important;
>   }
> ```

Too bad that it breaks anything else inside the div...

**Comment by ysds** [comment] 2020-03-17 03:57
This is a browser bug. Unfortunately there is no general way to solve. There are [some workarounds](https://github.com/twbs/bootstrap/issues/26781#issuecomment-522019523), those are incompletely but may help for some cases.

Also please see:
https://bugzilla.mozilla.org/show_bug.cgi?id=939897

Sorry but closing this since we can't fix.

**Closed by ysds** 2020-03-17 03:57 UTC
Labels: browser bug, print, v4
