### ISSUE TITLE
[v4] sub/sup element inside input-group-addon is wrong

### ISSUE THREAD

**Issue by steve3d** [twbs/bootstrap#23170] opened 2017-07-28 09:01 UTC
please see this jsfiddle, in bootstrap v4, `sub`/`sup` elements inside a `input-group-addon` are placed at wrong position. but all other position is correct.

https://jsfiddle.net/pta5mn5u/1/

is there a quick fix for this?

**Comment by alecpl** [comment] 2017-07-28 12:01
This is caused by display:flex on .input-group-addon

**Comment by steve3d** [comment] 2017-07-28 17:20
@alecpl  huge thanks for this information!

**Comment by utkarshkukreti** [comment] 2017-07-29 08:03
@steve3d A quick fix would be to wrap the text and the sup/sub in a span:

    <span class="input-group-addon">M<sup>3</sup></span>

->

    <span class="input-group-addon"><span>M<sup>3</sup></span></span>

**Comment by mdo** [comment] 2017-08-22 01:35
Was fixed in Beta 1. https://jsfiddle.net/oxb2x4er/

**Closed by mdo** 2017-08-22 01:35 UTC
Labels: css, v4
