### ISSUE TITLE
Ability to change css focus outline style in buttons, forms etc.

### ISSUE THREAD

**Issue by Tauhid8k** [twbs/bootstrap#31061] opened 2020-06-17 05:44 UTC
Most of the bootstrap component has blue Outline focus style. At least add a class as an optional to be able to remove the outline thik focus border. Not the thin border. The outline thik border. Sometime it looks odd! for example in group buttons or group forms.  [check here](https://v5.getbootstrap.com/docs/5.0/forms/input-group/)

**Comment by Tauhid8k** [comment] 2020-06-17 05:54
![IMG_20200617_114208](https://user-images.githubusercontent.com/57229427/84860663-4ace4500-b091-11ea-9413-1d6bf249437e.jpg)
![IMG_20200617_113907](https://user-images.githubusercontent.com/57229427/84860674-502b8f80-b091-11ea-9ce3-8266bcaba2be.jpg)

**Comment by florianlacreuse** [comment] 2020-06-17 13:03
You can override `$input-btn-focus-box-shadow`.

**Comment by mdo** [comment] 2020-06-17 16:01
This is by design with our buttons and for now will stay the same. We've been discussing if we can do something else for a focus right that will provide better contrast, but haven't committed to any particular direction yet.

**Closed by mdo** 2020-06-17 16:01 UTC
Labels: css, feature
