### ISSUE TITLE
Incorrect image scaling on carousel slide in MS Edge

### ISSUE THREAD

**Issue by sanusart** [twbs/bootstrap#16915] opened 2015-07-30 19:16 UTC
![image](https://cloud.githubusercontent.com/assets/267718/8992664/a747ac74-36b4-11e5-8b8f-6399de8faa1d.png)

**Comment by sanusart** [comment] 2015-07-30 19:40
Seems like changing `max-width: 100%` to `width: 100%` [here](https://github.com/twbs/bootstrap/blob/b8bc20432f93385989291f2a67112e29b97de682/dist/css/bootstrap.css#L1125) fixing it.

**Comment by cvrebert** [comment] 2015-07-30 20:01
Tweeted to @jonathansampson, since this seems Edge-specific: https://twitter.com/cvrebert/status/626844607972831232

**Comment by cvrebert** [comment] 2016-01-23 10:05
Since [carousel images mix-in `.img-responsive`](https://github.com/twbs/bootstrap/blob/7e0cac1b47a71dfdf2636242323bbff332b66ac5/less/carousel.less#L24) and since Holder.js uses SVG internally, we might actually be hitting http://getbootstrap.com/css/#callout-images-ie-svg

https://github.com/twbs/bootstrap/issues/10073#issuecomment-44956296 and #16782 suggest that that bug might apply to IE11 too, and if that's true then it's plausible it could apply to Edge too.

**Comment by cvrebert** [comment] 2016-01-23 10:26
Hmm, my speculation is looking unlikely.
However, I did manage to craft a simple testcase that shows Edge rendering SVGs with `max-width:100%` differently than IE11/Firefox/Chrome/Safari, which seems to be the underlying bug here:
http://jsbin.com/tiyuda/edit?html,css,output

**Comment by twbs-lmvtfy** [comment] 2016-01-23 10:26
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/tiyuda/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment] 2016-01-23 10:46
Filed Edge bug: https://connect.microsoft.com/IE/feedback/details/2274240/edge-edge-renders-an-svg-img-with-max-width-100-too-small

**Comment by cvrebert** [comment] 2016-01-23 10:54
Added to the Wall of Browser bugs in #19010.

**Comment by cvrebert** [comment] 2016-01-26 19:42
@sanusart @XhmikosR @patrickhlauke Can someone test http://embed.plnkr.co/iuiKDC2HIkvov9ALb5vS/ in Edge 10586 please? The interstate sign and the green square should be basically the same size. The Edge folks say the bug has been fixed in the latest version (10586).

**Comment by twbs-lmvtfy** [comment] 2016-01-26 19:42
Hi @cvrebert!

You appear to have posted a live example (http://run.plnkr.co/plunks/iuiKDC2HIkvov9ALb5vS/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by XhmikosR** [comment] 2016-01-26 19:48
I don't have Edge installed on my dev rig, so I will try tomorrow from another machine and let you know.

**Comment by patrickhlauke** [comment] 2016-01-26 20:27
confirmed that it's fixed in 25.10586.0.0

> ![capture](https://cloud.githubusercontent.com/assets/895831/12593869/24844dc0-c46b-11e5-8293-b9c5fee429ff.PNG)

**Comment by cvrebert** [comment] 2016-01-26 20:31
Thanks!

**Closed by cvrebert** 2016-01-26 20:31 UTC
Labels: browser bug, css, v3

**Comment by cvrebert** [comment] 2016-01-26 20:39
Updated the Wall accordingly in 701b4679941f54120bde22a4f6d240d2bac835cd.

**Comment by sanusart** [comment] 2016-01-26 21:26
Great news! Thanks.
