### ISSUE TITLE
Dropdown Not on TOP?

### ISSUE THREAD

**Issue by cgountanis** [twbs/bootstrap#25850] opened 2018-03-14 21:31 UTC
Any quick solution for something like this?

https://jsfiddle.net/bshasvbp/3/

**Comment by jipexu** [comment] 2018-03-14 21:39
humm... it is a old very long post (issue)  for this context .. but as long as i remember is not quick solution ...

**Comment by thatnini** [comment] 2018-03-14 22:42
What about adding `data-boundary="viewport"` to your button?

[https://jsfiddle.net/bshasvbp/12/](https://jsfiddle.net/bshasvbp/12/)

[https://getbootstrap.com/docs/4.0/components/dropdowns/#options](https://getbootstrap.com/docs/4.0/components/dropdowns/#options)

**Comment by cgountanis** [comment] 2018-03-14 22:51
@thatnini you might be my new favorite person right now. I think that'll work I need to test it but that is much easier than I thought.

**Comment by mdo** [comment] 2018-03-15 06:14
Closing as not a bug. Thanks, y'all!

Let me know if this is something we need to improve in our docs though and we can open a new issue or PR to start that.

**Closed by mdo** 2018-03-15 06:14 UTC

**Comment by cgountanis** [comment] 2018-03-15 14:14
The only issue I have found is when in responsive mode (FireFox) the scroll bar is over the menu. Is this normal?

![image](https://user-images.githubusercontent.com/14899817/37468522-47d00e6e-2831-11e8-9ca8-f3dcef3d1b41.png)
