### ISSUE TITLE
HTML5 Color picker is broken

### ISSUE THREAD

**Issue by juancolacelli** [twbs/bootstrap#22909] opened 2017-06-26 13:28 UTC
- Operating system: macOS Sierra 10.12.5 (16F73)
- Browser: Google Chrome 58.0.3029.110 (64-bit)
- Bootstrap: v4.0.0-alpha.6

If I remove the class "form-control" from the input, it works as intended, but with the class the input just looks like a line.

You can reproduce it even in the samples page: https://v4-alpha.getbootstrap.com/components/forms/#textual-inputs

**Comment by juancolacelli** [comment] 2017-06-26 13:34
I forgot to mention that the line doesn't even change color.

**Comment by juancolacelli** [comment] 2017-06-26 13:38
I tried and it works on Mozilla Firefox 54.0 (64-bit) but in Safari 10.1.1 (12603.2.4) it looks just like a input text (I think Safari doesn't support color pickers yet).

**Comment by mdo** [comment] 2017-06-26 15:11
Closing as duplicate of #18786.

**Closed by mdo** 2017-06-26 15:11 UTC
Labels: css, v4
