### ISSUE TITLE
Migrate from Popper 1.x to 2.x

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#31896] opened 2020-10-14 14:36 UTC
Migrate from [Popper](https://popper.js.org/) 1.x to 2.x.

Maybe this can be done for Bootstrap 5?

https://popper.js.org/docs/v2/migration-guide/

**Comment by mdo** [comment] 2020-10-14 16:45
Duplicate of #29842.

**Closed by mdo** 2020-10-14 16:45 UTC
Labels: feature
