### ISSUE TITLE
In a modal, a form-select with floating label is misaligned and has wrong width

### ISSUE THREAD

**Issue by lcsqlpete** [twbs/bootstrap#37569] opened 2022-11-30 18:41 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Please see the Codepen below for a test case.

I have included the select twice in this Codepen. The instance immediately below the Location Name field displays correctly.  The instance below the Track and Ceiling inputs display incorrectly.  It's left edge is slightly out of line with the other elements above it and its width is shorter than the instance that displays correctly even though they both have the same column and offset definitions.

### Reduced test cases

https://codepen.io/lcsqlpete/pen/vYrzVLw

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by julien-deramond** [comment] 2022-11-30 18:53
Hey @lcsqlpete 
Just took a look very quickly (I'll get back to it after depending on your answer).
1. If I take the `<form>` code and display it outside the modal, the issue remains so I think it is not related to the modal
2. The issue isn't here because your `<div class="row">` (line 75) should be closed at line 104 (just before the other `<div class="row">` containing the `<select>`?

**Comment by lcsqlpete** [comment] 2022-11-30 19:28
Thanks for spotting that.  I ran the code though the codepen analyze function when I posted it but it didn;t spot that.  I add ed the closing div tag and now all looks fine.

**Comment by julien-deramond** [comment] 2022-11-30 19:34
Sure no problem. So I'm closing it since the issue seems to be resolved.

**Closed by julien-deramond** 2022-11-30 19:34 UTC
Labels: awaiting-reply, v5
