### ISSUE TITLE
Bower install individual components

### ISSUE THREAD

**Issue by gdcohan** [twbs/bootstrap#16105] opened 2015-03-18 18:58 UTC
Hey--

I was wondering if it's possible to make individual components available via bower (i.e. modal, dropdown, etc.). 

Thanks!
Greg

**Comment by zacechola** [comment] 2015-03-18 20:43
Are you asking just for the JS components or for the corresponding CSS, as well?

**Comment by cvrebert** [comment] 2015-03-18 20:45
Duplicate of #11569.

**Closed by cvrebert** 2015-03-18 20:45 UTC

**Comment by gdcohan** [comment] 2015-03-19 01:08
I think either is reasonable...what's stopping us from doing this until v4, though?

**Comment by kkirsche** [comment] 2015-03-19 01:16
@gdcohan v3 is essentially frozen in regards to major changes such as this. By truly separating components and allowing distribution separately I believe it would either lead to large amounts of duplication or would require a major code base restructure which isn't worth the potential bugs at this point.

**Comment by gdcohan** [comment] 2015-03-19 01:28
@kkirsche: would ppl be opposed to someone else maintaining a bower version of an individual component (no code changes or support required)

**Comment by kkirsche** [comment] 2015-03-19 01:41
I can't speak for the project but I think it would be ok and some people would probably appreciate it, it just wouldn't be officially backed by the team as it would be a third party repo.

**Comment by cvrebert** [comment] 2015-03-19 01:43
Well, Bootstrap is MIT and CC-BY licensed, so folks are free to do those sorts of things. Whether the Core Team would officially endorse such an initiative would be another matter.
[Edit: Dammit mobile! Yeah, basically what @kkirsche said.]

**Comment by zacechola** [comment] 2015-03-19 14:59
X-Refs: #14064, #14265, #11569. There are others, I'm sure.

fwiw, I'm not necessarily for modularizing each component/script as a bower component. I think much of this can and should be handled in the build step and not necessarily be married to a package management system. There are lots of ways to make it all more modular, but as has been said several times it's a good discussion for 4.0.
