### ISSUE TITLE
Custom builds links

### ISSUE THREAD

**Issue by avradul** [twbs/bootstrap#19671] opened 2016-04-04 08:34 UTC
On page
http://v4-alpha.getbootstrap.com/getting-started/download/
links Reboot, Grid only, Flexbox are broken - href="#".

http://i.imgur.com/qSWksCi.png

**Comment by RyanZim** [comment] 2016-04-04 14:07
Possible Duplicate of  #18568.

**Comment by cvrebert** [comment] 2016-04-04 19:23
Closing per @RyanZim

**Closed by cvrebert** 2016-04-04 19:23 UTC
Labels: docs, v4
