### ISSUE TITLE
input select (multi): underlying options are visible cause of syle overflow:visible;

### ISSUE THREAD

**Issue by djot** [twbs/bootstrap#20508] opened 2016-08-12 09:39 UTC
Ok, found this issue later (which is more or less the same):
https://github.com/twbs/bootstrap/issues/20384

input select has style `overflow:visible;` 
    in https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css:6
which causes e.g. multiple select options to show if you have more options than `size="x"`

```
<select name="foo" multiple="multiple" size="3">
<option value="3">1</option>
<option value="3" selected="selected">2</option>
<option value="3">3</option>
<option value="3">4</option>
<option value="3">5</option>
</select>
```

![multi](https://cloud.githubusercontent.com/assets/1754128/17618858/4bf28ab2-6082-11e6-896c-06f54f2e1d98.gif)

Sys: Windows 10 Insider Preview, Chrome Version newest

**Comment by wolfy1339** [comment] 2016-08-12 21:35
This is due to Normalize

**Comment by cvrebert** [comment] 2016-08-13 00:00
Duplicate of #20384.

**Closed by cvrebert** 2016-08-13 00:00 UTC
