### ISSUE TITLE
Nested accordions do not seem to be working

### ISSUE THREAD

**Issue by afgarcia86** [twbs/bootstrap#19309] opened 2016-02-24 21:57 UTC
I have a nested accordion, however it seems to collapse the parent instead of the nested element.

see example: https://jsfiddle.net/mk02wdpa/

**Comment by Johann-S** [comment] 2016-02-24 23:13
Maybe related to : https://github.com/twbs/bootstrap/issues/18824

**Comment by mdo** [comment] 2016-10-23 21:45
Closing as dupe of #18632.

**Closed by mdo** 2016-10-23 21:45 UTC
Labels: js, v4
