### ISSUE TITLE
Nav Document Outline

### ISSUE THREAD

**Issue by chrisbo** [twbs/bootstrap#25881] opened 2018-03-17 19:15 UTC
Noticed in the nav examples that `<h6>` is being used for a dropdown header which gives a nav document outline of

![capture](https://user-images.githubusercontent.com/5879776/37559080-9d924512-2a73-11e8-8f45-43d035bfd4ac.PNG)

Thoughts?

**Comment by andresgalante** [comment] 2018-04-06 11:54
Hi @chrisbo I couldn't find it here: http://getbootstrap.com/docs/4.0/examples/navbars/

Can you send me the URL where you found it please?

**Comment by mdo** [comment] 2018-04-07 21:02
There's an `<h6>` in our `dropdowns.md` file @andresgalante. I'm unsure what the screenshot is from, but it seems to be unrelated to our code :).

**Comment by chrisbo** [comment] 2018-06-22 14:03
@andresgalante Just bumped into an example in the documentation:

[https://getbootstrap.com/docs/4.0/components/dropdowns/#menu-headers]

An `<h6>` shouldn't be used for styling.

**Comment by XhmikosR** [comment] 2018-10-21 08:39
BTW this was caused by the workaround we had to use so that unrelated ToC entries weren't added. This issue is now fixed and we can safely use whatever header we want to. It's just that we don't have a list so it's hard to find these.

**Comment by avikranj1** [comment] 2018-11-21 18:57
As per my knowledge normally we do not use h6 for styling headline or even nav dropdown. But it depends on the designer.

**Comment by XhmikosR** [comment] 2019-02-06 15:21
What should we do about callouts though?

/CC @patrickhlauke

**Comment by XhmikosR** [comment] 2019-02-06 16:29
Ok I made a [branch](https://github.com/twbs/bootstrap/compare/v4-dev-xmr-docs-headers). While there are some good cases this can be fixed, there are others, namely some examples, that this will cause an extra class.

Also, the current ToC plugin will include some of the new headers. This will be fixed when we switch to Hugo though.

I'm not sure how to proceed.

**Comment by patrickhlauke** [comment] 2019-02-06 20:07
as mentioned before, having heading level gaps is not ideal...but nobody really dies from that. if we can't rewrite heading levels on the fly for things that get included (callouts) to have the appropriate level, then having those at `<h6>` is the lesser evil (it would at least guarantee they're always subordinate to whatever heading comes hierarchically above it/the section they're in, assuming those only go to `<h5>` at the most)

**Comment by XhmikosR** [comment] 2019-02-06 20:20
I'm actually more concerned about the examples. See the above diff.

**Comment by patrickhlauke** [comment] 2019-02-07 00:37
this is where the semantics of HTML aren't quite sufficiently expressive...you'd really want to be able to somehow demarcate those example bits of code as something that doesn't *really* pertain to the overall page structure...

but, as that's not possible, i'd say those are fine as per the diff. Once these don't show up in the TOCs either, it's probably as good as they can be made...

**Comment by XhmikosR** [comment] 2020-11-21 13:08
@patrickhlauke do we close this one?

**Comment by patrickhlauke** [comment] 2020-11-21 14:32
yup, i'd say close

**Closed by patrickhlauke** 2020-11-21 14:32 UTC
Labels: examples, help wanted, v4
