### ISSUE TITLE
Bring back wells, thumbnails, and panels

### ISSUE THREAD

**Issue by SachinAgarwal1337** [twbs/bootstrap#17741] opened 2015-09-30 17:51 UTC
I suggest make wells, thumbnails, and panels deprecated. Because it may break the UI when updated to v4 if those are widely used in the UI and forget to update at some places. Plus I even have custom styling for those in my UI, others may have it too. So it will be better to have them for now beside cards.

**Comment by cvrebert** [comment] 2015-09-30 21:12
Approximate duplicate of #17240.

**Closed by cvrebert** 2015-09-30 21:12 UTC
Labels: css, feature, v4
