### ISSUE TITLE
AMD module wrapping by default

### ISSUE THREAD

**Issue by kriskate** [twbs/bootstrap#16519] opened 2015-05-21 11:46 UTC
It would be nice to have a similar functionality to **jquery-ui**'s, meaning that the package should check for the ***define*** function, and act as an AMD module if found... 

I spent around 2 hours figuring out why jquery-ui's widgets were not overwritten by bootstrap's (eg: **tooltip**)... it was because my ***grunt-require*** task's ***wrap*** option was set to ***true***. If the package would have had detected it's AMD wrapping by default, it would've been great :+1: 

*jquery-ui's way*:
```javascript
(function( factory ) {
	if ( typeof define === "function" && define.amd ) {

		// AMD. Register as an anonymous module.
		define('jquery-ui',[ "jquery" ], factory );
	} else {

		// Browser globals
		factory( jQuery );
	}
}(function( $ ) {
/*!
 * jQuery UI Core[...]*/
```

LE: **wrap:false** or **wrapShim:** false do not help me undo the autocall at the end ( ***(this)*** ):

```javascript
define("bootstrap", ["jquery"], (function (global) {
    return function () {
        var ret, fn;
        return ret || global.bootstrap;
    };
}(this)));

**Comment by juthilo** [comment] 2015-05-21 14:03
Duplicate of #14755.

**Closed by juthilo** 2015-05-21 14:03 UTC
