### ISSUE TITLE
v4 - Set borders to 1px rather than rem units

### ISSUE THREAD

**Issue by Skwai** [twbs/bootstrap#18166] opened 2015-11-04 22:38 UTC
After using v4 have encountered issues where borders aren't displayed if they're calculated as less than the equivalent of 1px

This is encountered if the `$font-size-root` is reduced below 16px (which is very large, especially if reducing for smaller devices)

For example if I want to reduce the rem font-size to 14px on mobile devices many of my borders will disappear as the border width is now:

```
 border-width: .0625 * 14px = 0.875px // less than 1px, therefore usually won't appear
```

```
@media (max-width: breakpoint-max(sm)) {
   html { font-size: 14px; }
}
```

I understand that this approach was probably implemented so that element heights could be calculated using all rem attributes, as you cannot mix unit types in sass calculations. However it seems to be causing me a lot of issues and I end up just overriding all the borders with `border-width: 1px;`

**Comment by Skwai** [comment] 2015-11-04 22:42
Also worth noting that v4 currently impliments both 1px and rem units for borders. Should be one or the other IMO.

eg.
```
.carousel-indicators li
.dropdown-menu
.img-thumbnail
.c-select

**Comment by cvrebert** [comment] 2015-11-04 23:10
Approximate duplicate of #17812.

**Closed by cvrebert** 2015-11-04 23:10 UTC
