### ISSUE TITLE
modal: stack overlay option

### ISSUE THREAD

**Issue by leandroruel** [twbs/bootstrap#20014] opened 2016-06-01 14:52 UTC
would be great if, bootstrap comes with the option of stack modals together with the background overlay, some people are trying to do it with some hacks, like this [StackOverflow Post](http://stackoverflow.com/questions/19305821/multiple-modals-overlay)

example:
```js
$('#myModal').modal('stack');
```

**Comment by rafalp** [comment] 2016-06-01 20:15
Seems like dupe of #19914

**Comment by patrickhlauke** [comment] 2016-06-01 20:36
Indeed.

**Closed by patrickhlauke** 2016-06-01 20:36 UTC

**Comment by leandroruel** [comment] 2016-06-03 18:11
oh sorry for that
