### ISSUE TITLE
.form-control kills ability to have narrow <select>s

### ISSUE THREAD

**Issue by merriam** [twbs/bootstrap#16335] opened 2015-04-23 00:08 UTC
Here's the problem.   I want to make a select box (drop down) that has a maximum width.  I set the maximum width.  On a wide screen, it gets overridden by https://github.com/twbs/bootstrap/blob/a2680e8b6ba628312780b00d8d74d28d28b89a84/less/forms.less#L477 :
```scss
width: auto; // Prevent labels from stacking above inputs in `.form-group`
```

This trumps anything done trying to keep the select box small enough to prevent my labels from stacking.  Specifically, if the screen is small, the size of my select drop down is limited.   Once the size of screen goes past a certain point, the .width attribute down in bootstrap overrides my .width attribute, which makes a very long label blow the select box to very wide, which pushes other components on to another line.

**Comment by cvrebert** [comment] 2015-04-23 07:36
Setting a `max-width` seems to work fine for me in Chrome: http://jsbin.com/yuhaha/1/edit
Could you explain how or post an example where it's not working for you?

**Comment by twbs-lmvtfy** [comment] 2015-04-23 07:36
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/yuhaha/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 43, column 13 thru line 43, column 19: Element ```` style ```` is missing required attribute ```` scoped ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment] 2015-04-25 07:59
If you match or exceed the specificity, you shouldn't have a problem. Using `max-width` should also override any `width` that's set. Closing as not a bug though for now.

**Closed by mdo** 2015-04-25 07:59 UTC
Labels: css
