### ISSUE TITLE
Provide dropdown-menu-center for the dropdowns to center the menu

### ISSUE THREAD

**Issue by silviaAut** [twbs/bootstrap#35325] opened 2021-11-04 13:49 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Hello,

You can currently align the dropdown component to the right / left / top / bottom, but not centered.

Can you please provide a `dropdown-menu-center` class to center the dropdown-menu easily?

![dropdown-centered](https://user-images.githubusercontent.com/6195977/140324562-96dc679e-fb59-482c-8bed-9049107a6635.png)

### Motivation and context

Currently all directions are provided to use it easily with a simple class except for a centered menu. If you want to center it, you have to do some ugly CSS at the moment.

**Comment by mdo** [comment] 2022-02-23 23:10
Duplicate of #34436.

**Closed by mdo** 2022-02-23 23:10 UTC
Labels: feature
