### ISSUE TITLE
*::first-line selector in print styles crashes IE11 print / print preview

### ISSUE THREAD

**Issue by y2wde** [twbs/bootstrap#20814] opened 2016-09-30 14:19 UTC
There seems to be a bug in printing with Internet Explorer.  It's not a bug in my code, because the website of Bootstrap v4 also doesn't work. My system run with W10 + IE11. Does anyone have the same problem or a solution?

**Comment by acshef** [comment] 2016-09-30 15:33
Can you be more specific? What's the bug? Can you provide screenshots of what you're seeing vs what you're expecting? Have you tried with other browsers?

**Comment by y2wde** [comment] 2016-09-30 16:36
I can print in all other browsers (chrome, firefox, opera, edge). It's only the ie11. The print-preview shows nothing and works and works until the browser crashes. If i print directly, nothing happend.

The bug is in alpha3 + alpha4. With alpha2 it works fine.

**Comment by slavanga** [comment] 2016-09-30 20:37
Related: https://github.com/h5bp/html5-boilerplate/pull/1799

**Comment by y2wde** [comment] 2016-10-02 14:14
@slavanga Thanks, this was the solution. 
I hope, the dev-team will change this in future releases.

**Comment by slavanga** [comment] 2016-10-02 14:22
@y2wde you should keep this issue opened so that it can be fixed.

**Comment by patrickhlauke** [comment] 2016-10-02 14:35
if the issue is due to `:first-line`, then it seems the fix needs to happen upstream in https://github.com/necolas/normalize.css

**Comment by slavanga** [comment] 2016-10-02 14:48
@patrickhlauke This is not an issue with normalize. The print styles are from the HTML5 Boilerplate.

**Comment by patrickhlauke** [comment] 2016-10-02 15:00
ah sorry, got confused when i skimmed the dist CSS. been a while since i looked, but it appears we've copied the print styles from HTML5 Boilerplate wholesale with changes, so we'll need to tweak at BS end https://github.com/twbs/bootstrap/blob/v4-dev/scss/_print.scss

**Comment by patrickhlauke** [comment] 2016-10-02 16:55
note that #20821 fixes the crashing, but printing behavior is still borked in IE11 it seems (won't print more than 1 page). but that's a different issue, which should be filed once #20821 is merged

**Comment by niteraven78** [comment] 2016-10-02 23:12
There's a change in Windows Update "September 29, 2016 — KB3194496 (OS Builds 14393.222)":

Addressed issue causing “Print all linked documents” to not work in Internet Explorer 11.

Does that fix it?

https://support.microsoft.com/en-us/kb/3194496

**Comment by patrickhlauke** [comment] 2016-10-03 08:59
> Does that fix it?

no

**Closed** 2016-10-03 09:00 UTC
Labels: browser bug, confirmed, css, v4

**Comment by cvrebert** [comment] 2016-10-05 06:21
> but printing behavior is still borked in IE11 it seems (won't print more than 1 page). but that's a different issue, which should be filed once #20821 is merged

@patrickhlauke Care to file that issue now that it's been merged?
