### ISSUE TITLE
put back autocomplete="off" warning and add it on all checkboxes and radio?

### ISSUE THREAD

**Issue by Lausselloic** [twbs/bootstrap#28623] opened 2019-04-08 09:39 UTC
I haven't find it in v4 documentation and all input checkboxes and radio doen't have the autocomplete attribute but as mentioned in v3 :
https://getbootstrap.com/docs/3.4/javascript/#callout-buttons-ff-autocomplete firefox persist state during browsing https://bugzilla.mozilla.org/show_bug.cgi?id=654072

So maybe need to add autocomplete="off" on all radio and checkboxes in V4/V5 documentation + put back the callout?

**Comment by mdo** [comment] 2019-04-09 16:19
Inclined to leave it off—haven't seen any reported issues I think on this?

**Comment by Lausselloic** [comment] 2019-04-10 06:34
there's no issues you're right but maybe need to make a choice? remove all autocomplete on checkboxes and labels, or put it quite everywhere with an explaination?
I've open that question because I've question myself about that attribute on a radio group in bootstrap and find the reply in v3.

But for sure it's a desired functionnality of Firefox so maybe remove all autocomplete attribute would make sense. Let you decide :-)

**Comment by ffoodd** [comment] 2019-04-10 06:48
FWIW as a Firefox user I truly appreciate those persistent states.
I'd recommend to completely remove autocomplete on radio/checkbox groups.

**Comment by mdo** [comment] 2019-04-12 00:31
I'm in favor of removing them all.

**Comment by patrickhlauke** [comment] 2019-04-13 13:08
> FWIW as a Firefox user I truly appreciate those persistent states.
I'd recommend to completely remove autocomplete on radio/checkbox groups.

However...do they cause issues? I've not tested, but could these lead to situations where a programmatically set CSS style (like `active`) is NOT present, but the underlying input/button has been autocompleted by Firefox silently when returning to the page?

**Comment by tmorehouse** [comment] 2019-04-25 21:11
Using the back button will sometimes persist input states on Firefox. which is not always what is wanted (specifically with dynamically generated pages, and when the user cannot control the caching headers that served the page)  I've had to use autocomplete="off" many times where I couldn't set caching headers to no-cache/must-revalidate/etc.

**Comment by tmorehouse** [comment] 2019-04-25 21:12
Also, isn't is needed specifically for button styles checkboxes/radios?

**Comment by mohe2015** [comment] 2019-04-25 22:20
In my opinion the problem is that there is no visual indication that firefox autocompleted a radio or checkbox. The text boxes are at least marked yellow. As I recently was looking for a bug in my code that didn't exist because of this I'm also voting for the autocomplete=off or at least something mentioned in the documentation.

**Comment by patrickhlauke** [comment] 2019-06-24 13:08
trying to tackle the fundamental problem here https://github.com/twbs/bootstrap/pull/28952

**Comment by patrickhlauke** [comment] 2019-06-24 20:03
Closed via https://github.com/twbs/bootstrap/pull/28952

**Closed** 2019-06-24 20:03 UTC
Labels: docs, v4, v5
