### ISSUE TITLE
Fixed top navbar scroll problem on uncollapsed menu

### ISSUE THREAD

**Issue by fakeartist** [twbs/bootstrap#16094] opened 2015-03-17 20:53 UTC
To see the problem, check the official demo page below.

http://getbootstrap.com/examples/navbar-fixed-top/

If you make the window's width and height really small (to see the responsive effect) and press the menu button, then you'll see that you cannot scroll the menu (so the bottom buttons are hidden and cannot be reached). 

I think it's a bug. Anyone for a workaround?

**Comment by cvrebert** [comment] 2015-03-18 23:20
Approximate duplicate of #12738.

**Closed by cvrebert** 2015-03-18 23:20 UTC
Labels: css
