### ISSUE TITLE
V4 docs for input size shows input-lg and input-sm in placeholder.

### ISSUE THREAD

**Issue by ShaunR** [twbs/bootstrap#18132] opened 2015-11-02 20:07 UTC
http://v4-alpha.getbootstrap.com/components/forms/#control-sizing

Looks like version 4 now uses form-control-size for sizing inputs, the examples in the docs though use a place holder that still shows .input-lg and .input-sm.  They just need to be updated to the correct new classes.

**Comment by cvrebert** [comment] 2015-11-02 22:38
Duplicate of #17670.

**Closed by cvrebert** 2015-11-02 22:38 UTC
Labels: docs, v4
