### ISSUE TITLE
[v4] Modal flickering when within .list-group-item

### ISSUE THREAD

**Issue by gizburdt** [twbs/bootstrap#25206] opened 2018-01-05 13:25 UTC
Hi,

In some cases the modal filckers (see video).

![bootstrap](https://user-images.githubusercontent.com/1470623/34611050-36f855bc-f224-11e7-96ba-a8315a4a601a.gif)

This is the html:
```html
<div class="row align-items-center">
    <div class="col-md-6">
        <strong>Test</strong> <br>
        Street 1 31 <span><span class="badge badge-info">Primary</span></span> <br>
        1234AA Amsterdam <br>
    </div> 

    <div class="col-md-6 text-right"><!----> 
        <div class="d-inline-block text-left">
            <a href="#" class="btn btn-sm btn-warning">Edit</a> 
            
            <div tabindex="-1" role="dialog" id="editModalLHzoKhSu" class="modal fade">
                <div role="document" class="modal-dialog">
                    <form class="modal-content">
                        <div class="modal-header"><p id="editAddressModalLabel" class="modal-title h5">Edit address</p> <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true">×</span></button>
                        </div> 

                        <div class="modal-body">
                            // Form
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
```

If you need more info, please let me know :)

- OS: MacOS,
- Browser: Chrome 63.0.3239.84

**Comment by Ruffio** [comment] 2018-01-05 13:44
@gizburdt do you have some custom css/js that can cause this? Can you make a jsbin or similar that demonstrates this behaviour?

**Comment by Johann-S** [comment] 2018-01-05 14:17
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by gizburdt** [comment] 2018-01-09 22:37
Hmm, will have a look at it. The code is nested in my project (and Vue), so I will have a try moving it to JSbin.

Extra info: The error is not present in 4.0.0-beta.2, but it is in 4.0.0-beta.3

**Comment by gizburdt** [comment] 2018-01-18 11:17
Here is the JS bin: https://jsbin.com/sitemohuno/2/edit?html,js,output

The problem happens when the modal is within a list-group-item. Normally I place my modals at the bottom of the body, but I can't in my current project, because i'm using vue components.

**Comment by gizburdt** [comment] 2018-01-18 21:19
@Johann-S Looks like this is causing the problem:

`.list-group-item:hover{ z-index: 1; }`

**Comment by namnh06** [comment] 2018-01-19 02:37
I met this problem already, not happen in beta 2 but in beta 3, it's very annoy. It happen in list-group-item confirm.
Using SPA Angular Js + bootstrap 4 beta 3.
Run on Chrome, ubuntu 16.04.

**Comment by ysds** [comment] 2018-01-19 03:31
This is not a browser bug. This occurs because the `z-index: 1` of a `.list-gorup-item:hover` cause a new [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

I created a very simple pen: https://codepen.io/anon/pen/ppqbeq
You can see the modal backdrop (z-index: 1040) is above the modal (z-index: 1050).

**Comment by namnh06** [comment] 2018-01-19 03:36
@ysds any idea to fix this bug man ?

**Comment by ysds** [comment] 2018-01-19 03:40
I don't have a solution right now, but it is certain to put a modal HTML outside a item without z-index.

**Comment by gizburdt** [comment] 2018-01-19 08:52
Quick fix for now:

‘.list-group-item,
.list-group-item:hover{
    z-index: auto;
}’

**Comment by ysds** [comment] 2018-01-19 12:22
Now is the time to back to #16432 !

**Comment by namnh06** [comment] 2018-01-22 02:42
@gizburdt Thank you, it's worked.
@ysds Thank to you.

**Comment by ibussieres** [comment] 2018-01-23 02:35
Strangely, the same solution did not work for me. On bootstrap 4.0.0.

**Comment by namnh06** [comment] 2018-01-23 02:40
@ibussieres i'm working on bootstrap 4.0.0 after upgrade from beta 3, it's still working bro.

**Comment by ibussieres** [comment] 2018-01-23 14:27
I just double checked. When inspecting my `.list-group-item, .list-group-item:hover` definitely has the `z-index: auto`. 

![image](https://user-images.githubusercontent.com/422296/35279988-bb67a130-001c-11e8-8d41-894632d946a1.png)

I guess there is something else interfering. I've extracted the markup produced by react here, I have _no_ custom CSS at all, I'm still prototyping this app.  Any ideas what it could be ? I'll continue my attemps to find it, maybe another z-index somewhere.

```<div class="list-group-item list-group-item-action row d-flex">
  <div class="col col-md-6 order-1">
    <span class="text-muted text-truncate">...</span>
    <span class="text-dark">...</span>
  </div>
  <div class="col-12 col-md-4 order-3 order-md-2">
    <div class="row my-1">
      <div class="col order-2 order-md-1 text-right">...</div>
    </div>
  </div>
  <div class="col-5 col-md-2 order-2 order-md-3 d-flex align-items-center justify-content-between">
    <span class="badge badge-pill badge-info mr-2">...</span>
    <div>
      <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#urgent-confirm-modal">...</button>
      <div class="modal fade" id="urgent-confirm-modal" tabindex="-1" role="dialog" aria-labelledby="confirm-modal-title" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="confirm-modal-title">
                <span>...</span>
              </h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="...">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">
             <p><span>...</span></p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">
                <span>Cancel</span>
              </button>
              <button type="button" class="btn btn-outline-primary" data-dismiss="modal">
                <span>Confirm</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>```

**Comment by nathanosoares** [comment] 2018-01-27 18:20
> Quick fix for now:
.list-group-item, .list-group-item:hover{ z-index: auto; }

it works on 4.0.0

**Comment by mdo** [comment] 2018-04-01 02:18
Duplicate of #23916.

**Closed by mdo** 2018-04-01 02:18 UTC
Labels: css, v4

**Comment by qingfengbaili** [comment] 2018-11-20 08:41
> Quick fix for now:
> 
> `.list-group-item, .list-group-item:hover{ z-index: auto; }`

可以使用了,thanks
