### ISSUE TITLE
Chrome doesn't honor border-radius on <select>s

### ISSUE THREAD

**Issue by niftylettuce** [twbs/bootstrap#15588] opened 2015-01-16 18:48 UTC
This is related to this StackOverflow post at <http://stackoverflow.com/questions/5780109/removing-rounded-corners-from-a-select-element-in-chrome-webkit>.

Basically if you have the following HTML:

```html
<div class="input-group">
  <select class="form-control input-sm">
    <option value="4242" selected="">Visa ending in 4242 (12/2015)</option>
  </select>
  <div class="input-group-btn">
    <button type="button" data-toggle="modal" data-target="#cards-modal" class="btn btn-primary btn-sm card-manage-btn">Manage</button>
  </div>
</div>
```

Chrome will render the <select> as follows (ignoring the `border-top-right-radius: 0px;` and `border-bottom-left-radius: 0px;` rules as set by Bootstrap:

![screen shot 2015-01-16 at 1 43 22 pm](https://cloud.githubusercontent.com/assets/523141/5782074/583d2aae-9d86-11e4-8152-c062e2a6eb1f.png)

A possible fix would be something like this:

```html
<select class="form-control input-sm" style="border: 0; outline: 1px inset #cccccc; outline-offset:-1px;">
  <option value="4242" selected="">Visa ending in 4242 (12/2015)</option>
</select>
```

Which renders the select as follows:

![screen shot 2015-01-16 at 1 43 09 pm](https://cloud.githubusercontent.com/assets/523141/5782035/019e5c9a-9d86-11e4-9cc2-6886a9b452ac.png)

**Comment by niftylettuce** [comment] 2015-01-16 18:49
Just documenting this here, most likely this issue will be closed as it's Chrome only.

**Comment by cvrebert** [comment] 2015-01-16 18:57
Approximate duplicate of #15340.

Yeah, this is already documented: https://github.com/twbs/bootstrap/blob/b7c332f183d52c6b1432a4eb511b8c61478bfc81/docs/_includes/css/forms.html#L409
And we also specifically recommend against `<select>`s in `.input-group`s: https://github.com/twbs/bootstrap/blob/b7c332f183d52c6b1432a4eb511b8c61478bfc81/docs/_includes/components/input-groups.html#L8

I'll leave it to @mdo to evaluate whether your hack is worth pursuing.

**Comment by niftylettuce** [comment] 2015-01-16 18:57
@cvrebert thank you :+1:

**Comment by mdo** [comment] 2015-01-16 21:34
Nah, we'll pass on the hack for that. Not worth our time to get into even more form inconsistencies.

**Closed by mdo** 2015-01-16 21:34 UTC
Labels: css

**Comment by niftylettuce** [comment] 2015-01-21 23:09
@mdo @cvrebert does anyone know if there is a WebKit, Safari, or CRBug for this filed somewhere?  It'd be so nice if they patched WebKit to support border-radius customization on <select>'s...

**Comment by cvrebert** [comment] 2015-01-21 23:51
No, I haven't gone looking for one because it's more of an RFE than a bug per se. CSS/HTML currently deliberately leaves a lot of stuff around styling `<select>`s undefined.

**Comment by lucasgranberg** [comment] 2015-08-06 08:37
http://stackoverflow.com/a/5780261
select {
  -webkit-appearance: none;
  -webkit-border-radius: 0px;
}

**Comment by nathanayling** [comment] 2015-08-06 10:36
Isn't it.
<pre>select {
-webkit-appearance: none;
-webkit-border-radius: 0px; 
}</pre>

According to that link you've referenced?

**Comment by heralder99** [comment] 2015-08-06 10:39
NAVER - http://www.naver.com/
--------------------------------------------

heralder@naver.com 님께 보내신 메일 <Re: [bootstrap] Chrome doesn't honor border-radius on <select>s (#15588)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by lucasgranberg** [comment] 2015-08-06 10:45
yeah but it doesn't work anyway becouse of the disappearing arrows. In my case I tested with only appearence but the -webkit- part was added by grunt. In any case it doesn't work becouse of the disappearing arrows. For reference I just went with ui-select for my application, select2 is another option.
