### ISSUE TITLE
[v5] Tooltip, rapid change of state causes problem

### ISSUE THREAD

**Issue by ionurboz** [twbs/bootstrap#32380] opened 2020-12-08 11:04 UTC
- Operating system and version (Windows)
- Browser and version (Chrome 86.0.4240.198)
- https://getbootstrap.com/docs/5.0/components/tooltips/

If we move the mouse over an item more than once in quick succession, the item's tooltip will either stay open or not work at all.

SS
------
![image](https://user-images.githubusercontent.com/5174447/101475570-a18c4b80-395d-11eb-8e73-4e13744f2346.png)

**Comment by rohit2sharma95** [comment] 2020-12-08 11:31
Duplicate of #32372

**Closed** 2020-12-08 12:09 UTC
Labels: duplicate
