### ISSUE TITLE
Tooltip stays if button with tooltip is disabled when clicked

### ISSUE THREAD

**Issue by elliotleelewis** [twbs/bootstrap#22380] opened 2017-04-07 23:59 UTC
If a button that has a tooltip attached is clicked, in which the click event disables the button, the tooltip is permanently attached to that button.

Found on Google Chrome 57, tested also on Firefox 52.

Screenshots:

Before:
![](http://i.imgur.com/85DKRjo.png)

After:
![](http://i.imgur.com/nIpS0Nh.png)

In the after, i can move my mouse wherever, and the tooltip will stay present on the button.

### EDIT

JSFiddle: https://jsfiddle.net/zth44zhm/3/

**Comment by pkozlowski-opensource** [comment] 2017-04-08 07:10
See https://github.com/twbs/bootstrap/issues/9294

tl;dr; is that disabled buttons don't fire mouse events, so there is no way of knowing that the mouse is out and that the tooltip should be closed. There are work-arounds like putting another element around a button (ex.: http://stackoverflow.com/questions/33599955/tooltip-to-disabled-button)

IMO this is a duplicate of existing issues.

**Comment by elliotleelewis** [comment] 2017-04-08 12:59
Wrapping it in another element, and then putting the tooltip on the outer element still doesn't fix the issue for some reason?

https://jsfiddle.net/zth44zhm/4/

**Comment by sagar12861** [comment] 2017-04-11 12:07
Tool tip is not working for disabled element is it expected ?
https://jsfiddle.net/zth44zhm/7/

**Comment by mdo** [comment] 2020-09-18 21:45
Didn't realize there were so many tooltip disabled issues. Unfortunately this is the behavior that's required—you'll have to do a wrapper element (in both v4 and v5).

See https://getbootstrap.com/docs/4.5/components/tooltips/#overview for mention of this.

**Closed by mdo** 2020-09-18 21:45 UTC
Labels: js, v4, v5
