### ISSUE TITLE
.navbar-fixed-bottom renders on top of .navbar-fixed-top's collapsible menu (blocking access to some items)

### ISSUE THREAD

**Issue by CriseX** [twbs/bootstrap#16580] opened 2015-06-04 04:10 UTC
http://jsbin.com/tupixasozi/1/edit?html,output

On mobile devices when screen height falls short certain menu items become impossible to view when the navbar is collapsed and both top and bottom navbar are fixed. My first instinct is to add z-index: -1 to the bottom navbar on these devices, however, I am wondering whether this has any side effects (edit: after some experimentation, obviously it does).

**Comment by cvrebert** [comment] 2015-06-04 05:21
Duplicate of #12738?

**Comment by CriseX** [comment] 2015-06-04 05:50
I can neither confirm or deny that, that issue may be related but even on displays where all the menu items would otherwise fit the fixed bottom navbar creates this issue by being on top of the expanded top nav. So I can't really tell if fixing that bug would completely fix this use case.

Because this is an issue of two absolutely positioned elements being on a different planes on the z-axis as far as I can tell (ie. even if you don't expand the collapsed menu, artificially reducing the height will cause the bottom nav to eventually overlap the top one).

**Comment by cvrebert** [comment] 2015-06-04 06:14
I'm kinda doubtful that there's any one-size-fits-all solution here. Also, we're not making any more significant changes to Bootstrap v3's navbar at this point, in order to focus on Bootstrap v4's completely overhauled navbar.

**Comment by CriseX** [comment] 2015-06-04 06:24
http://jsbin.com/zisosikavo/1/edit?html

So, this should more or less work, apart from the issue reference here earlier, but I can't say I like it from markup point of view. Of course this is within the reasonable assumption that the top navbar should have preference over the bottom one.

I can't wait for this mythical v4 navbar you people keep talking about... both figuratively and literally at this point. I wonder if there is a way to tell which z-index the fixed navbars get assigned with so swapping them could be achieved without reversing the order in the actual DOM.

**Comment by mdo** [comment] 2015-06-05 04:24
Echoing @cvrebert's comment, not really anything we can do here for v3.

**Closed by mdo** 2015-06-05 04:24 UTC
Labels: confirmed, css
