### ISSUE TITLE
Button Element not updated if target ID contains colon

### ISSUE THREAD

**Issue by svenhaag** [twbs/bootstrap#22060] opened 2017-02-24 14:21 UTC
Bootstrap Version 4.0.0-alpha.6 and 3.3.7

Target ID = "collapse:Example"
data-target = "data-target="#collapse\\:Example""
aria-controls="collapse:Example"

Only the Target attributes get updated, not the button (toggle element) attributes.
IDs with a colon exist especially in the JSF world.

[Bug JS Fiddle](https://jsfiddle.net/DTcHh/30179/)

[Related Bug](https://github.com/twbs/bootstrap/issues/22041)

**Comment by bkdotcom** [comment] 2017-02-24 14:48
This works

```
<button role="button" type="button"
        data-toggle="collapse"
        data-target="#collapse\:\:Example"
        aria-expanded="true"
        aria-controls="collapse:Example">
  Button with data-target
</button>
<div class="collapse in" id="collapse::Example">
  bla bla bla
</div>
```

apparently one needs to escape the colons in the data attribute

**Comment by svenhaag** [comment] 2017-02-24 15:55
Hi, in the JSFiddle the data-target ID is already escaped with a single backslash, i.e data-target="#collapse\\:Example". This is an already valid jQuery selector. Though why doubling it to "\:\:" ? This does not work for me in the JSFiddle example. Maybe you can provide a running JSFiddle? Thanks.

**Comment by bkdotcom** [comment] 2017-02-24 16:59
[double colon fiddle](https://jsfiddle.net/DTcHh/30182/)

**Comment by svenhaag** [comment] 2017-02-27 10:11
Hi bkdotcom, adding a second double-colon is not a solution. JSF will render the ID attribute like "`a:b:c`".

**Comment by bkdotcom** [comment] 2017-02-27 17:31
> "second double-colon"

?

> JSF will render the ID attribute like "a:&#8203;b:c".

?

I inspected my fiddle's html and it's
```
<div class="collapse in" id="collapse::Example" aria-expanded="true">
  bla bla bla
</div>
```

> Button Element not updated if target ID contains double-colon

Fiddle has working double-colon

Am I missing something?

**Comment by svenhaag** [comment] 2017-02-28 07:33
Hi bkdotcom, sorry for the messup. I did not mean two subsequent colons but instead a single one. I fixed the heading and description of this issue. However the first JSFiddle still shows the bug. The toggling elements aria attributes are not updated if the ID contains a colon. Cheers.

**Comment by peterdesmet** [comment] 2017-10-04 16:29
Maybe related: I noticed that Scrollspy doesn't work either with anchors/ids that include a colon (e.g. `#foo:bar`). This was already brought up in [this discussion](https://github.com/twbs/bootstrap/pull/14789#issuecomment-60138926) and decided to postpone to v4. Anyone has an idea if this still on the roadmap? /cc @hnrch02

**Comment by Johann-S** [comment] 2017-11-07 09:08
I made a Codepen with our latest release (beta 2) see : https://codepen.io/Johann-S/pen/Ebgmgg
And aria-expanded is correctly updated

The only thing we can fix here it's to avoid the thing folks must escape manually their ID

**Comment by Johann-S** [comment] 2017-11-07 11:41
#24700 is merged so now Bootstrap will escape your ID

**Closed by Johann-S** 2017-11-07 11:41 UTC
Labels: js, v4

**Comment by meeque** [comment] 2018-01-05 13:49
Hm, maybe too late but, here's how I see it:

* Assuming an element with id `foo:bar` the correct CSS selector is in fact `#foo\:bar`
   (When writing this selector in JS, you also need to escape the backslash, but that's not relevant here.)
* Per documentation bootstrap's `data-target` holds a CSS selector
* In contrast, the `aria-controls` attribute does not hold a CSS selector but a verbatim id

And here's my conclusions:
* It is not bootstraps job to fix broken CSS selectors
* If application authors rely on bogus ids, the should learn to write the corresponding selectors
* There is actually a reason why CSS selectors treat an unescaped colon specially: colons are used to express pseudo classes or pseudo elements
* There may be valid reasons for using colons inside `data-target` as intended by CSS, e.g. `#myfield:enabled`
* If bootstrap introduces magic fixes, it will most likely break other stuff. 
* In the very least this should be clearly documented

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors
