### ISSUE TITLE
col-lg in 1600px version

### ISSUE THREAD

**Issue by kasperhartwich** [twbs/bootstrap#15943] opened 2015-02-27 15:16 UTC
Right now we support grids up to 1200>= pixels. As people gets better and better resolutions, maybe it is time to make 1400>= og 1600>= pixel gridsupport?

![screen shot 2015-02-27 at 16 14 29](https://cloud.githubusercontent.com/assets/616231/6414984/e76a06a8-be9b-11e4-8e09-6e93fd3ad342.png)

**Comment by kkirsche** [comment] 2015-02-27 15:31
Thanks for suggestion! While this won't happen for V3 of Bootstrap I believe a new grid system is in the works for V4 :smiley:

**Comment by cvrebert** [comment] 2015-02-27 22:36
Duplicate of #14683.

**Closed by cvrebert** 2015-02-27 22:36 UTC
Labels: css, feature
