### ISSUE TITLE
breadcrumbs dissapear if inside conteiner-fluid

### ISSUE THREAD

**Issue by joeaudette** [twbs/bootstrap#25812] opened 2018-03-08 19:53 UTC
If I use a main element with class=container, breadcrumbs inside it display as expected, if I change it to container-fluid breadcrumbs disappear

Seems like a bug to me

**Comment by chiraggmodi** [comment] 2018-03-09 08:17
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Johann-S** [comment] 2018-03-09 12:32
What @chiraggmodi said 👍

**Comment by kevdotbadger** [comment] 2018-03-11 13:46
https://codepen.io/anon/pen/NYqROj

Chrome 64, Firefox 58 on OS X 10.13.3

Certainly, not a bootstrap issue, might as well close this.

**Comment by Johann-S** [comment] 2018-03-11 15:11
Unable to reproduce it on Chrome 64 Win10 😟

**Comment by kevdotbadger** [comment] 2018-03-11 17:42
Oh, in case it's not clear, there's no problem on Chrome 64, Firefox 58 on OS X 10.13.3! I re-read my message and it was immediately clear what the hell I was going on about.

**Closed** 2018-03-13 02:21 UTC
Labels: awaiting reply
