### ISSUE TITLE
v5.1 Dropdown autoClose='false' closes with esc button

### ISSUE THREAD

**Issue by Unkulon** [twbs/bootstrap#37280] opened 2022-10-10 13:15 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Steps to reproduce

1. Go to https://getbootstrap.com/docs/5.1/components/dropdowns/#auto-close-behavior
2. In the examples open the dropdown that has `data-bs-auto-close="false"`
3. Click the `ESC` key

### What to expect
The dropdown stays open as per the options documentation (https://getbootstrap.com/docs/5.1/components/dropdowns/#options).

### Actual outcome
The dropdown closes.

### Note
This issue seems to be introduced with v5.1 since the v5 dropdown works fine in that regard. (Perform the same on the docs for it https://getbootstrap.com/docs/5.0/components/dropdowns/#auto-close-behavior)

### Reduced test cases

Really nothing more to put here unless you need your example code in a code pen.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.1.3

**Comment by julien-deramond** [comment] 2022-10-10 18:54
Something's not very clear in the documentation for `autoClose`. At the same time we have:
* "(Also will not be closed by pressing esc key)" when `autoClose` is `false`
* "Note: the dropdown can always be closed with the ESC key." as a general information for `autoClose`

**Comment by EthanBnntt** [comment] 2022-10-12 01:58
This looks like a flaw with the documentation and not the code. Should I update the documentation?

**Comment by julien-deramond** [comment] 2022-10-12 05:29
Thanks @EthanBnntt for the PR.
@GeoSot or @XhmikosR do you confirm that it's rather a flaw with the documentation and not the code?

**Comment by GeoSot** [comment] 2022-10-12 07:38
I can confirm that on 5.0 with `data-bs-auto-close="false" `, the `esc` doesn't work, but on 5.2 works ok

**Comment by EthanBnntt** [comment] 2022-10-12 14:08
In bootstrap v5.2, does pressing **ESC** close a dropdown?

**Comment by XhmikosR** [comment] 2022-10-25 18:44
Not sure I follow here. Is this a regression or it just didn't work properly in v5.0?

**Comment by GeoSot** [comment] 2022-10-25 19:27
As I got it, it wasn't working properly on 5.0

**Comment by XhmikosR** [comment] 2022-10-26 05:44
In that case, we can close this issue? There's also #37300 linked to this issue.

**Comment by GeoSot** [comment] 2022-10-26 07:39
As it depends on me, I would say yes to both of them

**Closed** 2022-11-12 15:49 UTC
Labels: docs, v5
