### ISSUE TITLE
Box sizing not working for older Firefox versions.

### ISSUE THREAD

**Issue by codecrafting-net** [twbs/bootstrap#18977] opened 2016-01-20 20:42 UTC
Since Firefox 29 does not require anymore the use of prefix -moz- for box-sizing property in css. I suggest to include in the code the `-moz-box-sizing` to avoid problems with older firefox versions.

**Comment by cvrebert** [comment] 2016-01-20 22:00
Duplicate of #17237.
It's really not advisable to be running such old versions of Firefox...

**Closed by cvrebert** 2016-01-20 22:00 UTC
Labels: css

**Comment by codecrafting-net** [comment] 2016-01-22 05:37
I know that it's not advisable to use old versions of FIrefox, but that can happen and the 28 version is not that much old, I think that has no cost to add a -moz-box-sizing property. Many companies use old ESR versions and don't follow the update rhythm. I don' know, to me doesn't cost to add that. Sorry for the duplicated. My bad.
