### ISSUE TITLE
Modal toggle issue in v3.3.6

### ISSUE THREAD

**Issue by Prathiban** [twbs/bootstrap#20269] opened 2016-07-11 06:13 UTC
I am using `data-toggle` to toggle between modals, but I am unable to scroll the modal after toggling, instead the body element is scrolling behind. I found that the `modal-open` class is not getting added to body tag. <a href="http://jsbin.com/nojiteq/edit?html,output">Sample code in v3.3.6</a>
But it seems that this scroll issue is not occurring in v3.2.0 <a href="http://jsbin.com/kudomot/edit?html">(Sample here...)</a>
Should I use 3.2.0 or 3.3.6, or did I miss anything in v3.3.6 modal.

I don't know whether this question should be asked here, please guide me

**Comment by neilhem** [comment] 2016-07-11 06:18
Without demo it's not possible to find out what's going on and better place to ask questions like this is [Stackoverflow](http://stackoveflow.com)

**Comment by Prathiban** [comment] 2016-07-11 06:19
The demo link is in the issue i generated, Please see it again for the link

**Comment by Prathiban** [comment] 2016-07-11 06:21
And thanks, I will ask these kinda questions in Stackoverflow from now onwards...

**Comment by neilhem** [comment] 2016-07-11 06:25
My bad, looks like a bug. Workaround will be using bs.modal hidden event & opening another one after that

**Comment by Prathiban** [comment] 2016-07-11 06:26
Got it! Thank you.

**Comment by cvrebert** [comment] 2016-07-11 07:03
Duplicate of #17956.

**Closed by cvrebert** 2016-07-11 07:03 UTC
