### ISSUE TITLE
a.navbar-brand computed as `display:block;` instead of inline-block

### ISSUE THREAD

**Issue by sidot3291** [twbs/bootstrap#22305] opened 2017-03-29 20:09 UTC
This bug is visible on the documentation page - just inspect the link example:
http://v4-alpha.getbootstrap.com/components/navbar/#brand

Inspector shows `display:block;` is being computed despite `display:inline-block;` being assigned.  This is the result of `<nav>` being set to `display:flex`, and a.navbar-brand being its immediate descendant.

The effect is that the entire `<nav>` is linked instead of just the contents of `.navbar-brand`.

A quick fix is to wrap a.navbar-brand in a div:
```
<div>
   <a class="navbar-brand" href="#">Navbar</a>
</div>
```

This way, `display:block;` is forced on the wrapping div and the link behaves as intended.

Does anyone know of a better solution?  Perhaps there is some magic with flexbox?

**Comment by mdo** [comment] 2017-03-30 05:57
Sounds like a duplicate of #21621.

**Closed by mdo** 2017-03-30 05:57 UTC
