### ISSUE TITLE
Modal with Tooltips and popovers don't not close

### ISSUE THREAD

**Issue by raesromero** [twbs/bootstrap#22382] opened 2017-04-08 13:49 UTC
If popover or tooltips button is clicked. the modal can't close.

<a href="https://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers">Tooltips and popovers</a>

**Comment by pkozlowski-opensource** [comment] 2017-04-08 13:57
Most probably duplicate of #22314, which should be fixed in the `v4-dev` branch but not released yet

**Comment by Johann-S** [comment] 2017-04-08 14:01
Fixed by #21743

**Closed by Johann-S** 2017-04-08 14:01 UTC
