### ISSUE TITLE
Bug: inputs of type = "date" | "time" | "datetime-local" render with incorrect height and placeholder colors in Safari 14.1.2

### ISSUE THREAD

**Issue by nstuyvesant** [twbs/bootstrap#34760] opened 2021-08-17 17:08 UTC
- Operating system and version (Windows, macOS, Android, iOS): macOS 11.5.2
- Browser and version: Safari 14.1.2

Problems:

1. On Safari 14.1.2 on macOS 11.5.2 (the latest of both as of submitting this issue), HTML inputs of type = "date" | "time" | "datetime-local" have a default height of 34 whereas the default height of type="text" is 24. This causes the contents to be positioned in a way that will not align with contents of inputs of type text and it leaves an uneven amount of space between the border and the contents. For example: 
![image](https://user-images.githubusercontent.com/5770938/129768972-0867d7dc-f710-4327-b11b-bb07cdf2a96f.png)
2. Placeholders for inputs of "date" | "time" | "datetime-local" have delineator characters that appear in black such as "/", ":" and commas vs. the placeholder values that appear gray by default. Incidentally, Chrome displays placeholders for these input types in black whereas inputs of type text are gray.

Steps to reproduce:

1. Using Safari 14.1.2 on macOS 11.5.2, navigate to https://getbootstrap.com/docs/5.1/forms/form-control/#example
2. Hover over the email address field in the first example and right-click and pick **Inspect Element**
3. In the HTML sources, change
```html
<input type="email" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
```
to
```html
<input type="datetime-local" class="form-control" id="exampleFormControlInput1" placeholder="name@example.com">
```
and view the results in the Safari browser.

4. Try the same thing in Chrome and note the change in color of the placeholder from darkgray to black.
![image](https://user-images.githubusercontent.com/5770938/129770424-bfd0d6b7-9516-4410-a26e-db9f7ec1ff5e.png)
to
![image](https://user-images.githubusercontent.com/5770938/129770380-7b16c434-d133-4d33-b4a3-be5f31c90c6a.png)

**Comment by shikhar0512L** [comment] 2021-09-19 06:04
YES

**Comment by Mushr0000m** [comment] 2022-03-08 09:40
I can confirm this issue, also it might be a bug of Safari, this issue appears on other frameworks or even plain CSS if the input have a line-height and is of type date/time/datetime-local the final height is buggy

**Comment by tkrotoff** [comment] 2022-04-10 15:57
See #34433 (duplicate)

**Comment by mdo** [comment] 2022-05-02 04:16
Duplicate of #34433.

**Closed by mdo** 2022-05-02 04:16 UTC
