### ISSUE TITLE
Tooltip floats to top of page in docs when "copy is clicked"

### ISSUE THREAD

**Issue by hdusten** [twbs/bootstrap#33339] opened 2021-03-11 19:46 UTC
https://github.com/twbs/bootstrap/blob/e153e5f5b2b82ad09a9874b8ff1dfca986790f76/site/assets/js/application.js#L144
https://github.com/twbs/bootstrap/blob/e153e5f5b2b82ad09a9874b8ff1dfca986790f76/site/assets/js/application.js#L156

replace lines above with

tooltipBtn.update() //call to positional update
tooltipBtn.show() //then call to show

Real small.. lol but was just in the docs today and noticed. Hope this is helpful.

**Comment by XhmikosR** [comment] 2021-03-12 15:59
Duplicate of the other toolip issues.

**Closed by XhmikosR** 2021-03-12 15:59 UTC
