### ISSUE TITLE
v4 - Text does not display inside tooltips in Firefox browser

### ISSUE THREAD

**Issue by ryannpr** [twbs/bootstrap#17465] opened 2015-09-03 15:59 UTC
Text is not displaying inside of tooltips when using the Firefox browser.  It appears that the tooltip javascript code is working, as a small tooltip indicator does display, but the tooltip is empty, there is no text displaying inside the tooltip.  The issue seems to be isolated to only the Firefox browser for me, I have tested in IE11, Chrome, Safari, and Firefox, and I have only run into the issue in Firefox, so this might be a browser bug.

**Comment by mdo** [comment] 2015-09-03 16:01
JS Bin reproducing the bug?

**Comment by ryannpr** [comment] 2015-09-03 17:36
JSBin link to issue: http://jsbin.com/wuzexikelo/edit?html,output

Note problem only in Firefox for me so far.  (have not tried Opera)

**Comment by dtamm** [comment] 2015-09-03 17:42
I can confirm this eine, had the same issue in my Firefox 40 recently!

**Comment by cvrebert** [comment] 2015-09-03 18:48
Duplicate of #17097.

**Closed by cvrebert** 2015-09-03 18:48 UTC

**Comment by BorderCloud** [comment] 2016-01-31 11:54
+1  in bootstrap.min.js  version v4.0.0-alpha.2 
I had exactly the same problem with Fireworks and the version v4.0.0-alpha.2 (installed via git) with bootstrap.min.js but this problem is fix in the version bootstrap.js.
I deleted the old bootstrap.min.js and I minified the good version.

Hope this helps.

**Comment by cvrebert** [comment] 2016-01-31 12:12
@BorderCloud Unable to reproduce with http://jsbin.com/yamosal/edit?html,output
![proof](https://cloud.githubusercontent.com/assets/419884/12702038/ac739840-c7d0-11e5-94c1-1b102e237acf.jpg)
Also, in the future, kindly open new issues instead of commenting on old closed ones where your comments are liable to go unnoticed.
