### ISSUE TITLE
--bs-nav-link-font-weight variable missing in .nav class, v5.2.0-beta1.

### ISSUE THREAD

**Issue by SamuelMiller** [twbs/bootstrap#36684] opened 2022-07-06 17:30 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

As shown below, the css variable --bs-nav-link-font-weight is left blank (line 3826), no value/string is given in Bootstrap v5.2.0-beta1, installed via npm.
```
.nav {
  --bs-nav-link-padding-x: 1rem;
  --bs-nav-link-padding-y: 0.5rem;
  --bs-nav-link-font-weight: ;
  --bs-nav-link-color: var(--bs-link-color);
  --bs-nav-link-hover-color: var(--bs-link-hover-color);
  --bs-nav-link-disabled-color: #6c757d;
  display: flex;
  flex-wrap: wrap;
  padding-left: 0;
  margin-bottom: 0;
  list-style: none;
}
```

--bs-nav-link-font-weight  is used in .nav-link to set font-weight:

```
.nav-link {
  display: block;
  padding: var(--bs-nav-link-padding-y) var(--bs-nav-link-padding-x);
  font-size: var(--bs-nav-link-font-size);
  font-weight: var(--bs-nav-link-font-weight);
  color: var(--bs-nav-link-color);
  text-decoration: none;
  transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out, border-color 0.15s ease-in-out;
}
```

### Reduced test cases

See above.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2

**Comment by julien-deramond** [comment] 2022-07-06 19:14
Thanks for reporting this issue @SamuelMiller.
IMO it is done on purpose as explained in the description of https://github.com/twbs/bootstrap/pull/31035.
It is `null` by default because not needed in Bootstrap style but can be set by projects changing the style; overriding `$nav-link-font-weight` for example.

**Comment by mdo** [comment] 2022-07-19 20:04
Closing as duplicate of #36595. Same problem to solve here.

**Closed by mdo** 2022-07-19 20:04 UTC
Labels: css, v5
