### ISSUE TITLE
Responsive typography?

### ISSUE THREAD

**Issue by paper9oll** [twbs/bootstrap#19311] opened 2016-02-25 05:04 UTC
Hi Developers,

Do your have any plans to introduce responsive typography based on Sass maps in v4?

**Comment by cvrebert** [comment] 2016-02-25 09:33
Duplicate of #17095. Please search more in the future. Thanks.

**Closed by cvrebert** 2016-02-25 09:33 UTC
Labels: css, feature, v4

**Comment by paper9oll** [comment] 2016-02-25 09:38
sorry about that
