### ISSUE TITLE
!important on all text helper classes (v4)

### ISSUE THREAD

**Issue by dszopa** [twbs/bootstrap#20808] opened 2016-09-28 17:52 UTC
In version 4, text-muted, text-primary, text-success, text-info, text-warning, & text-danger all have !important on all of their color definitions making it impossible to override them with custom css. 

Is there a reason for this?

**Comment by cvrebert** [comment] 2016-09-28 20:47
Yes, because this is how utility classes are supposed to work.
Approximate duplicate of #18817, which gives background on the rationale.

> making it impossible to override them with custom cs

You should not override them in the first place. You should either adjust the relevant Sass color variables to your desired values, or add your own `.text-*` classes with distinct names.

**Closed by cvrebert** 2016-09-28 20:47 UTC
