### ISSUE TITLE
v4 - `btn-group-xs` not working

### ISSUE THREAD

**Issue by Qqwy** [twbs/bootstrap#17233] opened 2015-08-22 17:32 UTC
http://v4-alpha.getbootstrap.com/components/button-group/#sizing 

In above section, the `<div class="btn-group btn-group-xs" role="group" aria-label="...">...</div>` shows up with the same size as the normal button group.

Either `btn-group-xs` is something that ought to be added and is not yet in the new Bootstrap alpha(I hope so, it is a great feature), or this section in the documentation needs updating.

**Comment by kkirsche** [comment] 2015-08-22 17:33
They were removed on purpose and the docs will be updated to reflect that shortly. See also #17029.

Duplicate of a number of issues like #17121 and more

**Comment by Qqwy** [comment] 2015-08-22 17:39
Thank you for your reply! Excuses for re-opening an issue that was already reported.

**Comment by kkirsche** [comment] 2015-08-22 17:53
No worries. Thanks for reporting :smiley: we appreciate the help catching all of these bugs :+1:

**Closed** 2015-08-22 20:26 UTC
