### ISSUE TITLE
Tooltips disposing themselves on mouseover if animation is not complete

### ISSUE THREAD

**Issue by danjudgemusic** [twbs/bootstrap#33032] opened 2021-02-10 00:15 UTC
**Operating System:** macOS Big Sur 11.1
**Browser:** Chrome (Version 88.0.4324.146)

**Bootstrap v5.0.0-beta1**  (Can't recreate in 4.6)

When initialising a tooltip on an inline-block element via an on click, it's appears to work, but when you mouseover the element with the attached tooltip, mouseout, then quickly mouseover just before the tooltip is fully faded out, the tooltip no longer shows. You also can't dispose it. Below is my code which I'm using to initialise the tooltip.

I apologise in advance if this is incorrectly posted in any way, this is my first time.

https://codepen.io/danjudgemusic/pen/eYBdBYL

**Comment by XhmikosR** [comment] 2021-02-10 04:42
Duplicate of #32372

**Closed by XhmikosR** 2021-02-10 04:42 UTC
