### ISSUE TITLE
Feature Request: .card-img-left / .card-img-right

### ISSUE THREAD

**Issue by michaelkrieger** [twbs/bootstrap#23987] opened 2017-09-18 16:55 UTC
Currently you can have a card with an image on top or bottom, but not to the left (as is typical).

Requesting that card-img-left and card-img-right be added, getting your very typical box with some text and an image to the left or right on desktops and as a top-cap on mobile.

Example Desired Behaviour:
```
-----------------------------
| img  |  Title                     |
| img  |  Text text text text |
| img  |  Button                 |
-----------------------------
```

Example Code Using Columns instead of cards of what I want to do:
```
					<div class="container">
						<div class="row align-items-center">
							<div class="col-12 col-md-6"><img width="100%" alt="Grandfather with child" src="image.jpg" sizes="(max-width: 660px) 100vw, 660px"></div>
							<div class="col-12 col-md-6">
								<h3>Title</h3>
								<p>Copy</p>
								<a class="btn btn-primary my-3 btn-block" href="/contact/">Contact Us</a>
							</div>
						</div>
					</div>
```

Possible solutions in BS4 solutions explored
**Media Left**
This looks great at full width, however as the viewport shrinks, the image stays the same size and the text stays on the right shifting further right.  If done in a card, this would stack when the width gets too small.

```
<div class="media">
   <img class="media-left" width="400" alt="Image" src="image.jpg">
   <div class="media-body">
      <h4 class="card-title">Title</h4>
      <p class="card-text">Copy</p>
      <a class="btn btn-primary my-3 btn-block" href="/contact/">Contact Us</a>
   </div>
</div>
```

**Float Left**
Doesn't seem to work for this image

**Comment by andresgalante** [comment] 2017-09-18 19:01
@gijsbotje that's cool, I'll review it

**Comment by mdo** [comment] 2017-10-02 05:07
Duplicate of #20794.

**Closed by mdo** 2017-10-02 05:07 UTC
Labels: css, v4

**Comment by yoohyunseog** [comment] 2018-05-08 23:27
thank you
