### ISSUE TITLE
npm package for 4.0.0-alpha.3 has wrong 'main' field in package.json

### ISSUE THREAD

**Issue by Malgin** [twbs/bootstrap#20480] opened 2016-08-07 13:40 UTC
npm package for 4.0.0-alpha.3 is missing ./dist/js/npm.js file, while it is specified as entry point in package.json ('main' field). 

This, for example, causes [node-resolve](https://github.com/substack/node-resolve) to fail when trying to resolve bootstrap.

This was introduces by PR #20072, but as I understand, author just forgot to change entry point.

This bug is really frustrating, as it stops people from using latest bootstrap with e.g. this great Angular2 tutorial: https://github.com/AngularClass/angular2-webpack-starter/issues/215

**Comment by cvrebert** [comment] 2016-08-07 16:46
Duplicate of #20383

**Closed by cvrebert** 2016-08-07 16:46 UTC
