### ISSUE TITLE
0.1em gap between -up and -down breakpoints

### ISSUE THREAD

**Issue by loglow** [twbs/bootstrap#18886] opened 2016-01-14 03:39 UTC
I'm quite new to Bootstrap, so forgive me if I've missed something here, and thanks in advance.

It looks like there's a 0.1em gap between the media-breakpoint-up and -down definitions, for example:

    @media (min-width: 34em)
    @media (max-width: 33.9em)

These gaps appear to result in these little in-between zones of a few pixels where the layout might use a hybrid of two different breakpoints (often garbling the page pretty badly) when resizing a browser window, if both up and down breakpoints are being used at the same time.

Seems like a simple fix would be to give extra precision to the max-width values, for example:

    @media (min-width: 34em)
    @media (max-width: 33.99999999em)

Please let me know what you think, and thanks again.

**Comment by cvrebert** [comment] 2016-01-14 07:52
Duplicate of #18414.

**Closed by cvrebert** 2016-01-14 07:52 UTC
