### ISSUE TITLE
btn-outline-light

### ISSUE THREAD

**Issue by pyojo** [twbs/bootstrap#23398] opened 2017-08-14 00:25 UTC
Both the inside of the button, the border and the text are white.

![image](https://user-images.githubusercontent.com/30057178/29254564-b196adc4-806d-11e7-896d-1e618c6786d3.png)

**Comment by mdo** [comment] 2017-08-14 05:34
Duplicate of #23351.

**Closed by mdo** 2017-08-14 05:34 UTC
Labels: css, v4
