### ISSUE TITLE
dropdown-menu - background-color active error

### ISSUE THREAD

**Issue by scadox** [twbs/bootstrap#23919] opened 2017-09-11 13:28 UTC
Hi team,

i have found a ( bug ) when use **dropdown-menu** with class **dropdown-menu-right**.

Open this picture attachment file for have a example. The background class with :active overflow the parent element.

![botostrapissue](https://user-images.githubusercontent.com/10082315/30276539-309b3538-96d3-11e7-9135-f7b8b9c1cda6.png)

I use v4.0.0-beta.

Cordialement,
Matthew

**Comment by Johann-S** [comment] 2017-09-11 13:34
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Joyrex** [comment] 2017-09-15 15:53
I noticed this issue in Alpha 6, and this is how I fixed the issue:
`.dropdown-item {
   width: inherit;
}`

**Comment by mdo** [comment] 2017-10-18 21:29
Without a demo, we cannot reproduce and fix. Closing until we have one.

**Closed by mdo** 2017-10-18 21:29 UTC
Labels: awaiting reply, css

**Comment by scadox** [comment] 2017-10-18 22:55
Hi all,

sorry for long time to response. With the CSS fix ( .dropdown-item { width: inherit; } ) fix good the problem.

You can only append this fix to source project for prevent others users report this.

I verry like Bootstrap! Good job team.
