### ISSUE TITLE
text-light is being overridden by .table-striped odd row color

### ISSUE THREAD

**Issue by ryanmortier** [twbs/bootstrap#35220] opened 2021-10-18 16:50 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In Bootstrap `v5.1.1` the following works correctly and the table row color is using `text-light` color for odd rows:

```html
<table class="table table-striped">
    <tbody>
        <tr class="text-light"><td>Working - Text is using light color</td></tr>
        <tr class="text-light"><td>Working - Text is using light color</td></tr>
        <tr class="text-light"><td>Working - Text is using light color</td></tr>
    </tbody>
</table>
```

In Bootstrap `v5.1.2` the following no longer works:
```html
<table class="table table-striped">
    <tbody>
        <tr class="text-light"><td>Color being overridden by table-striped odd row</td></tr>
        <tr class="text-light"><td>Working because even rows aren't colored</td></tr>
        <tr class="text-light"><td>Color being overridden by table-striped odd row</td></tr>
    </tbody>
</table>
```

Is this an intentional change or is this a bug?

### Reduced test cases

v5.1.1 https://codepen.io/morty11/pen/vYJGVxX
v5.1.2 https://codepen.io/morty11/pen/mdMPzrO

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.1 and v5.1.2

**Comment by XhmikosR** [comment] 2022-01-13 19:28
Duplicate of #35158.

**Closed by XhmikosR** 2022-01-13 19:28 UTC
