### ISSUE TITLE
Date-picker height is not the same as other fields

### ISSUE THREAD

**Issue by cinqlair** [twbs/bootstrap#24375] opened 2017-10-14 19:57 UTC
With Bootstrap 4, I build a form with a date-picker and text inputs located to the right. I realized that date-picker and other fields don't have the same size. It's a pity because everything is so nice with Bootstrap !

[CodePen](https://codepen.io/anon/pen/WZYQWx?editors=1000) (Tx fabiofl)

The problem:
![screenshot from 2017-10-14 22-00-12](https://user-images.githubusercontent.com/25717685/31578924-63bd04b0-b12b-11e7-87eb-21a0190aed74.png)

The code :
```
<form>
    <div class="form-row my-0">
        <div class="form-group col-md-6">
            <input class="form-control" type="date" />
        </div>
        <div class="form-group col-md-3">
            <input class="form-control" type="text" />
        </div>
        <div class="form-group col-md-3">      
            <input class="form-control" type="text" />
        </div>
    </div>
</div>

```

**Comment by AmalJMathew** [comment] 2017-10-15 10:57
`<input class="form-control" type="text" style="width:50px" />`
Use style in your text boxes to adjust the width.

**Comment by Johann-S** [comment] 2017-10-16 07:21
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by fabiofl** [comment] 2017-10-16 16:48
In name of OP, here's a [CodePen](https://codepen.io/anon/pen/WZYQWx?editors=1000) based on Bootstrap's own form examples, modified to have a date input.

All inputs seem to have outerHeight equals to 38px while`input[type="date"]` have 42px.

Using Bootstrap 4.0.0-beta

**Comment by cinqlair** [comment] 2017-10-16 18:15
fabiofl, thank you for the CodePen. I totally agree with you : I don't like `height: 38px`. 

So I guess it's a bug ?

**Comment by alecpl** [comment] 2017-10-19 06:35
Looks like a dupe of #18842, though I confirm it's 4px in Chrome not 2px.

**Comment by mdo** [comment] 2017-10-19 15:27
Closing as duplicate.

**Closed by mdo** 2017-10-19 15:27 UTC
Labels: css, v4

**Comment by pawanmkr** [comment] 2021-07-06 13:50
**You can fix it with CSS,**
Select all the input tag at **once** and set the height.
