### ISSUE TITLE
Migration document incorrect - table-responsive

### ISSUE THREAD

**Issue by Braunson** [twbs/bootstrap#26449] opened 2018-05-03 19:29 UTC
So I'm following the 4.0 migration docs which tell me to:

> Responsive tables no longer require a wrapping element. Instead, just put the .table-responsive right on the <table\>

Awesome, so I manually replace all 100+ instances where it was wrapped. Now I got to test and this happens.

![](https://goo.gl/chdzwp)

So should they still be wrapped in 4.x or no? The docs [here](https://getbootstrap.com/docs/4.0/content/tables/) say to wrap them, the migration [here](https://getbootstrap.com/docs/4.0/migration/#tables) says there's no need anymore

**Comment by thatnini** [comment] 2018-05-04 11:39
They should still be wrapped.

Duplicate of [#25509](https://github.com/twbs/bootstrap/issues/25509)

**Comment by Braunson** [comment] 2018-05-04 12:51
While it may be a duplicate of a closed ticket, the issue still stands, the PR https://github.com/twbs/bootstrap/pull/25539 which is suppose to remove that line for some reason or another hasn't been applied to the live site.

**Comment by ysds** [comment] 2018-05-04 12:56
v4-alpha docs have been outdated. 

Please see https://getbootstrap.com/docs/4.1/migration/

**Closed** 2018-05-04 12:59 UTC
