### ISSUE TITLE
Live demo modal data-target

### ISSUE THREAD

**Issue by peterbenoit** [twbs/bootstrap#22934] opened 2017-06-29 15:26 UTC
This might save some headaches....

In the [Modal Live demo](https://v4-alpha.getbootstrap.com/components/modal/#live-demo), the button data-target does not match the id of the modal; so it doesn't work by default when you copy & paste it.

&lt;!-- Button trigger modal --&gt;
&lt;button type="button" class="btn btn-primary" data-toggle="modal" data-target="**#exampleModal**"&gt;
  Launch demo modal
&lt;/button&gt;

&lt;!-- Modal --&gt;
&lt;div class="modal fade" id="**myModal**" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"&gt;
  &lt;div class="modal-dialog" role="document"&gt;
    &lt;div class="modal-content"&gt;
      &lt;div class="modal-header"&gt;
        &lt;h5 class="modal-title" id="exampleModalLabel"&gt;Modal title&lt;/h5&gt;
        &lt;button type="button" class="close" data-dismiss="modal" aria-label="Close"&gt;
          &lt;span aria-hidden="true"&gt;&times;&lt;/span&gt;
        &lt;/button&gt;
      &lt;/div&gt;
      &lt;div class="modal-body"&gt;
        ...
      &lt;/div&gt;
      &lt;div class="modal-footer"&gt;
        &lt;button type="button" class="btn btn-secondary" data-dismiss="modal"&gt;Close&lt;/button&gt;
        &lt;button type="button" class="btn btn-primary"&gt;Save changes&lt;/button&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;

**Comment by michaelwoodew** [comment] 2017-06-29 16:06
fixed [https://github.com/twbs/bootstrap/pull/21671](url)

**Comment by mdo** [comment] 2017-06-29 16:16
Yes, dupe of #21665.

**Closed by mdo** 2017-06-29 16:16 UTC
