### ISSUE TITLE
Tooltip/popover shrinks if the trigger is near the right edge

### ISSUE THREAD

**Issue by cervengoc** [twbs/bootstrap#20576] opened 2016-08-25 10:07 UTC
If the trigger element is near the right edge of the document, the tooltip/popover shrinks to about its half. The issue happens when BS sets the `left` offset to center the tip to the trigger.

- OS: Windows 8.1 64bit
- Browser: Chrome latest, IE11

**Expected behavior:**

The tooltip/popover should keep it's width and adjust its `left` offset accordingly.

**DEMO**

http://www.bootply.com/DkdajVS3cl

**Comment by bardiharborow** [comment] 2016-08-26 08:15
Confirmed on `Mac OS X 10.11.5 Chrome 53.0.2785.80`.

**Comment by MAWAVANSMOOKEY** [comment] 2016-08-28 01:12
Leave a comment.NICE

**Comment by bardiharborow** [comment] 2016-08-29 05:29
I tested this on v4. The tooltip is [clipped by the window instead](https://jsbin.com/kocikex/1/edit?output).

**Comment by mdo** [comment] 2016-09-05 22:36
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Closed by mdo** 2016-09-05 22:36 UTC
Labels: js, v3

**Comment by cervengoc** [comment] 2016-09-06 07:22
@bardiharborow could you please open a new issue about the mentioned clipping using v4 (if there isn't one already)? Actually clipping is not the correct behavior either.

**Comment by bardiharborow** [comment] 2016-09-07 05:45
@cervengoc looks like it's already been reported in #17297.
