### ISSUE TITLE
Dropdown Menu not expanding in mobile

### ISSUE THREAD

**Issue by tomasts248** [twbs/bootstrap#30693] opened 2020-04-30 01:33 UTC
For some reason upon clicking in the submenu "servicios" on mobile screens nothing happens. Tried using the very same code of the docs, so the issue may be somewhere else.
url for debugging: https://www.molinozuniga.cl/
Do note this website has two menus: one for desktop and another for mobile.

**Comment by mdo** [comment] 2020-04-30 01:59
> Do note this website has two menus: one for desktop and another for mobile.

This seems to be your culprit :). Styles we modify for our core nav components are being affected by your custom nav. Closing here as this isn't something we can help with here since it's not a bug in our project.

**Closed by mdo** 2020-04-30 01:59 UTC

**Comment by tomasts248** [comment] 2020-04-30 02:33
Ok i understand that but any help at all? or wher should I ask?

**Comment by ffoodd** [comment] 2020-04-30 06:53
@tomasts248 You may try our Slack or StackOverflow.

**Comment by tomasts248** [comment] 2020-04-30 18:08
Okey thanks!
