### ISSUE TITLE
Checkboxes not vertically aligned with <label>

### ISSUE THREAD

**Issue by paulsperanza** [twbs/bootstrap#19160] opened 2016-02-11 21:31 UTC
See the form inline example with a check box at http://getbootstrap.com/css/#forms

**Comment by cvrebert** [comment] 2016-02-11 23:45
Approximate duplicate of #18797.

**Closed by cvrebert** 2016-02-11 23:45 UTC
Labels: css, v3

**Comment by paulsperanza** [comment] 2016-02-12 00:44
I can confirm that this happens only in windows in all browsers. It does not happen, in any browsers on a Mac Book Pro. Just in case this helps at all.
