### ISSUE TITLE
V4 docs for collapse accordion reference missing V3 panel-* classes

### ISSUE THREAD

**Issue by bpierson** [twbs/bootstrap#20482] opened 2016-08-08 01:40 UTC
In the docs page for Collapse ([http://v4-alpha.getbootstrap.com/components/collapse/](url)), the Accordion example references the old v3 `panel` classes.

**Comment by Starsam80** [comment] 2016-08-08 01:46
Duplicate of #18375

**Comment by cvrebert** [comment] 2016-08-08 03:54
@Starsam80 Thanks!

**Closed** 2016-08-08 03:54 UTC
