### ISSUE TITLE
sections ids containing dot cause scrollspy.js stops working

### ISSUE THREAD

**Issue by Reasno** [twbs/bootstrap#16054] opened 2015-03-13 06:36 UTC
At scrollspy.js line 50-60

> var href  = $el.data('target') || $el.attr('href')
> var $href = /^#./.test(href) && $(href)

Here scrollspy.js uses href as a selector to determine whether id=href exists. The problem is ids may contain dot(.) which is valid html. 

For example, if there is 
`<a href="#x.y"> `
in the nav and 
`<section id="x.y">` 
in the body, code will break. I suggest you guys escape href before passing it to jquery selector.

read more:
http://stackoverflow.com/questions/9930577/jquery-dot-in-id-selector

**Comment by cvrebert** [comment] 2015-03-13 10:45
Approximate duplicate of #14285.

**Closed by cvrebert** 2015-03-13 10:45 UTC
