### ISSUE TITLE
v4.0.0-alpha.6 card-deck css missing

### ISSUE THREAD

**Issue by joonkui95** [twbs/bootstrap#23137] opened 2017-07-22 09:58 UTC
`@media (min-width: 576px) {
    .card-deck .card:first-child {
        margin-left: 15px;
    }
    .card-deck .card:last-child {
        margin-right: 15px;
    }
}`
after add css then fixed
![image](https://user-images.githubusercontent.com/14049597/28490229-6336552a-6f07-11e7-9701-af205f8c0157.png)

![image](https://user-images.githubusercontent.com/14049597/28490232-6e45ebf6-6f07-11e7-94d5-bd4abb1ef3aa.png)

**Comment by mdo** [comment] 2017-07-23 03:13
Duplicate of #21976, which was already fixed in `v4-dev`. Alpha 6 doesn't have this change because it's an older release.

**Closed by mdo** 2017-07-23 03:13 UTC
Labels: css, v4
