### ISSUE TITLE
SassC::SyntaxError: Error: style declaration must contain a value

### ISSUE THREAD

**Issue by mayur-kambariya** [twbs/bootstrap#32019] opened 2020-10-30 14:32 UTC
![image](https://user-images.githubusercontent.com/25054175/97717390-bff36180-1aea-11eb-964b-6f3499bb0e42.png)

During deploy rails application on heroku

**Comment by mdo** [comment] 2020-10-30 15:58
This looks like any error on your part? Can't see anything that says Bootstrap is to blame here.

**Comment by rasbary** [comment] 2020-10-30 18:19
@mdo We're also seeing this, it appears that it was introduced in v4.5.1 with this change: https://github.com/twbs/bootstrap/pull/30957

You'll also see another comment on that issue reporting the same issue.

For now we're pinning at v4.5.0 to avoid this.

**Comment by ffoodd** [comment] 2020-10-30 20:21
Nullifying the value should not output the property. What's the Sass compiler you use?

**Comment by rasbary** [comment] 2020-10-30 20:36
> Nullifying the value should not output the property. What's the Sass compiler you use?

In our case Bootstrap (`bootstrap/scss/bootstrap.scss`) being passed through the newest release of the sassc-ruby gem, which it appears is using LibSass 3.6.1 for compilation.

For completeness, the error we're seeing:
```
SassC::SyntaxError: Error: style declaration must contain a value
        on line 8038:13 of stdin
>>   box-shadow:;

   ------------^
```

**Comment by mdo** [comment] 2020-10-30 21:32
Gotcha, we'll look into!

**Comment by XhmikosR** [comment] 2020-11-08 19:05
Have you tried reporting the issue upstream?

We only test node-sass and dart sass and we cannot guarantee things will work with other implementations.

**Comment by leoplct** [comment] 2020-11-13 19:47
We are having the same issue +1

**Comment by XhmikosR** [comment] 2020-11-14 06:16
https://github.com/twbs/bootstrap/issues/32019#issuecomment-723652058

**Comment by ThaisTMartins** [comment] 2020-11-19 13:05
I'm having the same error, I don't change any file of bootstrap and my application was working before (I'm using the version 4.4.1).

I only add gems wicked_pdf and wkhtmltopdf-binary to make a report with highchart. After this, when I precompile assets in production mode (RAILS_ENV=production bundle exec rails assets:precompile), I recive the same error of this issue.

![image](https://user-images.githubusercontent.com/52137845/99669825-67aae200-2a4e-11eb-9c8b-8055d50a293b.png)

Ruby version: 2.6.3
Rails version: 6.0.2

**Comment by ThaisTMartins** [comment] 2020-11-19 13:06
I'm having the same error, I don't change any file of bootstrap and my application was working before (I'm using the version 4.4.1).

I only add gems wicked_pdf and wkhtmltopdf-binary to make a report with highchart. After this, when I precompile assets in production mode (RAILS_ENV=production bundle exec rails assets:precompile), I recive the same error of this issue.

![image](https://user-images.githubusercontent.com/52137845/99670158-db4cef00-2a4e-11eb-923c-f0e4d34a5678.png)

Ruby version: 2.6.3
Rails version: 6.0.2

**Comment by XhmikosR** [comment] 2020-11-19 13:08
@ffoodd @MartijnCuppens @mdo: since people don't seem to report the issue upstream

1. we either report it upstream ourselves and hope they fix it
2. figure out if we can revert the offending change
3. ignore the issue since it's something we don't test nor use ourselves

**Comment by ffoodd** [comment] 2020-11-19 13:23
From my understanding:
1. @rasbary mentionned that the sassc-ruby gem used Libsass under the hood, and [Libsass is deprecated](https://sass-lang.com/blog/libsass-is-deprecated). So either we report 
   - upstream #1 (sassc-ruby gem) and suggest to switch to dart-sass
   - ~~upstream #2: Libsass compilation failure when nullifying a value (if it can be reproduced with Libsass directly)~~
2. @rasbary also spotted the offending PR (#30957) which can be reverted easily, with as single drawback to output a few useless `box-shadow: none`.

FYI: I tried things out [on Sassmeister](https://www.sassmeister.com/gist/c98a7b9560ed35123f435f7ad0512f86) and whatever compiler I use, nothing wrong happens.

**Comment by MartijnCuppens** [comment] 2020-11-19 13:39
Yeah, pretty weird it happens now, since we we've been using `null` variables for quite a while now (https://github.com/twbs/bootstrap/pull/28035)

**Comment by mdo** [comment] 2020-12-03 04:00
I think this is something we ignore and close as a won't fix? Seems like there's not much to change here and we're on Dart Sass now.

**Comment by XhmikosR** [comment] 2020-12-03 16:07
We also have #29760 FYI.

**Comment by mdo** [comment] 2020-12-03 21:28
Yeah, I say we close for that issue.

**Closed by mdo** 2020-12-03 21:28 UTC
Labels: 3rd-party, css, v4

**Comment by yoones** [comment] 2020-12-04 17:45
I have the same issue when I put `$enable-shadows: true;` in my scss file. Setting this to false doesn't trigger an error.

_yarn package.json: "bootstrap": "^4.5.3"_

**Comment by Frimlik** [comment] 2021-03-31 11:35
> I have the same issue when I put `$enable-shadows: true;` in my scss file. Setting this to false doesn't trigger an error.
> 
> _yarn package.json: "bootstrap": "^4.5.3"_

I think `$enable-shadows: true;` is the default value. At least I haven't found this command in my code.
I spent few days and sleepless nights implanting `node-sass-json-importer` into Angular 10 (to be able to use values from `json` file in `scss`) and this was my last obstacle...
But interesting thing for me was that when I looked at [#30957](https://github.com/twbs/bootstrap/pull/30957) and did "revert" in my local code (insert `none` instead of `null`), everything worked fine as well.

**Comment by wongwf82** [comment] 2022-11-14 06:44
This answer on SO worked for me:
https://stackoverflow.com/questions/70401077/rails-7-asset-pipeline-sasscsyntaxerror-with-tailwind/70665740#70665740

I put inside `production.rb` and deployment to Heroku was fine, while retaining `gem "sassc-rails"` in my Gemfile though.
