### ISSUE TITLE
Card footers are not at the bottom when using decks

### ISSUE THREAD

**Issue by jshthornton** [twbs/bootstrap#18905] opened 2016-01-15 02:20 UTC
![image](https://cloud.githubusercontent.com/assets/2814746/12343760/9c92c34e-bb71-11e5-90dd-30312e023aeb.png)

**Comment by petetnt** [comment] 2016-01-15 08:01
Dupe of #17134, the issue also contains a workaround :+1:

**Comment by cvrebert** [comment] 2016-01-16 09:40
Closing as dupe.

**Closed by cvrebert** 2016-01-16 09:40 UTC
Labels: confirmed, css, v4
