### ISSUE TITLE
Resize examples screenshots

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#29030] opened 2019-07-13 11:32 UTC
It seems after some recent changes, the examples screenshots dimensions have changed.

We shouldn't have bigger images than what we need them to be.

**Comment by mdo** [comment] 2019-07-13 20:44
Agreed, but let's wait on this until we're much closer to release. I'm not 100% on the design and layout just yet.

**Comment by kodeGenius** [comment] 2019-07-26 19:54
Hi all, anyone working on this?  I'll be glad to take it on.

**Comment by mdo** [comment] 2020-09-24 02:56
Closing as a duplicate of #30286 just to consolidate.

**Closed by mdo** 2020-09-24 02:56 UTC
Labels: docs, examples, v5
