### ISSUE TITLE
Offcanvas triggering element problem

### ISSUE THREAD

**Issue by subliminalhash** [twbs/bootstrap#33614] opened 2021-04-13 05:34 UTC
The problem is when there is a FontAwesome icon within the triggering anchor element for the offcanvas. 

When clicking on the element e.g. hamburger icon, backdrop appears and disappears very quickly without revealing the offcanvas div. However when clicked outside of the <i> element and within the boundaries of the anchor, then offcanvas appears successfully. So I am guessing it might be something related to bubbling?

Case link:
https://jsfiddle.net/kemalemin/eyd89grm/

I am on a Windows 10 machine.
Tested on:
- Vivaldi 3.7.2218.45 (Stable channel) (64-bit)
- Chrome 89.0.4389.114 (Official Build) (64-bit)
- Brave 1.22.71 Chromium: 89.0.4389.114 (Official Build) (64-bit)
- Edge 89.0.774.75 (Official build) (64-bit)

**Comment by mdo** [comment] 2021-04-13 17:36
Duplicate of #33457.

**Closed by mdo** 2021-04-13 17:36 UTC
