### ISSUE TITLE
the Collapse have a problem

### ISSUE THREAD

**Issue by h492831190** [twbs/bootstrap#30651] opened 2020-04-27 06:42 UTC
1. 

/show|hide/.test(config)   there have a problem,  change to /show|hide/.test(config.toggle)

2.
Collapse._jQueryInterface = function _jQueryInterface(config) {
      return this.each(function () {
        var $this = $(this);
        var data = $this.data(DATA_KEY$3);

        var _config = _objectSpread2({}, Default$1, {}, $this.data(), {}, typeof config === 'object' && config ? config : {});

        if (!data && _config.toggle && /show|hide/.test(config)) {
          _config.toggle = false;
        }

        if (!data) {
          data = new Collapse(this, _config);
          $this.data(DATA_KEY$3, data);
        }

        if (typeof config === 'string') {
          if (typeof data[config] === 'undefined') {
            throw new TypeError("No method named \"" + config + "\"");
          }

          data[config]();
        }
      });

3. error infomation
Uncaught TypeError: Cannot convert object to primitive value
    at RegExp.test (<anonymous>)
    at HTMLDivElement.<anonymous> (app.js:3449)
    at Function.each (app.js:6853)
    at jQuery.fn.init.each (app.js:6675)
    at jQuery.fn.init._jQueryInterface [as collapse] (app.js:3443)
    at HTMLDivElement.<anonymous> (app.js:3503)
    at Function.each (app.js:6853)
    at jQuery.fn.init.each (app.js:6675)
    at HTMLButtonElement.<anonymous> (app.js:3498)
    at HTMLDocument.dispatch (app.js:11901)

**Comment by InsanityMeetsHH** [comment] 2020-04-27 06:49
Don't use jQuery 3.5.0 currently. Switch back to 3.4.1.
https://github.com/twbs/bootstrap/issues/30553
https://github.com/twbs/bootstrap/pull/30559/files

**Comment by XhmikosR** [comment] 2020-04-27 08:40
Duplicate of #30553

**Closed by XhmikosR** 2020-04-27 08:40 UTC
