### ISSUE TITLE
Missing right border-radius when using valid-feedback or invalid-feedback with input-group

### ISSUE THREAD

**Issue by francoisrouault** [twbs/bootstrap#30116] opened 2020-02-01 11:06 UTC
# Describe the bug

Missing right (top and bottom) `border-radius` when using `valid-feedback` or `invalid-feedback` with `input-group`.

# To Reproduce

Go and see Username input field in bootstrap official documentation : https://getbootstrap.com/docs/4.4/components/forms/?#custom-styles

# Reproducible Example

Live example here : https://getbootstrap.com/docs/4.4/components/forms/?#custom-styles

JSFiddle : https://jsfiddle.net/7am1xfnq/

Sample code :
```
    <div>
      <label for="validationCustomUsername">Username</label>
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroupPrepend">@</span>
        </div>
        <input type="text" class="form-control" id="validationCustomUsername" aria-describedby="inputGroupPrepend" required>
        <div class="invalid-feedback">
          Please choose a username.
        </div>
      </div>
    </div>
```

# Expected behavior

We should see a right border radius (top and bottom).

# Screenshots

<img width="1440" alt="Capture d’écran 2020-02-01 à 11 09 45" src="https://user-images.githubusercontent.com/2499356/73590694-a387b180-44e5-11ea-8a73-0ddaf28747ab.png">

<img width="1440" alt="Capture d’écran 2020-02-01 à 11 10 57" src="https://user-images.githubusercontent.com/2499356/73590666-4e4ba000-44e5-11ea-8dc9-5185d30f2263.png">

# Environment
Operating System: macOS 10.15.2
Browser, Version : Chrome 78.0.3904.108 (Build officiel) (64 bits)
Bootstrap Version : 4.4.1

**Comment by flayestdev** [comment] 2020-02-01 15:12
According to the source code the input child of  input-group is styled to have a 0 border-radius, I don't know if it's the effective visual style for the input-group or not.
What I noticed is maybe it's hard coded to support both input-group-prepend directions, because the side where the two element meet they should be styled with 0 border-radius.

**Comment by flayestdev** [comment] 2020-02-01 15:30
I find where is the issue, the style try to target the last element with the selector last-child, but if the feedback element is present, it's the element that is affected by the style, I found a work around using the two selectors each for case (first-child / "next-sibling")

**Comment by mdo** [comment] 2020-02-03 22:45
Duplicate of #25110.

**Closed by mdo** 2020-02-03 22:45 UTC
