### ISSUE TITLE
Clipboard "Copy" buttons in docs aren't styled correctly

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#18438] opened 2015-12-05 10:09 UTC
#17751 appears to have broken the positioning and hover-coloring of the clipboard "Copy" buttons in the docs.

Old styling:
<img width="177" alt="old-copy" src="https://cloud.githubusercontent.com/assets/419884/11607271/11730568-9af5-11e5-9c55-8976126360f6.png">

Current styling:
<img width="119" alt="new-copy" src="https://cloud.githubusercontent.com/assets/419884/11607273/173e5b3c-9af5-11e5-8ba6-6410195ec4b6.png">

CC: @XhmikosR

**Comment by XhmikosR** [comment] 2015-12-05 10:15
Yeah, I noticed that too, but are you 100% sure it was #17751 that broke it?

I'll try to fix it unless someone else beats me to it.

**Comment by cvrebert** [comment] 2015-12-05 10:21
Yes, I'm sure. I `git bisect`-ed.

**Comment by XhmikosR** [comment] 2015-12-05 10:22
OK, I found the cause.

On a side note, I miss `jekyll s` not reloading when the sass files change :/ Makes things harder to develop.

**Comment by cvrebert** [comment] 2015-12-05 10:26
Agreed, having to remember the `grunt copy:docs` step is annoying.

**Comment by mdo** [comment] 2015-12-08 05:51
Fixed in 4520b0f.

**Closed by mdo** 2015-12-08 05:51 UTC
Labels: confirmed, docs, v4
