### ISSUE TITLE
Bootstrap 4 collapsible navbar smooth closing animation (navbar-toggleable)

### ISSUE THREAD

**Issue by janssh** [twbs/bootstrap#17990] opened 2015-10-20 14:58 UTC
The [bootstrap 4 collapsible navbar](http://v4-alpha.getbootstrap.com/components/navbar/#collapsible-content) doesn't contain a smooth closing animation as you can see in the link. The opening animation is just fine, but the closing animation doesn't exist. How can I add a smooth closing animation ?

A code example on bootply.com can be found here:
[code](http://www.bootply.com/KpPQFhR1Gb#)
[preview](http://www.bootply.com/render/KpPQFhR1Gb#) (on xs screen width)

**Comment by twbs-lmvtfy** [comment] 2015-10-20 14:58
Hi @janh92!

You appear to have posted a live example (http://s.bootply.com/render/KpPQFhR1Gb), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 39, column 9: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by janh92** [comment] 2015-10-20 15:01
Fixed!

**Comment by iliasch** [comment] 2015-10-20 15:37
What do you mean? The closing animation looks smooth on my browser. Can you try it on another browser and check the console log for errors?

**Comment by janh92** [comment] 2015-10-20 15:59
You can see the problem here:
http://screencast.com/t/QIsdYKG8Dbg2

**Comment by iliasch** [comment] 2015-10-20 18:06
Did you try it on Safari? How about a mobile device? Works properly on Firefox/Windows, so it's something about your configuration.

**Comment by janh92** [comment] 2015-10-20 18:27
How could that be? I tested it on multiple other devices and get the same problem. 

OSX El Capitan, newest Firefox
OSX El Capitan, newest Chrome
OSX El Capitan, newest Safari
Windows 10, newest firefox
Windows 10, newest Chrome
Iphone 6, newest Safari

Maybe you didn't scroll down to the correct navbar example on bootstrap 4 docs?
The navbar closes really fast without a smooth animation.

**Comment by tshinnic** [comment] 2015-10-20 19:03
I believe I am also seeing what @janh92 is reporting.  In the section [/components/navbar/#collapsible-content](http://v4-alpha.getbootstrap.com/components/navbar/#collapsible-content) but *not* the example titled "Collapsible content". Rather the next example - last example on the page - second example in that section - which can show up as titled "Responsive navbar" on wider screens.

On both Android and latest source, and Firefox 41 squished thin, the hamburger expands nicely when clicked, then basically snaps shut when clicked again.

I have seen comments elsewhere that navbar's are very much an "in-progress" feature ?

**Comment by iliasch** [comment] 2015-10-20 19:09
Yes, it's visible only on xs devices and thus missed it, but it's replicated even after you remove the hidden-sm-up class, so there is a bug somewhere. Investigating...

**Comment by sceendy** [comment] 2015-10-20 19:13
Yeah, I see it too. If you change the inner content from the list and link to the example above it, it works fine.

**Comment by janh92** [comment] 2015-10-20 19:33
@sceendy I can't confirm that adding `.text-block` to the unordered list solves the problem.
I tested it on Chrome 46, OSX.

**Comment by sceendy** [comment] 2015-10-20 20:01
Sorry, yeah, just removed the classes the unordered list was using. Looks like @iliasch has a fix :+1:

**Comment by iliasch** [comment] 2015-10-20 20:01
This bug was nasty, but eventually found it. If you use dist files, open bootstrap.js / line 1170 and deleted (does nothing useful, just messed up with the calculated height). If you use src files, look at the pull request above.

**Comment by iliasch** [comment] 2015-10-20 22:31
I'm still investigating whether this is the best solution. Alternatively you can just encase your collapsible content within a .container to get proper behavior. Theoretically, you always need a container, even though it does seem weird.

**Comment by Deilv** [comment] 2015-10-25 19:34
@cvrebert I believe you can close this, because this bug is caused by browser inconsistencies and after thoroughly testing I couldn't find a proper solution. Using a container to wrap the contents of the collapsible element seems to be the most reasonable solution at the moment.

**Comment by fredericlefeurmou** [comment] 2015-11-15 18:41
It doesn't work on chromium `Version 45.0.2454.101 Ubuntu 14.04 (64-bit)`

**Comment by janannedehaan** [comment] 2016-02-04 13:19
It does work, but when you open the menu on mobile-view and resize back to desktop-view, the menu height will not resize back to normal.

**Closed** 2016-10-19 08:00 UTC
Labels: css, v4

**Comment by mdo** [comment] 2016-10-19 08:02
Resolved in #19890.
