### ISSUE TITLE
custom-select menu arrows missing in Firefox on v4-alpha5

### ISSUE THREAD

**Issue by rhinoman** [twbs/bootstrap#20991] opened 2016-10-24 20:34 UTC
Since updating to Bootstrap v4-alpha-5, I've noticed that the little up-down arrows on the `select.custom-select` menus have disappeared in Firefox.  IE, Edge, and Chrome still appear to work.

Info:
Windows 10
Firefox 49.0.2
JSFiddle: https://jsfiddle.net/hy74z6gh/

This problem is also visible in the Bootstrap alpha documentation page: http://v4-alpha.getbootstrap.com/components/forms/#select-menu

**Comment by patrickhlauke** [comment] 2016-10-25 00:51
Duplicate of https://github.com/twbs/bootstrap/issues/20956

**Closed by patrickhlauke** 2016-10-25 00:51 UTC
