### ISSUE TITLE
Small display issue on a dropdown form control

### ISSUE THREAD

**Issue by PatrikFomin** [twbs/bootstrap#23998] opened 2017-09-19 08:41 UTC
I could not find it in here and i don't know if it belongs in here or if its just an issue with Bootstraps own website. The text for "Large select" looks a bit weird.
https://getbootstrap.com/docs/4.0/components/forms/

I am using Windows 10 on my Laptop with the version 60.0.3112.113 of Chrome installed. No specific test case, was just browsing using a Chrome window of about 60% wide of a 1920x1080 screen.

![bootstrap form](https://user-images.githubusercontent.com/18208521/30583182-8b4e56c8-9d26-11e7-8b4d-196ac2d41387.PNG)

**Comment by Johann-S** [comment] 2017-09-19 09:39
Duplicate of : https://github.com/twbs/bootstrap/issues/23769

**Closed by Johann-S** 2017-09-19 09:39 UTC
Labels: css, v4
