### ISSUE TITLE
Input group with multiple dropdown buttons uses first ul list only

### ISSUE THREAD

**Issue by thewongandonly** [twbs/bootstrap#36876] opened 2022-08-01 14:53 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Looking at https://getbootstrap.com/docs/5.2/forms/input-group/#buttons-with-dropdowns you see an example with 2 buttons. This example will always show the first list found in input group, making the second one useless.

### Reduced test cases

introduce an id attribute to refer to

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2

**Comment by GeoSot** [comment] 2022-08-01 15:12
Duplicate of #36803

**Closed by GeoSot** 2022-08-01 15:12 UTC
