### ISSUE TITLE
Border-color of form feedback success/warning/error states cannot easily be changed

### ISSUE THREAD

**Issue by JelteF** [twbs/bootstrap#17718] opened 2015-09-27 17:21 UTC
For some reason the border-color argument uses the same color as the text. Which results in very dark borders, especially when focussed. When you want to change this it requires calling of the mixin again, instead of just changing a color variable. See these two snippets for the code in question:
- https://github.com/twbs/bootstrap/tree/master/less/forms.less#L427-L436
- https://github.com/twbs/bootstrap/blob/master/less/mixins/forms.less#L6-L40
And see this for an example of dark borders: http://getbootstrap.com/css/#forms-control-validation

The main suggestion is the usage of another variable for this so it can at least be changed without changing the text. The second is changing the default to make it lighter. 

There already is a variable called `$state-warning-border`, but that is too light to use as border color for inputs. If that would be made darker it could be used for all.

I could try to add this myself, but I would first like to know what idea you think is best.

**Comment by cvrebert** [comment] 2015-09-27 20:11
Duplicate of #12731.

**Closed by cvrebert** 2015-09-27 20:11 UTC
Labels: css, v3

**Comment by JelteF** [comment] 2015-09-27 22:19
To be clear, I'm not suggesting changing it to the `-border` variant. My main change would be just a separate variable, which can default to the value of the `-text` variant of the variables. Just so it is not necessary to call the mixin for all cases, but it is possible to change a default variable.

**Comment by cvrebert** [comment] 2015-09-27 22:25
CC: @mdo

**Comment by JelteF** [comment] 2015-11-08 22:56
Can this be reopened or get a response?

**Comment by cvrebert** [comment] 2015-11-08 23:02
"Nothing will change here until v4" -- https://github.com/twbs/bootstrap/issues/12731#issuecomment-51951553

**Comment by JelteF** [comment] 2015-11-08 23:03
But my change can be done fully backwards compatible.

**Comment by kkirsche** [comment] 2015-11-08 23:30
I think what is failing to be explained by the team @JelteF isn't that this is a feature which isn't implementable in a manner that is backwards compatible but rather has failed to mention that active development of V3 has ended and V3 is in support-only mode until an unknown date (tbd by core team) at the moment with only severe bug fixes being addressed.

At this point all feature requests, implementations, etc are to be done against V4. Patches for your own repositories or forks of V3 are also always an option though neither would have the core team's support and would be your own / with the assistance of the community (eg stackoverflow)

**Comment by JelteF** [comment] 2015-11-09 00:13
Ah alright, thanks for the explanation.
