### ISSUE TITLE
Bootstrap 4.1.1 input-group issue

### ISSUE THREAD

**Issue by lugavin** [twbs/bootstrap#26665] opened 2018-06-05 13:47 UTC
When add some validation messages inside the input group, the **border-(top|bottom)-right-radius** style of form control doesn't work.  Code see: https://jsfiddle.net/lugavin/aserqdx4/1/

![issue](https://user-images.githubusercontent.com/28991162/40979942-cc131d56-6909-11e8-8150-68d05938eccf.JPG)

**Comment by alecpl** [comment] 2018-06-05 15:38
This is duplicate of #25110.

**Comment by Johann-S** [comment] 2018-06-11 08:18
Closed as duplicate 👍 thanks @alecpl

**Closed by Johann-S** 2018-06-11 08:18 UTC
