### ISSUE TITLE
Web site getbootstrap.com

### ISSUE THREAD

**Issue by iPrior** [twbs/bootstrap#21051] opened 2016-10-31 10:32 UTC
Hi,
I can not open the site (getbootstrap.com) - error timed out
Ping, nslookup and traceroute works correctly
I have to use an anonymous proxy server for access to site. 
It is inconvenient =\

My IP address 194.190.24.2

**Comment by patrickhlauke** [comment] 2016-10-31 10:38
Cannot reproduce. What location are you trying to access this from? Any particular browser/configuration that may be causing problems?

**Comment by iPrior** [comment] 2016-10-31 10:41
I used FireFox and Google Chrome
I think access is closed over IP

**Comment by iPrior** [comment] 2016-10-31 10:52
![dis_proxy](https://cloud.githubusercontent.com/assets/3328595/19851881/2b5381de-9f71-11e6-9714-3dff8c19dcc9.png)
![enb_proxy](https://cloud.githubusercontent.com/assets/3328595/19851882/2b56397e-9f71-11e6-83f7-2aaf5f914d5f.png)

**Comment by iqbalaqaba** [comment] 2016-10-31 11:13
@iPrior maybe it's blocked on your country ?

**Comment by iPrior** [comment] 2016-10-31 11:19
@iqbalaqaba no =)
my friends can open the site =\
maybe my provider is blocked site...

**Comment by iqbalaqaba** [comment] 2016-10-31 11:58
@iPrior maybe yes, have you check to open the site with wifi ?

**Comment by iPrior** [comment] 2016-10-31 12:19
support of provider says that they nothing blocked
I can open site on my smartphone (3G)
If your hosting provider does not block my IP address, then can be thought of that this is magic and close this issue =)

**Comment by iqbalaqaba** [comment] 2016-10-31 12:21
Woah glad to hear that! yess, please someone close this issue.

**Closed** 2016-10-31 12:57 UTC
