### ISSUE TITLE
Responsive font sizes

### ISSUE THREAD

**Issue by MartijnCuppens** [twbs/bootstrap#23053] opened 2017-07-12 09:13 UTC
Currently there is no font-resizing implemented in Bootstrap. Font-resizing is needed to make large texts readable on all devices and to prevent longer words and [compounds](https://en.wikipedia.org/wiki/Compound_(linguistics)) to fall off screen. 

It's currently possible to alter the font-size of the html element with media queries (see [Responsive typography](https://getbootstrap.com/docs/4.1/content/typography/#responsive-typography)), but this method can cause the font-size of text to be too small on mobile devices and because the rem-value is overridden, users can't change their font-size in their browser anymore.

[RFS](https://github.com/MartijnCuppens/rfs) can solve this by because this mixin automatically calculates the appropriate font-size based on the width of the device. 

RFS is also available in Sass, Less, PostCSS and Stylus.

**Example problem with bigger font-sizes:** 
http://getbootstrap.com/docs/4.1/content/typography/#display-headings

**RFS solution:**
https://project-rfs.github.io/bootstrap/docs/4.1/content/typography/#display-headings

**Bootstrap implementation demo:** 
https://project-rfs.github.io/bootstrap/

**Github page:** 
https://github.com/project-rfs/rfs

**Pull request**
https://github.com/twbs/bootstrap/pull/23816

**Comment by gijsbotje** [comment] 2017-07-12 15:25
would love this feature, how do you suggest implementing this though?
what would be my first thought is a class that can be added to the `html` element, like `.responsive-font-size`

and would you rather have responsive or [fluid](https://madebymike.com.au/writing/fluid-type-calc-examples/) font size?

just some questions that pop in to my head

**Comment by MartijnCuppens** [comment] 2017-07-12 16:20
@gijsbotje, for the demo I changed the font-sizes in the `_variables.scss`-file into unitless numbers like this:

```
$font-size-h1: 40 !default;
$font-size-h2: 32 !default;
$font-size-h3: 28 !default;
$font-size-h4: 24 !default;
$font-size-h5: 20 !default;
$font-size-h6: 16 !default;
```

In the `.scss`-files I changed the `font-size` -declarations to the RFS-mixin:
```
h1, .h1 { @include rfs($font-size-h1); }
```

It's also still possible to use fixed values like `15px` or `1.25rem` by passing them to the mixin.

<br>
So at this moment there is not really a way to enable/disable it per page. However it is possible to alter the mixin by adding a class inside it.

The mixin generates a fluid font size below the rfs-breakpoint, above this breakpoint it would be static (the explanation in detail can be read in the blogpost, https://blog.intracto.com/rfs-automated-scss-responsive-font-sizing)

**Comment by kimamil** [comment] 2017-07-15 01:35
Basically, everything is set for this! The only thing missing is to use the äfont-size-<whatever> to be set as the html font-size. Don't make this bigger than it is...

Use rem to define the the rythm of the font in mobile (as bootstrap is mobile first) an then adapt the base font size for bigger screens. If you wanna go fancy, allow to set different ratiosfor each breakpoint (bit that's simply not what bootstrap is about). Set a rythm, scale it, and we're fine out here...

**Comment by MartijnCuppens** [comment] 2017-07-15 09:53
Thanks for the input @kimamil. The problem with that approach is that you scale every font-size linear and that means the smallest text will become hard to read. For example, if we take the narrow jumbotron example:
https://v4-alpha.getbootstrap.com/examples/narrow-jumbotron/

If we want to let the title to fit in it's container, we need to set the html font-size to 12px. The result of this is that all the normal text-elements will also have a font-size of 12px and that might be a little to small.

Of course we can just make an exception for that case, and maybe another case and after all, we still need a lot of manual testing to check if there are some edge-cases we need to fix. 

Bootstrap is also a framework that is widely used over the world and in some languages a lot of compounds (https://en.wikipedia.org/wiki/Compound_(linguistics)) are used causing longer words and font resizing problems. I speak Dutch myself and I frequently came across these circumstances where I needed to manual test and rescale the font-size while keeping in mind I don't set the font size to small to keep a visual difference between titles and text.

**Comment by MartijnCuppens** [comment] 2017-07-19 18:37
At this moment I use unitless numbers for the configuration like: 
```
$font-size-h1: 40 !default;
```

This might be a little bit confusing for those who do not know what it means. Should we switch (back) to `px` for font sizes if we implement RFS in bootstrap?

**Comment by kimamil** [comment] 2017-07-20 19:44
@MartijnCuppens I see, I was a bit overenthusiastic. If it will be a new feature for a next version I guess an overhaul of some current elements/components might be worth it?

As I understand bootstrap it is delivered with a default configuration that works for most, maybe not any language. A customized version can be downloaded, or the ones that need more customization probably work with sass anyway.

So testing and finding a good default value might be easier, if a default language or set of languages is defined? If you need anybody helping testing or so, I might find some time.

Good Luck with implementing.

**Comment by XhmikosR** [comment] 2017-07-21 08:14
Is there a PR for this I'm missing? I too find it pretty useful and I'd like to have a look at a PR.

**Comment by MartijnCuppens** [comment] 2017-07-21 08:33
@XhmikosR, I'll make a fork of bootstrap with the RFS implementation this weekend, I'll link to it here. A fork might be more interesting so we can test multiple implementations and configurations of RFS. As pointed out by @kimamil, some elements/components might need to be overhauled.

Once we have a solid implementation with documentation I'll make a PR. 

I'll keep you posted about further development.

**Comment by MartijnCuppens** [comment] 2017-07-22 13:28
Fork available here: https://github.com/MartijnCuppens/bootstrap/tree/rfs

**Comment by XhmikosR** [comment] 2017-07-24 16:30
@mdo: what is your first opinion on this?

**Comment by MartijnCuppens** [comment] 2017-07-24 17:30
The current implementation in the fork has:
- Configuration in px
- Option to quickly enable/disable responsive font sizes (`$enable-responsive-font-sizes`).
- A new documentation page for responsive font sizes.

**Comment by Jakobud** [comment] 2017-09-18 05:00
### Accessibility Warning

Just FYI folks, when you start using `vw` units for font sizes (even in a `calc()`), accessibility goes out the window. In other words, your font will no longer resize when you change the font size in the browser. In a `calc()` the level of scaling that is lost is dependent on the pixel value that is paired with the `vw` value. But the problem is still there. And since pretty much every calculated value in Bootstrap is based off of `rem`s, if you use `vw` anywhere in the base font value, then accessible scaling of the entire interface is going to suffer.

Bootstrap has always maintained keeping accessibility in the forefront and it would be nice to keep it that way. Definitely something to keep in mind if you are considering using `vw` units for fonts.

But if that is the road that the team is going down, I would also recommend [this method](https://medium.com/@jakobud/css-polyfluidsizing-using-calc-vw-breakpoints-and-linear-equations-8e15505d21ab) (also [republished on Smashing Magazine](https://www.smashingmagazine.com/2017/05/fluid-responsive-typography-css-poly-fluid-sizing/)) that I came up with earlier this year, which is simplified and allows you to fluidly scale multiple font sizes across multiple breakpoints instead of one linear scale.

**Comment by MartijnCuppens** [comment] 2017-09-18 07:52
Hi @Jakobud,

Thanks for the feedback. The method you mentioned is indeed a great method, however the complexity of font-resizing increases drastically. Also [RFS](https://github.com/MartijnCuppens/rfs) will automatically take care of relations between font-sizes, with mappings you need to look out for this manually.

The rendering of the font-sizes can also be changed to change to `rem`-units in combination with `vw`-units (with `$rfs-minimum-font-size-unit: rem`) so the font-size will resize if the browsers' default font-size is changed. However, this prevents the developer from scaling gutter-widths which are set in rem-units.

**Comment by MartijnCuppens** [comment] 2017-11-15 20:59
- In the latest PR (#23816) I used a `font-size()` mixin which is an alias for `rfs()` which is a bit easier for developers to understand.
- Font-sizes are configured and rendered in `rem` units. 
- The minimum font-size is set to `.875rem` (14px).
- The breakpoint is set to `1200px`, screens with a smaller size will have dynamic rescaling.
- The factor which determines the strength of font size resizing is set to `5`.

**Comment by wujekbogdan** [comment] 2017-12-28 19:40
The idea of having responsive typography is great, but IMO the approach discussed in this thread isn't correct. This approach can ruin the [vertical rhythm](https://zellwk.com/blog/why-vertical-rhythms/) which is a huge typography concern. Font sizes and line height should depend only on breakpoints, never on the screen size. 

The lack of properly set up vertical rhythm has always been a problem in Bootstrap. That's why I've been using [Gridlover](https://www.gridlover.net/try) tool and its SCSS implementation [Sassy Gridlover](https://github.com/hiulit/Sassy-Gridlover) and never relied on Bootstrap's font sizes and line heights.

It can't be merged with Bootstrap as it is because Sassy Gridlover doesn't support breakpoints out of the box. But it could be easily extended because it's built in a modular way. So IMO with little effort, you could significantly improve typography.

**Comment by tarkhov** [comment] 2018-12-24 12:01
Implemented here - https://tarkhov.github.io/postboot/#font-size-responsive

**Comment by XhmikosR** [comment] 2018-12-24 12:19
@tarkhov: please stop spamming the repo.

**Comment by tarkhov** [comment] 2018-12-24 12:58
@XhmikosR I'm just trying to help people, because I faced the same problems, I can't submit this code to Bootstrap framework, because these features refused or implemented too slow or partially.

**Comment by XhmikosR** [comment] 2018-12-24 13:03
You keep spamming the repo, that's a fact. You can help by submitting PRs, testing PRs and so on.

As for delays, we have speed things up a lot, but we still prioritize things.

You can do whatever you want obviously, just stop commenting on each issue/PR here saying that "the X feature is implemented there" especially when something is already merged.

**Closed** 2019-02-07 22:32 UTC
Labels: css, feature, has-pr, v4
