### ISSUE TITLE
Validation issues

### ISSUE THREAD

**Issue by jineshshah36** [twbs/bootstrap#23497] opened 2017-08-16 15:39 UTC
There seems to be an issue with the css for `.invalid-feedback`. Based on my testing, `.invalid-feedback` classes seem to appear under inputs that are valid when `.was-validated` is set on the `form`. See the jsfiddle here: https://jsfiddle.net/5o1y05vq/2/

What (I think) should happen is that `.invalid-feedback` should only `display: block` when the input element is invalid. Otherwise you get the following behavior:

<img width="539" alt="screenshot 2017-08-16 11 39 22" src="https://user-images.githubusercontent.com/6501089/29371871-91dbdf20-8277-11e7-9e42-aa2d5eef65bc.png">

**Comment by mdo** [comment] 2017-08-16 16:12
Duplicate of #23372 and fixed in `v4-dev`.

**Closed by mdo** 2017-08-16 16:12 UTC
Labels: css, v4
