### ISSUE TITLE
UI scrolling issue on actual Bootstrap site

### ISSUE THREAD

**Issue by abitofbrit** [twbs/bootstrap#39618] opened 2024-01-30 16:34 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I noticed a UI scrolling issue on the actual Bootstrap site, and I didn't know how else to bring it to y'alls attention. 

If click inside any of the HTML boxes and drag my mouse to try and copy the code (vs clicking the clipboard icon in the corner), it scrolls me down to the bottom of the page. I noticed this issue on a few pages:
- [Components > Cards page](https://getbootstrap.com/docs/5.3/components/card/)
- [Components > Carousel page](https://getbootstrap.com/docs/5.3/components/carousel/)
- [Components > Accordion page](https://getbootstrap.com/docs/5.3/components/accordion/)
- _... possibly other pages, but I only checked a handful_

### Reduced test cases

I checked a few other pages, and here are a few that _don't_ have this issue:
- [Components > Badges page](https://getbootstrap.com/docs/5.3/components/badge/)
- [Components > Button group page](https://getbootstrap.com/docs/5.3/components/button-group/)
- [Components > Navs and tabs page](https://getbootstrap.com/docs/5.3/components/navs-tabs/)

I also tried clicking the clipboard icon to copy, and that functionality works fine – doesn't shoot me down the page.

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3

**Comment by louismaximepiton** [comment] 2024-01-30 16:49
Duplicate of #39605.

**Closed by louismaximepiton** 2024-01-30 16:49 UTC

**Comment by abitofbrit** [comment] 2024-01-30 17:21
Sounds good! I didn't see that issue when checking to see if it was brought up already. Looks to be the same. Thanks! 😄
