### ISSUE TITLE
Thumbnail overflow on Firefox

### ISSUE THREAD

**Issue by Wtower** [twbs/bootstrap#16144] opened 2015-03-24 16:41 UTC
A page has several thumbnails in a column. This column is in a row, which row is in a panel. The panel itself is last in a container.

For some reason which I cannot understand, the thumbnails render properly in Chrome (Opera etc) but not in Firefox 36. In this case the thumbnails take up a large size overflowing the row.

This is the markup of the page (from Django):
http://www.bootply.com/ZOS8y2vHPE

I was wondering if there is something wrong with my markup (most possibly) or there is something off with twbs.

**Comment by twbs-lmvtfy** [comment] 2015-03-24 16:41
Hi @Wtower!

You appear to have posted a live example (http://s.bootply.com/render/ZOS8y2vHPE), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 432, column 23: Element ```` style ```` not allowed as child of element ```` body ```` in this context. (Suppressing further errors from this subtree.)
* line 435, column 84: Element ```` link ```` is missing required attribute ```` property ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Wtower** [comment] 2015-03-24 16:47
Removed irrelevant django-toolbar markup which seemed to be causing a validation issue:
http://www.bootply.com/DcSCcJxJzV

**Comment by twbs-lmvtfy** [comment] 2015-03-24 16:47
Hi @Wtower!

You appear to have posted a live example (http://s.bootply.com/render/DcSCcJxJzV), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 9, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1
* line 437, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.4 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Wtower** [comment] 2015-03-24 16:54
Now using latest bootstrap version:
http://jsfiddle.net/7wfmnbbq/

**Comment by Wtower** [comment] 2015-03-24 17:07
Removed some irrelevant markup from tests that might have been confusing (apologies for that); latest fiddle:
http://jsfiddle.net/fdab1jgc/

**Comment by cvrebert** [comment] 2015-03-24 18:38
Which OS are you using?

**Comment by cvrebert** [comment] 2015-03-24 21:58
I can confirm the thumbnail images being giant on medium-and-larger screens on OS X Firefox.
This is because you are using `<fieldset>`s, which have weird legacy behavior (`min-width: min-content`) in HTML. Here's a version with `<div>`s instead that works fine: http://jsfiddle.net/5xj1hpc9/1/show/

For more info and another workaround, see the "Browser compatibility" & "Bugs" sections of https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Fieldset

Closing since it's not feasible to do anything about this at the Bootstrap level.

**Closed by cvrebert** 2015-03-24 21:58 UTC
Labels: css

**Comment by Wtower** [comment] 2015-03-24 23:42
Great. Many thanks for your accurate and swift response.
