### ISSUE TITLE
Bootstrap tooltips require Tether. But not using Tooltips

### ISSUE THREAD

**Issue by surjithctly** [twbs/bootstrap#22601] opened 2017-05-11 12:03 UTC
Hello,

I have just got this error when using Bootstrap.min.js  (v4-alpha)

`Error: Bootstrap tooltips require Tether `

However, I'm not using the Tooltip Function in my project. So adding an extra JS which is unused is not good for performance. So why not throw the error only if I'm using Tooltips and Tether is not called.

So that for users who use Tooltips see the error, so they can fix it.

PS: I don't want to recompile the bootstrap.js without the tooltip code because I'm sharing the code to other users where they might or might not need tooltips. 

Can you add a solution for this?

~Surjith

**Comment by Johann-S** [comment] 2017-05-12 11:46
Bootstrap  depend on Tether for Tooltips/Popover and Tether is required as you can see here : http://v4-alpha.getbootstrap.com/getting-started/introduction/#quick-start

Duplicate of : #19669, #18664

**Closed by Johann-S** 2017-05-12 11:46 UTC
Labels: js, v4

**Comment by surjithctly** [comment] 2017-05-12 12:04
Hello @Johann-S 

I understand Bootstrap Tooltip requires Tether. But my question is different. Can you read again?

It's about when and how the error should throw.

~Surjith
