### ISSUE TITLE
angular 13+ compilation :  legend+* -> Cannot read properties of undefined (reading 'type') v5.1.3

### ISSUE THREAD

**Issue by amassal** [twbs/bootstrap#36136] opened 2022-04-08 17:07 UTC
**Prerequisites**
 I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
 I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
 I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

**Describe the issue**
Hi Team,

I am getting that watning when i compile my angular 13.2.1 project : 
Warning: 2 rules skipped due to selector errors:
  legend+* -> Cannot read properties of undefined (reading 'type')
  legend+* -> Cannot read properties of undefined (reading 'type')

**Reduced test cases**
If i comment the import of bootstrap i have no longer that warning.
Looking forward for your valuable response.

**What operating system(s) are you seeing the problem on?**
windows 10

**What browser(s) are you seeing the problem on?**
Chrome

**What version of Bootstrap are you using?**
v5.1.3

**Comment by WinterSilence** [comment] 2022-04-08 20:32
no matters, Angular abandoned

**Comment by ffoodd** [comment] 2022-04-09 09:21
Angular is not abandoned 😅

I suspect an issue with your compiler or something. This CSS compiles fine everywhere so that's very likely your tooling (compiler, linter, loader...) which struggles.

This CSS selector is old enough to not be an issue anywhere (that's CSS 2.1, 20 years ago 😄) so there can't be an issue.

Moreover that's only a warning, so I'm closing this for now — but feel free to comment again with any information you'd grab, if needed.

**Comment by WinterSilence** [comment] 2022-04-09 14:14
@ffoodd https://docs.angularjs.org/misc/version-support-status

**Comment by ffoodd** [comment] 2022-04-09 17:05
AngularJS is not the same as [Angular](https://angular.io/guide/roadmap). 🙂

**Closed** 2022-04-09 17:14 UTC
Labels: won't fix

**Comment by andreimindru** [comment] 2022-06-02 10:58
I have the problem after updating angular/cli 13.3.2->13.3.7. Using bootstrap 5.1.3

**Comment by romodog** [comment] 2022-06-03 15:23
fuck u set up this one u self see if u can make it

________________________________
Från: Salvatore Di Palo ***@***.***>
Skickat: den 3 juni 2022 17:14
Till: twbs/bootstrap ***@***.***>
Kopia: romodog ***@***.***>; Comment ***@***.***>
Ämne: Re: [twbs/bootstrap] angular 13+ compilation : legend+* -> Cannot read properties of undefined (reading 'type') v5.1.3 (Issue #36136)


@ffoodd<https://github.com/ffoodd> https://docs.angularjs.org/misc/version-support-status

Imagine getting confused and still recommending angularJs

**Comment by XhmikosR** [comment] 2022-09-22 09:14
For reference, this is the root cause: https://github.com/GoogleChromeLabs/critters/issues/103
