### ISSUE TITLE
Improve grid system: .float-right-md

### ISSUE THREAD

**Issue by comerc** [twbs/bootstrap#15663] opened 2015-01-24 03:52 UTC
for example:

```html
<div class="row">
    <div class="col-xs-12 col-md-8 float-right-md">always on top</div>
    <div class="col-xs-12 col-md-4" style="height: 100px;">left or bottom</div>
    <div class="col-xs-12 col-md-8">footer after #top or #bottom</div>
</div>
```

```css
/* if -md */ 
.float-right-md { float: right; }
```

**Comment by cvrebert** [comment] 2015-01-24 04:40
Duplicate of #13690.

**Closed by cvrebert** 2015-01-24 04:40 UTC
