### ISSUE TITLE
Add off-canvas sidebar navigation widget

### ISSUE THREAD

**Issue by krvikash35** [twbs/bootstrap#18918] opened 2016-01-17 18:34 UTC
need a vertical sidebar navigation, which is widely used in mobile app development.

**Comment by cvrebert** [comment] 2016-01-17 20:15
Erm, you mean an off-canvas navigation like http://getbootstrap.com/examples/offcanvas/ ?

**Comment by krvikash35** [comment] 2016-01-17 20:56
@cvrebert ...yes...I wish if releases as part of v4

**Comment by cvrebert** [comment] 2016-01-17 21:59
Duplicate of #17502.

**Closed by cvrebert** 2016-01-17 21:59 UTC
Labels: awaiting reply, css, feature, v4

**Comment by saclychan** [comment] 2016-01-19 03:02
I also liked that

2016-01-18 3:58 GMT+07:00 Vikash Kumar <notifications@github.com>:

> @cvrebert <https://github.com/cvrebert> ...yes...I wish if releases as
> part of v4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/18918#issuecomment-172379726>.
>



-- 
Ngô Cẩm Hà
