### ISSUE TITLE
Bootstrap 5 Offcanvas (Navbar): Offcanvas in Navbar broke after putting two offcanvas inside it?

### ISSUE THREAD

**Issue by devhoussam1998** [twbs/bootstrap#37841] opened 2023-01-09 00:21 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

the Bootstrap 5 two offcanvas component inside a navbar element, but are experiencing problems with the layout or functionality of the offcanvas.

### Reduced test cases

https://codepen.io/devhoussam1998/pen/eYjgrMN

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3.0-alpha1

**Comment by julien-deramond** [comment] 2023-01-09 06:42
Thanks for opening this issue @devhoussam1998. Could you please precise in the description what you mean by "[...] experiencing problems with the layout or functionality of the offcanvas"; what's happening versus what's expected.

**Comment by devhoussam1998** [comment] 2023-01-09 10:48
well, in bootstrap docs there is the possibility to put the offcanvas into a navbar component that's amazing but this it will work only with one off-canvas inside it what if I want to add two separate offcanvas inside this navbar component it will not work as the live preview I mentioned above.

**Comment by julien-deramond** [comment] 2023-01-09 11:34
Please define "not work" in details. Is it the layout with one toggle button on the left-hand side and the other on the right hand side?
Because when I try your example, I don't see any issues where both of the offcanvases seem to be triggered correctly:

![2023-01-09 12 32 24](https://user-images.githubusercontent.com/17381666/211299115-7b090afe-a946-47d0-a3ed-7cf37df25abe.gif)

**Comment by devhoussam1998** [comment] 2023-01-09 14:02
try to the page in large view not in medium view

**Comment by julien-deramond** [comment] 2023-01-09 14:56
In https://getbootstrap.com/docs/5.3/components/navbar/#offcanvas, it is mentioned that
> In the example below, to create an offcanvas navbar that is always collapsed across all breakpoints, omit the .navbar-expand-* class entirely.

If you click on the "Edit on StackBlitz" button, you'll be able to test it with a large view. The toggle button that triggers the offcanvas is always present.

If you add `.navbar-expand-lg` (as you did in the CodePen), the content of the offcanvas will be seeable in the navbar with a large view. That's what we can see in your example as well.

So again, please define "not work". What is the expected behavior? What is the expected rendering? What are you trying to achieve?

**Comment by devhoussam1998** [comment] 2023-01-09 17:51
**Check my live preview example:** 

https://stackblitz.com/edit/mmsipk?file=index.html

you will find in the full-screen view that the body content of both off-canvas is displayed in large view this shouldn't be happening because I already add `navbar-expand-lg` into my navbar class.

**see this image:** 

![Alt text](https://i.imgur.com/mFX2Czj.png?raw=true "Title")

**Full Code:** 

```
        <nav class="navbar navbar-expand-lg bg-warning p-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasEnd" aria-controls="offcanvasEnd">
                    <span class="navbar-toggler-icon"></span>
                    <span class="ms-2">Open Offcanvas End</span>
                </button>
                <a href="#" class="navbar-brand d-block d-lg-none">Logo</a>
                <!-- Offcanvas End -->
                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasStart">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title">Offcanvas Start</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">Offcanvas End Body (Shouldn't be displayed in Full screen)</div>
                </div>
                <!-- Offcanvas Start -->
                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasEnd">
                    <div class="offcanvas-header">
                        <h5 class="offcanvas-title">Offcanvas End</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">Offcanvas Start Body (Shouldn't be displayed in Full screen)</div>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasStart" aria-controls="offcanvasStart">
                    <span class="navbar-toggler-icon"></span>
                    <span class="ms-2">Open Offcanvas Start</span>
                </button>
            </div>
        </nav>
```

you should know that does not happen when I remove the second off-canvas from the navbar components. it's means that the navbar components do not accept two off-canvas inside it.

**Comment by julien-deramond** [comment] 2023-01-09 18:01
> you will find in the full-screen view that the body content of both off-canvas is displayed in large view this shouldn't be happening because I already add navbar-expand-lg into my navbar class.

And that's the problem 😄 
As I said, if you have `.navbar-expand-lg` it will behave like that so **remove it**.

> If you add .navbar-expand-lg (as you did in the CodePen), the content of the offcanvas will be seeable in the navbar with a large view. That's what we can see in your example as well.

**Comment by mdo** [comment] 2023-01-10 04:44
Closing as not a bug.

**Closed by mdo** 2023-01-10 04:44 UTC
Labels: v5
