### ISSUE TITLE
Safari iPad - Modal shift the body to the top when focus on input

### ISSUE THREAD

**Issue by elianapiquets** [twbs/bootstrap#20117] opened 2016-06-14 18:58 UTC
Issue on Safari iPad, just update to 9.3.2 iOS

This happens in a web of my own and also in bootstrap official page. With this modal http://getbootstrap.com/javascript/#modals-related-target

The modal open fine, But the problem is when i touch the Input or textarea. The body scrolls back to the top.

**Comment by cvrebert** [comment] 2016-06-14 19:23
Duplicate of #17497.
I recommend CC-ing yourself on https://bugs.webkit.org/show_bug.cgi?id=153224

**Closed by cvrebert** 2016-06-14 19:23 UTC
Labels: browser bug, v3
