### ISSUE TITLE
Table with fixed header

### ISSUE THREAD

**Issue by MugeshM** [twbs/bootstrap#26931] opened 2018-07-20 08:17 UTC
Table component works fine in all the way but things has to introduce and improve is 
1) Table with fixed header
2) Table with card layout responsive

**Comment by bkdotcom** [comment] 2018-07-20 14:00
Dupe of #26337  ?

**Comment by mdo** [comment] 2018-07-20 14:08
Yup, closing out.

**Closed by mdo** 2018-07-20 14:08 UTC
