### ISSUE TITLE
"bottom: 0" is missing in Bootstrap v3.3.2 

### ISSUE THREAD

**Issue by dgofman-equinix** [twbs/bootstrap#15629] opened 2015-01-21 21:10 UTC
.modal-backdrop {
  position: absolute;
  top: 0;
  right: 0;
  left: 0;
  background-color: #000;
}

**Comment by cvrebert** [comment] 2015-01-21 21:18
Duplicate of #15314. Please search next time.

**Closed by cvrebert** 2015-01-21 21:18 UTC
Labels: css
