### ISSUE TITLE
v4 input-group-lg issue (broken)

### ISSUE THREAD

**Issue by iBasit** [twbs/bootstrap#18180] opened 2015-11-05 20:25 UTC
http://v4-alpha.getbootstrap.com/components/input-group/#sizing

![image](https://cloud.githubusercontent.com/assets/34341/10980690/40972e02-83fb-11e5-8272-8382f4ec00a5.png)

browser chrome

**Comment by cvrebert** [comment] 2015-11-05 20:30
Duplicate of #17035. Please search more in the future!

**Closed by cvrebert** 2015-11-05 20:30 UTC
