### ISSUE TITLE
Improve .card-img-overlay

### ISSUE THREAD

**Issue by aRestless** [twbs/bootstrap#21256] opened 2016-11-30 14:48 UTC
Currently, the `.card-img-overlay` only properly works for cards that use the `img` as their full background, because the overlay will span the whole `.card`. If the `.card` has content below the image, then the `.card-img-overlay` can overflow the image, _and_ it's not possible to align elements to the bottom of the image. For images that are not the first element of a card the overlay breaks completely.

This is very simply solved with a wrapper div around `.card-img` and `.card-img-overlay` with `position: relative;`. JS Bin for comparison: https://jsbin.com/hixuvegihu/edit?html,output

So a single class like `.card-img-overlay-wrapper` would solve this issue and make the img-overlay much more flexible to use.

**Comment by mdo** [comment] 2016-12-25 08:51
Closing as a dupe of #18476 which asks for a `position: relative` utility that'd help you out here.

**Closed by mdo** 2016-12-25 08:51 UTC
Labels: css, v4
