### ISSUE TITLE
Placeholders look way too identical to input text

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#21655] opened 2017-01-10 23:25 UTC
Using Chrome 55 on Windows 10.

Placeholders look too identical to input text which makes it difficult for someone filling a form to differentiate between a filled input and an empty one.

**Comment by patrickhlauke** [comment] 2017-01-10 23:30
Duplicate of https://github.com/twbs/bootstrap/issues/21624

**Closed by patrickhlauke** 2017-01-10 23:30 UTC
