### ISSUE TITLE
Floating labels select option text not fully visible

### ISSUE THREAD

**Issue by AlexHolly** [twbs/bootstrap#34147] opened 2021-05-30 22:33 UTC
Windows 10
Google Chrome Version 91.0.4472.77 (Offizieller Build) (64-Bit)

Some characters will be cut off.

Example "jgy":
```
<div class="form-floating">
  <select class="form-select" id="floatingSelect" aria-label="Floating label select example">
    <option selected="">jgy</option>
    <option value="1">One</option>
  </select>
  <label for="floatingSelect">Works with selects</label>
</div>
```
https://getbootstrap.com/docs/5.0/forms/floating-labels/#selects

**Comment by alecpl** [comment] 2021-05-31 05:56
Duplicate of #32672.

**Closed** 2021-05-31 07:14 UTC

**Comment by theodorejb** [comment] 2023-12-11 21:59
This issue still exists in Bootstrap 5.3. Specifically, letters with descenders like j, g, and y are cut off in select dropdowns. It can be seen right on the Bootstrap docs page for floating labels by editing one of the options to include any of these letters:  
![BS 5 3 bug light](https://github.com/twbs/bootstrap/assets/3053271/176a6d58-8a1d-41f5-9712-9e1c269ebf43)

The problem gets even worse when using the `form-select-lg` class.
