### ISSUE TITLE
getbootstrap.com link points to old blog post

### ISSUE THREAD

**Issue by KimPrince** [twbs/bootstrap#19960] opened 2016-05-24 07:52 UTC
When you click on the V4 teaser link at the top of the getbootstrap.com home page it points to the blog post from August 2015.  You might want to update it to point at the December 2015 blog post.

**Comment by cvrebert** [comment] 2016-05-24 21:00
Duplicate of #18913. The docs will be redeployed when 3.3.7 is released.

**Closed by cvrebert** 2016-05-24 21:00 UTC
Labels: docs, v3
