### ISSUE TITLE
Documentation: incorrectly positioned "submit" button

### ISSUE THREAD

**Issue by gmile** [twbs/bootstrap#30536] opened 2020-04-08 10:00 UTC
"Submit form" button on the "[Validation](https://deploy-preview-29925--twbs-bootstrap.netlify.com/docs/5.0/forms/validation/)" documentation page is positioned weirdly.

![image](https://user-images.githubusercontent.com/207112/78771435-d1332000-7998-11ea-952f-7f3c89fb0cbc.png)

Versions:
* OS: macOS 10.14.2 (18C54)
* Google Chrome: 80.0.3987.163

**Comment by Deckluhm** [comment] 2020-04-08 10:23
Isn't it the same issue than https://github.com/twbs/bootstrap/issues/30438?

**Comment by XhmikosR** [comment] 2020-04-08 11:22
Please do not use the PR previews to report issues!

This is not always the latest code. The v5 preview is <https://twbs-bootstrap.netlify.com/>

And yeah it's a duplicate of #30438.

**Closed by XhmikosR** 2020-04-08 11:22 UTC
Labels: duplicate

**Comment by gmile** [comment] 2020-04-08 11:56
> Please do not use the PR previews to report issues!

@XhmikosR ugh, my apologies! I didn't notice latest v5 preview had a nice URL 🤦‍♂
