### ISSUE TITLE
Add variable for nav-link padding in navbar nav

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#24036] opened 2017-09-21 14:24 UTC
Currently .nav-link in navbar nav has 0.5rem horizontal padding defined in _navbar.scss. If i want to override these values, i get all breakpoint classes with new values on top of the current ones. Would be better to change it to some variable for better overriding capability so that i can override them without adding new CSS.

**Comment by andresgalante** [comment] 2017-09-21 14:41
Yes, you are right, A PR has been submitted to fixe it here #23109

**Comment by Johann-S** [comment] 2017-09-21 15:01
duplicate of #23034

**Closed by Johann-S** 2017-09-21 15:01 UTC
