### ISSUE TITLE
input[type=date] height and font (Firefox / Chrome)

### ISSUE THREAD

**Issue by samuelcecilio** [twbs/bootstrap#25630] opened 2018-02-15 00:48 UTC
Firefox 58 (font):

![Firefox 58 - Font](https://user-images.githubusercontent.com/30150045/36235918-6f862ed8-11da-11e8-8cfc-253a78c9b3d3.png)

Chrome 64 (height):

![Chrome 64 - Height](https://user-images.githubusercontent.com/30150045/36235926-76ef1644-11da-11e8-8e94-72421899e4f9.png)

**Comment by mdo** [comment] 2018-02-16 03:00
Duplicate of #18842 (a very old and annoyingly tricky bug to fix).

**Closed by mdo** 2018-02-16 03:00 UTC

**Comment by samuelcecilio** [comment] 2018-02-16 03:07
What about the font color in Firefox? Is that an old friend too? Thanks for the feedback
