### ISSUE TITLE
responsive font-sizes?

### ISSUE THREAD

**Issue by kimamil** [twbs/bootstrap#23047] opened 2017-07-11 22:01 UTC
In _variables.scss I found the $font-size-base, $font-size-lg, $font-size-sm ...

So I thought, this is the typical setup for responsive font sizes. Therefore I created a simple hello World on Codepen.io https://codepen.io/kimamil/pen/owQKVz and realised, there is no responsiveness in the font size at all...

I also found, that the _reboot.scss still sets the 16px font-size on html in v4.0.0-alpha.6 without accounting for different media queries. Additionally I couldn't find any font-size changes on the body tag which might be the case from other issues I read here.

I assume there is a part missing that does something like:

```
@include media-breakpoint-only(xs) {
  html { $font-size-base;  }
}
@include media-breakpoint-only(sm) {
  html { $font-size-sm;  }
}
@include media-breakpoint-only(md) {
  html { $font-size-md;  }
}
...
```

So:
* Did I miss anything?
* Why else are responsive font-sizes not working in v4.0.0-alpha.6 then with my hello world example?

Best regards
Manuel

**Comment by gijsbotje** [comment] 2017-07-11 22:31
these variables are used to, for example, setup the `.col-form-label-lg` and `.col-form-label-sm`
The variables are based on `rem` units, so these variables won't do you any good

the code you are suggesting could work but only if you set to pixel values eg.
https://codepen.io/gijsbotje/pen/KqbgNo

**Comment by kimamil** [comment] 2017-07-12 05:56
I see, thanks for the explanation.
So 1rem is TRUELY 16px by default in ALMOST ANY Browser, even mobile versions (probably due to tablet support I guess)..

So you're also saying that there's no native support for responsive font-sizes and it has to be done manually, right?

Manuel

**Comment by gijsbotje** [comment] 2017-07-12 06:41
well currently it's not, it might be a new feature for i guess v4.1 or beta2 or whatever

you can go really crazy with it though, like this article that explains fluid type https://madebymike.com.au/writing/fluid-type-calc-examples/

**Comment by mdo** [comment] 2017-07-14 23:40
Closing as duplicate of #23053 to consolidate.

**Closed by mdo** 2017-07-14 23:40 UTC
Labels: css, v4
