### ISSUE TITLE
Can I use Bootstrap v4.0 in production? Thank you!

### ISSUE THREAD

**Issue by duruitang** [twbs/bootstrap#19632] opened 2016-03-28 06:44 UTC
I want use it next week ~

**Comment by cvrebert** [comment] 2016-03-28 07:13
Approximate duplicate of #19403.
Bootstrap v4 is currently in [alpha](https://en.wikipedia.org/wiki/Software_release_life_cycle#Alpha). It has some known bugs and we will very likely make backward-incompatible changes to it between now and the first stable v4.0.0 release.
Thus, unless you're okay with dealing with elevated buginess and okay with the extra work of eventually migrating from v4.0.0-alpha.N to v4.0.0 (stable), I personally would not currently recommend using v4 alpha in production.

**Closed by cvrebert** 2016-03-28 07:13 UTC
Labels: meta, v4
