### ISSUE TITLE
$input-height-inner isn't a valid CSS value

### ISSUE THREAD

**Issue by WuglyakBolgoink** [twbs/bootstrap#28284] opened 2019-02-15 14:30 UTC
Are we missed something after latest upgrade? Before was ok...

```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

$input-height-inner:                    calc(#{$input-line-height * 1em} + #{$input-padding-y * 2}) !default;
                                                                                                  ^
      1.222em*em isn't a valid CSS value.
      in /Users/.../.../node_modules/bootstrap/scss/_variables.scss (line 491, column 100)
```

**Comment by mdo** [comment] 2019-02-15 21:24
@MartijnCuppens We probably need to rewrite this to move the operator and math outside the escaped variable.

**Comment by MartijnCuppens** [comment] 2019-02-16 11:04
This looks like a duplicate of https://github.com/twbs/bootstrap/issues/28240, but with `em`. If you remove the `em` from the line-height (`1.222em`), you should be fine.

**Closed by MartijnCuppens** 2019-02-16 11:04 UTC
Labels: backport-to-v5, css, v4
