### ISSUE TITLE
navbar comes vertical when we use bootstrap navbar code. i wrote correct code for that 

### ISSUE THREAD

**Issue by samrandhawa4** [twbs/bootstrap#21694] opened 2017-01-13 02:34 UTC
Here  is the correct css for navbar class of bootstrap.css file 
```css
.navbar-nav {
  display: -webkit-box; 
  display: -ms-flexbox; 
  display: flex; 
  -webkit-box-orient: vertical; 
  -webkit-box-direction: normal; 
  -ms-flex-direction: row; 
  flex-direction: row; 
  padding-left: 0; 
  margin-bottom: 0; 
  list-style: none;
}

.navbar-brand { 
  display: inline-block;
  margin-right: 1rem; 
  line-height: inherit; 
  white-space: nowrap;
}
```

**Comment by sharadcodes** [comment] 2017-01-16 13:23
Both navbar and navbar-nav have `flex-direction: column;`. Also there is no `.nav-item` class.

**Comment by mdo** [comment] 2017-01-21 22:30
Closing as I can't reproduce this and there's no test case presented in this issue.

**Closed by mdo** 2017-01-21 22:30 UTC
Labels: css, v4
