### ISSUE TITLE
Success colors breaking while overwriting of success color. 

### ISSUE THREAD

**Issue by Abdulla1995** [twbs/bootstrap#29981] opened 2020-01-08 07:53 UTC
Hi everyone. I have faced an issue and can not find the causing problem. 
**Element**  - `<button class="btn btn-success">Login</button>`
I have sass file that overwrites some variables of bootstrap. But weird thing is that when I have changed success color. 
On our site the first success color was : **$success: #5DBF4C;** and the result is perfect. I mean btn-success gives background **$success** color and text color white. Then on hover background turns little more dark $success and text to **white** color. Result is below image: 
![image](https://user-images.githubusercontent.com/26725106/71957391-1499b900-3207-11ea-84e3-c92f0d2fc5f2.png)
**Hovered**
![image](https://user-images.githubusercontent.com/26725106/71958132-f1700900-3208-11ea-933e-dd1cbcfb3874.png)

But when I change to new success color with this one : **$success: #76B963;** all success buttons fails. Background color is green but the text color is not white but turning black. 
![image](https://user-images.githubusercontent.com/26725106/71957522-66424380-3207-11ea-9d63-99799076550a.png)
And **on hover** right one - the **Registration** button which **class is btn-outline-success** and turns this one:
![image](https://user-images.githubusercontent.com/26725106/71957699-ebc5f380-3207-11ea-8521-7a2c4c5dfdad.png)

1. **Tested on** latest Chrome and Firefox Developer Edition browsers.
2. Deleted all other overwrites and only changed $success color the result was the same.

**Comment by florianlacreuse** [comment] 2020-01-08 09:55
It's related to [BS color contrast](https://getbootstrap.com/docs/4.4/getting-started/theming/#color-contrast).

**Comment by Abdulla1995** [comment] 2020-01-08 10:38
> 
> 
> It's related to [BS color contrast](https://getbootstrap.com/docs/4.4/getting-started/theming/#color-contrast).

Thanks @florianlacreuse . I get the idea but can not find a way to fix this issue.

**Comment by florianlacreuse** [comment] 2020-01-08 10:45
I don't know what's the best way to get your specific green with white text in this situation. May be someone from the BS team can help you more.

In the meantime, there is a variable `$yiq-contrasted-threshold`, may be you can find a better value for your case?

https://github.com/twbs/bootstrap/blob/71daf2ae610f687e9ab783ccc749f89a4fac9cdf/scss/_variables.scss#L97-L98

**Comment by Abdulla1995** [comment] 2020-01-09 13:58
@mdo Thanks. But if anybody can provide any fix please let me know :)

**Comment by MartijnCuppens** [comment] 2020-01-09 18:17
We could create mixins for each btn state, something like `btn-hover($color)`, `btn-focus($color)`, ect... These mixins can than be overridden if needed.

@Abdulla1995, for now you can try to change `$yiq-contrasted-threshold`, like @florianlacreuse suggested.

**Comment by florianlacreuse** [comment] 2020-01-09 20:16
> We could create mixins for each btn state, something like `btn-hover($color)`, `btn-focus($color)`, ect... These mixins can than be overridden if needed. Not sure if that would be flexible enough, just thinking out loud here.

@MartijnCuppens I think the issue is not limited to buttons but every other components like badges, alerts, backgrounds utilities, etc.

**Comment by ffoodd** [comment] 2020-01-10 08:34
FWIW this is expected for accessibility reasons, not an issue at all.

IMHO you shouldn't provide a way to decrease accessibility.

**Comment by MartijnCuppens** [comment] 2020-01-10 12:10
Indeed, gonna close this. Thanks for the input guys!

**Closed by MartijnCuppens** 2020-01-10 12:10 UTC
Labels: css
