### ISSUE TITLE
Add a namespace for classes

### ISSUE THREAD

**Issue by Sir-Genius** [twbs/bootstrap#31837] opened 2020-10-05 12:10 UTC
How do you feel about adding the namespace for classes as you have done it for CSS variables?

**Comment by florianlacreuse** [comment] 2020-10-07 21:47
Duplicate of #29547.

It won't happen: https://github.com/twbs/bootstrap/issues/29547#issuecomment-561025723

You will need to handle it with post-processors.

**Comment by florianlacreuse** [comment] 2020-11-01 00:55
I think we can close this one?

**Comment by mdo** [comment] 2020-12-06 04:18
Closing for now. Maybe in a future major release.

**Closed by mdo** 2020-12-06 04:18 UTC
Labels: feature
