### ISSUE TITLE
Progress Bars violate CSP style-src directive unless directive has 'unsafe-inline' in it

### ISSUE THREAD

**Issue by nchelluri** [twbs/bootstrap#17785] opened 2015-10-05 21:48 UTC
I see this in the docs for v3.3.5 but I'm using an older 3.x version and see the behavior in my application.

From the docs: http://getbootstrap.com/components/#progress

```
<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
```

That last attribute, the inline style, causes a CSP violation for me (and I assume anyone else using an effective CSP policy, since `'unsafe-inline'` is considered, well, unsafe).

A bit of searching helped me find an existing workaround for this issue: https://github.com/danielnixon/bootstrap-hacks/blob/master/progressbar.css

One thing to note is that I had to do a round on my percent values in order to make the `bootstrap-hacks` package work properly (e.g. `aria-valuenow="50.0"` doesn't work but `aria-valuenow="50"` does).

**Comment by cvrebert** [comment] 2015-10-05 23:23
That hack (add 100 declarations, one for each percentage point) is pretty gnarly; probably too gnarly for us to pursue.
`attr()` would be the obvious way to address this, but its browser support seems pretty lacking (https://developer.mozilla.org/en-US/docs/Web/CSS/attr#Browser_compatibility , https://github.com/Fyrd/caniuse/issues/1209). So this might be a WontFix situation.
CC: @mdo

**Comment by nchelluri** [comment] 2015-10-06 06:46
An option a co-worker suggested to me ( @RobertWHurst ) was to put the style code into JS.

**Comment by patrickhlauke** [comment] 2015-10-06 08:24
As JS is needed anyway to make the progress bar actually work, this may be an option. My preference for v4 would be to use actual `<progress>` in the markup, styled as much as possible with CSS, and then gently polyfill it (replacing it with a styled `<div>` with relevant `aria-*` attributes in browsers that don't natively support `<progress>`)

**Comment by mdo** [comment] 2015-10-13 07:37
> So this might be a WontFix situation.

I'm in favor of that.

> then gently polyfill it (replacing it with a styled <div> with relevant aria-* attributes in browsers that don't natively support <progress>)

Woof, sounds like a lot of overhead for not a lot of gain.

**Comment by iliasch** [comment] 2015-10-18 17:10
Modals with the .fade class also trigger an error when CSP is active (causing the modal to fail to show and scripts to stop working requiring a page reload). This wasn't a problem in v3 and seems to be caused by the reflow function trying to eval() and inject javascript in the page. The temporary solution I've found is to remove the fade class and use other means to achieve the transition. I'm still trying to figure out a better way though, which can work out of the box.

**Comment by cvrebert** [comment] 2015-10-27 19:08
I propose documenting this and deeming it WontFix: #18080.

> As JS is needed anyway to make the progress bar actually work

Eh, not really, IMHO. Progress bars that are only updated on page load are a thing.
E.g. "[progress bar goes here] You are 75% done answering this survey. Here's the next set of questions:"

**Closed** 2015-10-30 08:45 UTC
Labels: css, v3

**Comment by stgogm** [comment] 2015-12-29 17:34
If you set the element's width through JavaScript it wont violate the CSP policy:

```js
element.style.width = '30%';
```
