### ISSUE TITLE
Providing btn stylings as placeholder/silent classes

### ISSUE THREAD

**Issue by saitho** [twbs/bootstrap#35847] opened 2022-02-16 10:10 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Placeholders or silent classes(`%`-prefix) are blocks that contain stylings but are not rendered to CSS if not used by a class.

I propose adding silent classes to all basic button stylings in `scss/_buttons.scss`, so they can be extended from without bloat.

Example:

```scss
.btn, %btn {
   // button stylings here
}
```

### Motivation and context

We use external JavaScripts that embed own HTML structures that do not use Bootstrap.

We then apply the Bootstrap button stylings to the elements via `@extend`:
```
.external-component-button {
  @extends .btn;
}
```

The issue is that extending classes will extend ALL usages of the .btn class, even nested ones.
This results in a multitude of selectors that are not even needed (bloated selectors).
The solution is extending from a silent class aka placeholder:

```
.external-component-button {
  @extends %btn;
}
```

More information on that topic here: https://jdsteinbach.com/sass/use-extend/

**Comment by mdo** [comment] 2022-02-17 18:07
I've previously been against using extends, largely because they cannot be used in media queries if declared outside the media context. See https://sass-lang.com/documentation/at-rules/extend#extend-in-media for details. Beyond that, it creates additional selectors quite quickly, which I've considered a complication and performance risk when working at scale.

**Comment by saitho** [comment] 2022-02-17 18:28
Yes, extending from classes gets pretty bad quickly. I'd love to not use `@extend`, however I don't see a different solution on how to apply our consistent Bootstrap styling to components where we don't control the HTML (JS manipulation isn't an option, obviously 😄).

Extending from silent classes (or "placeholders" was also a term I found the `%` selectors) will just apply the styling inside - avoiding bloated selectors you get when extending from classes. That's why I want to introduce silent classes as well, at the same place where the class styling is defined.

**Comment by saitho** [comment] 2022-03-01 11:36
So, is it possible to move forward with the PR #35863, or is silent classes something you definitely won't add to Bootstrap?

**Comment by ffoodd** [comment] 2022-03-01 12:34
The discussion is opened, there're quite a few questions to solve and such feature takes time.

If we go with this, why not defining silent classes for other components, too? What about utilities?

For now I'm not convinced at all. First of all, it's not something we'd be able to maintain IMHO, because tons of situations wouldn't work for other components (and why would we only use this for buttons only?).

Moreover regarding your use case, that's not an issue with Bootstrap. You're able to add those classes with JavaScript, or to make a custom CSS build to add your selectors.

So either we fully go with silent classes usages, meaning it should work for any components and be documented as a new kind of usage, or we don't land this and maybe add something handling your use case in our docs (upcoming snippets, maybe?).

Still open for discussion but that's not so simple.

**Comment by saitho** [comment] 2022-03-03 10:55
> You're able to add those classes with JavaScript, or to make a custom CSS build to add your selectors.

I'm not a fan of DOM manipulation just to add classes - especially if the HTML that we need to modify is also added via JavaScript. We're already doing a custom CSS build with Bootstrap SCSS files. So we might just add the silent classes via patch where we need them for now.

I was just wondering if that may also be an issue for other developers – so this could be done directly in Bootstrap without the need to patch.

**Comment by ffoodd** [comment] 2022-03-03 13:58
Honestly I don't know, but AFAIK this hasn't been requested before—but I didn't check.

Moving to this would be a tough work. In your case, workarounds exist and the issue is not with Bootstrap but with another script adding markup roughly.

Bootstrap is meant to apply on specific markup, handling other markup is out scope. And I'm really concerned about what could come next, if we try to take such cases into account.

**Comment by jleroy-dev** [comment] 2022-03-09 21:00
I was seeking a way to use `@extend` with placeholders as well (I don't think `@extend` should be used directly on a class).
I have a use-case of wanting to apply `text-truncate` styles to an existing class.
It is safer for me to extend the Bootstrap utility, knowing that if something is fixed in the future regarding how to handle text ellipsis, the fix will be applied to my code as well.

That's only one example but I am sure everyone would find something useful.

**Comment by saitho** [comment] 2022-03-11 11:11
> I have a use-case of wanting to apply `text-truncate` styles to an existing class. It is safer for me to extend the Bootstrap utility, knowing that if something is fixed in the future regarding how to handle text ellipsis, the fix will be applied to my code as well.

Regarding your use case: as far as I see `.text-truncate` only uses the `text-truncate` mixin (at least as of Bootstrap v5.1.3). So you could just use the mixin as well.
Generally talking about Bootstrap utility classes generated via the Bootstrap Utility API, one should be able to extend from them just fine - as they should not be nested into some other contexts.

The issue comes up when a class e.g. `.fw-bold` is changed in nested structures and extended from:
```scss
.component1 {
	.fw-bold { // we want bold text in this class to be red as well
		text-color: red;
	}
}

.component2 { // we want text in this class to be black
	@extend .fw-bold;
}
```

it results in the following CSS:
```css
.fw-bold, .component2 {
  font-weight: bold;
}
.component1 .fw-bold, .component1 .component2 {
  text-color: red;
}
```

Here the selector ".component1 .component2" is generated which we probably did not want here.
As I said, the example above – modifying a utility class in nested structures – is obviously bad practice and shouldn't be the case with Bootstrap core. So it _should_ be fine to extend Bootstrap Utility classes.

**Comment by saitho** [comment] 2022-03-11 11:11
My issue is with components. I agree adding silent classes for components gets pretty complex as nesting and different states happen.

For now I patched the SCSS to add the silent classes I need and was able to reduce my dev CSS by 50%. :+1: 
Maybe we can add some documentation on the issues with `@extend` and how to deal with them properly?

Such may include:
- avoid them in genreral by applying Bootstrap classes to components (e.g. via JS)
- only extending from Bootstrap utility classes AND not modifying Bootstrap utility classes in nested contexts
- only extending from silent classes which one needs to patch into the Bootstrap package e.g. via [patch-package](https://www.npmjs.com/package/patch-package) – possibly increasing the maintainance during upgrades of Bootstrap in the own project

**Comment by WinterSilence** [comment] 2022-03-20 01:57
you can create mixins by classes.
before:
~~~scss
.red {
  color: red;
}
~~~
after:
~~~scss
@mixin c-red {
 color: red;
}
.red {
 @mixin c-red;
}
~~~
to parse scss use [regexp](https://3v4l.org/u77t7#v8.0.17) or something like as [scss-tokenizer](https://github.com/sasstools/scss-tokenizer)

**Comment by mdo** [comment] 2022-09-01 19:32
I think this is something that's tabled for discussion in v5—would be too much overhead IMO. I also have decently strong feelings against extend in general, so we'd need to weigh the pros and cons more deeply across all our components.

Closing for now and labelling for v6 to revisit for then.

**Closed by mdo** 2022-09-01 19:32 UTC
Labels: feature, v6
