### ISSUE TITLE
Black pixels on Modal with Chrome

### ISSUE THREAD

**Issue by emilioRamirez24** [twbs/bootstrap#24248] opened 2017-10-04 14:26 UTC
Hi. I got a Modal on a .cshtml page. It was worked fine, but now in Chrome the modal shows black pixels when I move the mouse over it.

![image](https://user-images.githubusercontent.com/32517084/31180754-d29cf43c-a8f5-11e7-82e2-aa57de431b34.png)

 

Anyone knows why this happen and the solution? I supose it's beacuse a Chrome update.

I'm using windows 10, Chrome Versión 61.0.3163.100 (Build oficial) (64 bits). 
On Edge it works fine. Thanks

**Comment by Johann-S** [comment] 2017-10-04 14:28
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mdo** [comment] 2017-10-04 16:59
Duplicate of #24233.

**Closed by mdo** 2017-10-04 16:59 UTC
Labels: awaiting reply

**Comment by emilioRamirez24** [comment] 2017-10-04 17:13
changed .fade.in opacity property on bootstrap.min.css from 1 to 0.99: .fade.in{opacity:0.99}

and that solved the problem while a better solution appears.

**Comment by Vasil806** [comment] 2017-10-12 19:18
Having the same issue
https://www.screencast.com/t/bUG01qhiR
I used this page http://webapplayers.com/inspinia_admin-v2.6/modal_window.html
