### ISSUE TITLE
Initializing Modal through JS throws Uncaught TypeError: BACKDROP

### ISSUE THREAD

**Issue by taka-oyama** [twbs/bootstrap#33840] opened 2021-05-06 04:46 UTC
Upgraded from v5 beta 3 to v5 seems to have broken dynamic modal.

When I do 
```js
<script>
    var modal = document.getElementById('modal-test');
    new bootstrap.Modal(modal).show();
</script>
```

I get the following error:

```
Uncaught TypeError: BACKDROP: Option "rootElement" provided type "null" but expected type "element".
    at index.js:130
    at Array.forEach (<anonymous>)
    at l (index.js:124)
    at xe._getConfig (backdrop.js:92)
    at new xe (backdrop.js:33)
    at Ne._initializeBackDrop (modal.js:218)
    at new Ne (modal.js:84)
    at modal.html:27
```

Please checkout the details by checking out the snippet below.

https://jsbin.com/tikogemofi/edit?html,console

This only seems to happen if I put the bootstrap JS file in `<head>`.

By debugging for a bit, I was able to see that the code below 

https://github.com/twbs/bootstrap/blob/main/js/src/util/backdrop.js#L14

was set to `null`.

This error probably occurred because document.body does not exist yet when the JS gets loaded in `<head>`.

**Comment by kartik-v** [comment] 2021-05-06 11:52
Agree with this issue.

**Comment by darcome** [comment] 2021-05-06 20:41
It happens to me too and it didn't happen in beta3. When can we expect a fix since this is (in my opinion) pretty serious?

**Comment by GeoSot** [comment] 2021-05-06 22:54
Hey guys. Let's take it form the beginning.

Advising the [Starter template](https://getbootstrap.com/docs/5.0/getting-started/introduction/#starter-template) and following the script loading best practices, your `script` tag, should be loaded at the end of the `body` element.
 
So the provided example is an anti-pattern, which at least could have the 'defer' attribute(which would guide to other problems)

I can confirm that the default option doesn't being initialized if  the scripts is loaded before body. 

So till be fixed, please try to load your script before `body` closing tag 🐰

**Comment by boddunan** [comment] 2021-05-07 04:35
Loading scribe before closing of body tag is not an option in many cases, for example in a CMS. We should not restrict the users to load the scripts, bootstrap should work in either way.

**Comment by mscdex** [comment] 2021-05-07 18:29
I also just encountered this same issue coming from 5.0.0-beta3 and realized what was happening before finding this GH issue. Forcing users to load the Bootstrap JS file in a specific way for no good reason is not a solution.

**Comment by alpadev** [comment] 2021-05-08 04:13
Guy, please calm down for a second. No one tries to enforce here something.

Like @GeoSot already mentioned, adding scripts into the head can be considered an antipattern, because it blocks the page rendering while the script files are downloaded and evaluated. One could argue that this should only be done, if your scripts really require it to be loaded upfront.

We adhere to the practise of putting our script tags at the end of the body, thus it didn't appear to be a problem while developing and testing our components. It was simply an oversight on our end and not something we did on purpose.

I understand, there are different requirements on a project and how you load bootstrap shouldn't be your concern. This is going to be addressed with the next release, but please accept is that we are all humans and errors can happen.

**Comment by connorhu** [comment] 2021-05-08 10:24
The `defer` attribute on the script tag "solves" the issue (of course async attribute is not enough). If this will a "wontfix" at the end then we have a documentation issue.

**Comment by leecollings** [comment] 2021-05-10 14:42
Can anyone give an idea as to when this will be released? It should be pushed out ASAP as it's broken the latest release, obviously causing issues. I can't even switch back to 4.6.0 because the button action does nothing to open the modal either, with no console output. So please rather than wait for the next release, push this fix out.

**Closed** 2021-05-10 18:17 UTC
Labels: confirmed, js, p1, v5

**Comment by DonikaV** [comment] 2021-05-12 11:16
So, 
```
myModal.modal({
        keyboard: true
      });
```
Is deprecated? I am right? 
Because in my case it doesn't work. I put bootstrap scripts in to bottom but is not help me. All modals stop working.

**Comment by NotAsea** [comment] 2023-03-07 03:12
facing this issue again with bootstrap 5.10 along with Asp.net core MVC 6, when try loading modal either with pure javascript or jQuery, it throws this error again, I have try either put script in most near `</body>` tag, or add `defer` attribute but this won't fix. 
HELP!!

**Comment by julien-deramond** [comment] 2023-03-07 05:39
Hey @NotAsea
This issue is closed. If you're facing a problem, please create a new issue referencing this one and include a live reproducible example. Otherwise, it's impossible for us to track already-closed stuff.

**Comment by tertek** [comment] 2023-04-24 14:00
In case anyone else stumbles here, this is what solved it for me:
https://github.com/twbs/bootstrap/issues/38307#issuecomment-1485570305
