### ISSUE TITLE
tooltip is not working if inited twice for single node

### ISSUE THREAD

**Issue by Drive4ik** [twbs/bootstrap#16641] opened 2015-06-15 18:48 UTC
Hello.
I found a bug in versions 3.3.2 - 3.3.4. in 3.3.1 this bug not replicated.
Please, see example
http://jsbin.com/hoyiwirudu/1/edit?html,js,output

**Comment by cvrebert** [comment] 2015-06-15 20:15
@Drive4ik Please upgrade the JS in your example to v3.3.4.

**Comment by kkirsche** [comment] 2015-06-16 00:22
Forked JSBin with v3.3.4:
http://jsbin.com/juvugi/edit?html,js,output

**Comment by cvrebert** [comment] 2015-06-16 03:08
Duplicate of #14167, which is on our list of things to consider fixing in v4.

**Closed by cvrebert** 2015-06-16 03:08 UTC
Labels: js
