### ISSUE TITLE
v4 - Flex broken in IE10

### ISSUE THREAD

**Issue by Skwai** [twbs/bootstrap#18165] opened 2015-11-04 22:34 UTC
IE10 seems to require max-width properties on columns as well as the autoprefixed -ms-flex-preferred-width: x%

My solution 

```
@mixin make-col-span($size, $columns: $grid-columns) {
  @if $enable-flex {
    flex: 0 0 percentage($size / $columns);
    // this fixes width of columns in IE10
    max-width: percentage($size / $columns);
    
     // Disable the max-width for browsers that actually support flex
    @supports (display: flex) {
      max-width: none;
    }
  } @else {
    width: percentage($size / $columns);
  }
}
```

**Comment by cvrebert** [comment] 2015-11-04 23:24
Duplicate of #17310.

**Closed by cvrebert** 2015-11-04 23:24 UTC
Labels: css, v4
