### ISSUE TITLE
Docs minor typo: v5 is Installed by yarn with yarn install bootstrap@next

### ISSUE THREAD

**Issue by yhk1038** [twbs/bootstrap#31271] opened 2020-07-10 05:19 UTC
### Operating system and version
In MacOS Catalina v10.15.5  
yarn 1.22.4

### Detail
In official v5 document for [**getting started**](https://v5.getbootstrap.com/docs/5.0/getting-started/download/), the part of `Install with yarn` looks like this:

![image](https://user-images.githubusercontent.com/13119624/87119014-cd74a980-c2b7-11ea-93a5-f10c7c01fe2e.png)

But it isn't working.

Running `yarn install bootstrap` install `bootstrap@4.5.0` pakage.

To install `5.0.0-alpha1`, It should be fix `yarn install bootstrap@next`, such as `Install with npm`. Then it works fine.

**Comment by Laim** [comment] 2020-07-10 13:06
I assume that would be because V5 isn't a non-alpha release yet?  Not sure if updating the docs to include @next is worth it since it would need to be removed once it goes live anyway?

**Comment by rohit2sharma95** [comment] 2020-07-10 13:28
This has been done already in #31075 
@Laim These are being tracked in #31057

**Comment by mdo** [comment] 2020-07-10 20:14
Duplicate of #31075.

**Closed by mdo** 2020-07-10 20:14 UTC
