### ISSUE TITLE
Justified nav is not working on chrome !

### ISSUE THREAD

**Issue by beingsagir** [twbs/bootstrap#19645] opened 2016-03-31 08:51 UTC
Here is the output of a theme sample on Chrome!

Example name : Justified nav

![onchrome](https://cloud.githubusercontent.com/assets/1620769/14170487/b33428f2-f74b-11e5-926a-41c30f37d79f.png)

**Comment by RyanZim** [comment] 2016-03-31 13:20
If you are referring to a theme at http://themes.getbootstrap.com, please do not report it here. See: [CONTRIBUTING.md#using-the-issue-tracker](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker).

**Comment by cvrebert** [comment] 2016-03-31 22:30
Duplicate of #17723. Please search more next time.

**Closed by cvrebert** 2016-03-31 22:30 UTC
Labels: css, examples, v4

**Comment by kutec** [comment] 2016-05-30 09:09
Not only Chrome in all browsers it's not working!
