### ISSUE TITLE
Typing in the documentation search bar scrolls the page

### ISSUE THREAD

**Issue by septatrix** [twbs/bootstrap#35882] opened 2022-02-22 12:13 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When typing something in the search bar the page scrolls up.

https://user-images.githubusercontent.com/24257556/155130144-4d48b9e5-1725-4593-9356-d45afc7e7afd.mp4

### Reduced test cases

Visit the docs, scroll down some page and type stuff in the search bar.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

Whichever the docs for v5.1 use

**Comment by ffoodd** [comment] 2022-02-22 17:25
I think we already tracked this down to `scroll-margin-top` or something. I can't find the related issue or PR though.

**Comment by nkdas91** [comment] 2022-02-23 12:27
PR: #35393

**Comment by mdo** [comment] 2022-02-23 15:58
Closing as duplicate of #33993, thanks @nkdas91.

**Closed by mdo** 2022-02-23 15:58 UTC
Labels: docs
