### ISSUE TITLE
NPM install throws an error in the node_modules folder

### ISSUE THREAD

**Issue by baasdesign** [twbs/bootstrap#19696] opened 2016-04-09 09:25 UTC
When I install Bootstrap trough NPM and try to install the dependencies in the _package.json_ (for Grunt)
I get an error. 

These are the steps I take:

- `npm install bootstrap`
- `cd node_modules/bootstrap`
- `npm install`

Then the following error occurs:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path /Users/Baasdesign/Desktop/Bootstrap/node_modules/bootstrap/node_modules/.staging/bootstrap-30f364fe
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename '/Users/Baasdesign/Desktop/Bootstrap/node_modules/bootstrap/node_modules/.staging/bootstrap-30f364fe' -> '/Users/Baasdesign/Desktop/Bootstrap/node_modules/bootstrap'
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/Baasdesign/Desktop/Bootstrap/node_modules/bootstrap/node_modules/.staging/bootstrap-30f364fe' -> '/Users/Baasdesign/Desktop/Bootstrap/node_modules/bootstrap'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path npm-debug.log.3513812185
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.3513812185'
npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.3513812185'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Baasdesign/Desktop/Bootstrap/node_modules/bootstrap/npm-debug.log
npm ERR! code 1
```
It then cleans the entire node_modules folder.
When I install bootstrap with `bower install bootstrap` and take the same steps. No problem.
When I use the `package.json` from the bower install IN the npm install folder and run `npm install`...everything works fine. It seems that something is wrong with the package.json delivered trough the NPM installation. 

sysInfo:

- OSX Yosemite
- Node 5.10.1
- NPM 3.8.6

**Comment by RyanZim** [comment] 2016-04-09 17:49
I'm running:

- Lubuntu 14.04.4 LTS
- Node v5.7.1
- NPM 3.6.0

I followed the reproduction steps except I ran `npm install bootstrap --save` instead of `npm install bootstrap`. I was unable to reproduce.

I tried again, this time installing bootstrap as an extraneous package (`npm install bootstrap`). I received this output when running `npm install` in `node_modules/bootstrap`:

```
npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm ERR! Linux 3.19.0-58-generic
npm ERR! argv "/home/ryan/.nvm/versions/node/v5.7.1/bin/node" "/home/ryan/.nvm/versions/node/v5.7.1/bin/npm" "install"
npm ERR! node v5.7.1
npm ERR! npm  v3.6.0

npm ERR! Cannot read property 'target' of null
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ryan/test-twbs/test2/node_modules/bootstrap/npm-debug.log
```

Not sure what the issue is. @baasdesign, could you try `npm install bootstrap --save`? Also, you could try `npm cache clean`. I've seen weird issues like this come down to a corrupted npm cache.

I assume you're installing the latest stable version of bootstrap.

**Comment by wolfy1339** [comment] 2016-04-09 18:12
When you do npm install bootstrap it should automatically install any and all dependencies... No need to go into the bootstrap directory located in the node_modulea directory.
This issue seems invalid to me

**Comment by RyanZim** [comment] 2016-04-09 18:23
@wolfy1339 I'm not sure exactly what his use case is; I assumed he wanted the devDependencies installed.

**Comment by wolfy1339** [comment] 2016-04-09 18:58
They get installed too if you do npm install
Otherwise it would be noted in the docs

**Comment by RyanZim** [comment] 2016-04-09 19:21
@wolfy1339 Not in this context.

If you have a package "foo" and you run `npm install` in its directory, it will install foo's dependencies and devDependencies, but not the devDependencies of foo's dependencies. devDependencies are not needed in production.

**Comment by cvrebert** [comment] 2016-04-09 21:30
Duplicate of https://github.com/npm/npm/issues/12279.

**Closed by cvrebert** 2016-04-09 21:30 UTC
Labels: meta, v3
