### ISSUE TITLE
missing ".dropdown-menu-right" in v4.0.0-beta

### ISSUE THREAD

**Issue by mrGibi** [twbs/bootstrap#23308] opened 2017-08-11 11:28 UTC
In v4.0.0-beta there is no `.dropdown-menu-right` class.
It was included in v4.0.0-alpha6 and its there in docs.

**Comment by Johann-S** [comment] 2017-08-11 11:30
That's right because Dropdown now depend on Popper.js and when you applied `.dropdown-menu-right` to your Dropdown it will be positionned by Popper.js not by CSS

**Comment by realtarget** [comment] 2017-08-12 09:37
Same here. The menu opens out of page in my right aligned navbar :-(

![image](https://user-images.githubusercontent.com/4380964/29239591-9a371644-7f52-11e7-96f8-6302607e97d5.png)

**Comment by CapturedMomentum** [comment] 2017-08-12 15:21
I encountered a similar issue as shown in realtarget's comment this morning after updating to the new bootstrap version. 

Looking at `node_modules/bootstrap/css/_navbar.scss` file in my dependencies, I found `.dropdown-menu-right` is still declared there but the generated selectors will be in the form: 
`.navbar-expand .navbar-nav .dropdown-menu-right` 

I believe the changelog mentioned that `.navbar-toggleable` was replaced by `.navbar-expand`

In my case, in the places where `.dropdown-menu-right` quit working as expected the elements with `.dropdown-menu-right` were not inside those 2 `.navbar` classes. I modified my HTML structure to so the dropdown menu to match that rule and it did fix the alignment issue for me.

Hope that helps somebody.

**Comment by Johann-S** [comment] 2017-08-12 16:10
We cannot help you without a live example in a JSBin or Codepen

**Comment by realtarget** [comment] 2017-08-12 16:58
I've copied the example dropdown from [getbootstrap.com](https://getbootstrap.com/docs/4.0/components/navs/#tabs-with-dropdowns) and now it works for me.

![image](https://user-images.githubusercontent.com/4380964/29242556-b828879a-7f8f-11e7-8b13-9742189e6a1d.png)

Unfortunately i can't reproduce the error.

**Comment by mdo** [comment] 2017-08-12 20:43
Closing out then. Please make sure y'all are using the latest code from the new beta docs <3.

**Closed by mdo** 2017-08-12 20:43 UTC

**Comment by froodley** [comment] 2017-08-16 02:41
I am having the same problem.  I have reproduced it here:

https://jsbin.com/qemicohayu/edit?html,output

**Comment by JavanXD** [comment] 2017-08-17 09:31
I could not reproduce it: https://www.codeply.com/go/ULpwrXl7R1 
But in my project i have also this issue since upgrading from alpha.6 to beta:
![grafik](https://user-images.githubusercontent.com/4342160/29405816-57867902-833f-11e7-9fc7-967d988a23e4.png)
Can't find the difference

**Comment by Johann-S** [comment] 2017-08-17 09:43
See my answer here : https://github.com/twbs/bootstrap/issues/23479#issuecomment-323020849
@JavanXD
