### ISSUE TITLE
Deprecated warning scss functions

### ISSUE THREAD

**Issue by MoatezNG** [twbs/bootstrap#37497] opened 2022-11-15 10:37 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `bootstrap@5.2.2` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/bootstrap/scss/_functions.scss b/node_modules/bootstrap/scss/_functions.scss
index 969a4b0..26c953b 100644
--- a/node_modules/bootstrap/scss/_functions.scss
+++ b/node_modules/bootstrap/scss/_functions.scss
@@ -198,7 +198,7 @@ $_luminance-list: .0008 .001 .0011 .0013 .0015 .0017 .002 .0022 .0025 .0027 .003
 // Return opaque color
 // opaque(#fff, rgba(0, 0, 0, .5)) => #808080
 @function opaque($background, $foreground) {
-  @return mix(rgba($foreground, 1), $background, opacity($foreground) * 100);
+  @return mix(rgba($foreground, 1), $background, opacity($foreground) * 100%);
 }
 
 // scss-docs-start color-functions
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by julien-deramond** [comment] 2022-11-15 10:44
Closing it. Duplicate of https://github.com/twbs/bootstrap/issues/37424 already fixed.

**Closed by julien-deramond** 2022-11-15 10:44 UTC

**Comment by yanyiik99** [comment] 2023-05-05 07:24
thank you brother
