### ISSUE TITLE
[feature request] add step component

### ISSUE THREAD

**Issue by Misiu** [twbs/bootstrap#15689] opened 2015-01-28 14:15 UTC
Recently I had to create step indicator for one of my school project, I couldn't find anything inside bootstrap so I build one based on tutorial found on internet, unfortunately it wasn't responsive.
I searched for other steps components and I found this: http://demo.titon.io/?step
Maybe there can be similar component added to bootstrap?

Here is my current steps indicator:
![image](https://cloud.githubusercontent.com/assets/1741838/5938934/bec74ac0-a6ff-11e4-9fe0-1c34495b8caf.png)

here is titon version:
![image](https://cloud.githubusercontent.com/assets/1741838/5939016/5cb036b6-a700-11e4-8d9d-e4ea70d2923f.png)

What do You think? Are there any chances this might be added?

**Comment by cvrebert** [comment] 2015-01-28 16:44
Duplicate of #1982 (among several others).

**Closed by cvrebert** 2015-01-28 16:44 UTC
Labels: css, feature
