### ISSUE TITLE
Wrong or unclear justified nav example 

### ISSUE THREAD

**Issue by Z-Doctor** [twbs/bootstrap#29217] opened 2019-08-05 20:55 UTC
On the [4.2 documentation for navs](https://getbootstrap.com/docs/4.2/components/navs/) the part about justified navs seems strange to me. Here is a snapshot of the example.
![snapshot of example](https://i.imgur.com/hVdeUE0.png)

The text for the top example reads:

> For equal-width elements, use .nav-justified. All horizontal space will be occupied by nav links, but unlike the .nav-fill above, every nav item will be the same width.

Which suggests that the following links would be equally sized, however, as you can see in the image, they are not.

I'm a beginner, so from what I can tell they're missing the "nav-item" class attribute, but even then, going by the previous example on that same page and a working example after that entry, I think they meant to put it into an unordered list, so the code would look like this:
```html
<ul class="nav nav-pills nav-justified">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Longer nav link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
  </li>
</ul>
```

Which would look like this (edited html on the page for code section):
![Corrected Html Code](https://i.imgur.com/p79yMA3.png)

If I am wrong, let me know.

**Comment by Z-Doctor** [comment] 2019-08-05 21:00
Fixed link to the second image.

**Comment by XhmikosR** [comment] 2019-08-06 10:10
Well, for one you shouldn't use such an old version :P

Is the issue present in the latest 4.x docs?

**Comment by ysds** [comment] 2019-08-06 15:26
Duplicate of #28117, and fixed in #28193.

**Closed by ysds** 2019-08-06 15:26 UTC
Labels: awaiting reply, docs

**Comment by Z-Doctor** [comment] 2019-08-06 20:17
I'm so dumb. I kept thinking I was in the latest docs. lol ty for letting me know. Also, if it was fixed, why is it still there?

**Comment by ysds** [comment] 2019-08-06 22:19
That is the old docs. You can see v4.3 docs: https://getbootstrap.com/docs/4.3/components/navs/
