### ISSUE TITLE
Text Input and Date Input in form when using class .form-row

### ISSUE THREAD

**Issue by psingl** [twbs/bootstrap#23730] opened 2017-08-29 14:03 UTC
There is a little alignment issue when using form->div.form-row When using text input and date input both together the date input height is more than text input as shown in image attatched.
![image](https://user-images.githubusercontent.com/13885706/29824857-38db5206-8cf0-11e7-83c3-ac25094ce8b7.png)
I am attaching the code also in below image for the form shown above
![image](https://user-images.githubusercontent.com/13885706/29825101-f0ba39f0-8cf0-11e7-983a-8d2f755aaf2b.png)

**Comment by psingl** [comment] 2017-08-29 14:19
Pull Request created #23731

**Comment by diemedina** [comment] 2017-08-29 14:35
Adding class :
`.form-row input[type=date] {
    height: 38px;
  }`

**Comment by mdo** [comment] 2017-08-29 15:33
Duplicate of #18842.

**Closed by mdo** 2017-08-29 15:33 UTC
Labels: v4
