### ISSUE TITLE
font weight semi bold class does not work 

### ISSUE THREAD

**Issue by Ahmed-Elbessfy** [twbs/bootstrap#37207] opened 2022-09-26 10:34 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi, I have tried to use `.fw-semibold` class but it applies nothing. I can't find it in the console at all. I would like to add it or make the change but don't know exactly which file I need to modify. 

### Reduced test cases

![Untitled](https://user-images.githubusercontent.com/25265723/192255759-3a19c6f9-b8f7-4c09-a44c-0bf942a1000d.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.2

**Comment by coliff** [comment] 2022-09-26 10:46
The `fw-semibold` class does work as expected. You can see it in the example in the docs at: https://getbootstrap.com/docs/5.2/utilities/text/#font-weight-and-italics
It shows this in Elements inspector:
![image](https://user-images.githubusercontent.com/1212885/192257706-999a4932-8260-4427-a9b2-6259c8a4a5ad.png)

If it's not showing for you then double-check you are including the `_utilities.scss` (if compiling from Sass) and ensure you're loading the latest Bootstrap CSS. The problem is with your setup and not with Bootstrap itself.

**Comment by julien-deramond** [comment] 2022-09-26 11:23
Thanks @coliff for providing the answer. I'm closing this issue since there's no problem with Bootstrap itself.

**Closed by julien-deramond** 2022-09-26 11:23 UTC
