### ISSUE TITLE
Navbar: Toggle button isn't accessible when is in container on iOS

### ISSUE THREAD

**Issue by jelen07** [twbs/bootstrap#21993] opened 2017-02-15 07:24 UTC
#### browser bug
When navbar toggle button (button.navbar-toggler) is within container, it has bad accessibility.

Check the [video](https://youtu.be/m6Pd_RGS4D0) - there are two navbars. The first is "normal" and the second is with div.container. When you are trying to click on toggle button, mostly nothing had happend.

[codepen](http://codepen.io/jelen/pen/XpGjMz)

Reproduced on Safari browser, iPhone 5S, iOS 10.0.1.
On macOS Safari it works well as on first picked Android device.

**Comment by mdo** [comment] 2017-03-19 02:17
Dupe of #21590.

**Closed by mdo** 2017-03-19 02:17 UTC
Labels: css, v4
