### ISSUE TITLE
.table-responsive inside .media-body problem

### ISSUE THREAD

**Issue by ezekel** [twbs/bootstrap#17376] opened 2015-08-28 02:16 UTC
Hi, I am having problem in viewing on small devices like mobile, the table inside in media body is not responsive in small devices.

Thank you in advance.
```html
           <div class="panel panel-primary">
                   <div class="panel-heading ">
                       <h3 class="panel-title">
                           Profile
                       </h3>
                   </div>
                   <div class="panel-body">
                       <div class="col-xs-12 col-sm-12 col-md-12">
                           <div class="media">
						         <div class="media-left">
								   <a href="#">
									      <img class="media-object img-size160" src="images/officestaff.jpg" alt="">
									</a>
								  </div>
										<div class="media-body">
										<div class="table-responsive">
											<table class="table">
											<tr><td class="info" width="40%">Name</td><td>Jenny</td></tr>
											<tr><td class="info">Location</td><td>New york</td></tr>
											<tr><td class="info">Designation</td><td>Office staff</td></tr>
											<tr><td class="info">Status</td><td>Probitionary</td></tr>.
											</table>
										</div>
										</div>
                           </div>                           
                       </div>
                   </div>
               </div> <!--//end panel-->


```

**Comment by ezekel** [comment] 2015-08-31 08:40
@cvrebert , can I ask your help on this ?Thank you.

**Comment by cvrebert** [comment] 2015-08-31 08:47
Duplicate of #15622.

**Closed by cvrebert** 2015-08-31 08:47 UTC
Labels: css, v3

**Comment by ezekel** [comment] 2015-08-31 10:06
@cvrebert , adding 1000px width to media body still doesn't work.

**Comment by ezekel** [comment] 2015-08-31 10:16
@cvrebert , I just put "overflow:auto" in media class and in media-body to have scrollbar.

**Comment by cvrebert** [comment] 2015-08-31 17:51
The underlying issue has been closed as WontFix. For further assistance regarding this matter, please try one of the community forums, such as StackOverflow: https://github.com/twbs/bootstrap/blob/master/README.md#community
