### ISSUE TITLE
Avoid reflow when glyphicon load

### ISSUE THREAD

**Issue by Krinkle** [twbs/bootstrap#16768] opened 2015-07-05 07:06 UTC
Is there a way to make a glyphicon reserve its dimensions so that it doesn't bump the text over when it loads? This would improve perceived performance

**Comment by cvrebert** [comment] 2015-07-05 07:17
Duplicate of #10022, which was [eventually reverted](https://github.com/twbs/bootstrap/pull/10022#issuecomment-118590542).

**Comment by mdo** [comment] 2015-07-06 01:11
You can apply custom width/height if you need, but we won't be doing that.

**Closed by mdo** 2015-07-06 01:11 UTC
Labels: css
