### ISSUE TITLE
Collapse prevents radio button update

### ISSUE THREAD

**Issue by trusche** [twbs/bootstrap#21079] opened 2016-11-03 12:30 UTC
When using `data-toggle="collapse"` and `data-target` on a radio button, the clicked radio button is not checked. See this minimal fiddle: https://jsfiddle.net/p0xkotyr/1/. Reproducible for me in Chrome (54.0), Safari (9.1.2) and Firefox (49.0.2) on OS X 10.11.6.

I didn't find any current open issue on this, just a couple of rather old closed ones:

* https://github.com/twbs/bootstrap/issues/1060
* https://github.com/twbs/bootstrap/issues/3857

Thanks for taking a look!

**Comment by Johann-S** [comment] 2016-11-03 13:02
Yes it's due to this line : https://github.com/twbs/bootstrap/blob/v4-dev/js/src/collapse.js#L354 

IMO, If you want to check the radio button, you have to listen this event ``show.bs.collapse`` and checked manually your radio button.

```javascript
$('input').on('show.bs.collapse', function() {
  $(this).attr('checked', 'checked');
})
.on('hide.bs.collapse', function() {
  $(this).attr('checked', '');
});

**Comment by trusche** [comment] 2016-11-03 15:20
I get that, but isn't the point of using `data-` attributes to avoid the need to roll your own JS? But if this is by design, perhaps it's worth a short explanation in the docs?

**Comment by Johann-S** [comment] 2016-11-03 15:28
As it said in the documentation (See http://v4-alpha.getbootstrap.com/components/collapse/#via-data-attributes) : 

> Just add data-toggle="collapse" and a data-target to the element to automatically assign control of a collapsible element.

By doing this you didn't declare your Collapse in JavaScript like this ``$('input').collapse()`` that's all

**Comment by sebastienros** [comment] 2016-12-05 23:56
The behavior comes from the call to `event.preventDefault();` in the click event handler. Is the recommended option to check if the target is a radio/checkbox input, or to actually add custom code to counter the effect by adding a `checked` attribute manually?

Testing the type of target should not be hard, but would probably require to think about which elements should fall into this list if not just radio and checked.

I have tried @Johann-S 's suggestion but this specific event is triggered on the targeted collapsed element, not the originator. I found the `click.bs.collapse.data-api` event though, but whatever I tried to do the checkbox doesn't reflect it's checked property or status.

**Comment by Johann-S** [comment] 2016-12-06 10:03
Yeah my suggestion was bad sorry for that but yes what I want to suggest is exactly what you said : 

> Testing the type of target should not be hard, but would probably require to think about which elements should fall into this list if not just radio and checked.

**Comment by mdo** [comment] 2017-03-26 23:12
Closing as a dupe of #22049.

**Closed by mdo** 2017-03-26 23:12 UTC
Labels: js, v4
