### ISSUE TITLE
Accordion bug

### ISSUE THREAD

**Issue by HUiTHEME** [twbs/bootstrap#37117] opened 2022-09-09 16:16 UTC
### Prerequisites

- [x] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://getbootstrap.com/docs/5.2/components/accordion/

![Accordion bug](https://s2.loli.net/2022/09/10/BtEhyTU4GkWseHZ.gif)

Not recovered

### Reduced test cases

Not recovered

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2

**Comment by julien-deramond** [comment] 2022-09-09 20:41
Duplicate of #35685.

**Closed by julien-deramond** 2022-09-09 20:41 UTC
