### ISSUE TITLE
<select> should be same height as other form elements

### ISSUE THREAD

**Issue by sodevious** [twbs/bootstrap#20318] opened 2016-07-17 21:50 UTC
The current `<select>` is smaller than other form elements. In bootstrap v3, the `<select>` was the same size as the rest of the form elements.

- Chrome Version 51.0.2704.103 (64-bit)
- See: http://v4-alpha.getbootstrap.com/components/forms/
- Example: https://jsbin.com/perosuzume/1

Screenshot of v3:
<img width="888" alt="screenshot 2016-07-17 17 49 53" src="https://cloud.githubusercontent.com/assets/915966/16903248/e7b0c9be-4c46-11e6-9b7c-5d6b1328e571.png">

Screenshots of v4:
<img width="613" alt="screenshot 2016-07-17 17 48 35" src="https://cloud.githubusercontent.com/assets/915966/16903239/b3d9d96e-4c46-11e6-822f-f66064629c7d.png">

<img width="493" alt="screenshot 2016-07-17 17 41 06" src="https://cloud.githubusercontent.com/assets/915966/16903228/2f7162a0-4c46-11e6-877f-8463a408deac.png">

**Comment by wolfy1339** [comment] 2016-07-17 22:11
this is an already known issue

**Comment by cvrebert** [comment] 2016-07-18 02:41
Duplicate of #17194. Please search more in the future. Thanks.

**Closed by cvrebert** 2016-07-18 02:41 UTC
Labels: css, v4
