### ISSUE TITLE
LTR and RTL at the same time spacing issue

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33065] opened 2021-02-12 16:09 UTC
I'm using **Bootstrap 5 LTR and RTL** mode at the same time but I get an issue with `ms-2` spacing class when I switch to **RTL** mode not working??

**the issue :** 

![Image](https://i.imgur.com/jnzoExd.png)

**The Bootstrap Version (package.json)**

```
"dependencies": {
   "bootstrap": "^5.0.0-beta1",
}

```

**The Main file (app.scss)**

```
/* rtl:begin:options: {
  "autoRename": true,
  "stringMap":[
    "name": "ltr-rtl",
    "priority": 100,
    "search": ["ltr"],
    "replace": ["rtl"],
    "options": {
      "scope": "*",
      "ignoreCase": false
    }
  ]
} */
.ltr {
    @import "~bootstrap/scss/bootstrap";
	@import "~bootstrap/scss/functions";
	@import "~bootstrap/scss/variables";
	@import "~bootstrap/scss/mixins";
}
/*rtl:end:options*/
```

_Note : When I use the same thing in **[Codepen.io](https://codepen.io/themes4all/pen/vYyyozb)** with CDN links it work Here is a **[preview link](https://codepen.io/themes4all/pen/vYyyozb)**._

**Comment by ffoodd** [comment] 2021-02-12 16:25
You're not supposed to use both CSS files in the same page, [as mentioned in our docs](https://getbootstrap.com/docs/5.0/getting-started/rtl/#required-html). You may have a look at our starter template in that page, using a single CSS file.

If you need RTL and LTR at the same time, you'll need to [use Sass and tweak your build a bit](https://getbootstrap.com/docs/5.0/getting-started/rtl/#required-html). But our official build (thus releases available through a CDN) won't work with both directions in the same page.

We plan to add an example template with some bidi contents in #32330 — but it's not done yet. I close this issue since it works as intended.

We'd be pleased to get any insights or suggestions you'd have to help us improve our docs or template example, though. :)

**Closed by ffoodd** 2021-02-12 16:25 UTC
