### ISSUE TITLE
Multiple selects spill out of container in v4-docs

### ISSUE THREAD

**Issue by ZakStrassberg** [twbs/bootstrap#20582] opened 2016-08-26 00:44 UTC
The example multiple select on v4-docs is off for me. The numbers spill out of the container.

[Here is an image](https://files.slack.com/files-pri/T04GZKGQY-F252AJTPC/pasted_image_at_2016_08_25_03_15_pm.png?pub_secret=23a0a0bb23)

It seems like problems with `overflow: hidden`. You can fix it with `select.form-control { overflow-y: hidden; }` in your CSS.

**Comment by cvrebert** [comment] 2016-08-26 05:36
Duplicate of #20384. Please search more in the future! Thanks.

**Closed by cvrebert** 2016-08-26 05:36 UTC
