### ISSUE TITLE
Nested modals not working (regression since 5.1.0)

### ISSUE THREAD

**Issue by nfplee** [twbs/bootstrap#34982] opened 2021-09-15 10:58 UTC
See https://jsfiddle.net/5chsroyL/ for an example. If you change the version to 5.1.0 then it works fine.

**Comment by GeoSot** [comment] 2021-09-15 11:42
I am not sure, if it is a js issue. As you can see in the bellow screen, the second modal is has the class `show`, however, being inside a hidden modal, I am not sure that can be seen on screen.

On 5.1.0 was working this way cause of the regression I suppose, and our documentation, doesn't support nested
Any opinions would help here. 

![image](https://user-images.githubusercontent.com/22406063/133426501-c5dfb068-a3a3-4e79-b48f-7d2514f26e91.png)

**Comment by nfplee** [comment] 2021-09-15 12:25
I've been using nested modals since version 3. For example say you have a form within a modal, that form may have an option to select a product. The select product functionality would be within the nested modal (since it requires searching and paging which would make the form quite large).

**Comment by GeoSot** [comment] 2021-09-15 12:45
@mdo 
@XhmikosR 
@patrickhlauke 
@ffoodd 

Your help please

**Comment by MrOldProger** [comment] 2021-09-16 11:42
@nfplee 
I think (and not only I), using nested modals should be avoided in UX.
For example, look at this: https://uxplanet.org/removing-nested-modals-from-digital-products-6762351cf6de
In your specific case - you should avoid using complex forms in modals. Use a regular pages for complex functionality instead. In good Web UX modals should be as simple as possible, typically no more than notification message or simple form. Now even login forms use not modals but pages.

**Comment by patrickhlauke** [comment] 2021-09-16 12:52
> Bootstrap only supports one modal window at a time. Nested modals aren’t supported as we believe them to be poor user experiences.

https://getbootstrap.com/docs/5.1/components/modal/

If this did happen to work in previous versions of bootstrap, it was likely purely by luck/accident, as our code is not geared towards it. As such, suggest closing this. We *may* revisit the decision not to support nested modals in future, but this will require a more fundamental fix in the JS.

**Closed by patrickhlauke** 2021-09-16 12:52 UTC

**Comment by nfplee** [comment] 2021-09-16 14:29
I guess I’ll have to find a new library then.

**Comment by salueii** [comment] 2023-03-12 16:08
using Nested Modal in app is common , and now new version of bootstrap do not support it !!!!!  😒
as nfplee said since then new library must be used.

**Comment by RomanApunts** [comment] 2023-03-15 10:33
This functionality its commonly used for me and others... Maybe hability to support it with a data attribute or something...

I hope bootstrap take back this hability to work again.
