### ISSUE TITLE
MAXCDN repository link unstable

### ISSUE THREAD

**Issue by Whirler** [twbs/bootstrap#21271] opened 2016-12-01 21:47 UTC
We've been having some very spotty performance from the hosted bootstrap links i the last week or two. We are using the ones given here: http://getbootstrap.com/getting-started/

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css
https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js

I am getting an error "This site can’t be reached. The connection was reset maxcdn.bootstrapcdn.com unexpectedly closed the connection."

I've tested across half a dozen different ISP's and these files seems to be inaccessible most of the time. I've tested on different platforms and browsers as well. So it doesn't seem like the problem is on my end.

If I change the sub-domain to www they seem to load fine:
https://www.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css
https://www.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css
https://www.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js

I would prefer not having to do this changed on hundreds of sites that are using these files though. Also, I wouldn't want to rely on that moving forward if the maxcdn sub-domain is the 'official' one.

**Comment by wolfy1339** [comment] 2016-12-01 22:57
There is also: http://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css
Which is listed on the boostrapcdn main page. I would use that instead

**Comment by bardiharborow** [comment] 2016-12-01 23:35
@Whirler I can't reproduce this. Could you provide a traceroute for each of the domains?

**Comment by y0z3431** [comment] 2016-12-02 19:27
We are seeing the same issue today.

**Comment by y0z3431** [comment] 2016-12-02 19:44
Changing https to http seem to load fine.

**Comment by cvrebert** [comment] 2016-12-06 18:54
Please file an issue with the BootstrapCDN folks:
https://github.com/MaxCDN/bootstrap-cdn/issues

**Comment by andreslucero** [comment] 2016-12-10 17:18
@Whirler CDNJS also provides hosting for Bootstrap if you're looking for an alternative:
https://cdnjs.com/libraries/twitter-bootstrap/3.3.7

According to [CDN Perf](https://www.cdnperf.com/) it has lower average latency than BootstrapCDN as well.

**Comment by mdo** [comment] 2016-12-22 03:42
Closing out for now since issues seem to have resolved themselves.

**Closed by mdo** 2016-12-22 03:42 UTC
Labels: meta
