### ISSUE TITLE
Has a fixed value for html font-size and not percentage, no browser resize?

### ISSUE THREAD

**Issue by ianjohnspain** [twbs/bootstrap#20326] opened 2016-07-19 12:17 UTC
Hi,

I just noticed that according to the font-size set on the html element, it is using a fixed value rather than percentage. It used to use a percentage right ? I am sure there is a reason behind this. Actually I was just testing increasing the browser font size and my current site doesn't resize when fonts are changed.

I presume this is because it doesn't offer a percentage base REM ?

I would really appreciate some help, this what i am seeing on the html
```

html {
  font-size: 10px;

  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```

actually I just noticed, it seems to be redefined on the body too 

```
body {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 14px;
  line-height: 1.42857143;
  color: #333;
  background-color: #fff;
}
```

**Comment by cvrebert** [comment] 2016-07-19 17:16
Approximate duplicate of #19460.

**Closed by cvrebert** 2016-07-19 17:16 UTC
Labels: css, v4
