### ISSUE TITLE
Error: $color: "var(--bs-primary-rgb)" is not a color for `rgba' in v5.1.0

### ISSUE THREAD

**Issue by harnishdesign** [twbs/bootstrap#34693] opened 2021-08-05 13:14 UTC
I try to compile in latest **v5.1.0** So, I get error as below. have i wrong anything?

> Error: $color: "var(--bs-primary-rgb)" is not a color for `rgba'
>         on line 41 of C:/xampp/htdocs/myproject/sass/bootstrap/_functions.scss
>         from line 2 of C:\xampp\htdocs\myproject\sass\stylesheet.scss

My stylesheet.scss

```
@import "bootstrap/functions";
@import "bootstrap/variables";
@import "bootstrap/mixins";
@import "bootstrap/vendor/rfs";

// Initialize
@import "variables";
@import "mixins";

// Core CSS
@import "reset";
@import "helpers";
@import "layouts";

// Content Blocks
@import "elements";
@import "social-icons";
@import "extras";
```

**Comment by diyadin2** [comment] 2021-08-05 13:44
i have the same problem

**Comment by morrow95** [comment] 2021-08-05 15:18
Same here

**Comment by mdo** [comment] 2021-08-05 16:28
Can you provide a reduced test case here? We use these RGB values to form RGBA colors for greater customization. It's not immediately clear here from your report what function or context is failing.

**Comment by morrow95** [comment] 2021-08-05 17:04
Line 41 from _functions.scss is : 

```
40 : @function rgba-css-var($identifier, $target) {
41 :  @return rgba(var(--#{$variable-prefix}#{$identifier}-rgb), var(--#{$variable-prefix}#{$target}-opacity));
42 : }
```

The original OP is doing the same thing as I am.  Importing the following in a custom scss file : 
```
@import "bootstrap/functions";
@import "bootstrap/variables";
@import "bootstrap/mixins";
```

so the variables, mixins, etc can be used in in that file.  No issues with prior versions... only started happening when I tried BS 5.1.0.

**Comment by mdo** [comment] 2021-08-05 18:00
I'm not seeing issues on my end when compiling `bootstrap.scss` with only those three imports, or in the `bootstrap-npm-starter` project when importing those into a custom stylesheet.

Anyone have a reduced test case to show the problem?

**Comment by diyadin2** [comment] 2021-08-05 18:19
Error while compiling scss file with Koala program.

**Comment by diyadin2** [comment] 2021-08-05 18:27
![1](https://user-images.githubusercontent.com/16868277/128402130-fee8d997-420d-4943-9465-9d00100869f7.jpg)

**Comment by ffoodd** [comment] 2021-08-05 18:33
@mdo Could be some compilers compatibility issue again, regarding `rgba()` that could be both a Sass function and a CSS function.

Sass (Ruby but maybe Libsass too) would throw an error since it needs a `color` value.

**Comment by MaxxDelusional** [comment] 2021-08-05 20:08
My sass is compiling correctly, but I get an error in the Edge dev tools, and the css class is not working.

```
Invalid Property Value:
background-color: get-function(rgba-css-var)("primary", "bg") !important
```
![image](https://user-images.githubusercontent.com/6978726/128414311-cb22d9f7-dad5-4d2e-8652-a1528e5a5e2c.png)

**Comment by mdo** [comment] 2021-08-05 20:32
@ffoodd Definitely seems that way. Dart Sass working without issue in our repo and the npm starter kit.

@MaxxDelusional Looks like that's not compiling correctly then. What version of Sass are you using?

**Comment by morrow95** [comment] 2021-08-05 22:58
@diyadin2 Using Koala here as well.

**Comment by harnishdesign** [comment] 2021-08-06 03:57
@mdo   I am also using Koala and get error.

**Comment by MaxxDelusional** [comment] 2021-08-06 12:21
@mdo I am using the Web Compiling extension for Visual Studio. I am not entirely sure what compiler it uses behind the scenes.

https://github.com/madskristensen/WebCompiler

**Comment by morrow95** [comment] 2021-08-06 15:27
For what it's worth, those of us using Koala already know that it hasn't been updated/supported in years now, but it looks like quite a lot of others haven't been updated either from the responses coming in.  Nothing wrong with the code being used just that a lot of us have compilers that can't handle it yet or are using ones like Koala that will never be updated.

Sidenote... someone should really come out with a Koala-like app for Windows as a replacement.  I would gladly pay for something with the same features/usability - haven't found anything close to it which is why I still use it.

**Comment by harnishdesign** [comment] 2021-08-07 11:57
@morrow95 Yes, You are right. Koala hasn't been updated/supported.

@diyadin2  I am trying with [Scout-app](https://scout-app.io/) and, It is working fine now.

**Comment by morrow95** [comment] 2021-08-09 16:18
Is there any workaround for the time being while I try to find a replacement compiler?  I'd prefer not to mod bs's scss files directly, but will do so in the meantime.

**Comment by harms-tbd** [comment] 2021-08-09 16:48
> @mdo I am using the Web Compiler extension for Visual Studio. I am not entirely sure what compiler it uses behind the scenes.
> 
> https://github.com/madskristensen/WebCompiler

I am using the same compiler and experiencing the same issue.

**Comment by mdo** [comment] 2021-08-09 17:20
Oh boy, that compiler hasn't been updated in 6 years... I'd really suggest finding something else. I don't think we can practically provide support for something that is so far behind our development stack :\.

**Comment by cklenk** [comment] 2021-08-09 20:22
> > @mdo I am using the Web Compiler extension for Visual Studio. I am not entirely sure what compiler it uses behind the scenes.
> > https://github.com/madskristensen/WebCompiler
> 
> I am using the same compiler and experiencing the same issue.

Same here

**Comment by betojaton** [comment] 2021-08-09 22:32
I have solved it with Scout App. (¬‿¬)

**Comment by morrow95** [comment] 2021-08-10 02:11
@betojaton Scout just doesn't cut it for me... no javascript, can't do input/output maps, and so on.  Koala, when it was maintained, killed Scout in features.  I'm actually looking to switch over to vs code, but trying to find a way to mimic what Koala did is proving a bit challenging since I've never used it before or know what is out there.

**Comment by icebits** [comment] 2021-08-10 11:10
For those using Web Compiler extension. The default node-sass v4.9.3 not able to compile BS v5.1.0 anymore. Please manually download latest node-sass (at least v5.0) using npm, then replace node-sass folder in C:\Users\<your id>\AppData\Local\Temp\WebCompiler1.12.394\node_modules. You also need to upgrade/replace existing Web Compiler's node.exe (located outside of node_modules folder), you can find the file after install node.js x64 for windows. Must use x64 executable file.

**Comment by softwarea** [comment] 2021-09-06 08:00
For all those using Visual Studio 2019 and Mad Kristensen's "Web Compiler" extension: yes, this extension is five years old. I uninstalled this extension and instead installed another extension called "Sass Compiler", which is from Mad Kristensen as well. Using this new extension, the errors with BS v5.1.0 went away.

**Comment by icebits** [comment] 2021-09-06 16:46
@softwarea Glad you had found the solution. Indeed it is from the same developer. Sass compiler is using libsass.dll, not sure about this library. I had cloned the Web Compiler source code and compile the vsix with latest node-sass to use on visual studio 2019. There is another developer already done the extension that work on visual studio 2022 x64. But since node-sass already deprecated, so not sure whether these two extensions will continue to work ob BS in future.

**Comment by mdo** [comment] 2021-09-06 22:06
Going to close this out as a compiler issue. I've added a mention of this to the v5.1.1 blog post (see draft at https://github.com/twbs/blog/pull/234). Please continue to leave comments here for alternative compilers for folks. Thanks!

**Closed by mdo** 2021-09-06 22:06 UTC
Labels: awaiting-reply

**Comment by zybersup** [comment] 2021-09-29 07:40
I have just faced this problem and quickly got to know the cause from this discussion. I would also love to use Koala so I tried finding a solution with Koala. Finally I got a solution using Dart Sass as a system sass in Koala. However there are some modification needed.

the following steps:

1. Download the standalone Dart Sass from https://github.com/sass/dart-sass/releases/tag/1.42.1, then extract and put it in your computer anywhere you want.
2. Go to Koala > Settings > Sass. See **Advanced Settings**. Check **Use the System Sass compiler** and put the full path to Dart Sass compiler in the box below. (In my case, it is "C:\path\to\dart-sass\sass.bat")
3. Modify the sass.bat to remove unsupported options which Koala will pass out (for its default Ruby Sass) and modify some options supported by Dart Sass. I put the following lines into sass.bat just before the real execution line.
```
set check_style=%arguments: nested=%
if not "%check_nested%"=="%arguments%" set style=expanded
set check_style=%arguments: expanded=%
if not "%check_style%"=="%arguments%" set style=expanded
set check_style=%arguments: compact=%
if not "%check_style%"=="%arguments%" set style=compressed
set check_style=%arguments: compressed=%
if not "%check_style%"=="%arguments%" set style=compressed

set sourcemap=
set check_sourcemap=%arguments:--sourcemap=%
if not "%check_sourcemap%"=="%arguments%" set sourcemap=--no-source-map

set arguments=%1 %2 %3 %4 --style=%style% %sourcemap%
```
4. Then enjoy conveniences from Koala.

Remark: Dart Sass will support only 2 options, source mapping [yes/no] and output style [expanded/compressed].

**Comment by morrow95** [comment] 2021-09-29 23:31
> I have just faced this problem and quickly got to know the cause from this discussion. I would also love to use Koala so I tried finding a solution with Koala. Finally I got a solution using Dart Sass as a system sass in Koala. However there are some modification needed.
> 
> the following steps:
> 
> 1. Download the standalone Dart Sass from https://github.com/sass/dart-sass/releases/tag/1.42.1, then extract and put it in your computer anywhere you want.
> 2. Go to Koala > Settings > Sass.
> 3. See **Advanced Settings**.
> 4. Check **Use the System Sass compiler**.
> 5. Put the full path to Dart Sass compiler in the box below. (In my case, it is "C:\path\to\dart-sass\sass.bat".)
> 6. Modify the sass.bat to remove unsupported options which Koala will pass out (for its default Ruby Sass) and modify some options supported by Dart Sass. I put the following lines into sass.bat just before the real execution line.
> 
> ```
> set check_style=%arguments: nested=%
> if not "%check_nested%"=="%arguments%" set style=expanded
> set check_style=%arguments: expanded=%
> if not "%check_style%"=="%arguments%" set style=expanded
> set check_style=%arguments: compact=%
> if not "%check_style%"=="%arguments%" set style=compressed
> set check_style=%arguments: compressed=%
> if not "%check_style%"=="%arguments%" set style=compressed
> 
> set sourcemap=
> set check_sourcemap=%arguments:--sourcemap=%
> if not "%check_sourcemap%"=="%arguments%" set sourcemap=--no-source-map
> 
> set arguments=%1 %2 %3 %4 --style=%style% %sourcemap%
> ```
> 
> 1. Then enjoy conveniences from Koala.
> 
> Remark: Dart Sass will support only 2 options, source mapping [yes/no] and output style [expanded/compressed].

@zybersup Just tried your suggestion for Dart with Koala... whenever I try to compile it errors on every file.  For example : 

C:\Users\Support\Documents\My Web Sites\BS5\example.com\_config\scss\bootstrap.scss

'Web' is not recognized as an internal or external command, operable program or batch file.  Web was unexpected at this time.

Any ideas?  Does it not like the spaces in the file location or something?  That is the only place I can think of that the word 'Web' is referenced.

**Comment by zybersup** [comment] 2021-09-30 04:08
Replied at https://github.com/oklai/koala/issues/837#issuecomment-930754728.

**Comment by riodelphino** [comment] 2022-05-18 17:40
I think the cause is in the version of 'sass' command.

I tested to compile bootstrap 5.0.0 and 5.1.3 on mac, then I got same issue.

I checked the version of 'sass' command installed by gem.
It seems to be too old. (v3.4.25)

So,
`gem uninstall sass`

Then, I think "npm is better ?"
so,
`npm install sass -g`

It works.

( I chose npm. but I guess just upgrading gem is also ok, right ? )

**Comment by dogooddesignco** [comment] 2022-08-20 13:08
I'm using Prepros to compile which is using Dart Sass 1.52.1 and I'm using Bootstrap 5.2.0. I'm getting the error:
`Undefined variable.
} @else {
  @return rgba (var(--#${$prefix}...`
on line 47, column 26 of node_modules/bootstrap/scss/_functions.scss

![image](https://user-images.githubusercontent.com/61759146/185747564-e44bd590-daaa-4ac0-8971-1af4f87f182e.png)

Is there a known issue with this version of Dart Sass and Bootstrap?

**Comment by morpolspc** [comment] 2022-08-20 14:29
@dogooddesignco  - Been using BS 5.2.0 since it came out and haven't had this issue, but I am using Koala with Dart using the info earlier in this thread (not sure if that is the difference or not).

**Comment by Bellatrix988** [comment] 2022-09-01 07:32
@dogooddesignco I had similar issue with undefined variable for the same line but for using . It turned out that in bootstrap 5.2 they replaced variable `$variable-prefix` with `$prefix` and it caused an issue for css package I'm using for.

The downgrading bootstrap to 5.1.3 helped me. It worth to try.

**Comment by mrelliot69** [comment] 2022-10-07 09:08
having also this issue with bootstrap 5.2 using scssphp compiler
any idea on how to solve it?

**Comment by mahyaghadrdan** [comment] 2022-11-07 09:47
> 6\. sass.bat j

Thank you. I did it but I can't open my sass.bat. it's opened just for less than 1 second and it's closed again. What should I do?

**Comment by maheshbokkisam** [comment] 2022-11-09 10:36
I am getting below error

 Angular 14.2.0
 Bootstrap 5.2.2

<img width="786" alt="image" src="https://user-images.githubusercontent.com/113166247/200805131-a53c7e13-a351-4697-b508-d26066fe9900.png">

my custom.scss file as below 
<img width="549" alt="image" src="https://user-images.githubusercontent.com/113166247/200807616-c0f7d615-085c-4232-b11c-1e17a35e335b.png">

**Comment by felcksn** [comment] 2022-11-15 11:42
@maheshbokkisam I get the exact same error after updating to angular 14

**Comment by cybercussion** [comment] 2022-11-16 20:29
Am I losing my mind or did they rename variables in a dot release?

**Comment by russcarver** [comment] 2022-11-19 22:03
I am getting something similar in Angular 15.0.0 (with Angular Material 15.0.0).

My app's color theme is customizable by a configuration loaded at runtime. As such, I set the theme to be based on CSS4 variables - eg:

```
$primaryPalette: (
  50 : var(--theme-primary-50),
  100 : var(--theme-primary-100),
  200 : var(--theme-primary-200),
  300 : var(--theme-primary-300),
  400 : var(--theme-primary-400),
  500 : var(--theme-primary-500),
  600 : var(--theme-primary-600),
  700 : var(--theme-primary-700),
  800 : var(--theme-primary-800),
  900 : var(--theme-primary-900),
  A100 : var(--theme-primary-A100),
  A200 : var(--theme-primary-A200),
  A400 : var(--theme-primary-A400),
  A700 : var(--theme-primary-A700),
  contrast: (
    50: var(--color__text),
    100: var(--color__text),
    200: var(--color__text),
    300: var(--color__text),
    400: var(--color__text),
    500: var(--color__text--light),
    600: var(--color__text--light),
    700: var(--color__text--light),
    800: var(--color__text--light),
    900: var(--color__text--light),
    A100: var(--color__text),
    A200: var(--color__text--light),
    A400: var(--color__text--light),
    A700: var(--color__text--light),
  )
);
```

I then alter those variables at runtime. This used to work just fine, but now, Angular Material complains (at compile time) with this:

```
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $color: var(--theme-primary-500) is not a color.
   ╷
16 │     track-color: color.adjust(mdc-theme-color.prop-value($color), $alpha: -0.75),
   │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 16:18  -palette-styles()
  node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 28:7   @content
  node_modules/@angular/material/core/mdc-helpers/_mdc-helpers.scss 176:5     @content
  node_modules/@angular/material/core/mdc-helpers/_mdc-helpers.scss 216:3     disable-mdc-fallback-declarations()
  node_modules/@angular/material/core/mdc-helpers/_mdc-helpers.scss 175:3     using-mdc-theme()
  node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 26:3   color()
  node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 53:7   @content
  node_modules/@angular/material/core/theming/_theming.scss 402:3             private-check-duplicate-theme-styles()
  node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 47:3   theme()
  node_modules/@angular/material/core/theming/_all-theme.scss 47:5            @content
  node_modules/@angular/material/core/theming/_theming.scss 402:3             private-check-duplicate-theme-styles()
  node_modules/@angular/material/core/theming/_all-theme.scss 44:3            all-component-themes()
  src/app/scss/theme/_theme.scss 146:1    
```

Based on other responses above, is it possible Angular Material has a bug where it is no longer supporting CSS4 variables in its themes?

**Comment by AdrianM** [comment] 2022-12-02 14:04
same here (css variables no longer allowed with Angular 15.0.0?)

**Comment by alicelebidev** [comment] 2022-12-05 11:05
> I am getting something similar in Angular 15.0.0 (with Angular Material 15.0.0).
> 
> My app's color theme is customizable by a configuration loaded at runtime. As such, I set the theme to be based on CSS4 variables - eg:
> 
> ```
> :root {
>   --theme-primary-50: #EEF6F5;
>   --theme-primary-100: #D4EAE7;
>   --theme-primary-200: #B8DCD7;
>   --theme-primary-300: #9CCDC7;
>   --theme-primary-400: #86C3BB;
>   --theme-primary-500: #71B8AF;
>   --theme-primary-600: #69B1A8;
>   --theme-primary-700: #5EA89F;
>   --theme-primary-800: #54A096;
>   --theme-primary-900: #429186;
>   --theme-primary-A100: #E7FFFC;
>   --theme-primary-A200: #B4FFF4;
>   --theme-primary-A400: #81FFED;
>   --theme-primary-A700: #68FFE9;
> }
> 
> $primaryPalette: (
>   50 : var(--theme-primary-50),
>   100 : var(--theme-primary-100),
>   200 : var(--theme-primary-200),
>   300 : var(--theme-primary-300),
>   400 : var(--theme-primary-400),
>   500 : var(--theme-primary-500),
>   600 : var(--theme-primary-600),
>   700 : var(--theme-primary-700),
>   800 : var(--theme-primary-800),
>   900 : var(--theme-primary-900),
>   A100 : var(--theme-primary-A100),
>   A200 : var(--theme-primary-A200),
>   A400 : var(--theme-primary-A400),
>   A700 : var(--theme-primary-A700),
>   contrast: (
>     50: var(--color__text),
>     100: var(--color__text),
>     200: var(--color__text),
>     300: var(--color__text),
>     400: var(--color__text),
>     500: var(--color__text--light),
>     600: var(--color__text--light),
>     700: var(--color__text--light),
>     800: var(--color__text--light),
>     900: var(--color__text--light),
>     A100: var(--color__text),
>     A200: var(--color__text--light),
>     A400: var(--color__text--light),
>     A700: var(--color__text--light),
>   )
> );
> 
> ...
> 
> // Define the primary, accent and warn palettes
> $default-primary-palette: mat.define-palette($primaryPalette);
> $default-accent-palette: mat.define-palette($accentPalette);
> $default-warn-palette: mat.define-palette($warnPalette);
> 
> // Create the Material theme object
> $theme: mat.define-light-theme($default-primary-palette, $default-accent-palette, $default-warn-palette);
> 
> @include mat.all-component-themes($theme);
> 
> // Apply the theme to the user components
> @include components-theme($theme);
> ```
> 
> I then alter those variables at runtime. This used to work just fine, but now, Angular Material complains (at compile time) with this:
> 
> ```
> HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> SassError: $color: var(--theme-primary-500) is not a color.
>    ╷
> 16 │     track-color: color.adjust(mdc-theme-color.prop-value($color), $alpha: -0.75),
>    │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    ╵
>   node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 16:18  -palette-styles()
>   node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 28:7   @content
>   node_modules/@angular/material/core/mdc-helpers/_mdc-helpers.scss 176:5     @content
>   node_modules/@angular/material/core/mdc-helpers/_mdc-helpers.scss 216:3     disable-mdc-fallback-declarations()
>   node_modules/@angular/material/core/mdc-helpers/_mdc-helpers.scss 175:3     using-mdc-theme()
>   node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 26:3   color()
>   node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 53:7   @content
>   node_modules/@angular/material/core/theming/_theming.scss 402:3             private-check-duplicate-theme-styles()
>   node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 47:3   theme()
>   node_modules/@angular/material/core/theming/_all-theme.scss 47:5            @content
>   node_modules/@angular/material/core/theming/_theming.scss 402:3             private-check-duplicate-theme-styles()
>   node_modules/@angular/material/core/theming/_all-theme.scss 44:3            all-component-themes()
>   src/app/scss/theme/_theme.scss 146:1    
> ```
> 
> Based on other responses above, is it possible Angular Material has a bug where it is no longer supporting CSS4 variables in its themes?

I've also just encountered this issue with Angular v15.0.0
Have you found a solution?

**Comment by Petmun** [comment] 2022-12-06 09:08
> 
I do have the same problem. Have you found a solution?

**Comment by alicelebidev** [comment] 2022-12-06 09:25
> > 
> 
> I do have the same problem. Have you found a solution?

I'm stuck with this issue at the moment. So annoying...

**Comment by bobliwang** [comment] 2022-12-10 06:52
> alter those variables at runtim

Same here. any clue will be appreciated

**Comment by bobliwang** [comment] 2022-12-10 09:15
> I am getting something similar in Angular 15.0.0 (with Angular Material 15.0.0).
> 
> My app's color theme is customizable by a configuration loaded at runtime. As such, I set the theme to be based on CSS4 variables - eg:
> 
> ```
> :root {
>   --theme-primary-50: #EEF6F5;
>   --theme-primary-100: #D4EAE7;
>   --theme-primary-200: #B8DCD7;
>   --theme-primary-300: #9CCDC7;
>   --theme-primary-400: #86C3BB;
>   --theme-primary-500: #71B8AF;
>   --theme-primary-600: #69B1A8;
>   --theme-primary-700: #5EA89F;
>   --theme-primary-800: #54A096;
>   --theme-primary-900: #429186;
>   --theme-primary-A100: #E7FFFC;
>   --theme-primary-A200: #B4FFF4;
>   --theme-primary-A400: #81FFED;
>   --theme-primary-A700: #68FFE9;
> }
> 
> $primaryPalette: (
>   50 : var(--theme-primary-50),
>   100 : var(--theme-primary-100),
>   200 : var(--theme-primary-200),
>   300 : var(--theme-primary-300),
>   400 : var(--theme-primary-400),
>   500 : var(--theme-primary-500),
>   600 : var(--theme-primary-600),
>   700 : var(--theme-primary-700),
>   800 : var(--theme-primary-800),
>   900 : var(--theme-primary-900),
>   A100 : var(--theme-primary-A100),
>   A200 : var(--theme-primary-A200),
>   A400 : var(--theme-primary-A400),
>   A700 : var(--theme-primary-A700),
>   contrast: (
>     50: var(--color__text),
>     100: var(--color__text),
>     200: var(--color__text),
>     300: var(--color__text),
>     400: var(--color__text),
>     500: var(--color__text--light),
>     600: var(--color__text--light),
>     700: var(--color__text--light),
>     800: var(--color__text--light),
>     900: var(--color__text--light),
>     A100: var(--color__text),
>     A200: var(--color__text--light),
>     A400: var(--color__text--light),
>     A700: var(--color__text--light),
>   )
> );
> 
> ...
> 
> // Define the primary, accent and warn palettes
> $default-primary-palette: mat.define-palette($primaryPalette);
> $default-accent-palette: mat.define-palette($accentPalette);
> $default-warn-palette: mat.define-palette($warnPalette);
> 
> // Create the Material theme object
> $theme: mat.define-light-theme($default-primary-palette, $default-accent-palette, $default-warn-palette);
> 
> @include mat.all-component-themes($theme);
> 
> // Apply the theme to the user components
> @include components-theme($theme);
> ```
> 
> I then alter those variables at runtime. This used to work just fine, but now, Angular Material complains (at compile time) with this:
> 
> ```
> HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
> SassError: $color: var(--theme-primary-500) is not a color.
>    ╷
> 16 │     track-color: color.adjust(mdc-theme-color.prop-value($color), $alpha: -0.75),
>    │                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>    ╵
>   node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 16:18  -palette-styles()
>   node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 28:7   @content
>   node_modules/@angular/material/core/mdc-helpers/_mdc-helpers.scss 176:5     @content
>   node_modules/@angular/material/core/mdc-helpers/_mdc-helpers.scss 216:3     disable-mdc-fallback-declarations()
>   node_modules/@angular/material/core/mdc-helpers/_mdc-helpers.scss 175:3     using-mdc-theme()
>   node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 26:3   color()
>   node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 53:7   @content
>   node_modules/@angular/material/core/theming/_theming.scss 402:3             private-check-duplicate-theme-styles()
>   node_modules/@angular/material/progress-bar/_progress-bar-theme.scss 47:3   theme()
>   node_modules/@angular/material/core/theming/_all-theme.scss 47:5            @content
>   node_modules/@angular/material/core/theming/_theming.scss 402:3             private-check-duplicate-theme-styles()
>   node_modules/@angular/material/core/theming/_all-theme.scss 44:3            all-component-themes()
>   src/app/scss/theme/_theme.scss 146:1    
> ```
> 
> Based on other responses above, is it possible Angular Material has a bug where it is no longer supporting CSS4 variables in its themes?

Hi mate,

The work round for Angular 15 is to replace line 16 with line 17 in _progress-bar-theme.scss from angular material source code.
Seems this file was modified by angular team for mdc, and it calls color.adjust function in .scss which requires a 'REAL' color instead of one relying on a css variable.
WARNING: it may affect a little style in progress bar. (but who cares :P )
![Screenshot 2022-12-10 at 8 09 05 pm](https://user-images.githubusercontent.com/861006/206842636-5369d953-1ef8-4528-8a03-18e1fe667be7.png)

Cheers

**Comment by bobliwang** [comment] 2022-12-10 09:18
> > alter those variables at runtim
> 
> Same here. any clue will be appreciated

work round as post below

**Comment by bobliwang** [comment] 2022-12-10 12:37
not that bad if we change it to: ``` track-color: var(--theme-primary-300)```

**Comment by b9chris** [comment] 2023-08-08 20:17
I had this problem also, even after getting Visual Studio to compile the file. The issue comes down to the rgba() function sometimes being a SASS extension, not a CSS built-in - which was fine until CSS variables were introduced:

https://stackoverflow.com/a/76862918/176877
