### ISSUE TITLE
How to Customize Bootstrap 4 Sass with npm

### ISSUE THREAD

**Issue by hosamalzagh** [twbs/bootstrap#27692] opened 2018-11-20 03:31 UTC
1
down vote
favorite
1
I Used laravel 5.7 , NPM To Install Bootstrap 4 And This Is Easy , Now I Want Make a Site In Multi Language rtl And ltr So I Change On File node_modules/bootstrap/scss/_reboot.scss

I made 3 variables: $direction: rtl; $left:left; And $right:right;

@if($direction == rtl)
   {
    $left : right;
    $right : left;
   }

  If I Want To Change LTR To RTL I Use This If

@if($direction === rtl){
    @include border-left-radius($border-radius);
}@else{
    @include border-right-radius($border-radius);
  }
My Method Effective works successfully 100% I Just Fine Best way To Do This Work .

Question Is the modification to the source files correct or wrong? If a mistake is t
he correct suggestion and save the adjustments to be used with the prefixes file example

node_modules / bootstrap / scss / _variables.scss We can modify it by requesting it in a new file resources / sass / _variables.scss

But the difference in the other files (node_modules / bootstrap / scss) are not variables
https://stackoverflow.com/questions/53123544/how-to-customize-bootstrap-4-sass-with-npm-in-laravel

**Comment by MartijnCuppens** [comment] 2018-11-20 08:01
I guess what you 're asking for is RTL support, which is a duplicate of #24807

**Closed by MartijnCuppens** 2018-11-20 08:01 UTC
