### ISSUE TITLE
On Bootstrap 5.3 web, "multiple" select example does not work.

### ISSUE THREAD

**Issue by StraffWentworth** [twbs/bootstrap#39162] opened 2023-09-08 20:57 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

On page:
https://getbootstrap.com/docs/5.3/forms/select/

The example for "multiple" which is a  multiselect does not work.
It should: provide checkboxes for selection and allow for multiple items
to be selected. It does neither. 

### Reduced test cases

N/A

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

5.3

**Comment by coliff** [comment] 2023-09-09 02:17
It's working as intended. You need to press SHIFT and click on each item to select.

See MDN docs for details: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/multiple

(I realise it's not intuitive though, if I was using a select with multiple attribute on a site I would explain how a user can select more than one - see accessibility concerns here: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/multiple#accessibility_concerns)

**Comment by julien-deramond** [comment] 2023-09-11 05:43
Closing this issue based on @coliff's answer

**Closed by julien-deramond** 2023-09-11 05:43 UTC
