### ISSUE TITLE
Feature Request: Badge/Pill Outline

### ISSUE THREAD

**Issue by danielrhodes** [twbs/bootstrap#27110] opened 2018-08-20 20:35 UTC
I recently became in need of having a badge or a pill with an outline over a solid background. Such a need is consistent with what already exists for [outlined Buttons](https://getbootstrap.com/docs/4.1/components/buttons/#outline-buttons).

I found a Codepen showing [somebody has already done this](https://codepen.io/uimax/pen/NRWVmo), but I think it should be part of Bootstrap itself.

<img width="264" alt="screen shot 2018-08-20 at 1 33 38 pm" src="https://user-images.githubusercontent.com/120044/44365111-aae80600-a47d-11e8-9dba-76e3fe6a5e55.png">

**Comment by tasoskakour** [comment] 2018-08-23 14:16
There is already an open PR waiting to be reviewed https://github.com/twbs/bootstrap/pull/23886

**Comment by alecpl** [comment] 2018-11-17 14:17
A duplicate of  #23882.

**Closed** 2018-12-15 19:16 UTC
Labels: css, feature, has-pr, v4
