### ISSUE TITLE
bower.json not including css file in main

### ISSUE THREAD

**Issue by ezraroi** [twbs/bootstrap#16663] opened 2015-06-17 14:39 UTC
Tools like Wiredep stopped working with bootstrap after the change in last version.

**Comment by Johann-S** [comment] 2015-06-17 14:49
It's due to this Pull request : https://github.com/twbs/bootstrap/pull/16359

But you have to check the new bower specs https://github.com/bower/bower.json-spec/pull/43

**Comment by ezraroi** [comment] 2015-06-17 15:23
yes I saw this.
But looks like the bootstrap bower.json file should provide a solution for the css file.
I don;t see a reason why not to include it

**Comment by kkirsche** [comment] 2015-06-17 15:29
I'm not sure I fully understand, so if I am wrong I apologize. But I think we should not do anything that is not directly from / for the spec. Anything else is up to the author because they chose to depend on third party libraries. We should not, in my opinion, be held responsible for fixing third-party functionality due to a different third party changing their spec. Our only goal is to follow the spec provided by the third party. I would recommend creating an issue with wiredep to adjust their behavior to use the new spec

**Comment by mdo** [comment] 2015-06-17 16:19
Should we say fuck the spec and do this? I didn't think about it much when I saw the PR—spec is spec—but this actually might fuck up a lot of folks. Thoughts @cvrebert?

**Comment by mlakmal** [comment] 2015-06-17 16:31
since .css reference is removed from main, wiredep is not able to identify if bootstrap has any css files to be injected into automated bower:css section ... this will break angular apps for lot of folks using bootstrap with yeoman scaffolding since yeoman uses this setup by default ...

i reverted the bootstrap version 3.3.1 for our project to build successfully until i identify a solution for this ...

**Comment by redysanin** [comment] 2015-06-17 17:16
Even we also face same issue. at grunt serve it remove    
<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css" />
It look like they remove  "dist/css/bootstrap.css" from bower_components\bootstrap\bower.json

We fix this issue temporary by  overrides our project bower.json. for us it work fine. but waiting for some solution from  bootstrap.

 "overrides":{
    "bootstrap" : {
         "main": [
            "less/bootstrap.less",
            "dist/css/bootstrap.css",
            "dist/js/bootstrap.js"
          ]
    }
  }

**Comment by mlakmal** [comment] 2015-06-17 17:25
I was trying out that override, that seems to do the trick. as long as we can override, this shouldn't be a issue on bootstrap side ...

**Comment by kkirsche** [comment] 2015-06-17 17:34
My personal preference is to follow the spec rather than to modify the bower file Bootstrap provides. My belief is that that as new bower projects are made and as other projects migrate to the latest spec this issue will crop up there as well. Us patching it while potentially solving this issue for users of Bootstrap, doesn't prevent the same issue with other repos thus making me believe the issue should be addressed by the package(s) which use this data, not by the package maintainers.

(Note: @redysanin use a backtick (`) for inline code, three backticks with a language name or 4 space indentation to begin it be a code block)

**Comment by ezraroi** [comment] 2015-06-17 17:41
I opened an issue on the bootstrap project. From the spec, where css files should be included?

**Comment by ezraroi** [comment] 2015-06-17 17:44
From what I understand from the spec, it is one file per type, so I can have one js file and one css file?

**Comment by ezraroi** [comment] 2015-06-17 19:10
Issue from the bower project:
https://github.com/bower/bower.json-spec/pull/43#issuecomment-112910472

**Comment by karthilxg** [comment] 2015-06-17 19:29
Reverting to bootstrap version 3.3.2 also works fine..

**Comment by ezraroi** [comment] 2015-06-17 19:40
Yes, but we want to be able to use the last versions.

**Comment by karthilxg** [comment] 2015-06-17 19:43
@ezraroi Try overriding option suggested by @redysanin as a temp fix.

```javascript
   "overrides":{
      "bootstrap":{
         "main":[
            "less/bootstrap.less",
            "dist/css/bootstrap.css",
            "dist/js/bootstrap.js"
         ]
      }
   }
```

**Comment by cvrebert** [comment] 2015-06-17 23:58
> From what I understand from the spec, it is one file per type, so I can have one js file and one css file?

@ezraroi The issue isn't JavaScript and CSS. The issue is CSS and Less/Sass. Per the spec:
> Use source files with module exports and imports over pre-built distribution files.

In other words, in the case of stylesheets specifically: `main` should include the Less/Sass source code, NOT the prebuilt CSS. I specifically sought clarity about this in https://github.com/bower/bower.json-spec/pull/43 , and the example in the spec backs this up by including `sass/motion.scss` and NOT `movement.css` in its `main`.

**Comment by cvrebert** [comment] 2015-06-18 09:34
@mdo Please god no. After [*over a year and a half* of discussion upstream](https://github.com/bower/bower/issues/935), and months of prodding the Bower devs into taking action, we *finally* have a proper spec; let's stick to it now that it exists. The very concept of specs is pointless otherwise. Down the path of deliberately disobeying the written spec in favor of ad-hoc shit folks just make up lies chaos and sadness.
Several other major projects have agreed to go along with the `main` spec change (https://github.com/zurb/foundation/pull/6525, https://github.com/zurb/foundation-apps/pull/607, https://github.com/Semantic-Org/Semantic-UI/pull/2244, https://github.com/videojs/video.js/pull/2145, https://github.com/select2/select2/pull/3350), and the tooling projects were consulted in https://github.com/bower/bower.json-spec/pull/43 and didn't raise an objection.
So it's reasonable to expect the tools to change, and there is/will-be pressure on the tools to change since we have major projects onboard, it will just take some time. There will be some pain during the transition period; I personally believe this is worth enduring in order to help bring sanity to Bower long-term.

Is the situation perfect? Of course not. Ideally, Bower ought to offer sufficient metadata to allow its users to use precompiled CSS (or JS for that matter) when packages like Bootstrap offer it. Or else it should explicitly narrow its scope to "Bower assumes that its users will use build tools (including Less/Sass/Stylus/PostCSS/etc. compilers)". But that's squarely a problem for *Bower's* developers and community to work out; I don't think it's Bootstrap's job to try to tackle that ourselves, other than to comply with future updates to the `bower.json` spec. We have quite enough work on our plate as it is.
It's high time for wiredep et al. and the Bower project to sit down and hash out how fonts, images, and precompiled CSS ought to work in `bower.json` now that they're definitively excluded from `main`. [The Bower devs acknowledged the likely need for such additional fields when discussing the new `main` spec.](https://github.com/bower/bower.json-spec/pull/43#issuecomment-91538230)

To folks interested in improving the situation, **I suggest lobbying/discussing/pull-requesting [the Bower project](https://github.com/bower/bower/issues) for something like https://github.com/bower/bower.json-spec/issues/21** (as a starting point).

(P.S. I apologize for the vitriol, but Bower's shittiness and lack of progress in addressing its shortcomings on a reasonable timescale has caused me much angst.)

**Comment by Alber70g** [comment] 2015-06-18 13:46
I'd like to add that here is mentioned that you can also add the css. But that's before the spec changed.: https://github.com/bower/bower.json-spec/issues/36#issuecomment-54574684

**Comment by mdo** [comment] 2015-06-18 16:08
It sucks that the Bower spec is just now getting some definition, but until the dust settles, I'm good keeping us within what little definition we have thus far. We'll stick with the spec and **not** add the compiled CSS dist files, nor font files.

Sorry if this fucks up your day as a Bootstrap user, but I suggest taking any feedback to the Bower folks so they can appropriately act on it for the entire Bower community.

**Closed by mdo** 2015-06-18 16:08 UTC
Labels: meta

**Comment by danielstankiewicz** [comment] 2015-06-19 13:35
I agree that we should be able to use it as a *library*, not as source. My app just got broken because of 3.4.5 version. Falling back to 3.4.4.

**Comment by kkirsche** [comment] 2015-06-19 13:46
The change itself is a package manager change and subject to their choices not bootstrap. Use and dependence on any package manager comes with risks. The core library has not had any breaking changes in the last release, my recommendation would be to raise your concern with bower as we are simply following their spec.

**Comment by s12chung** [comment] 2015-06-19 19:35
any complaints about the spec should go up to bower---standards of the web are incongruent enough already.

at the same time, could you upgrade the version to a major upgrade? following http://semver.org.

and maybe make an upgrade note. (i still haven't figured out how to upgrade yet)

**Comment by conslo** [comment] 2015-06-19 21:35
I understand deciding to conform to the spec right away, but this should still be considered a breaking change, this shouldn't have been a point release, but `4.0` instead.

**Comment by kkirsche** [comment] 2015-06-19 22:02
I would disagree. Semantic versioning says major is API change. We did not change our API. Bower changed theirs in my opinion

**Comment by conslo** [comment] 2015-06-19 22:40
you (bootstrap) previously made certain information available that people (whether you said they could or not) began to depend on. Said depended on data is no longer available, and things broke, lots of things broke. It's nice to say "not my fault not part of our definition!", but this is reality we live in, and in this reality when people allow minor version upgrades they expect things to keep working.

Gods forbid you actually care if you break things that use your stuff. This is why many companies do downstream testing before releasing internal packages: what's the point of a guaranteeing no breaking changes if you break things?

**Comment by conslo** [comment] 2015-06-19 22:43
you are technically correct in that semver only speaks to the api. One *could* attempt to argue that data in a metadata file is a form of an api, but I won't. Instead I'll say that a major version increase would have prevented a lot of things from breaking.

**Comment by kkirsche** [comment] 2015-06-19 22:49
I am not a core member of Bootstrap and do not speak for anyone other than myself to ensure there are no miscommunications on that point.

**Comment by conslo** [comment] 2015-06-19 22:53
@kkirsche apologies, I was in fact operating under that assumption. My opinion stands though.

**Comment by kkirsche** [comment] 2015-06-19 22:57
That's fair, and I can understand it, though I don't agree with it. I appreciate the input, and believe conversations like this are the only way to ensure the community as a whole is the best it can be and serves the most people. Simply on this subject I happen to disagree with many others — simply put, I look at this at this point as an agree to disagree situation. I wanted to ensure though that it was and is clear that at this time I speak only for myself and if I was representing the project as a team member I probably would not be vocal on this subject as I wouldn't feel I have the authority to address them as I feel the owners of the project would need to make the final call, not a general member or contributor due to the controversial nature of this change. 

Hope that makes sense

**Comment by cvrebert** [comment] 2015-06-19 23:41
@s12chung You make a good point; I'll see about adding the `bower.json` change to the 3.3.5 blog post summary and try to add some upgrade guidance for those unfortunate wiredep users.

**Comment by s12chung** [comment] 2015-06-20 00:03
thanks @cvrebert! it would be very helpful :)

**Comment by Alber70g** [comment] 2015-06-22 11:35
Yea... fuck the developers, the hundreds of thousands of developers who are dependent on generators, package managers, and other third-party tools: 

#we have a spec... so we will screw the people who actually need it

**Comment by desandro** [comment] 2015-06-22 13:29
I've proposed a new `bower.json` field `files` to help address this issue: bower/bower.json-spec#47. Would love to get Bootstrap team's input on what would work best for the BS projects.

**Comment by cvrebert** [comment] 2015-06-22 16:00
@desandro Thanks! Gave my 2¢.
CC: @twbs/team: https://github.com/bower/bower.json-spec/issues/47

**Comment by cvrebert** [comment] 2015-06-22 20:47
@s12chung Added more info & a workaround to the v3.3.5 release blog post:
* http://blog.getbootstrap.com/2015/06/15/bootstrap-3-3-5-released/#wiredep-and-bower
* https://github.com/twbs/bootstrap-blog/compare/a77062f6f8764b7fc0a2c13a2b048a7694c8339a...67e083446b49e31f58dead4db84df066f26f97ec
* https://twitter.com/getbootstrap/status/613081926157504512

**Comment by s12chung** [comment] 2015-06-23 01:11
thanks for the note :)

**Comment by calidion** [comment] 2015-06-30 14:44
confirm.
please release this fix asap, this problem is very urgent for those updated.

**Comment by cvrebert** [comment] 2015-06-30 19:07
@calidion See https://github.com/twbs/bootstrap/issues/16663#issuecomment-113204018
