### ISSUE TITLE
Tooltip positioning broken for elements outside body width.

### ISSUE THREAD

**Issue by DanielApt** [twbs/bootstrap#16904] opened 2015-07-29 16:23 UTC
Any element which is positioned horizontally outside the `body` will have a mis-aligned tooltip.

![screen shot 2015-07-29 at 17 11 48](https://cloud.githubusercontent.com/assets/52545/8963138/6f930a60-3616-11e5-8000-12f5e9f726ae.png)

This is because the [tooltip](https://github.com/twbs/bootstrap/blob/master/js/tooltip.js) does not take the body's `scrollLeft` in to account.

For a live example please visit http://jsfiddle.net/DanielApt/x21kxmut/

This is related to #16825

**Comment by cvrebert** [comment] 2015-07-29 20:35
@DanielApt How is this not just a duplicate of #16825?

**Comment by DanielApt** [comment] 2015-07-30 00:47
Because the previous issue was more of a “help me” kind of post, and this is an isolated example of the issue.

**Comment by kkirsche** [comment] 2015-07-30 00:58
Not sure I understand how that isn't a duplicate...

**Comment by DanielApt** [comment] 2015-07-30 01:02
That's fine. My concern is improving the library, not the criteria for
opening / closing an issue. I'm happy to continue discussion on the
original issue.

On Thursday, 30 July 2015, Kevin Kirsche <notifications@github.com> wrote:

> Not sure I understand how that isn't a duplicate...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/16904#issuecomment-126144323>.
>


-- 
This e-mail and any attachments to it are confidential and may also be
legally privileged. If you are not the addressee or have otherwise received
it in error, you are on notice of its status. Please telephone or email the
sender and delete this e-mail. If you are not the addressee, please do not
copy this e-mail or attachments or use it for any purposes, or disclose the
contents to any other person.

For further information about Knowsis Limited, please see our website at
http://www.knows.is

**Comment by lsfcode** [comment] 2015-07-30 02:01
Why always email me?

**Comment by cvrebert** [comment] 2015-07-30 03:16
Closing as duplicate then. Isolated examples definitely help us with debugging though.

**Closed by cvrebert** 2015-07-30 03:16 UTC
Labels: awaiting reply, js
