### ISSUE TITLE
Tooltip is not working in bootstrap 5 beta1 with an svg?

### ISSUE THREAD

**Issue by saptam-dev** [twbs/bootstrap#32952] opened 2021-02-01 11:57 UTC
Currently I'm using [Bootstrap 5 beta1](https://getbootstrap.com/docs/5.0/getting-started/introduction/).

But I face a problem. When I use [tooltip](https://getbootstrap.com/docs/5.0/components/tooltips/) with button it working good. But If I use tooltip with an icon (svg, [feather icon](https://github.com/feathericons/feather)), it's not working.
On another things. If I use tooltip with svg it working 1st time. Please check.

**[Click here to see my JSFiddle](https://jsfiddle.net/saptamdev/p9jbcwno/3/)**

I also checked bootstrap 5 beta1 tooltip example. But I face same problem here.
Check here it's not working. [See svg with tooltip section.](https://getbootstrap.com/docs/5.0/components/tooltips/#examples)
Please anyone give me a solution. 
Thanks in advance.

**Comment by harshpandey002** [comment] 2021-02-01 14:18
I'm new to open source and I wanna fix this issue. Can you please guide me what procedure do I need to follow before forking the code and start working ?

**Comment by XhmikosR** [comment] 2021-02-02 18:32
Duplicate of #31646

**Closed by XhmikosR** 2021-02-02 18:32 UTC
