### ISSUE TITLE
Disabled custom checkboxes and radio buttons cursor looks clickable

### ISSUE THREAD

**Issue by TheSharpieOne** [twbs/bootstrap#21781] opened 2017-01-19 15:19 UTC
- Operating system and version: Mac OS X 10.11
- Browser and version: Chrome 55, Firefox 50, Safari 10

Go to https://v4-alpha.getbootstrap.com/components/forms/#disabled hover over the disabled checkbox. Notice the cursor.

![disabled-custom-checkbox-radio](https://cloud.githubusercontent.com/assets/664714/22112252/3b5bfc0c-de30-11e6-99cd-6e3aaf82d380.gif)

History: #17918

**Comment by RusinovAnton** [comment] 2017-01-19 15:23
FYI Pointer is not changing because of `pointer-events: none` property

**Comment by TheSharpieOne** [comment] 2017-01-19 15:40
Yes, but would the solution be to remove it from `.custom-control-indicator` (not sure why it was added there) or to override it in `.custom-control-input:disabled~.custom-control-indicator` (such as setting it to `inherit`  or back to `auto`?

**Comment by RusinovAnton** [comment] 2017-01-19 15:46
@TheSharpieOne seems like `pointer-events: none` makes no sense because it is still impossible to check disabled checkbox by clicking on `.custom-control-indicator` without it.

**Comment by TheSharpieOne** [comment] 2017-01-19 15:56
Fixing this causes the visual issue describe on https://github.com/twbs/bootstrap/issues/17918#issuecomment-148997105

> It is a shame the `cursor:not-allowed;` is applied separately to the element and the label, and not the entire hitbox (e.g. there is a gap between the element and label where the normal cursor is shown). This is again a consequence of not being able to style the parent control (the form-group div) based on the child's state. (Without non-trivial changes to the html.)

Which really begs the question, why is this different than other checkboxes and radios when it is disabled. The regular checkboxes and radios have `.disable` on a parent element and that is fine, but here it is considered as "non-trivial changes to the html"

**Comment by RusinovAnton** [comment] 2017-01-19 16:35
@TheSharpieOne but look, when I want to control disabled attribute for my checkbox with Javascript I'd rather add it for input itself than adding `.disable` on a parent element.

**Comment by TheSharpieOne** [comment] 2017-01-19 16:40
@RusinovAnton Same, but that is not how the [standard controls work](https://v4-alpha.getbootstrap.com/components/forms/#default-stacked). Consistency is king.

**Comment by CyrilWork** [comment] 2017-01-19 18:03
noob question: Is there a selector to select parent node ?

like `input[disabled] < label`

**Comment by TheSharpieOne** [comment] 2017-01-19 18:13
That question would probably be best for stackoverflow.... but...
CSS4 has `$` (not sure what the actual feature is called) which allows you to apply the styles to parent elements. such as `$label > input[disabled]` would apply the styles to a `label` which has a direct child of `input[disabled]`

**Comment by RusinovAnton** [comment] 2017-01-24 07:56
@mdo how that #21812 fixes this issue? I've just tested and the problem is still present.

**Comment by patrickhlauke** [comment] 2017-01-24 09:10
Reopening because although the mouse cursor now doesn't change to the hand / `cursor:pointer`, it's still true that the `cursor: not-allowed` isn't shown when on the control itself

**Comment by mdo** [comment] 2017-01-24 17:39
Doh, you're right. Thanks for commenting @RusinovAnton and reopening @patrickhlauke.

**Comment by mdo** [comment] 2017-03-20 04:06
This is caused by the `pointer-events: none` added in #18935. Unsure how best to proceed if we have that; there's no option of setting a `cursor` unless we remove it.

**Comment by chiraggmodi** [comment] 2017-06-15 06:45
what if we add `pointer-events:auto` to class `.custom-control-input:disabled ~ .custom-control-indicator`

**Comment by mdo** [comment] 2017-07-02 05:26
This looks fine in Safari 10 now. Closing out.

**Closed by mdo** 2017-07-02 05:26 UTC
Labels: css, v4
