### ISSUE TITLE
css-prefix task fails

### ISSUE THREAD

**Issue by FlorianLudwig** [twbs/bootstrap#23241] opened 2017-08-07 19:59 UTC
* System: Fedora 25, NodeJS 6.11.1

> bootstrap@4.0.0-alpha.6 css-prefix /src/upstream/bootstrap
> postcss --config build/ --replace dist/css/*.css

```
✖ Processing dist/css/bootstrap.min.css
{ Error: EISDIR: illegal operation on a directory, read
    at Error (native) errno: -21, code: 'EISDIR', syscall: 'read' }
```

fixed it for me:

```diff
diff --git a/package.json b/package.json
index 72a6e21..c952304 100644
--- a/package.json
+++ b/package.json
@@ -24,8 +24,8 @@
     "css-lint-docs": "bundle exec scss-lint --config .scss-lint.yml --exclude assets/scss/docs.scss assets/scss/*.scss",
     "css-compile": "node-sass --output-style expanded --source-map true --precision 6 scss/bootstrap.scss dist/css/bootstrap.css && node-sass --output-style expanded --source-map true --precision 6 scss/bootstrap-grid.scss dist/css/bootstrap-grid.css && node-sass --output-style expanded --source-map true --precision 6 scss/bootstrap-reboot.scss dist/css/bootstrap-reboot.css",
     "css-compile-docs": "node-sass --output-style expanded --source-map true --precision 6 assets/scss/docs.scss assets/css/docs.min.css",
-    "css-prefix": "postcss --config build/ --replace dist/css/*.css",
-    "css-prefix-docs": "postcss --config build/ --no-map --replace assets/css/docs.min.css",
+    "css-prefix": "postcss --config build/postcss.config.js --replace dist/css/*.css",
+    "css-prefix-docs": "postcss --config build/postcss.config.js --no-map --replace assets/css/docs.min.css",
     "css-minify": "cleancss --level 1 --source-map --output dist/css/bootstrap.min.css dist/css/bootstrap.css && cleancss --level 1 --source-map --output dist/css/bootstrap-grid.min.css dist/css/bootstrap-grid.css && cleancss --level 1 --source-map --output dist/css/bootstrap-reboot.min.css dist/css/bootstrap-reboot.css",
     "css-minify-docs": "cleancss --level 1 --source-map --output assets/css/docs.min.css assets/css/docs.min.css",
     "js": "npm-run-all js-lint js-compile js-minify",

```

**Comment by bardiharborow** [comment] 2017-08-08 00:08
Duplicate of #23188.

**Closed by bardiharborow** 2017-08-08 00:08 UTC
Labels: build, v4
