### ISSUE TITLE
Please update repository assets 

### ISSUE THREAD

**Issue by lucasjuna** [twbs/bootstrap#37510] opened 2022-11-17 12:17 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

This [changes](https://github.com/twbs/bootstrap/pull/37425/files) not found in this 
archive https://github.com/twbs/bootstrap/archive/refs/tags/v5.2.2.zip

### Reduced test cases

no need

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.2

**Comment by julien-deramond** [comment] 2022-11-17 12:44
Closing it. Duplicate of https://github.com/twbs/bootstrap/issues/37424 already fixed.
More info in https://github.com/twbs/bootstrap/discussions/37467

**Closed by julien-deramond** 2022-11-17 12:44 UTC
