### ISSUE TITLE
Validation error for inline radios

### ISSUE THREAD

**Issue by vpratfr** [twbs/bootstrap#26407] opened 2018-04-27 15:45 UTC
I have a group of radio buttons displayed inline.

Problem is that the error message shows up right after the last option.

It should instead display below the inlined radios.

Below is the snippet to reproduce :

```html
<div class="form-group">
    <div class="radio-group" id="inline_radio_field_radio_group" aria-describedby="inline_radio_field_helptext">
        <div class="custom-control-inline custom-control custom-radio">
            <input class="custom-control-input is-invalid" type="radio" name="inline_radio_field"
                   id="inline_radio_field_choice_1" value="choice_1">
            <label class="custom-control-label" for="inline_radio_field_choice_1">Choice 1</label>
        </div>
        <div class="custom-control-inline custom-control custom-radio">
            <input class="custom-control-input is-invalid" type="radio" checked="checked" name="inline_radio_field"
                   id="inline_radio_field_choice_2" value="choice_2">
            <label class="custom-control-label" for="inline_radio_field_choice_2">Choice 2</label>
        </div>
        <div class="custom-control-inline custom-control custom-radio">
            <div class="invalid-feedback">This is an error below the inline radio group</div>
            <input class="custom-control-input is-invalid" type="radio" name="inline_radio_field"
                   id="inline_radio_field_choice_3" value="choice_3">
            <label class="custom-control-label" for="inline_radio_field_choice_3">Choice 3</label>
            <div class="invalid-feedback">This is an error below the inline radio group</div>
        </div>
    </div>
    <small class="text-muted" id="inline_radio_field_helptext">... and another radio group, shown inline this time
    </small>
</div>
```

**Comment by vpratfr** [comment] 2018-04-27 16:30
Here you go: https://jsfiddle.net/pd5w2ha8/

Thanks :)

**Comment by mdo** [comment] 2018-04-29 22:54
We could look at providing a demo for this, but essentially you need to hack flexbox into submission with a random `width: 100%` element between the last input and the feedback message.

**Comment by anumalasri** [comment] 2018-09-19 00:10
Is there any update ?

**Comment by mdo** [comment] 2018-09-19 01:31
Not to be too snarky, but if there was an update, you'd see it reflected here :).

**Comment by mdo** [comment] 2019-07-10 16:36
Duplicate of #25540.

**Closed by mdo** 2019-07-10 16:36 UTC
Labels: css, v4
