### ISSUE TITLE
support for <form> around navbar for asp.net webforms masterpage

### ISSUE THREAD

**Issue by beefydog** [twbs/bootstrap#15552] opened 2015-01-13 02:00 UTC
I discovered that the navbar does not work properly if it is contained by a form tag. Basically, in asp.net Masterpages, there is a very common need to keep the form tag in the masterpage: primarily for server side buttons, ajaxcontroltoolkit requirement for the UpdatePanel, and other items.
Basically, when the screen width is reduced to phone size, the navbar menu option drops down for a fraction of a second, then closes immediately, making selections impossible.
While a form tag can be used anywhere, having to repeat code over and over for every page defeats the purpose of a master page and slows loading time as well. ASP.Net webforms are still alive and well especially in enterprise applications.

**Comment by cvrebert** [comment] 2015-01-13 02:23
Can't you just replace `<nav class="navbar navbar-default">` with `<form class="navbar navbar-default">` in your template?

**Comment by patrickhlauke** [comment] 2015-01-13 10:26
I think the problem is that in general, the preferred pattern for an ASP.Net page is to basically have one big form that wraps around the entirety of the ``<body>`` content. Also, just changing from ``<nav`` to ``<form>`` would lose the navigation's landmark nature for AT users (unless you then also inject ``role="navigation""``)

**Comment by cvrebert** [comment] 2015-01-13 10:52
Okay, what about `<body><form style="width: 100%">...everything...</form></body>` then? (Using a class instead of inline `style` of course.)

> Also, just changing from `<nav>` to `<form>` would lose the navigation's landmark nature for AT users

Right, just seemed like a somewhat reasonable trade-off considering that this all-encompassing `<form>` is a rather unusual constraint in the first place.
Good point about `role="navigation"`.

**Comment by beefydog** [comment] 2015-01-13 16:27
The only problem with that is then the form can only surround the navigation bar (if it worked, but the nav menu still snaps back - so the form tag won't work no matter what classes you put in).

**Comment by beefydog** [comment] 2015-01-13 16:33
In asp.net, you can use multiple form blocks, but the nav bar simply will not work w/ a form tag surrounding it (as written). I'll play around w/ the raw code - I ran into something similar years ago w/form tags and HTML.

**Comment by cvrebert** [comment] 2015-01-13 20:30
Testcase: http://jsbin.com/peguza/2

**Comment by cvrebert** [comment] 2015-01-13 20:34
@beefydog Navbar collapsing/uncollapsing/selection seems to work fine in the above testcase on iPhone. Please clarify where you're seeing issues.

**Comment by mdo** [comment] 2015-01-13 20:49
Closing as it's not a feature or change we'll be implementing.

**Closed by mdo** 2015-01-13 20:49 UTC
Labels: css, feature
