### ISSUE TITLE
The color for disabled SELECT is different from INPUT TYPE=TEXT and TEXTAREA

### ISSUE THREAD

**Issue by rmacfadyen** [twbs/bootstrap#33089] opened 2021-02-15 03:49 UTC
OS: win10
Browser: chrome 88, firefox 85, opera 73, edge 88

Repo: [js fiddle](https://jsfiddle.net/w3aguken/)

Picture of the bug in action: [picture](https://imgur.com/a/JRDOdFC)

The class form-select defines color and background color different from the class form-control. They should be the same. 

In v4 a SELECT did not have a specific form-XYZ class of it's own, just form-control. In v5 a SELECT does have a specific form-select class.

**Comment by ffoodd** [comment] 2021-02-15 09:55
From your own fiddle, `background-color` is the same but not `color`, indeed: @mdo should we use `.form-select:disabled` color for other inputs, or simply drop it?

From an accessibility perspective, I'd go with two since it has better contrasts. If we go the other way, current disabled select is only 3.95:1, could easily be increased to pass 4.5:1 :)

**Comment by rmacfadyen** [comment] 2021-02-16 17:35
@ffoodd I thought you were correct but decided to double check this morning :)

The backgrounds are **not** the same color. The INPUT TYPE=TEXT and TEXTAREA have a background color of #e9ecef, opacity 1. The SELECT also has a background color of #e9ecef, but it's opacity is .7 from the agent style sheet (I only checked chrome). 

The .form-control:disabled, .form-control[readonly] rules set the opacity to 1, but not the .form-select rules.

**Comment by ffoodd** [comment] 2021-02-16 18:05
Yeah so `background-color` is the same. I didn't notice `opacity` differences but only checked in Firefox: maybe something to harmonize in our reboot, too.

**Comment by mdo** [comment] 2021-02-16 23:24
This is unique to Chrome, so attaching it into Reboot. See #33127.

**Comment by tkrotoff** [comment] 2021-02-22 11:17
The issue is also present with Bootstrap v4.
6.0: https://codepen.io/tkrotoff/pen/oNYGooP

Under Chrome 88 macOS, opacity problem:

![image](https://user-images.githubusercontent.com/643434/108700678-40f5bf00-7507-11eb-8c6c-1c1e72ec0e38.png)

Under Firefox 85, no opacity problem but the text color is wrong and misaligned:

![image](https://user-images.githubusercontent.com/643434/108700877-84e8c400-7507-11eb-9f6a-13dab65425eb.png)

Under Safari 13.1.2 there are also text color problems :

![image](https://user-images.githubusercontent.com/643434/108701041-beb9ca80-7507-11eb-8d47-5faae7e91850.png)

**Closed** 2021-03-02 14:40 UTC
Labels: confirmed, css, v4, v5
