### ISSUE TITLE
grunt watch will not work after a bower install

### ISSUE THREAD

**Issue by AlexNeises** [twbs/bootstrap#22101] opened 2017-03-02 19:22 UTC
The current bower file has `docs` added to the ignore list.  Currently, `grunt watch` requires this folder and will fail on attempting to build.

Either `docs` should not be excluded from bower, or the `grunt watch` command needs to be slightly modified.

**Comment by AlexNeises** [comment] 2017-03-02 19:39
Works without docs via `grunt watch:sass`

**Comment by mdo** [comment] 2017-04-09 04:51
Dupe of #22177.

**Comment by mdo** [comment] 2017-04-09 04:51
Going to punt on this for now—the Gruntfile likely shouldn't be in any of our package managers.

**Closed by mdo** 2017-04-09 04:51 UTC
Labels: grunt, v4
