### ISSUE TITLE
Cards break into multiple columns

### ISSUE THREAD

**Issue by vdest** [twbs/bootstrap#20718] opened 2016-09-14 07:53 UTC
Using the doc for card columns at [http://v4-alpha.getbootstrap.com/components/card/](http://v4-alpha.getbootstrap.com/components/card/), I experience cards that get split across columns, i.e. image is in column 1 and card block continues in column 2. This breaks the design of a single card. This only occurs on Mac in Chrome v53 and Firefox v48.2. Chrome v52 and Firefox v48.0 on Linux for example are rendering cards as expected.

**Comment by copynpaste** [comment] 2016-09-14 13:13
#20654 #20665

**Comment by cvrebert** [comment] 2016-09-14 15:57
Closing as a duplicate of the aforementioned issues.

**Closed by cvrebert** 2016-09-14 15:57 UTC
