### ISSUE TITLE
BUG: latest Tagify and latest Bootstrap (ie. any version > 5.0.2) has conflict in modals

### ISSUE THREAD

**Issue by gidzr** [twbs/bootstrap#37881] opened 2023-01-15 04:17 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When using Tagify https://yaireo.github.io/tagify/ in a Bootstrap Modal for BS. v5.1.3 and v5.2.3, selection of a tagify item (an event that causes $().on('add')) using a mouseclick, will cause the modal to auto scroll to top of modal.

I've tested using different versions of Bootstrap, and this bug doesn't occur in version 5.0.2, only in versions above this.

This modal scroll-to-top bug doesn't occur with select2 or other input selection, and doesn't occur when 'enter' is used for a typed selection.. it only occurs on a click selection.

### Reduced test cases

In this codepen I've set up a long modal (lots of br) 

Steps to re-create:
1. Scroll to the bottom and make a selection for tagify with mouseclick. The modal will scroll to top. 
2. Then change (un 'X') the src/href for v5.0.1 and 'X' out v5.2.3 in the <head> of the HTML section, and re-do the same test. The modal will NOT scroll to top.

https://codepen.io/gidzr/pen/OJwjMNN

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.0 vs 5.1 and 5.2.. the issues are on 5.1 and 5.2

**Comment by mdo** [comment] 2023-01-26 01:57
Closing as not an issue with Bootstrap as far as I can tell. If this can be reduced to Bootstrap itself, we can maybe look into it more. /cc @GeoSot for more ideas though just in case.

**Closed by mdo** 2023-01-26 01:57 UTC

**Comment by gidzr** [comment] 2023-02-16 03:07
Hey Mdo, I've got a response from the creator of Tagify, and confirmed it IS a Bootstrap issue.

https://github.com/yairEO/tagify/issues/1170
"I've analyzed the bug and it's Bootstrap's fault. Tagify's dropdown list is injected to the <body> element and I think Bootstrap is treating it in a weird way, since a click-outside should close the modal, but it doesn't get closed in this situation (which is easily done since you can know if a mouse click was made on top of a modal, even if the element is not within it in the DOM) and then scrolls to the top."

It does seem to be a legit Bootstrap unintended consequence bug..

Can you please re-open this issue?

**Comment by mdo** [comment] 2023-02-16 04:48
@GeoSot Thoughts on this?

**Comment by GeoSot** [comment] 2023-02-16 13:14
It got some time till I was guided to https://github.com/twbs/bootstrap/blob/cbc4e3a4098506315c32346b194e9e1a4d7db091/js/src/util/focustrap.js#L102


Seems that a focus event is triggered out of Modal, so FocusTrap, catches this and re-focus to Modal element
Unfortunately, it is a feature and not a bug :rofl: :laughing: 

and this suggestion seems to be the only and the right way to solve the issue https://github.com/yairEO/tagify/issues/1170#issuecomment-1399429774

**Comment by yairEO** [comment] 2023-02-16 15:58
Hi @GeoSot, 
great progress with pinpointing to the source of the "problem"!

Theoretically *bootstrap* could allow an "off-the-books* way to tell it when should the focus trap work and when should it be ignored, by exposing a global mechanism, for example:

```js
// now I want bootstrap to stop trapping focus:
window.bootstrap.features = {} // initialize this object property globally somewhere inside bootstrap
window.bootstrap.features.focustrap = false;

// ...developer doing some UI stuff 

// ...UI stuff are done, so revert things back as they were
window.bootstrap.features.focustrap = true;
```

I know this is very easy to make but at the same time, a huge thing to implement as this opens the door to an endless discussion about what should be allows in `features` property and how best to expose things and who knows what else :)

**Comment by gidzr** [comment] 2023-02-18 02:32
Hey @GeoSot + @mdo .. cool re explanation and approach.. and really appreciate the time to check out this issue.. though not a bug, certainly an unintended downstream effect. The jitter with Tagify/Boot-Modals makes the combo unusable from an experience perspective - but I don't want to forgo either technology. ;P  .. they're both awesome.. :)

For now I'll apply @yairEO's suggestion `appendTarget: document.querySelector('.modal-content')` and see how that works, as I'm very keen to get back to the latest Bootstrap version (after having wound back to 5.0).

Hopefully getting this on your radar might come in handy later - might affect other libraries in-modal. <wink wink nudge nudge>

**Comment by Diana-Alex-Rodrigues** [comment] 2024-03-02 00:58
Anybody still dealing with this ? When one of the tags is selected in the modal the pages scrolls to the top.
Even with all you guys suggestions, still does not work.

Bootstrap 5.3.2
