### ISSUE TITLE
V4 btn-secondary-outline style fore-/back-ground contrast too low

### ISSUE THREAD

**Issue by Sequoia** [twbs/bootstrap#20084] opened 2016-06-06 18:18 UTC
* Foreground: `#ccc`
* Background: `#fff` (on [demo page](http://v4-alpha.getbootstrap.com/components/buttons/#outline-buttons))
* [Contrast: **1.61:1** ](http://webaim.org/resources/contrastchecker/?fcolor=CCC&bcolor=FFF) ❌ (minimum is 4.5:1)

Contrast this low makes it difficult to read button text which makes websites using this style less usable & less accessible to many people.

See [Web Content Accessibility Guidelines](https://www.w3.org/WAI/WCAG20/quickref/#qr-visual-audio-contrast-contrast) for more info.

**Comment by patrickhlauke** [comment] 2016-06-06 19:23
Duplicate of #17286

**Closed by patrickhlauke** 2016-06-06 19:23 UTC
