### ISSUE TITLE
Add prefix to class and data names to prevent clashes

### ISSUE THREAD

**Issue by saturdaywalkers** [twbs/bootstrap#15614] opened 2015-01-20 10:45 UTC
Please add a prefix to class names to prevent clashes with existing class= & data= names.

e.g., when moving to bootstrap, I already had a class=warning, and a class=danger. And maybe some other clashes I haven't noticed yet.

So, could Bootstrap classes be twb-danger, twb-warning, twb-btn, 
- or even bs-danger :)

Same for data="twb-something"

I realise this would break **everything**, so it would need some thought....

Thanks for all your work, appreciated

Similar to locked #1287

**Comment by cvrebert** [comment] 2015-01-20 19:27
Duplicate of #1287 (and others). You can do something similar yourself (e.g. only apply Bootstrap styles to descendants of elements with a `bootstrap` class) using CSS postprocessors, but the request to do this in Bootstrap itself has been declined several times.

**Closed by cvrebert** 2015-01-20 19:27 UTC
Labels: css, feature
