### ISSUE TITLE
Safari and Chrome on Mac and iOS didn't apply color for disabled and readonly inputs

### ISSUE THREAD

**Issue by ihorzenich** [twbs/bootstrap#30890] opened 2020-05-25 13:43 UTC
Safari and Chrome on Mac and iOS didn't apply color for readonly and disabled inputs, they use internal `-webkit-text-fill-color` property instead of `color`, so you can't customize text color for disabled/readonly inputs.

Because we already have styles for fixing browser inconsistencies for form-colntrols like
* placeholder color in Firefox: https://github.com/twbs/bootstrap/blob/master/scss/forms/_form-control.scss#L43 
* and iOS disabled/readonly color: https://github.com/twbs/bootstrap/blob/master/scss/forms/_form-control.scss#L56 

it seems legit to add correspondent styles to fix the same issues for Chrome/Safari on MacOS/iOS.

It could be fixed by:
```
.form-control {
  ...
  &:disabled,
  &[readonly] {
    -webkit-text-fill-color: currentColor;
  }
}
```

Screenshots of issue:
<img width="1680" alt="MacOS disabled form-controls" src="https://user-images.githubusercontent.com/1684521/82818005-acdac680-9ea6-11ea-9e86-f9e30cdc5591.png">
<img width="1680" alt="MacOS readonly form-controls" src="https://user-images.githubusercontent.com/1684521/82817985-a0ef0480-9ea6-11ea-9d9d-997bcc3a8044.png">

**Comment by ffoodd** [comment] 2020-06-02 14:32
FWIW, [`-webkit-text-fill-color` works on most browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-fill-color), despite its vendor prefix.

I reproduced this on latests Chromium / Ubuntu.

**Comment by mdo** [comment] 2020-06-13 02:59
This seems to only apply to `placeholder` values. Adding or changing to `value` will pick up the custom `color`.

**Comment by mdo** [comment] 2020-09-17 04:46
Following up on this: if you do add a color to the disabled and readonly selector (in both v4 and v5), this will not affect the examples in the docs right now because those examples are using `placeholder` values. If you want their color to change, you'll need to set an explicit `value`.

Here's that problem illustrated in an example. The top two are `placeholder` values, the bottom two have `value`s that override the `placeholder`.

<img width="820" alt="Screen Shot 2020-09-16 at 9 31 15 PM" src="https://user-images.githubusercontent.com/98681/93420541-fd19d200-f863-11ea-8e84-f0c8b8d1bed8.png">

Similarly, in our v4.5 docs for disabled forms, this is what's happening for our `.form-control` and `.form-select`. The `.form-control` only has a `placeholder` attribute, while the `.form-select` has a declared value because of the options.

<img width="1028" alt="Screen Shot 2020-09-16 at 9 32 45 PM" src="https://user-images.githubusercontent.com/98681/93420723-6994d100-f864-11ea-91ba-5d7f3e238fbf.png">

Based on all that, I don't think this is a bug at all, just a mismatch of expectations and attributes. However, while investigating this, I've found that we don't have individual examples of disabled selects and inputs in our docs, so I've opened #31686.

Think this and the associated PR are safe to close?

**Comment by ihorzenich** [comment] 2020-09-22 23:59
Yes, the problem comes from a lack of styles for [disabled] **but also and ::placeholder** styles.
So, please add `::placeholder` styles in #31686 

See: https://codepen.io/ihorzenich/pen/dyGXoza

**Comment by mdo** [comment] 2021-01-13 00:51
I think we close this as a won't fix? The referenced PR mentioned here is just about _documenting_ the disabled states, not adding styles for them since those styles already exist. Unless anyone on @twbs/css-review thinks we need to style placeholders for disabled and other form states, I'm passing on this for now.

**Closed by mdo** 2021-01-13 00:51 UTC
Labels: confirmed, css, v4, v5
