### ISSUE TITLE
Selecting / Scroll issue in Documentation

### ISSUE THREAD

**Issue by Mtillmann** [twbs/bootstrap#39669] opened 2024-02-11 12:29 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi, on current(~120ish) chromium-based browser, the documentation has an issue where when you try to select example markup from a textarea that has a horizontal scrollbar, the document will scroll to the bottom. This happens to me on ubuntu and windows in chrome, brave, edge etc but not in firefox. In the attached video you can see me selecting text from textareas without the scrollbar without issue. 
[Screencast from 11.02.2024 13:23:04.webm](https://github.com/twbs/bootstrap/assets/289963/a3324ccd-1aad-4cce-992e-2d9000666df0)

### Reduced test cases

https://getbootstrap.com/docs/5.3/forms/checks-radios/

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3

**Comment by saadkhan011** [comment] 2024-02-12 07:21
Working on this issue assign me this.

**Comment by mdo** [comment] 2024-02-12 19:38
Duplicate of #39605.

**Closed by mdo** 2024-02-12 19:38 UTC
