### ISSUE TITLE
v4 - Varying modal content example missing JS

### ISSUE THREAD

**Issue by zacechola** [twbs/bootstrap#17150] opened 2015-08-20 17:50 UTC
http://v4-alpha.getbootstrap.com/components/modal/#varying-modal-content-based-on-trigger-button

Looks like application.js file is missing the relatedTarget demo code.

**Comment by bardiharborow** [comment] 2016-11-16 02:47
Duplicate of #17584. Fixed by ba50680.

**Closed** 2016-11-26 02:26 UTC
Labels: confirmed, docs, v4
