### ISSUE TITLE
Dropdown options not accounted for when showing using JS

### ISSUE THREAD

**Issue by JasonTheProgrammer** [twbs/bootstrap#30893] opened 2020-05-25 21:38 UTC
When using JavaScript to set the options for a dropdown, I'm finding that the options are only applied / accounted for when I'm **not** using JavaScript to show the dropdown.

I have a reduced test case here:
https://jsbin.com/falugunipe/edit?console,output

If you click the "Dropdown button", which is relying on the data attributes to show / hide the dropdown, the `getOffset` function configured in options is triggered, and has an effect on dropdown placement.

But if you click the "Expand" button, which uses JS `.dropdown('show')`, the dropdown does show, but the `getOffset` function is not called, and no offset is used.

I'm setting the dropdown options like `dropButton.dropdown({ offset: getOffset })`, where `dropButton` is a jQuery object referencing the "Dropdown button".

Operating System:
Windows 10

Browsers: 
Firefox 76.0.1 (64-bit)
MS Edge 83.0.478.37 (64-bit)

**Comment by JasonTheProgrammer** [comment] 2020-05-25 23:29
I've managed to determine that the issue is a combination of the jQuery interface for dropdown here:
https://github.com/twbs/bootstrap/blob/v4.4.1/js/src/dropdown.js#L375
which calls the functions without any parameters. I.e. `$('#myDropdownInput').dropdown('show')` ultimately becomes `dropdownInstance.show()`.

And the default parameter for `show()`...
https://github.com/twbs/bootstrap/blob/v4.4.1/js/src/dropdown.js#L140
is `show(usePopper = false)`

It looks like it's been this way since [this commit](https://github.com/twbs/bootstrap/commit/ef1c7aadbc61c69e03ecc7c6e13bdccd1901cbd4) by @Johann-S introduced Popper to the `show` function.

At this point, I can work around the difference in behaviour by bypassing the jQuery interface and going direct to the `show` function. But I wonder what the team thinks of `usePopper = false` being the default behaviour for the function, whereas the data- attribute method, *and* toggle function, default to using Popper. Seems inconsistent?

**Comment by Johann-S** [comment] 2020-05-28 09:57
Hi @JasonTheProgrammer 

Indeed it's something we should tackle to be consistent 👌 
Do not hesitate to submit a PR if you're willing to

**Comment by rohit2sharma95** [comment] 2020-12-02 18:43
This issue seems only with V4 :thinking: 

Demo for V5: https://jsbin.com/higaqehube/1/edit?js,console,output (Seems working)
Demo for V4: https://jsbin.com/nemapufebo/1/edit?js,console,output

Can you confirm please? :slightly_smiling_face: @JasonTheProgrammer

**Comment by JasonTheProgrammer** [comment] 2020-12-02 23:08
Thanks for the ping @rohit2sharma95. Yes, I agree with your evaluation, the not-insignificant refactoring in dropdown.js has incidentally resolved this issue. I can see that in both "show" scenarios (1 - click the element specified as the anchor, or; 2 - explicitly call the show method), the same method is executed, and do **not** bypass the use of the popper class.

**Comment by rohit2sharma95** [comment] 2020-12-02 23:19
But did you check that the issue is still with V4? 🙂

**Comment by JasonTheProgrammer** [comment] 2020-12-02 23:21
Yes, present in 4.4.1 (per my original example), and still present in 4.5.3 (per your updated demo).

**Comment by mdo** [comment] 2021-01-12 20:18
Looks like this was backported so closing out.

**Closed by mdo** 2021-01-12 20:18 UTC
Labels: js, v4
