### ISSUE TITLE
Part of Popover is outside boundaries of viewport

### ISSUE THREAD

**Issue by martinfojtik** [twbs/bootstrap#19279] opened 2016-02-20 15:02 UTC
![bootstrap-1](https://cloud.githubusercontent.com/assets/7465851/13197312/120e7efc-d7eb-11e5-970e-eeb7fb559c7e.jpg)

it should look like this:

![bootstrap-2](https://cloud.githubusercontent.com/assets/7465851/13197313/1e1287a2-d7eb-11e5-86fc-628c428f1ae5.jpg)

**Comment by hebbet** [comment] 2016-02-20 15:40
looks like your browser zoom is not at 100%.

**Comment by fojtCz** [comment] 2016-02-20 16:30
yes, it's true, but problem occurs even if zoom is 100%

**Comment by kybishop** [comment] 2016-02-21 08:45
This also occurs with tooltips. I'd wager the problem is related.

![screen shot 2016-02-21 at 2 25 18 pm](https://cloud.githubusercontent.com/assets/679465/13201780/a0921af0-d8a7-11e5-81c1-192d80f1e062.png)

**Comment by jipexu** [comment] 2016-03-06 17:01
Hi
Sorry but i have also this tooltip problem? is it fixed or not or is there a way to avoid this ?
Thanks

**Comment by omnibrain** [comment] 2016-12-22 16:29
Any chance this fix will be in alpha 6?

**Comment by Joyrex** [comment] 2017-01-11 19:22
Still an issue in α6 - did this get introduced with the switch to Tether? v3 did not have this issue...

**Comment by jipexu** [comment] 2017-01-11 21:37
yes same behavior even in alpha doc ...

**Comment by Joyrex** [comment] 2017-01-11 22:47
Wasn't the auto value v3 had (that is dropped in v4) is what prevented tooltips and popovers from leaving the viewport?

**Comment by alecpl** [comment] 2017-03-10 14:47
Can be fixed with `constraints: [{to: 'window', attachment: 'together', pin: true}]`, but the arrow is in wrong position. Please, do something with popover, this widget is really important but so broken in v4.

**Comment by mscu** [comment] 2017-04-25 17:00
same issue here, please fix :)

**Comment by Johann-S** [comment] 2017-05-14 09:47
Closed by #22444

**Closed by Johann-S** 2017-05-14 09:47 UTC
Labels: css, has-pr, js, v4
