### ISSUE TITLE
Modal Dialog

### ISSUE THREAD

**Issue by hn1** [twbs/bootstrap#15579] opened 2015-01-16 01:14 UTC
If Modal dialog is taller than browser view port, when you scroll, the backdrop is cut-off. The backdrop only corrects itself if you re-size browser

**Comment by cvrebert** [comment] 2015-01-16 01:23
Duplicate of #15483. **Please search next time.**

**Closed by cvrebert** 2015-01-16 01:23 UTC
Labels: js

**Comment by cvrebert** [comment] 2015-01-16 01:28
Duplicate of your own #15574 also.
