### ISSUE TITLE
Textareas does not works well for floating labels.

### ISSUE THREAD

**Issue by binulad** [twbs/bootstrap#34234] opened 2021-06-11 13:30 UTC
When added large content in textarea, it's overlapping the textarea label.
![image](https://user-images.githubusercontent.com/43953443/121693518-da60d500-cae6-11eb-9e63-86da7fc62ae8.png)

**Comment by mdo** [comment] 2021-06-11 17:05
Duplicate of #32800.

**Closed by mdo** 2021-06-11 17:05 UTC
