### ISSUE TITLE
Collapse on A with a href="#" and data-target="#mydiv"

### ISSUE THREAD

**Issue by AaronLayton** [twbs/bootstrap#20018] opened 2016-06-02 10:35 UTC
I am getting an issue where if I specify a `data-target` on my `a` tag, the script works correctly but then still works tries to use the href as a secondary target.

Is this intended behavior or should the data-target take priority in this instance?

HTML I am using is

``` html
<a href="#" class="collapsed" data-toggle="collapse" data-target="#billingAddress" aria-expanded="false">
    My Delivery address is the same as my Billing address
</a>
```

**Comment by cvrebert** [comment] 2016-06-02 16:30
What version of Bootstrap are you using?

**Comment by AaronLayton** [comment] 2016-06-02 20:05
It is version "bootstrap": "~3.3.5"

**Comment by AaronLayton** [comment] 2016-06-02 20:05
I have since fixed my issue by removing the data-targets on my a tags but would still be useful to know

**Comment by AaronLayton** [comment] 2016-06-02 20:15
I narrowed it down before though to this selector in the `hide` method

```
// ...
this.$trigger.addClass("collapsed").attr("aria-expanded", !1),

// selector is
"[data-toggle="collapse"][href="#"],[data-toggle="collapse"][data-target="#billingAddress"]"
```

I am doing some funky stuff but would that selector need to just be 
`[data-toggle="collapse"][data-target="#billingAddress"]` if data-target is set

**Comment by wfinder** [comment] 2016-06-14 20:42
I have a use case where I want the data-target attribute to indicate what element to collapse, then I would like the href still behave as a jump link.  So in this case I would say this is not a bug and very much a feature.

**Comment by mdo** [comment] 2016-10-28 23:57
Did we fix this with our recent collapse changes, @Johann-S @bardiharborow?

**Comment by Johann-S** [comment] 2016-10-29 06:59
I have to make some tests in V4 @mdo,  but this issue is for V3 not V4

**Comment by mdo** [comment] 2016-11-28 00:45
Closing per last comment <3.

**Closed by mdo** 2016-11-28 00:45 UTC
Labels: awaiting reply, js, v3
