### ISSUE TITLE
Website Jumping older doc version version after search

### ISSUE THREAD

**Issue by anonymuos1** [twbs/bootstrap#26577] opened 2018-05-24 08:15 UTC
Hi!

On the website (getbootstrap.com), after i used search on the left side in 4.1 documentation, it jump to the 4.0 doc version.

**Comment by wolfy1339** [comment] 2018-05-24 12:28
Please search more. This is a known issue

**Comment by mdo** [comment] 2018-05-24 15:16
Duplicate of #26441.

**Closed by mdo** 2018-05-24 15:16 UTC
