### ISSUE TITLE
Bootstrap 5 modal .fade does not finish hide animation if element within it is focused

### ISSUE THREAD

**Issue by suneettipirneni** [twbs/bootstrap#32993] opened 2021-02-05 18:35 UTC
Whenever closing a `.fade` modal the animation should complete fully, however when an element in the modal is focused this is not the case. I can successfully reproduce this issue by using the any one of the bootstrap 5 modal examples that have `.fade`. The difference is hard to see at first glance so I attached slowed down videos of the two animations to identify the discrepancies.

Closing modal with no element focused:

https://user-images.githubusercontent.com/77477100/107073805-d24dfd00-67b5-11eb-8b7e-b6df468a9754.mp4

As you can see the animation finishes and executes properly.

Closing modal with element within it focused:

https://user-images.githubusercontent.com/77477100/107073751-bf3b2d00-67b5-11eb-9a51-6d75f8bd1ac2.mp4

Here the animation starts, but then gets interrupted and suspends.

- Operating system and version
macOS Big Sur 11.2
- Browser and version
Safari 14.0.3

Bootstrap 5.0.0-beta1

- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

https://getbootstrap.com/docs/5.0/components/modal/#varying-modal-content

**Comment by mdo** [comment] 2021-06-09 21:11
Possibly a duplicate of #34055?

**Comment by alpadev** [comment] 2021-06-11 20:56
@mdo I think this issue is fixed by #33845.

**Closed by alpadev** 2021-06-11 20:56 UTC
