### ISSUE TITLE
Invalid height of input.form-control in IE11

### ISSUE THREAD

**Issue by altso** [twbs/bootstrap#26815] opened 2018-07-06 15:47 UTC
The height of `<input type="text" class="form-control">` is smaller than `<select class="form-control"></select>` and other input controls in IE11. You can see it in the documentation (https://getbootstrap.com/docs/4.1/components/forms/).

![image](https://user-images.githubusercontent.com/1263018/42387817-93a6b836-8111-11e8-84a7-b334212f1b08.png)

I filed a new bug, but most likely it's the same as #25923.

**Comment by mdo** [comment] 2018-07-08 23:33
Closing as duplicate of #25923.

**Closed by mdo** 2018-07-08 23:33 UTC
