### ISSUE TITLE
Extending Bootstrap documentation english fail

### ISSUE THREAD

**Issue by mrstewar** [twbs/bootstrap#29575] opened 2019-10-22 19:05 UTC
https://getbootstrap.com/docs/4.3/extend/approach/#html-and-css-over-js

Second paragraph, first sentence.  Seems off to me. :)

"This principle is our first-class JavaScript API is data attributes."

**Comment by MartijnCuppens** [comment] 2019-10-23 19:19
Duplicate of https://github.com/twbs/bootstrap/issues/29163
Fixed by https://github.com/twbs/bootstrap/pull/29168

**Closed by MartijnCuppens** 2019-10-23 19:19 UTC
