### ISSUE TITLE
Print view: First letter displayed bellow the line.

### ISSUE THREAD

**Issue by ramiy** [twbs/bootstrap#23145] opened 2017-07-23 22:41 UTC
## Issue Description

All the pages in print view looks broken - the first letter displayed bellow the line.

I though it was an issues on my project but seems like the same issues appears in the official bootstrap site.

## How to Recreate

1. Visit: https://v4-alpha.getbootstrap.com/layout/grid/
2. CTRL + P

## Result

Attaching a PDF with the result: [bootstrap-print-issue.pdf](https://github.com/twbs/bootstrap/files/1168460/bootstrap-print-issue.pdf)

## Env

I'm using:
* Google Chrome 59.
* Windows 10 Home Edition (version 1607).

**Comment by wolfy1339** [comment] 2017-07-23 23:00
Duplicate of #21771

**Comment by Johann-S** [comment] 2017-07-24 13:12
Closed thanks to @wolfy1339 comment's 👍

**Closed by Johann-S** 2017-07-24 13:12 UTC
