### ISSUE TITLE
RTL Problem

### ISSUE THREAD

**Issue by omoridi** [twbs/bootstrap#32666] opened 2021-01-03 23:01 UTC
Hello dear
I see you added RTL in version 5, but it have some problem!
What's the problem?
I can not have both ltr and rtl in same time.
I do it for my self and add a rtl class. so you can have both ltr and rtl in same time.
if you use inspect of browser and add rtl to class attribute, everything shown RTL at runtime and do not need refreshed the page.
You can see on below link:
http://widgetnas.nastouh.com/Bootstrap/RTL
and fixed some a little css bugs of bootstrap 4
If you want the source files contact me to send you as free. or download css file free from 
http://widgetnas.nastouh.com/Bootstrap
Best regards
Omid Moridi

**Comment by ffoodd** [comment] 2021-01-04 10:01
Hi there,

This is explained [in our remaining tasks for RTL issue](https://github.com/twbs/bootstrap/issues/32330#issuecomment-743253285). We chose to have two separate files, meaning you can't use both at the same time.

We want to add some new examples showing bidi contents, but that's not done yet.

FWIW, implementing your way of doing this using our sources is pretty straightforward [thanks to RTLCSS String Maps](https://rtlcss.com/learn/usage-guide/string-map/) as long as you run Sass and RTLCSS by yourself. Simply wrap the desired partials (or everything) with something like:

```scss
/* rtl:begin:options: {
    "autoRename": true,
    "stringMap":[ 'name'    : 'ltr-rtl',
    'priority': 100,
    'search'  : ['ltr', 'Ltr', 'LTR'],
    'replace' : ['rtl', 'Rtl', 'RTL'],
    'options' :	{
        'scope' : '*',
        'ignoreCase' : false
      } ]
} */
.ltr {
  @import …;
}
/*rtl:end:options*/
```

This would result in `.ltr *` in LTR, and `.rtl` in RTL. Then you'd be able to import both files.

**Note**: this is only a concept, I didn't try so you may have a few things to handle manually.

I'm closing this for now since this is the intended behaviour, feel free to comment again or open more detailed issues for specific bugs or suggestions.

**Closed by ffoodd** 2021-01-04 10:01 UTC
Labels: feature
