### ISSUE TITLE
In Bootstrap Docs the dark mode the dark button goes invisible or negligible to see it

### ISSUE THREAD

**Issue by Phoenixz-py** [twbs/bootstrap#37724] opened 2022-12-26 17:38 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I was reading through docs in dark theme, and I saw this. There was a CSS for the dark button but not the button then I looked carefully and found that the button is almost negligible to see.
![image](https://user-images.githubusercontent.com/73833580/209572007-dbe5d0b4-6a2c-4119-be4f-f09d92c76f25.png)

I just wanted to report minor stuff in Boostrap docs nothing else, sorry if it's not worth noticing the issue. Just wanted better docs so we could learn.

### Reduced test cases

Sorry, Im, a beginner and wanted to suggest that's all but we can maybe use #00000 or border should fix.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.3

**Comment by julien-deramond** [comment] 2022-12-26 17:48
Hey @Phoenixz-py 
It is a duplicate of #37711 but thanks anyway for taking the initiative to report it :)

**Closed by julien-deramond** 2022-12-26 17:48 UTC
