### ISSUE TITLE
Bootstrap should have multi-level navbar out of the box.

### ISSUE THREAD

**Issue by bhadauriya18** [twbs/bootstrap#28953] opened 2019-06-24 13:27 UTC
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-success">
<a class="navbar-brand" href="#">Navbar</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">
<li class="nav-item">
<a class="nav-link" href="#">Home</a>
</li>
<li class="nav-item">
<a class="nav-link" href="#">About</a>
</li>
<li class="nav-item dropdown">
<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
Dropdown
</a>
<div class="dropdown-menu" aria-labelledby="navbarDropdown">
<a class="dropdown-item" href="#">Action</a>
<a class="dropdown-item" href="#">Another action</a>
<a class="dropdown-item" href="#">Something else here</a>
<div class="dropright">
<a class="dropdown-item dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
Dropdown
</a>
<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
<a class="dropdown-item" href="#">Action</a>
<a class="dropdown-item" href="#">Another action</a>
<a class="dropdown-item" href="#">Something else here</a>
</div>
</div>
</div>
</li>
<li class="nav-item">
<a class="nav-link" href="#">Contact</a>
</li>
</ul>
</div>
</nav>

**Comment by mdo** [comment] 2019-06-24 20:37
If I’m reading this right, this isn’t a navbar issue, but a multi-level dropdown issue. Closing as a duplicate of #27659.

**Closed by mdo** 2019-06-24 20:37 UTC

**Comment by bhadauriya18** [comment] 2019-06-25 00:53
But my issue is still unsolved

**Comment by robinwilson16** [comment] 2023-08-25 22:46
Not fixed in Bootstrap 5 either so need to use JavaScript workarounds.
Please can this be fixed or at least considered to be fixed.
