### ISSUE TITLE
Form Input Addon IE10

### ISSUE THREAD

**Issue by NightFlash82** [twbs/bootstrap#22186] opened 2017-03-14 09:13 UTC
Bootstrap 4 alpha-6

When having an addon on a form the clear icon gets centered and well half gone in IE10.
No other browser has those icons so not sure if it's me that doing something wrong.

![bs4-error2](https://cloud.githubusercontent.com/assets/7119894/23893412/a0db6f16-089e-11e7-9699-1043f05febfe.jpg)

**Comment by bkdotcom** [comment] 2017-03-14 16:55
not having IE10 in front of me... any chance some sort of plugin/extension is adding those icons?

**Comment by NightFlash82** [comment] 2017-03-14 17:20
I'm not running any plugins at all, not even addblockers. Looks fine in Bootstrap 4 alpha 5
![bs4-error4](https://cloud.githubusercontent.com/assets/7119894/23913315/d46bff64-08e2-11e7-98dd-de3076d5c1bb.jpg)

**Comment by Olivia101** [comment] 2017-03-14 20:38
@NightFlash82 Please include a live demo of the problem by creating a reduced test case via JS Bin.

**Comment by NightFlash82** [comment] 2017-03-14 20:55
https://jsbin.com/nazixajile/1/edit?html,output
You mean like this? =)

**Comment by patrickhlauke** [comment] 2017-03-14 21:19
seems to be caused by `.input-group .form-control { ... -ms-flex-direction:column; flex-direction:column; ... }` - likely a buggy implementation in IE11 (which unfortunately won't get any more bug fixes, so something bootstrap will have to work around)

**Comment by bastienmoulia** [comment] 2017-03-21 11:04
It looks like the `flex-direction` should be `row` and not `column`.

**Comment by GlenCroft** [comment] 2017-04-11 10:52
Pull Request #21716 fixes this issue.

**Comment by patrickhlauke** [comment] 2017-04-11 22:04
> Pull Request #21716 fixes this issue.

confirmed. closing

**Closed by patrickhlauke** 2017-04-11 22:04 UTC
Labels: confirmed, css, v4
