### ISSUE TITLE
Navbar Container Brand and Toggle Button Overlap on Small Screens

### ISSUE THREAD

**Issue by tikenn** [twbs/bootstrap#22370] opened 2017-04-07 05:15 UTC
When utilizing a container with a toggleable navbar on a small screen, the navbar-brand and the navbar-toggler overlap.  I think this is a combination effect from the width being removed from the container at the small screen and the margins on the left and right being set to auto.  The overlap makes the container feature of the navbar unusable.

Environment
 - OS: Windows 10 Desktop
 - Browsers
     - Chrome v57.0.2987.133
     - Opera v44.0.2510.857
     - Internet Edge v38.14393.0.0
     - Firefox v51.0.1

Test case:  https://jsbin.com/riroregime/2/edit?html,css,output

**Comment by iatek** [comment] 2017-04-07 11:09
I think this is a duplicate of #21590, and has been fixed in v4-dev branch.

**Comment by zalog** [comment] 2017-04-07 11:11
This was fixed here #22230
Take a look https://jsbin.com/rusafep/edit?html,css,output
Make sure you update html markup https://github.com/twbs/bootstrap/blob/v4-dev/docs/migration.md#navbar

**Comment by tikenn** [comment] 2017-04-07 14:53
Thanks!  And very sorry for the duplicate post.

**Comment by Johann-S** [comment] 2017-04-07 15:01
Closed thanks to @zalog 👍

**Closed by Johann-S** 2017-04-07 15:01 UTC
