### ISSUE TITLE
Need for offcanvas menu and vertical accordion menu

### ISSUE THREAD

**Issue by leonardo1024** [twbs/bootstrap#24894] opened 2017-11-27 19:18 UTC
I think it would be very helpful if there is offcanvas menu and vertical accordion menu (whithout ID )

**Comment by mdo** [comment] 2017-11-27 19:21
First part is a duplicate of #24718. No plans for the second part other than our existing accordion options in our collapse plugin.

**Closed by mdo** 2017-11-27 19:21 UTC
