### ISSUE TITLE
User-Select: all is not supported in IE or Edge Legacy

### ISSUE THREAD

**Issue by coliff** [twbs/bootstrap#32092] opened 2020-11-09 04:13 UTC
The Text Selection `.user-select-all` is not supported in IE or Edge Legacy.
REF: https://caniuse.com/mdn-css_properties_user-select_all

Maybe it could mention this as a note on on the v4 docs?
https://getbootstrap.com/docs/4.5/utilities/interactions/#text-selection

The compiled CSS actually includes:
```
.user-select-all {
  -ms-user-select: all !important;
```
but it doesn't do anything. Not really a big deal since it'd make almost no difference to the file-size after gzip compression - but  Can that be excluded from the CSS? Or would this be an issue with Autoprefixer?

**Comment by XhmikosR** [comment] 2020-11-09 05:27
You should definitely make an issue upstream (autoprefixer) regarding the CSS since that's handled automatically for us.

**Comment by coliff** [comment] 2020-11-09 05:30
cool will do that re: autoprefixer.

Should I open a PR for the v4 docs to mention that it's not supported? Something like:

> Note: `user-select-all` is not supported on Internet Explorer or Edge Legacy.

**Comment by XhmikosR** [comment] 2020-11-09 05:33
I'd wait a bit until the issue is solved because it could be something documented wrong. Please link to the upstream issue and let us know of the outcome and then we can proceed with a docs callout if needed.

**Comment by coliff** [comment] 2020-11-09 05:41
Sounds good. Opened an issue upstream: https://github.com/postcss/autoprefixer/issues/1372

**Comment by coliff** [comment] 2020-11-09 14:05
Neat! @ai has fixed it in Autoprefixer already and will release an update shortly!

**Comment by XhmikosR** [comment] 2020-11-09 16:45
@coliff feel free to send a PR adding a warning callout that this doesn't work on IE, otherwise we'll tackle it later. I still want to finish with the Hugo switch since that PR is touching almost all doc files.

**Comment by XhmikosR** [comment] 2020-11-10 15:11
Updated the deps in #32115 which takes case of one part of this issue. The callout is left; any PRs welcome.

**Comment by coliff** [comment] 2020-11-10 15:12
cool - will open a PR for the docs within the hour.

**Comment by coliff** [comment] 2020-11-10 15:37
What branch should the PR be made from - the `v4-dev` branch?

**Comment by XhmikosR** [comment] 2020-11-13 18:50
Fixed by #32151

**Closed by XhmikosR** 2020-11-13 18:50 UTC
Labels: build, docs, v4
