### ISSUE TITLE
Cards with image overlays don't work with CSS filters on Chrome

### ISSUE THREAD

**Issue by phbo85** [twbs/bootstrap#18802] opened 2016-01-08 14:59 UTC
It seems only the first card with images overlay seems to work with the filter. The other cards appear white on Chrome 47 with Windows 10.

Example: http://codepen.io/phbo/pen/obWwwB

Edit: closed the div

**Comment by twbs-lmvtfy** [comment] 2016-01-08 14:59
Hi @phbo85!

You appear to have posted a live example (http://codepen.io/phbo/pen/obWwwB.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 38, column 1 thru column 7: End tag for  ```` body ```` seen, but there were unclosed elements.
* line 8, column 1 thru column 23: Unclosed element ```` div ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by mdo** [comment] 2016-01-08 18:55
What makes this a Bootstrap bug exactly? Sounds like something funky with image filters.

**Comment by kevin-quach** [comment] 2016-01-08 21:20
It looks to be a conflicting issue between .card-column's `-webkit-column-count` and the `-webkit-filter`. `-webkit-backface-visibility: hidden;` applied to the `<img>` seems to fix the issue. 

Codepen: http://codepen.io/anon/pen/mVmXRJ

**Comment by cvrebert** [comment] 2016-01-09 07:44
> The other cards appear white on Chrome 47 with Windows 10.

Same on OS X Chrome, but not on Firefox or Safari.
@phbo85 So it looks like you've found a Chrome bug! Congratulations! You should file a report at http://crbug.com/new and post a link to the report here when you're done.
But since this involves additional custom styles, it's not a bug in Bootstrap itself. So I'll close this issue.

**Closed by cvrebert** 2016-01-09 07:44 UTC
Labels: browser bug, css, v4
