### ISSUE TITLE
Odd placements in a fixed-top navbar within a container, XS screens

### ISSUE THREAD

**Issue by LastZactionHero** [twbs/bootstrap#23059] opened 2017-07-12 21:04 UTC
Using Bootstrap 4, Alpha 6

I'm using a `fixed-top` `navbar`, with the contents placed within a `container` to center. I noticed that the placement is off on XS screen sizes.

Following the directions form the Navbar docs:

> Although it’s not required, you can wrap a navbar in a .container to center it on a page or **add one within to only center the contents of a fixed** or static top navbar.

In my attached sample code, I'm using the boilerplate navbar, with `fixed-top` class added, and contents placed within a `container`. I believe this is correct.

The issue, Bootstrap 4 on XS screen:
![bootstrap_4_xs](https://user-images.githubusercontent.com/246122/28139642-41fc858e-6712-11e7-94d1-f91068e9ad6e.png)

Working properly on Bootstrap 4 on SM screen:
![bootstrap_4_sm](https://user-images.githubusercontent.com/246122/28139653-4ab9dc3a-6712-11e7-882e-90edc04136c6.png)

Working properly in Bootstrap 3 on XS screen:
![bootstrap_3_xs](https://user-images.githubusercontent.com/246122/28139661-50d4a212-6712-11e7-8432-ef5b8daee152.png)

What changes on the drop down from XS to SM:

- The width of the container (540px) is removed.
- `margin-left: auto` and `margin-right: auto` are applied

This causes the container to shrink to only contain the brand logo. Because the toggler is `placement: absolute` relative to `.container`, it moves to a weird placement next to the logo in the smaller container.

**My Workaround**
```
@media (max-width: 575px) {
  .navbar {
     .container {
      margin-left: 0px;
      margin-right: 0px;
    }
  }
}
```

Zip file contains an example in Bootstrap 4 and a working example in Bootstrap 3
[html_files.zip](https://github.com/twbs/bootstrap/files/1143306/html_files.zip)

**Comment by gijsbotje** [comment] 2017-07-12 21:33
see #23056 (posted 4 hours ago)

**Comment by Johann-S** [comment] 2017-07-13 07:28
@LastZactionHero does the @gijsbotje's answer solved your issue ?

**Comment by LastZactionHero** [comment] 2017-07-13 16:34
I can confirm that the fixed-nav [example](https://twbs.github.io/staging/docs/4.0/examples/navbar-top-fixed/) @gijsbotje provided works, and works even with a `.container`, which is great.

It looks like the example is using a staging stylesheet- the example does not work with the alpha 6 release css. Is there a way to achieve this on the alpha 6 release? Otherwise I'll probably just stick with my workaround for this purpose of my project until the next release.

**Comment by mdo** [comment] 2017-07-14 23:32
This has been fixed in `v4-dev`. Hosted docs will be updated with our next release.

**Closed by mdo** 2017-07-14 23:32 UTC
Labels: css, v4

**Comment by alexandre1985** [comment] 2017-08-21 07:31
I'm using bootstrap beta 4 cdn.
A navbar with a container has too much space with is left and right margin in the lg and below devices. In using `navbar-expand-lg`.
In my local copy of alpha-v6 it did everything correctly.
Here is the difference:
_Bootstrap 4 alpha-v6:_
```
@media (min-width: 768px)
.container {
    max-width: 100%;
}
```
(its ok)
_Bootstrap 4 beta:_
```
@media (min-width: 768px)
.container {
    max-width: 720px;
}
```
(it lefts too much space around the container)
the problem is in scss/mixins/_grid.scss:18
here is a example of what I mean: [container within navbar](https://codepen.io/dannysantos1985/pen/LjdmgR?editors=1000)

**Comment by alexandre1985** [comment] 2017-08-28 18:17
This can be fixed with
```
@media (max-width: 991px) {
  .navbar-expand-lg .container {
    max-width: 100%;
  }
}
```
