### ISSUE TITLE
ScrollSpy in v3 does not properly escape IDs

### ISSUE THREAD

**Issue by Parent5446** [twbs/bootstrap#18892] opened 2016-01-14 09:25 UTC
I cannot seem to find an issue for this already, so here it goes:

When using ScrollSpy, ScrollSpy.refresh() gets the href directly from the attribute and immediately passes it to jQuery. However, if the href contains a colon, it needs to be escaped before it can be used in a jQuery selector.

The relevant code: https://github.com/twbs/bootstrap/blob/master/js/scrollspy.js#L59
Relevant jQuery docs: https://api.jquery.com/id-selector/

**Comment by cvrebert** [comment] 2016-01-14 22:44
Duplicate of #14285.

**Closed by cvrebert** 2016-01-14 22:44 UTC
Labels: js, v3
