### ISSUE TITLE
Grid system broken with flex and IE10-11

### ISSUE THREAD

**Issue by ezramorse** [twbs/bootstrap#17310] opened 2015-08-25 15:00 UTC
The following code block renders on two lines when compiling the SASS stylesheet with option:
$enable-flex: true !default;

`<div class="container">
        <div class="row">
                <div class="col-sm-6">
One of Two Columns
                </div>
                <div class="col-sm-6">
Two of Two Columns
                </div>
        </div>
</div>`

**Comment by kkirsche** [comment] 2015-08-25 15:13
Per [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports), bug reports should include an isolated example of the problem with instructions (as necessary) for us to reproduce the problem. This would greatly assist us in debugging

Thanks for your understanding and cooperation!

**Comment by ezramorse** [comment] 2015-08-25 15:37
Issue is with flex width calculation and IE11

1. Edit scss/_variables.scss and set $anable-flex:true
2. run grunt dist-css
3. Include compiled css in project

Link: http://output.jsbin.com/xacunafogu/1/

Is this merely a limitation of IE11? I don't think this scenario matches the known issues listed.

**Comment by ezramorse** [comment] 2015-08-25 16:09
If you remove the left and right padding from the columns, the grid layout will be corrected in IE11.
http://output.jsbin.com/vicamaviyo/1/

For a temporary workaround on IE 11, if you are not needing wrapping (using less than 12 columns per row), change flex-wrap on row to "nowrap".
http://output.jsbin.com/ziyorijuli/1/

**Comment by slavanga** [comment] 2015-08-25 19:53
It looks like we're hitting this bug here:
https://github.com/philipwalton/flexbugs#7-flex-basis-doesnt-account-for-box-sizingborder-box

Using ```width: 50%``` instead of ```flex-basis: 50%``` would solve this issue in IE10 and 11.

**Comment by neilhem** [comment] 2015-09-11 11:16
How about max-width property with flex-basis? Like:
```css
.col-md-6 {
  flex: 0 0 50%;
  max-width: 50%;
}
```

**Comment by johanhar** [comment] 2015-09-22 11:58
Yeah, the `box-sizing: border-box` is ignored by IE11 when using flex. See link from @slavanga for more info... 

If you create an example and compare IE11 with something like Chrome, and then go to Chrome and change to `content-box` you'll see that also Chrome will be broken and they look exactly the same...

**Comment by johanhar** [comment] 2015-09-22 12:07
As @neilhem suggest, it seems to work (haven't tested for very long yet) when setting the `max-width` equal to `flex-basis`:

```
.col-xs-1 {
    flex-grow: 0;
    flex-shrink: 0;
    flex-basis: 8.33%;
    max-width: 8.33%;
}
```

**Comment by IceReaper** [comment] 2015-09-22 13:27
Using currently this in my project to get around that - works perfectly.

```scss
// IE 11 flexbox fix.
// TODO: Remove when fixed in bootstrap.
// https://github.com/twbs/bootstrap/issues/17310
@if $enable-flex {
	@each $breakpoint in map-keys($grid-breakpoints) {
		@include media-breakpoint-up($breakpoint) {
			@for $size from 1 through $grid-columns {
				.col-#{$breakpoint}-#{$size} {
					max-width: percentage($size / $grid-columns);
				}
			}
		}
	}
}
```

**Comment by johanhar** [comment] 2015-09-22 13:33
Thanks @IceReaper :+1:

**Comment by alexkerr** [comment] 2015-10-13 14:41
Thanks @IceReaper  - also using this fix

**Comment by cvrebert** [comment] 2015-10-31 21:44
CC: @mdo

**Comment by artifactdev** [comment] 2015-11-02 11:41
It seems that this bug also appears in Firefox.

**Comment by cvrebert** [comment] 2015-11-05 21:03
@artifactdev I can't reproduce with http://output.jsbin.com/lasiwu on Firefox 44.0a2

**Comment by artifactdev** [comment] 2015-11-09 07:44
@cvrebert it seems that only firefox > 42 is affected by this bug.

**Comment by cvrebert** [comment] 2015-11-09 07:50
@artifactdev Erm, 44 > 42, yet I couldn't repro.

**Comment by MaxKorz** [comment] 2015-12-24 11:01
Same problem.

The issue can be seen on this codepen http://codepen.io/ncerminara/pen/EjqbPj/
Open it in IE 11 and switch from Float Grid to Flexbox Grid.
max-width fixes it

**Comment by bassjobsen** [comment] 2015-12-27 00:18
https://github.com/twbs/bootstrap/pull/17756 solves this? also see: https://github.com/twbs/bootstrap/issues/18688

**Comment by mdo** [comment] 2016-01-07 08:33
Fixed with #17756.

**Closed by mdo** 2016-01-07 08:33 UTC
Labels: browser bug, confirmed, css, v4

**Comment by t-wales** [comment] 2016-07-25 16:37
thanks @IceReaper you just saved my job.
