### ISSUE TITLE
There are 16 css variable in bootstrap.css that haven't any value why ??

### ISSUE THREAD

**Issue by Archanadesai** [twbs/bootstrap#38878] opened 2023-07-07 05:17 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

There are 16 css variable in bootstrap.css that haven't any value why ?? it create so many issue with dark mode

### Reduced test cases

https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css

https://imgur.com/a/zge6crl

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.3

**Comment by julien-deramond** [comment] 2023-07-07 05:39
Thanks for opening an issue @Archanadesai but it's a duplicate of #36595
FWIW, it's not linked to dark mode itself, most of them were created before the color modes implementation

**Closed by julien-deramond** 2023-07-07 05:39 UTC
Labels: duplicate
