### ISSUE TITLE
Tooltip Not Work as Well when using svg

### ISSUE THREAD

**Issue by fiik346** [twbs/bootstrap#31616] opened 2020-09-09 10:30 UTC
When tooltip using svg sometimes is show, sometimes is not show and console log output like that.

```
tooltip.js:343 Uncaught TypeError: Cannot read property 'destroy' of null
    at n (tooltip.js:343)
    at e.i.hide (tooltip.js:370)
    at e.i._leave (tooltip.js:655)
    at HTMLAnchorElement.<anonymous> (tooltip.js:548)
    at HTMLAnchorElement.n (event-handler.js:101)
```
Html code like this
```
<a class='share-btn share-btn-facebook' href='https://www.facebook.com/sharer/sharer.php?u=https://codepen.io/marko-zub/#' rel='nofollow' target='_blank' data-toggle="tooltip" data-placement="right" title="Share on Facebook">
<svg height="16px" width="16px" width="1.1em" height="1.1em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z"/></svg>
</a>
```

**Comment by mznet** [comment] 2020-09-09 14:27
@fiik346  This problem occurs when calling the `destroy` method of `_popper` variable before `Popper` instance is assigned to the `_popper` variable. It is handled by [Pull Request](https://github.com/twbs/bootstrap/pull/31115)

**Comment by coliff** [comment] 2020-09-10 06:27
I ran into this issue too and opened a discussion about it yesterday before seeing this issue.

I have posted a simplified test-case CodePen here:
https://codepen.io/coliff/pen/JjXpOJY

**Comment by hallmatt** [comment] 2020-09-11 18:16
I'm encountering this issue as well. Hopefully that PR will resolve the CodePen @coliff created...

**Comment by mdo** [comment] 2020-09-14 22:01
Duplicate of #31646.

**Closed by mdo** 2020-09-14 22:01 UTC
