### ISSUE TITLE
v4: Cannot use input of a popover inside modal

### ISSUE THREAD

**Issue by nunofilipesf** [twbs/bootstrap#22249] opened 2017-03-23 12:03 UTC
I've tried to create a modal with a popover inside. 
This popover has html content with an _input_ and a _select_.

If i open the modal and the popover, i can use the _select_, but not the _input_. 
Also, the focus is not on the _input_.

Sample here: https://jsfiddle.net/bpx3zsyz/2/

Tested in Chrome, Edge and Firefox, always with the same behaviour

**Comment by gsferreira** [comment] 2017-03-23 14:46
:+1:

**Comment by satyajit11** [comment] 2017-03-23 19:09
remove  tabindex="-1"  of your modal it'll work.put the below line without tabindex

<div class="modal fade" id="exampleModalLong" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">

here is example fiddle
[jsfiddle](https://jsfiddle.net/satya6565/w8yh65cr/1/)

**Comment by Johann-S** [comment] 2017-03-23 21:31
IMO @satyajit11 give a correct answer (see https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex).

I'm not sure it's a Bootstrap bug here, any advice @mdo or @bardiharborow ?

**Comment by mdo** [comment] 2017-03-23 22:59
Our docs include `tabindex="-1"`—do we need to update to fix that on our end, or is there JS to tackle?

**Comment by satyajit11** [comment] 2017-03-24 02:40
@Johann-S  when add popover code is append to body which is outside modal because we already have tabindex="-1"  so focus won't go there.I don't proper js solution but i think we need to append inside the container or remove focus from modal when we add popover

**Comment by nunofilipesf** [comment] 2017-03-24 10:25
Removing the tabindex from the modal solved my problem.

Can i close the issue or there is here a bug in Bootstrap to solve?

**Comment by Johann-S** [comment] 2017-03-24 12:40
As @mdo said we should update our documentation and remove ``tabindex="-1"`` reference.
@nunofilipesf we have to update our documentation

**Comment by patrickhlauke** [comment] 2017-03-24 13:46
removing the `tabindex=-1` on the modal is NOT the solution. or rather: once you remove this, the modal cannot be programmatically focused by javascript when it's opened, meaning that accessibility for the modal is broken (screen reader doesn't announce there's a modal, doesn't read the title of the modal).

i'd suggest the problem is in the popup and the way it's generated, rather than the modal itself.

**Comment by Johann-S** [comment] 2017-03-24 16:18
When #22263 will be merged @nunofilipesf  you'll have to update your code to the following : 
```javascript
    $(document).ready(function () {
    	var popoverContent = '<div> \
                                    <select class="form-control mb-1"> \
                                        <option value="eq">Is equal to</option>  \
                                        <option value="ct">Contains</option> \
                                    </select> \
                                    <input type="text" class="form-control"> \
                                </div>';
    
    	$('#exampleModalLong').on('shown.bs.modal', function (e) {
    		var popover = $('#popover-btn').popover({
    			title: '',
    			placement: 'bottom',
    			html: true,
    			content: popoverContent,
    			trigger: 'manual',
                        container : '#exampleModalLong'
    		});
    	});
    
    	$('#popover-btn').click(function () {
    		$(this).popover('show');
    	});

**Comment by DavidEmanuelsen** [comment] 2017-03-29 11:41
I tried this with the changes in the pull-request + tether 1.4.0. Tried adding an id to the modal-element and using that as the container, but I'm having issues with the position of the popover as soon as there is a scrollbar / long content in the modal. Seems like the popover moves twice as much as it should on the y-axis. 

Is this something known, or am I doing something horribly wrong? :)

**Comment by Johann-S** [comment] 2017-03-29 11:48
Please @DavidEmanuelsen post a JSBin or a CodePen to see your issue thank you

**Comment by DavidEmanuelsen** [comment] 2017-03-29 12:01
https://jsfiddle.net/w8yh65cr/3/

Slightly ugly jsfiddle, not sure how to reference bootstrap including the changes you've made.

**Comment by Johann-S** [comment] 2017-03-29 12:44
It seems Tether determine position of the popover according to the scroll position 🤔

**Comment by FezVrasta** [comment] 2017-04-05 18:59
The "append" option of Tether accepts only an element that is **identical** to body, nothing different. (same size, same position, same everything).

This, and lot of different problems, were the reason that convinced me in opening this PR:
https://github.com/twbs/bootstrap/issues/19673

**Comment by Johann-S** [comment] 2017-05-14 09:48
Closed and fixed by #22444

**Closed by Johann-S** 2017-05-14 09:48 UTC
Labels: js, v4

**Comment by dersar00** [comment] 2019-05-17 07:20
I'm still experiencing this issue too, `v4.3.1`.

**Comment by Johann-S** [comment] 2019-05-17 07:34
Hi @dersar00,

It seems related to your code because you have a live example which work here: https://getbootstrap.com/docs/4.3/components/modal/#tooltips-and-popovers

Anyway it's pointless to comment on a closed issue, if you have an issue open a new one with a live test example 👍
