### ISSUE TITLE
"Automatically set modal's width for larger viewports" causes overflow X (v4)

### ISSUE THREAD

**Issue by ivandurst** [twbs/bootstrap#19969] opened 2016-05-25 22:47 UTC
`.modal-dialog` gets set to `width: 600px` at `media-breakpoint-up(sm)`, causing it to be wider than the browser window between 544px and 599px. I overrode the var `$modal-md` with a value of `map-get($grid-breakpoints, sm) !default;` to resolve the issue.

The issue is on line **133** of **_modal.scss**:

    // Scale up the modal
    @include media-breakpoint-up(sm) {
      // Automatically set modal's width for larger viewports
      .modal-dialog {
        width: $modal-md;
        margin: 30px auto;
      }
    ...

**Comment by RyanZim** [comment] 2016-05-26 00:41
Testcase: https://jsfiddle.net/x1qpe0mm/

**Comment by cvrebert** [comment] 2016-05-26 01:09
Duplicate of #17581, I believe.

**Closed by cvrebert** 2016-05-26 01:09 UTC
Labels: css, v4

**Comment by RyanZim** [comment] 2016-05-26 10:38
@cvrebert The testcase uses the latest master branch. #17581 is supposedly fixed. This issue isn't. Please reopen.

**Comment by cvrebert** [comment] 2016-05-26 18:19
@RyanZim The `width` declaration that OP referenced no longer exists. It's a `max-width` now: https://github.com/twbs/bootstrap/blob/v4-dev/scss/_modal.scss#L119
Also, couldn't repro with your testcase (in OS X Chrome):
![modal](https://cloud.githubusercontent.com/assets/419884/15585321/9a607e2a-2333-11e6-9bfc-54e01e004212.png)

**Comment by RyanZim** [comment] 2016-05-26 18:27
@cvrebert Perhaps it is a different issue, but your screenshot demonstrates it. The modal comes right up to the edge of the viewport. If you make the preview window smaller, it will have a nice margin. I doubt this is intended behavior.

**Comment by cvrebert** [comment] 2016-05-26 18:49
@RyanZim Filed #19973.
