### ISSUE TITLE
import "bootstrap" is not working

### ISSUE THREAD

**Issue by kamalpatel125** [twbs/bootstrap#20491] opened 2016-08-09 16:00 UTC
Hi,

import "bootstrap" is not working and i think because in "package.json" - "main": "./dist/js/npm" but there is no npm folder exist..

For now can use "import 'bootstrap/dist/js/bootstrap';"  but it's nice to have "import 'bootstrap;" So could you fix this please ? 

Thanks, 

Kamal Patel.

**Comment by pkozlowski-opensource** [comment] 2016-08-09 16:04
Duplicate of #20383

**Closed** 2016-08-09 17:02 UTC

**Comment by cvrebert** [comment] 2016-08-09 17:03
Please search more for existing issues in the future. Thanks.
