### ISSUE TITLE
Carousel Images appear below currrent Image, and then replace it.

### ISSUE THREAD

**Issue by markddrake** [twbs/bootstrap#40839] opened 2024-09-16 20:58 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

using a simple bootstrap carouse, when the carousel starts to cycle or the left and right buttons are pressed the new image appears  below the bottom right corner of the image to be replaced, both images then slide left and the bottom (new) imagesmoves up to replace the old image when the old image is not longer viasable.

### Reduced test cases

```html
<!doctype html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Available Services</title>
    <link rel="stylesheet" href="/npm/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="/npm/bootstrap-icons/font/bootstrap-icons.css">
<style>
</style>
  </head>
  <body>
    <div class="container">
      <div class="row">
	     <div id="slideCarosuel" class="carousel slide" data-bs-ride="carousel">
	       <div class="carousel-inner">
  		     <div class="carousel-item  active"><img class="d-block w-100" src="https://www.aber.ac.uk/en/discover-aberystwyth/about-aber/aboutaberystwyth.jpg"/></div>
	       </div>
		   <div class="carousel-inner">
  		     <div class="carousel-item"><img class="d-block w-100" src="https://www.aber.ac.uk/en/discover-aberystwyth/about-aber/aboutaberystwyth.jpg"/></div>
	       </div>
  		   <div class="carousel-inner">
		     <div class="carousel-item"><img class="d-block w-100" src="https://www.aber.ac.uk/en/discover-aberystwyth/about-aber/aboutaberystwyth.jpg"/></div>
		   </div>
           <a class="carousel-control-prev" href="#slideCarosuel" role="button" data-bs-slide="prev">
             <span class="carousel-control-prev-icon"></span>
           </a>
           <a class="carousel-control-next" href="#slideCarosuel" role="button" data-bs-slide="next">
             <span class="carousel-control-next-icon"></span>
           </a> 
        </div>
	  </div>
	</div>
    <script src="/npm/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of Bootstrap are you using?

5.3

**Comment by julien-deramond** [comment] 2024-09-17 04:38
Hello @markddrake.

From the HTML markup, everything looks correct as described in the documentation. I’ve also double-checked the example’s rendering on Edge, and I couldn’t spot any unusual behavior.

Could you please create a working reduced test case on [CodePen](https://codepen.io/) or [StackBlitz](https://stackblitz.com/) for easier testing?
If possible, a short video or GIF highlighting the issue would be helpful for us to better understand what's happening.

Thanks for your time 🙏

**Comment by omishah** [comment] 2024-09-17 04:42
The issue is because you have multiple ``.carousel-inner`` divs, instead you should have one and within this div all your      individual slides ``.carousel-item`` must be present!

**Comment by julien-deramond** [comment] 2024-09-17 04:54
Good catch @omishah! Thanks for pointing that out!
You got better eyes than me. It's too early in the morning on my side 😇 
So I'm closing this issue as it's a markup issue.

**Closed by julien-deramond** 2024-09-17 04:54 UTC
Labels: awaiting-reply

**Comment by markddrake** [comment] 2024-09-17 05:11
Thanks guys - problem solved.
