### ISSUE TITLE
Justified nav example header bug

### ISSUE THREAD

**Issue by adelivuk** [twbs/bootstrap#19428] opened 2016-03-07 09:48 UTC
Seems to break:

![screen shot 2016-03-07 at 10 46 06](https://cloud.githubusercontent.com/assets/6178877/13565677/db3c6902-e451-11e5-97b8-fa9fd7e73f1f.png)

Tested in Chrome v48.0.2564.116 (64-bit) and v49.0.2623.75 (64-bit), FF v42.0 and v44.0.2

**Comment by cvrebert** [comment] 2016-03-07 09:49
@adelivuk What version of Bootstrap?

**Comment by adelivuk** [comment] 2016-03-07 09:50
@cvrebert i'm looking at [v4-alpha.getbootstrap.com/examples/justified-nav/](http://v4-alpha.getbootstrap.com/examples/justified-nav/).

**Comment by cvrebert** [comment] 2016-03-07 09:54
Duplicate of #17723. Please search more in the future.

**Closed by cvrebert** 2016-03-07 09:54 UTC
Labels: css, v4

**Comment by adelivuk** [comment] 2016-03-07 10:01
@cvrebert sorry, my bad - searched but with a low quality query.
