### ISSUE TITLE
Padding added when modal is available

### ISSUE THREAD

**Issue by TechnicalSuwako** [twbs/bootstrap#27333] opened 2018-09-28 03:15 UTC
When opening modal , navbar will be adding this to style attrib:
`padding-right: 31px; margin-right: -15px;`

In events of closing the modal, style attrib become empty again.
![modalerror](https://user-images.githubusercontent.com/15627184/46186037-8eaa7500-c317-11e8-8748-be58a1c73cf5.gif)

Please cure.

Bug reports must include:

- Manjaro Linux, kernel 4.14.71-1-MANJARO, Qt 5.11.1, KDE 5.13.5
- Chromium 69.0.3497.92
- ？？

**Comment by XhmikosR** [comment] 2018-09-29 14:52
@Johann-S isn't this similar if not the same as #27071?

**Comment by Johann-S** [comment] 2018-10-01 09:53
yep it's the same here 👍 

Closed because duplicate of #27071

**Closed by Johann-S** 2018-10-01 09:53 UTC
