### ISSUE TITLE
New documentation rendering issues on MS Edge 15.0

### ISSUE THREAD

**Issue by rosieks** [twbs/bootstrap#22751] opened 2017-06-04 19:36 UTC
It looks that new documentation doesn't look well on MS Edge 15.15063 / Windows 10
Bellow I've attached screenshots:
![image](https://cloud.githubusercontent.com/assets/1107959/26764763/b0e01104-496d-11e7-9a55-aba653cef8fd.png)
![image](https://cloud.githubusercontent.com/assets/1107959/26764768/c65f47e8-496d-11e7-8dde-b5db259555ef.png)

**Comment by Johann-S** [comment] 2017-06-04 20:21
I confirme Edge and Win10 too

**Comment by Johann-S** [comment] 2017-06-04 20:24
It seems a well known not implemented feature in Edge see : https://developer.microsoft.com/en-us/microsoft-edge/platform/status/positionsticky/

**Comment by mdo** [comment] 2017-06-05 05:30
Hmm, I thought I accounted for this in the docs. I'll take another look.

**Comment by mdo** [comment] 2017-06-10 23:55
Can you confirm you have the latest from `v4-dev`, and the version of Edge? I don't have Edge on my VM.

**Comment by patrickhlauke** [comment] 2017-06-11 19:27
Yes, confirmed

![capturebs](https://user-images.githubusercontent.com/895831/27013887-553b896a-4ee4-11e7-992d-9f0ae785e9d2.PNG)

**Comment by Studio384** [comment] 2017-06-15 11:58
If this is due to ```position: sticky``` not being supported, than it is fixed as of Edge 15.16215 which does support that.

**Comment by Johann-S** [comment] 2017-06-15 12:01
For Windows insider preview yes see : https://developer.microsoft.com/en-us/microsoft-edge/platform/status/positionsticky/

**Comment by mdo** [comment] 2017-06-15 14:51
I've updated my VM and still don't have that version, hmm. Will need to look into it more still.

**Comment by Studio384** [comment] 2017-06-15 15:34
@mdo: what version do you mean? Edge 15.15063? You can force it to upgrade with the Windows Upgrade Tool.

**Comment by mdo** [comment] 2017-06-15 16:01
Yeah, for Edge. I'll take a look at the force upgrade. Running Windows Update wasn't cutting it for me.

**Comment by mdo** [comment] 2017-06-15 16:04
I thought I had found a way to work around the bug in `position: sticky` with some `@supports` action. See https://github.com/twbs/bootstrap/blob/v4-dev/assets/scss/_sidebar.scss#L51-L68. Basically Edge and IE11 are rendering it as `position: relative` and thus applying the `top` offsets. My intent was to only apply those styles if it was fully supported. Might not be working completely.

**Comment by Studio384** [comment] 2017-06-15 17:39
This will help you get your VM to the latest stable release so that you can test it out: https://www.microsoft.com/en-us/software-download/windows10.

**Comment by mdo** [comment] 2017-06-16 03:24
Working on the update, but here's what I see on Edge 14 for posterity.

<img width="1653" alt="screen shot 2017-06-15 at 8 23 42 pm" src="https://user-images.githubusercontent.com/98681/27210630-91a9320e-5208-11e7-9c40-11fede7c82b7.png">

**Comment by mdo** [comment] 2017-06-16 03:55
Works on my machine! lol

<img width="1552" alt="screen shot 2017-06-15 at 8 54 52 pm" src="https://user-images.githubusercontent.com/98681/27211264-f74f9aae-520c-11e7-9b34-26e9604b0060.png">

**Comment by JohanSellberg** [comment] 2017-06-16 09:03
Works well for me as well on MS Edge 15.15063 / Windows 10.

![screenshot_edge15](https://user-images.githubusercontent.com/182779/27219833-5e64e49e-5283-11e7-8d42-57fc3059f3e7.png)

**Comment by patrickhlauke** [comment] 2017-06-16 10:02
just to check: did you scroll down a bit, maybe follow an in-page link, then scroll back up?

**Comment by craigpotter** [comment] 2017-06-16 10:18
It isn't sticky or fixed for me on scroll but other wise works ok. 



![capture](https://user-images.githubusercontent.com/1442635/27222715-4cce5768-5285-11e7-823d-b61db06f9fa0.JPG)

**Comment by JohanSellberg** [comment] 2017-06-16 10:42
@patrickhlauke I have tried that now and I am unable to reproduce the same issue that @rosieks reported.  But as @craigpotter points out it is not fixed or sticky when you scroll. (also @craigpotter that is in version 14, issue should be in 15.15063 ? )

**Comment by craigpotter** [comment] 2017-06-16 10:55
@Johann-S   Ah I assumed I would already have the update ... Doh! My bad. New Issue or effect of side effect?

**Comment by Johann-S** [comment] 2017-06-16 10:57
@craigpotter it's the same issue 👍 `sticky` position isn't applied

**Comment by patrickhlauke** [comment] 2017-06-17 12:10
Confirming that the issue of the gap appearing at the top of the left-hand navigation, per the issue starter, is now not present anymore.

As for `position:sticky`, this is likely to come in future versions of Edge - see https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/10982527/ and https://developer.microsoft.com/en-us/microsoft-edge/platform/status/positionsticky/?q=sticky

**Closed by patrickhlauke** 2017-06-17 12:10 UTC
Labels: browser bug, confirmed, docs, v4

**Comment by mdo** [comment] 2017-06-17 17:04
When it comes to Edge, it should just work provided everything happens as intended with `@supports`.
