### ISSUE TITLE
Responsive Carousel with Chrome, Opera and Vivaldi v4

### ISSUE THREAD

**Issue by josmaissan** [twbs/bootstrap#21611] opened 2017-01-08 14:26 UTC
## Responsive Carousel does not work with browsers: Chrome, Opera and Vivaldi
**The hight stays at real picture hight.**

- Operating system and version (macOS Sierra 10.12.3 and Windows 10.0)
- Browser and version (Google Chrome 56.0.2924.87, Opera 43.0.2442.806 and Vivaldi 1.7.735.46)

Here is a demo of the problem (desktops with i.a. Chrome & Opera all stable) on JSFiddle:
https://jsfiddle.net/josmaissan/2e54sbt7/

This is what it looks like:
![schermafbeelding 2017-01-09 om 08 24 01](https://cloud.githubusercontent.com/assets/24986277/21759681/67b5240a-d646-11e6-87d4-ae7ff2aeb349.png)
### Here are some posible solutions:

1. [Solution option 1](#issuecomment-271177357), with the suggestion of @Jas-n:
https://jsfiddle.net/josmaissan/vgh5z4zx/
2. [Solution option 2](#issuecomment-272711228), with the suggestion of @DeltaOS2:
https://jsfiddle.net/josmaissan/0tqjxrf3/
3. Solution option 3, #21799, with the suggestion of @vanduynslagerp:
https://jsfiddle.net/josmaissan/08u40Lue/

**Comment by wrldtrvllr** [comment] 2017-01-08 15:34
I recognized the same behavior. Worked as expected with alpha 5.

**Comment by Jas-n** [comment] 2017-01-08 17:51
You can fix this by overwriting the ".carousel-item.active" selector to display:block;

**Comment by josmaissan** [comment] 2017-01-08 20:23
@Jas-n It's a partly fix.
During the transition it is still to high displayed (only the upper part of the picture is visible), but pops in when transition is finished.

**Comment by Jas-n** [comment] 2017-01-08 20:34
Sorry, Need to add 3 classes which covers the transitions:

.carousel-item.active,
.carousel-item-next,
.carousel-item-prev{
	display:block;
}

**Comment by wrldtrvllr** [comment] 2017-01-08 20:55
Will this be fixed in an upcoming release or should we stick with the workaround?

**Comment by Jas-n** [comment] 2017-01-08 20:57
I'd guess this'll be fixed before the next (beta) release.

**Comment by wrldtrvllr** [comment] 2017-01-08 21:00
Great! Thank you very much.

**Comment by josmaissan** [comment] 2017-01-08 21:08
Yes, now it works fine!

**Comment by mdo** [comment] 2017-01-09 00:16
Does anyone have a demo of the problem?

**Comment by josmaissan** [comment] 2017-01-09 07:26
@mdo Here is a temperary demo:
http://jossan.home.xs4all.nl/test-carousel.html
problems with Chrome, Opera, Vivaldi only
![schermafbeelding 2017-01-09 om 08 24 01](https://cloud.githubusercontent.com/assets/24986277/21759542/37840aae-d645-11e6-9cb2-5d346cdfadf2.png)

**Comment by josmaissan** [comment] 2017-01-09 07:34
@mdo Here is a temperary demo:
http://jossan.home.xs4all.nl/test-carousel.html
problems with Chrome, Opera, Vivaldi only
![schermafbeelding 2017-01-09 om 08 24 01]

This is what it looks like:
![schermafbeelding 2017-01-09 om 08 24 01](https://cloud.githubusercontent.com/assets/24986277/21759681/67b5240a-d646-11e6-87d4-ae7ff2aeb349.png)

**Comment by iatek** [comment] 2017-01-09 13:22
Here's another example of the issue:
http://www.codeply.com/go/0QUU06MiIL

**Comment by DeltaOS2** [comment] 2017-01-15 17:49
I fixed it by overwriting the size in the img-element directly:
`<div class="carousel-item active">
          <img class="d-block img-fluid" src="assets/images/slides/slide1.jpeg" alt="First slide" style="width:100%; height:100%">
        </div>`
it works in chrome 55.x, opera 42.x, firefox 50.1x ans Safari on Mac.

**Comment by josmaissan** [comment] 2017-01-16 09:57
You,re right @DeltaOS2, by adding a width- and height style of 100% to **each** `img` it seems to look okay too.

I have made a temporary sample page with 3 situations at http://jossan.home.xs4all.nl/test/carousel-1.html :

carousel 0, as it is in v4.0.0-alpha.6, uncorrected.
carousel 1, with the suggestion of @Jas-n
carousel 2, with the suggestion of @DeltaOS2

**Comment by josmaissan** [comment] 2017-01-21 03:41
**See:
Prevent images in carousel-item to be stretched #21799
Carousel plugin dont save aspect ratio of images #21658**

**Comment by josmaissan** [comment] 2017-02-12 19:26
@mdo Here is a demo of the problem on **desktops** with **i.a. Chrome & Opera** on **JSFiddle**: 
https://jsfiddle.net/josmaissan/5jsonocq/15/

**Comment by mdo** [comment] 2017-04-08 22:29
Closing as dupe of #21658.

**Comment by mdo** [comment] 2017-04-09 04:59
Fixed by #22392

**Closed by mdo** 2017-04-09 04:59 UTC
Labels: css, has-pr, v4
