### ISSUE TITLE
how to stop the modal from refocusing its trigger button after being hidden?

### ISSUE THREAD

**Issue by skoub** [twbs/bootstrap#16688] opened 2015-06-23 16:04 UTC
I need to change the scroll position of the page when i click a button inside a modal. The problem is that on the hide of the modal, it tries to focus the button that showed the modal at the beginning. The line `$this.is(':visible') && $this.trigger('focus')` is responsable of this behavior. The prevent this, I tried to execute `e.preventDefault()` on the show event but the modal is not showing at all.

So how can i prevent this to happen?

```
// MODAL DATA-API
  // ==============

  $(document).on('click.bs.modal.data-api', '[data-toggle="modal"]', function (e) {
    var $this   = $(this)
    var href    = $this.attr('href')
    var $target = $($this.attr('data-target') || (href && href.replace(/.*(?=#[^\s]+$)/, ''))) // strip for ie7
    var option  = $target.data('bs.modal') ? 'toggle' : $.extend({ remote: !/#/.test(href) && href }, $target.data(), $this.data())

    if ($this.is('a')) e.preventDefault()

    $target.one('show.bs.modal', function (showEvent) {
      if (showEvent.isDefaultPrevented()) return // only register focus restorer if modal will actually get shown
      $target.one('hidden.bs.modal', function () {
        $this.is(':visible') && $this.trigger('focus')
      })
    })
    Plugin.call($target, option, this)
  })
```

**Comment by cvrebert** [comment] 2015-06-23 16:30
Approximate duplicate of #16604.

**Closed by cvrebert** 2015-06-23 16:30 UTC
Labels: js
