### ISSUE TITLE
Override `$focus-ring-*` Sass vars

### ISSUE THREAD

**Issue by bluedge** [twbs/bootstrap#38697] opened 2023-06-02 21:21 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Changing these settings (overriding) have no effect, specifically on :focus state of Text inputs
```
$focus-ring-width:      .25rem !default;
$focus-ring-opacity:    .25 !default;
$focus-ring-color:      rgba($primary, $focus-ring-opacity) !default;
$focus-ring-blur:       0 !default;
$focus-ring-box-shadow: 0 0 $focus-ring-blur $focus-ring-width $focus-ring-color !default;
```

### Reduced test cases

Overriden as follow:
```
// scss-docs-start focus-ring-variables
$focus-ring-width 			: 0;
$focus-ring-opacity			: 0;
$focus-ring-color			: transparent;
$focus-ring-blur			: 0;
$focus-ring-box-shadow		: 0 0 $focus-ring-blur $focus-ring-width $focus-ring-color;
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3

**Comment by julien-deramond** [comment] 2023-06-03 08:05
Thanks for opening this issue @bluedge 

I just tried to override the values with the ones from your description, and the focus ring disappears for `:focus` state for text inputs.

For example with:
```scss
$focus-ring-width:      6rem !default;
$focus-ring-opacity:    .5 !default;
$focus-ring-color:      rgba($warning, $focus-ring-opacity) !default;
```
![Screenshot 2023-06-03 at 10 04 17](https://github.com/twbs/bootstrap/assets/17381666/a7fc9856-4507-4623-93f7-a7931e90cd6f)



The override may not be at the right place, have you tried at the same place for example to override a color or something else?

Please try to create a StackBlitz example (or with any other tools) that reproduces your issue.

**Comment by mdo** [comment] 2023-06-06 04:25
Closing due to lack of reply.

**Closed by mdo** 2023-06-06 04:25 UTC
Labels: css, awaiting-reply, v5
