### ISSUE TITLE
Modal scrolling on mobile devices - what is the current state?

### ISSUE THREAD

**Issue by stefek99** [twbs/bootstrap#15852] opened 2015-02-20 10:51 UTC
![gif-modal](https://cloud.githubusercontent.com/assets/249703/6284921/c7312406-b8ed-11e4-9e21-78d3d412089f.gif)

Fiddle: http://jsfiddle.net/stefek99/t6oq2gze/

It was also here:
* https://github.com/twbs/bootstrap/issues/7501
* https://github.com/twbs/bootstrap/issues/3361

Some StackOverflow too:
* http://stackoverflow.com/questions/19060301/how-to-prevent-background-scrolling-when-bootstrap-3-modal-open-on-mobile-browse
* http://stackoverflow.com/questions/9538868/prevent-body-from-scrolling-when-a-modal-is-opened

I think it's a common issue and should be fixed, my solution (after doing some research):
```
body.modal-open {
    position: fixed;
}
```

**Comment by twbs-lmvtfy** [comment] 2015-02-20 10:51
Hi @stefek99!

You appear to have posted a live example (http://fiddle.jshell.net/stefek99/t6oq2gze/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 75, column 7: Stray end tag ```` body ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment] 2015-02-20 20:15
We explicitly mention this in the documentation:
> ## [Modals, navbars, and virtual keyboards](http://getbootstrap.com/getting-started/#support-fixed-position-keyboards)
> ### Overflow and scrolling
> Support for `overflow: hidden` on the `<body>` element is quite limited in iOS and Android. To that end, when you scroll past the top or bottom of a modal in either of those devices' browsers, the `<body>` content will begin to scroll.

---
> my solution (after doing some research):
> `body.modal-open { position: fixed; }`

Note that this has the side-effect of "scrolling" to the top of the page while the modal is open.

**Comment by mdo** [comment] 2015-02-22 02:22
Closing then.

**Closed by mdo** 2015-02-22 02:22 UTC
Labels: css

**Comment by felipe-canaviri** [comment] 2015-12-22 15:58
Hello Bootstrap team,

As mentioned in the issue #7501, this bug should be fixed in the version 3. 

I'm currently using version 3.3.6 and unfortunately the issue can be still be reproduced, similar to the animated picture above. Also, if you use an iPad with iOS 8 by browsing this page https://nakupanda.github.io/bootstrap3-dialog/, you'll be able to reproduce when opening the modal samples showed in the page. Please note that the samples in the page are using Bootstraop 3.3.5.

Despite that this effect is mentioned in the documentation, I wonder if there will be chances to fix the issue since it's really annoying when the modal has its own scrolling. 

Thanks so much in advance for any feedback you can provide.

**Comment by vanflymen** [comment] 2016-03-06 18:42
Why was this closed?

**Comment by cvrebert** [comment] 2016-03-06 20:28
@vanflymen It's a bug in the browsers themselves. We can't do anything about it on our end. It's already mentioned in our documentation as a known issue.

**Comment by cvrebert** [comment] 2016-03-06 20:43
If you want to follow its progress, the browser bug is https://bugs.webkit.org/show_bug.cgi?id=153852

**Comment by g0dlight** [comment] 2016-05-03 21:33
Just run into this bug, Here is my fix:

`$('body').on('touchmove', function(e){`
` if($('.scroll-disable').has($(e.target)).length) e.preventDefault();`
`});`
`$('body').on('shown.bs.modal', function(){`
` $(this).addClass('scroll-disable');`
`});`
`$('body').on('hidden.bs.modal', function(){`
` $(this).removeClass('scroll-disable');`
`});`
