### ISSUE TITLE
Algolia search returns results for docs 4.0

### ISSUE THREAD

**Issue by adaniello** [twbs/bootstrap#26544] opened 2018-05-20 14:53 UTC
Simply, if you search something (eg. "colors") starting by 4.1 docs, results redirect to 4.0 version of documentation (so, in my example, some new class color are missing).

**Comment by sts-ryan-holton** [comment] 2018-05-20 17:40
@adaniello   Already aware of the issue, see => https://github.com/twbs/bootstrap/issues/26441

For a solution, do this:

> open Chrome Devtools, open Application tab and then Application > Clear Storage. Then tap the 'Clear site data' button to wipe service worker storage etc. That'll fix it for you.

**May as well close this issue**

:-)

**Comment by mdo** [comment] 2018-05-20 19:44
Duplicate of #26441.

**Closed by mdo** 2018-05-20 19:44 UTC

**Comment by Turqueso** [comment] 2018-05-30 18:44
I'm having the same issue in Firefox. Tried to clear local storage for Algolia in the doc but the problem remains
