### ISSUE TITLE
NPM install fails

### ISSUE THREAD

**Issue by denvasden** [twbs/bootstrap#19595] opened 2016-03-23 16:08 UTC
Hi, all!

I'm trying to run npm install command in bootstrap folder to have ability to build dist and it doesn't work.

Command line log:

npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v5.9.0
npm ERR! npm  v3.7.3

npm ERR! No compatible version found: read-json@0.1.0
npm ERR! Valid install targets:
npm ERR! 1.0.3, 1.0.2, 1.0.1
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Work\Projects\zapp360\node_modules\bootstrap\npm-debug.log

I've tried to google but the only answer I found is to update NPM.
My version of NPM is 3.7.3 and it is not very old.

Really need help!

**Comment by bmatusiak** [comment] 2016-03-23 16:12
i have came across the same issue

**Comment by arechsteiner** [comment] 2016-03-23 16:33
Caused by https://github.com/uber/npm-shrinkwrap/issues/103

Nothing wrong with your setup. I've spent some time troubleshooting, installing and reinstalling node and npm and finally figured out which package is responsible. I guess this will resolve itself in a short while (hopefully)! I assume this breaks lots of builds all over the world.

**Comment by denvasden** [comment] 2016-03-23 16:38
Hope so!

**Comment by bmatusiak** [comment] 2016-03-23 19:34
https://github.com/twbs/bootstrap/issues/19596#issuecomment-200503219

here is a temp fix that i used

**Comment by cvrebert** [comment] 2016-03-23 20:18
Duplicate of #19596.

**Closed** 2016-03-23 20:19 UTC
