### ISSUE TITLE
input group addon on time input causes bad styling in Chrome

### ISSUE THREAD

**Issue by holotrek** [twbs/bootstrap#22901] opened 2017-06-23 15:02 UTC
When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)

Windows 10

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)

Chrome

- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)

https://codepen.io/evshell18/pen/zzdPZe

The above example on codepen shows how putting an input addon, i.e. ['.input-group .input-group-addon'], to a time input causes it to have extra height, most likely due to the extra native spinner and deletion icon. This does not happen on MS Edge (which has a different method of entering time), or other browsers such as Firefox, that do not have the time input and fall back to text.

**Comment by mdo** [comment] 2017-06-23 18:10
Duplicate of #22894.

**Closed by mdo** 2017-06-23 18:10 UTC
Labels: css, v4
