### ISSUE TITLE
Possibly unintended behavior for modal margins

### ISSUE THREAD

**Issue by mrbodoia** [twbs/bootstrap#21832] opened 2017-01-24 18:35 UTC
In v4-alpha-6, there is some possibly unintended behavior for modal margins. In the current setup, modals have `margin: $modal-dialog-margin` by default (https://github.com/twbs/bootstrap/blob/v4-dev/scss/_modal.scss#L45) and switch to `margin: $modal-dialog-sm-up-margin-y auto` above the small media breakpoint (https://github.com/twbs/bootstrap/blob/v4-dev/scss/_modal.scss#L130).

However, this means that if the small breakpoint is set to be smaller than the max-width of the modal, then the modal will have no margins. In my case, I notice this effect with a small breakpoint of 480, the default modal width of 500, and using the modal code from the documentation:
```
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
```
Under these conditions, when the screen width is between 480px (the small breakpoint) and 500px (the max-width of the modal), the modal has no margins.

This issue can be worked around fairly easily, but it does seem like unintended behavior. It might be better if the modal was guaranteed to have nonzero margin at all breakpoints, rather than just below the small breakpoint.

**Comment by mdo** [comment] 2017-06-18 05:26
Closing as a won't fix—modals saw some style changes to move from width to max-width and I believe they're working as intended now. If not, please comment again with a demo JS Bin and we can revisit.

**Closed by mdo** 2017-06-18 05:26 UTC
Labels: css, v4
