### ISSUE TITLE
Tether-related error in Angular 2 app made with angular-cli

### ISSUE THREAD

**Issue by alvipeo** [twbs/bootstrap#19923] opened 2016-05-17 01:41 UTC
Angular cli projects use system.js and if you try to use Bootstrap 4 (which requires tether) you're in trouble.

1. you can't use 'import "tether"' - this just doesn't work. Bootstrap throws
2. I tried to use it with "script" tag - this makes ng2 app work but tests fail

So it's either your app work or your tests.

Related - https://github.com/HubSpot/tether/issues/177.

**Comment by alvipeo** [comment] 2016-05-17 01:42
Related issues - https://github.com/angular/angular-cli/issues/630
and this one - https://github.com/angular/angular-cli/issues/699

**Comment by cvrebert** [comment] 2016-05-17 16:19
> Bootstrap throws

Please copy-paste the error message you're getting.

> (2) I tried to use it with

Use it with what?

**Comment by alvipeo** [comment] 2016-05-17 17:49
Updated original post.

Tests fail with some weird error but guys from angular team told me that script are not loaded in correct order. I tried to change karma.config and include jquery, tether and bootstrap into it but that doesn't change anything.

**Comment by alvipeo** [comment] 2016-05-17 18:14
If I comment out script tag then I get this:
```
Unhandled Promise rejection: Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)
	    at eval (http://localhost:4200/vendor/bootstrap/dist/js/bootstrap.min.js:7:2417)
	    at eval (http://localhost:4200/vendor/bootstrap/dist/js/bootstrap.min.js:7:10496)
	    at eval (http://localhost:4200/vendor/bootstrap/dist/js/bootstrap.min.js:7:12639)
	    at Object.eval (http://localhost:4200/app/test-app-cli.component.js:17:1)
	Evaluating http://localhost:4200/vendor/bootstrap/dist/js/bootstrap.min.js
	Evaluating http://localhost:4200/app/test-app-cli.component.js
	Evaluating http://localhost:4200/app/index.js
	Evaluating http://localhost:4200/main.js
	Error loading http://localhost:4200/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)(…)
```

**Comment by cvrebert** [comment] 2016-05-17 19:26
Approximate duplicate of #19017. See #17325 for context. Our ES6 modules story is still a work-in-progress at the moment.

**Closed by cvrebert** 2016-05-17 19:26 UTC
Labels: js, v4

**Comment by oh-wo** [comment] 2017-11-04 01:42
A hack to get both tests and the app working is to add `<script>var Tether = {};</script>` to your index.html.
