### ISSUE TITLE
bootstrap-flex "mobile first"/xs columns aren't working unless explicitly declared

### ISSUE THREAD

**Issue by mejobloggs** [twbs/bootstrap#18237] opened 2015-11-13 06:18 UTC
This code works great on normal bootstrap 4 (and 3)

	<style type="text/css">
		.col-sm-4 { border: 1px solid black; }
	</style>

	<div class="row">
		<div class="col-sm-4">aaa aaa aaa</div>
		<div class="col-sm-4">bbb bbb bbb bbb bbb bbb</div>
		<div class="col-sm-4">ccc ccc ccc ccc ccc ccc ccc ccc ccc</div>
	</div>

As expected, you have 3 equal columns until you get down to XS, then you have 3, 100% vertically stacked columns like this:
XS screen without Flex
![nonflex-working](https://cloud.githubusercontent.com/assets/10529756/11139958/459ff150-8a3a-11e5-9749-fce79d2b3c3b.png)

However, when you enable Flex support, SM and up is still fine, but XS is not. This is what you get:

XS screen with Flex
![flex-notworking1](https://cloud.githubusercontent.com/assets/10529756/11139968/5873881e-8a3a-11e5-95dd-20f61ff73ba6.PNG)

Or... if there's enough room to fit more on a line, you will get this:
![flex-notworking2](https://cloud.githubusercontent.com/assets/10529756/11139976/665e2092-8a3a-11e5-8a95-c12f20446bb9.png)

To get the desired column behavior with Flex I have to explicitly declare the XS columns like so:

	<div class="row">
		<div class="col-xs-12 col-sm-4">aaa aaa aaa</div>
		<div class="col-xs-12 col-sm-4">bbb bbb bbb bbb bbb bbb</div>
		<div class="col-xs-12 col-sm-4">ccc ccc ccc ccc ccc ccc ccc ccc ccc</div>
	</div>

Which in XS screen gives us:
![flex-workingwithexplicitxs](https://cloud.githubusercontent.com/assets/10529756/11140036/ef4d0652-8a3a-11e5-8656-f38a9479c751.png)

Can we get it fixed so we don't have to explicitly declare col-xs-12?

**Comment by cvrebert** [comment] 2015-11-13 06:22
Duplicate of #17603. Please search more in the future. Thanks!

**Closed by cvrebert** 2015-11-13 06:22 UTC
Labels: css, v4
