### ISSUE TITLE
Tooltip and Popover made seo-friendly

### ISSUE THREAD

**Issue by world33** [twbs/bootstrap#20365] opened 2016-07-26 11:00 UTC
Hi,
Would it be possible to make both the tooltip and popover components seo friendly in the 4.0 version?
Content/Code ratio is one ranking factor for Google and wasting so much content in popovers or tooltips that are not parsed or read by the Google bot is a pity.
Thanks for considering it.
Fabio

**Comment by patrickhlauke** [comment] 2016-07-26 11:12
dupe of https://github.com/twbs/bootstrap/issues/20364

**Closed by patrickhlauke** 2016-07-26 11:12 UTC
