### ISSUE TITLE
Linux Firefox <select> in modal dialog bug

### ISSUE THREAD

**Issue by nikolas** [twbs/bootstrap#15532] opened 2015-01-09 20:38 UTC
In Firefox 34, Bootstrap 3.3.1, the `<select>` items in modal dialogs aren't behaving correctly.

Here's an example:
http://jsfiddle.net/kmrjmgLm/2/

When I click on the 'B' option, 'A' gets selected. When I click on 'A', nothing happens.

Let me know if this is a duplicate - I searched and couldn't find anything.

**Comment by cvrebert** [comment] 2015-01-09 21:47
What OS are you using?

**Comment by nikolas** [comment] 2015-01-09 21:54
Ubuntu 14.10.

**Comment by cvrebert** [comment] 2015-01-09 22:26
Unable to reproduce on Linux via Sauce Labs. Unable to reproduce on OS X.
Sounds like a gnarly Linux Firefox bug.
* Do `<select>`s in Bootstrap webpages work properly outside of modals?
* Do `<select>`s work properly on non-Bootstrap webpages?

**Comment by nikolas** [comment] 2015-01-09 23:24
Yes, `<select>`s work on Bootstrap pages outside of modals, and on non-bootstrap webpages.

**Comment by cvrebert** [comment] 2015-01-09 23:35
@nikolas Could you please file [Firefox](https://bugzilla.mozilla.org/enter_bug.cgi) and/or [Ubuntu](https://help.ubuntu.com/community/ReportingBugs#Reporting_non-crash_hardware_and_desktop_application_bugs) bugs regarding this? Post the bug link(s) here when you're done. Thanks!

**Comment by nikolas** [comment] 2015-01-10 00:10
@cvrebert I made a Firefox ticket here: https://bugzilla.mozilla.org/show_bug.cgi?id=1120010

**Comment by cvrebert** [comment] 2015-01-10 00:47
Thanks! Closing this in favor of the Firefox bug since:
* This is almost certainly a bug on the Firefox or Linux side.
  * Our JavaScript doesn't do anything with `<select>`s
  * Our basic `<select>` CSS styles are very minimal (the buggy example doesn't even use our "fancy" `.form-control` class), nothing nearly crazy enough to potentially explain this bug.
* [Linux is only unofficially supported by Bootstrap](http://getbootstrap.com/getting-started/#support-browsers)
* This is the only report we've gotten about this bug so far, and the bug doesn't repro on Linux via Sauce, which suggests that only some (hopefully small) subset of Linux systems is affected.

**Closed by cvrebert** 2015-01-10 00:47 UTC
Labels: browser bug

**Comment by nextgenthemes** [comment] 2015-01-10 00:53
The jsfiddle works perfectly here on Ubuntu 14.10 Firefox 34. I think this is probably a thing related to extensions or so rather then a plain fx bug.

**Comment by nikolas** [comment] 2015-01-10 01:18
@nextgenthemes thanks for testing this. I'll try to further isolate this to find out what's going on, and try on other Linux installs. I first encountered this bug in a Django application that I'm working on.

**Comment by hebbian** [comment] 2015-11-01 07:38
Sorry for necrobump, but I still have this bug on my archlinux box with firefox 41.0.2

**Comment by cvrebert** [comment] 2015-11-01 07:54
@hebbian Follow and/or weigh in on the aforementioned Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1120010
