### ISSUE TITLE
iOS10 Safari - modal scrolling behaviour

### ISSUE THREAD

**Issue by SubZane** [twbs/bootstrap#20782] opened 2016-09-25 10:43 UTC
**The bug**
When opening up a modal window on your iphone in safari and scrolling down the modal freeze and the background starts scrolling. This will take som scrolling to reproduce but when you succeed you can reproduce it easily.

**Platforms**
Bug exists in iOS9 and iOS10 on Safari

**How to reproduce**
Use the demo site at [getBootstrap.com#modals](http://getbootstrap.com/javascript/#modals). Open up the modal on your iPhone in Safari. Scroll the modal up and down, trigger the bounce-effect a lot and the modal will freeze and your finger now scrolls the body-element instead.

**Comment by cvrebert** [comment] 2016-09-26 20:28
Duplicate of #14839.
You can CC yourself on and/or comment on https://bugs.webkit.org/show_bug.cgi?id=153852 to let Apple know that people care about the bug.

**Closed by cvrebert** 2016-09-26 20:28 UTC
Labels: browser bug, v3
