### ISSUE TITLE
bootstrap v5 - carousel on mobile touch swipe directions are inverted

### ISSUE THREAD

**Issue by kimmanwky** [twbs/bootstrap#33683] opened 2021-04-19 09:33 UTC
Bootstrap Carousel on mobile touch swipe directions are inverted.

Used bootstrap version - 5.0.0-beta3
`https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css`
`https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js`

**Current behaviour:** 
1. swipe to left, slide/change to preview item
2. swipe to right, slide/change to next item

**Expected behaviour:**
1. swipe to left should go to next item
2. swipe to right should go to previous item

**Proposed solution:**
1. change the touch deviced swiping behaviour according to expected behaviour, or
2. add something like `inverted` properties to enabled **'inverted swipe direction or behaviour'**

**Comment by alpadev** [comment] 2021-04-19 09:40
Duplicate of https://github.com/twbs/bootstrap/issues/33655 https://github.com/twbs/bootstrap/issues/33657
Fixed by https://github.com/twbs/bootstrap/pull/33499

**Closed by alpadev** 2021-04-19 09:40 UTC
