### ISSUE TITLE
Responsive Navbar overflows after after expanding the collapsing

### ISSUE THREAD

**Issue by tomedelliott** [twbs/bootstrap#20845] opened 2016-10-06 11:09 UTC
Hello,

In boostrap 4 alpha 4 collapsed nav bars will overflow text after you expand then collapse them.
If you shrink this page until the nav fully collapses then expand and collapse the menu, when you increase the page width again the menu will overflow elements below.

[Example here](https://jsfiddle.net/j0q6114t/)

Tested with Firefox 49 and chrome 53 on Linux, and IE 11 on windows 7

**Comment by twbs-lmvtfy** [comment] 2016-10-06 11:09
Hi @tomedelliott!

You appear to have posted a live example (https://fiddle.jshell.net/j0q6114t/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* JSFiddle inserts the contents of its "HTML" pane within ```` <body>...</body> ```` tags, so you cannot include your own ```` <body> ```` tag in your JSFiddle.
* line 66, column 7 thru column 12: Start tag ```` body ```` seen but an element of the same type was already open.
* line 98, column 1 thru column 7: Saw an end tag after ```` body ```` had been closed.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by tomedelliott** [comment] 2016-10-06 12:01
I've updated the [jsfiddle](https://jsfiddle.net/j0q6114t/3/) removing the <body> tag

Looks like the problem is a inline style of `height: 0px;` hanging around after the menu has been expanded.

**Comment by twbs-lmvtfy** [comment] 2016-10-06 12:01
Hi @tomedelliott!

You appear to have posted a live example (https://fiddle.jshell.net/j0q6114t/3/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 88, column 17: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-lg-8 col-md-8"` is redundant and can be simplified to `class="col-md-8"`
* line 69, column 21: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by tomedelliott** [comment] 2016-10-06 12:04
[updated jsfiddle](https://jsfiddle.net/j0q6114t/4/)

**Comment by twbs-lmvtfy** [comment] 2016-10-06 12:04
Hi @tomedelliott!

You appear to have posted a live example (https://fiddle.jshell.net/j0q6114t/4/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 69, column 21: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by tomedelliott** [comment] 2016-10-06 12:15
[updated jsfiddle](https://jsfiddle.net/j0q6114t/5/)

**Comment by twbs-lmvtfy** [comment] 2016-10-06 12:15
Hi @tomedelliott!

You appear to have posted a live example (https://fiddle.jshell.net/j0q6114t/5/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 90, column 17: [E029](https://github.com/twbs/bootlint/wiki/E029): Since grid classes apply to devices with screen widths greater than or equal to the breakpoint sizes (unless overridden by grid classes targeting larger screens), `class="col-lg-8 col-md-8"` is redundant and can be simplified to `class="col-md-8"`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by tomedelliott** [comment] 2016-10-06 12:15
[updated jsfiddle](https://jsfiddle.net/j0q6114t/6/)

**Comment by mdo** [comment] 2016-10-10 03:32
Looks like a dupe of #17555.

**Closed by mdo** 2016-10-10 03:32 UTC
Labels: js, v4
