### ISSUE TITLE
Ability to reverse default float direction of columns for RTL

### ISSUE THREAD

**Issue by tim6400** [twbs/bootstrap#20075] opened 2016-06-05 04:53 UTC
Now, by default all columns float to the left, if I want to make it float to right I need to add ''pull-right'' atrr
to every Col or overide the default by css for each size of column. 

So in V4, is it possible to add one variable in the Sass file to control the float direction of all columns size?

**Comment by cvrebert** [comment] 2016-06-05 04:57
What's you use case for this?

**Comment by tim6400** [comment] 2016-06-05 05:07
My language is ''rtl'' so I want my site to be from ''rtl'' as well as the text.
There for I want every column of the row to float to the right by default.
Like I said, my options now is to add class ''pull-right'' to every column.

**Comment by cvrebert** [comment] 2016-06-05 05:14
Since this is regarding RTL, I added a note to #19555 and will close this as an approximate duplicate of #19555.

**Closed by cvrebert** 2016-06-05 05:14 UTC
Labels: css, feature, v4
