### ISSUE TITLE
Bootstrap 4.5.0 SASS error

### ISSUE THREAD

**Issue by jordyvandomselaar** [twbs/bootstrap#31354] opened 2020-07-24 09:37 UTC
We're using Bootstrap `4.5.0` in our SASS project.

We have this `sass` file:

```scss
@import "~bootstrap/scss/bootstrap-grid";
@import "~bootstrap/scss/bootstrap-reboot";
@import "~bootstrap/scss/alert";
@import "~bootstrap/scss/buttons";
@import "~bootstrap/scss/forms";
@import "~bootstrap/scss/nav";
@import "~bootstrap/scss/navbar";
@import "~bootstrap/scss/dropdown";
@import "~bootstrap/scss/utilities/text";
@import "~bootstrap/scss/type";
```

When we try to compile this, we get this error:

> ERROR in node_modules/bootstrap/scss/_root.scss:5:1 Please check validity of the block starting from line #5 [Fatal]

It appears that this piece of code is throwing the error:

```scss
@each $color, $value in $colors {
    --#{$color}: #{$value};
  }
```

We're using the Dart implementation for SASS, version `1.26.10`.

I was unable to create a reproducible example because I keep getting other errors. Please advise.

**Comment by Acharya99** [comment] 2020-07-25 16:02
Try to change the way of importing 
@import '../../../node_modules/bootstrap/scss/bootstrap';
like this, then it should work.
Thanks

**Comment by Deckluhm** [comment] 2020-07-25 21:17
If you can't reproduce the bug on a reduced test case, that probably means there is no bug or the bug is caused by something else that doesn't work well with Bootstrap (another package, your own code...etc.).

Reproducing bugs is a good way for you to confirm it's actually a bug (and if it's not to understand the issue) and for the Bootstrap team to fix it quickly if it's a confirmed bug.

**Comment by jordyvandomselaar** [comment] 2020-07-28 13:49
@Deckluhm it's not that I can't reproduce the error, it's that the repro case has a bunch of unrelated errors so I can't get the reproduction to get to my error :/

**Comment by jordyvandomselaar** [comment] 2020-07-28 13:49
@Acharya99 I'll give that a shot. Thanks!

**Comment by jordyvandomselaar** [comment] 2020-07-29 09:47
@Acharya99 Unfortunately, the same error occurs. Dart SASS is complaining that Bootstrap is using wrong Sass syntax.

**Comment by jordyvandomselaar** [comment] 2020-07-29 11:14
After searching around more, I found [this comment](https://github.com/twbs/bootstrap/issues/24549#issuecomment-347057261).

When I change

```scss
// Do not forget to update getting-started/theming.md!
:root {
  // Custom variable values only support SassScript inside `#{}`.
  @each $color, $value in $colors {
    --#{$color}: #{$value};
  }

  @each $color, $value in $theme-colors {
    --#{$color}: #{$value};
  }

  @each $bp, $value in $grid-breakpoints {
    --breakpoint-#{$bp}: #{$value};
  }

  // Use `inspect` for lists so that quoted items keep the quotes.
  // See https://github.com/sass/sass/issues/2383#issuecomment-336349172
  --font-family-sans-serif: #{inspect($font-family-sans-serif)};
  --font-family-monospace: #{inspect($font-family-monospace)};
}
```

to

```scss
// Do not forget to update getting-started/theming.md!
:root {
  // Custom variable values only support SassScript inside `#{}`.
  @each $color, $value in $colors {
      #{--#{$color}}: #{$value};
  }

  @each $color, $value in $theme-colors {
      #{--#{$color}}: #{$value};
  }

  @each $bp, $value in $grid-breakpoints {
    #{--breakpoint-#{$bp}}: #{$value};
  }

  // Use `inspect` for lists so that quoted items keep the quotes.
  // See https://github.com/sass/sass/issues/2383#issuecomment-336349172
  --font-family-sans-serif: #{inspect($font-family-sans-serif)};
  --font-family-monospace: #{inspect($font-family-monospace)};
}
```

it compiles successfully.

**Comment by jordyvandomselaar** [comment] 2020-07-29 11:25
Related comment: https://github.com/sasstools/sass-lint/issues/1114#issuecomment-544216127

**Comment by Acharya99** [comment] 2020-07-30 04:13
@jordyvandomselaar Is the issue resolved?

**Comment by mdo** [comment] 2020-07-31 04:26
Sounds like an issue in the linter or Sass compiler? If so, perhaps we close this out?

**Comment by XhmikosR** [comment] 2020-08-05 04:38
Our CI builds the CSS with both node.sass and dart and both are passing.

This seems like a configuration issue. So, please make sure you update your tooling to the latest versions. If the issue persists, make a public repo with the minimum required stuff to reproduce.

**Comment by mdo** [comment] 2020-08-05 20:37
Closing per last couple comments.

**Closed by mdo** 2020-08-05 20:37 UTC
Labels: awaiting reply

**Comment by tordans** [comment] 2021-08-11 07:17
>Sounds like an issue in the linter or Sass compiler? If so, perhaps we close this out?

@mdo the issue is still present in Bootstrap 4.5 ATM, the linked ticket on sass-linkt is from 2017 and I cannot see any relevant action since then https://github.com/sasstools/sass-lint/issues/1114#issuecomment-544216592.

This ticket is a year old now.

I think it would be good to find a solution in Bootstrap (4) and not wait any longer for upstream changes. 
Could you reopen the ticket? And do you have a preferred way of solving this?
