### ISSUE TITLE
Arrow out of popover

### ISSUE THREAD

**Issue by alecpl** [twbs/bootstrap#23846] opened 2017-09-06 07:12 UTC
Popover arrow can be placed incorrectly when button on the edge of the screen.
![arrow-issue](https://user-images.githubusercontent.com/546788/30098664-2ce12888-92e3-11e7-9d05-188237188b94.png)
Tested with most recent Bootstrap4 build.

**Comment by Johann-S** [comment] 2017-09-06 07:32
Can you make a CodePen of this issue please ? As it mentionned in our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md)

**Comment by alecpl** [comment] 2017-09-06 07:55
@Johann-S I thought it's obvious, but here you go: https://jsbin.com/horagubehe. See that horizontal as well as vertical position is buggy.

**Comment by Johann-S** [comment] 2017-09-06 08:13
it seem's has a CSS problem because Popper.js position correctly our arrow but our arrow width is too high 🤔 

yes @alecpl but that's easier for us to made a fix with a reproducible bug in live 👍

**Comment by FezVrasta** [comment] 2017-09-06 12:18
@Johann-S: Popper.js already takes care to include the arrow width in its computations (theorically), make sure the most outer arrow element has the right width set.

**Comment by Johann-S** [comment] 2017-09-06 13:15
Thank you so much @FezVrasta 👍 if you want to do that changes do not hesitate

**Comment by alecpl** [comment] 2017-09-07 16:45
Maybe #23820 should be considered first.

**Comment by wojtask9** [comment] 2017-09-07 18:04
Can you check this https://codepen.io/anon/pen/jLjraP ?

**Comment by wojtask9** [comment] 2017-09-07 18:33
I didn't saw #23820 
This PR should fix the issue

**Comment by wojtask9** [comment] 2017-09-07 20:13
I was wrong. #23820 isn't working
https://codepen.io/anon/pen/ZJdLpW (css compiled with popover changes from #23820)

**Comment by Johann-S** [comment] 2017-09-08 11:39
this CodePen : codepen.io/anon/pen/gxNxZw seems fine @wojtask9, isn't it ?

**Comment by wojtask9** [comment] 2017-09-08 15:07
@Johann-S 
Yes.
This pen contains my fix to Popper.js and css popover changes.
I'll make PR when I'll get back home

**Comment by jipexu** [comment] 2017-09-09 10:44
> this CodePen : http://codepen.io/anon/pen/gxNxZw seems fine @wojtask9, isn't it ?

the popover bottom left lost his left border ??

**Comment by wojtask9** [comment] 2017-09-13 11:24
@jipexu 
Something with popper position is wrong. I'm not sure what.

@alecpl 
my PR https://github.com/twbs/bootstrap/pull/23936 that should fix your issues

**Comment by Johann-S** [comment] 2017-11-14 12:12
It seems https://github.com/FezVrasta/popper.js/pull/489 fixe this issue, so when @FezVrasta will ship a new release of Popper.js we'll close this issue :+1:

**Comment by FezVrasta** [comment] 2017-11-14 12:23
Released as v1.12.8

**Comment by Johann-S** [comment] 2017-11-14 15:38
The new release of Popper.js fixe only one part of this issue see : https://codepen.io/Johann-S/pen/qVXEaX

But IMO the first issue is on our CSS here (see the first Popover)

**Comment by FezVrasta** [comment] 2017-11-14 15:43
yes, you still need to perform the changes I described [in this comment](https://github.com/twbs/bootstrap/issues/23846#issuecomment-327465549)

**Closed** 2017-12-27 06:31 UTC
Labels: css, v4
