### ISSUE TITLE
Floating labels in the input group do not fully cover

### ISSUE THREAD

**Issue by eturerer** [twbs/bootstrap#36754] opened 2022-07-16 19:14 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

   <div class="row row-cols-md-4 g-4">

      <div class="col bg-info">
        <div class="input-group">
          <div class="form-floating">
            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="input-model" class="col-form-label">model</label>
          </div>
          <div class="input-group-text">
            <div class="form-check form-switch">
              <input type="checkbox" name="override[model]" value="1" id="input-variant-model" class="form-check-input" /> 
              <label for="input-variant-model" class="form-check-label"></label>
            </div>
          </div>
        </div>
      </div>

      <div class="col bg-warning">
        <div class="input-group">
          <div class="form-floating">
            <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
            <label for="input-model" class="col-form-label">model</label>
          </div>
          <div class="input-group-text">
            <div class="form-check form-switch">
              <input type="checkbox" name="override[model]" value="1" id="input-variant-model" class="form-check-input" /> 
              <label for="input-variant-model" class="form-check-label"></label>
            </div>
          </div>
        </div>
      </div>

    </div>

### Reduced test cases

https://stackblitz.com/edit/bootstrap-5-fnseaq?file=src%2Findex.html

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.0-beta1

**Comment by mdo** [comment] 2022-07-18 00:05
Duplicate of #34513.

**Closed by mdo** 2022-07-18 00:05 UTC
