### ISSUE TITLE
BS5 - Floating Labels + Select - Text is cut off

### ISSUE THREAD

**Issue by JustDoItSascha** [twbs/bootstrap#33711] opened 2021-04-21 08:07 UTC
I couldn't find an open ticket for that, so here it is:

Letters which are going a little bit under the baseline are cut off (like y g j). Screenshot attached.
![image](https://user-images.githubusercontent.com/8389022/115519332-64c84d80-a289-11eb-9e46-145f8ebde248.png)

**Comment by alecpl** [comment] 2021-04-21 09:36
Duplicate of #32672

**Closed** 2021-04-21 11:22 UTC

**Comment by jaxramus** [comment] 2022-06-24 12:14
yeah this is still happening even on the latest version: https://stackblitz.com/edit/hxnclf?file=index.html
