### ISSUE TITLE
File browser not working for non `en` language pages

### ISSUE THREAD

**Issue by ztvMark** [twbs/bootstrap#23612] opened 2017-08-22 05:51 UTC
Bootstrap 4
Chrome Versión 59 And Firefox Last Version
Ubuntu 16.04

File browser No Working
https://getbootstrap.com/docs/4.0/components/forms/#file-browser

Appears in white as in the following image
http://imgur.com/a/sPJgo

Do not see choose file or browse

**Comment by patrickhlauke** [comment] 2017-08-22 07:23
cannot reproduce. displaying fine for me. what browser/OS?

**Comment by ztvMark** [comment] 2017-08-22 16:45
Chrome Versión 59 And Firefox Last Version
Ubuntu 16.04

**Comment by samhoward86** [comment] 2017-08-22 20:01
I'm seeing the same in Chrome Version 60.0.3112.101 (Official Build) (64-bit)

The ::before and ::after CSS selectors are not being rendered.

**Comment by patrickhlauke** [comment] 2017-08-22 20:17
Works for me in Chrome 60.0.3112.101 (Official Build) (64-bit), Firefox, IE 11. So not sure what's going on there...

![capture](https://user-images.githubusercontent.com/895831/29585519-5348a8bc-877f-11e7-93b2-307d4c268c2e.PNG)

**Comment by samhoward86** [comment] 2017-08-22 21:19
This simple codepen doesn't render properly for me.

https://codepen.io/anon/pen/EvLqdq

**Comment by samhoward86** [comment] 2017-08-22 21:28
I added ` lang="en"` to the html tag and it is now rendering the "Browse" text. It is still not displaying the "Choose file..." text.

**Comment by patrickhlauke** [comment] 2017-08-22 21:44
aha, confirmed. seems the CSS is specifically targetting English only

**Comment by samhoward86** [comment] 2017-08-22 22:42
Thanks @patrickhlauke

**Comment by ztvMark** [comment] 2017-08-23 01:42
True if you change lang = "en" it works in Spanish no

**Comment by mdo** [comment] 2017-12-28 18:46
I imagine this still holds true for Beta 3. Thinking about it, we might want to include some default `content` values and then override for the languages. That way, anyone without an explicit `lang` attribute could pick up at least the English version.

**Comment by Borkason** [comment] 2018-01-10 13:06
Does not work for me even with `<html lang="en">`. Best example is https://getbootstrap.com/docs/4.0/components/forms/#file-browser

In Edge I have a working File Browser, but in Firefox 57.0.4 it just looks like this:

![grafik](https://user-images.githubusercontent.com/2971735/34774403-7d858b32-f60f-11e7-9b6f-85f71d49d43d.png)

**Comment by patrickhlauke** [comment] 2018-01-10 15:12
@Borkason that particular thing is likely due to https://github.com/twbs/bootstrap/issues/25112 which has been fixed in the repo already

**Closed** 2018-01-15 07:19 UTC
Labels: confirmed, css, v4
