### ISSUE TITLE
Broken rounded corners for "input-group-prepend" with class "invalid-feedback"

### ISSUE THREAD

**Issue by pranuel** [twbs/bootstrap#25606] opened 2018-02-13 08:52 UTC
Hi,

I want report a **bug** for the class "input-group-prepend" in combination with a div for displaying the "invalid-feedback".

**Actual** behaviour: If you implement this like documented by bootstrap the input's corners to the right are not rounded.
**Expected** behaviour: The corners to the right should be rounded, too.

How to **reproduce** this behaviour:
* go to the bootstrap docs for form validation: https://getbootstrap.com/docs/4.0/components/forms/#custom-styles
* Have a look at the "Username" input group: The top right and the bottom right corners are not rounded

I think this results from the :last-child selector which is used by bootstrap to decide whether or not to use rounded corners for the input.

**Comment by rafalp** [comment] 2018-02-13 09:33
Duplicate of #25110

**Closed** 2018-02-13 20:32 UTC
