### ISSUE TITLE
[v5] skeleton text as placeholder for images and texts

### ISSUE THREAD

**Issue by spahno** [twbs/bootstrap#32560] opened 2020-12-20 14:12 UTC
Hey, what do you think about adding skeleton texts to bootstrap? I really see some useful scenarios, especially for prototyping. 

Feel free to discuss... 😊

<img width="364" alt="skeleton-text" src="https://user-images.githubusercontent.com/56961433/102715300-bc9f7980-42d4-11eb-883d-ecc592a5b38b.png">

Image source: https://ionicframework.com/docs/api/skeleton-text

**Comment by XhmikosR** [comment] 2020-12-20 15:13
Duplicate of #31665

**Closed by XhmikosR** 2020-12-20 15:13 UTC
Labels: feature
