### ISSUE TITLE
Change the default responsive option and merge it inside variants option with  Pseudo-Classes.

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#32071] opened 2020-11-06 15:08 UTC
I am thinking about create a Pseudo-Class Variants like tailwindcss using SASS/SCSS and merge between this option and Utility API in Bootstrap V5

I want to add a new option called variants in Bootstrap V5 Utility API to control Pseudo-Classes like (hover, focus) and more... and remove the default responsive option and add it to variants option.

Here is a simple example of How Utilities Map look like after add this new option:

```
$utilities: () !default;
$utilities: map-merge(
  (
    "float": (
        property: float,
        variants: ('responsive', 'hover', 'focus'),
        //rfs: false,
        //class: null,
        values: left,
        //print: false,
    ),
  ),
  $utilities
);
```
so after you add variants as in option in your Utility it will give you this results after compiling to css.

```
.float-left {
  float: left !important;
}

.hover\:float-left:hover {
  float: left !important;
}

.focus\:float-left:focus {
  float: left !important;
}

@media (min-width: 576px) {
  .sm\:float-left {
    float: left !important;
  }
  .sm\:hover\:float-left:hover {
    float: left !important;
  }
  .sm\:focus\:float-left:focus {
    float: left !important;
  }
}

@media (min-width: 768px) {
  .md\:float-left {
    float: left !important;
  }
  .md\:hover\:float-left:hover {
    float: left !important;
  }
  .md\:focus\:float-left:focus {
    float: left !important;
  }
}

@media (min-width: 992px) {
  .lg\:float-left {
    float: left !important;
  }
  .lg\:hover\:float-left:hover {
    float: left !important;
  }
  .lg\:focus\:float-left:focus {
    float: left !important;
  }
}

@media (min-width: 1200px) {
  .xl\:float-left {
    float: left !important;
  }
  .xl\:hover\:float-left:hover {
    float: left !important;
  }
  .xl\:focus\:float-left:focus {
    float: left !important;
  }
}

@media (min-width: 1400px) {
  .xxl\:float-left {
    float: left !important;
  }
  .xxl\:hover\:float-left:hover {
    float: left !important;
  }
  .xxl\:focus\:float-left:focus {
    float: left !important;
  }
}
```

**Comment by ffoodd** [comment] 2020-11-06 15:58
Duplicate of #31856 and #31639. Please share ideas and thoughts on #31856 (which seems more advanced). Thanks :)

**Closed by ffoodd** 2020-11-06 15:58 UTC
Labels: feature
