### ISSUE TITLE
Add support for light and dark colours in same theme from user preferences

### ISSUE THREAD

**Issue by WHK102** [twbs/bootstrap#32891] opened 2021-01-23 23:25 UTC
By example, using the user preference of darkness in OSX or Gnome, use the default white theme or black slate theme. By example: https://spring.io/projects top switch but atomatic, like as Whatsapp WEB or github: https://youtu.be/5ATR5FKPb_U?t=748

This works on OSX enviroments and Gnome 3.

And please, add reduce motion user preference from css to reduce effects from transitions for epileptic users: https://youtu.be/5ATR5FKPb_U?t=883

**Comment by mdo** [comment] 2021-01-25 19:31
Duplicate of #27514 I think.

We already have reduced motion.

**Closed by mdo** 2021-01-25 19:31 UTC
Labels: feature
