### ISSUE TITLE
Justified Nav template not functional

### ISSUE THREAD

**Issue by bobrast** [twbs/bootstrap#18846] opened 2016-01-11 17:55 UTC
The justified nav template in the Docs/examples folder doesn't work. The justified-nav.css and main bootstrap.css files need something like .nav-justified > li { display: inline-block } and some way to force the individual li elements to fill 100% of the nav div the way the 3.5.x version does.

Without adjustments, the li elements pile up on the left side of the nav div. With the li's set to display inline-block, the elements line up but float left.

**Comment by cvrebert** [comment] 2016-01-11 20:07
Duplicate of #17723. Please search next time.

**Closed by cvrebert** 2016-01-11 20:07 UTC
Labels: css, examples, v4
