### ISSUE TITLE
Utilities.scss - generating 'state' definitions like hover/focus also generates stateless output.

### ISSUE THREAD

**Issue by oobi** [twbs/bootstrap#38149] opened 2023-03-02 01:19 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

There seems to be an issue with the utility API that generates 'state' classes
https://github.com/twbs/bootstrap/pull/31643

The hover/focus state generates fine, but also comes along with the stateless definition like so:

```
.something {}   // <-- this shouldn't be there according to docs
.something:hover{} 
.something:focus{}
```

The additional definition renders the utility useless when trying to set something like a colour change on hover.

I'm running 5.2 but I've tried other 5.x versions in case it was a recent glitch. 

Docs under "States" indicate that the above definition should only produce the :hover output.
https://getbootstrap.com/docs/5.2/utilities/api/

### Reduced test cases

In utilities.scss:
```
$utilities: (
	"hover-bg": (
		property: background-color,
		class: hover-bg,
		state: hover,
		values: $colors,
	)
);
```

This will generate the correct output for the :hover state but also generates duplicate output for the non-hover(?) state, rendering it useless.

Output CSS:
```
.hover-bg-blue {
  background-color: #00539b !important;
}

.hover-bg-blue-hover:hover {
  background-color: #00539b !important;
}
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2, 5.1.3

**Comment by ffoodd** [comment] 2023-03-02 06:28
This is unclear in the docs Indeed, but you're seeing the intended behaviour: `state` and other properties in the Utilities API are meant to extend utilities, without the need to add specific  entries for states, responsive variants, RTL conditions, etc.

To get hover state on `background-color`, you only need to extend existing `.bg-*` utitilies with the `state` property. Would this work for you?

I think the docs need some clarifications regarding properties and how to use them.

**Comment by oobi** [comment] 2023-03-02 06:36
That makes sense. That would probably work for me. My use case was setting different hover colours (bg/text) for buttons.

For example, something like:
btn bg-yellow bg-hover-red text-black text-hover-white 

How does one extend the bg-utilities as you suggest? The docs show how to declare a new util but I'm not clear on how to add 'state' to an existing one. Would you just redeclare the whole shebang? I'm feeding it my colours array rather than the "theme colours".

**Comment by julien-deramond** [comment] 2023-03-02 06:36
@oobi I let you confirm if it would work for you. In the meantime, I'm adding "docs" and "enhancement" labels to this issue so that we try to add some clarifications regarding properties and how to use them.

**Comment by ffoodd** [comment] 2023-03-02 06:49
The docs explain how to extend a utility to [enable responsable variants](https://getbootstrap.com/docs/5.2/utilities/api/#enable-responsive). Adding states is the same, using the `state` property.

**Comment by oobi** [comment] 2023-03-03 00:53
Thanks so much - this worked perfectly. It took me a few tries to find exactly where to import this, but if you're hitting the docs at some stage, it may be worth mentioning that the custom utils need be imported after _utilities.scss and before bootstrap.scss. 

```
// custom variables
@import "variables";

@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";
@import "~bootstrap/scss/utilities";

// custom utilities (must be declared before bootstrap and after BS utilities)
@import "utilities";

@import "~bootstrap/scss/bootstrap";
```


In case this helps some future reader (most likely me when I forget next time), here's the snippet to add hover states to background colours and text colours (bg-primary-hover, text-primary-hover)

```
$utilities: map-merge(
    $utilities,
    (
        // extend existing bg/text classes for hover state
        "background-color":
            map-merge(
                map-get($utilities, "background-color"),
                (
                    state: hover,
                )
            ),
        "color":
            map-merge(
                map-get($utilities, "color"),
                (
                    state: hover,
                )
            ),
    )
);
```

**Comment by julien-deramond** [comment] 2023-03-03 06:34
You might have had issues because you use both exclusive approaches to include Bootstrap Sass files. Based on our [Cutomize > Sass](https://getbootstrap.com/docs/5.2/customize/sass/#importing) docs, it's either `@import "~bootstrap/scss/bootstrap";` ("Include all of Bootstrap"), either including parts of Bootstrap.
I haven't tried in details your use case so maybe it's useful here but it sounded strange to me when I read your last comment.
But this is cool if you succeeded to make it work! Neat!

**Comment by mdo** [comment] 2023-03-04 19:41
Echoing Julien's comments and closing out. I could see us maybe revisiting the states options to provide a `default` that could be optional in some way, such that you could remove the initial non-pseudo element states. Tagging for v6 to consider.

**Closed by mdo** 2023-03-04 19:41 UTC
Labels: docs, enhancement
