### ISSUE TITLE
v4: <a> & <button> .dropdown-item have different font families

### ISSUE THREAD

**Issue by puzrin** [twbs/bootstrap#21614] opened 2017-01-08 17:58 UTC
If you use `<a class="dropdown-item">` and `<button class="dropdown-item">` in the same menu, it's well seen that text dencity is different. Dev tools shows that items have different font faces.

**Comment by mdo** [comment] 2017-01-08 19:00
Dupe of #21588.

**Closed by mdo** 2017-01-08 19:00 UTC
Labels: css, v4

**Comment by puzrin** [comment] 2017-01-08 19:09
Is it possible, that user configures different font for buttons? Does it worth to override it in .dropdown-item for safety?
