### ISSUE TITLE
No Gutter from Container up to col

### ISSUE THREAD

**Issue by Igcorreia** [twbs/bootstrap#21239] opened 2016-11-28 17:53 UTC
Please consider adding:

.no-gutter.row,
.no-gutter.container,
.no-gutter.container-fluid{
  margin-left: 0;
  margin-right: 0;
  padding-left: 0;
  padding-right: 0;
}

.no-gutter>[class^="col-"]{
  padding-left: 0;
  padding-right: 0;
}

**Comment by mdo** [comment] 2016-11-28 18:50
Dupe of #19107 and added in #21211.

**Closed by mdo** 2016-11-28 18:50 UTC
Labels: css, v4
