### ISSUE TITLE
<select> element rendering incorrectly in input-group

### ISSUE THREAD

**Issue by swirlsky** [twbs/bootstrap#24412] opened 2017-10-18 07:52 UTC
I'm using Bootstrap and `<select>` elements on my page without any additional styling and their arrows look ugly if they are parts of an _input-group_. That's how such a `<select>` shows up in Firefox (not much difference in Chrome either):

![image](https://user-images.githubusercontent.com/27681171/31706363-fe4f6828-b3e8-11e7-8156-b0f1260b13d7.png)

And this is how Firefox normally renders a `<select>` element without Bootstrap (or without placing it in an _input-group_):

![image](https://user-images.githubusercontent.com/27681171/31706387-16dfe868-b3e9-11e7-9663-47efa2136ed1.png)

[This fiddle shows the behaviour.](https://jsfiddle.net/0043ozj4/1/)

What causes the issue? Is this a known bug, and if so, are there any workarounds? (I'd rather not use dropdown components instead as it would be hard to configure those as Angular FormControls.)

(OS: Ubuntu 17.04, Browser: Firefox 56.0)

**Comment by alecpl** [comment] 2017-10-18 12:00
This is not `input-group` specific. This is caused by background/border styling in `form-control`.

**Comment by swirlsky** [comment] 2017-10-18 21:20
Thanks for the correction @alecpl . This I can confirm.

I tried toggling the border and background properties of the `<select>` which it inherited from the `form-control` class and it made the arrow change, but it's really hard to tell what coexistence and combination of these properties cause the behaviour.

Should we look at it as a Bootstrap bug, or an accepted issue that won't (and maybe can't) be corrected?

**Comment by alecpl** [comment] 2017-10-19 06:02
Any background or border (including border-radius) change causes this. I think there's no solution.  It worked the same in Bootstrap 3. Maybe there should be a variable that would allow to disable this select styles.

**Comment by mdo** [comment] 2017-10-19 15:26
Can the custom select component be used here?

**Comment by mdo** [comment] 2017-10-23 02:37
Closing as custom select support is coming in #24455.

**Closed by mdo** 2017-10-23 02:37 UTC
Labels: css, v4
