### ISSUE TITLE
Found no color leading for #5e81ac and #bf616a

### ISSUE THREAD

**Issue by thewebartisan7** [twbs/bootstrap#31963] opened 2020-10-25 07:12 UTC
- Operating system and version: macOS
- Compilation issue
- Bootstrap v5-alpha2

For 2 colors I get below warnings in `node_modules/bootstrap/scss/_functions.scss 117:3 color-contrast()`

WARNING: Found no color leading to 4.5:1 contrast ratio against #5e81ac...
WARNING: Found no color leading to 4.5:1 contrast ratio against #bf616a...

The text color for this background color sometime is dark sometime is light.
For example for buttons and bg-* classes are dark, while for badges are light.

**Comment by mdo** [comment] 2020-10-25 19:57
Is this with the default CSS, or something custom you’ve written? We need more context here and a live example ideally.

**Comment by thewebartisan7** [comment] 2020-10-26 07:53
I only change variables, the functions are default from bootstrap.

I can't find on codepen.io bootstrap v5 alpha, so not sure where to add live example, but I can show you live compiled example and below are how to reproduce this.

Main app.scss file that first include variables overrides and then main bootstrap.scss directly from node_modules.

https://gist.github.com/thewebartisan7/f14097a263b1a3db0e0692139d6cc14d

Compiled app.css:

https://gist.github.com/thewebartisan7/bfc4cfa1b04182d02a26604c3ba50086

Demo of result:
http://laravel-ui.laraloop.com/docs/theme

Full error log:

```
$ node_modules/sass/sass.js sass/app.scss dist/app.css
Warning: Found no color leading to 4.5:1 contrast ratio against #bf616a...
    node_modules/bootstrap/scss/_functions.scss 117:3        color-contrast()
    node_modules/bootstrap/scss/mixins/_forms.scss 36:12     form-validation-state()
    node_modules/bootstrap/scss/forms/_validation.scss 10:3  @import
    node_modules/bootstrap/scss/_forms.scss 9:9              @import
    node_modules/bootstrap/scss/bootstrap.scss 23:9          @import
    sass/app.scss 20:9                                       root stylesheet

Warning: Found no color leading to 4.5:1 contrast ratio against #5e81ac...
    node_modules/bootstrap/scss/_functions.scss 117:3      color-contrast()
    node_modules/bootstrap/scss/mixins/_buttons.scss 9:11  button-variant()
    node_modules/bootstrap/scss/_buttons.scss 60:5         @import
    node_modules/bootstrap/scss/bootstrap.scss 24:9        @import
    sass/app.scss 20:9                                     root stylesheet

Warning: Found no color leading to 4.5:1 contrast ratio against #5e81ac...
    node_modules/bootstrap/scss/_functions.scss 117:3       color-contrast()
    node_modules/bootstrap/scss/mixins/_buttons.scss 18:20  button-variant()
    node_modules/bootstrap/scss/_buttons.scss 60:5          @import
    node_modules/bootstrap/scss/bootstrap.scss 24:9         @import
    sass/app.scss 20:9                                      root stylesheet

Warning: Found no color leading to 4.5:1 contrast ratio against #bf616a...
    node_modules/bootstrap/scss/_functions.scss 117:3      color-contrast()
    node_modules/bootstrap/scss/mixins/_buttons.scss 9:11  button-variant()
    node_modules/bootstrap/scss/_buttons.scss 60:5         @import
    node_modules/bootstrap/scss/bootstrap.scss 24:9        @import
    sass/app.scss 20:9                                     root stylesheet

Warning: Found no color leading to 4.5:1 contrast ratio against #bf616a...
    node_modules/bootstrap/scss/_functions.scss 117:3       color-contrast()
    node_modules/bootstrap/scss/mixins/_buttons.scss 18:20  button-variant()
    node_modules/bootstrap/scss/_buttons.scss 60:5          @import
    node_modules/bootstrap/scss/bootstrap.scss 24:9         @import
    sass/app.scss 20:9                                      root stylesheet

Warning: Found no color leading to 4.5:1 contrast ratio against #5e81ac...
    node_modules/bootstrap/scss/_functions.scss 117:3       color-contrast()
    node_modules/bootstrap/scss/mixins/_buttons.scss 77:17  button-outline-variant()
    node_modules/bootstrap/scss/_buttons.scss 66:5          @import
    node_modules/bootstrap/scss/bootstrap.scss 24:9         @import
    sass/app.scss 20:9                                      root stylesheet

Warning: Found no color leading to 4.5:1 contrast ratio against #5e81ac...
    node_modules/bootstrap/scss/_functions.scss 117:3       color-contrast()
    node_modules/bootstrap/scss/mixins/_buttons.scss 80:18  button-outline-variant()
    node_modules/bootstrap/scss/_buttons.scss 66:5          @import
    node_modules/bootstrap/scss/bootstrap.scss 24:9         @import
    sass/app.scss 20:9                                      root stylesheet

Warning: Found no color leading to 4.5:1 contrast ratio against #bf616a...
    node_modules/bootstrap/scss/_functions.scss 117:3       color-contrast()
    node_modules/bootstrap/scss/mixins/_buttons.scss 77:17  button-outline-variant()
    node_modules/bootstrap/scss/_buttons.scss 66:5          @import
    node_modules/bootstrap/scss/bootstrap.scss 24:9         @import
    sass/app.scss 20:9                                      root stylesheet

Warning: Found no color leading to 4.5:1 contrast ratio against #bf616a...
    node_modules/bootstrap/scss/_functions.scss 117:3       color-contrast()
    node_modules/bootstrap/scss/mixins/_buttons.scss 80:18  button-outline-variant()
    node_modules/bootstrap/scss/_buttons.scss 66:5          @import
    node_modules/bootstrap/scss/bootstrap.scss 24:9         @import
    sass/app.scss 20:9                                      root stylesheet

Warning: Found no color leading to 4.5:1 contrast ratio against #5e81ac...
    node_modules/bootstrap/scss/_functions.scss 117:3             color-contrast()
    node_modules/bootstrap/scss/helpers/_colored-links.scss 8:19  @import
    node_modules/bootstrap/scss/_helpers.scss 2:9                 @import
    node_modules/bootstrap/scss/bootstrap.scss 46:9               @import
    sass/app.scss 20:9                                            root stylesheet

Warning: Found no color leading to 4.5:1 contrast ratio against #bf616a...
    node_modules/bootstrap/scss/_functions.scss 117:3             color-contrast()
    node_modules/bootstrap/scss/helpers/_colored-links.scss 8:19  @import
    node_modules/bootstrap/scss/_helpers.scss 2:9                 @import
    node_modules/bootstrap/scss/bootstrap.scss 46:9               @import
    sass/app.scss 20:9    
```

**Comment by patrickhlauke** [comment] 2020-10-26 09:33
you're setting/overriding colours, and the ones you've chosen (`$nord10` and `$nord11`) make it impossible to create sufficiently contrasting variants. not much we can do at bootstrap's end, you'll need to choose stronger colours, or live with the fact that some of the variants/derivations will have insufficient colour contrast

**Comment by thewebartisan7** [comment] 2020-10-26 09:38
@patricker I am not sure to understand. Should not be possible to create color contrast for any colors? I mean this affect the color text of a specific background color. Also why this affects only buttons and badges while not others?

**Comment by thewebartisan7** [comment] 2020-10-26 09:44
Ok, I see now why badges are white while buttons are correctly dark..
Seem that badges doesn't use color-variant but it's always white using variables `$badge-color`

Should not be better to create a color variants also for badges?

Anyway, I am not sure why that warnings appear since all seem correctly working, I think that there was an issues with color text of badges that was not the same as buttons.

Screenshot:

<img width="731" alt="Screenshot 2020-10-26 at 10 41 06" src="https://user-images.githubusercontent.com/57477934/97157307-36553400-1778-11eb-9437-5c7c8bfa9f3f.png">

**Comment by thewebartisan7** [comment] 2020-10-26 09:46
I see now in your docs you are using helper .text-dark, I copy paste code from docs.
<span class="badge bg-secondary  text-dark">Secondary</span>

**Comment by ffoodd** [comment] 2020-10-26 12:18
Warnings aren't errors, they won't prevent you from compiling: it's only here to ensure you get the info—in that case, insufficient contrast.

[Badges do not have variants](https://github.com/twbs/bootstrap/blob/1b6caf69c2ab66bd6d2517845f9165e57cdc5058/scss/_badge.scss): you simply customize them using our `background-color` utilities, that's why you don't have any warning for them. [Buttons on the other hand have variants, processed from a single color](https://github.com/twbs/bootstrap/blob/1b6caf69c2ab66bd6d2517845f9165e57cdc5058/scss/mixins/_buttons.scss) and using [our internal `contrast-color()` function to get the most contrasted color](https://github.com/twbs/bootstrap/blob/1b6caf69c2ab66bd6d2517845f9165e57cdc5058/scss/_functions.scss#L95).

You may override [our contrast related variables](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L85) (such as `$mion-contrast-ratio` or `$color-contrast-dark` / `$color-contrast-light`) but I'd recommend you to better fix your contrast issue (using `.text-*` utilities is fine).

I'm closing this since it's the intended behaviour and I assume per your latest comments that you better understand what's happening, but feel free to step in again if you got questions or anything. :)

**Closed by ffoodd** 2020-10-26 12:18 UTC

**Comment by thewebartisan7** [comment] 2020-10-26 12:42
Yes I know warnings are not errors. I just don't get at first what happen. 

Would be good to have for badges like for alerts where we can define level of backgrounds and colors are darker background color. Soft colors with dark colored text looks better for badge.

But that is another story.

**Comment by ffoodd** [comment] 2020-10-26 12:52
That was [the case in v4](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_badge.scss#L46).
[Dropping this in v5](https://v5.getbootstrap.com/docs/5.0/migration/#badges-1 ) was because simply apply the `background` didn't have any sense ATM, but it could allow to define a foreground color alongside. To be continued, that may be a good thing to tackle (and at least to better document, since it surprised you).

I'll keep that in mind :)

**Comment by thewebartisan7** [comment] 2020-10-26 13:04
I missed that, thanks for info.
I like where bootstrap 5 are moving, by using more utility classes.
And for badge make sense.

But what I mean is that soft background color variant for badges looks better like for alerts.

Check this comparison:

<img width="477" alt="Screenshot 2020-10-26 at 14 00 58" src="https://user-images.githubusercontent.com/57477934/97175594-0a47ac00-1794-11eb-8167-ba199dcc35c4.png">

Following the new way, would be good to have something like .bg-soft-success or similar which could be used for alerts, badges and other things, and can be defined using levels like for alert.

**Comment by ffoodd** [comment] 2020-10-26 14:25
Can be a feature request. Not sure if we'll handle this, but still.

**Comment by motad333** [comment] 2021-08-16 13:14
in bootstrap 5 i solved this warnings by changing $min-contrast-ratio from 4.5 that is default to 2.5
use bellow line in settings.scss and import settings before bootstrap
$min-contrast-ratio: 2.5;

**Comment by patrickhlauke** [comment] 2021-08-16 14:30
the problem, of course, is still there (combinations of foreground/background colours that have insufficient contrast per [WCAG 2.1 SC 1.4.3 Contrast (Minimum)](https://www.w3.org/TR/WCAG21/#contrast-minimum)) ... it's just that you're suppressing the check, effectively. each to their own i guess...
