### ISSUE TITLE
Reboot overwrites .dropdown-item.disabled color when no href.

### ISSUE THREAD

**Issue by SmallhillCZ** [twbs/bootstrap#28666] opened 2019-04-17 14:06 UTC
When using a link without href in dropdown, reboot overwrites grey color by inherit:

![image](https://user-images.githubusercontent.com/1273865/56293038-9f420180-6128-11e9-8781-ea3cccf2695f.png)

CodePen Test Case: https://codepen.io/anon/pen/XQZeev

Versions: 
- Windows 10
- Chrome, version 73.0.3683.103 (Official Build) (64-bit)

**Comment by mdo** [comment] 2019-04-17 19:04
Those anchor styles are by design and have been explained in other issues. Don't have links handy right now, but closing as this isn't a bug right now.

/cc @MartijnCuppens @patrickhlauke We might want to revisit this and just nuke those styles.

**Closed by mdo** 2019-04-17 19:04 UTC

**Comment by patrickhlauke** [comment] 2019-04-17 19:15
the `a:not([href]):not([tabindex])` style is there to make sure anchors (which is what `<a>` without an `href` is) blend in like normal text...but it seems not many people use anchors as anchors anymore. i could imagine removing that rule set for v5 (provided it's explained in the migration guide)
