### ISSUE TITLE
.caret has line down its center in iOS Safari

### ISSUE THREAD

**Issue by Sonic3R** [twbs/bootstrap#17617] opened 2015-09-16 09:36 UTC
I created a button using the following code:

```
<!-- Large button group -->
<div class="btn-group">
  <button class="btn btn-default btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Large button <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    ...
  </ul>
</div>
```
I use bootstrap version 3.3.5

On Safari iOS, looks like: http://i.stack.imgur.com/xi8XQ.png

**Comment by cvrebert** [comment] 2015-09-16 18:07
That looks like iOS Chrome, which we don't support.
Also, we'd need a JS Fiddle or JS Bin that demonstrates the problem.

**Comment by fennec15** [comment] 2015-09-16 19:13
The fonts also fail on Firefox 38.2.0, once anything is changed in the HTML and the page is forced to reload.

**Comment by cvrebert** [comment] 2015-09-16 19:24
@fennec15 Please open a separate issue.

**Comment by Sonic3R** [comment] 2015-09-17 05:48
I solved issue, read my answer from here: http://stackoverflow.com/questions/32460263/bootstrap-fonts-seem-to-be-striped-on-safari-ios

**Comment by fleaflicker** [comment] 2015-10-23 19:33
@cvrebert you can see this on the getbootstrap.com site. As far as I can tell this was caused by 119ce267a60732ba98513e5ed329baa3d866168a .
![image1](https://cloud.githubusercontent.com/assets/682081/10703055/5e18c766-799b-11e5-8442-bc4dacabffb0.png)

**Comment by julmot** [comment] 2015-11-15 14:51
@Sonic3R Thanks, this helped me out.
This should be fixed asap.

**Comment by cvrebert** [comment] 2015-11-25 04:57
X-Ref: https://github.com/zurb/foundation-sites/blob/8ff8ba68f1d1b0b4c6299e0e1e6fee2b5999fcbe/scss/util/_mixins.scss#L14

**Comment by mdo** [comment] 2016-09-05 22:27
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Closed by mdo** 2016-09-05 22:27 UTC
Labels: css, v3
