### ISSUE TITLE
4.5.1 removal of mixin `make-container-max-widths`

### ISSUE THREAD

**Issue by matthewnessworthy** [twbs/bootstrap#31433] opened 2020-08-05 07:40 UTC
Removal of the mixin `make-container-max-widths` causes a SASS exception to be thrown if it's used in custom code.

IMO this should not be included in a patch release and the removal should be clearly documented.

**Comment by Zryru** [comment] 2020-08-05 11:25
Confirming this is happening to us too.

simple to reproduce


>>   @include make-container-max-widths();

   -----------^

**Comment by mdo** [comment] 2020-08-05 16:08
Duplicate of #31436. We'll get a patch out hopefully.

**Closed by mdo** 2020-08-05 16:08 UTC
