### ISSUE TITLE
Modal without `fade` class flickers

### ISSUE THREAD

**Issue by kjdion84** [twbs/bootstrap#24668] opened 2017-11-03 20:53 UTC
Using beta v2 and the latest Chrome in Windows 10, all modals have an ugly flicker for a half second when hiding/showing the modal if they do not have the `fade` class. I do not want the `fade` class, I'd like modals to show/hide instantly.

See this fiddle: https://jsfiddle.net/4rffwu28/

Notice how for a split second when hiding/showing the modal theres some weird flickering action going on. This also wasn't happening with beta v1. I'm not sure what changed in v2 to cause this.

**Comment by asyncdesign** [comment] 2017-11-04 08:31
Windows 10 Home
Version 1703
OS Build 15063.674

Chrome: Version 61.0.3163.100 (Official Build) (64-bit)
Chrome: Version 62.0.3202.75 (Official Build) (64-bit)

Unable to reproduce this issue using the supplied link. Modal shows and hides without flicker.

**Comment by mdo** [comment] 2018-01-04 05:22
Closing given latest comment.

**Closed by mdo** 2018-01-04 05:22 UTC
Labels: v4
