### ISSUE TITLE
In 5.2.0-beta1, the popover is placed incorrectly on the second attempt

### ISSUE THREAD

**Issue by GeorchW** [twbs/bootstrap#36518] opened 2022-06-07 09:14 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I've used the [official example from the docs](https://react-bootstrap.github.io/components/overlays/#overlaytrigger) (more or less) to create a popover, and noted that the placement is incorrect after hovering for the second time. This only occurs in the latest beta (5.2.0-beta1). It's working fine in the latest non-beta version (5.1.3).

~~I'd like to attach a video, but GitHub doesn't want me to do so for some reason. Will try again later.~~ **EDIT:** A video demonstrating the issue in the code sandbox can be found in the comment below.

### Reduced test cases

Here's a code sandbox: https://codesandbox.io/s/dawn-flower-0y6peq

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.2.0-beta1

**Comment by GeorchW** [comment] 2022-06-07 09:16
Now it works, here's the video:

https://user-images.githubusercontent.com/8687777/172343906-87004149-16f1-4769-908a-880fd06a3c2d.mp4

**Comment by tnir** [comment] 2022-07-22 03:29
This regression affects me even in v5.2.0 as well as v5.2.0-beta1. And on https://codesandbox.io/s/dawn-flower-0y6peq, I confirmed that this does not happen with v5.1.3, too. Relevant to #35679 and #36668.

**Comment by GeoSot** [comment] 2022-07-22 07:35
Please, try to update your libraries first to the latest versions and re-try. 
The problem is fixed on 5.2.0 and the  proper bootstrap-react version is the `2.5.0-beta.1`

https://user-images.githubusercontent.com/22406063/180388294-bc2cf0f0-ee66-4c8c-b420-7688f41695b6.mp4

**Closed by GeoSot** 2022-07-22 07:35 UTC

**Comment by tnir** [comment] 2022-07-22 08:02
Thanks.
