### ISSUE TITLE
artifacts with Chrome on Windows

### ISSUE THREAD

**Issue by jackpeters** [twbs/bootstrap#24233] opened 2017-10-04 06:18 UTC
http://jsfiddle.net/1aeur58f/1/

```html
<!-- Button trigger modal -->
<button type="button" id="mymodal" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
<div class="modal-dialog" role="document">
<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
  </div>
  <div class="modal-body">
    ...
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-primary">Save changes</button>
  </div>
 </div>
 </div>
```
![is8uu](https://user-images.githubusercontent.com/12909743/31162317-4f3d3aa2-a8fa-11e7-8634-7f8ac64f375b.jpg)

Hello Bootstrap Team,

I have face issue on bootstrap modal background issue? flickering background pixels.

I have placed StackOverflow for more details below link:
https://stackoverflow.com/questions/46501097/background-pixels-flickering-on-bootstrap-modal

Please update me... if you got any solution...

Thanks,
Jagdish Parmar

**Comment by jackpeters** [comment] 2017-10-04 06:21
Please update me... if you got any solution...

**Comment by Johann-S** [comment] 2017-10-04 07:16
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by emilioRamirez24** [comment] 2017-10-04 17:13
changed .fade.in opacity property on bootstrap.min.css from 1 to 0.99: .fade.in{opacity:0.99}

and that solved the problem while a better solution appears.

**Comment by XhmikosR** [comment] 2017-10-05 07:13
@addyosmani: is this a known issue?

Whoever has this issue: can you please try the beta or canary build and see if the issue happens there too? Chances are it's already fixed.

**Comment by emilioRamirez24** [comment] 2017-10-05 13:32
try this on bootstrap.min.css

.fade.in{opacity:1;-webkit-backface-visibility: hidden;}

**Comment by XhmikosR** [comment] 2017-10-05 13:51
Personally I don't use Chrome on my main machine, but I could test a couple of things with @Johann-S.

Requirements:

* Windows 7 or 10
* Chrome stable (some people reported it happens with beta and canary too in #24258)
* Intel VGA

This results in visual glitches like this one and the ones mentioned in #24258.

Whoever is affected, you should see that the problem goes away if you disable hardware acceleration.

/CC @addyosmani: can we escalate this issue? It seems a lot of people are affected :/

**Comment by bryanspears** [comment] 2017-10-05 17:43
I've been testing this across all browsers and all OS. As reported above, it's only Windows, Chrome, and GPU acceleration enabled.

Has anyone created an upstream bug with Chromium/Chrome?

**Comment by XhmikosR** [comment] 2017-10-05 18:48
@bryanspears: I haven't, but that is why I CC'ed @addyosmani above hoping to speed things up.

Regardless, if you make an issue please comment here with the link.

Thanks!

**Comment by MarcBra** [comment] 2017-10-06 08:19
Same here. This is quite bad... I cannot post a link, unfortunately.
![pixelissue](https://user-images.githubusercontent.com/9166139/31269210-c0ebeb36-aa7f-11e7-9675-f0ab049ef9cb.jpg)

**Comment by smickus** [comment] 2017-10-09 08:22
I managed to workaround this issue by changing .modal-backdrop.show opacity to 1 and background-color to rgba(0,0,0,0.5)

![before](https://user-images.githubusercontent.com/8790849/31329562-6a3b37ae-ace3-11e7-83ec-54054f1cee1b.PNG)
![after](https://user-images.githubusercontent.com/8790849/31329563-6a3b555e-ace3-11e7-8ca5-d643cae32db0.PNG)

**Comment by MarcBra** [comment] 2017-10-09 08:53
That seems to works for me also... Note: _.modal-backdrop.in_ instead of _modal-backdrop.show_ in my case. Thank you!

**Comment by XhmikosR** [comment] 2017-10-09 13:53
Guys, all the "solutions" aren't real solutions, but merely workarounds like the one I mention above about disabling hardware acceleration.

**The issue needs to be reported to Chrome and fixed there.**

So, please don't post such comments, they don't help resolve the issue properly.

**Comment by addyosmani** [comment] 2017-10-11 02:49
Hey folks. Is there a crbug.com bug report filed for this issue that we can chase up on our end? Happy to once there is. It's usually fastest to file there with a reproduction so we can get someone on our graphics teams to take a look (I'm buried in GH issues and didn't see this before I'm afraid).

I'm not otherwise aware of a bug filed for this issue. We have had some reports of color profile related issues with the latest Chrome stable on Windows but this looks completely different.

**Comment by XhmikosR** [comment] 2017-10-11 13:31
@addyosmani: I think this one is related https://bugs.chromium.org/p/chromium/issues/detail?id=770701&q=bootstrap&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by pyrographics** [comment] 2017-10-23 20:44
Chrome for Mac has a similar but difficult to reproduce issue with Bootstrap modals.  I have not tried to reproduce with a bare bones page  but so far have found the issue only occurs when sticky.js is present and seems to only appear when viewed at a medium window size.  This causes a white strip in the center of the page with ghosted content along side the original.

**Comment by XhmikosR** [comment] 2017-10-27 21:20
Closing as per the Chromium bug report.

If anyone has any issues, please report them there.

https://bugs.chromium.org/p/chromium/issues/detail?id=770701#c27

**Closed by XhmikosR** 2017-10-27 21:20 UTC
Labels: browser bug

**Comment by ray73864** [comment] 2017-10-30 08:37
So glad I found this issue posted, I've been going crazy for the last couple of weeks thinking yet another part of my work PC was starting to fail (only had the PC for about 10months). Nice to see it is a Chrome bug, according to the Chrome issue tracker it is fixed in the latest 62 version, so updating to that now.

**Comment by jesben** [comment] 2017-10-30 08:53
I have just tested with v. 62 and the bug is gone :)
