### ISSUE TITLE
Change .nav-tabs to use flex-wrap by default

### ISSUE THREAD

**Issue by Jas-n** [twbs/bootstrap#21681] opened 2017-01-12 13:24 UTC
Currently .nav-tabs uses flex without wrap to display, however when the viewport is narrower than the width of all of the tabs, they overflow.

With flex-wrap as default they'll continue to behave as they did with the previous versions, and flow underneath.

Without flex-wrap
![image](https://cloud.githubusercontent.com/assets/14942820/21891423/7dc0cd90-d8ca-11e6-9485-9dbf749ca0c7.png)

With flex-wrap:
![image](https://cloud.githubusercontent.com/assets/14942820/21891499/db0c48ee-d8ca-11e6-95e3-c914f80a967f.png)

**Comment by mdo** [comment] 2017-01-21 22:22
Dupe of #21660.

**Closed by mdo** 2017-01-21 22:22 UTC
Labels: css, v4
