### ISSUE TITLE
col-sm-5/2/5 doesn't fit on one line in Spartan

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#16316] opened 2015-04-19 19:14 UTC
When you make a row with 2 ```col-sm-5```-divs and one ```col-sm-2```-div, the collumns won't fit on one row, through they do cover 12 rows. The total size of the rows is slightly to big at 100,01%.

**Comment by cvrebert** [comment] 2015-04-19 19:15
What browser and OS are you using?

**Comment by Studio384** [comment] 2015-04-19 20:22
Internet Explorer 11 in Windows 10

**Comment by patrickhlauke** [comment] 2015-04-19 21:43
Do you have a minimal test case as a [JSFiddle](http://jsfiddle.net/), by any chance?

**Comment by cvrebert** [comment] 2015-04-20 19:45
Presumably the example is basically something like http://jsbin.com/papani/1/edit

**Comment by cvrebert** [comment] 2015-04-20 19:48
@Studio384 Windows 10 is currently only available as a preview release. Can you reproduce the problem on any stable version of Windows?

**Comment by cvrebert** [comment] 2015-04-20 19:51
I can't seem to reproduce on Win 8.1 IE11 via Sauce Labs.

**Comment by cvrebert** [comment] 2015-04-20 19:55
@Studio384 Also, what's your monitor's resolution and your browser window's `window.innerWidth` ?

**Comment by patrickhlauke** [comment] 2015-04-20 20:00
Confirming that this happens in IE11/Win10 Preview (10049) when "Enable Experimental Web Platform Features" in about:flags is turned on, as well as Spartan/Win10.

Cannot reproduce in IE11/Win8.1.

![capture](https://cloud.githubusercontent.com/assets/895831/7239250/44c6d1aa-e7a0-11e4-9ca3-83e80180d158.PNG)

**Comment by patrickhlauke** [comment] 2015-04-20 20:26
Flagged with @jacobrossi https://twitter.com/jacobrossi/status/590249609278070784

**Comment by cvrebert** [comment] 2015-04-20 20:33
Closing this since the IE bug has now been reported upstream and we don't support beta/preview versions of OSes or browsers.

**Closed by cvrebert** 2015-04-20 20:33 UTC
Labels: browser bug, confirmed, css
