### ISSUE TITLE
Default Col min-width: 0 affects responsive behavior

### ISSUE THREAD

**Issue by anthonylonergan** [twbs/bootstrap#30852] opened 2020-05-19 03:51 UTC
After upgrading from Bootstrap 4.4 to 4.5 I noticed cards within columns which used to respond responsively when the screen size is made smaller, now become stacked (i.e. overlap).

It appears to be related to a CSS change in 4.5 where the col min-width defaults to 0. https://github.com/twbs/bootstrap/pull/30049

Effect can be viewed in this example by simply changing the CSS bootstrap setting between 4.4.1 (responsive) and 4.5 (stacked) https://codepen.io/alonergan/pen/BaoGqwO 

OS: Win 10
Browser: Chrome Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by alessandromarotta** [comment] 2020-05-19 04:30
There is the same issue here: https://github.com/twbs/bootstrap/issues/30851, opened some hours ago

**Comment by madman-81** [comment] 2020-05-25 08:33
I ran into a similar issue after updating to 4.5. What is a correct/best way to fix it? Or is this a bug in Bootstrap and will it be reverted?

**Comment by alessandromarotta** [comment] 2020-05-25 09:47
@madman-81 you have to set

```
 .col{
   min-width: initial !important;
}
```

**Comment by madman-81** [comment] 2020-05-25 09:50
Yes, I saw on Stackoverflow (https://stackoverflow.com/a/61899064) and I've done that for now. But is it a workaround or solution?

**Comment by alessandromarotta** [comment] 2020-05-25 09:56
It's a patch (solution): "initial" reset to browser initial value.

**Comment by OrangeDog** [comment] 2020-05-27 11:18
This caused all the margins to collapse and images to overlap in this sort of structure
```html
<div class="row no-gutters" id="row">
  <a class="col-lg"><img></a>
  <a class="col-lg"><img></a>
  <a class="col-lg"><img></a>
</div>
```
```css
#row {
  align-items: center;
  margin-left: auto !important;
  text-align: right;
}
#row img {
  margin: 10px 0;
}
```

**Comment by ffoodd** [comment] 2020-06-02 13:54
I digged this a bit, and there're a few things to consider:
1. `min-width: 0;` on `.col` resolves a very uncommon use case, which should be fixed with `.col-6` classes instead of amending the main column class (in [the associated codepen](https://codepen.io/jensluyten/pen/povxyPe), [just use `.col-6` and it works fine (forked pen)](https://codepen.io/ffoodd/pen/yLeBdZp));
2. in [the current issue's codepen](https://codepen.io/alonergan/pen/BaoGqwO), there's also something wrong: hardoced, arbitrary `width` on cards. I know they're coming from the docs, but setting `width` on something contained in a grid is a bit odd. By removing those widths, you get the exact same result with both [4.4.1 (forked pen)](https://codepen.io/ffoodd/pen/wvMwLZg) and [4.5.0 (forked pen)](https://codepen.io/ffoodd/pen/PoZYrLN) — so this might not be a regression, after all. 

To get this current codepen's result in 4.4.1, you should've use the `.col` classes too. This is the best way to control layout.

The current reduced test case should probably not be considered as a regression; **however I presume there are other use cases where this `min-width` has side-effects**, so I'd be in favor of simply dropping this.

@mdo @MartijnCuppens any thought?

**Comment by uvbeenzaned** [comment] 2020-06-05 21:29
I have had major issues with the new min-width setting. I upgraded because I saw it was a minor and I didn't check my app as thoroughly as I would with a bigger update so unfortunately my app made it to production looking like hot garbage on smaller size windows and devices. Hoping to push the min-width: initial !important patch out before customers notice how bad it is. I am in favor of removing this if many more people are having the same issues I am.

**Closed** 2020-06-09 18:49 UTC
Labels: css, has-pr, v4, v5

**Comment by NathanQ** [comment] 2020-07-14 20:59
The .col class `min-width: 0` now breaks the column's layout when contained in a `.row.no-gutters` div when preceded by col-x divs that fill the row's width. It used to lay underneath them. See codepen https://codepen.io/NathanQ/pen/rNxZwox

Thanks for looking!
