### ISSUE TITLE
Precompiled dark version

### ISSUE THREAD

**Issue by fuzzy76** [twbs/bootstrap#28424] opened 2019-03-07 10:02 UTC
Since there are several elements (like the hamburger menu) that won't work with the default settings on a "light text on dark background" scenario without recompiling, would it be possible to offer a precompiled dark version (ie colors inverted)?

**Comment by ysds** [comment] 2019-03-07 11:13
If you mean windows high-contrast mode, this might be duplicate of #21269.

**Comment by fuzzy76** [comment] 2019-03-07 12:20
No, I was talking about website design colors. If you create a site with dark background and light text, every element that has SVG background images set becomes invisible / impossible to see.

**Comment by patrickhlauke** [comment] 2019-03-07 12:43
i think this would be solved more fundamentally by having SVGs use `currentColor` in their styles. however, that doesn't work with background SVGs, and would require foreground `<svg>` (as noted in #21269 )

**Comment by patrickhlauke** [comment] 2019-03-07 12:44
so i think i'd rather spend energy on the fundamental fix, rather than a separate precompiled dark version, tbh

**Comment by mdo** [comment] 2019-03-08 04:37
We won't be providing a prebuilt dark version (although I am messing around with dark mode for our docs with a handful of overrides), but v5 could see some improvements to how we handle SVGs.

**Closed by mdo** 2019-03-08 04:37 UTC
