### ISSUE TITLE
'this' ref not set in function passed as title option in tooltip config

### ISSUE THREAD

**Issue by josephclawrence** [twbs/bootstrap#38846] opened 2023-06-28 17:13 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In the docs, it says 'If a function is given, it will be called with its this reference set to the element that the popover is attached to.' But this no longer seems to be true in 5.3.

Now, I needed to pass an argument to the function, and that argument is a reference to the element that the popover/tooltip is attached to. 

I looked through the internal functions '_resolvePossibleFunction' and 'execute' and this is how it appears to be structured now.

So the docs should be updated to reflect this. 

### Reduced test cases

Uneccessary

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3

**Comment by nwalters512** [comment] 2023-06-28 18:15
I believe this is a duplicate of #38720. I opened #38725 to fix this.

**Comment by julien-deramond** [comment] 2023-06-28 20:27
Closing it as duplicate. @josephclawrence you can follow #38720 to know when and how it's going to be fixed.

**Closed by julien-deramond** 2023-06-28 20:27 UTC
