### ISSUE TITLE
Multiple Tabs can become .active at once

### ISSUE THREAD

**Issue by Manuellama** [twbs/bootstrap#20027] opened 2016-06-03 09:26 UTC
In this page:
http://v4-alpha.getbootstrap.com/components/navs/

And this section:
# **JavaScript behavior**
Use the tab JavaScript plugin—include it individually or through the compiled bootstrap.js file—to extend our navigational tabs and pills to create tabbable panes of local content, even via dropdown menus.

> When you choose a dropdown item, and open the dropdown again and choose another item, both items are selected with class .active. It causes a bug, not being able to choose either of them again.

I think I fixed it here, I commented the lines with Fix 1 and Fix 2 so you can see the two modifications.

https://www.dropbox.com/s/eg235dwr8clpny8/bootstrap.js?dl=0

**Comment by cvrebert** [comment] 2016-06-03 18:45
Duplicate of #17371. Feel free to submit a pull request.

**Closed by cvrebert** 2016-06-03 18:45 UTC
Labels: js, v4
