### ISSUE TITLE
Bootstrap 3.3.7 not published to Atmospherejs

### ISSUE THREAD

**Issue by frco9** [twbs/bootstrap#20450] opened 2016-08-03 15:48 UTC
I can't update my bootstrap meteor package. It seems the last release (3.3.7) was not published to AtmosphereJS ?

**Comment by cvrebert** [comment] 2016-08-03 20:01
Approximate duplicate of #20389. Same underlying cause.

**Closed by cvrebert** 2016-08-03 20:01 UTC

**Comment by frco9** [comment] 2016-08-03 21:25
Ok thanks ! 
Maybe the package.js should be removed from source, so that it would be more explicit that bootstrap is not anymore published on AtmosphereJS.
