### ISSUE TITLE
Double increase carousel interval after click 4.4.1

### ISSUE THREAD

**Issue by RvRedd** [twbs/bootstrap#30219] opened 2020-02-18 00:34 UTC
After manually switching carousel slide interval increases by 1.5-2 times on mobile safari.
Just check for yourself on your manual page — https://getbootstrap.com/docs/4.0/components/carousel/#with-captions
For me, this is a critical problem: I wanted to make carousel like a stories page (instagram / facebook) but the interval is out of sync with the story indicator

**Comment by XhmikosR** [comment] 2020-02-18 17:07
That's a pretty old version. The latest one v4.4.1 https://getbootstrap.com/docs/4.4/components/carousel/#with-captions

**Comment by RvRedd** [comment] 2020-02-18 17:44
Showed the wrong page. I use the latest version on the project.
You didn’t even try it yourself. I will tell in more detail:
Try on an mobile safari scroll forward 5-8 times and calculate how much the interval will be. Usually from 5 seconds it becomes 8-11.

**Comment by XhmikosR** [comment] 2020-02-18 17:45
I don't have such a browser to try and yes, you linked an old version without filling up the needed info.

**Comment by XhmikosR** [comment] 2020-02-18 17:49
So,
as per our guidelines, I need at least the browser/OS versions.

**Comment by RvRedd** [comment] 2020-02-18 17:55
https://www.youtube.com/watch?v=DWUx8E_Lmxk
iOS 13.3.1 iPhone 7 plus
Chrome 80.0.3987.95
Safari 13

**Comment by XhmikosR** [comment] 2020-02-18 18:05
Alright, I reproduced it on BrowserStack. It also happens on master branch (https://twbs-bootstrap.netlify.com/docs/4.3/components/carousel/#with-captions) and seems to happen on >= 4.0. v3.4.1 doesn't seem to have the issue.

Now, why this happens is a mystery to me...

/CC @Johann-S

**Comment by XhmikosR** [comment] 2020-02-18 18:14
v4.0.0-alpha6 doesn't have the issue either. So it must be something in https://github.com/twbs/bootstrap/compare/v4.0.0-alpha.6...v4.0.0#diff-c176963d34a5956a70f8be7623e90a50

**Comment by patrickhlauke** [comment] 2020-02-18 23:44
likely due to the hover-type behavior for touch devices - so that once a user interacts with a carousel, it pauses cycling for twice the duration (so the user gets a chance to actually read/interact with it), similar to what happens with mouse hover https://github.com/twbs/bootstrap/commit/6ae5fb12e6c996a6526250e8cb703b007e4213fc#diff-c176963d34a5956a70f8be7623e90a50

**Comment by patrickhlauke** [comment] 2020-02-18 23:44
(ah, i see that's the same change @XhmikosR pointed to)

**Comment by patrickhlauke** [comment] 2020-02-18 23:46
so, as documented in https://getbootstrap.com/docs/4.4/components/carousel/#options when `pause` is set to `hover`

> If set to "hover", pauses the cycling of the carousel on `mouseenter` and resumes the cycling of the carousel on `mouseleave`. If set to false, hovering over the carousel won't pause it.
>
> On touch-enabled devices, when set to "hover", cycling will pause on `touchend` (once the user finished interacting with the carousel) for two intervals, before automatically resuming. Note that this is in addition to the above mouse behavior.

**Comment by morrissey-ingenious** [comment] 2020-02-19 19:34
@RvRedd - assuming you are playing video content in your carousel you shouldn't be using set intervals on the carousel slide itself but instead you should be listening for the video end and then calling `.carousel('next')`.  using a listener will provide the correct functionality across all devices especially if videos are buffering etc, etc.

**Comment by mdo** [comment] 2021-09-06 22:50
I think we can close this out as a won't fix given the docs mention.

**Closed by mdo** 2021-09-06 22:50 UTC
Labels: js, confirmed, v4, v5
