### ISSUE TITLE
Error in bower.json file bootstrap4v2

### ISSUE THREAD

**Issue by bogdanmir** [twbs/bootstrap#24479] opened 2017-10-20 18:13 UTC
When I try to run the command "bower i", I see this error 

bower bootstrap#^v4.0.0-alpha.6       EMALFORMED Failed to read C:\Users\MURON\AppData\Local\Temp\DESKTOP-C4FMOVN-MURON\bower\ca4c50b905dc21ea17a10549a6f5944f-12648-A0s3u3\bower.json
Additional error details:
Unexpected token @ in JSON at position 0

If I use git://github.com/twbs/bootstrap.git#v4.0.0-alpha.6 (without ^), all good, but if I use git://github.com/twbs/bootstrap.git#v^4.0.0-alpha.6 and try loaded last version I see this error
http://c2n.me/3OL911r

**Comment by myorangeca** [comment] 2017-10-20 18:18
They dropped bower support for beta.2, I am trying to find out how to migrate to NPM. https://stackoverflow.com/questions/46854634/moving-from-bower-to-npm-and-using-main-bower-files

**Comment by Johann-S** [comment] 2017-10-20 18:42
Bower is dead, so we've removed it from v4.

duplicate of #24451

**Closed by Johann-S** 2017-10-20 18:42 UTC

**Comment by jgacuca567** [comment] 2017-10-20 23:14
@myorangeca let me know if you have a challenge migrating to NPM.

**Comment by myorangeca** [comment] 2017-10-20 23:29
@jgacuca567 :( Struggling for the last 3 days on it. I ended up posting a question on stackoverflow (link above). Love to get your support or a hint on the right direction. :)

**Comment by PatrizioR** [comment] 2017-10-23 07:18
@myorangeca 
I had the same issue. I resolved it using following dependencies in package.json (NPM):
"popper.js": "1.12.3",
"bootstrap": "4.0.0-beta.2"

It creates the folder under node_modules\bootstrap\

Be aware using nodejs version >= 6. In Visual Studio 2017 I had to change environment variable priority.
([https://stackoverflow.com/questions/43849585/update-node-version-in-visual-studio-2017](Stackoverflow Update Node Version in Visual Studio 2017)

Hope this solves your migrating problem.

**Comment by phantom2017-Nov** [comment] 2017-11-07 11:32
OK, I just published an article on Medium - with step-by-step instructions on how to add React to your ASP.Net core projects. Check out the article here (includes support for Bootstrap 4.0 Beta 2):

https://medium.com/@csharpsolutionsuk/how-to-use-webpack-in-asp-net-core-projects-a-basic-react-template-sample-25a3681a5fc2

Github repo: https://github.com/phantom2017-Nov/AspNetCore-ReactTemplate

**Comment by 8bitreid** [comment] 2017-11-07 21:03
@Johann-S  if Bower is dead then why is Bootstrap 4.0.0-beta.2 in the bower package manager?

**Comment by Johann-S** [comment] 2017-11-07 21:16
You won't be able to pull Bootstrap beta 2 from Bower 😉
