### ISSUE TITLE
Customizer error

### ISSUE THREAD

**Issue by Wachiwi** [twbs/bootstrap#15922] opened 2015-02-25 16:37 UTC
Since yesterday the [customizer](http://getbootstrap.com/customize/) shows the following error message: 

![error](https://cloud.githubusercontent.com/assets/4199845/6374969/76c0e058-bd14-11e4-9776-2996c75c8892.png)

Until then everything worked well. I'm using Safari 8 on OS X 10.10. If more information is required pls let me know.

**Comment by kkirsche** [comment] 2015-02-25 16:42
Please refer to #14832

Essentially:
"Well, we are aware that it doesn't work, I mean it even says it in the alert.
In Safari (even version 8) attempting to save the generated ZIP directly doesn't work, so FileSaver.js opens the contents up in a new tab as a data URI and you'd need to manually save it which is anything but intuitive. That's why we just disable the customizer completely in Safari."

**Comment by hnrch02** [comment] 2015-02-25 17:10
Closing as a duplicate of #14832.

**Closed by hnrch02** 2015-02-25 17:10 UTC
Labels: customizer
