### ISSUE TITLE
Suspecting a bug in nav component with dropdowns Bootstrap 5

### ISSUE THREAD

**Issue by JOFosuware** [twbs/bootstrap#33318] opened 2021-03-09 14:02 UTC
**I am suspecting a bug in Bootstrap 5 within the nav component implementation.**

I am working on a project of which I am using bootstrap 5, I have taken a snippet of the code and placed in a public github repository, [https://github.com/JOFosuware/bootstrap-5-nav-dropdown-error](url). 

I am trying to use nav component to build the navigation in a vertical position and within I have placed dropdown menus.
The problem is the dropdown menu for the Product button is Add Product, Update Product, and Remove Product. When you select Add Product and again select Update Product the navigation stacks, the two menus become highlighted (active) and selection becomes impossible again until page refresh. This can be seen in the simple version of the project [https://github.com/JOFosuware/bootstrap-5-nav-dropdown-error](url).
![Error OseeEA](https://user-images.githubusercontent.com/54850965/110481227-3e868e00-80df-11eb-9b9b-de023cf67594.png)

The reason I suspect it to be a bug is I have done that with Bootstrap 4 and it worked good with no issue like the above described. The link to a simplify version of the project code with bootstrap 4 is [https://github.com/JOFosuware/good-with-bootstrap-4](url)
I will be glad if this report is taken close look and the version of bootstrap work on if found true as described.

**Operating system and version**
- Windows 10 Enterprise  Version	20H2 (64-bit)

**Browser and version** 
- Microsoft Edge Version 88.0.705.81 (Official build) (64-bit)

**The project with bootstrap 5**
- [https://github.com/JOFosuware/bootstrap-5-nav-dropdown-error](url)

**The project with bootstrap 4**
- [https://github.com/JOFosuware/good-with-bootstrap-4](url)

**Comment by korki43** [comment] 2021-03-10 17:51
You are using one id multiple times. The `id` of an element must be unique. If it's not it'll cause a lot of trouble. In the second row you're even using `product-lg-nav` for almost every list item. I think this will be the cause.

**Comment by XhmikosR** [comment] 2021-03-16 06:44
Closing per the above comments, thanks @korki43!

**Closed by XhmikosR** 2021-03-16 06:44 UTC

**Comment by JOFosuware** [comment] 2021-03-16 12:37
Hi @korki43,
I do understand that I used one id for multiple div tags but I don't think that is causing the problem. I have corrected and used single ids for individual tags but the problem still persist.
I don't know whether you tried correcting to see if it worked but I think this issue show be taken close look at.
Check my repo to see the correction at [https://github.com/JOFosuware/bootstrap-5-nav-dropdown-error](url)
It will really help if this issue is taken close look at. Thank you.

**Comment by korki43** [comment] 2021-03-19 11:23
@JOFosuware please have a look at the documentation for this feature: [Nav Tabs in Bootstrap v5](https://getbootstrap.com/docs/5.0/components/navs-tabs/#javascript-behavior).

It's currently not supported to have tabs inside a dropdown, beacuse there's no good way to use a WAI ARIA pattern for it. You could write some custom JavaScript to remove the `active` class from one tab when anotherone is clicked.

> Note that dynamic tabbed interfaces should not contain dropdown menus, as this causes both usability and accessibility issues. From a usability perspective, the fact that the currently displayed tab’s trigger element is not immediately visible (as it’s inside the closed dropdown menu) can cause confusion. From an accessibility point of view, there is currently no sensible way to map this sort of construct to a standard WAI ARIA pattern, meaning that it cannot be easily made understandable to users of assistive technologies.

> As a best practice, we recommend using `<button>` elements for the tabs, as these are controls that trigger a dynamic change, rather than links that navigate to a new page or location.

**Comment by JOFosuware** [comment] 2021-03-19 11:32
Ok thanks @korki43 ,
I do understand it now, I will work around with javascript as you have advised.
