### ISSUE TITLE
Document when/how to override Modal's enforceFocus

### ISSUE THREAD

**Issue by ocxers** [twbs/bootstrap#20603] opened 2016-09-01 01:34 UTC
OS: OS X v10.11.6
Browser: Firefox v48.0.1
Bootstrap: v3.3.7
Description: if there is no modal, the input box can get focus; if clicks the button "Launch demo modal", the input box can not get focus any more.
Note: The modal should be high enough to show the vertical scrollbar.
JSBin: [https://jsbin.com/xegenuzuve/edit?html,css,js,output](https://jsbin.com/xegenuzuve/edit?html,css,js,output)

**Comment by cvrebert** [comment] 2016-09-01 03:56
Approximate duplicate of #12142. The workaround is to override the `$.fn.Modal.prototype.enforceFocus` method.
#19850 tracks improving `enforceFocus` in v4.
We aren't likely to try to change v3 here, since it's in maintenance-mode, but the workaround is worth finally documenting properly, so recategorizing this as a documentation issue.

**Comment by ocxers** [comment] 2016-09-01 04:58
$.fn.modal.Constructor.prototype.enforceFocus = function() {};

Thanks.

**Comment by mdo** [comment] 2016-09-05 22:36
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Comment by mdo** [comment] 2016-09-05 22:36
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Closed** 2016-09-05 22:37 UTC
Labels: docs, v3
