### ISSUE TITLE
Modal focus on form input scrolls body rather than modal in android

### ISSUE THREAD

**Issue by yellow-beard** [twbs/bootstrap#15160] opened 2014-11-17 22:05 UTC
In Android Chrome browser, open a bootstrap modal that has several form fields, or some text and a form field near the bottom. Click on the last text input field, while it is near the bottom of the browser viewport. The android keyboard pops up. The body of the document (behind the modal) scolls, but the modal itself doesn't scroll - so the input field is hidden behind the keyboard. 

In IOS this does not appear to be a problem, and the modal scrolls as it should.

Example (you need to use an android): http://jsbin.com/hoheberomo/2/

**Comment by cvrebert** [comment] 2015-02-28 05:45
* @yellow-beard Duplicate of #9667?
* What about Chrome on Android 5.x?
* I was unable to reproduce with http://jsbin.com/xirofi/5 on my Nexus 10 running Android 5.0.2 and Chrome 40, although that could be due to the screen size. Yes, the keyboard covers the input, but the browser zooms rather than scrolling, and I think I've seen keyboard-covers-the-input problems like that on many sites and even on iOS. The browsers' behavior when they summon their keyboards is mediocre in general.

**Comment by yellow-beard** [comment] 2015-03-18 18:07
Yes I think this is a duplicate of #9667
I can reproduce on a nexus 5, with chrome 40.0.2214.109 and Android 5.0.1

**Comment by mdo** [comment] 2015-03-26 04:23
Anything to do here?

**Comment by spyksoftware** [comment] 2015-03-26 04:32
Bump.
Would be great if this could be fixed. We feel it's a very real usability
issue.

Tim
www.avaza.com

**Comment by cvrebert** [comment] 2015-03-26 04:48
@mdo Close as a duplicate, I guess.

**Comment by mdo** [comment] 2015-03-26 07:50
Punting as a won't fix in v3.

**Closed** 2015-03-26 07:50 UTC
Labels: css

**Comment by zires** [comment] 2015-06-30 12:02
Still got problem in ios8
