### ISSUE TITLE
dropup is covered by navbar

### ISSUE THREAD

**Issue by mariusa** [twbs/bootstrap#31244] opened 2020-07-06 08:36 UTC
Dropup is covered by navbar:

![Screenshot from 2020-07-06 11-28-31](https://user-images.githubusercontent.com/1283842/86572839-27a20180-bf7c-11ea-8a51-baeb4756692c.png)

### Steps to reproduce the bug

1. Go to https://v5.getbootstrap.com/docs/5.0/components/dropdowns/
2. Scroll page to have some space between "Dropup" button and navbar, as in screenshot. Too less space will open dropup down instead of up (which is good)
2. Click on "Dropup"
4. See drop-up covered by navbar

If the problem seems minor: we're using https://bootstrap-vue.org/docs/components/form-datepicker#form-datepicker
which has all controls covered by navbar.

### Expected behavior

Dropup should be on top of navbar.
Changing z-index of dropdown from 1000 to 10000 fixes this. I'm not sure of the best way to make it future-proof.

### Versions

**Libraries:**

- Bootstrap 5 alpha

**Environment:**

- Browser: Chrome 83

**Comment by mdo** [comment] 2020-07-08 17:57
Having our subnav above this is by design, so closing as a won't fix. Thanks!

**Closed by mdo** 2020-07-08 17:57 UTC
