### ISSUE TITLE
Tooltip flickers while inside .table-responsive

### ISSUE THREAD

**Issue by simPod** [twbs/bootstrap#26836] opened 2018-07-09 15:48 UTC
When using Tooltips inside .table-responsive, they flicker as can be seen on this [codepen example](https://codepen.io/anon/pen/oMvdpY).

It can be fixed by placing `overflow: visible` on `.table-reponsive` but that breaks table's responsivity.

**Comment by simPod** [comment] 2018-07-09 18:39
I solved it by changing `{ boundary: 'window' }` but shouldn't the default value then be reconsidered?

**Comment by alecpl** [comment] 2018-07-10 07:01
The default value change is also a solution for #25428.

**Comment by Johann-S** [comment] 2018-07-10 08:52
You found the solution and it's not a bug so I'll close this issue too

**Comment by simPod** [comment] 2018-07-10 09:04
But it is a bug when used with table responsive. 

The thing that I was able to solve it doesn't mean it is not a bug. 

The bug is something that behaves not according to the specification. And the specification states that tooltip is created and steadily visible when the underlying object is hovered. But in this case tooltip flickers. So it is a bug.

**Comment by Johann-S** [comment] 2018-07-10 09:15
Yep but under the hood if you use our Tooltips/Popovers or Dropdown, you use Popper.js, so you have to dig in Popper.js documentation and find a solution to your problem, which isn't the common use case.

At least we can add a callout in the `.table-responsive` to help folks

**Comment by FezVrasta** [comment] 2018-07-16 04:18
There's an open issue on Popper.js to make the default value even smarter, that should also fix this annoyance, but there's not any ETA unfortunately.

**Closed** 2018-07-20 23:36 UTC
Labels: docs, v4

**Comment by warmwhisky** [comment] 2019-03-14 10:38
> I solved it by changing `{ boundary: 'window' }` but shouldn't the default value then be reconsidered?

Hey would you let me know where I use `{ boundary: 'window' }` I am currently having this issue and absolutely need responsive tables.

**Comment by simPod** [comment] 2019-03-14 11:06
@warmwhisky check my PR https://github.com/twbs/bootstrap/pull/26844

**Comment by warmwhisky** [comment] 2019-03-14 11:15
> @warmwhisky check my PR #26844
Thank you :)

**Comment by cjsteven** [comment] 2019-09-11 08:07
Hi guys I tried to put some media query in table-responsive. Like table-responsive-lg. It worked for me. I do hope also it might help you.
