### ISSUE TITLE
Dont see placeholder in form-control input

### ISSUE THREAD

**Issue by rorc** [twbs/bootstrap#23355] opened 2017-08-12 09:18 UTC
Version 4.0.0-beta.
Browser: Firefox 54.0.1

Dont see placeholder http://joxi.ru/D2PBPzGcdWkONr

**Comment by Johann-S** [comment] 2017-08-12 17:13
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by rorc** [comment] 2017-08-12 20:08
https://jsfiddle.net/rorc/1njk3yr1/1/

**Comment by mdo** [comment] 2017-08-12 20:36
Closing as a duplicate of #23209.

**Closed by mdo** 2017-08-12 20:36 UTC
Labels: css, v4
