### ISSUE TITLE
Bootstrap Carousel touch swipe

### ISSUE THREAD

**Issue by MrShishi** [twbs/bootstrap#33688] opened 2021-04-19 15:59 UTC
i used this example:

```
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators btn_rounded_mycss">
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
      </div>
      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000">
          <img src="../img/foto/primo/img1.jpg" class="d-block w-90 mycss" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="10000">
          <img src="../img/foto/primo/img2.jpg" class="d-block w-90 mycss" alt="...">
        </div>
        <div class="carousel-item" data-bs-interval="10000">
          <img src="../img/foto/primo/img3.jpg" class="d-block w-90 mycss" alt="...">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

```
the swipe is reverse, when i swap left the img went right and viceversa in Mobile devices.
and
Can i make pc devices swipe the images ?
sorry for my english, i hope you can understand.

**Comment by GeoSot** [comment] 2021-04-19 21:46
Duplicate of #33655 #33657, #33683
Fixed by #33499

**Closed by GeoSot** 2021-04-19 21:46 UTC

**Comment by MrShishi** [comment] 2021-04-21 14:10
i am new at github, i still dont get it, how do i fix it ?

**Comment by alpadev** [comment] 2021-04-21 17:28
> i am new at github, i still dont get it, how do i fix it ?

Just wait for the next release. It will be fixed by this.
