### ISSUE TITLE
card-header class doesn't work anymore

### ISSUE THREAD

**Issue by mejakm** [twbs/bootstrap#36887] opened 2022-08-02 10:28 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In the new version of bootstrap 5.2 the class card-header doesn't work as before and it aligns the headers in the top left corner and the colors change as well

header with v5.1.x
![image](https://user-images.githubusercontent.com/14975302/182352995-97a2a821-ae7b-42a1-a5b9-4186c48e3d53.png)

header with v5.2.x
![image](https://user-images.githubusercontent.com/14975302/182353060-5d8567f7-5811-4f6d-a5f4-f175f99d6641.png)

### Reduced test cases

```html
          <div class="card-header">
            <div class="row toolbar">
              <div class="col">
                <span
                  id="card-layers"
                  class="icon-layers"
                  style="color: #a5a7aa"
                ></span>
              </div>
....
```

### What operating system(s) are you seeing the problem on?

Windows, macOS

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

5.1.3 and 5.2.0

**Comment by louismaximepiton** [comment] 2022-08-03 09:31
I can't reproduce this use case on my side, could you provide a reduced test case on StackBlitz, Codepen, JsBin, ...

**Comment by mdo** [comment] 2022-08-06 15:57
Without a live reproducible test case, we can't help, so closing out for now.

**Closed by mdo** 2022-08-06 15:57 UTC

**Comment by mejakm** [comment] 2022-10-12 11:17
> Without a live reproducible test case, we can't help, so closing out for now.

@mdo found out what the problem is

the new classes in card-header 
https://github.com/twbs/bootstrap/commit/e342142b61aacc187c776052bde93e414eb25db7
This padding classes:
![image](https://user-images.githubusercontent.com/14975302/195328230-178633e1-aae7-4c21-9335-3d0d3e4090a5.png)

The result on my project with bootstrap 5.0.0.:
![image](https://user-images.githubusercontent.com/14975302/195328723-480e1fe3-fb2a-4e0c-a2a9-3140dcbec8f8.png)
card header: 
![image](https://user-images.githubusercontent.com/14975302/195328840-0bfdcb4e-a110-4474-9323-769e4d44f808.png)


same project same element but bootstrap 5.2.2.
![image](https://user-images.githubusercontent.com/14975302/195329072-74400b3e-249e-4b3c-8d92-c1632c528218.png)

card header:
![image](https://user-images.githubusercontent.com/14975302/195329116-8841e4a0-06db-4893-a9f9-013335ad4b7c.png)
