### ISSUE TITLE
Is it a mistake? Bootstrap.css line 4492 in class .navbar-right 

### ISSUE THREAD

**Issue by Windstep** [twbs/bootstrap#18475] opened 2015-12-08 11:25 UTC
margin-left should be 0 instead of -15, I believe. Reason for that: page with it becomes scrollable by width (x) and makes different widgets to overflow the screen.

**Comment by kkirsche** [comment] 2015-12-08 12:03
The negative margins offset the margins applied by `.container` Because it does not go within a row.

**Comment by cvrebert** [comment] 2015-12-08 12:19
@Windstep Line number references aren't clear unless you say what release version or git commit of Bootstrap that you're using.

**Comment by Windstep** [comment] 2015-12-08 12:51
@cvrebert, I'm using version 3.3.6 of it. From official site.

**Comment by lachlanjc** [comment] 2015-12-08 18:30
@Windstep You're referring to https://github.com/twbs/bootstrap/blob/181f76f115a35c03c5e7629af670fea144ee25dd/dist/css/bootstrap.css#L4492, correct? /cc @cvrebert

**Comment by cvrebert** [comment] 2015-12-09 02:38
Duplicate of #18355.

**Closed by cvrebert** 2015-12-09 02:38 UTC
Labels: css
