### ISSUE TITLE
Navbar expand breaks at 767px

### ISSUE THREAD

**Issue by mhverbakel** [twbs/bootstrap#24137] opened 2017-09-27 09:59 UTC
The layout breaks at exactly 767px wide screens. The easiest example is the documentation.
1. Go to https://getbootstrap.com/docs/3.3/css/#responsive-utilities-tests in Chrome or Firefox.
2. Use the emulator to limit your screen width to 766 pixels (height is not relevant).
3. Scroll to the green checks that show which sizes are shown and hidden (it's under Test cases).
4. Check that the page works as intended (e.g. there are at least some green checks visible).
5. Increase the screen width to 767 pixels.
6. Check that the page breaks (e.g. there are no more checks for visible or hidden).
7. Increase the screen width to 768 pixels.
8. Check that the page works as intended (e.g. there are green checks visible again).

My OS is Windows 10, I've been able to reproduce this on different machines using Chrome and Firefox (I was unable to reproduce this on MS Edge).

I think this is a browser issue, but it happens in multiple browsers, so this might be another issue. (I narrowed it down to 'media queries under 768 are exclusive, media queries above 767 are inclusive', and I have a minimal html/css test page if needed). Is there a way Bootstrap can work around this issue?

In case you cannot reproduce step 6, this is what it looks like on my PC:
![image](https://user-images.githubusercontent.com/11353785/30907633-70bb5756-a37b-11e7-9ab7-2cc290040d20.png)

Possibly related issues: #18845, #15787

**Comment by mhverbakel** [comment] 2017-09-27 10:00
In case you cannot reproduce step 6, this is what it looks like on my PC:
![image](https://user-images.githubusercontent.com/11353785/30907633-70bb5756-a37b-11e7-9ab7-2cc290040d20.png)

**Comment by mhverbakel** [comment] 2017-09-27 10:14
Possibly related issues: #18845, #15787

**Comment by Johann-S** [comment] 2017-09-27 10:28
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by mhverbakel** [comment] 2017-09-27 12:30
Okay, then let me provide an example of the same issue in v4.

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M"
    crossorigin="anonymous">
</head>

<body>
  <!-- START OF THE IMPORTANT CODE -->
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container">
      <a class="navlink">Always visible</a>
      <a class="d-none d-md-block navlink">Sometimes visible</a>
    </div>
  </nav>
  <!-- END OF THE IMPORTANT CODE -->
</body>

</html>
```

If you make the screen 766 or 767 pixels wide, the layout should be equal. If you make it 768 (or bigger), the layout must be switched. However, because of my issue, the navbar already gets padding at 767 pixels, although it should get it at 768 pixels.

The line in the CSS that causes this is this line:
```css
@media (max-width: 767px) {
  .navbar-expand-md > .container,
  .navbar-expand-md > .container-fluid {
    padding-right: 0;
    padding-left: 0;
  }
}
```

Note, moving this number to 768 is not a solution.

**Comment by Johann-S** [comment] 2017-09-27 12:35
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by mhverbakel** [comment] 2017-09-27 12:44
Bootstrap version: 4.0.0-beta by MaxCDN
Browser: Chrome 61.0.3163.100 (64-bits) / Firefox 55.0.3 (64-bits)
OS: Windows 10 (if you want, I can provide the list of installed updates or something like that)

Steps to reproduce:
1. Open https://output.jsbin.com/qigutefeti
2. Use the responsive testing utility from the inspector to change the width to 766, 767 and 768 pixels. Watch the padding on the "Always visible" menu item.

**Comment by XhmikosR** [comment] 2017-09-28 06:55
@andresgalante: can you reproduce? It is possible the navbar-expand is using the wrong mixin thus being off by 1 pixel.

**Comment by andresgalante** [comment] 2017-09-28 14:30
Hi @XhmikosR I've tested this one and I have a few comments:

- @mhverbakel you've added a `.container` inside `nav-bar` The way you use containers is [outside the navbar](https://getbootstrap.com/docs/4.0/components/navbar/#containers).

- This kind of issues on 1px differences always happen when we use max-width instead of min-width. Since bootstrap is mobile first it should always use min-width, and I think we do.

To be honest I was not able to reproduce the issue, but next steps I think is to review media queries and see where we use max-width and test it out better. What do you think?

**Comment by mhverbakel** [comment] 2017-09-28 14:51
Hello @andresgalante,

Second example on your link: "When the container is within your navbar, its horizontal padding is removed at breakpoints...", so the container should go in the navbar.

The only reason I put it there, is to show that `max-width: 768px` is broken for screens with width 767px. Not only in bootstrap v4, also in boostrap v3.3.

I have an HTML page which shows the issue more clearly:
```html
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
<style>
body {
    background-color: black;
    color: white;
}

@media screen and (max-width: 769px) {
    body { background-color: blue; }
}

@media screen and (max-width: 768px) {
    body { background-color: red; }
}

@media screen and (max-width: 767px) {
    body { background-color: orange; }
}

@media screen and (max-width: 766px) {
    body { background-color: green; }
}

@media screen and (max-width: 765px) {
    body { background-color: black; }
}
</style>
</head>
<body>
<p>Test the range 765px - 770px width.</p>
</body>
</html>
```

As a matter of fact, I couldn't reproduce this on my current laptop (Windows 7), and I couldn't reproduce it on another Windows 10 laptop. So that's 2 devices with the issue, and 2 devices without the issue.

Until the root cause of this issue is found, I think media queries for maximal 767px should be avoided.

**Comment by andresgalante** [comment] 2017-09-28 14:57
@mhverbakel you are right, I missed the second paragraph, sorry :(

I am testing this on out

**Comment by andresgalante** [comment] 2017-09-28 15:08
Ok, it's really hard to debug something I can't see but as @mhverbakel mentions, if you have your grid media queries set up with `min-width` and the breakpoints of `.nav-expand` set up in max-width here:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L149

There is a 1px point, when things are not max nor min, and strange things happen.

@mhverbakel @XhmikosR If it's ok with you guys, I can try work on a version of nav-bar that uses only min-width. Although I can't reproduce the bug, the new version will be as functional as the one we have now. What do you guys think?

**Comment by mhverbakel** [comment] 2017-09-28 16:01
Hello @andresgalante,

I believe the setup for reproducing this is a Windows 10 device with 125% display scaling.

Commenting on your idea to migrate to min-width: I will check if this would resolve the issue (because I haven't tested the edge case for min-width yet).

Kind regards (and thank you in advance),
Martijn Verbakel

**Comment by andresgalante** [comment] 2017-09-28 16:44
So... I've took a deeper look at this one. Although using `max-width` is not ideal to do mobile first, I don't think that the logic of the navbar is wrong.

I've been pushing it to see any bug and I couldn't, I guess I need a windows machine. I'll leave the min-width change on my todo list to explore a better way to implement the navbar, but for now I think we should be ok with what we have.

Thanks a lot Martijn for bringing this up, it was fun to digg into this part of the codebase.

**Comment by mhverbakel** [comment] 2017-09-30 08:05
I think I've narrowed this down to a browser bug in Chrome and Firefox on Windows 10 with 125% scaling of the screen. The next part of the question: should bootstrap work around this?

**Comment by XhmikosR** [comment] 2017-10-01 07:52
I think it's a browser bug. We should try and find tickets and add those to the wall of bugs.

**Comment by patrickhlauke** [comment] 2017-10-02 19:00
not looked deeply at this, but sounds like this is related to min-, max- and their shortcomings when it comes to fractional values? https://github.com/w3c/csswg-drafts/pull/1083/files

**Comment by mhverbakel** [comment] 2017-10-03 04:50
No, because screen width 767 would then fall into max-width 767px, but it doesn't. This is a different issue.

Kind regards,
Martijn Verbakel

**Comment by patrickhlauke** [comment] 2017-10-03 05:00
when working with a zoom of 125%, you never get an exact viewport width of 767. you'll be in the sub-pixel value range, where the fact that min- and max- have that 1px no-man's land area will kick in, no?

**Comment by mdo** [comment] 2017-10-03 20:53
Closing as a won't fix if this is about page zooming. Please commend and we can re-open if we need to address anything else.

**Closed by mdo** 2017-10-03 20:53 UTC
Labels: browser bug, css, v4

**Comment by mhverbakel** [comment] 2017-10-03 21:08
This is not about page zooming, this is (maybe) about having a scaled desktop (which is default in Windows 10).

**Comment by patrickhlauke** [comment] 2017-10-03 23:16
@mdo note we won’t be able to just close issues on zoom grounds, as dpr will have similar/same effect and that’s not within user’s control

**Comment by patrickhlauke** [comment] 2017-10-03 23:16
@mdo note we won’t be able to just close issues on zoom grounds, as dpr will have similar/same effect and that’s not within user’s control

**Comment by mhverbakel** [comment] 2017-10-04 06:16
@patrickhlauke The CSS spec speaks of inclusive ranges for those values, but the browser apparently treats it as an exclusive range: If I test with simple CSS selectors, every 4th pixel works as expected, and in between it matches against `max-width: $width + 1`.

I also validated that this is only the case in an 1.25dppx environment.

**Comment by patrickhlauke** [comment] 2017-10-08 16:02
> The CSS spec speaks of inclusive ranges for those values, but the browser apparently treats it as an exclusive range

the "inclusive" part means that they include that exact value, not that they also include any decimal/fractional value. so interpret `max-width` as meaning `<=`. 768 is <= 768, but 768.25, 768.50, 768.75 are *not* <= 768

**Comment by mhverbakel** [comment] 2017-10-08 16:11
That sounds like the issue being shown here. The solution for this is to ban either `max-width` or `min-width`. I believe v4 almost always relies on `min-width`, so this is just something that needs to be checked.

**Comment by patrickhlauke** [comment] 2017-10-08 16:16
@mhverbakel no, "banning" use of `max-width` or `min-width` is not the solution. again, see https://github.com/w3c/csswg-drafts/pull/1083/files

only solution, while browsers still don't support range context queries, is to modify the values use for the min/max comparisons to include higher precision (e.g. checking for `max-width: 767.99` rather than `max-width:767` or similar)

**Comment by mhverbakel** [comment] 2017-10-08 16:34
I've confirmed that checking for `max-width: 767.99` indeed fixes the issues. Could this also be a patch deployed for v3 please?

**Comment by patrickhlauke** [comment] 2017-10-08 17:40
See https://github.com/twbs/bootstrap/pull/24299. As for v3, that's now in maintenance mode, so there are unfortunately no plans to roll out these sorts of changes there.

**Comment by MatinT-SA** [comment] 2021-07-03 09:23
guys. i have the same issue and i used both min-width and max-width and it's not working properly. i'm using bootstrap 3.3.7 version and i have exactly the same issue of @mhverbakel when i scale down to 767px.
it's ok at 768px and also 766px but exactly at "767px", suddenly the whole page breaks and unfortunately there is nothing i can do about it. does anybody have the same issue and what are the possible ways to solve this?
thanks

**Comment by patrickhlauke** [comment] 2021-07-03 12:51
i'd suggest either updating to a more recent version of bootstrap, or applying the suggested fix above manually to your old copy of bootstrap.
