### ISSUE TITLE
wrong padding at input-group-lg > input-group-addon

### ISSUE THREAD

**Issue by yasinkocak** [twbs/bootstrap#18334] opened 2015-11-24 22:35 UTC
when u use input-group-lg sizing and add span with input-group-addon will get wrong padding.

See documentation: http://v4-alpha.getbootstrap.com/components/input-group/#sizing

**Comment by cvrebert** [comment] 2015-11-25 00:02
Duplicate of #17035 / #18083. Please search more before opening an issue in the future. Thanks.

**Closed by cvrebert** 2015-11-25 00:02 UTC
