### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by icpblog** [twbs/bootstrap#17747] opened 2015-10-01 06:14 UTC
I have a site that uses getbootstrap, my google ranking was perfect, it showed all the pages, etc.. Now I switched to getbootstrap and google switched the pages to the actual homepage of the site and will not show any of the actual pages in the search results besides the homepage, why is this?

EDIT: It also does it on other search engines, it use to pop the pages up until I switched to getbootstrap, now it does not and it only shows the homepage which made me loose views. Why is it doing this?

**Comment by cvrebert** [comment] 2015-10-01 06:25
No idea. Bootstrap usage per se shouldn't affect this (it's just CSS and JavaScript after all). Perhaps you made some other change at the same time you switched to Bootstrap and that's what caused the change in Google's results.
Closing since there's no further assistance we can offer regarding this.

**Closed by cvrebert** 2015-10-01 06:25 UTC

**Comment by patrickhlauke** [comment] 2015-10-01 07:02
The only thing I can think of is: did you switch your site from having all your pages as separate files to using a tabbed interface http://getbootstrap.com/javascript/#tabs which effectively makes all your pages just one single page? If so, that's your issue there...

Beyond that, I can confirm what @cvrebert said: whether or not you use Bootstrap will not affect the way Google and co. see and rank your site.

**Comment by cvrebert** [comment] 2015-10-01 07:12
> whether or not you use Bootstrap will not affect the way Google and co. see and rank your site.

Well, adding our suggested viewport meta tag might help get a site labeled as ["mobile-friendly"](http://googlewebmastercentral.blogspot.com/2015/04/rolling-out-mobile-friendly-update.html), but that's a positive thing and not related to this case, where the pages are apparently getting indexed differently (or not at all).
