### ISSUE TITLE
d-*-block doesn't apply on <button> with btn class

### ISSUE THREAD

**Issue by pejmanchatrrooz** [twbs/bootstrap#26321] opened 2018-04-17 09:39 UTC
# BS-4.1
As in title you can see, d-*-block doesn't apply on `button` tag with `btn` class, but it'll applies on `<a class="btn"...`
and I tried to use `<input class="btn d-md-block" type="submit" ...`, and the same result happend.
How can I manage this? I'm sure we need responsive displays for buttons too.

**Comment by mdo** [comment] 2018-04-17 15:34
Duplicate of #20617.

You need to change `display`, `width`, and `text-align` I believe for the `<button>` element.

**Closed by mdo** 2018-04-17 15:34 UTC

**Comment by pejmanchatrrooz** [comment] 2018-04-17 15:47
but if I wanted to use css, I didn't post an issue here :-|

**Comment by mdo** [comment] 2018-04-17 17:33
@pejmanchatrrooz The issue was closed because we have an open feature request that would accomplish this with responsive `.btn-block-*` classes. We don't currently have this, and a single class chance doesn't do enough for the buttons. You can manually do all most of these things with classes though: `btn d-md-block text-md-center`. The `width` one might need custom CSS or inline styles though as we don't have responsive classes for those.
