### ISSUE TITLE
Docs don't show latest version

### ISSUE THREAD

**Issue by zadam** [twbs/bootstrap#29658] opened 2019-11-09 17:12 UTC
Google search results often point to 4.0 version of the documentation which is fine, but then dropdown on the top does not show latest versions:

![image](https://user-images.githubusercontent.com/617641/68532342-577d0480-031c-11ea-99c3-c9ec5fe0fa59.png)

**Comment by midzer** [comment] 2019-11-09 17:28
This might be linked to https://github.com/twbs/bootstrap/issues/29406

**Comment by florianlacreuse** [comment] 2019-11-10 13:58
On old BS4 docs there is a warning section on the top of the page: "There's a newer version of Bootstrap 4!", with a link.

**Comment by zadam** [comment] 2019-11-10 17:14
That link leads to a homepage which is not very useful.

**Comment by XhmikosR** [comment] 2019-11-11 07:45
Yeah, this is a duplicate of #29406.

**Closed by XhmikosR** 2019-11-11 07:45 UTC
