### ISSUE TITLE
rtl versions

### ISSUE THREAD

**Issue by hooman-pro** [twbs/bootstrap#16455] opened 2015-05-10 16:38 UTC
hi first i should say bootstrap is the best responsive framework, and big thanks from bootstrap and twitter.

but one big problem that we have with it is:
bootstrap is ltr and it have not rtl version support by bootstrap
but some iraninan pepole do it. such as http://www.webdesignermag.ir/download/473/ that you see it's 3.1.1 version, but now 3.3.4 released.
for solving this problem , I have an offer to crate an ability in http://getbootstrap.com/customize for download rtl version for rtl language pepole.
with respect hooman mirghasemi.

**Comment by cvrebert** [comment] 2015-05-10 21:19
Duplicate of #14510. Please search next time.
See also #15509.

**Closed by cvrebert** 2015-05-10 21:19 UTC
Labels: feature
