### ISSUE TITLE
Row doesn't apply media queries on mobile devices and displays all in block style

### ISSUE THREAD

**Issue by mensur-durakovic** [twbs/bootstrap#30884] opened 2020-05-23 11:45 UTC
- Operating system and version (Windows, macOS, Android, iOS)
- Browser and version : Chrome,  81.0.4044.138 (Official Build) (64-bit)

Grid works on all other devices, but on mobile it's not even showing media queries. 

I want all divs to be visible of tablet, laptop or larger devices, but on mobile I want to hide Staff and phone number.

It displays everything in block style on mobile, I don't know why.

Template is copied from Bootstrap's official site.

```html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <h1>Hello, world!</h1>
	
	<div class="row table-row">
		<div class="col-md-1 col-xs-1">
			<img src="https://mdbootstrap.com/img/Photos/Avatars/avatar-5.jpg"
				class="rounded-circle z-depth-0" alt="avatar image" height="35" />
		</div>

		<div class="col-md-3 col-xs-5">Felecia Burke</div>
		<div class="col-md-2 d-none d-sm-block">Staff</div>
		<div class="col-md-3 d-none d-sm-block">+1 (070) 123-4567</div>
		<div class="col-md-2 col-xs-4">example@mail.com</div>
		<div class="col-md-1 col-xs-1">
			<i class="fas fa-ellipsis-h table-row-menu"></i>
		</div>
	</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
```

**Comment by ske66** [comment] 2020-05-23 16:20
Can't reproduce. I tested this using Google Chrome and viewing the page as iPhone X. Staff and phone number are no longer visible but are visible when viewing the page as iPad

**Comment by herbalite** [comment] 2020-05-24 03:40
Check in your mobile that you don't have the option Desktop View on.

**Comment by ffoodd** [comment] 2020-06-02 13:03
@herbalite Please refer to our [grid documentation](https://getbootstrap.com/docs/4.5/layout/grid/), there are a few mistakes in your markup:
1. there's no `.col-xs-*` utilities,
2. grid is mobile-first, meaning you start for mobile and override for upper breakpoints.

[I forked your Pen](https://getbootstrap.com/docs/4.5/layout/grid/) to fix those, and am probbaly getting close to what you want. Could you please check and confirm?

**Comment by herbalite** [comment] 2020-06-02 14:29
@ffoodd 

Seems you choose the wrong person to answer to. I am not the one who created this report :)

**Comment by ffoodd** [comment] 2020-06-02 14:36
@herbalite Fixed, thanks; and sorry!

**Comment by mdo** [comment] 2020-06-13 02:55
Thinking this is a case of incorrect markup. Closing as your `col-xs-*` classes should be `col-*` instead, which seems to fix the issues I saw. Please comment with a live demo of any further issues and more details if not.

**Closed by mdo** 2020-06-13 02:55 UTC
Labels: awaiting reply
