### ISSUE TITLE
different heights for btn/textbox in input-group-lg sizing class example 

### ISSUE THREAD

**Issue by bhutaninitin** [twbs/bootstrap#17914] opened 2015-10-13 18:29 UTC
The button and textbox in first example in http://v4-alpha.getbootstrap.com/components/input-group/#sizing do not seem to have the same height

**Comment by cvrebert** [comment] 2015-10-13 18:56
Duplicate of #17386. Please search more in the future.

**Closed by cvrebert** 2015-10-13 18:56 UTC
