### ISSUE TITLE
Responsive Table is not rendered

### ISSUE THREAD

**Issue by quicktsi** [twbs/bootstrap#17999] opened 2015-10-21 02:53 UTC
I am using Bootstrap v3.3.5 and Chrome Version 46.0.2490.71

Refer to page below. Half of table is not rendered. There is horizontal scroll bar shown at the bottom.

Check http://www.quicktransportsolutions.com/carrier/california/trucking-companies.php 

Issue is reproduced on desktop.

Did anyone face this issue?

Gary

**Comment by quicktsi** [comment] 2015-10-21 05:46
I fixed website with workaround.

+++++++++++++++ Before +++++++++++++
<div class="table-responsive">
        <table class="table table-condensed table-striped table-hover table-bordered">
        <tbody>
++++++++++++++++++++++++++++++++++
I removed table-responsive in div class.
+++++++++++++++ After the fix +++++++++++++
<div>
        <table class="table table-condensed table-striped table-hover table-bordered">
        <tbody>
++++++++++++++++++++++++++++++++++

That's workaround but still requires fix as table will not be responsive.

Gary

**Comment by cvrebert** [comment] 2015-10-21 17:38
@quicktsi 
* Please post your not-working example as a JS Fiddle or JS Bin.
* What OS are you using?
* A screenshot of the problem would also be appreciated.

**Comment by quicktsi** [comment] 2015-10-22 17:57
You can view issue at http://www.quicktransportsolutions.com/carrier/bstraptableissue.html

Issue is reproduced on Windows and Linux.

**Comment by cvrebert** [comment] 2015-10-22 18:29
<img width="555" alt="shot" src="https://cloud.githubusercontent.com/assets/419884/10674489/feaf4b2e-78af-11e5-8327-37b6ba2f40d3.png">

> Half of table is not rendered. There is horizontal scroll bar shown at the bottom.

Because the nested column that you put the `.table-responsive` inside is fairly narrow, hence there's only enough room to show a portion of the table. The whole point of `.table-responsive` is that it cuts off the portion of the table that doesn't fit and adds a horizontal scrollbar to view the rest.

Closing as "Working as Intended".

**Closed by cvrebert** 2015-10-22 18:29 UTC
Labels: css, v3

**Comment by cvrebert** [comment] 2015-10-22 18:32
Additionally, I note in passing that the `align` HTML attribute used in the example is obsolete; see https://wiki.whatwg.org/wiki/Presentational_elements_and_attributes
