### ISSUE TITLE
Custom file input label overflows input

### ISSUE THREAD

**Issue by bbbenji** [twbs/bootstrap#27630] opened 2018-11-08 10:50 UTC
- 4.18.16-arch1-1-ARCH #1 SMP PREEMPT Sat Oct 20 22:06:45 UTC 2018 x86_64 GNU/Linux
- Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)
- [Reduced test case](https://jsfiddle.net/bbbenji/aq9Laaew/266303/)

When the label for a custom file input is too long, it overflows the input. 

![screenshot_20181108_113928](https://user-images.githubusercontent.com/1678118/48193550-fe664380-e34a-11e8-9dfd-44eb651ae6fd.png)

A quick solution is to set `label {overflow: hidden;}`

![screenshot_20181108_114347](https://user-images.githubusercontent.com/1678118/48193804-a5e37600-e34b-11e8-97a9-c478b9dc4257.png)

However this presents a new problem when `label {font-size: <1rem;}`

![screenshot_20181108_114334](https://user-images.githubusercontent.com/1678118/48193798-a11ec200-e34b-11e8-9ddc-4df06f29a877.png)

You might ask why you would put such a long label if no one is going to see the whole thing anyway. But this use case can apply when the window is resized horizontally or a script is used which updates the label with the name of the selected file.

EDIT: Looks like best solution is to add the `.text-truncate` to the given label.

**Comment by bbbenji** [comment] 2018-11-08 12:36
You can just add `.text-truncate` to the label, no need for the span.

Thanks for showing me that class.

**Comment by Johann-S** [comment] 2018-11-08 13:10
Closed as duplicate of: #26933

**Closed by Johann-S** 2018-11-08 13:10 UTC
