### ISSUE TITLE
Failed to decode downloaded font [bower-asset/bootstrap v3.3.5] 

### ISSUE THREAD

**Issue by duynguyen0511** [twbs/bootstrap#16708] opened 2015-06-25 21:43 UTC
since upgrading to bower-asset/bootstrap v3.3.5 (via composer update), I got in Chrome Console

```js
Failed to decode downloaded font: /assets/edae1c82/fonts/glyphicons-halflings-regular.woff2
Failed to decode downloaded font: /assets/edae1c82/fonts/glyphicons-halflings-regular.woff
Failed to decode downloaded font: /assets/edae1c82/fonts/glyphicons-halflings-regular.ttf
```

Bower-asset/bootstrap v3.3.4 does not have above warnings

Below is the Screenshot showing diff between v3.3.4 and v3.3.5

![2015-06-25_1329](https://cloud.githubusercontent.com/assets/436950/8363734/3da91cc6-1b3e-11e5-9e95-ef58e49f8a4f.png)

**Comment by cvrebert** [comment] 2015-06-26 02:26
What's `bower-asset/bootstrap`? [`twbs/bootstrap`](https://packagist.org/packages/twbs/bootstrap) is our Composer package.

Perhaps this is related to our `main` change in #16359?

**Comment by cvrebert** [comment] 2015-06-26 22:52
`bower-asset` seems to refer to https://github.com/francoispluchino/composer-asset-plugin . So yes, this seems to be a duplicate of #16359.

Presumably the "downloaded fonts" that are failing to decode are actually 404 error pages or something.
The Glyphicons font files themselves weren't changed between v3.3.4 and v3.3.5.

**Closed by cvrebert** 2015-06-26 22:52 UTC
Labels: meta
