### ISSUE TITLE
Popover dismiss on next click failing on iOS

### ISSUE THREAD

**Issue by jholt1** [twbs/bootstrap#19848] opened 2016-05-05 16:06 UTC
Your example does not work on ios http://getbootstrap.com/javascript/#dismiss-on-next-click

I have seen that there was a discussion about it before (https://github.com/twbs/bootstrap/issues/15935#issuecomment-76694397), however it seems to be not resolved

**Comment by jeffmcnabb** [comment] 2016-05-05 19:02
Was just looking in to this issue as well. Have been unable to get this working in Mobile Safari, and then realized even the GetBootstrap demo was failing as well.

**Comment by jeffmcnabb** [comment] 2016-05-05 19:05
@jholt1 I would suggest changing the name of this to something like "Popover dismiss on next click failing on iOS", the current title seems too generic.

**Comment by RyanZim** [comment] 2016-05-05 20:58
Possible duplicate of #16028.

**Comment by cvrebert** [comment] 2016-05-08 07:46
@RyanZim Indeed. Closing as duplicate.

**Closed by cvrebert** 2016-05-08 07:46 UTC
