### ISSUE TITLE
Dropdown menu dynamic position

### ISSUE THREAD

**Issue by imami** [twbs/bootstrap#15949] opened 2015-03-01 02:05 UTC
Currently in Bootstrap 3.3.1 Dropdown menu always appears
below the `dropdown button`.

the problem is when the offset of dropdown button from the bottom of page
is less than drop-down-menu's height.
in such case, the menu will be half-displayed.

Currently the ralated CSS is:
<code> .dropdown-menu: {top:90%;} </code>
the bootstrap.js file should check, if bottom-offset is less than drop-menu's height
this shoud be set to:
<code> .dropdown-menu: {bottom:90%; top:inherit;} </code>

so simple :)

here is the screenshot from latest [Bootstrap Demo](http://getbootstrap.com/components/#btn-dropdowns)

![image](https://cloud.githubusercontent.com/assets/638917/6429121/387c6340-bfd4-11e4-956b-2c35c398aa29.png)

**Comment by cvrebert** [comment] 2015-03-01 02:25
Duplicate of #10756.
You can manually flip the expansion direction of the menu from downwards to upwards using `.dropup`; see https://github.com/twbs/bootstrap/blob/3173efd9d96ae54992057df9259725d5732f5629/docs/_includes/components/button-dropdowns.html#L276

**Comment by imami** [comment] 2015-03-01 02:46
I'm talking about when you're scrolling the page.
also when you, as a coder, cold not be sure if
drop-button is on top of page and the list is outside from top of viewport
or drop-button is on bottom of page and the list is outside from bottom of viewport...

also i'm not talking about my own code.
YES, I can use my own script and fix this, as I already have the solution.

I'm talking about Bootstrap.js [ lines 766 - 797 ]
this could be fixed by some calculation in document.outerheight and offset.top.
maximum 2 lines of extra code. :)


btw, thanks for fast reply.

**Closed** 2015-03-01 02:52 UTC
Labels: feature, js
