### ISSUE TITLE
Feature Request: Stacked Notifications with Auto and Manual Dismissal in Bootstrap

### ISSUE THREAD

**Issue by caioalvesbraga** [twbs/bootstrap#40731] opened 2024-08-15 02:11 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal
Provide a new feature in Bootstrap called "Stacked Notifications" that allows users to easily create, manage, and dismiss multiple notifications that are stacked vertically on the screen.

- **Notification Stacking:** Notifications will appear stacked on top of each other in the top-right corner of the screen, with the newest notification appearing at the top.
- **Automatic Dismissal:** Notifications can be configured to automatically dismiss after a set amount of time.
- **Manual Dismissal:** Each notification will include a close button that allows users to manually dismiss notifications.
- **Clear All Notifications:** Provide a method to clear all active notifications at once.

### Motivation and Context
**Benefit:**

This feature enhances user experience by providing a streamlined way to manage multiple notifications on a webpage. Users can quickly see and respond to notifications without them overlapping or being missed.

This feature is especially useful for:

- **Web Applications:** Where multiple notifications may need to be displayed simultaneously, such as error messages, success alerts, or user prompts.
- **Improving Accessibility:** Helps users who might be overwhelmed by multiple pop-ups or dialogs by providing a clear, organized notification system.
- **User Control:** Users can easily manage notifications without being distracted by multiple elements on the screen.

**Targeted Use Cases:**

- **Developers:** Can easily integrate a notification system without building one from scratch.
- **Users:** Who need to manage alerts and messages efficiently in a clutter-free way.
- **Websites:** That require real-time updates, such as dashboards, admin panels, or e-commerce sites.

By implementing this feature, Bootstrap can offer a robust notification management system that improves user interaction and accessibility.

**Comment by louismaximepiton** [comment] 2024-08-19 07:59
Hey there, thanks for your contribution.

I feel like the feature request your asking for is partially existing already with [Toasts](https://main--twbs-bootstrap.netlify.app/docs/5.3/components/toasts/#stacking) (with autohide option set to false or a long delay) using the right [placement](https://main--twbs-bootstrap.netlify.app/docs/5.3/components/toasts/#placement) on the Toast container.
So if I understand well, you are asking for a "dismiss all" button that would remove all the Toasts inside a given container. To my understanding, something like this plugged on a button would do the trick. I don't know if we really need this:
```js
document.getElementById('toast-container').children.forEach(child => {
  Toast.getOrCreateInstance(child).hide();
});
```

Might also be a duplicate of #38424.

**Closed** 2024-09-03 00:16 UTC
Labels: feature, awaiting-reply
