### ISSUE TITLE
In v5.3 Floating label having "::after" Pseudo-elements 

### ISSUE THREAD

**Issue by rohit-kumaar** [twbs/bootstrap#38941] opened 2023-07-20 06:20 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In v5.2  Pseudo-elements  does not implement in floating labels, in v5.3  Pseudo-elements have background-colour white so it's reflecting in our existing website 

### Reduced test cases

https://getbootstrap.com/docs/5.3/forms/floating-labels/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3

**Comment by julien-deramond** [comment] 2023-07-20 06:41
Thanks for reporting an issue @rohit-kumaar 
Isn't it a duplicate of #38731?

**Comment by rohit-kumaar** [comment] 2023-07-20 11:04
Yes it's a duplicate

**Closed** 2023-07-20 11:14 UTC
Labels: css, v5
