### ISSUE TITLE
Box-sizing of input type="search"

### ISSUE THREAD

**Issue by heruan** [twbs/bootstrap#17379] opened 2015-08-28 08:48 UTC
In v4-dev when using `<input type="search">` something's wrong with its box-sizing, it's pretty clear for example in `<td>`s.
See http://jsfiddle.net/heruan/vdj9j6rb/ where the first table has `type="search"` while the second has `type="text"`. I'm on Chrome and using Flexbox.

**Comment by patrickhlauke** [comment] 2015-08-28 08:58
Indeed. It appears the problem is caused by
```
-webkit-box-sizing: content-box;
box-sizing: content-box;
```
in normalize.scss

**Comment by patrickhlauke** [comment] 2015-08-28 08:58
![capture](https://cloud.githubusercontent.com/assets/895831/9542736/634a5c06-4d6b-11e5-8a88-7686325fa48e.PNG)

**Comment by cvrebert** [comment] 2015-08-28 19:52
We should override it back to `border-box`. It's the browser default (http://w3bug.com/28784) and we prefer `border-box` anyways.

**Comment by slavanga** [comment] 2015-08-28 20:00
+1 for overriding it to ```border-box``` like in Bootstrap 3:
https://github.com/twbs/bootstrap/blob/master/less/forms.less#L46

**Comment by mdo** [comment] 2015-09-02 04:16
Fixed in 468a9d9.

**Closed by mdo** 2015-09-02 04:16 UTC
Labels: confirmed, css, v4
