### ISSUE TITLE
V5 Navbar (.navbar-collapse) - Collapsed Height (too small)  - Beta2

### ISSUE THREAD

**Issue by IMTanuki** [twbs/bootstrap#33231] opened 2021-03-02 04:28 UTC
**Environment**
Wndows 10 x64 1909
Chrome Version 88.0.4324.190 (Official Build) (64-bit)
IntelliJ 2020.3.2
Bootstrap V5 Beta 2

**Problem Desc**
In Beta1, navbar-collapse displayed collapsed menu correctly - navbar height matched number of nav items.
In Beta2, navbar-collapse uses flex-basis and flex-grow properties and this seems to be causing a fixed height display.

**Codepen**
[navbar html from examples](https://codepen.io/imtanuki/pen/qBqbRJg?editors=1100)

**Workaround**
Changed code as follows and now it's OK. But I think the flex-basis and flex-grow were added for a reason, so this is probably not a long-term fix.

```
.navbar-collapse {
  // For always expanded or extra full navbars, ensure content aligns itself
  // properly vertically. Can be easily overridden with flex utilities.
  // flex-basis: 100%; // added in beta2, commented out
  // flex-grow: 1; // added in beta2, commented out
  width: 100%; // deleted in beta2, added back in
  align-items: center;
  }
```

**Comment by ffoodd** [comment] 2021-03-02 10:52
You're using the new `.navbar-nav-scroll` feature with a maximum height of  `100px` (through `--bs-scroll-height` custom property).  [Please read the dedicated doc carefully](https://getbootstrap.com/docs/5.0/components/navbar/#scrolling). The diff with beta1 is only that this feature didn't exist ATM.

I'm closing this since this feature is working as intended.

**Closed by ffoodd** 2021-03-02 10:52 UTC

**Comment by IMTanuki** [comment] 2021-03-02 17:52
Apologies - I was using the beta1 navbar html code, which had a hard-coded 100px height.
