### ISSUE TITLE
Dropdown arrow of select looks rather ugly on Firefox

### ISSUE THREAD

**Issue by jpswade** [twbs/bootstrap#16201] opened 2015-04-01 14:25 UTC
As you're probably aware the select dropdown menus are ugly in Firefox.

* http://getbootstrap.com/css/#selects

**On Windows 7 (x64), Firefox v37**
![capture](https://cloud.githubusercontent.com/assets/1087963/6922036/56b559da-d7c0-11e4-951a-5cb32a6c6215.PNG)

This is not a new issue, the problem is also apparent on OS X:

* [Bootstrap 3 Styled Select dropdown looks ugly in Firefox on OS X](http://stackoverflow.com/questions/20366166/bootstrap-3-styled-select-dropdown-looks-ugly-in-firefox-on-os-x)
* [select form in firefox bit ugly #765](https://github.com/twbs/bootstrap/issues/765)

There are a number of third party solutions:
* [SelectBoxIt](http://gregfranko.com/jquery.selectBoxIt.js/)
* [Chosen](http://harvesthq.github.io/chosen/)
* [bootstrap-select](http://silviomoreto.github.io/bootstrap-select/)
* [select2](https://select2.github.io/)

However, as Bootstrap was originally described as "as a way to document and share common design patterns and assets". It would seem to me that this is a common design pattern issue and does sit within the scope of this project.

It is possible that this problem extends to [Normalize.css](http://necolas.github.io/normalize.css/), responsible for "render[ing] all elements more consistently" within Bootstrap.

In any case, solving this common problem would certainly bring us one step closer to making "front-end web development faster and easier".

**Comment by zacechola** [comment] 2015-04-01 14:54
Duplicate of #7602. See also: [#8029 (comment)](https://github.com/twbs/bootstrap/issues/8029#issuecomment-18707235)

**Comment by jpswade** [comment] 2015-04-01 15:11
@zacechola thanks, those links support the fact that this common design pattern problem exists.

**Comment by zacechola** [comment] 2015-04-01 16:16
But the links also point out that it's not an issue Bootstrap intends to solve. 
 
It may be an issue worth revisiting at some point, but styling `select`s to look consistent cross-browser almost certainly means supporting a series of browser hacks. @mdo can elaborate here more I'm sure.

Anyway, @filamentgroup maintains an experiment showing custom-styled selects which illustrates this better: https://github.com/filamentgroup/select-css

**Comment by patrickhlauke** [comment] 2015-04-01 17:28
Yup, this is something that we're not likely to fix in v3. There's a possibility this will be addressed in v4 though, so punting for now.

**Closed by patrickhlauke** 2015-04-01 17:28 UTC

**Comment by Hongbo-Miao** [comment] 2016-08-25 20:00
@pamelafox 

Bootstrap 4 alpha 3 select in Firefox 51.0a1 still shows not well.

![image](https://cloud.githubusercontent.com/assets/3375461/17983880/cd1028f2-6adc-11e6-86d8-cae25313a48f.png)

**Comment by wolfy1339** [comment] 2016-09-02 21:45
Usd the custom forms

**Comment by rdettai** [comment] 2016-11-16 07:18
After a bit of struggle, I found a little workaround. I just put it here in case it helps someone:
```
select {
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        background: url(dropdown.ico) right / 20px no-repeat #fff;
        padding-right: 20px;
}
```
It first removes the native select then adds an icon of your choice. I used the very sober triangle that is used natively in chrome: 

![dropdown-5](https://cloud.githubusercontent.com/assets/7913347/20338079/3e020c9a-abee-11e6-8e5a-ca49c55b22ee.png)

**Comment by kaburkett** [comment] 2018-06-25 16:24
Now that version 4 is here, is this something to reopen? @patrickhlauke

**Comment by wolfy1339** [comment] 2018-06-25 16:54
no, the custom forms component was created to look exactly the same across browsers. The default form component, is only styled slightly but doesn't override system defaults

**Comment by volomike** [comment] 2019-06-03 17:49
Here's how to make it identical to Chrome without having to put an image in a directory.

```
/* FIREFOX FIX OF UGLY SELECT BOXES */
@supports (-moz-appearance:none) {

  SELECT
  {
  -moz-appearance:none !important;
  background: transparent url('data:image/gif;base64,R0lGODlhBgAGAKEDAFVVVX9/f9TU1CgmNyH5BAEKAAMALAAAAAAGAAYAAAIODA4hCDKWxlhNvmCnGwUAOw==') right center no-repeat !important;
  background-position: calc(100% - 5px) center !important;
  }

}

```
