### ISSUE TITLE
copied tool tip in doc not proper

### ISSUE THREAD

**Issue by honnappapujari** [twbs/bootstrap#33363] opened 2021-03-15 12:52 UTC
OS : MACOS 10.15.7(19H15I) 
crome: 89.00
Issue:When Click to copy code, tooltip is going to top.

![image](https://user-images.githubusercontent.com/49408454/111155755-e0641a00-85ba-11eb-95d0-90e381f332ff.png)

**Comment by ffoodd** [comment] 2021-03-15 19:47
Duplicate of other tooltip issues. This is tracked already, thanks for reporting.

**Closed** 2021-03-15 19:47 UTC
Labels: duplicate
