### ISSUE TITLE
Regression in label button group alignment in version 4.0.0-alpha.6

### ISSUE THREAD

**Issue by amanteaux** [twbs/bootstrap#21871] opened 2017-01-29 11:00 UTC
In version 4.0.0-alpha.6, buttons and labels are not aligned within the same button group. It works fine in version 4.0.0-alpha.5.

The problematic code is:
```html
<div class="btn-group" role="group">
  <button type="button" class="btn btn-secondary">Button</button>
  <label class="btn btn-secondary">Label</label>
</div>
```

Here is 2 live examples showing the problem:
- version 4.0.0-alpha.5 is OK: http://scratchpad.io/squalid-unit-144
- version 4.0.0-alpha.6 is broken: http://scratchpad.io/festive-mountain-919

**Comment by mdo** [comment] 2017-01-30 05:06
Sounds like a dupe of #21793, fixed by #21796.

**Closed by mdo** 2017-01-30 05:06 UTC
Labels: css, v4
