### ISSUE TITLE
Dismissing alerts and "long" text

### ISSUE THREAD

**Issue by Ydalb** [twbs/bootstrap#24625] opened 2017-10-31 15:12 UTC
- Chrome 61.0.3163.100 (Build officiel) (64 bits)
- Windows 10
- Test case : https://jsbin.com/texahuquli/edit?html,output

The text of an alert goes below the button sometimes.

![alert-dismiss](https://user-images.githubusercontent.com/1888805/32231555-35baa9a4-be56-11e7-93ff-5ab16606e926.png)

**Comment by dushkostanoeski** [comment] 2017-10-31 15:21
duplicate of #24469  ?

**Comment by splice7** [comment] 2017-10-31 15:25
Yep. It does work fine if you use the dev-branch css file: https://jsbin.com/xazohovobo/1/edit?html,output

**Comment by Johann-S** [comment] 2017-10-31 15:27
Closed thanks to @dushkostanoeski

**Closed by Johann-S** 2017-10-31 15:27 UTC
