### ISSUE TITLE
Modal allows user to mousewheel scroll on main body content

### ISSUE THREAD

**Issue by andycole** [twbs/bootstrap#15245] opened 2014-11-27 11:26 UTC
Is this intentionally so? If not a simple preventDefault on mouse wheel events while modal is open might help.

The only possible arguement for this to be allowed is if the modal itself is larger than the window, but in this instance a modal should maintain it's own scrollbar.

**Comment by venimus** [comment] 2015-02-26 10:49
There is a bug in when opening more than one modals. When you close the topmost modal dialog it removes the `.modal-open` class from the body which is required for the srolling.

you could use something like this until is fixed

```
$(document).on('hidden.bs.modal', '.modal', function () {
    $('.modal:visible').length && $(document.body).addClass('modal-open');
});

**Comment by cvrebert** [comment] 2015-02-26 11:05
@venimus That doesn't sound at all relevant to this issue.

**Comment by cvrebert** [comment] 2015-02-27 01:26
@andycole What OS and browser are you using?

**Comment by cmawhorter** [comment] 2015-03-08 00:39
I think [this commit](https://github.com/twbs/bootstrap/commit/f5beebe726aa8c1810015d8c62931f4559b49664) closes this.

**Comment by cvrebert** [comment] 2015-03-08 05:43
Closing this since (a) I haven't been able to reproduce this with `master` on OS X, and (b) OP never responded to the questions we asked him.

**Closed by cvrebert** 2015-03-08 05:43 UTC
Labels: js
