### ISSUE TITLE
Input type date issue

### ISSUE THREAD

**Issue by karolisgrinkevicius** [twbs/bootstrap#21598] opened 2017-01-07 16:05 UTC
input type date looks ugly since it uses flex-direction column. My suggestion to put:
```
.form-control[type="date"] {
  flex-direction: row;
}
```

**Comment by sudhirj** [comment] 2017-01-16 08:43
Will be fixed when #21716 lands.

**Comment by bardiharborow** [comment] 2017-01-21 06:56
Duplicate of #21651.

**Closed by bardiharborow** 2017-01-21 06:56 UTC
Labels: css, v4
