### ISSUE TITLE
Dashboard example doesn't function fully on a mobile screen

### ISSUE THREAD

**Issue by fulopm** [twbs/bootstrap#26884] opened 2018-07-15 15:45 UTC
- [ ] The Dashboard example's menu isn't showing up on a mobile device (iPhone 8 plus)
- [ ] Also, the navbar covers the title of the page, see attachment.
![img_0712](https://user-images.githubusercontent.com/12369436/42735581-d0504b52-8856-11e8-8c39-564a6f9de34a.PNG)

**Comment by ysds** [comment] 2018-07-16 01:59
#26332 ？

**Comment by mdo** [comment] 2018-07-16 03:38
Duplicate of #26311.

**Closed by mdo** 2018-07-16 03:38 UTC
