### ISSUE TITLE
v4 - Improve Docs Search

### ISSUE THREAD

**Issue by surjithctly** [twbs/bootstrap#21170] opened 2016-11-21 08:06 UTC
The current search in v4 docs only looking for Page Titles, not the actual content. Due to the structure change and ease of usability, I recommend improving the search to all **content and code**.  So it will be easier to look for a specific element. 

There are some search providers like Agolia and Swiftype.  I hope it will be easier to integrate those. 

On version 3, I was  (most of the people may be) using the Browser Search CTRL + F. Since in new version, all sections are different page, its impossible to do that too :(

**Comment by bardiharborow** [comment] 2016-11-21 12:09
Duplicate of #21125.

**Closed** 2016-11-21 13:03 UTC
