### ISSUE TITLE
Customizer doesn't report if there's an error in the configuration

### ISSUE THREAD

**Issue by jphollanti** [twbs/bootstrap#15128] opened 2014-11-14 08:34 UTC
In case of invalid syntax (like `lighten(@gray-base)`, where the second parameter is missing) customizer doesn't report about the error. Instead it will just report back with a success message which points to a config.json gist.

**Comment by cvrebert** [comment] 2015-01-08 19:12
Unable to reproduce. Was probably fixed by #15309.

**Closed by cvrebert** 2015-01-08 19:12 UTC
Labels: customizer
