### ISSUE TITLE
[v4 beta-3] [bug] Input group button loses border radius if group has invalid feedback

### ISSUE THREAD

**Issue by martinbean** [twbs/bootstrap#25359] opened 2018-01-18 18:25 UTC
I have an input group with a single text input, and a button as a suffix. If I add a class of `.is-invalid` to the input, and add an `.invalid-feedback` element to the group, the button suffix loses its `border-radius` because it’s no longer the last child within the group.

Mark-up:

```html
<div class="input-group">
    <input type="text" name="coupon" id="coupon" class="form-control is-invalid" autofocus required />
    <div class="input-group-append">
        <button type="submit" class="btn btn-primary">Apply coupon</button>
    </div>
    <div class="invalid-feedback">You have already redeemed this coupon.</div>
</div>
```

Screen-shot:

![screen shot 2018-01-18 at 18 23 06](https://user-images.githubusercontent.com/167312/35114529-032b5bf4-fc7d-11e7-81fc-5248a08e3374.png)

**Comment by mdo** [comment] 2018-01-18 18:27
Duplicate of #25110. I'm getting closer with #25352, but might need an extra class to provide all the functionality we want :(.

**Closed by mdo** 2018-01-18 18:27 UTC

**Comment by martinbean** [comment] 2018-01-18 18:33
@mdo Ah! I did search Issues first to see if it had already been reported, but missed that one. Sorry!
