### ISSUE TITLE
Copying issue in breakpoints section => max with code window

### ISSUE THREAD

**Issue by vijith6600** [twbs/bootstrap#39664] opened 2024-02-09 06:40 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

## copying the max width syntax is not possible, 
![Screenshot 2024-02-09 115245](https://github.com/twbs/bootstrap/assets/105054251/ff34c353-ad8b-4fe7-a99d-158b44202bb9)

### Reduced test cases

 https://getbootstrap.com/docs/5.3/layout/breakpoints/

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3

**Comment by julien-deramond** [comment] 2024-02-09 07:04
Thanks for reporting this issue @vijith6600 
I suppose that you're trying to copy it by selecting the code with the mouse and not using the copy button.
If so, this is a duplicate of https://github.com/twbs/bootstrap/issues/39605
Closing this issue, if this is a different use case, please add a new comment to this issue so that I can reopen it

**Closed by julien-deramond** 2024-02-09 07:04 UTC

**Comment by vijith6600** [comment] 2024-02-09 09:50
Thankyou https://github.com/twbs/bootstrap/issues/39605 same issue
