### ISSUE TITLE
Split in multiple npm packages (was "Change peerDependencies to optionalDependencies") 

### ISSUE THREAD

**Issue by tkrotoff** [twbs/bootstrap#23557] opened 2017-08-18 18:35 UTC
Edit: see comments below
> So, 3 packages, and make `bootstrap` depend on the other 2, `bootstrap-css` and `bootstrap-js`

<br>
<br>

-----

jQuery and Popper.js are defined as `peerDependencies`: https://github.com/twbs/bootstrap/blob/v4.0.0-beta/package.json#L69

Bootstrap can be used without the JS part (think of [reactstrap](https://github.com/reactstrap/reactstrap), [React-Bootstrap](https://github.com/react-bootstrap/react-bootstrap), [Angular UI Bootstrap](https://github.com/angular-ui/bootstrap), [NG Bootstrap](https://github.com/ng-bootstrap/ng-bootstrap), [BootstrapVue](https://github.com/bootstrap-vue/bootstrap-vue)...)

~~Suggestion: switch to [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies) so there is no warning when not installing jQuery and Popper.js.~~

```
$ yarn
...
warning "bootstrap@4.0.0-beta" has unmet peer dependency "jquery@>=3.0.0".
warning "bootstrap@4.0.0-beta" has unmet peer dependency "popper.js@^1.11.0".
```

**Comment by XhmikosR** [comment] 2017-08-18 18:48
@Johann-S: what do you think? We should probably add a check if it doesn't exist for popper.js. For jQuery we already check.

**Comment by Johann-S** [comment] 2017-08-18 18:58
Not sure because we switch from `dependencies` to `peerDependencies` because folks complaint about having unwanted libs installed... 
And with `optionalDependencies` (if I understand correctly) it will be the same because npm will try to install those libs

**Comment by XhmikosR** [comment] 2017-08-18 19:27
I think we should have used optional deps instead of peer deps.

**Comment by tkrotoff** [comment] 2017-08-18 21:38
@Johann-S 
> with `optionalDependencies` [...] npm will try to install those libs

Sure? I did some tests with npm and Yarn and now I don't even understand how `optionalDependencies` works and its purpose:

Bootstrap package.json:
```JSON
"optionalDependencies": {
  "jquery": ">=3.0.0",
  "popper.js": "^1.11.0"
}
```

Inside the package that uses Bootstrap (let's call it the "client"):
- With npm 5.3.0, jquery and popper.js are not present inside `node_modules` (*) + not present at root level of `package-lock.json` => OK
- With Yarn 0.27.5, jquery and popper.js are present inside `node_modules` (*) + root level of `yarn.lock` => KO?

Naively I though:
- `dependencies` => install inside the client
- `peerDependencies` => no install but check that the client has jquery and popper.js with matching versions as `dependencies`, warning if not
- `optionalDependencies` => no install, no check if jquery and popper.js are installed (if they are, check the versions match - otherwise what the point?) thus no warning

(*) talking about the root level of `node_modules` of course

**Comment by FezVrasta** [comment] 2017-08-19 11:45
> ### [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies)
> 
> If a dependency can be used, but **you would like npm to proceed if it cannot be found or fails to install**, then you may put it in the optionalDependencies object. This is a map of package name to version or url, just like the dependencies object. The difference is that build failures do not cause installation to fail.

I don't think `optionalDependencies` is the correct way to handle this case.

**Comment by XhmikosR** [comment] 2017-08-19 11:49
We can't make everyone happy. If one wants to use only the CSS part then the deps are redundant thus optional makes sense. If one wants to use the JS part then the deps are required.

So, perhaps we should split the packages. I can't think of another solution.

**Comment by FezVrasta** [comment] 2017-08-19 11:53
`optionalDependencies` doesn't make sense at all in this case, its purpose is to avoid the package to crash if one of the `optionalDependencies` can't be installed (because they are architecture specific usually).

**Comment by Johann-S** [comment] 2017-08-19 11:58
We will split Bootstrap in different packages in release 4.3

**Comment by pkozlowski-opensource** [comment] 2017-08-19 11:59
> So, perhaps we should split the packages. I can't think of another solution.

Yup, I think that separate packages are way to go. There could be one package with CSS only (`bootstrap-css`?) and then another one that depends on `bootstrap-css` and adds JS part.

**Comment by XhmikosR** [comment] 2017-08-19 11:59
Either way, we can't split the packages now.

**Comment by XhmikosR** [comment] 2017-08-19 12:00
Either way, we can't split the packages now since it's a breaking change. So need to make this change when we bump the major version or something.

@Johann-S: feel free to rename this issue and assign it to you.

**Comment by FezVrasta** [comment] 2017-08-19 12:02
@XhmikosR you may avoid to have a breaking change if you provided:

- `bootstrap-css`
- `bootstrap`

where `bootstrap` is the `bootstrap-js` package with `bootstrap-css` as dependency.

Doing so people which install `bootstrap` will still get the exact same result of before.

**Comment by XhmikosR** [comment] 2017-08-19 12:06
So, 3 packages, and make `bootstrap` depend on the other 2, `bootstrap-css` and `bootstrap-js`.

That would work.

Any PRs welcome BTW.

**Comment by FezVrasta** [comment] 2017-08-19 12:08
I think you will need something like Lerna to manage the multiple packages in the same repository. And at this point you will hit the same problem I have with Bower and Popper.js.

https://github.com/FezVrasta/popper.js/issues/390

**Comment by XhmikosR** [comment] 2017-08-19 12:16
I personally don't have the time to add lerna. That is why I said PRs welcome.

As for Bower, personally I would drop support for it. But again, we can't do it now.

**Comment by tkrotoff** [comment] 2017-08-19 17:14
> As for Bower, personally I would drop support for it. But again, we can't do it now.

Why not? It's deprecated:

![screen shot 2017-08-19 at 19 09 46](https://user-images.githubusercontent.com/643434/29488770-04e430e8-8512-11e7-9946-f5e29622e114.png)

See https://github.com/bower/bower/issues/2298

If someone wants to upgrade an existing project to cutting edge technology like Bootstrap v4 (not even released yet), it does not make sense to use Bower.

**Comment by XhmikosR** [comment] 2017-08-19 22:06
@tkrotoff: please make a PR to drop support for Bower.

And if someone else can make a PR to split the npm projects please CC me.

**Comment by wrakky** [comment] 2017-08-21 09:32
@XhmikosR have you considered using scoped package names? There are also a lot of packages already named bootstrap-* including bootstrap-css which will make finding meaningful names when splitting the packages harder. Using scoped packages would allow names like @bootstrap/css and @bootstrap/js which is much simpler and makes further packages in the future easier (like having @bootstrap/grid and @bootstrap/reboot as separate packages)

**Comment by XhmikosR** [comment] 2017-08-21 09:43
@wrakky: yeah, I have thought about it too. Both solutions are fine. We'd just need to ask npm to pass over `bootstrap-css` and `bootstrap-js` ownership to twbs.

**Comment by kvz** [comment] 2017-08-21 10:51
Lerna.js is used by e.g. babel to have multiple npm packages while keeping one monorepo to have atomicity in PRs/reverts that touch multiple components, and to have a single issue tracker. Thought it'd be worth your consideration since there's talk about potentially splitting node modules

**Comment by AnimaMundi** [comment] 2017-08-28 17:13
@FezVrasta 

> you may avoid to have a breaking change if you provided:
>
> - bootstrap-css
> - bootstrap
>
> where bootstrap is the bootstrap-js package with bootstrap-css as dependency.
> Doing so people which install bootstrap will still get the exact same result of before.

 Unfortunately, this is still a breaking change for people who directly import Bootstrap sass files for customisation.

**Comment by FezVrasta** [comment] 2017-08-28 17:49
@AnimaMundi I don't think it ever been public API what you are describing, right?

**Comment by AnimaMundi** [comment] 2017-08-28 20:54
@FezVrasta https://getbootstrap.com/docs/4.0/getting-started/options/

Some of those SASS files are described here and useage of them seems to be encouraged, so I'd consider that public.

But even if you guys don't consider it public, I see Bootstrap used in this way much more often than just by downloading precompiled CSS. So what I'm trying to say is, whatever approach you take, breaking out into separate modules is going to break things for a lot of people so I wouldn't take it into consideration with whatever approach you take. Take the best approach and don't allow an attempt to avoid breaking changes steer you away from a possibly better option. Which in my opinion, is using npm scoped packages.

**Comment by tkrotoff** [comment] 2017-08-29 10:31
@AnimaMundi 
> a breaking change for people who directly import Bootstrap sass files

This would go from:
```SCSS
@import 'node_modules/bootstrap/scss/bootstrap';
```
to:
```SCSS
@import 'node_modules/bootstrap-css/scss/bootstrap';
```

We could create file `node_modules/bootstrap/scss/bootstrap.scss` that imports `node_modules/bootstrap-css/scss/bootstrap.scss`.

Problem is that you potentially need to do that with all existing .scss files, not only bootstrap.scss, to retain full compatibility.

**Comment by alundiak** [comment] 2017-09-09 20:54
#OMG these all changes are so 2017 :) ok... 

Anyway, I see, that https://github.com/StevenIseki/bootstrap-css.git exists, is this officially related to This Main Repo? I doubt, maybe @StevenIseki will explain. 
But how I spotted on it? I was reading this issue thread, and at some point started thinking, that `bootstrap-css` which (theoretically/potentially) mentioned here/above (by @tkrotoff, @pkozlowski-opensource, @FezVrasta) is already done by Twitter, and hit `npm install bootstrap-css`, and voilà. I also see, that in discussion between @XhmikosR and @wrakky there is   "ownership to twbs.". 

So is this all about that existed NPM module and passing name to twbs? Should I remove recently installed bootstrap-css? It's not critical for me, but just matter of interest.

**Comment by mdo** [comment] 2017-10-02 20:43
I haven't followed this thread at all really... where are we at?

**Comment by tkrotoff** [comment] 2017-10-02 20:56
@mdo check PR #23614

**Comment by mdo** [comment] 2017-10-23 02:51
Closing this as a won't fix. While we're not splitting, that is the intent of this issue. I'll leave that PR opened for now to explore how we can publish separate packages outside this main one. We won't be breaking up the core repo.

**Comment by AnimaMundi** [comment] 2017-10-23 16:28
The intent of the issue is to split into multiple NPM packages, not to split the actual repo. Splitting the repo just came up as one approach to splitting the NPM package so I think it makes sense to leave this open.

**Comment by tobi-or-not-tobi** [comment] 2018-09-24 08:34
@Johann-S I'm a bit confused about this ticket. It's been closed by @mdo after [you've stated](https://github.com/twbs/bootstrap/issues/23557#issuecomment-323518928) that you're going to split up in two packages. I've seen you closed newly created tickets around this topic, but I can imagine these have been created after this one was closed. 

Can you confirm the strategy here: Are you still planning to split the package, so that we can consume a css-only version of bootstrap and use a custom JS implementation?

**Comment by tobi-or-not-tobi** [comment] 2018-09-24 08:37
Excuses-et-moi, just noticed that the ticket has been reopened already. I'm still interested on the plan.

**Comment by tomprats** [comment] 2018-09-26 22:57
Whatever happened to this? I'm very much interested in using split packages but it doesn't look like anything has happened with that PR (https://github.com/twbs/bootstrap/pull/23614). Any way I can help get it moving?

**Comment by mdo** [comment] 2018-12-17 21:04
Inclined to close this as stale—I don't know how much anyone on the core team wants to take this on themselves. I wouldn't mind feedback and ideas for how to implement the autopublishing to multiple packages, so long as it doesn't force a ton of build tooling or project changes for us here.

**Closed** 2019-02-19 01:35 UTC
Labels: meta, v4
