### ISSUE TITLE
v5: JS constant declaration / minification

### ISSUE THREAD

**Issue by pvdlg** [twbs/bootstrap#20011] opened 2016-06-01 03:08 UTC
Most of the constant in javascript modules are declared as properties of constant objects, i.e.:

```
const ClassName = {
  BACKDROP : 'dropdown-backdrop',
  DISABLED : 'disabled',
  OPEN     : 'open'
}
```

Once minified, these constants are not mangled (for example search for 'BACKDROP' in [bootstrap.min.js](https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/bootstrap.min.js)) because uglify, by default doesn't mangle object keys (I didn't find a safe way to have Uglify mangling objects keys). 

Defining a variable as a constant make it a read-only reference, however defining an object as a constant make this object reference read-only, but not its keys. See [const](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const).
As all the variables declared this way in Bootstrap are read but never reassigned, therefore really used as constants, I would imagine that the original intent was to make the actual variable a constant, rather than its wrapping object.

Declaring these constants directly rather than as object key would:
- allow mangling of the variables declaration and their references (smaller minified file, faster parsing)
- be more consistent with the intention (as I understand it) of declaring read-only variable

Is there a reason for which the constants are declared as object keys rather than directly as a constant ?

If not, I would like to propose a PR that would change the code example above into:

```
const CN_BACKDROP = 'dropdown-backdrop'
const CN_DISABLED = 'disabled'
const CN_OPEN = 'open'
```

The `CN_` naming convention for Class name (or `S_` for selectors, `E_` for events)  would maintain the readability of the current implementation (I imagine readability might be the reason for this choice ?).

Am I missing/misunderstanding something ? Would you consider such PR ?

**Comment by cvrebert** [comment] 2016-06-01 06:08
I think this scheme was related to making subclassing feasible and/or to constraints imposed by the [Closure Compiler](https://github.com/google/closure-compiler) optimizer (which we were using for a while in an old draft of v4).

**Comment by vanduynslagerp** [comment] 2016-06-01 13:22
Thanks for the prompt answer !
Closure compiler is not used anymore but I'm not sure if subclassing is still a goal.

The PR wouldn't be difficult to do, but as it modifies a lot of code it would be difficult to maintain if it's not merged right away (pretty much every JS modification would impact the PR).

So if you decide to change this scheme, just let me know and I'll make the PR :-)

**Comment by wifiextender** [comment] 2016-06-06 00:50
[_jQueryInterface](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/button.js#L117)

[CTRL+f ](https://raw.githubusercontent.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.min.js) _jQueryInterface

Why is not the "function" mangled, because each class object is stored as key/value.

You provide a good points regarding the optimizations, but the hassle to re-write ALL the code and use the reference to call/use some object/array/function etc, the interpreter will have to go back and forth (lookup) where does this reference came from. Sticking to locals is and always but much faster for the interpreter to lookup.

Regarding the `const`:

```javascript
const a = {};

a.one = 1;
a.two = 2;
a.three = 3;

// Object {one: 1, two: 2, three: 3}

a = null;
// Uncaught TypeError: Assignment to constant variable.
```

**Comment by vanduynslagerp** [comment] 2016-06-06 01:18
The _jQueryInterface should not be changed as it's exposed externally, and it's intended that it's not mangled. The change I propose is regarding variable local (or private) to the module, that are used as configuration such as class name or selectors.

The changes I propose would keep these variable local to the object (i.e. local to `Dropdown`, `Modal` etc...).
Also these variable are constant that should not be reassigned. So the 'Uncaught TypeError' in your example is actually the intended behavior. For example, the classes name the javascript module depends on, should not be re-assigned at runtime. Currently they can, the objective to this change is to make them actual immutable constants.

Considering the "hassle of the of the re-write", there is absolutely no re-write or any modifications in any code using or depending on Bootstrap.
The modification I propose changes only private variable, that are purely internal, and cannot be used by any external code anyway.

Performance wise I don't think there is any difference in accessing a local variable (what I'm proposing) versus accessing the key of an object declared as a local variable (what is currently implemented).
I'm not sure what you mean by " the interpreter will have to go back and forth (lookup) where does this reference came from" as we are talking about local variable.

Maybe there is a disconnect because my original post wasn't clear enough on the fact that it would modifies only the constants used as unmodifiable configurations such as the html markup and css classes the module relies on.

**Comment by wifiextender** [comment] 2016-06-06 02:09
Since it's limited to the class scope I agree with you.

Thought that you wanted to use globals everywhere.

**Comment by robfrawley** [comment] 2016-06-24 17:29
@cvrebert Out of curiosity, why did you stop using Closure Compiler? You can easily gain 5-25% savings in size if you use the available advanced options of the tool.

**Comment by cvrebert** [comment] 2016-06-24 18:36
@robfrawley We didn't feel it would be viable to add Java as a dependency.

**Comment by bardiharborow** [comment] 2016-12-08 10:12
@cvrebert bump. Do you have an opinion about how to go forward with this?

**Comment by vanduynslagerp** [comment] 2017-01-13 21:07
I went ahead and made the PR #21711.
We can reduce the minified and gzipped distribution file by 6.3% (10.8% with #21715)

**Closed** 2020-03-18 10:58 UTC
Labels: js, v5
