### ISSUE TITLE
Tooltips/Popovers not working consistently

### ISSUE THREAD

**Issue by joeforjoomla** [twbs/bootstrap#32886] opened 2021-01-23 16:54 UTC
Tooltips are not working well with BS5. If you try to enter/exit the mouse over a certain element even without any child node, the tooltip vanishes. This incorrect behavior can be seen also on the demo page using the latest Chrome: https://getbootstrap.com/docs/5.0/components/tooltips/

Definitely tooltips/popovers not working consistently with Popper 2 in BS5

**Comment by XhmikosR** [comment] 2021-01-25 10:35
Duplicate of #32372 and/or #31646

**Closed by XhmikosR** 2021-01-25 10:35 UTC
