### ISSUE TITLE
Border problem in Button input groups

### ISSUE THREAD

**Issue by rranke** [twbs/bootstrap#24837] opened 2017-11-20 16:31 UTC
Border problem in Button input groups.

Tested on FF 57.0 (64-Bit) Ubuntu at
https://getbootstrap.com/docs/4.0/components/input-group/#segmented-buttons

![bildschirmfoto vom 2017-11-20 17 24 41](https://user-images.githubusercontent.com/5783257/33029266-6fd4433a-ce18-11e7-8ee3-8326f0433d4b.png)

**Comment by mdo** [comment] 2017-11-20 19:16
Duplicate of #24216.

**Closed by mdo** 2017-11-20 19:16 UTC
Labels: css, v4
