### ISSUE TITLE
`tooltip.js` error with table editable

### ISSUE THREAD

**Issue by bounlu** [twbs/bootstrap#39743] opened 2024-03-06 05:34 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

After submitting an editable field, the Console gives the below error even though the editing succeeds:

```
tooltip.js:534 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at us._isWithActiveTrigger (tooltip.js:534:19)
    at tooltip.js:268:16
    at g (index.js:226:51)
    at HTMLDivElement.a (index.js:247:5)
    at s (index.js:71:11)
    at index.js:253:7
```

### Reduced test cases

Replace this:

```
  _isWithActiveTrigger() {
    return Object.values(this._activeTrigger).includes(true)
  }
```

with this:

```
_isWithActiveTrigger() {
    if (this._activeTrigger && typeof this._activeTrigger === 'object') {
        return Object.values(this._activeTrigger).includes(true);
    }
    return false; // or handle the case when _activeTrigger is not an object
}
```

### What operating system(s) are you seeing the problem on?

macOS, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

5.3.1

**Comment by batje** [comment] 2024-03-06 10:41
This is a duplicate of #37474

**Comment by julien-deramond** [comment] 2024-03-06 10:56
Thanks @batje! This is indeed a duplicate so I'll close this one. @bounlu, you can add a comment in #37474 with your patch suggestion if it's not already mentioned in the discussion.

**Closed by julien-deramond** 2024-03-06 10:56 UTC
Labels: awaiting-reply, needs-example
