### ISSUE TITLE
Add Horizontal Cards

### ISSUE THREAD

**Issue by vaggelisifa** [twbs/bootstrap#23462] opened 2017-08-15 14:35 UTC
I think would be good to add horizontal cards.

**Comment by myorangeca** [comment] 2017-08-15 14:37
How so? What do you mean by horizontal cards?

**Comment by scrooby** [comment] 2017-08-15 14:45
Do you mean like this: https://getbootstrap.com/docs/4.0/components/card/#card-groups or this: https://getbootstrap.com/docs/4.0/components/card/#card-decks ?

**Comment by mdo** [comment] 2017-08-15 15:54
Please search first next time. Duplicate of #20794.

**Closed by mdo** 2017-08-15 15:54 UTC

**Comment by vaggelisifa** [comment] 2017-08-16 00:07
No I mean something like this [http://materializecss.com/cards.html#horizontal](http://materializecss.com/cards.html#horizontal)

**Comment by mdo** [comment] 2017-08-16 16:15
Yeah, that's the same as the issue I referenced.
