### ISSUE TITLE
data-bs-toggle="dropdown" cannot be targeted with jquery "on" while data-bs-toggle="collapse" can be

### ISSUE THREAD

**Issue by dazetoyo** [twbs/bootstrap#32729] opened 2021-01-08 11:32 UTC
- Operating system and version Windows 10
- Browser and version Chrome 87.0.4280
- https://codepen.io/dazetoyo/pen/RwGBRRJ

Any explanations for this?

**Comment by XhmikosR** [comment] 2021-01-08 19:02
I guess it's a duplicate of #31935

**Closed by XhmikosR** 2021-01-08 19:02 UTC
