### ISSUE TITLE
.form-control <select> flickers/flashes in OS X Chrome v50 & v51

### ISSUE THREAD

**Issue by caroso1222** [twbs/bootstrap#19865] opened 2016-05-09 03:26 UTC
This started happening recently when I updated Chrome for Mac to v50.

Whenever I set `.form-control` to a select element, I will start flickering when activated. It's really annoying and haven't ever run into this issue before. I made a video so you can see what's going on. https://www.youtube.com/watch?v=Z04pW9Jkgso

The only workaround I found is to disable the `transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;` property of `.form-control` for `select` elements. I've been able to replicate this bug on two more machines.

I might be omitting details so if you need more details about my environment I can provide with no problem.

Thanks!

**Comment by wolfy1339** [comment] 2016-05-09 03:43
Whats your complete Chrome and OS X version

**Comment by caroso1222** [comment] 2016-05-09 03:48
@wolfy1339 Chrome: Version 50.0.2661.94 (64-bit). OSX: 10.11.4.

**Comment by RyanZim** [comment] 2016-05-09 12:42
@caroso1222 Your video is private so I can't see it. Please provide a JSFiddle/JSBin. Are you using Bootstrap v3 or v4?

**Comment by caroso1222** [comment] 2016-05-09 18:18
Hi @RyanZim. I'm so sorry, I just disabled the private property of the video. I'm working of the JSFiddle. I'm working with Bootstrap v3.3.6.

Thanks!

**Comment by bryanskene** [comment] 2016-05-10 00:00
Me too, same symptoms. Number of flickers doesn't depend on number of items in dropdown selector. It can vary as I navigate around to other pages, then return. In my Gemfile.lock: twitter-bootstrap-rails (3.2.0). Chrome Version 50.0.2661.94 (64-bit), OSX 10.11.4. Seemed to start around 2w ago. Any pointers on root cause would be appreciated. Off to try the workaround, thanks for that.

**Comment by bryanskene** [comment] 2016-05-10 00:15
BTW, awesome, many thanks for that hint, this has been bugging us for weeks and our team thanks you! Added this to our .css and problem solved!

`select.form-control {
  transition: none;
}`

**Comment by slgriffiths** [comment] 2016-05-10 00:22
Adding the `transition: none` override to select tags with `form-control` fixed it for me. Currently midway through a BS2 -> BS3 upgrade and this was bothering me. Thanks!

**Comment by RyanZim** [comment] 2016-05-10 14:05
Looks like a browser bug to me.

CC: @cvrebert

**Comment by cvrebert** [comment] 2016-05-10 17:56
Definitely a browser bug, although I haven't been able to reproduce with a trivial JS Bin I whipped up.
@caroso1222 Looking forward to seeing your JS Fiddle.

**Comment by martin-walsh** [comment] 2016-05-23 05:56
OS: OSX 10.11.4 (15E65)
Browser: Chrome Version 50.0.2661.102 (64-bit)

**Comment by cvrebert** [comment] 2016-05-23 06:29
@martin-walsh JS Bin, jsFiddle, or video please.

**Comment by vecmezoni** [comment] 2016-05-23 10:00
https://bugs.chromium.org/p/chromium/issues/detail?id=613885

**Comment by nagarakesh4** [comment] 2016-05-23 18:21
same issue for me too.

OS: OSX 10.11.3
Browser: Chrome Version 50.0.2661.102 (64-bit)

**Comment by cvrebert** [comment] 2016-05-23 20:06
Has anyone observed this problem on Windows or Linux?

**Comment by cvrebert** [comment] 2016-05-23 20:18
@bryanskene @slgriffiths @nagarakesh4 Could you please make a JS Bin, jsFiddle, or similar that demonstrates the problem? Without a testcase, I can't really file a good bug against Chrome. Thanks in advance.

@vecmezoni That bug seems to be Android-specific, whereas this bug is OS X-specific so far. Though it's possible there could be some relation.

**Comment by RyanZim** [comment] 2016-05-23 20:19
I can test on windows when we get a testcase.

**Comment by SourceCode** [comment] 2016-05-25 18:58
OSX: 11.5 Chrome: 50.0.2661.102 (64-bit) - latest bootstrap and I'm using select2 (which may not apply).  Select flashes twice on open.

**Comment by cvrebert** [comment] 2016-05-25 19:13
@SourceCode We need a live example, not a screenshot. Do you experience this problem on getbootstrap.com?

**Comment by danoc** [comment] 2016-05-25 20:46
I've seen this bug outside of Bootstrap and was also able to prevent the flashing by killing the transition. Wasn't able to create a test case though and have a feeling that it may only happen on heavy pages.

**Comment by SourceCode** [comment] 2016-05-25 21:43
If I use it in the most basic example and just a small piece of the code in a fiddle it does not happen but unfortunately in more complex scenarios it does seem to happen (more libraries, more controls, more 'things' happening).    

I'm working to isolate it but I am at a conference which is why I could only supply a quick screen capture to illustrate what I and other users are observing.  It could be unrelated to bootstrap - however this is the very first result when searching for this issue in google.  If I locate the cause I will update the thread but that may be some time.

**Comment by RyanZim** [comment] 2016-05-25 22:04
> @SourceCode Do you experience this problem on getbootstrap.com?

**Comment by cvrebert** [comment] 2016-05-25 22:09
Filed Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=614838
Please star it, folks.
(Testcases would still be greatly appreciated and very helpful.)

**Comment by caroso1222** [comment] 2016-05-25 22:16
@cvrebert thanks! starred.

**Comment by fczbkk** [comment] 2016-05-31 14:35
I have managed to isolate and reproduce the problem: https://jsfiddle.net/fczbkk/jhdsua5k/

**Comment by RyanZim** [comment] 2016-05-31 14:58
@cvrebert I tried the testcase on Windows and am unable to reproduce there. I'm guessing it's OS X-specific.

**Comment by cvrebert** [comment] 2016-05-31 21:37
@fczbkk You seem to have found a different bug (related to DOM attribute mutations) which also causes the same type of flickering.

**Comment by cvrebert** [comment] 2016-06-01 17:39
The relevant bug for this might be https://crbug.com/608140 , which was fixed as of Chrome 51.0.2704.54.
Can y'all please re-test with up-to-date stable Chrome?

**Comment by ochong** [comment] 2016-06-01 18:04
Are we sure it's not the other issue that was reported by @fczbkk? https://crbug.com/616197

**Comment by cvrebert** [comment] 2016-06-01 18:45
We're not completely sure of anything at this point.

**Comment by Jakobud** [comment] 2016-06-07 22:03
Using OSX 10.10.5 (Yosemite) and Chrome 50.0.2661.102 (64-bit) 

I DO NOT get the flashing select menu on this page:

https://jsfiddle.net/fczbkk/jhdsua5k/

**Comment by ryanguill** [comment] 2016-06-20 14:45
El Capitan 10.11.5, Chrome Version 51.0.2704.103 (64-bit) I _do_ get the flashing, fwiw.

**Comment by cvrebert** [comment] 2016-06-20 15:08
@ryanguill Could you please post a comment on https://bugs.chromium.org/p/chromium/issues/detail?id=608140 with the same information, to let the Chrome folks know?

**Comment by ryanguill** [comment] 2016-06-20 15:16
I am not able to reproduce with the codepen in that bug, but was able to with the jsfiddle in this one https://bugs.chromium.org/p/chromium/issues/detail?id=616197 - and I have posted there.

**Comment by cvrebert** [comment] 2016-06-20 15:32
@ryanguill The issue that that was duped to (https://bugs.chromium.org/p/chromium/issues/detail?id=614250 ) is supposed to have been fixed in v52. Could you re-test using Chrome Canary?

**Comment by ryanguill** [comment] 2016-06-20 16:00
I just downloaded canary - can confirm that everything looks to be fixed both with that fiddle example and with my personal test case that brought me here.

**Comment by cvrebert** [comment] 2016-06-20 17:05
Going to assume at this point that Chrome 52 has fixed the relevant bugs.
I'll be happy to reopen this if anyone observes the problem in Chrome 52+.

**Closed by cvrebert** 2016-06-20 17:05 UTC
Labels: browser bug, confirmed, css, v3
