### ISSUE TITLE
Collapse on media breakpoints

### ISSUE THREAD

**Issue by danielmarkavis** [twbs/bootstrap#27074] opened 2018-08-15 10:48 UTC
Would it be worth while to add breakpoints for collapsible content?

https://codepen.io/danielmarkavis/pen/WKBOBG

I added a class to show items on desktop and collapse on mobile.

The main issue is the JS as it does not know in which collapse state it is in and does some weird double open.

So adding classes such as ".show-sm", ".show-md", and adapting the JS would be a great thing.

**Comment by Johann-S** [comment] 2018-08-15 13:47
For me it's not the good things to here, that's not the business of our JS to detect in which breakpoint we are. That's the goal of our CSS to adapte the rendering according to our breakpoints.

A small tips, an `id` should be unique 

/CC for feedbacks @andresgalante, @MartijnCuppens, @mdo

**Comment by dvmuccillo** [comment] 2018-08-15 15:49
Don't we have something like this and CSS based for navbar? Would be good to have the same feature for collapse.

**Comment by MartijnCuppens** [comment] 2018-08-19 21:12
Buttons that don't do anything when they are clicked may confuse the users, so I think it's better to hide them when you don't need them.

I think what you're trying to achieve is possible with existing utility classes, is this what you want, @danielmarkavis: [https://codepen.io/MartijnCuppens/pen/eLOKpV?editors=1100](https://codepen.io/MartijnCuppens/pen/eLOKpV?editors=1100)?

**Comment by VaclavElias** [comment] 2020-10-20 22:20
@MartijnCuppens this doesn't work on Desktop if you remove d-lg-none from the button wrapper. I would like to have the toggle button available at all time but by default the content will show up on Desktop and will be collapsed on mobile.

**Comment by mdo** [comment] 2021-01-10 05:49
Duplicate of #25765.

**Closed by mdo** 2021-01-10 05:49 UTC
Labels: css, feature, js
