### ISSUE TITLE
[getbootstrap.com site] Latest version number in docs is misleading

### ISSUE THREAD

**Issue by rafrafek** [twbs/bootstrap#35658] opened 2022-01-05 22:14 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When I go to docs using Google, it always opens old version and there is no information that 5.1 exists!
![image](https://user-images.githubusercontent.com/23004737/148296633-5ee30e79-a923-4a63-a098-ce1cfcb4e717.png)

### Reduced test cases

Search `bootstrap 5 docs` in Google. Same applies for older Bootstrap version, e.g. 4.5 is not pointing to 4.6.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

I want to (always) use latest version

**Comment by alecpl** [comment] 2022-01-06 09:08
Sounds like a duplicate of #31980.

**Comment by ffoodd** [comment] 2022-01-06 09:24
Agreed. This is a longstanding issue, and we didn't have time to handle appropriately. Thanks for reporting though :)

**Closed by ffoodd** 2022-01-06 09:24 UTC
