### ISSUE TITLE
Container should have initial width of 100%

### ISSUE THREAD

**Issue by bairathirahul** [twbs/bootstrap#22335] opened 2017-04-02 19:08 UTC
Dear Bootstrap team,

I want to indicate a scenario with .container inside navbar. In extra small size, the container collapse like the below screenshot as it is inside a flex container.

I think the default width of container should be explicitly set to 100% to avoid this scenario.

![image](https://cloud.githubusercontent.com/assets/11868123/24590142/8777cb4c-17e8-11e7-887e-1182f1191ad0.png)

**Comment by mdo** [comment] 2017-04-02 19:41
Please search before opening new issues—this was already solved in `v4-dev`. Duplicate of #21590 and fixed by #21722.

**Closed by mdo** 2017-04-02 19:41 UTC
