### ISSUE TITLE
radio .btn-group not highlighting properly for keyboard users

### ISSUE THREAD

**Issue by HirenBhalani-BTC** [twbs/bootstrap#20211] opened 2016-06-30 07:20 UTC
I need one help about bootstrap radio button group.

I have a form in which I have 12 radio buttons as button-group like given [here](http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons).

Now while a press arrow key, it's changing the focus on the neighbour button but not highlighting selected one, Is there any way that can select the radio button on pressing arrow key or highlight selected one while changing the focus.

**Comment by cvrebert** [comment] 2016-06-30 20:48
I believe this is a duplicate of #18874.

**Closed by cvrebert** 2016-06-30 20:48 UTC
Labels: js, v4
