### ISSUE TITLE
Color values should use a global css variable instead a fixed hex color

### ISSUE THREAD

**Issue by CarlosEGuerraSilva** [twbs/bootstrap#38173] opened 2023-03-06 01:23 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Theming bootstrap via sass is "easy" for a fixed theme and colors, but if you want your website be color-reactive or customized per user it become unreliable

E.g. When you want to customize your primary color you set it as:
`$primary: #429bf5`

Then you compile the sass and now all components will have the value #429bf5 in places where the primary color should be, if you want all the components use a different color you have to set them individually, would be better if bootstrap generates some css global like `--bs-theme-primary:  #429bf5` for the primary color and then in every component just use var(--bs-theme-primary) to get that color and then we can just change that value to affect all the components

### Motivation and context

- The color in a global scope will be easy to customize even in a separate css file if you don't want to customize via sass, at least colors...
- Increases flexibility to customize and more css variables always are welcome
- Avoid changing every hex value or attribute per component, just one change and that's all

**Comment by julien-deramond** [comment] 2023-03-06 05:39
With the new color mode and the integration of custom properties, v5.3.0 will be somewhere in between. We have to break a lot of things IMO in order to provide better customization so it would be rather in v6.
We have ideas to improve this customization but unfortunately, it's impossible without breaking changes that can happen only in a major version.

Changing the main colors is important for simple customization for end-users, but we also have to maintain fine customization per component. Moreover, custom properties have some limitations that will be complicated to handle. But we will try things :)

**Comment by mdo** [comment] 2023-03-08 05:55
Duplicate of #38170.

**Closed by mdo** 2023-03-08 05:55 UTC
Labels: feature, css
