### ISSUE TITLE
Dropdown in navbar not working

### ISSUE THREAD

**Issue by prkshtshrm4** [twbs/bootstrap#32624] opened 2020-12-27 16:59 UTC
I recently used dropdown menu from bootstrap navigation and encountered an bug which was easy to resolve maybe some latest version issue:

Issue_Code : 

```html
<li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
```

Resolve Code: 

```html
<li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
  ```

Explanation: data-bs-toggle is causing the issue.
* It has a simple fix i just removed bs from that part and it was working fine with just "data-toggle".

Browser Checked on: 
Google Crome,
Microsoft Edge.

Hope my information was of some help 

Thank You 
Parikshit Sharma
(parikshitsharma@ieee.org) 

https://user-images.githubusercontent.com/52581502/103175808-d885bb00-4892-11eb-82bb-099716837588.mp4

**Comment by XhmikosR** [comment] 2020-12-29 13:48
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and Operating System details.

*This is an automated reply*

**Comment by yeezy69** [comment] 2020-12-29 14:17
I have noticed that when the dropdown-toggle a-href is not "#", an uncaught DOMException raised.

https://jsbin.com/nutusocono/edit?html,output

`Uncaught DOMException: Failed to execute 'querySelector' on 'Document': 'http://www.google.com/' is not a valid selector.
    at c (https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js:6:1109)
    at Function.o.getParentFromElement (https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js:6:45979)
    at Function.o.clearMenus (https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js:6:45249)
    at o.r.toggle (https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js:6:42058)
    at Function.o.dropdownInterface (https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js:6:44993)
    at HTMLAnchorElement.<anonymous> (https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js:6:47382)
    at HTMLDocument.i (https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js:6:4334)`

**Comment by XhmikosR** [comment] 2020-12-29 14:22
Yeah, that's a known issue and we have a WIP PR for it.

Duplicate of #32273 I guess then

**Closed by XhmikosR** 2020-12-29 14:22 UTC
Labels: awaiting-reply
