### ISSUE TITLE
When there are multiple dropdown menus in an input group, the first dropdown menu is always opened

### ISSUE THREAD

**Issue by Harvey1214** [twbs/bootstrap#36982] opened 2022-08-18 07:50 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When we have an input group containing for example two buttons and an input field and the two buttons are supposed to toggle different dropdown menus, however, all of the dropdown toggles in the input group toggle the first dropdown menu.

### Reduced test cases

In [this demo](https://getbootstrap.com/docs/5.2/forms/input-group/#buttons-with-dropdowns), take a look at the third input group.

- when the first Dropdown toggle button is clicked, a dropdown menu is opened - correct

![image](https://user-images.githubusercontent.com/62853076/185339062-2bf74d45-b61c-4992-9348-537d487ca026.png)

- when the second Dropdown toggle button is clicked, the same dropdown menu is opened, even though there is a different one it should toggle

![image](https://user-images.githubusercontent.com/62853076/185339183-4018c3b1-3d98-4dff-af74-2cc5bf5685dd.png)

Considering the code, the content of the dropdown menus should be different, however, the same one is rendered when we click the buttons.

![bootstrapissue](https://user-images.githubusercontent.com/62853076/185340056-40758e45-2d7b-4aff-b93e-f30c59ba05d1.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0

**Comment by mdo** [comment] 2022-08-18 07:57
Duplicate of #36803

**Closed by mdo** 2022-08-18 07:57 UTC

**Comment by joehanna** [comment] 2022-12-04 01:58
Fixed in at least 5.2.3
