### ISSUE TITLE
Bootstrap 4 not accepting offset-sm-3, I have attached cdn links in the head and also the script before </body>. 

### ISSUE THREAD

**Issue by kashyaprashant** [twbs/bootstrap#23712] opened 2017-08-28 13:23 UTC
<dl class="row">
            <dt class="col-sm-3">Lorem ipsum dolor.</dt>
            <dd class="col-sm-9">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam, eaque.</dd>

            <dt class="col-sm-3">Lorem ipsum dolor sit amet.</dt>
            <dd class="col-sm-9">Lorem ipsum dolor sit amet, consectetur adipisicing elit.</dd>

            <dd class="col-sm-9 offset-sm-3">Lorem ipsum dolor sit amet.</dd>

            <dt class="col-sm-3 text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem, hic!</dt>
            <dd class="col-sm-9 text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil nisi omnis beatae modi, obcaecati inventore recusandae dolore sunt in esse. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio at iure vitae voluptatibus quaerat quia dolores nesciunt pariatur, odio asperiores!</dd>

            <dt class="col-sm-3">Lorem ipsum dolor sit.</dt>
            <dd class="col-sm-9">
                <dl class="row">
                    <dt class="col-sm-3">Lorem ipsum dolor.</dt>
                    <dd class="col-sm-9">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quasi, nesciunt.</dd>
                </dl>
            </dd>
        </dl>

**Comment by browner12** [comment] 2017-08-28 13:31
`offset` classes were removed in favor of margin utilities, but there was a huge demand for them, so they will be coming back.

**Comment by browner12** [comment] 2017-08-28 13:32
https://github.com/twbs/bootstrap/pull/23445

**Comment by mdo** [comment] 2017-08-28 15:38
Duplicate of #23445.

**Closed by mdo** 2017-08-28 15:38 UTC
