### ISSUE TITLE
Carousel in Chrome shows vertical scroll

### ISSUE THREAD

**Issue by dandaka** [twbs/bootstrap#21663] opened 2017-01-11 16:52 UTC
I open this page:
https://blog.getbootstrap.com/

And see following result:
![carousel-chrome](https://cloud.githubusercontent.com/assets/2384694/21857643/ca8521ea-d82e-11e6-8f2b-9b2f1cb68b6c.jpg)

Looks like a bug. Sorry, if I have broken some rules of contribution. I presume Blog uses latest BS version and doesn't plan to show vertical scroll.

OSX 10.11.6 (15G1212)
Chrome Version 56.0.2924.51 beta (64-bit)

**Comment by bardiharborow** [comment] 2017-01-12 02:59
I think you'll find that the scrollbar is caused by that example being a embedded JSBin, rather than an issue with the carousel itself.

**Comment by mdo** [comment] 2017-04-08 22:44
Closing because this is on the blog and not this repo.

**Closed by mdo** 2017-04-08 22:44 UTC
Labels: docs, v4
