### ISSUE TITLE
v5: Bootstrap tooltips don't appear after numbers of focusing

### ISSUE THREAD

**Issue by sajadafaghiy** [twbs/bootstrap#32372] opened 2020-12-08 01:55 UTC
- Operating System: **Windows 10**
- Browser: **Chrome version 87.0.4280.88**

Titled problem occurs even on official docs of bootstrap website at [here](https://getbootstrap.com/docs/5.0/components/tooltips). Tooltips all after some hovering are disappeared and not be accessible any more.

**Comment by XhmikosR** [comment] 2020-12-08 06:00
Sorry, we need more info. Please make a CodePen as per our issue template.

**Comment by septatrix** [comment] 2020-12-08 08:59
I can reproduce the issue on [the example](https://getbootstrap.com/docs/5.0/components/tooltips/#examples) linked to in the documentation. Quickly hovering over the button seems to cause this issue... To be more precise it seems as if refocusing/-hovering while the popover still transitions out leads to the behaviour.

**Comment by XhmikosR** [comment] 2020-12-08 09:02
OK, thanks for the info. I can reproduce indeed.

**Comment by XhmikosR** [comment] 2020-12-08 09:41
I believe it's a regression from the Popper 2.x update. Testing the PR preview before the Popper update seems to be fine https://deploy-preview-32280--twbs-bootstrap.netlify.app/docs/5.0/components/tooltips/#examples

**Comment by XhmikosR** [comment] 2020-12-08 13:34
I had a quick look at https://popper.js.org/docs/v2/migration-guide/ and there are a few things that we might have missed like:

>`scheduleUpdate()` is now `update()` (and returns a promise).

We must be missing something in https://github.com/twbs/bootstrap/pull/31178/files#diff-6c132568dfa4c274ad864998ee3f464980c59004919fb76102b8427893062cf2

**Comment by XhmikosR** [comment] 2020-12-08 14:12
I think I pinpointed the issue. It lies in these lines:

https://github.com/twbs/bootstrap/blob/b1290ff189f03fae12a74ece09b25069d6f97f1a/js/src/tooltip.js#L608-L611

After hovering a few times over the same tooltip, it seems that `context.getTipElement().classList.contains(CLASS_NAME_SHOW)` becomes `true`, thus we enter that block and return.

Now, I don't know if that block is even needed anymore, or if we shouldn't return from there.

**Comment by Jas-n** [comment] 2020-12-09 09:57
The buttons in the example work for me. However, it seems that the SVG example doesn't, neither does it on my project with child elements:

```
<a class="js-toggle-help" data-bs-placement="bottom" data-bs-toggle="tooltip" title="" data-bs-original-title="Help">
    <span class="visually-hidden">Help</span>
    <i class="fa-fw fad fa-life-ring"></i>
</a>
```

I've done a bit more testing and it seems like if you stay on the element with the tooltip(s) assigned it works, but if you then hover over the child element the tooltip breaks for that (parent) element and doesn't reappear.

**Comment by XhmikosR** [comment] 2020-12-14 11:33
It seems the issue is caused by the popper 2.x update.

I still don't get why the above happens https://github.com/twbs/bootstrap/issues/32372#issuecomment-740642835

**Comment by pwagsc** [comment] 2020-12-23 01:00
Issue is that BS5 is starting to process a tooltip “leave” before the fade delay expires on the previous 'enter/show' (thus the ‘complete’ function has not been executed yet).  So BS starts processing the 'leave' and the show complete occurs immediately after the leave executes its leave transition. (alternatively a show may kick off before a leave executes its complete)  Depending on timing this sometimes causes the tooltip object to be deleted but the tooltip element remains in the show state.  So the 'enter' and 'leave' will not execute (enter because the element says its showing and leave because the tooltip object has been destroyed).   WORKAROUND: Simply add data-bs-animation='false'  and everything works fine.  I will leave it to you to add appropriate code to flag a previous show or hide is pending and process the new request appropriately (kill the animation event and execute the complete before processing new event or queue the events??).  BTW - this is also why it fails more often where elements are nested because rapid transitions in and out of hover occur in constrained areas.

**Comment by Swiftless** [comment] 2020-12-23 01:10
Can confirm the above workaround from @pwagsc, I had quick hovers of the trigger element causing the tooltip to stay visible (instead of disappearing) but it appears to be related if not another result of the same issue defined in the ticket.

**Comment by GeoSot** [comment] 2020-12-24 13:47
**Two possible solutions**, both exclude many fallback tooltip placements on popper .
If the option is omitted, it enables to flip only in the opposite side. (which is not so bad)

Two branches to test it:
a) https://github.com/GeoSot/bootstrap/tree/fix-tooltip-2 

* minimum changes that works

b) https://github.com/GeoSot/bootstrap/tree/fix-tooltip 
 
* more changes, removing too many extra actions that are not needed. 
* one problem, the side arrows on first load are not centered, which can be solved with css



I avoided to open PR not to mess things. If you want me to open a PR, please tell me.

**Comment by septatrix** [comment] 2020-12-24 14:49
It seems like it should be possible to internally track whether or not a transition is currently in progress and if e.g. 'show' finishes while 'leave' is already fired it should not modify classes etc.

**Comment by XhmikosR** [comment] 2021-01-22 14:03
No news, the issue is still not fixed yet.

**Comment by javierartero** [comment] 2021-01-26 12:25
This error happened to me when I clicked on the tooltip, I added this in the CSS and it seems to work:

```
.tooltip {
  pointer-events: none;
}
```

I think it could be added directly to the tooltip if you don't see any inconvenience.

**Comment by septatrix** [comment] 2021-01-26 14:16
> This error happened to me when I clicked on the tooltip, I added this in the CSS and it seems to work:
> 
> ```
> .tooltip {
>   pointer-events: none;
> }
> ```
> 
> I think it could be added directly to the tooltip if you don't see any inconvenience.

This still does not fix the issue.

**Comment by lawgsy** [comment] 2021-01-29 23:11
Hello.
As for tooltips (I have not tried out bootstrap (and therefore popper's) popovers):

https://popper.js.org/docs/v2/tippy/ states:
> As explained in the introduction, Popper has a sole goal: position elements. That's why we call it a "positioning engine" and not a "tooltip library".

Manually disabling the animations in bootstrap (in the initialisation phase) seems to fix the tooltips only showing once or a few times for me:
```
var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
  return new bootstrap.Tooltip(tooltipTriggerEl, {
    animation: false // <-
  })
})
```

This will obviously disable any kind of (fading) animation.

**Using Tippy instead seems to work fine for me.** The tooltips show reliably and fading works. I have yet to try customisation.

**Comment by septatrix** [comment] 2021-01-30 13:16
@lawgsy If you read the above comments you should see that cause of the issue has already been found. It is indeed due to animations. More specifically hiding the tooltip when the show animation is still in progress and vice versa seems to be the root cause. This is due to some assumptions about active classes on the element which gets inconsistent when the above event happen simultaneously.

Using tippy would simplify this however it would also introduce a new dependency and increase bundle size by a lot as most features would not be used by bootstrap. You can however still use tippy if you want those features.

No one however has yet taken the time to look at this more in depth AFAIK. If you know a good way to solve this issue you are free to contribute though I guess the bootstrap team is working on other issues at the moment and so am I. The solution is probably as simple as either introduce a new check or removing a superfluous one by what it looks like. But you can be certain that this will be fixed before the release.

**Comment by pytchoun** [comment] 2021-02-04 00:00
i confirm i have this bug

**Comment by Jas-n** [comment] 2021-02-11 08:48
Hi Guys,
Seems there's still an issue relating to [my above comments](https://github.com/twbs/bootstrap/issues/32372#issuecomment-741664210), replicable on the official [SVG example](https://getbootstrap.com/docs/5.0/components/tooltips/#examples).

**Comment by Mister-42** [comment] 2021-02-11 08:50
> Hi Guys,
> Seems there's still an issue relating to [my above comments](https://github.com/twbs/bootstrap/issues/32372#issuecomment-741664210), replicable on the official [SVG example](https://getbootstrap.com/docs/5.0/components/tooltips/#examples).

The issue is still open, so ... yes

**Comment by Jas-n** [comment] 2021-02-11 08:55
> > Hi Guys,
> > Seems there's still an issue relating to [my above comments](https://github.com/twbs/bootstrap/issues/32372#issuecomment-741664210), replicable on the official [SVG example](https://getbootstrap.com/docs/5.0/components/tooltips/#examples).
> 
> The issue is still open, so ... yes

Sorry, didn't finish reading "What's Next" :)

**Comment by joeforjoomla** [comment] 2021-02-12 09:08
Just checked the Beta 2 version but the problem with tooltips changed but it's still here! Now when the pointer enters an element with a tooltip on the same side of the tooltip, as a result the tooltip and the arrow are broken and divided, the main tooltip body is positioned outside in a wrong position or disappears.

**Comment by ffoodd** [comment] 2021-02-12 10:14
@joeforjoomla We know, that's why the issue is still opened.

**Comment by RyanBerliner** [comment] 2021-03-06 01:41
I may be wildly over simplifying this but an extra check before completing the hide transition seems to work for me https://github.com/RyanBerliner/bootstrap/commit/c2ece10f4bda37029931e0b17078936ac1dae23a

**Comment by XhmikosR** [comment] 2021-03-06 05:50
@RyanBerliner can you please add a test case and if it passes submit a PR?

**Comment by RentecTravis** [comment] 2021-03-11 20:40
I think this and #32897 may have the same root cause.

**Closed** 2021-03-16 05:48 UTC
Labels: confirmed, help wanted, v5

**Comment by davemj88** [comment] 2022-02-09 14:58
> Issue is that BS5 is starting to process a tooltip “leave” before the fade delay expires on the previous 'enter/show' (thus the ‘complete’ function has not been executed yet). So BS starts processing the 'leave' and the show complete occurs immediately after the leave executes its leave transition. (alternatively a show may kick off before a leave executes its complete) Depending on timing this sometimes causes the tooltip object to be deleted but the tooltip element remains in the show state. So the 'enter' and 'leave' will not execute (enter because the element says its showing and leave because the tooltip object has been destroyed). WORKAROUND: Simply add data-bs-animation='false' and everything works fine. I will leave it to you to add appropriate code to flag a previous show or hide is pending and process the new request appropriately (kill the animation event and execute the complete before processing new event or queue the events??). BTW - this is also why it fails more often where elements are nested because rapid transitions in and out of hover occur in constrained areas.

THANK YOU!!!!!!!!! adding data-bs-animation='false' works like a charm.
