### ISSUE TITLE
Everything is turned to black when printing

### ISSUE THREAD

**Issue by action-this-day** [twbs/bootstrap#16713] opened 2015-06-26 12:10 UTC
Why does bootstrap turn every color to black when printing? Is there a way to disable that? I think this should be optional, I want to be able to print colors on my page.
I've attached a screenshot of my problem.
This is how it looks on print:
![screenshot from 2015-06-26 14 07 43](https://cloud.githubusercontent.com/assets/8231938/8376938/d7c000d0-1c0c-11e5-8c0e-e00c917edf0c.png)

This is how it should look on print:
![screenshot from 2015-06-26 14 09 48](https://cloud.githubusercontent.com/assets/8231938/8376955/0505248a-1c0d-11e5-971e-3dfc64e7bf3e.png)

**Comment by kkirsche** [comment] 2015-06-26 14:22
Thank you for reporting this feature request / change. I don't believe Bootstrap would change this behavior in V3 as this is a major change to the functionality of Bootstrap version 3 which some users may currently rely on or have implemented workarounds for. As V3 is feature frozen due to active V4 development, potentially this is a feature request for V4 which the core team could evaluate and decide the course of action.

This change though comes as a result of HTML5 BP — you can note the original comment:

```css
color: #000 !important; // Black prints faster: h5bp.com/s
```

**Comment by cvrebert** [comment] 2015-06-26 22:17
Duplicate of #14313.

**Closed by cvrebert** 2015-06-26 22:17 UTC
