### ISSUE TITLE
[4.4] form-control generates invalid height property

### ISSUE THREAD

**Issue by ChrisRedButton** [twbs/bootstrap#29768] opened 2019-11-28 13:11 UTC
when using .form-control, the CSS is like this:
```
display: block;
width: 100%;
height: calc(1.6em + 0.75rem2px);
padding: 0.375rem 0.75rem;
font-size: 0.9rem;
font-weight: 400;
line-height: 1.6;
color:
#495057;
background-color:
#ffffff;
background-clip: padding-box;
border: 1px solid
#ced4da;
border-radius: 0.25rem;
transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
```

So `height` becomes `height: calc(1.6em + 0.75rem2px);`.
What I could find was that it has something to do with the `add` mixin:
`node_modules/bootstrap/scss/_variables.scss:503` which says:
`add($input-line-height * 1em, add($input-padding-y * 2, $input-height-border, false)) !default;`

**Comment by Hectix** [comment] 2019-11-28 13:13
Duplicate of #29743

**Closed** 2019-11-28 13:41 UTC
