### ISSUE TITLE
[v4-dev] Removing auto-collapsing from navbar?

### ISSUE THREAD

**Issue by marktopper** [twbs/bootstrap#19641] opened 2016-03-30 12:03 UTC
In the [pull](https://github.com/twbs/bootstrap/pull/17021) it seems that the support for auto collapsing navbars are gone.

May I ask why and will there come an alternative to this?

I believe that many of us using bootstrap really liked that they didn't had to think much about the size of the menu, but without this feature we will have to make some custom Javascript in order to get the same result or using media queries, but using media queries would require that the navbar is not dynamic.

**Comment by cvrebert** [comment] 2016-03-31 00:52
Duplicate of #17250. It's on the todo list.

**Closed by cvrebert** 2016-03-31 00:52 UTC
Labels: css, v4
