### ISSUE TITLE
Darkmode: `btn-outline-dark` is not visible in button group component

### ISSUE THREAD

**Issue by teaca-sebastian** [twbs/bootstrap#37753] opened 2022-12-29 06:20 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://getbootstrap.com/docs/5.3/components/button-group/#sizing
https://getbootstrap.com/docs/5.3/components/buttons/

The bug is pretty self-explainatory, this happens because `.btn-light .btn-dark .btn-outline-light & .btn-outline-dark` don't change with `data-bs-theme="dark"`, and there is no "body" color to change along with the data attribute. To properly solve this issue .btn-body and .btn-outline-body classes should be added to complement the darkmode feature.

![Screenshot_20221229_075540](https://user-images.githubusercontent.com/120113707/209909914-92618c21-ed42-49b8-9a58-c2a8ae77a8a2.png)
![Screenshot_20221229_075548](https://user-images.githubusercontent.com/120113707/209909938-60edbc7e-54f3-432e-bc67-e240bae63bf6.png)

### Reduced test cases

See above

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

v5.3

**Comment by julien-deramond** [comment] 2022-12-29 06:59
FYI case 2 is a duplicate of https://github.com/twbs/bootstrap/issues/37711. It can be removed from your description. However I don't think case 1 has already been mentioned somewhere. Thanks for that @Teaca-Sebastian

**Closed** 2022-12-29 20:28 UTC
Labels: docs, v5, color mode

**Comment by threehymns** [comment] 2023-01-27 18:28
@mdo, for the purposes of other sites using bootstrap, we should still add something like `.btn-outline-body` and `.btn-body` for buttons with neutral colors that adapt to dark mode. I honestly don't like those tag names much as they sound too generic because the `body` part does not sound like a color, so I might suggest something like `.btn-outline-monochrome` or `.btn-monochrome`.

**Comment by jrief** [comment] 2024-12-09 13:37
In my opinion Bootstrap should offer some button styles which adopt automatically to either light or dark mode.

In one of my projects, I implemented the styles https://github.com/ngblaylock/bootstrap-extensions/blob/main/src/scss/_btn-contrast.scss and they work perfectly in both modes. I don't get the point, why Bootstrap doesn't offer these styles out of the box themselves.
