### ISSUE TITLE
Drop down list should be auto adjust at top position

### ISSUE THREAD

**Issue by sadashivm** [twbs/bootstrap#22479] opened 2017-04-20 11:56 UTC
Hi Team,
This is one of the best framework for build web application. one thing i have seen drawback of dropdown list . for example i am showing a drop down in reg form at end of the form.if scrolled down form at end of the form then dropdown list should come at top position when form is reached window screen. 
anyway default list come at bottom postion if form screen is reached to window screen then automatically list should display at top.

**1. Normal Mode** 
![capture](https://cloud.githubusercontent.com/assets/10355473/25229491/202088b2-25ee-11e7-84af-dc2d86924c1b.PNG)

**2. When Dropdown reached window screen**

![capture2](https://cloud.githubusercontent.com/assets/10355473/25229549/57996a84-25ee-11e7-89ca-408571bfb532.PNG)

**Comment by wojtask9** [comment] 2017-04-20 15:15
Done in this PR https://github.com/twbs/bootstrap/pull/22444 :)

**Comment by Johann-S** [comment] 2017-04-20 19:22
Not implemented in my PR @wojtask9 
But yes it's a good idea I'll implement that tomorrow 👍

**Comment by wojtask9** [comment] 2017-04-20 21:23
@Johann-S 
are you sure ? 
Popper.js solves this case out of box (default flip behavior). So with my tests and source reading it should work or maybe i don't understand this Issue?

**Comment by Johann-S** [comment] 2017-04-20 21:26
Yes you're totally right Popper handle that natively my bad I'm a bit tired

**Comment by wojtask9** [comment] 2017-04-20 21:32
totally understand you.
BTW info about this behavior can be added do BS docs because now doc only mention about dropdown using popper.js and not explain why.

**Comment by FezVrasta** [comment] 2017-04-21 07:57
I noticed that the dropdowns documentation page is a bit confusing now that the flip behavior is on by default.

The docs mention about `dropdown` and `dropup`, but now the distinction isn't very clear because of it.
You could open a dropdown and see it as a dropup because of the position in the page and vice-versa.

**Comment by IdanCo** [comment] 2017-04-24 08:13
@sadashivm , no doubt a native solution like the one in @Johann-S PR would be the best solution, but meanwhile you might find useful this little piece of code i've wrote to achieve the same behavior in the current (soon to be departed) library -

```js
  setDropDirection() {
    const canDropDown = this.menuHeight < this.distanceFromBottom;
    this.elememt.toggleClass('dropdown', canDropDown);
    this.elememt.toggleClass('dropup', !canDropDown);
  }

  get menuHeight() {
    return $('.dropdown-menu', this.elememt).height();
  }

  get distanceFromBottom() {
    const windowHeight = window.innerHeight;
    const distanceFromWindowTop = this.elememt.offset().top - $(document).scrollTop();
    const elementHeight = this.elememt.height();

    return windowHeight - distanceFromWindowTop - elementHeight;
  }
```
(it's part of an angularJS component, but i hope the basic mechanism is clear)

**Comment by Johann-S** [comment] 2017-05-04 10:52
Duplicate of #17167

**Closed by Johann-S** 2017-05-04 10:52 UTC
Labels: js, v4
