### ISSUE TITLE
v4 input-group-sm issues

### ISSUE THREAD

**Issue by jacobp100** [twbs/bootstrap#17160] opened 2015-08-20 19:46 UTC
1. ~~Does not work with `$enable-rounded: false`~~
2. Middle items remain rounded

**Comment by cvrebert** [comment] 2015-08-21 04:35
(1) Was fixed by #17161.

**Comment by cvrebert** [comment] 2015-12-15 08:03
> Middle items remain rounded

Unable to reproduce with Bootstrap v4.0.0-alpha.2 on OS X Chrome.

**Closed by cvrebert** 2015-12-15 08:03 UTC
Labels: css, v4
