### ISSUE TITLE
Offcanvas button does not work if it contains HTML tags.

### ISSUE THREAD

**Issue by SamThilmany** [twbs/bootstrap#33776] opened 2021-04-27 16:39 UTC
- Operating system and version: macOS 10.15.7
- Browser and version: Safari 14.0.3
- A [reduced test case](https://jsfiddle.net/h5aefdqn/3/)

The new `offcanvas` component is triggered by a link with the `href` attribute or a button with the `data-bs-target` attribute. However, if the link/button contains other HTML tags, *e.g.* an icon like `<span class="navbar-toggler-icon"></span>` chances are, that the user ends up clicking on the icon. If he does so, the offcanvas will not be triggered. It only works if the border of the link/button is clicked, *i.e.* outside of the included HTML tag. I suppose that the responsible JS function uses the `event.target` instead of `event.currentTarget` but I'm not sure about this.

Have a look at the attached [reduced test case](https://jsfiddle.net/h5aefdqn/3/) to see this bug in action.

**Comment by alpadev** [comment] 2021-04-27 18:18
Fixed by https://github.com/twbs/bootstrap/pull/33545
Duplicate of https://github.com/twbs/bootstrap/issues/33614 https://github.com/twbs/bootstrap/issues/33654 https://github.com/twbs/bootstrap/issues/33477 https://github.com/twbs/bootstrap/issues/33457

**Closed by alpadev** 2021-04-27 18:18 UTC
