### ISSUE TITLE
nav-justified displays  incorrect in safari 9.1.2

### ISSUE THREAD

**Issue by zhou9197** [twbs/bootstrap#20342] opened 2016-07-22 03:20 UTC
link: http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_tabs_pills_justified&stacked=h 
1. open the link with safari and chrome 
2. resize the window size and make it < 768px and resize back ( > 768px)
3. chrome displays the tabs by one row but safari displays the tabs by 2 rows which is not expected.

**Comment by cvrebert** [comment] 2016-07-22 04:05
Duplicate of #9774.
[Known Safari bug](https://bugs.webkit.org/show_bug.cgi?id=138167), already mentioned in the docs: http://getbootstrap.com/components/#nav-justified
Thankfully, the bug is fixed in the current Safari Technology Preview version.

Sidenote: Protip: Avoid w3schools.

**Closed by cvrebert** 2016-07-22 04:05 UTC
Labels: browser bug, css, v3
