### ISSUE TITLE
Add input group example to the docs

### ISSUE THREAD

**Issue by vanillajonathan** [twbs/bootstrap#30204] opened 2020-02-17 12:44 UTC
Add an example to the documentation when using both `.input-group-prepend` and `.input-group-append` together to create an input group with "the extra" between two inputs.

## Example 1
```html
<div class="input-group">
  <input class="form-control" type="text" />
  <div class="input-group-prepend input-group-append">
    <div class="input-group-text">@</div>
  </div>
  <select class="form-control"></select>
</div>
```

## Example 2
```html
<div class="input-group">
  <input class="form-control" type="date" />
  <div class="input-group-prepend input-group-append">
    <div class="input-group-text">–</div>
  </div>
  <input class="form-control" type="date" />
</div>
```

**Comment by ysds** [comment] 2020-02-17 13:30
Duplicate of #25120

**Closed by ysds** 2020-02-17 13:30 UTC
