### ISSUE TITLE
Will Bootstrap 3 support jQuery 3?

### ISSUE THREAD

**Issue by lipis** [twbs/bootstrap#20168] opened 2016-06-24 12:07 UTC

**Comment by Florian-R** [comment] 2016-06-24 12:25
#19433

**Comment by lipis** [comment] 2016-06-24 12:41
@Florian-R I think the question is very clear that is about Bootstrap v3..

**Comment by Florian-R** [comment] 2016-06-24 12:46
@lipis My bad, misread it. You might want to take a look at #16834

**Comment by cvrebert** [comment] 2016-06-24 17:34
Duplicate of #16834.

**Closed by cvrebert** 2016-06-24 17:34 UTC
Labels: js, meta, v3
