### ISSUE TITLE
conflict with font-awesome 4 on modals

### ISSUE THREAD

**Issue by jroxonline** [twbs/bootstrap#17534] opened 2015-09-08 22:22 UTC
when using the modal option for V4 and font-awesome css icons are loaded, the whole page shifts to the left when loading a modal.

**Comment by mdo** [comment] 2015-09-08 23:11
That's now a unique problem with Font Awesome as far as I can tell. Without a live example, it seems like a dupe of #14040 and the like.

**Closed by mdo** 2015-09-08 23:11 UTC
