### ISSUE TITLE
Modal Background

### ISSUE THREAD

**Issue by hn1** [twbs/bootstrap#15575] opened 2015-01-15 16:10 UTC
If the contents of a modal is taller than the browser viewport, when you scroll, the black background is cut-off. Only if you re size the browser, does the backdrop fill the window.

**Comment by juthilo** [comment] 2015-01-15 16:29
Duplicate of #15574. Please note that you can edit anything you post or comment on GitHub by clicking the small pencil icon in the upper right corner of something you wrote.

**Closed by juthilo** 2015-01-15 16:29 UTC
