### ISSUE TITLE
.caret rendering problem in Firefox

### ISSUE THREAD

**Issue by bangive** [twbs/bootstrap#16657] opened 2015-06-17 11:02 UTC
![caret_error](https://cloud.githubusercontent.com/assets/11285347/8205472/3e633bd4-151b-11e5-8e7d-e7f58014ff6a.png)
Link for demonstrating problem: http://jsbin.com/wifike/2/edit?html,css,output
This happend in Firefox 38.0.5 on Windows 7.
The border-top css value of caret in dropdown.less is "dashed" so it is displayed wrong in firefox. When i change the value to "solid" it is displayed right.

**Comment by kkirsche** [comment] 2015-06-17 11:12
This was changed to `dashed` due to #15682

**Comment by clarkdemvher** [comment] 2015-06-17 11:38
On Jun 17, 2015 7:04 PM, "bangive" <notifications@github.com> wrote:
>
> This happend in Firefox 38.0.5 on Windows 7.
> The border-top css value of caret in dropdown.less is "dashed" so it is
displayed wrong in firefox. When i change the value to "solid" it is
displayed right.

**Comment by cvrebert** [comment] 2015-06-17 11:39
@bangive Please post a [JS Bin](http://jsbin.com) example demonstrating the problem.

**Comment by cvrebert** [comment] 2015-06-23 18:21
@bangive I can't reproduce this in Win 7 Firefox 38.0.5 on Sauce Labs:
![ff38-win7](https://cloud.githubusercontent.com/assets/419884/8313804/e69727a2-1999-11e5-9e52-9f84ac309a7d.png)
Can you post your original example with the UK flag?

**Comment by PaulBGD** [comment] 2015-06-24 03:08
I can't see it on 38.1

**Comment by bangive** [comment] 2015-06-24 05:02
This is the original code that has caret rendering problem http://jsbin.com/yesuvu/2/edit?html,output
The flag does not show because i don't include svg file. If you want i will include svg file.

**Comment by cvrebert** [comment] 2015-07-03 03:57
@kkirsche You didn't attempt to reproduce this, right?

**Comment by cvrebert** [comment] 2015-07-03 04:02
Still can't reproduce the problem, even with the new JS Bin:
![shot1](https://cloud.githubusercontent.com/assets/419884/8492358/51f77eb0-20fd-11e5-8b32-40f14c938425.png)
and even after zooming in:
![shot2](https://cloud.githubusercontent.com/assets/419884/8492364/64b47c56-20fd-11e5-82b4-fefca6edcf7e.png)

So, going to close this until/unless someone manages to repro it.

**Closed by cvrebert** 2015-07-03 04:02 UTC
Labels: css

**Comment by kkirsche** [comment] 2015-07-03 04:42
@cvrebert tried but wasn't able to. Must have gotten distracted and forgot to post that. Sorry about that!
