### ISSUE TITLE
Missing new version after 6 months

### ISSUE THREAD

**Issue by mohandes** [twbs/bootstrap#23033] opened 2017-07-09 22:19 UTC
I want to point out a very important issue, and this is why bootstrap has not yet provided any new version after six months. I know that you have every day trying to overcome the flaws. But there are a lot of people around the world, like myself, we want to start a new project using Bootstrap 4, but unfortunately, there is still no reassurance version.
I check every day whether a new version will be unveiled! But I'm disappointed each day.
Let us know at least a little how long should we wait?

**Comment by cr101** [comment] 2017-07-09 22:33
Duplicate of #[23027](https://github.com/twbs/bootstrap/issues/23027)

**Comment by mdo** [comment] 2017-07-09 23:37
We'll release our beta when we're ready.

**Closed** 2017-07-09 23:37 UTC
