### ISSUE TITLE
Tab children of .dropup do not lose active class when other tabs selected

### ISSUE THREAD

**Issue by jblesage** [twbs/bootstrap#18660] opened 2015-12-24 17:49 UTC
If you select the child tab of a .dropup, then select another tab, the originally selected tab will not remove it's .active class. 

This only applies to children of a .dropup, children of a .dropdown are not affected by this bug. This applies to Bootstrap v3.3.6, unconfirmed for other versions.

Interim solution: 

```javascript
$('a[data-toggle="tab"]').on('hidden.bs.tab', function (e) {
    $(e.currentTarget.parentNode).removeClass('active')
})
```

**Comment by cvrebert** [comment] 2015-12-24 21:26
Duplicate of #16913.

**Closed by cvrebert** 2015-12-24 21:26 UTC
