### ISSUE TITLE
Illegal invocation error when modal has word model in id

### ISSUE THREAD

**Issue by jaystacey** [twbs/bootstrap#32652] opened 2020-12-30 07:09 UTC
OK:

`<div class="modal fade" id="header_search" tabindex="-1" aria-labelledby="headerSearchModalLabel"  aria-hidden="true">
`

Not OK:

`<div class="modal fade" id="header_search_modal" tabindex="-1" aria-labelledby="headerSearchModalLabel"  aria-hidden="true">`

**Comment by rohit2sharma95** [comment] 2021-01-03 09:16
Can you please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and Operating System details. :slightly_smiling_face:

**Comment by mdo** [comment] 2021-01-05 19:08
`modal` is in the IDs of our size examples in our docs, so that doesn't seem to be the cause of the issue you're running into. https://getbootstrap.com/docs/5.0/components/modal/#optional-sizes

Closing until we hear more with a reduced test case.

**Closed by mdo** 2021-01-05 19:08 UTC
Labels: awaiting-reply
