### ISSUE TITLE
Header Link's href to Link to the Most Recent Version of the Same Article

### ISSUE THREAD

**Issue by rua-iri** [twbs/bootstrap#40732] opened 2024-08-15 05:55 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

When viewing an article from an older version of the Bootstrap documentation there is a link with the text "There's a newer version of Bootstrap!".

![image](https://github.com/user-attachments/assets/3b21f27d-1ab9-4426-8158-93a1e03a087f)

Currently this links to the _homepage_ of version 5.3.

It would be better if this instead linked to the _same article_ from version 5.3.

This should be a matter of slightly modifying the `partial` template where this component is defined.

### Motivation and context

The current link forces the user to navigate to the homepage before returning to the documentation and then locating the same article from the sidebar.

This is also redundant as the logo and the home button both already link to the homepage of the most recent version.

**Comment by Sparsh-06** [comment] 2024-08-15 07:47
Thanks for pointing it out, will work on it.

**Comment by louismaximepiton** [comment] 2024-08-19 07:44
Duplicate of #31980.

**Closed by louismaximepiton** 2024-08-19 07:44 UTC
Labels: feature
