### ISSUE TITLE
Forms input[type=color] element style looks odd

### ISSUE THREAD

**Issue by jeradrutnam** [twbs/bootstrap#20104] opened 2016-06-10 05:52 UTC
Hi,

Noticed above $subject issue in v4-dev source

Current:
![forms bootstrap](https://cloud.githubusercontent.com/assets/7569427/15954641/1a00d520-2ef7-11e6-93f4-cc533b4ced86.png)

Suggestion:
![forms bootstrap2](https://cloud.githubusercontent.com/assets/7569427/15954642/1d359a8c-2ef7-11e6-989b-75193e93b3ae.png)

Also created a PR [1] with a fix for above issue, please review and merge if think its useful

[1] - https://github.com/twbs/bootstrap/pull/20103

Thanks,
Jerad

**Comment by cvrebert** [comment] 2016-06-10 06:49
Duplicate of #18786.

**Closed by cvrebert** 2016-06-10 06:49 UTC
Labels: css, v4
