### ISSUE TITLE
navbar fixed-top, sidebar sticky-top: missing padding-top.

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#26364] opened 2018-04-23 12:32 UTC
Here the reproduction: https://jsbin.com/lawafu/edit?html,output

Is this a bug? A mistake? A problem? An unrealizable idea?

**Before scroll:**
![before](https://user-images.githubusercontent.com/21275217/39126721-57ec229c-4703-11e8-91f4-8a7de5ef046d.PNG)

**After scroll:**
![after](https://user-images.githubusercontent.com/21275217/39126720-57d19620-4703-11e8-81cc-da8c6ce45d5d.PNG)

**What I need**:

Obviously I need to see the sidebar when I scroll down the page, using padding-top of the body for the fixed-top navbar.

**Comment by morrissey-ingenious** [comment] 2018-04-23 16:00
You will need to add your own custom css or modify the .sticky-top top attribute.

ie

```
.app-sticky-top {
  top: 5rem;
}

<div class="sticky-top app-sticky-top">
```

**Comment by Joyrex** [comment] 2018-04-23 23:28
If you look at the [included CSS](https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/sticky-footer-navbar.css) with the sticky-top demo, you'll see the best way to implement a sticky top navbar.

**Comment by mdo** [comment] 2018-04-24 02:14
Closing as not a bug—this is the reality of sticky and fixed positioning in CSS.

**Closed by mdo** 2018-04-24 02:14 UTC
