### ISSUE TITLE
Bootstrap 4 btn-secondary-outline on bg-faded contrast issue

### ISSUE THREAD

**Issue by zackarychapple** [twbs/bootstrap#19731] opened 2016-04-13 20:19 UTC
When you put a `btn-secondary-outline` in a `bg-faded` navbar the contrast makes the button difficult to see.

![screen shot 2016-04-13 at 4 17 21 pm](https://cloud.githubusercontent.com/assets/2133184/14507993/61b67a00-0193-11e6-967d-3bdbd56092d8.png)

**Comment by patrickhlauke** [comment] 2016-04-13 21:24
Agree. approximate duplicate of https://github.com/twbs/bootstrap/issues/17286

**Closed by patrickhlauke** 2016-04-13 21:24 UTC
