### ISSUE TITLE
2px border in .input-group-lg

### ISSUE THREAD

**Issue by partizzzzzan** [twbs/bootstrap#16575] opened 2015-06-02 12:17 UTC
![screencapture_bootstrap](https://cloud.githubusercontent.com/assets/5182989/7935546/7d802634-093a-11e5-8833-f8005daf758f.png)

**Comment by kkirsche** [comment] 2015-06-02 14:34
@partizzzzzan is this stating that it should be `1px` instead of `2px` or something else? If you could provide a more detailed explanation with a JSBin demonstrating the problem that would be greatly appreciated. Thanks!

**Comment by zacechola** [comment] 2015-06-02 16:17
This is a duplicate of #14237.

It's not just `.input-group-lg`. I see this in Chrome (45.0.2416.0 canary 64-bit), as well, specifically on dropdown on the [left side of the group](http://getbootstrap.com/components/#input-groups-buttons-dropdowns). 

![screenshot 2015-06-02 11 11 50](https://cloud.githubusercontent.com/assets/498418/7940733/52c6690c-0918-11e5-9390-99c370b2c163.png)

Don't see it in Firefox or Safari.

The decision in the last issue was to wait and see what Chrome will do.

**Comment by cvrebert** [comment] 2015-06-02 20:40
Nope.

**Comment by mdo** [comment] 2015-06-18 23:16
After playing with this more, I'm pretty confident it's a pixel rounding problem. Not much to do there, and it doesn't seem like something we really need to document anywhere as pixel rounding problems happen in various ways in damned near every browser.

@cvrebert Feel free to reopen if I'm cray.

**Closed by mdo** 2015-06-18 23:16 UTC
Labels: browser bug, confirmed, css

**Comment by cvrebert** [comment] 2015-09-23 21:25
Fixed in Chrome Canary; see https://github.com/twbs/bootstrap/issues/14237#issuecomment-142512236
