### ISSUE TITLE
Font-family issues

### ISSUE THREAD

**Issue by NicoLB** [twbs/bootstrap#21629] opened 2017-01-10 02:21 UTC
`<button>`, `<input>`, '<select>' and '<textarea>' render a different font-family (Helvetica on Mac).
This is due to Normalize v5 using `font-family: sans-serif` (line 257) compare to `font: inherit` in the past.

We can fix this by updating `_reboot.scss` and add `font: inherit` (line 316).

Can anyone see a problem with this?

**Comment by nwoltman** [comment] 2017-01-10 03:13
Dupe of #21588. Related to issue necolas/normalize.css#642 which will be fixed by PR necolas/normalize.css#649.

**Comment by mdo** [comment] 2017-01-10 04:53
Closed as dupe.

**Closed** 2017-01-10 04:52 UTC
Labels: css, v4
