### ISSUE TITLE
v5: Revisit table styles

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#28480] opened 2019-03-13 17:39 UTC
#26678 has conflicts and tried to tackle a ton, so let's revisit style scoping, Sass maps, and more in v5.

**Comment by ysds** [comment] 2020-03-05 15:37
A list of the table style issues:
* Nested table
    * #26678, #29244, #27800, ＃30251
* Color variants
    * #24529 Inconsistent `.table-active` color caused by the opacity
    * #27879 `.table-dark` is used in two conflicting contexts
    * #28160 Hover style for table rows/cells color classes
    * #25675 Table row-variants does not respect font-color
    * #29290 Contextual table classes apply `tr` class instead of `td` class to individual cells
* Others
    * #25057 Table cell padding in card
    * #29244 Table child elements (thead, tbody, tfoot, tr, td, th) should inherit parent background color

**Comment by tmorehouse** [comment] 2020-03-06 00:26
Perhaps a `.table-reset` class for child nested tables to negate the parent class inheritance?

**Comment by dimitor115** [comment] 2020-03-27 18:10
@mdo Sorry but I don’t get it. Even if not many people requested a bug or problem there is still a reason to improve a selectors. Current behavior is just confusing. With not much effort we can provide a better tool. I can prepare the PR for example 😁

**Comment by MartijnCuppens** [comment] 2020-04-26 10:04
https://github.com/twbs/bootstrap/pull/30466 closed this issue

**Closed by MartijnCuppens** 2020-04-26 10:04 UTC
Labels: css, v5
