### ISSUE TITLE
Spacing sizes are a bit counter-intuitive

### ISSUE THREAD

**Issue by entozoon** [twbs/bootstrap#21702] opened 2017-01-13 12:01 UTC
Referring to the spacing sizes explained in:
https://v4-alpha.getbootstrap.com/utilities/spacing/

I was surprised to see that these aren't linear increments `0, 1, 2, 3, etc` as might be expected by the classnames (i.e. p-3 yields 1 spacers worth, rather than 3)

but aside from that, with the pattern they currently have, it looks like they're supposed to double up each increment but they don't - the pattern being `0, 0.25, 0.5, 1, 1.5, 3` which is inconsistent.

Perhaps there's a logical reason?
If not, I've popped in a pull request for a consistent doubling up pattern `0, 0.25, 0.5, 1, 2, 4` although (in my opinion) linear increments might be better, for which I'd happily do a PR if desirable.

https://github.com/twbs/bootstrap/pull/21703

**Comment by Starsam80** [comment] 2017-01-13 16:59
Duplicate of #21342.

**Comment by mdo** [comment] 2017-01-16 05:30
Closing as dupe.

**Closed by mdo** 2017-01-16 05:30 UTC
Labels: css, v4
