### ISSUE TITLE
Documentation search results redirect to v4.0 instead of v4.1

### ISSUE THREAD

**Issue by CyrusVatandoost** [twbs/bootstrap#26549] opened 2018-05-21 15:13 UTC
While in the Bootstrap v4.1 documentation, the search bar redirects the user to v4.0 results instead of the expected v4.1 results.

![image](https://user-images.githubusercontent.com/22030882/40314918-83f3e280-5d4c-11e8-935f-5148eba8c728.png)

**Comment by wolfy1339** [comment] 2018-05-21 17:14
This is a duplicate, please search before making an issue

**Comment by mdo** [comment] 2018-05-21 22:29
Duplicate of #26441.

**Closed by mdo** 2018-05-21 22:29 UTC
