### ISSUE TITLE
Grid issue safari and ucbrowser.

### ISSUE THREAD

**Issue by carloboy16** [twbs/bootstrap#23218] opened 2017-08-04 03:52 UTC
Hello the i have a problem on gridding system the the column is adjusting the width but its not wrapping instead its overflowing
see the site in safari
https://eiexchange.com.au/index.php#

**Comment by Johann-S** [comment] 2017-08-04 07:53
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by nimmolo** [comment] 2017-08-04 17:33
Possible duplicate of #23193

**Comment by mdo** [comment] 2017-08-04 21:12
Closing as duplicate of #23193.

**Closed by mdo** 2017-08-04 21:12 UTC
Labels: awaiting reply, css
