### ISSUE TITLE
ReferenceError: event is not defined using modal('show')

### ISSUE THREAD

**Issue by lhoezee** [twbs/bootstrap#18917] opened 2016-01-17 17:45 UTC
Using version 3.3.6 I'm getting the following error. I searched the issues and did not find anything for this fix.  It was not happening before I just updated to 3.3.6 last night. I do not recall the exact version I was before.

![ReferenceError: event is not defined](https://d1ro8r1rbfn3jf.cloudfront.net/ms_85506/rteKC7hue41RdeLTGrv8GIN9kQmiqe/Edit%2BCapture%2BPages%2B%257C%2BCapture%2BPage%2BHosting%2B2016-01-17%2B12-39-07.png?Expires=1453138802&Signature=e85PM152WvmOQYPrE3kX0va2iayQJKCJXw4prjSYu2MjuatGsV2qLN-f7FtZwuuD7qqXPOV7ot379GBP08cvm4hE-tpFWUwa~vBcXVilKMPtUhOAkzVqZO0KpLEwwWQnkZHBMH2Y8o7E2sngrdQGHeXZ03buvwAjtQeTmyGEGO1FwKv~pMomAQhq4eqehBhYS6bbOXTxas85PZ1~Lfe7-Fg~0JUjPVSzvJVjRlJI7quP6l97Znld-k396o9klcRjJ~Nl5LBjWGx7KTNyMMvTpEO52IRJTuGluHhAiMsZyXSyOuDaX6W6WwPLL040qs7WX2y2vRWzFWm2KJIjpwXFFw__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

This screenshot shows my suggested change:

![Suggested Fix](https://d1ro8r1rbfn3jf.cloudfront.net/ms_85506/UBchYBRacjn7aEvnlvPiF3rvwwqj5V/Edit%2BCapture%2BPages%2B%257C%2BCapture%2BPage%2BHosting%2B2016-01-17%2B12-40-59.png?Expires=1453138899&Signature=XynGz3Zg9e3ccS2UYeHLyTXlfh4T~A4bs92QJu0lKYdHJMjhEo0shReD4dFGyz873PtT8IBXfZ36YcVwNJjCxsvx6ZPD6GY~eK0MuoKamEyXDq5m9susR-qk1qb8vMVzDuhdHl5WMq7YSrI8KBLFGJPs2KWNzUfviD4Z9pX6d0~XG2GuhE~3PXsAFGl2ZmGXJ9~bAd5m8ELYDR8yi~hfJF~VR4NpZVEPNc1biXzI5caTZKm1hnuTz8pTlYvi9BJA8UUxhTG8HNqGQxhBHrFe9qTb1bUQikPDYLtMnHPEumMB3QF6Bt~SKXSph9bYHv1Fyw4pk9VPjTKhoCoSgRg5NA__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)

Thank you. Let me know if you need anything else from me. I'm also using JQuery 2.2.0

**Comment by cvrebert** [comment] 2016-01-17 20:03
Duplicate of #18908.

**Closed by cvrebert** 2016-01-17 20:03 UTC
