### ISSUE TITLE
[BUG] longer navbar when open modal

### ISSUE THREAD

**Issue by BlackYuzia** [twbs/bootstrap#28090] opened 2019-01-18 19:43 UTC
### About PC
- Operating system and version: **Windows 7**
- Browser and version: **Chrome 71.0.3578.98 (x64)**
### Info
What I use when trap on it - https://pastebin.com/CCYbaU1n
#### About Bug
I create a **Nav-Bar**.
Next, I create a **Modal** (window).
Next, I add class **sticky-top** to **Nav-Bar**.
Next, I open a **Modal**, and get some ... fail? (check screenshot №2)

_I try remove class **sticky-top**, and without this class I don't have this bug._

#### Screenshoots
**Normal state:**
![image](https://user-images.githubusercontent.com/25010528/51409256-f6582a80-1b69-11e9-9f13-a4623af11410.png)
**After open modal window:**
![image](https://user-images.githubusercontent.com/25010528/51409259-fbb57500-1b69-11e9-8fe5-a5ba9f64af5f.png)

**Comment by CrazyHackGUT** [comment] 2019-01-18 19:47
Can confirm.
Windows 7 (build 7601), Firefox 64.0.2

**Comment by Johann-S** [comment] 2019-01-21 12:30
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

*This is an automated reply*

**Comment by ysds** [comment] 2019-01-22 15:55
Duplicate of #27071

**Comment by SharakPL** [comment] 2019-01-29 21:15
The problem + the fix: https://codepen.io/SharakPL/pen/OdRayP but the real fix would be to leave padding and margin untouched and position with `right` property

**Comment by XhmikosR** [comment] 2019-02-06 10:22
Closing as duplicate of #27071

**Closed by XhmikosR** 2019-02-06 10:22 UTC
Labels: awaiting reply
