### ISSUE TITLE
Issue in col-xs-* grid for mobile while nesting.

### ISSUE THREAD

**Issue by rakeshmali** [twbs/bootstrap#15871] opened 2015-02-23 13:03 UTC
When i created col-xs-* class as parent class another child class as nested of it
and I run this code to mobile, the "inside row" failed down in the next row, while i used a class="row" as its parent.

![selection_001](https://cloud.githubusercontent.com/assets/8438390/6328088/9ac8f008-bb89-11e4-8279-89e169a65a57.png)

And again when i changed the "col-xs-1" and "col-xs-5" to "col-xs-2" and "col-xs-4" respectively, then it is working fine.
Like:
![selection_002](https://cloud.githubusercontent.com/assets/8438390/6328089/9c1dbd12-bb89-11e4-81e5-156e71a1cf41.png)

The issue is in the calculation of the values of "col-xs-1" and "col-xs-5", when they are nested.

**Comment by kkirsche** [comment] 2015-02-23 13:41
Would you be able to post a JSBin of the problem for us?

**Comment by cvrebert** [comment] 2015-02-24 04:12
I speculate that this is basically a duplicate of #13221.

**Comment by rakeshmali** [comment] 2015-02-24 05:17
SO, where is the solution for that?

On Tue, Feb 24, 2015 at 9:44 AM, Chris Rebert <notifications@github.com>
wrote:

> I speculate that this is basically a duplicate of #13221
> <https://github.com/twbs/bootstrap/issues/13221>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/15871#issuecomment-75696670>.
>



-- 
--
Thanks

*Rakesh Mali*
Web Developer
Ready Bytes Software Labs Bhilwara, India

**Comment by cvrebert** [comment] 2015-02-27 02:57
>> SO, where is the solution for that?
>
> [For those who need it, you have basically one option: remove or modify the padding on `.col-xs-1`.](https://github.com/twbs/bootstrap/issues/13221#issuecomment-48101157)

Closing as a duplicate.

**Closed by cvrebert** 2015-02-27 02:57 UTC
Labels: css
