### ISSUE TITLE
new version of bs beta2 - breaks jekly compiler with the addition of the new file _root.scss

### ISSUE THREAD

**Issue by geetee24** [twbs/bootstrap#24845] opened 2017-11-21 18:38 UTC
previous beta-1 built fine with jekly
now v2 beta crashes during build due to inclusion of _root.scss.
is that file needed?

**Comment by wolfy1339** [comment] 2017-11-21 18:42
Duplicate of #24368 and #24549

**Closed** 2017-11-21 18:44 UTC
