### ISSUE TITLE
The size of .input-group contents does not change the size correctly when using the relative form sizing classes

### ISSUE THREAD

**Issue by w0pke** [twbs/bootstrap#17109] opened 2015-08-20 09:02 UTC
![bs-input-group-sizing](https://cloud.githubusercontent.com/assets/10436866/9379469/d90596ce-4729-11e5-8d35-c33bd7b2a9f2.JPG)

```
<div class="input-group input-group-lg">
  <span class="input-group-addon" id="sizing-addon1">@</span>
  <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon1">
</div>
<br>
<div class="input-group">
  <span class="input-group-addon" id="sizing-addon2">@</span>
  <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon2">
</div>
<br>
<div class="input-group input-group-sm">
  <span class="input-group-addon" id="sizing-addon3">@</span>
  <input type="text" class="form-control" placeholder="Username" aria-describedby="sizing-addon3">
</div>
```

**Comment by cvrebert** [comment] 2015-08-20 09:08
Duplicate of #17035. Please search more next time.

**Closed by cvrebert** 2015-08-20 09:08 UTC
