### ISSUE TITLE
form-control-static makes a long text of textarea input to overflow

### ISSUE THREAD

**Issue by Yog** [twbs/bootstrap#17691] opened 2015-09-24 10:04 UTC
![textareatext](https://cloud.githubusercontent.com/assets/432220/10070570/97cb584c-62b3-11e5-96c8-0bdba991eabc.png)
If
```
.form-group-sm .form-control-static {
    height: 30px;
}
```
was
```
.form-group-sm .form-control-static {
    min-height: 30px;
}
```
instead, then there would be no problem. 

html:
```
        <div class="form-group form-group-sm">
            <label for="" class="col-xs-2 control-label">Nazwa</label>
            <div class="col-xs-4 form-control-static">
                <span>Opis at g sr g</span>
            </div>
            <label for="" class="col-xs-2 control-label">Adres</label>
            <div class="col-xs-4 form-control-static">
                <span>Opis at g sr g</span>
            </div>
        </div>
        <div class="form-group form-group-sm">
            <label for="" class="col-xs-2 control-label">Description</label>
            <div class="col-xs-10 form-control-static">
                <span>Opis awer aerter t ert er tsrt g sr gOpis awer aerter t ert er tsrt g sr gOpis awer aerter t ert er tsrt g sr gOpis awer aerter t ert er tsrt g sr gOpis awer aerter t ert er tsrt g sr gOpis awer aerter t ert er tsrt g sr gOpis awer aerter t ert er tsrt g sr gOpis awer aerter t ert er tsrt g sr gOpis awer aerter t ert er tsrt g sr gOpis awer aerter t ert er tsrt g sr gOpis awer aerter t ert er tsrt g sr gOpis awer aerter t ert er tsrt g sr g</span>
            </div>
        </div>

        <div class="form-group form-group-sm">
            <div class="col-xs-offset-2 col-xs-10">
                <button class="btn btn-primary" name="submit" type="submit">Zapisz organizację</button>
            </div>
        </div>
```

**Comment by perrosen** [comment] 2015-10-07 09:41
Hi all,

I have tested this on my local and can reproduce it. This same issue also appears when using form-group-lg.

In terms of the fix it seems that the min height is already there for both these cases. The height just needs to be removed though which would solve the issue.

```CSS
.form-group-lg .form-control-static {
    /* height: 46px; */
    min-height: 38px;
    padding: 11px 16px;
    font-size: 18px;
    line-height: 1.3333333;
}
```

```CSS
.form-group-sm .form-control-static {
    /* height: 30px; */
    min-height: 32px;
    padding: 6px 10px;
    font-size: 12px;
    line-height: 1.5;
}
```

```HTML
<div class="form-group form-group-lg">
    <label for="" class="col-xs-2 control-label">Description</label>
    <div class="col-xs-10 form-control-static">
      <span>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam ipsam asperiores neque, porro doloribus omnis, repellat expedita! Possimus eos, hic, earum ipsam, officia at sint expedita fugit modi, repudiandae eligendi!
            </span>
    </div>
  </div>

  <div class="form-group form-group-sm">
    <div class="col-xs-offset-2 col-xs-10">
      <button class="btn btn-primary" name="submit" type="submit">Zapisz organizację</button>
    </div>
  </div>

  <div class="form-group form-group-sm">
    <label for="" class="col-xs-2 control-label">Description</label>
    <div class="col-xs-10 form-control-static">
      <span>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam ipsam asperiores neque, porro doloribus omnis, repellat expedita! Possimus eos, hic, earum ipsam, officia at sint expedita fugit modi, repudiandae eligendi!
            </span>
    </div>
  </div>

  <div class="form-group form-group-sm">
    <div class="col-xs-offset-2 col-xs-10">
      <button class="btn btn-primary" name="submit" type="submit">Zapisz organizację</button>
    </div>
  </div>
```

I will have a go on this one. But since this would be my first contribution to any project I will not assign it to myself. If someone feels the need to do this before me then be my guest :) Might take some time for me. Will fork and get the process started. Let me know if I have misunderstood or missed something.

Cheers,
Per

**Comment by mdo** [comment] 2015-11-15 04:47
Closing as a won't fix since this class is largely meant to be used as a replacement for `<input>`s, not `<textareas>`.

**Closed by mdo** 2015-11-15 04:47 UTC
Labels: css, v3

**Comment by Yog** [comment] 2015-11-15 21:15
@perrosen You are correct, same goes with `form-group-lg`
@mdo The output text of an `input` can also possibly wrap to multiple lines, plus the html structure of `textarea` and `input` is exactly the same. 
I don't see how this solution can be only for inputs.

**Comment by markhewett** [comment] 2015-12-09 20:49
@mdo So, what is the correct solution to align long static text with a label in a form? Any long text that wraps suffers from this issue.  I just updated from v3.3.1 to v3.3.6 and was impacted by this.

**Comment by cvrebert** [comment] 2015-12-09 23:59
FWIW, `.form-control-static.form-control-sm` in Bootstrap v4 doesn't suffer from this bug.
