### ISSUE TITLE
Add possiblility to apply a custom class to the tooltip wrapper

### ISSUE THREAD

**Issue by fabiomaggio** [twbs/bootstrap#15835] opened 2015-02-18 12:09 UTC
For easier custom theming of a tooltip it would be nice if you could pass it a css class (or multiple) that would be applied to the default wrapper of the tooltip (the one that has the "tooltip" class). I simply needed to change the background-color of one of my tooltips but to accomplish this i had to pass it a custom template that was actualy just a copy of the default template except it had an extra class.

**Comment by zacechola** [comment] 2015-02-18 14:30
Was there a reason you couldn't override the `background-color` of the `.tooltip-inner` class and the appropriate `.border-*-color` for `.tooltip.* .tooltip-arrow`?

**Comment by cvrebert** [comment] 2015-02-18 22:09
Duplicate of #12776.

**Closed by cvrebert** 2015-02-18 22:09 UTC
