### ISSUE TITLE
Add a.btn-* to override link text color with button color

### ISSUE THREAD

**Issue by uranuz** [twbs/bootstrap#19909] opened 2016-05-15 15:36 UTC
I've tried to use btn, btn-primary, etc with 'a' tag and I have problems with it. On my site $btn-primary-color, but a:visited has some kind of green too. So I cannot see button caption. So I think it would be good idea to override link text color for 'a', 'a:visited' and etc by appropriate button text color. Also maybe reset 'a' text-decoration to the same as for button. Links are made underline very often, but button text is not.

**Comment by mdo** [comment] 2016-05-15 18:54
Without a live example via JS Bin, we can't help you. Beyond that, it sounds like you're facing some problems not caused by Bootstrap. Hit us back with a linked, reduced example and we can take another look.

**Comment by mdo** [comment] 2016-10-28 04:31
Closing due to lack of reply.

**Closed by mdo** 2016-10-28 04:31 UTC
Labels: css
