### ISSUE TITLE
Popover with focus trigger not working in iOS

### ISSUE THREAD

**Issue by beej75** [twbs/bootstrap#17002] opened 2015-08-18 01:50 UTC
Not sure if this is the best place to post this, but I can't seem to get bootstrap popovers working with the focus trigger in any iOS devices.

Best place to show this is the actual Bootstrap website, on the 'Javascript' page, in the Popover section: http://getbootstrap.com/javascript/#popovers

![popover](https://cloud.githubusercontent.com/assets/13843022/9320598/444b38bc-459f-11e5-8688-ebf885139bff.png)

Try getting the 'Dismissable Popover' button working on an iPad or iPhone - doesn't work. Seems to work fine pretty much everywhere else except iOS. 

I'm currently working on trying to mimic the 'focus' trigger using 'click' (which works in iOS, but obviously allows multiple popovers which I don't want), but in the meantime, I can't find many (if any) references to this being a known bug, so I'm hoping I can find out if it is, and the likelihood of it being fixed.

**Comment by cvrebert** [comment] 2015-08-18 04:38
Duplicate of #16028.

**Closed by cvrebert** 2015-08-18 04:38 UTC
Labels: docs, js
