### ISSUE TITLE
When i copy the code manually it redirects to bottom page

### ISSUE THREAD

**Issue by mabhi0122** [twbs/bootstrap#39667] opened 2024-02-11 06:44 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When I try to select and highlight code from examples on the site the page will automatically scroll to the bottom. 
i have issue on chrome, brave browser, edge

### Reduced test cases

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.3

**Comment by mdo** [comment] 2024-02-12 19:37
Duplicate of #39605.

**Closed by mdo** 2024-02-12 19:37 UTC
