### ISSUE TITLE
v4: justified button groups

### ISSUE THREAD

**Issue by bellwood** [twbs/bootstrap#19918] opened 2016-05-16 17:49 UTC
Doesn't appear to be working properly:

https://jsfiddle.net/7sqnran9/2/

Expected result is buttons stretch at equal sizes to span the entire width of its parent as per:
http://getbootstrap.com/components/#btn-groups-justified

Not sure if WIP or missing/broken

**Comment by mdo** [comment] 2016-05-16 18:02
Dupe of #17631.

**Closed by mdo** 2016-05-16 18:02 UTC

**Comment by dejurin** [comment] 2017-11-08 13:19
```
<div class="btn-group d-flex" role="group">
   <a href="" class="btn btn-secondary w-100">Previous</a>
   <a href="" class="btn btn-secondary w-100">Next</a>
</div>
```
https://getbootstrap.com/docs/4.0/migration/#button-group

**Comment by Ohidur** [comment] 2018-09-25 08:59
Thank you very much @dejurin
