### ISSUE TITLE
Dropdowns are broken in v4 docs

### ISSUE THREAD

**Issue by OmgImAlexis** [twbs/bootstrap#20610] opened 2016-09-02 03:34 UTC
When clicking on any dropdown on the v4 docs I get this in the console along with the dropdown not opening. The same happens on Chrome, Firefox and Safari so I don't believe to it be a browser issue.

```
Uncaught Error: Syntax error, unrecognized expression: #
```

For example try the [dropup-variation](https://v4-alpha.getbootstrap.com/components/dropdowns/#dropup-variation) demo.

**Comment by fzls** [comment] 2016-09-02 15:19
Same problem occurred for me 
http://v4-alpha.getbootstrap.com/components/dropdowns/#split-button-dropdowns

**Comment by cvrebert** [comment] 2016-09-02 16:54
Duplicate of #20410. Please search more in the future.

**Closed by cvrebert** 2016-09-02 16:54 UTC
Labels: docs, v4

**Comment by OmgImAlexis** [comment] 2016-09-02 23:41
@cvrebert I did and nothing turned up in the [open issues.](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20dropdown%20docs) so I assumed it was still an issue that needed reporting.

**Comment by cvrebert** [comment] 2016-09-02 23:48
Protip: Always include closed issues when searching. :-)
