### ISSUE TITLE
Carousel becomes very buggy when combining swipes with clicks on prev/next controls on Android with Firefox

### ISSUE THREAD

**Issue by StayCoolDK** [twbs/bootstrap#28070] opened 2019-01-16 09:49 UTC
Bootstrap 4.2.1

Operating system: Android 9 - OxygenOS 9.0.11
Browser and version: Firefox 64.0.2
Test case: https://getbootstrap.com/docs/4.2/components/carousel/ 

- Slide/touch once in any direction and then press the next/previous controls. The carousel becomes very buggy and the user actions do not match what the carousel is doing. This seems like a bug that has been introduced with the new sliding/mobile touch functionality, however only with Firefox. 

I have tried disabling the touch functionality with $('.carousel').carousel({touch: false}); but this does not seem to work as intended either - the touch functionality is still active. 

I'm also experiencing that there is no transition between slides in Firefox.

**Comment by Johann-S** [comment] 2019-01-16 10:15
Hi @StayCoolDK,

I found this strange behavior:
![gif](https://user-images.githubusercontent.com/1689750/51242157-96059500-197f-11e9-8841-9a718e102e6e.gif)

It seems the swipe change the behavior of our arrows (next, prev) but just on Firefox.

About to be able to disable the `touch` behavior we already did a fix that here: https://github.com/twbs/bootstrap/pull/28046

If I remember well if you have no transition on our Carousel between slides in Firefox it's because some accessibility configuration on your Firefox, but @patrickhlauke can explain that better than me 😄

**Comment by StayCoolDK** [comment] 2019-01-16 10:22
Yes, this matches the behaviour i'm getting. I think you're right regarding that the swipe changes the behaviour of the arrows on Firefox, it seems like they're being switched around. 

I can confirm that [this](https://github.com/twbs/bootstrap/issues/24657#issuecomment-360552841) fixes the issue with transitions on Firefox.

**Comment by StayCoolDK** [comment] 2019-01-16 10:36
Also another minor little issue. When sliding using touch on Firefox there is a chance that the page will scroll a little bit. Your gif also shows this issue.

**Comment by StayCoolDK** [comment] 2019-01-16 13:46
@Johann-S I have added another minor issue as a edit to the previous comment. Feel free to delete this comment. Just letting you know :)

**Comment by StayCoolDK** [comment] 2019-02-12 09:52
@Johann-S Is there an ETA for fixing this issue? It seems like it's not a part of Bootstrap 4.3 - perhaps it will ship with 4.4? :-)

**Comment by nradford** [comment] 2019-05-20 21:11
I"m seeing the same issue in iOS 12.3 Safari as well (swiping changes the behavior of the arrows).

**Comment by Johann-S** [comment] 2019-05-24 07:47
Hi @nradford yep that's something we already tackled here: https://github.com/twbs/bootstrap/pull/28558 and it'll be available in our next v4 release

**Comment by Johann-S** [comment] 2019-05-24 08:02
@StayCoolDK it seems the bug is fixed, you can try it here: https://master--twbs-bootstrap.netlify.com/docs/4.3/components/carousel/#with-controls

fixed by: #28558

**Closed by Johann-S** 2019-05-24 08:02 UTC
Labels: confirmed, js, v4

**Comment by StayCoolDK** [comment] 2019-05-24 08:37
@Johann-S Thank you! It seems to work perfectly in Firefox now. 

> Edit:
> AND a minor Chrome & Edge issue - when using touch, the first click on the next/previous control does not work, only the second click. This is not an issue on Safari & Firefox.

This however, still seems to still be an issue:

Try opening the page in Chrome, doing a single slide with touch in any direction

When you have done a slide with touch control and try to use the arrow in either direction afterwards it is not responding - until you've pressed either arrows a second time. Would be awesome if this worked on the first press.

**Comment by Johann-S** [comment] 2019-05-24 09:19
Hi @StayCoolDK,

Please open a new issue about that, but I tried what you said and I'm unable to reproduce it 😟 

I did:
  - First swipe
  - Tap on arrow control

And it works fine on Chrome

**Comment by StayCoolDK** [comment] 2019-05-24 10:27
Hi @Johann-S - i've opened a new issue regarding this. [#28819](https://github.com/twbs/bootstrap/issues/28819#issue-448095350)
It seems weird that you're not able to replicate the issue.
