### ISSUE TITLE
Non-transparent $table-bg overrides table-color classes on rows

### ISSUE THREAD

**Issue by prietveld** [twbs/bootstrap#34132] opened 2021-05-28 13:31 UTC
When setting a color other than transparent (e.g. $white) for $table-bg, all cells inside that table are filled with an inset drop-shadow of that color, overriding any other color a cell might have based on e.g. .table-primary or .table-warning set on any of the table's rows.

This is reproducable with the provided official cheatsheet at https://getbootstrap.com/docs/5.0/examples/cheatsheet/ and Bootstrap 5.0.1.

**Comment by alpadev** [comment] 2021-05-28 13:46
Duplicate of https://github.com/twbs/bootstrap/issues/34012

**Closed by alpadev** 2021-05-28 13:46 UTC
