### ISSUE TITLE
Background blur on Toasts producing weird artifacts

### ISSUE THREAD

**Issue by visionlewis** [twbs/bootstrap#28116] opened 2019-01-24 18:19 UTC
This is my first time reporting an issue. Hopefully there isn't anything missing.

Bootstrap: v4.2.1
Operating System: Windows 10 Pro 17134.523
Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)
Reduced test case: This problem is actually visible on the official documentation for toasts and can be seen here: https://getbootstrap.com/docs/4.2/components/toasts/#translucent
Proposed Fix: I've only been able to fix it by removing the blur altogether.

```
.toast{
      backdrop-filter: initial;
}

```
![image](https://user-images.githubusercontent.com/33150346/51699369-7d8f1d80-2004-11e9-997b-eb4efd88299a.png)

I have been able to reproduce this on [codepen ](https://codepen.io/anon/pen/MLevWx?editors=1111)

![image](https://user-images.githubusercontent.com/33150346/51844958-76bb2000-230e-11e9-9dc3-bfc3eb8b8fa8.png)

**Comment by MartijnCuppens** [comment] 2019-01-27 20:15
Hmm, I can't reproduce this with the same setup. Anyone else who can check this?

**Comment by visionlewis** [comment] 2019-01-28 15:08
I have now linked a codepen demo where I've been able to reproduce this issue.

**Comment by mdo** [comment] 2019-01-29 17:00
Not seeing it in myself right now on latest Chrome (v71) on Win10 in VMware.

<img width="1552" alt="screen shot 2019-01-29 at 8 58 30 am" src="https://user-images.githubusercontent.com/98681/51925630-563da500-23a4-11e9-9de5-e134ab3e314e.png">

**Comment by MartijnCuppens** [comment] 2019-01-29 17:09
I've tested this on a Windows 10 with exactly the same Chrome version and I've also tested this on Browserstack with several other versions and I can not reproduce this. I'm going to close this since you're currently the only one experiencing this.

**Closed by MartijnCuppens** 2019-01-29 17:09 UTC
Labels: css, v4

**Comment by karimcambridge** [comment] 2019-02-18 17:15
I never used to get but, but even since 4.3.1 I'm getting this now.

**Comment by karimcambridge** [comment] 2019-03-05 02:21
Sorry for the double post, but he is correct. It's only when there is a 'blur' in the background.

![image](https://user-images.githubusercontent.com/4283893/53776214-bd7ed580-3ecb-11e9-9dec-da4ade18e4d2.png)

**Comment by visionlewis** [comment] 2019-03-06 10:24
Figured out what was causing the problem (at least for me). Enabling the **Chrome Flag** "Experimental Web Platform Features" is what caused this bug. 

![image](https://user-images.githubusercontent.com/33150346/53874293-0d5bba80-3ffa-11e9-9b17-eb9c6e27b411.png)

**Comment by MartijnCuppens** [comment] 2019-03-06 11:06
Thanks for sharing this, @visionlewis!

**Comment by karimcambridge** [comment] 2019-03-06 21:44
Very cool, but in my situation I can not toggle flags at runtime (CEF).

I'm sure there must be a way to fix this, on the bootstrap end. Why is that weird background even created? Shouldn't there be a way to make it totally transparent?
