### ISSUE TITLE
Dialog Shifts Page Content

### ISSUE THREAD

**Issue by hershko** [twbs/bootstrap#17977] opened 2015-10-19 15:09 UTC
Creating a modal dialog on v4-alpha shifts the content of the page a bit to the left if the HTML tag for the page has "overflow-y: scroll" as a style.

Here's a JSFiddle that shows the issue:
https://jsfiddle.net/329e9x1n/1/
(click the "Launch demo modal" button to see)

**Comment by cvrebert** [comment] 2015-10-19 17:14
Duplicate of #14040.

**Closed by cvrebert** 2015-10-19 17:14 UTC
Labels: js, v4
