### ISSUE TITLE
X icon for invalid inputs confusing

### ISSUE THREAD

**Issue by hawkeye1194** [twbs/bootstrap#28532] opened 2019-03-20 18:09 UTC
The X icon that is used when form controls have the is-invalid class applied to them is confusing, specifically so for the IE and Edge browsers that have an X to clear the text entered into the inputs. I second other suggestions for an exclamation icon or some better image denoting that the form control input is invalid.

**Comment by alecpl** [comment] 2019-03-21 06:51
That's a duplicate of my ticket #28440.

**Closed** 2019-03-21 07:28 UTC

**Comment by demiro** [comment] 2019-04-16 10:28
WHY is this closed? this is the worse issue in bootstrap ever.... how can somebody come up with such a ridiculous idea in 2019 to put a cross icon for an invalid input field.... so many people raised this issue... and for some reason it is getting closed... with no explanation.... not that an explanation would matter... this is next level ridiculous decision. Bootstrap trying to be this accessible UX friendly library, but this is completely backwards.

**Comment by alecpl** [comment] 2019-04-16 10:35
There's another ticket that is open.

**Comment by demiro** [comment] 2019-04-16 10:39
> There's another ticket that is open.

which one?

**Comment by alecpl** [comment] 2019-04-16 10:46
Don't you see my earlier comment?

**Comment by demiro** [comment] 2019-04-16 12:27
> Don't you see my earlier comment?

I did, I thought your one was closed as well O:)
