### ISSUE TITLE
card-columns should be responsive

### ISSUE THREAD

**Issue by rocifier** [twbs/bootstrap#20905] opened 2016-10-16 02:27 UTC
Can card-columns have responsive variants? I can't set the number of columns on different device widths without doing custom media queries.

**Comment by mdo** [comment] 2016-10-17 03:09
Maybe in the future, but not for v4.0.

**Comment by mdo** [comment] 2016-10-17 03:09
Closing as dupe of #20321.

**Closed by mdo** 2016-10-17 03:09 UTC

**Comment by shivampaw** [comment] 2016-10-20 19:46
I think this needs to be done as a priority. It defeats the point of cards and it ruins the responsiveness.

**Comment by rocifier** [comment] 2016-10-22 10:18
FYI this isn't a dupe of #20321 - that feature request is about card-deck this one is about card-columns. Anyway, I just question the usefulness of releasing 3 hard-coded columns in final production v4 - I mean, why 3? and for all devices?

**Comment by ayoubkhan558** [comment] 2018-06-17 21:01
Try This 
https://codepen.io/migli/pen/OQVRMw
