### ISSUE TITLE
Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by agentvnod** [twbs/bootstrap#21022] opened 2016-10-27 05:55 UTC
Hi Team,

I am getting "Cannot read property 'offsetWidth' of undefined" in my website which contains bootstrap carousels. Interestingly all carousels are working fine but when I see the console, there it is. I would like to know why it is coming and How could I fix this.
url: https://classicescapes.com.au/home 

Thanks,
Vinod.

**Comment by mdo** [comment] 2016-10-27 16:56
Does this happen outside your website? As in, do you see the error in our docs or in a reduced test case?

**Comment by agentvnod** [comment] 2016-10-31 10:11
What do you mean by outside website?
As I said all carousels are working fine, and I don't want to have a console error behind the scene.
I couldn't find anything helpful in git hub or in other forums. Please take a look at it.

**Comment by Johann-S** [comment] 2016-10-31 11:03
@mdo his website use Bootstrap v3.3.6 FYI and I'm unable to reproduce this error from our documentation.

**Comment by liangmc89** [comment] 2016-11-22 09:20
hi，I have the same problem, this mistake in my carousel cannot switch the picture, this error is a 40% chance. My url:http://test.iptid.com/guchenghu_api_pc/web/index.html, in the "APPRECIATION BEAUTY" module, click the corresponding picture appear this error. Please help, thank you.

**Comment by mdo** [comment] 2016-11-28 21:52
Closing on account of v3 not being actively developed anymore.

**Closed by mdo** 2016-11-28 21:52 UTC
Labels: js, v3
