### ISSUE TITLE
.invalid-feedback is displaying block on valid

### ISSUE THREAD

**Issue by bestmomo** [twbs/bootstrap#23592] opened 2017-08-21 10:33 UTC
I think there is an issue with a rule with **.invalid-feedback** class on valid enter because it is displaying block and it should be not displayed. Easy to check [in documentation](https://getbootstrap.com/docs/4.0/components/forms/#custom-styles).

**Comment by max41479** [comment] 2017-08-21 12:43
Confirmed. I just typed 123456 in ZIP and submitted, and it says "Please provide a valid zip." with green border.

**Comment by mdo** [comment] 2017-08-21 17:15
Duplicate of #23372 I believe.

**Closed by mdo** 2017-08-21 17:15 UTC
Labels: css, v4
