### ISSUE TITLE
input type="text" readonly class="form-control-plaintext" doesnt work in real life.

### ISSUE THREAD

**Issue by SomeProgrammerGuy** [twbs/bootstrap#31008] opened 2020-06-11 01:13 UTC
Unless I'm missing something (which is very possible).

```
<input type="text" readonly class="form-control-plaintext">
```

 Just doesn’t really work in real life.

If it’s long and the screen is made smaller (mobile etc) it simply doesn’t show the whole text.

I would normally use something like a display list, but I liked the idea of inputs that became readonly instead.

I attempted a few work arounds but they all just didn’t really work. I turned all the text inputs to textarea inputs, but various CSS and raw JS resizing just wouldn’t play (and were bodges being honest).

This should be either updated to work everywhere (not hiding long inputs on smaller screens, textarea’s not working either with all its scrollbars and resize stuff). Or be simply documented out and use a display list (or whatever).

There really is no point having a *display field* that cuts off the text.

**Comment by mdo** [comment] 2020-06-11 05:50
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---

_This is a saved reply._

**Comment by patrickhlauke** [comment] 2020-06-11 08:29
`.form-control-plaintext` simply removes the visual styling of form controls (the border around them etc.) - nothing more, nothing less. the `readonly` part is the default browser behavior when it comes to readonly form controls. so it seems that your main issue/problem here is with how browsers handle `readonly`, rather than bootstrap's extra style that removes the borders etc.

**Comment by mdo** [comment] 2020-06-11 15:24
^ Fwiw that was my assumption as well, pending a live demo reproducing the problem.

**Comment by alecpl** [comment] 2020-06-15 19:50
As I understand, the problem is when the text is longer than the input width. The text is cut. Using inputs for such cases will just not work. Of course, you can use span/div instead.

To reproduce, goto the first input on https://getbootstrap.com/docs/4.4/components/forms/#readonly-plain-text and set its width to 100px.

**Comment by mdo** [comment] 2020-06-15 23:38
Thinking this is a won't fix. If you need complete normal text behavior, you likely should be using normal text elements instead of a modifier of the `form-control`, or [using some text utilities](https://getbootstrap.com/docs/4.5/utilities/text/#text-wrapping-and-overflow) as needed.

Open to revisiting if the @twbs/css-review team thinks it necessary.

**Closed by mdo** 2020-06-15 23:38 UTC

**Comment by patrickhlauke** [comment] 2020-06-16 10:45
tend to agree this is more an author choice thing. regardless of bootstrap or not, this is something that authors would need to decide for themselves even if they were using pure vanilla HTML.

**Comment by SomeProgrammerGuy** [comment] 2020-06-16 13:40
Hi all, Sorry for my late response I've just been very busy.

My point really isn't about how it can be done, it's more about the Bootstrap documentation isn't clear about what this is for (and it's drawbacks).

I would normally use an HTML Description Lists to display Key : Value type data which (debatably) is how it should be done. 

I noticed the hidden border text input way in the Bootstrap documentation and it seemed an interesting idea.

As this in truth doesn't really do (what Bootstrap seems to *imply*) it can be used for, due to the actual limitations of HTML itself I think better class naming or a clearer description should be added to the documentation.

I myself wasn't initially sure if it was something from Bootstrap that would override the HTML rules that I had overlooked.

As a fix this can be done with textareas and some JS to size (which I have managed to get to work now) but it wasn't really about fixing it as such being honest.

As I said in my original post "There really is no point having a display field that cuts off the text."

Hopefully that makes sense.
