### ISSUE TITLE
4.0.0-alpha - hidden-lg-down / hidden-xl-up at the same time

### ISSUE THREAD

**Issue by jimolina** [twbs/bootstrap#17504] opened 2015-09-07 11:15 UTC
Hi

When I have this:
```
<div class="hidden-lg-down">Hi Big</div>
<div class="hidden-xl-up">Hi Large</div>
```
Over 1200px both div are visible.

To fix that, I made this little change:
```
@media (max-width: 74.96em) {
	.hidden-lg-down {
		display: none !important;
	}
}
```
instead:
```
@media (max-width: 74.9em) {
	.hidden-lg-down {
		display: none !important;
	}
}
```

**Comment by cvrebert** [comment] 2015-09-07 20:33
Duplicate of #17282.

**Closed by cvrebert** 2015-09-07 20:33 UTC
