### ISSUE TITLE
What happened to the navigation for smartphones?

### ISSUE THREAD

**Issue by afuno** [twbs/bootstrap#19814] opened 2016-04-27 16:14 UTC
I began to migrate to the Bootstrap 4. All components are successfully updated, except for navigation.

How does the navigation Bootstrap 3 for smartphones: [image](https://habrastorage.org/files/c9d/56d/39a/c9d56d39a3c24964834cba92254316e8.png)

How does the navigation Bootstrap 4 for smartphones: [image1](https://habrastorage.org/files/174/9a7/e65/1749a7e655a94be9b9fe85562021caad.png) or [image2](https://habrastorage.org/files/cbe/bea/5a3/cbebea5a3729408c99f36fab137b9d13.png)

What caused such an attitude to navigation?

**Comment by bellwood** [comment] 2016-04-27 17:31
There is a large amount of work to be done on navs still... 

Alpha2 is not production ready so you'll have to live with issues as v4 matures

**Comment by afuno** [comment] 2016-04-27 17:34
Well, I hope that this defect will be fixed.

**Comment by RyanZim** [comment] 2016-04-27 17:54
@afuno It's not a defect, it's a WIP. Please close this issue since it is a duplicate of https://github.com/twbs/bootstrap/issues/17250.

**Comment by patrickhlauke** [comment] 2016-04-27 19:12
As @RyanZim said, v4 is still in early alpha, and a lot of structures, styles and scripts have changed considerably/aren't finished yet - migrating to v4 already at this stage will likely bring up issues. And yes, duplicate of #17250

**Closed by patrickhlauke** 2016-04-27 19:12 UTC
