### ISSUE TITLE
Responsive cards, card-groups, card-decks

### ISSUE THREAD

**Issue by manju-reddys** [twbs/bootstrap#28456] opened 2019-03-11 18:56 UTC
Following css proposal to make card-group, card-deck or simply cards can be made responsive (without any JS code).
This feature only supports the browsers listed [here](https://caniuse.com/#search=grid).

```
.grid-container {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
        grid-gap: 20px;
        padding: 3px 8px;
        width: 100%;
    }
    .grid-item {
        display: grid;
        height: 148px;
        overflow: hidden;
        max-width: 400px;
        box-shadow: 0 6px 10px rgba(0, 0, 0, .08), 0 0 6px rgba(0, 0, 0, .05);
        transition: .3s transform cubic-bezier(.155, 1.105, .295, 1.12), .3s box-shadow;
        border-radius: 5px;
    }

```

[Demo](https://codepen.io/manju-reddys/pen/moyoZE)

**Comment by mdo** [comment] 2019-03-11 19:00
Duplicate of #20321.

**Closed by mdo** 2019-03-11 19:00 UTC
