### ISSUE TITLE
radio button and checkbox margin error

### ISSUE THREAD

**Issue by nickolasnikolic** [twbs/bootstrap#16416] opened 2015-05-03 19:43 UTC
input[type="radio"], input[type="checkbox"]{
  margin: 0 0.3em;
}

fixes it. Take a look around, I forget just where it is.

Thanks,
Nick

**Comment by cvrebert** [comment] 2015-05-03 20:03
Could you please describe and/or post a demo of what the problem is that this supposedly fixes?

**Comment by nickolasnikolic** [comment] 2015-05-03 22:37
there is a problem with radio/checkbox styling probably due to accidentally hitting the L button rather than the ; button. typo. not sure how else to help, I fixed it here.

**Comment by patrickhlauke** [comment] 2015-05-03 22:50
sounds a bit like #16399. downloading the zip from http://getbootstrap.com/getting-started/ and looking at the CSS, I'm finding a few instances of `\9` in the CSS (but not on this specific one, strangely). could there be a problem with the way the zip is being created? @cvrebert

**Comment by patrickhlauke** [comment] 2015-05-03 22:54
ah, scratch that...looking at the less sources, it seems these instances i'm seeing are explicitly there as IE8 hacks.

**Comment by cvrebert** [comment] 2015-05-04 22:35
@nickolasnikolic Presumably you're referring to https://github.com/twbs/bootstrap/blob/aa2c5b5672f5a7b8b0419bee51023f7e9ae4acba/less/forms.less#L55 ? The `\9` is a deliberate [browser hack](http://browserhacks.com) which is used to make that particular line only apply in IE8-9 and not other browsers.
Was your concern just about this `\9`, or was there something visually wrong with the way checkboxes/radios were being rendered?

**Comment by nickolasnikolic** [comment] 2015-05-04 23:05
The radio/checkboxes were rendering on the top of the neighboring text at
the left side. That was my concern. It was corrected upon replacing the \9
with ";"

**Comment by cvrebert** [comment] 2015-05-04 23:09
@nickolasnikolic 
* Which OS and browser are you using?
* Please post a [JS Fiddle](http://jsfiddle.net) demonstrating the problem.

**Comment by nickolasnikolic** [comment] 2015-05-05 04:32
Windows/Mac chrome Version 42.0.2311.135 m

I am unable to reproduce it and apologize for this.

**Comment by cvrebert** [comment] 2015-05-05 05:01
@nickolasnikolic Well, unfortunately we can't do much to help without a concrete demonstration of the problem...
The example doesn't have to be a JS Fiddle, but we do need some kind of example webpage to be able to investigate.

**Comment by mdo** [comment] 2015-05-14 03:42
Closing for now.

**Closed by mdo** 2015-05-14 03:42 UTC
Labels: awaiting reply, css
