### ISSUE TITLE
Modal Backdrop

### ISSUE THREAD

**Issue by tjaartvanderWalt** [twbs/bootstrap#15849] opened 2015-02-20 04:58 UTC
We upgraded bootstrap from version 3.2.0 to 3.3.0, but now the modal backdrop gets added inside the modal, instead of getting added to the body.

I tracked the change to line 169 in the modal.js (version 3.3.0) file in the bootstrap branch.

The code use to append the modal backdrop to the current body, but now it prepends to the current target(the target modal div).

As of this the backdrop’s top position is now the same as the modal, and there is a white space not covered by the backdrop.

Please advise if this is a bug or if this was an intended change, if this was an intended change I will update/fix my css accordingly.

Old Code:
![g2gpi](https://cloud.githubusercontent.com/assets/11085642/6281656/c5281d56-b8cd-11e4-80fc-d931cf9f221c.png)
New Code:
![hnxlr](https://cloud.githubusercontent.com/assets/11085642/6281661/cf6aaaea-b8cd-11e4-97c9-a97a17dee1ed.png)

**Comment by cvrebert** [comment] 2015-02-20 06:12
Approximate duplicate of #15136. Please search more next time.

**Closed by cvrebert** 2015-02-20 06:12 UTC
