### ISSUE TITLE
Warning: autoprefixer: color-adjust shorthand is currently deprecated.

### ISSUE THREAD

**Issue by axelsomerseth** [twbs/bootstrap#36559] opened 2022-06-13 20:27 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

## Hi there!

I am experiencing a warning when I am using the bootstrap's compiled CSS in my React project.

I think this warning is in the `.form-check-input` CSS class.

I got the following warning from the webpack dev server:

```console
Compiled with warnings.

Warning
(2482:3) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in ./node_modules/bootstrap/dist/css/bootstrap.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/bootstrap/dist/css/bootstrap.css)
Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(2482:3) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.
```

### Reduced test cases

Code must be from this:
```css
.form-check-input {
  /* Other properties */
  /* ... */
  -webkit-print-color-adjust: exact;
  color-adjust: exact;
}
```

To this: 
```css
.form-check-input {
  /* Other properties */
  /* ... */
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;  /* <- change goes here */
}
```

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.3

**Comment by ffoodd** [comment] 2022-06-13 21:18
Duplicate of #36259.

**Comment by ffoodd** [comment] 2022-06-13 21:18
Duplicate of #36259.

**Closed** 2022-06-13 21:18 UTC
