### ISSUE TITLE
Buttons and input elements not inheriting $font-family-base

### ISSUE THREAD

**Issue by dohayon** [twbs/bootstrap#21652] opened 2017-01-10 16:26 UTC
It seems like normalize is overriding the body with font-family: sans-serif, instead of reboot's setting of $font-family-base

**Comment by vanduynslagerp** [comment] 2017-01-10 16:42
I think it's a duplicate of #21595

**Comment by maimairel** [comment] 2017-01-12 09:38
`_reboot.scss`

``// Normalize includes `font: inherit;`, so `font-family`. `font-size`, etc are
// properly inherited. However, `line-height` isn't inherited there.``

But normalize doesn't inherit the font anymore.

**Comment by mdo** [comment] 2017-01-16 02:47
Dupe of #21588.

**Closed by mdo** 2017-01-16 02:47 UTC
Labels: css, v4
