### ISSUE TITLE
Buttons missing active disabled state

### ISSUE THREAD

**Issue by phazei** [twbs/bootstrap#29656] opened 2019-11-09 00:23 UTC
https://github.com/twbs/bootstrap/blob/v4.3.1/scss/_buttons.scss#L31
That line there specifically states "Disabled comes first so active can properly restyle".
But the lines for disabled include `&:not(:disabled):not(.disabled)`
In BS3 it was possible to have have a `disabled` vs `disabled & active` distinguished from each other.   Is this an oversight or intentional?  I believe it should be distinguished.

Use case: 3 options, one selected, but all disabled until some 'edit' button is clicked.  If all the buttons are disabled, there's no way to know which is selected.

**Comment by ysds** [comment] 2019-11-29 18:53
Duplicate of #27814

**Closed by ysds** 2019-11-29 18:53 UTC
