### ISSUE TITLE
tooltip needs the 'word-wrap' css

### ISSUE THREAD

**Issue by jackie88558** [twbs/bootstrap#20319] opened 2016-07-18 02:19 UTC
**Bootstrap 3.3.5**
If the content in tooltip is completely number and the length of the number is really big. It won't break word automatically( not a bug if it's a text ). The number will overflow from the tooltip frame.
So I think we should add some code to the Tooltip.prototype.setContent method in bootstrap.js to fix this bug.
Just like below:
```
Tooltip.prototype.setContent = function () {
    var $tip  = this.tip()
    var title = this.getTitle()

    //add this line.
    $tip.find('.tooltip-inner').css('word-wrap', 'break-word');
    $tip.find('.tooltip-inner')[this.options.html ? 'html' : 'text'](title)
    $tip.removeClass('fade in top bottom left right')
  }
```

**Comment by cvrebert** [comment] 2016-07-18 02:39
Duplicate of #16871.

**Closed by cvrebert** 2016-07-18 02:39 UTC
Labels: css, v3

**Comment by mubinsabu** [comment] 2022-11-20 07:42
**vsfss**
