### ISSUE TITLE
No media query for xs

### ISSUE THREAD

**Issue by robertzajda** [twbs/bootstrap#23965] opened 2017-09-16 19:04 UTC
Hi
There are a great mixins for media query `media-breakpoint-*`, but it's not possible to build media query for xs.
I tried to use `media-breakpoint-between(xs, xs)`. In my opinion it should return:
```
@media (min-width: 0) and (max-width: 576px) {
```
but it returns:
```
@media (min-width: null) and (max-width: 576px) {
```
The problem is in `breakpoint-min` function:
```
@function breakpoint-min($name, $breakpoints: $grid-breakpoints) {
  $min: map-get($breakpoints, $name);
  @return if($min != 0, $min, null);
}
```
This small fix with return solves the problem:
```
@function breakpoint-min($name, $breakpoints: $grid-breakpoints) {
  $min: map-get($breakpoints, $name);
  @return $min;
}
```
So null will be returned only when breakpoint does not exists.

**Comment by Johann-S** [comment] 2017-09-16 21:46
can you specify which release of Bootstrap do you use please ?

**Comment by robertzajda** [comment] 2017-09-18 09:01
current - 4-beta

**Comment by andresgalante** [comment] 2017-09-18 17:25
@robertzajda I see what you mean, since bootstrap is mobile first the xs viewport should be the default.

Did you try using `@include media-breakpoint-only(xs) { ... }` or `@include media-breakpoint-down(xs) { ... }` ?

**Comment by robertzajda** [comment] 2017-09-18 18:45
Yes, I did, but how about larger condition?
Ex. `media-breakpoint-between(xs, sm)`.
The problem is that the function breakpoint-min never returns **0**, but it shoud.
Secondly something like:
```
media-breakpoint-between(xs, xs)
```
Could return:
```
@media (max-width: 576px) {
```
instead of:
```
@media (min-width: 0) and (max-width: 576px) {
```
or instead like now:
```
@media (min-width: null) and (max-width: 576px) {
```
**`null` should be never returned becouse it's not correct css value in this case.**

**Comment by andresgalante** [comment] 2017-09-18 19:25
@robertzajda yeap, you are right! 👍  It'd be cool if you could send a PR

**Comment by Defcon0** [comment] 2017-09-26 09:53
Same problem for media-breakpoint-only(xl) -> doesn't work either.

**Comment by trentclowater** [comment] 2017-09-28 11:23
I'm not seeing any problem with `media-breakpoint-only(xl)`.

**Comment by Defcon0** [comment] 2017-09-28 13:07
Strange. In my project I initialized just yesterday the following code translates to exactly nothing in css:

```
@include media-breakpoint-only(xl) {
    display: none;
}
```

**Comment by trentclowater** [comment] 2017-09-29 04:26
I tried both `@include media-breakpoint-only(xl)` and `@include media-breakpoint-only(sm)` and could not reproduce any problems. Also traced through the code, and it looks like it should work fine.

**Comment by nemad** [comment] 2017-09-30 10:29
> md, lg work as well. Only xs and xl don't.

I have the same issue.

**Comment by mdo** [comment] 2017-10-03 04:38
There's confusion around the usage here...

---

@defcon0: These have the same output, so first one shouldn't be a thing you need. `xl` has no max as it's the highest value in the grid breakpoints, so it cannot do what your next example does.

```
@include media-breakpoint-only(xl) {
    display: none;
}

@include media-breakpoint-up(xl) {
    display: none;
}
```

This makes sense and should be a thing: it outputs query between sm's min and sm's max.

```
@include media-breakpoint-only(sm) {
    display: none;
}
```

---

Some more examples to compare the mixins...

```
// Pointless as `xl` is limitless, it has no max or breakpoint above it
@include media-breakpoint-between(md,xl) {
  .test { color: orange; }
}

// It's the same as...
@include media-breakpoint-up(md) {
    display: none;
}
```

```
// Pointless as `xs` is `0` and `xl` is again limitless with no max
@include media-breakpoint-between(xs,xl) {
  .test { color: pink; }
}

// It's the same as...
.test { color: pink; }
```

**Comment by mdo** [comment] 2017-10-03 04:39
#23997 merged, so closing.

**Closed by mdo** 2017-10-03 04:39 UTC
Labels: css, v4
