### ISSUE TITLE
Tooltip placement is off with single line tooltip and fallback to left in Edge and Chrome

### ISSUE THREAD

**Issue by prietveld** [twbs/bootstrap#35038] opened 2021-09-22 09:18 UTC
If a top-aligned tooltip with a single line of text falls back to the left due to space constraints, the tooltip is placed too high in relation to it's arrow, apparently being placed as if it were two lines high. Scrolling the browser snaps it to it's correct placement.

![screenshot](https://user-images.githubusercontent.com/32836373/134316777-393c6895-7778-47d6-9bad-14f0293a61a3.png) 

- Issue confirmed with Chrome 93.0.4577.82 and Edge 93.0.961.52 for Windows 10
- Working as expected with Firefox 92.0 for Windows 10

Isolated test case on [CodePen](https://codepen.io/PatrickKennisnet/pen/LYLromp)

**Comment by GeoSot** [comment] 2021-09-22 09:27
Thank you @prietveld . And specially for the test case.

I am closing it as duplicate of #34595

**Closed by GeoSot** 2021-09-22 09:27 UTC
