### ISSUE TITLE
[v4 beta-3] bug: d-print-inline causes stacking!

### ISSUE THREAD

**Issue by WebDevBooster** [twbs/bootstrap#25327] opened 2018-01-16 05:29 UTC
This bug report here: 
https://github.com/twbs/bootstrap/issues/25322

was closed wrongly because it actually had **2 separate issues** only one of which was fixed here: 

https://github.com/twbs/bootstrap/issues/25221

The unfixed issue is related specifically to the "inline" part of the `d-print-inline` class. 

So, while the d-print-* issue was fixed in 25221, the "inline" part of the `d-print-inline` class should send the inline form to the printer which does NOT happen. Instead, the form that's being sent to the printer is stacked.

**Comment by mdo** [comment] 2018-01-16 06:15
You'll need to provide a live example of the problem.

**Comment by bischofb** [comment] 2018-01-16 06:48
Here is a basic code snippet where Email label appears in the same row as the email input:

```
<body>
    <div class="container">
    <form class="form-inline">
        <div class="form-group">
        <div class="col-sm-2">
          <label for="inputEmail3" class="form-control-label">Email</label>
        </div>
        <div class="col">
          <input type="text" class="form-control col" style="width:100%" placeholder="email">
        </div>
      </div>
    </form>
  </div>
</body>
```
When printing it appears as a horizontal form. 
![bs4printhorizontal](https://user-images.githubusercontent.com/1018692/34975286-009824aa-fa46-11e7-8856-c137e389f645.png)

Here is a blog post of someone that wrote up some quick CSS to fix it for BS 3 that works pretty well. Hopefully this can be done for BS 4 as well!
https://blog.donnierayjones.com/2014/10/fix-bootstrap3-printing/

**Comment by WebDevBooster** [comment] 2018-01-16 06:55
I'm sure by "horizontal form" @bischofb actually meant "stacked". 

That's the issue. 

I hope you now have everything you need to investigate.

**Comment by bischofb** [comment] 2018-01-16 07:12
I thought horizontal forms meant stacked and inline meant side-by-side positioning. Sorry if I added confusion. I meant to say that when the output is printed then the side-by-side fields now become stacked and lose their formatting. From what it appears via my web searches is that the default printing for responsive layouts (including Foundation) is to have the @media settings default to a super small setting (like a label printer). But It would be great if there was a setting to make it use at least medium setting so it fits on 8.5x11 paper without wiping out all your formatting.

**Comment by mdo** [comment] 2018-01-16 17:08
@WebDevBooster You really need to create a live demo yourself if there's any uncertainty around what component and behavior you're seeing.

Regarding the form—that's the intended behavior. We only make it "inline" when we know we have space to do so. Otherwise, it will appear stacked to ensure accessibility and clarity to end users. If the page is being rendered essentially as a mobile device when printing, that'd explain the stacking.

Now, regarding printing—I merged #25164 not long ago into `v4-dev` which aimed to make the printer page width more consistent across all browsers. This specifically targets the problem @bischofb mentions about defaulting to smaller media queries when printing.

[Check this CodePen example](https://codepen.io/anon/pen/vpzwEL) (right click on the preview, open frame in new tab if possible). It prints as a full page to me with the form rendered as inline. This is using the latest CSS from `v4-dev`.

**Comment by bischofb** [comment] 2018-01-16 20:26
I pulled down v4-dev and I'm running some tests . It looks great! Now I just need to find the time to convert my entire BS3 site to BS4 and see how everything prints. Thanks for all your work on this!

**Comment by mdo** [comment] 2018-01-17 01:50
Great! If you look at my referenced PR, you should be able to copy-paste from v4 to v3 some of those print style changes if you don't want to do a full upgrade just for that.

Closing out this issue for now though since this appears resolved.

**Closed by mdo** 2018-01-17 01:50 UTC
Labels: awaiting reply, css, v4
