### ISSUE TITLE
add option to button.js to trigger custom checkbox/radio button without moving focus

### ISSUE THREAD

**Issue by ghost** [twbs/bootstrap#24039] opened 2017-09-21 17:12 UTC
Hello

Radio button.

Is input.focus() required at https://github.com/twbs/bootstrap/blob/v4-dev/js/src/button.js#L104 ?

Input field behaves as "hidden", not sure what is the idea of focus? If it is required could we add some option to disable it? Let say we have some radio buttons which gets triggered from something else. On small screens those radio buttons could be below viewport and on every change it gets focus or jump to.

Thanks

**Comment by Johann-S** [comment] 2017-09-22 06:14
can you add a live example of an issue related to this line ?

**Comment by patrickhlauke** [comment] 2017-09-22 07:11
i understand your use case, i think (correct me if I'm wrong): you have custom checkboxes/radio buttons https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons that may be triggered programmatically (e.g. some other part of the page needs to trigger a change to the checkboxes/radio buttons); currently, triggering this programmatically also then yanks focus to the checkbox/radio button when it's not desired. correct?

I can see a rationale for allowing an extra way to allow programmatic triggering without focus change here as an option.

**Comment by pnxsaz** [comment] 2017-09-22 07:58
@patrickhlauke yes, that is correct.

**Comment by pnxsaz** [comment] 2017-09-22 08:44
However there is a workaround, instead of clicking on label one could do following on input element.

```javascript
el.parent().siblings().removeClass(ClassName.ACTIVE);
el.parent().addClass(ClassName.ACTIVE);
el.prop('checked', true)
el.trigger('change');
```

**Comment by pnxsaz** [comment] 2017-09-22 09:41
input.focus() is used to toggle class focus on label element which adds outline and answers my question. There is a workaround, will close this issue.

**Comment by patrickhlauke** [comment] 2017-09-22 09:43
i'd actually keep this open. your workaround works of course, but it pretty much replicates a lot of logic. would be good to get an option built right into bootstrap itself for it...

**Comment by samneub** [comment] 2017-10-26 16:32
I may be confused here (perhaps this is a different issue or the intended behavior), but it appears that the custom checkboxes and radios also receive focus on click when browser default and the bootstrap non-custom buttons don't. When selected by keyboard navigation this is great for accessibility but when clicking on it, it makes it look like a target.

**Comment by mdo** [comment] 2021-01-10 02:29
Should we close a won't fix since we dropped the bulk of buttons JS in v5?

**Comment by patrickhlauke** [comment] 2021-01-10 14:28
agree, believe we should close this since v5 does away with all the horribly hacky stuff (i think, on average, i must have spent most of my time with v3-v4 from the moment i started contributing messing around with the custom radios/checkboxes one way or another, will be SO glad when they're dumped fully with v5 stable)

**Closed by patrickhlauke** 2021-01-10 14:28 UTC
Labels: feature, js, v4
