### ISSUE TITLE
Auto-layout columns doesn't wrap in safari

### ISSUE THREAD

**Issue by fjeldsoe** [twbs/bootstrap#23193] opened 2017-08-01 08:26 UTC
When using the auto-layout classes .col, columns doesn't wrap in safari. Below is example screenshots, taken from a modified example on the docs page (https://v4-alpha.getbootstrap.com/layout/grid/#auto-layout-columns):

**Chrome, Firefox, Edge (works fine):**
<img width="268" alt="skaermbillede 2017-08-01 kl 10 14 12" src="https://user-images.githubusercontent.com/5346652/28815917-4071984e-76a3-11e7-80bd-2d779f7d750b.png">

**Safari (not so good):**
<img width="321" alt="skaermbillede 2017-08-01 kl 10 14 29" src="https://user-images.githubusercontent.com/5346652/28815944-570228b2-76a3-11e7-9ae9-4372dbf00201.png">

**Comment by XhmikosR** [comment] 2017-08-01 11:29
Can someone try with the latest v4-dev and also mention the Safari version?

**Comment by gijsbotje** [comment] 2017-08-01 18:25
i can confirm this on a macbook pro in safari 10.1.1 with v4-dev branch

**chrome 59.0.3071.115**
<img width="308" alt="schermafbeelding 2017-08-01 om 20 21 06" src="https://user-images.githubusercontent.com/7714133/28840501-77f8c586-76f7-11e7-8660-8786969990a7.png">

**safari 10.1.1**
<img width="307" alt="schermafbeelding 2017-08-01 om 20 21 26" src="https://user-images.githubusercontent.com/7714133/28840484-67071fc0-76f7-11e7-81ea-5185bf5f28be.png">

**Comment by XhmikosR** [comment] 2017-08-01 18:30
Do you know if it's a known flex issue with Safari? If there's a workaround you could try https://github.com/luisrudge/postcss-flexbugs-fixes or https://www.npmjs.com/package/postcss-fixes and report back.

Personally I can't test on Safari. We have a Browserstack account I will try when I have some time if no one tries the above.

**Comment by madmax** [comment] 2017-08-02 06:44
Can somone make live example? I tested it on Safari 11 and can't reproduce.

**Comment by fjeldsoe** [comment] 2017-08-02 06:53
I made a barebones codepen (https://codepen.io/fjeldsoe/pen/rzLqzJ) to replicate the issue, duplicating the css flex rules of bootstrap. I get the same behavior as described above. It seems to be a Safari bug, but I don't know if there is a workaround. When applying Modernizr to see how it feature detects between the browsers, it's also the same: class="flexbox flexboxlegacy no-flexboxtweener flexwrap"

**Comment by fjeldsoe** [comment] 2017-08-02 07:02
Actually this pen, seems to be consistent between the browsers:
https://codepen.io/fjeldsoe/pen/RZReOW

So maybe it's a flexbox syntax problem?

**Comment by madmax** [comment] 2017-08-02 07:06
For Safari 11 it works ok. 

![zrzut ekranu 2017-08-02 o 09 06 35](https://user-images.githubusercontent.com/4486/28861601-e7e0dc84-7761-11e7-9687-62d9adf53b4d.png)

**Comment by gijsbotje** [comment] 2017-08-02 07:12
I think the solution might be changing out `width: 100%;` (as flexbox default is to stretch elements)  and change it out for `flex-basis: auto;`
This fixed it form me on safari 10.1.1 > https://codepen.io/gijsbotje/pen/dzXQYo

The behaviour is different though

**Comment by lid3rs** [comment] 2017-08-31 10:50
Having the same issue. 

<img width="1102" alt="screen shot 2017-08-31 at 13 41 21" src="https://user-images.githubusercontent.com/1872001/29919778-6089279c-8e53-11e7-8796-3a10abd39557.png">

**Comment by MartijnCuppens** [comment] 2019-01-05 19:09
This is fixed in Safari the meantime.

**Closed by MartijnCuppens** 2019-01-05 19:09 UTC
Labels: css, v4
