### ISSUE TITLE
Affix not dynamically calculated on window.resize with anonymous function

### ISSUE THREAD

**Issue by tikenn** [twbs/bootstrap#19194] opened 2016-02-15 01:41 UTC
I have been attempting to use the bootstrap JavaScript affix plugin to dynamically set the top and bottom offset upon window resize using the suggested anonymous function.  Generalized code below:

    $(window).on('load resize', function() {
        $agendaDay.affix({
            offset: {
                top: function() { return (this.top = (element.offset().top - navbarHeight)); },
                bottom: function() { return (this.bottom = ($(document).height() - elementBottom)); }
            }
        });
    });

Unfortunately, the initial values are cached for some reason and will not be reset with a resized window.  I have used the following code as a work-around, but would like to use the above more simplified code.

    $(window).on('load resize', function(e) {
        $agendaDay.affix({
            offset: {
                top: element.offset().top - navbarHeight,
                bottom: $(document).height() - elementBottom
            }
        });
        if (e.type === 'resize') {
            $agendaDay.data('bs.affix').options.offset.top = element.offset().top - navbarHeight;
            $agendaDay.data('bs.affix').options.offset.bottom = $(document).height() - elementBottom;
        }
    });

**Comment by cvrebert** [comment] 2016-02-15 05:22
Approximate duplicate of #15845. Patches welcome to add `resize` event handling by default.

**Comment by 1eddy87** [comment] 2016-08-29 15:39
Has this issue been resolved?

**Comment by cvrebert** [comment] 2016-08-29 17:03
Closing as duplicate.

**Comment by mdo** [comment] 2016-09-05 22:33
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Closed by mdo** 2016-09-05 22:33 UTC
Labels: js, v3
