### ISSUE TITLE
Justified nav and sticky footer examples are broken

### ISSUE THREAD

**Issue by hnrch02** [twbs/bootstrap#17026] opened 2015-08-19 16:57 UTC
See http://v4-alpha.getbootstrap.com/examples/justified-nav/ and http://v4-alpha.getbootstrap.com/examples/sticky-footer-navbar/.

Source: https://news.ycombinator.com/item?id=10086756

**Comment by XhmikosR** [comment] 2015-09-06 17:39
Ah, here it is! And I pinged @mdo this morning on Slack.

**Comment by mdo** [comment] 2015-12-08 08:26
Footers are fixed, justified is a dupe of #17723.

**Closed by mdo** 2015-12-08 08:26 UTC
Labels: css, examples, v4
