### ISSUE TITLE
Bootstrap Modal issue with iPhone

### ISSUE THREAD

**Issue by jaypatel711** [twbs/bootstrap#22902] opened 2017-06-23 15:03 UTC
bootstrap modal starts blinking in iPhone in below scenario.

- Main Page has height more then mobile screen so it will have a scroll.
- In iframe include other html which has modal in that and again modal height should be greater then mobile screen height, so modal will have also a scroll.
- When you keep multiple input fields inside a modal and if you try to enter value in any below input field, bootstrap modal will get disappear and will appear again after sometime

Below is code (Parent html):

	<!DOCTYPE html>
	<html>
	<head>
	<meta charset="UTF-8">
	<title>Insert title here</title>
	<meta name="viewport" content="initial-scale=1.0 user-scalable=no">
			<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
	<script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<link rel="stylesheet" type="text/css" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
	<script type="text/javascript" src="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
	</head>
	<body style="background-color: lightgrey;height:1000px;">
	<div style="margin-top:50px;">
		<button class="btn btn-default" id="btn"> Open iframe</button>
	</div>
	<div style="margin-top:50px;">
		<button class="btn btn-default" id="btn1"> Open iframe</button>
	</div>
	<div style="margin-top:50px;">
		<button class="btn btn-default" id="btn11"> Open iframe</button>
	</div>
	<div style="margin-top:50px;">
		<button class="btn btn-default" id="btn111"> Open iframe</button>
	</div>
	<div style="margin-top:50px;">
		<button class="btn btn-default" id="btn2"> Open iframe</button>
	</div>
	<div style="margin-top:50px;">
		<button class="btn btn-default" id="btn22"> Open iframe</button>
	</div>
	<div style="margin-top:50px;">
		<button class="btn btn-default" id="btn222"> Open iframe</button>
	</div>
	<div style="margin-top:50px;">
		<button class="btn btn-default" id="btn3"> Open iframe</button>
	</div>
	<div style="margin-top:50px;">
		<button class="btn btn-default" id="btn33"> Open iframe</button>
	</div>
	<iframe id="frm" name="frm" src="incModalForm.html" style="display:none;position: fixed;top: 0px;left: 0px;z-index: 2147483647;width: 100%;height: 100%;overflow: hidden;"></iframe>
	<script type="text/javascript">
	$(document).ready(function(){
		$("#btn").click(function(){
			$("#frm").show();
		});
		$("#btn1").click(function(){
			$("#frm").show();
		});
		$("#btn11").click(function(){
			$("#frm").show();
		});
		$("#btn111").click(function(){
			$("#frm").show();
		});
		$("#btn2").click(function(){
			$("#frm").show();
		});
		$("#btn222").click(function(){
			$("#frm").show();
		});
		$("#btn3").click(function(){
			$("#frm").show();
		});
		$("#btn33").click(function(){
			$("#frm").show();
		});
		
	});
	</script>
	</body>
	</html>
Second html which will be included "incModalForm.html"

	<!DOCTYPE html>
	<html>
	<head>
	<meta charset="UTF-8">
	<title>Insert title here</title>
	<meta name="viewport" content="initial-scale=1.0 user-scalable=no">
			<meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'>
	<link rel="stylesheet" type="text/css" href="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
	<script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script type="text/javascript" src="https://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.3.1/jquery.maskedinput.min.js"></script>
	</head>
	<body style="background: transparent;">
		<div class="modal show" tabindex="-1" role="dialog" style="-webkit-overflow-scrolling: touch;" aria-labelledby="modalLabel">
			<div class="modal-dialog  modal-container" role="document" style="width: 90%;height:800px;">
					<div class="modal-content" style="height: auto;">
						<div class="modal-header">
							<button type="button" class="close" id="btnWidgetClose" style="font-size:30px;opacity:0.5;">×</button> 
							<h3 class="modal-title" id="modalLabel">Input Form</h3>
						</div>
						<div class="modal-body" style="padding: 0px;">
							<div class="main-wrap" id="widgetApptBookingDiv" style="">
								<div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> Name: </div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> <input type="text" class="form-control" id="name1" name="name1" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> Address: </div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="add" name="add" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> Address 2:</div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="add1" name="add1" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> City :</div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="city" name="city" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> State :</div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="state" name="state" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> Country :</div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="country" name="country" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> Email :</div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="email" name="email" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> Phone No :</div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="phone" name="phone" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> Gender :</div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="gender" name="gender" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> State :</div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="state" name="state" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> Country :</div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="country" name="country" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> Email :</div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="email" name="email" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> Phone No :</div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="phone" name="phone" /></div>
								</div><div class="row form-group">
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"> Gender :</div>
									<div class="col-sm-6" style="text-align:center; margin-top:10px;"><input type="text" class="form-control" id="gender" name="gender" /></div>
								</div>
							</div>
						</div>
					</div>
			</div>
		</div>
		<script type="text/javascript">
		$(document).ready(function(){
			$.mask.definitions['~']='[+-]';
			$.mask.definitions['y'] = '[12]';
			$.mask.definitions['m'] = '[01]';
			$.mask.definitions['d'] = '[0-3]';
			$('#add1').mask('m9/d9/y999');
			$('#add').mask('m9/d9/y999');
		});
		</script>
	</body>
	</html>

Try to open first html in iphone safari browser and try to enter value in email or phone no or gender.

Thanks

**Comment by Johann-S** [comment] 2017-06-23 15:21
Bootstrap 3 is essentially in maintenance mode as we focus on working towards a stable v4. As such, we're only accepting changes to v3's code on a case-by-case basis, usually only for critical bug fixes or docs improvements.

**Comment by jaypatel711** [comment] 2017-06-23 15:26
@Johann-S Are you going to take care of this bug with v4?

**Comment by Johann-S** [comment] 2017-06-23 15:31
Yes if you can provide a reduce test case in V4 of this issue

**Comment by jaypatel711** [comment] 2017-06-23 15:46
@Johann-S  I tried to reproduce this issue with v4 but unfornatuatly i was not able to open modal it self when I click on button. Not sure if it is bug or not. Is it possible I can have solution with existing v3?
I tried with JS from below link

https://v4-alpha.getbootstrap.com/

**Comment by jaypatel711** [comment] 2017-06-23 15:51
Well I just found that this is still but with v4. I am able to reproduce this with v4.

**Comment by jaypatel711** [comment] 2017-06-23 16:03
https://codepen.io/jaypatel711/pen/VWzyEQ

**Comment by mdo** [comment] 2017-07-02 19:09
I'm not seeing this on my iPhone 7 running latest iOS 10. I had to fork your demo and force the modal to be displayed though as you have no trigger to show it, but that shouldn't be an issue either. Could be the mix of those inline styles and something else on your end?

**Comment by jaypatel711** [comment] 2017-07-02 19:42
http://ijhrds.com/test/

Here is the link you can test it.
Just launch this in your iphone and with safari browser.

Try to enter value in email or any other filed which is on bottom of page.
No inline css has been used i just imported bootstrap and jquery.

**Comment by mdo** [comment] 2017-07-02 21:39
Just tried, works fine—no problems with anything disappearing.

**Comment by jaypatel711** [comment] 2017-07-02 22:01
I am not sure why you are not able to reproduce it as it is a clearly issue I am seeing on my iPhone 7 plus with latest iOS. I hope you follow below steps to reproduce this.

1) Open above URL is safari browser
2) click on first button open iframe
3) Directly try to enter value in email (Do not enter value in above fields). you will see modal will disappear.

Will try to send a video to recorded screen of my iphone.

**Comment by patrickhlauke** [comment] 2017-07-02 22:08
confirming that this happens. however, i'd note: this feels like a bug in iOS relating to iframe handling, and not something relating to bootstrap directly. your approach is rather unorthodox: you open an iframe which then contains a modal, when really it should probably be the other way around (open a modal that then contains an iframe).

**Comment by jaypatel711** [comment] 2017-07-02 23:40
I really tried all possible ways to fulfill my requirement  but as I am working on client side widget I don't have any other option then this. As I need to create iframe on client website so that I can open my modal inside my iframe, with my css, so I don't have any other choice. You can surely suggest me any other way.

Thanks for confirming about bug. Let me know if you want me to open this as bug in other forum.

**Comment by samurai30** [comment] 2018-03-31 07:34
yes even I have the same exact problem with my site, It works properly on android devices though. I think its something to do with IOS.

**Comment by ysds** [comment] 2020-03-05 14:53
Close this since the tests doesn't work for now and cannot be reproduced.

**Closed by ysds** 2020-03-05 14:53 UTC
Labels: css, v3, v4
