### ISSUE TITLE
Rounded corners lost when invalid feedback on input group

### ISSUE THREAD

**Issue by vpratfr** [twbs/bootstrap#26406] opened 2018-04-27 15:02 UTC
This is visible in the documentation too. Here is a sample snippet

```
    <div class="col-md-4 mb-3">
      <label for="validationServerUsername">Username</label>
      <div class="input-group">
        <div class="input-group-prepend">
          <span class="input-group-text" id="inputGroupPrepend3">@</span>
        </div>
        <input type="text" class="form-control is-invalid" id="validationServerUsername" placeholder="Username" aria-describedby="inputGroupPrepend3" required>
        <div class="invalid-feedback">
          Please choose a username.
        </div>
      </div>
    </div>
```

You will notice that the rounded corners of the input are lost on the right side. Due to the input not being the `last-child`

**Comment by vpratfr** [comment] 2018-04-27 16:34
Here is a live demo: https://jsfiddle.net/g6wn5nrL/

**Comment by claudioalmeiida** [comment] 2018-04-29 19:43
https://github.com/twbs/bootstrap/issues/25110

**Comment by mdo** [comment] 2018-04-29 22:47
Duplicate of #25110.

**Closed by mdo** 2018-04-29 22:47 UTC
Labels: css, v4
