### ISSUE TITLE
Can't install boostrap 4 via meteor add.

### ISSUE THREAD

**Issue by lednhatkhanh** [twbs/bootstrap#20703] opened 2016-09-12 07:48 UTC
Hi, when I run `meteor add twbs:bootstrap@=4.0.0-alpha.4` in my project, I received this error message:

```
=> Errors while parsing arguments:                                                                            
                                                                                                               
While adding package twbs:bootstrap@=4.0.0-alpha.4:                                                            
error: no such version twbs:bootstrap@4.0.0-alpha.4
```

Any helps? Thank you.

**Comment by Kamshak** [comment] 2016-09-12 09:11
Which meteor version are you using? If you are using >=1.3 you can simply use meteor npm to install bootstrap

**Comment by cvrebert** [comment] 2016-09-12 20:39
Duplicate of #20389.

**Closed by cvrebert** 2016-09-12 20:39 UTC
