### ISSUE TITLE
v4 - Button group caret is not horizontally alligned

### ISSUE THREAD

**Issue by cihadturhan** [twbs/bootstrap#17135] opened 2015-08-20 14:57 UTC
I think the image below describes.

![image](https://cloud.githubusercontent.com/assets/3739536/9386570/c3a45b5e-4764-11e5-87d0-a961a44bbb16.png)

Thanks for making bootstrap better

**Comment by kkirsche** [comment] 2015-08-20 15:29
This is caused by: `margin-left: .25rem;` with no corresponding right margin. PR submitted to fix this.

**Comment by cvrebert** [comment] 2015-11-13 05:45
Fixed by #17137.

**Closed by cvrebert** 2015-11-13 05:45 UTC
Labels: confirmed, css, v4
