### ISSUE TITLE
Dreamweaver crashes opening HTML or PHP files calling Boostrap 3 files

### ISSUE THREAD

**Issue by jlnwcic** [twbs/bootstrap#15513] opened 2015-01-07 13:43 UTC
We're running into issues where Dreamweaver, Zend, and Codelobsterr hang and crash opeing even small HTML files that call Boostrap 3 CSS files.  It seems that the Boostrap CSS files are just too big. We've replicated this issue on other machines, even one with a fast Solid state drive and 16 GB Ram.
Since it never happended with Bootstrap 2, this seems to be centric to opening an HTML or PHP file that calls too many CSS files or CSS files that are too large.  Not an issue of temp file space, as the SSD has plenty of space.  As a temp bandaid, we're opening these files to edit them in the old HomeSite or Sublime Text editor.  Suggestions?

**Comment by NYPD** [comment] 2015-01-07 14:44
Wouldn't this be dreamweavers issue?

**Comment by cyborgcassowary** [comment] 2015-01-07 14:51
It might have something to do with the CC Sync Folder. https://forums.adobe.com/thread/1445116

If this isn't the case, you could temporarily link to the Bootstrap CDN: http://bootstrapcdn.com/

**Comment by cvrebert** [comment] 2015-01-07 18:07
Closing as not a bug in Bootstrap itself.

**Closed by cvrebert** 2015-01-07 18:07 UTC

**Comment by jlnwcic** [comment] 2015-01-07 19:00
This issue occurs in Zend, Codelobster and Dreamweaver, so it's not a Dreamweaver-centric issue.
Additionally, we can replicate it on multiple machines.
We checked, and it's not a CC Sync issue. That came about with Dreamweaver CC, and this occurs using Dreamweaver CS4, CS5, CS5.5 and CC. We also ran a memory tracer to follow the issue and memory never peaked at over 25%.
It is interesting that if we comment out the Bootstrap calls, the files open with no issues.

**Comment by jlnwcic** [comment] 2015-01-07 19:14
I should add: Additionally, we created a folder just with Bootstrap and the free "SB Admin 2" theme.
When opening the index.html file, all three editors crash, and on multiple machines.  This would seem to indicated that the Bootstrap files being called are too large for the editors to include in the process.  I asked a few other developers, and they are starting to run into this issue as well. 
So, if this thread could be kept open, the above seems to indicate clearly that this is a Bootstrap issue.

**Comment by NYPD** [comment] 2015-01-07 19:48
This still is not bootstrap's issue. If the min.css file is still too large and dreamweaver and friends keep crashing, the bootstrap devs can't do anything besides strip away features to make the file smaller.

Bootsrap's website does offer a customize section(http://getbootstrap.com/customize/) where you can pick and choose the features you want which you can try to get a smaller file size.

If you mentioned it opens in sublime and other text editors, why would you think it is a bootstrap problem anyway?

**Comment by jlnwcic** [comment] 2015-01-07 20:05
Thanks for the response.  Here is why:
-1-We can open very large PHP files with no issues.  
-2-We can also open other framework apps similar to Bootstrap without issue.  
-3-If we comment out calls to Bootstrap, the files load fine.
-4-The above can be replicated on multiple machines.
-5-Other developers are experiencing the same issue.
-6-The issue repeats with Boostrap calls in 3 other editors.
-7-Opening a boostrap app without customization creates the same error.
-8-This issue has arisen with Bootstrap 3, not with ver. 2, and arose only after ver. 3 came out.
-9-Sublime opens the HTML file only, and does not load calls to Bootstrap files.
-10- The old Homesite (Pre-Dreamweaver) opens the files fine, as it also does not call the Bootstrap files.

**Comment by finchweb** [comment] 2015-01-07 20:53
Things to try: 
Maybe those IDE's don't like the minification (all the rules being stacked on one line), so try it unminified.

If that doesn't work, try reducing the size of your bootstrap files using the customizer mentioned above and remove features you don't forsee using:
http://getbootstrap.com/customize/

**Comment by cvrebert** [comment] 2015-01-08 00:45
Please move further discussion of these editor bugs to forum(s) related to the editor(s), and possibly file bugs / support-tickets with the relevant editor vendors. Thanks!

**Comment by vaughany** [comment] 2015-01-08 08:28
Can you open the Bootstrap files directly in Sublime Text?  I have used it for some time now on Win7 and Ubuntu and have successfully opened, edited and saved files with sizes orders of magnitude greater than that of the Bootstrap CSS files. I doubt size is the issue (unless Dreamweaver's doing something odd when it opens the file). Possibly an encoding issue? (Thinking out loud now).

**Comment by jlnwcic** [comment] 2015-01-08 18:22
Hi Vaughany.  Since Sublime is not a smart web page editor and does not call the Bootstrap files, yes.
But working with IDE dialogs and code completion routines for CSS, JavaScript, SQL, PHP is not possible with Sublime-it's just a workaround that delays production.  
This also is not directly an editor issue though. It is an issue that Bootstrap files have become too big for the mainstream IDE's to handle.  if it was just an editor issue, then other frameworks would also fail in IDE's which they do not.  See the top 10 reasons above.
Bottom line:  Less finger pointing and more solutions. We'll likely move away from Bootstrap altogether for the time being until IDE's address wake up to the reality that web pages and scripts are getting bigger and more complex, and framework providers accept that there are code size issues that are hampering developers in the real world.
DMXZone has a plugin to handle Bootstrap, but it is limited to their template extension plugins and does not solve manual page edits of web pages that call Bootstrap.
If this drags on much longer, someone might just develop a plugin that can hook into an IDE's API and bypass the memory limitations in IDE's.
For now, we'll trudge on, knowing that we COULD be developing 2-3 times faster than we currently do.
