### ISSUE TITLE
Modal bug

### ISSUE THREAD

**Issue by armancho7777777** [twbs/bootstrap#23180] opened 2017-07-30 19:16 UTC
![_001](https://user-images.githubusercontent.com/4474900/28756317-9d7802e0-759e-11e7-9d12-82b64fda7551.png)

**Comment by patrickhlauke** [comment] 2017-07-30 19:24
dupe of https://github.com/twbs/bootstrap/issues/23173 - fixed in https://github.com/twbs/bootstrap/pull/21743

**Closed by patrickhlauke** 2017-07-30 19:24 UTC
