### ISSUE TITLE
Negative margin

### ISSUE THREAD

**Issue by ct-viral** [twbs/bootstrap#36248] opened 2022-04-29 09:27 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

this is same continue bug with  https://github.com/twbs/bootstrap/issues/36246

i have made change in only one file wich is _variable.scss that i will attech,

_sorry for that scss file will not allow me to attach so ican attach in text format_

[_variables.txt](https://github.com/twbs/bootstrap/files/8589597/_variables.txt)

### Reduced test cases

[_variables.txt](https://github.com/twbs/bootstrap/files/8589597/_variables.txt)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by mdo** [comment] 2022-04-29 16:03
Duplicate of #36246.

**Closed by mdo** 2022-04-29 16:03 UTC
