### ISSUE TITLE
Automate 404 links checking

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#23322] opened 2017-08-11 13:35 UTC
Maybe using something like simplecrawler.

**Comment by bardiharborow** [comment] 2017-08-11 14:23
I used to run a crawler on the docs periodically, but I've been lazy recently. I feel like this has come up before, but it was suggested that it's probably too much extra CI weight for little gain, and it could make Travis flap. A separate script might be helpful though.

**Comment by XhmikosR** [comment] 2017-08-11 14:29
I'd rather have a CI delay than having Sauce tests run for each patch. Previously we could skip sauce tests.

And honestly, simple crawler should be pretty fast.

**Comment by mdo** [comment] 2017-08-13 22:14
Duplicate of #18568.

**Closed by mdo** 2017-08-13 22:14 UTC
Labels: help wanted, js, meta, v4
