### ISSUE TITLE
Bad rendering of btn-outline-light under navbar-dark

### ISSUE THREAD

**Issue by Soullivaneuh** [twbs/bootstrap#24048] opened 2017-09-22 11:08 UTC
With the following html code:

```twig
<header>
    <nav class="navbar navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="{{ path('homepage') }}">
                LintoCop
            </a>
            <a class="btn btn-outline-light"
               href="#"
            >Sign in</a>
        </div>
    </nav>
</header>
```

Hovering the button makes this:

![image](https://user-images.githubusercontent.com/1698357/30741922-2bb521ce-9f97-11e7-8d4a-8d07f88505ea.png)

I don't think this is the expected behavior. :-)

**Comment by andresgalante** [comment] 2017-09-22 16:22
Hi @Soullivaneuh I am confuse. I can't reproduce it. Here is your exact same code running on 4-beta:
https://codepen.io/andresgalante/pen/NaRMvN

**Comment by mdo** [comment] 2017-09-26 18:51
Duplicate of #23351.

**Closed by mdo** 2017-09-26 18:51 UTC
Labels: css, v4
