### ISSUE TITLE
Form-horizontal class + collapse

### ISSUE THREAD

**Issue by sulian** [twbs/bootstrap#16608] opened 2015-06-09 14:13 UTC
Dear all,
I have a strange result if I use a form and after a collapsed table (you must see this example in full screen : 
https://jsfiddle.net/5k7a7yts/8/embedded/result/
the table is pushed to right !!

This jsfiddle work but I must add a form-horizontal class to my form :
https://jsfiddle.net/5k7a7yts/6/embedded/result/

Did I miss something ??

[sorry for my poor english]

**Comment by twbs-lmvtfy** [comment] 2015-06-09 14:13
Hi @sulian!

You appear to have posted a live example (https://fiddle.jshell.net/5k7a7yts/2/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 41, column 13 thru line 41, column 52: Bad value ````  ```` for attribute ```` action ```` on element ```` form ````: Must be non-empty.
* line 56, column 42 thru line 57, column 45: The ```` width ```` attribute on the ```` th ```` element is obsolete. Use CSS instead.
* line 57, column 52 thru line 58, column 46: The ```` width ```` attribute on the ```` th ```` element is obsolete. Use CSS instead.
* line 58, column 56 thru line 59, column 46: The ```` width ```` attribute on the ```` th ```` element is obsolete. Use CSS instead.
* line 59, column 63 thru line 60, column 46: The ```` width ```` attribute on the ```` th ```` element is obsolete. Use CSS instead.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by twbs-lmvtfy** [comment] 2015-06-09 14:13
Hi @sulian!

You appear to have posted a live example (https://fiddle.jshell.net/5k7a7yts/3/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 41, column 13 thru line 41, column 28: Bad value ````  ```` for attribute ```` action ```` on element ```` form ````: Must be non-empty.
* line 56, column 42 thru line 57, column 45: The ```` width ```` attribute on the ```` th ```` element is obsolete. Use CSS instead.
* line 57, column 52 thru line 58, column 46: The ```` width ```` attribute on the ```` th ```` element is obsolete. Use CSS instead.
* line 58, column 56 thru line 59, column 46: The ```` width ```` attribute on the ```` th ```` element is obsolete. Use CSS instead.
* line 59, column 63 thru line 60, column 46: The ```` width ```` attribute on the ```` th ```` element is obsolete. Use CSS instead.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by sulian** [comment] 2015-06-09 14:18
Examples has been updated

**Comment by sulian** [comment] 2015-06-09 14:30
Ok, the answer is very simple, you need to add a clearfix class after the end of the form...

https://jsfiddle.net/5k7a7yts/9/embedded/result/

**Comment by kkirsche** [comment] 2015-06-10 00:36
Hey @sulian, sorry no one was available earlier to take a look at this earlier today. It sounds as though (correct me if I'm wrong) you were able to get this sorted out. One thing I'd consider though is adding the clearfix directly to the `form` element not to a new `div`. As far as I can tell on the monitors I have here (1440px wide) it seems to do the same thing, but with a tiny bit less markup.

Are there any additional questions or issues here which haven't been addressed?

**Comment by sulian** [comment] 2015-06-10 07:54
It works like a charm, thanks @kkirsche

**Comment by kkirsche** [comment] 2015-06-10 11:23
Of course :+1: 

If the issue is fully solved with no additional assistance needed, would you be able to close the issue?

**Comment by kkirsche** [comment] 2015-06-10 11:26
Thanks Patrick :smiley:

**Closed** 2015-06-10 11:26 UTC
Labels: css
