### ISSUE TITLE
Bootstrap 4.0.0-alpha3 Popover data-container not work.

### ISSUE THREAD

**Issue by acopalipsis** [twbs/bootstrap#20569] opened 2016-08-23 19:10 UTC
Popover data-container="..." always `body`. Bug :(

[jsfiddle](https://jsfiddle.net/dxk3o83c/)

**Comment by cvrebert** [comment] 2016-08-27 01:17
Duplicate of #17755. Please search more in the future.

**Closed by cvrebert** 2016-08-27 01:17 UTC
Labels: js, v4
