### ISSUE TITLE
Navbar do not work after resize page. Boostrap 4.0.0 alpha 6

### ISSUE THREAD

**Issue by office-work-account** [twbs/bootstrap#22108] opened 2017-03-03 15:19 UTC
Example from boostrap page, the navbar menu don't work in plunker.
issue - after click on menu button the item of menu won't show.

**Comment by patrickhlauke** [comment] 2017-03-03 15:39
without some more information (what's "plunker"? what browser is having problems? etc) there's little that can be actioned here...

**Comment by mdo** [comment] 2017-03-03 18:29
Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via JS Bin and report back with specific browser and OS details.

**Comment by MargateSteve** [comment] 2017-03-07 22:22
I am not sure if office-work-account is talking about the potential issue that I have come here to see if it is raised. The container example at https://v4-alpha.getbootstrap.com/examples/navbars, when viewed at (I think) the sm breakpoint and down, centers and disappears behind the brand. I was expecting the brand to stay at the leftmost of the container and the toggle to right.
If this is not the same and this is an issue that has not already been raised, I will happily do so.
![image](https://cloud.githubusercontent.com/assets/13920439/23680833/8f630d30-0384-11e7-8de6-ed4664ae7dd1.png)

**Comment by GBH** [comment] 2017-03-14 07:46
Bah, spent too much time thinking I did something wrong. Confirming that container inside navbar messes things up when resized to phone screen. Also alignment of the navbar-brand is messed up in all other sizes.

**Comment by dougkillmer** [comment] 2017-03-14 22:43
https://jsbin.com/meluxuqeto/edit?html,output

Navbar contents becomes centered at 575px and down.
![image](https://cloud.githubusercontent.com/assets/11560014/23925494/c15bac3c-08cc-11e7-92d9-9b965c2ee580.png)

**Comment by Olivia101** [comment] 2017-03-15 00:58
It's related to the width of the `.container`

![screenshot_2](https://cloud.githubusercontent.com/assets/4064582/23928902/6c6197b2-0987-11e7-9e4d-d131223b7bdf.png)

**Comment by mdo** [comment] 2017-03-15 03:39
Sounds like a dupe of #21590, fixed by #21722. Updated demo with latest CSS from `v4-dev`: https://jsbin.com/gugunimixo/edit?html,css,output.

**Closed by mdo** 2017-03-15 03:39 UTC
Labels: awaiting reply, css, v4
