### ISSUE TITLE
v4 alpha package not avialable via npm

### ISSUE THREAD

**Issue by e-oz** [twbs/bootstrap#18305] opened 2015-11-20 23:14 UTC
Please publish v4 to npm - planned date of releases for some projects are in 2016, for them it's already good time to start with twbs v4.

**Comment by kkirsche** [comment] 2015-11-20 23:27
Noting that I believe this is done via `npm publish --tag unstable` though I couldn't find any guides for publishing pre release software on NPM

**Comment by cvrebert** [comment] 2015-11-23 04:17
X-Ref: #18006

**Comment by cvrebert** [comment] 2015-11-24 13:30
In addition to being a duplicate of #18006, I'll interpret this as a request that `v4.0.0-alpha.2` be released Real Soon.
Your request is duly noted.

**Closed by cvrebert** 2015-11-24 13:30 UTC
Labels: meta, v4
