### ISSUE TITLE
v4: .container width on small viewports

### ISSUE THREAD

**Issue by hypeJunction** [twbs/bootstrap#22292] opened 2017-03-28 13:42 UTC
``.container`` has a defined max width but no width on smaller viewports, which causes it to shrink.

See the codepen http://codepen.io/hypeJunction/pen/KWBwdg from #22259, which also demonstrates this issue.

**Comment by mdo** [comment] 2017-03-28 16:12
Dupe of #21590, fixed in `v4-dev` by #21722.

**Closed by mdo** 2017-03-28 16:12 UTC
Labels: css, v4
