### ISSUE TITLE
input-group-btn btn border

### ISSUE THREAD

**Issue by jonnysp** [twbs/bootstrap#23539] opened 2017-08-18 08:48 UTC
please remove the border from .input-group-btn > .btn it shows on color buttons ugly
the btn itself has a border from example   btn-primary or btn-outline-danger ...

before
![1](https://user-images.githubusercontent.com/1651241/29451319-865777d6-8402-11e7-9232-3297db7356ab.JPG)
after
![2](https://user-images.githubusercontent.com/1651241/29451327-8f7dd026-8402-11e7-94d8-970632f4815c.JPG)

https://github.com/twbs/bootstrap/blob/58994a16c589caef633682bc5e7a44d8793245df/scss/_input-group.scss#L145

**Comment by mdo** [comment] 2017-08-18 20:16
Duplicate of #23379.

**Closed by mdo** 2017-08-18 20:16 UTC
Labels: css, v4
