### ISSUE TITLE
hide.bs.dropdown not firing

### ISSUE THREAD

**Issue by gersonmsj** [twbs/bootstrap#32571] opened 2020-12-21 03:35 UTC
Windows 10 (1909)
Chrome (87.0.4280.88)

hide.bs.dropdown never fires, but show.bs.dropdown fires normaly (angular 11).
Ref.: bootstrap.css and bootstrap.bundle.js (no jQuery)

HTML
[https://getbootstrap.com/docs/5.0/components/dropdowns/#single-button](url)

Angular 11 code
```
@ViewChild("dropdownMenuButton") dropdownMenuButton!: ElementRef<HTMLElement>;

  ngAfterViewInit() {
    this.dropdownMenuButton.nativeElement.addEventListener('show.bs.dropdown', (e) => { console.log(e); }); // FIRING
    this.dropdownMenuButton.nativeElement.addEventListener('hide.bs.dropdown', (e) => { console.log(e); }); // NOT FIRING
  }
```

**Comment by XhmikosR** [comment] 2020-12-21 12:45
Seems like a duplicate of #31935, /CC @rohit2sharma95

**Comment by rohit2sharma95** [comment] 2020-12-21 13:05
Yes, duplicate of #31935

As per the naming convention of the reference variable, it is assumed that you are holding the reference of the `.dropdown-toggle` in `dropdownMenuButton`.

**Closed** 2020-12-21 13:13 UTC
Labels: duplicate
