### ISSUE TITLE
CDN is not working - https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.min.js

### ISSUE THREAD

**Issue by vikaspaturi** [twbs/bootstrap#31889] opened 2020-10-14 08:16 UTC
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS)
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser)
- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by vikaspaturi** [comment] 2020-10-14 08:16
CDN Bootstrap JS file is broken.

https://stackpath.bootstrapcdn.com/bootstrap/4.5.3/js/bootstrap.min.js

**Comment by aurelien-robineau** [comment] 2020-10-14 08:36
I am currently having the same issue.
Just copied the bootstrap starter template but it won't work.

**Comment by Gemorroj** [comment] 2020-10-14 10:06
https://github.com/twbs/bootstrap/issues/31887

**Comment by XhmikosR** [comment] 2020-10-14 10:32
Duplicate of #31887

**Closed by XhmikosR** 2020-10-14 10:32 UTC
Labels: duplicate
