### ISSUE TITLE
One item remains on navbar line after collapse

### ISSUE THREAD

**Issue by DeveloperLen** [twbs/bootstrap#20941] opened 2016-10-19 12:08 UTC
Dear twbs dudes,

following bug:
If I create a collapsing menu (responsive nav) one item remains on the same line as the brand. It happens if I open the menu. Following workaround I found for myself:

`<nav class="navbar navbar-fixed-top navbar-light bg-faded pull-xs-right">
  <a class="navbar-brand hidden-xs-down" href="#">Stay-linked</a>
  <div class="row hidden-sm-up">
    <div class="col-xs-12 col-sm-1">
      <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#collapsing-nav" aria-controls="collapsing-nav" aria-expanded="false" aria-label="Toggle navigation">
        &#9776;
      </button>
      <a class="navbar-brand" href="#">Stay-linked</a>
    </div>
  </div>
  <div class="collapse navbar-toggleable-xs" id="collapsing-nav">
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
    </ul>
  </div>
</nav>`
It works for me.

Further information:
- OS: Windows 10 (Build: 10.0.10586)
- Browser: Chrome Version 53.0.2785.143 m (64-bit)

Thanks

DeveloperLen
![navbar-collapse-bug](https://cloud.githubusercontent.com/assets/6708551/19518076/57a675ea-9605-11e6-969f-3747b7d3c453.png)
![navbar-collapse-fix](https://cloud.githubusercontent.com/assets/6708551/19518077/57a78fca-9605-11e6-9347-06648642ff96.png)

**Comment by bardiharborow** [comment] 2016-10-19 12:37
Duplicate of #20749. Please search for pre-existing issues in the future.

**Closed** 2016-10-19 16:10 UTC
Labels: css, v4
