### ISSUE TITLE
Dropdown doesn't work with null popperConfig

### ISSUE THREAD

**Issue by afrische** [twbs/bootstrap#29996] opened 2020-01-10 11:39 UTC
Error Message will be 
  `  DROPDOWN: Option "popperConfig" provided type "window" but expected type "(null|object)". `

Could be caused by Angular, as i and other users use Bootsrtap in conjunction with Angular.
Other users have the same problem: 
https://stackoverflow.com/questions/59628601/dropdown-bootstrap-4-doesnt-work-in-production-of-angulars-application 

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
Windows
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
Firefox 68 ESR
- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

Cause seems to be with the toType method, and the typecheck in Dropdown.

```
$ typeof null
> "object"
$ const toType = obj => ({}.toString.call(obj).match(/\s([a-z]+)/i)[1].toLowerCase())
$ toType(null)
> "window"
```

Expected type for popperConfig is [null | object ](https://getbootstrap.com/docs/4.4/components/dropdowns/#options)

For me it is not intuitive why toType(null) should return window, and not null

**Comment by asifuran2019** [comment] 2020-01-12 09:30
Where did you post those Reduced test cases?
Codepen and jsbin urls point to their homepages.

**Comment by XhmikosR** [comment] 2020-01-13 20:20
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and Operating System details.

*This is an automated reply*

**Comment by neil-benn** [comment] 2020-03-09 16:42
I've run into this but tbh I'm not sure how to provide the required reduced test case.  The problem only happens in electron with angular 8.2.14, ng-bootstrap 4.4.1 and popper.js 1.16.1 so you probably can't make it work in CodePen as you need to be in electron.  The stack trace is:

```
C:\Users\neilb\Documents\GitHub\datapaq5\node_modules\bootstrap\dist\js\bootstrap.js:211 Uncaught Error: DROPDOWN: Option "popperConfig" provided type "global" but expected type "(null|object)".
    at Object.typeCheckConfig (C:\Users\neilb\Documents\GitHub\datapaq5\node_modules\bootstrap\dist\js\bootstrap.js:211)
    at Dropdown._getConfig (C:\Users\neilb\Documents\GitHub\datapaq5\node_modules\bootstrap\dist\js\bootstrap.js:1828)
    at new Dropdown (C:\Users\neilb\Documents\GitHub\datapaq5\node_modules\bootstrap\dist\js\bootstrap.js:1670)
    at HTMLButtonElement.<anonymous> (C:\Users\neilb\Documents\GitHub\datapaq5\node_modules\bootstrap\dist\js\bootstrap.js:1917)
    at Function.each (C:\Users\neilb\Documents\GitHub\datapaq5\node_modules\jquery\dist\jquery.js:367)
    at jQuery.fn.init.each (C:\Users\neilb\Documents\GitHub\datapaq5\node_modules\jquery\dist\jquery.js:202)
    at jQuery.fn.init._jQueryInterface (C:\Users\neilb\Documents\GitHub\datapaq5\node_modules\bootstrap\dist\js\bootstrap.js:1911)
    at HTMLButtonElement.<anonymous> (C:\Users\neilb\Documents\GitHub\datapaq5\node_modules\bootstrap\dist\js\bootstrap.js:2094)
    at HTMLDocument.dispatch (C:\Users\neilb\Documents\GitHub\datapaq5\node_modules\jquery\dist\jquery.js:5237)
    at HTMLDocument.elemData.handle (C:\Users\neilb\Documents\GitHub\datapaq5\node_modules\jquery\dist\jquery.js:5044)
```

  The function that fails is:

```
typeCheckConfig: function typeCheckConfig(componentName, config, configTypes) {
      for (var property in configTypes) {
        if (Object.prototype.hasOwnProperty.call(configTypes, property)) {
          var expectedTypes = configTypes[property];
          var value = config[property];
          var valueType = value && Util.isElement(value) ? 'element' : toType(value);

          if (!new RegExp(expectedTypes).test(valueType)) {
            throw new Error(componentName.toUpperCase() + ": " + ("Option \"" + property + "\" provided type \"" + valueType + "\" ") + ("but expected type \"" + expectedTypes + "\"."));
          }
        }
      }
    },
```
The html is:

```
    <!-- Configure Options -->
    <li class="nav-item">
      <button type="button" class="btn ribbon-button" id="configureMenuButton" data-toggle="dropdown" aria-haspopup="true"
        aria-expanded="false">
        <fa-icon class="fa-ribbon" [icon]="['fas', 'cog']"></fa-icon>
        <span class="caption">Configure</span>
      </button>
      <div class="dropdown-menu" aria-labelledby="configureMenuButton">
        <button *ngFor="let action of configureActions" class="dropdown-item " (click)="actionEvent(action)">{{action}}</button>
      </div>
    </li>
```

The configureActions is simply a string array:

`configureActions: String[] = ['Scan', 'Container Reader', 'Export', 'Activators', 'Sound', 'Security'];
`
  As I said; this works when built and running in Chrome but in Electron - it doesn't.  As this is an Angular app with electron running it is not really a simple case of putting some code on an online editor to replciate the issue.  Note that we were on Angular 6 and it wokred fine but we had to upgrade to 8 and that was when it stopped working.

**Comment by XhmikosR** [comment] 2020-03-09 16:54
Judging by the error, it seems something is passing the wrong Popper config (global).

We need a way to reproduce the issue, so please try to make a reduced test repo.

/CC @Johann-S in case you have any ideas

**Comment by neil-benn** [comment] 2020-03-09 17:11
I can't write something in codepen but I can make a project on github and send you the repo link?

**Comment by neil-benn** [comment] 2020-03-09 19:37
OK there is a sample app on github - https://github.com/ZiathLtd/dropdowntest.git.

If you run ng serve the dropdown works just fine.  If you run npm run electron the electron starts up and when you click a button for dropdown you get the above-reported error.  Note that I've kept all of the other modules we use in this app in case one of them is clashing.

  I hope that is sufficient to determine the cause and if you need anything please don't hesitate to contact me.  Thanks again for your help; this has been an issue for me and a few people so I hope it is fixable.

**Comment by Johann-S** [comment] 2020-03-10 09:26
A solution which does not really fix the problem but will help our users, would be to change that line: https://github.com/twbs/bootstrap/blob/master/js/src/dropdown.js#L89

by: `popperConfig: {}`

What do you think @XhmikosR ?

**Comment by Johann-S** [comment] 2020-03-10 10:51
I'll add back the `awaiting reply` label, we need a correct a live case to work on that issue.

So please @neil-benn or @afrische do not hesitate to use those links to build a live example of this issue:

- [CodePen](https://codepen.io/)
- [JS Bin](https://jsbin.com/)
- [Stackblitz](https://stackblitz.com/) (for **Angular**/React projects)

**Comment by neil-benn** [comment] 2020-03-11 12:10
As requested by @XhmikosR; I've made a reduced test case repo that shows it failing in Electron

https://github.com/ZiathLtd/dropdowntest.git.

  This only contains a minimal amount of code that exactly replicates this issue.  All you need to do is to execute npm run electron.

As I said previously I can't do it with CodePen, JS Bin or StackBlitz you've shown because it _only_ happens in electron - it works fine in Chrome.

**Comment by Johann-S** [comment] 2020-03-11 12:13
Can you update your version of Electron please ? You're pretty outdated so the embedded Chromium inside Electron too

**Comment by neil-benn** [comment] 2020-03-11 12:38
That's done electron is 8.1.1 and ngx-electron is at 2.2.0 (I know that ngx-electron won't be affecting this but I did it anyways).  Commited back to the repo

**Comment by neil-benn** [comment] 2020-03-12 16:06
@Johann-S Thanks for resolving that - I'll keep an eye out to see when the pull happens and pick up the version with the fix in it.

**Closed** 2020-03-18 11:10 UTC
Labels: awaiting reply, js, v4
