### ISSUE TITLE
Dropdown sub-menus  

### ISSUE THREAD

**Issue by saboorazizi** [twbs/bootstrap#19845] opened 2016-05-05 07:02 UTC
Hello, 
Could you please add submenus in version 4 and update the examples. I think sub-menus are very important and every need that. I searched for that in this repository but couldn't find that. If you have already add that please give me update links.

I have found something for Bootstrap 3.3.6 from "Vasily" in here: https://vsn4ik.github.io/bootstrap-submenu/

Thanks from your great CSS.

**Comment by bellwood** [comment] 2016-05-05 19:21
Please see: #19814 

There's a ton of work to be done still hence Alpha status

**Comment by cvrebert** [comment] 2016-05-08 07:50
Duplicate of #14944. Please search more in the future. Thanks.

**Closed by cvrebert** 2016-05-08 07:50 UTC
Labels: css, feature, v4
