### ISSUE TITLE
.input-group-addon height doesn't match <input> height

### ISSUE THREAD

**Issue by marvin1023** [twbs/bootstrap#17602] opened 2015-09-15 14:47 UTC
![image](https://cloud.githubusercontent.com/assets/1264591/9879798/714bd73c-5bfb-11e5-9221-1df1e6b68a51.png)

Here is the table-cell, so the padding-top/bottom & line-height is no meaning for the vertical middle

**Comment by cvrebert** [comment] 2015-09-15 20:46
Are you referring to Bootstrap v4? If so, this is a duplicate of #17035.

**Comment by twbs-closer** [comment] 2015-09-30 07:00
Hey there!

We're automatically closing this issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own. Closed issues that remain inactive for a long period may get automatically locked.

Don't worry though; if this is in error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

(*Please note that this is an [automated](https://github.com/twbs/no-carrier) comment.*)

**Closed by twbs-closer** 2015-09-30 07:00 UTC
Labels: awaiting reply, css
