### ISSUE TITLE
Custom Radio's Active State Not Removed Using Keyboard

### ISSUE THREAD

**Issue by samneub** [twbs/bootstrap#24565] opened 2017-10-26 16:26 UTC
When using keyboard navigation, the active state of the custom-control-indicator is set upon pressing space. Not sure if the lighter color behavior is intended on space press, but regardless when you move away from the button it leaves it 'active' and the color stays.

![screen shot 2017-10-26 at 11 25 19 am](https://user-images.githubusercontent.com/13904823/32064798-845f9dcc-ba40-11e7-854a-8ea2f12247c1.png)

**Comment by mdo** [comment] 2017-11-07 15:38
Can't reproduce, so closing. Tabbing to the first radio and hitting space checks the radio, and using left/right arrow keys moves the focus and check across each radio.

**Closed by mdo** 2017-11-07 15:38 UTC
Labels: accessibility, v4
