### ISSUE TITLE
Collapse.js Left & Right [Feature Req.]

### ISSUE THREAD

**Issue by davebowker** [twbs/bootstrap#21303] opened 2016-12-05 16:36 UTC
I'm currently working on an off canvas navigation and I'm trying to use BS as much as possible. 

I implemented a nav as standard and just styled it to be like a sidebar. When applying collapse to it, as I would a top of page nav, the functionality works but collapse is setting `height:0` and scrolling vertical. I can overcome a lot of this in CSS. 

Feature Idea: Can we also collapse left/right with `.collapse-h` or `.collapse-v` and then we can do the rest in CSS?

Thanks

**EDIT:**
I see that you can add .width to dictate collapse direction, however it's not working 100% and is much worse when using flexbox.

**Comment by judetucker** [comment] 2017-01-05 04:47
@davebowker check out #21540. Is this the desired functionality?

**Comment by davebowker** [comment] 2017-01-05 10:17
@judetucker Yup! Looks good, nice job, bud! :)

**Comment by mdo** [comment] 2017-07-02 05:43
Closing as dupe of #17496.

**Closed by mdo** 2017-07-02 05:43 UTC
Labels: feature, js, v4
