### ISSUE TITLE
Card images ratio issue

### ISSUE THREAD

**Issue by Zmove** [twbs/bootstrap#22020] opened 2017-02-17 08:15 UTC
Hello,

Sometimes when you deal with responsive layout, your 1 column cards are larger on mobile device than the 4 column desktop version.

The problem is that the image behave weirdly not respecting image ratio.

I think it would be a better default behavior to add "object-fit: cover;" to card images.

With that rule, instead of stretching the image, it will crop it to maintain ratio.

**Default example**
![without object fit](https://cloud.githubusercontent.com/assets/1314678/23057680/85b8cbd6-f4f1-11e6-8732-b97e42ded1de.PNG)

**With object-fit rule**
![with object-fit](https://cloud.githubusercontent.com/assets/1314678/23057681/85bb7ba6-f4f1-11e6-9837-41f6e87d679f.PNG)

**Comment by erkstruwe** [comment] 2017-02-25 07:21
@Zmove, is this the same issue as in #21650?

**Comment by triggerman722** [comment] 2017-02-25 22:47
FYI - I believe doing this works (i.e. add no-gutters class to card and col-12 to the img):

```
<div class="card no-gutters">
   <img class="card-img-top col-12" src="..." alt="Card image cap">
   <div class="card-block">
      <h4 class="card-title">Card title</h4>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
   </div>
</div>
```

**Comment by mdo** [comment] 2017-03-03 19:26
Closing as a dupe of #21650.

**Closed by mdo** 2017-03-03 19:26 UTC
Labels: css, v4
