### ISSUE TITLE
backdrop on modal resize

### ISSUE THREAD

**Issue by vasena** [twbs/bootstrap#15833] opened 2015-02-18 09:19 UTC
I load content into modal, so the size of modal changes, but not the size of backdrop, so when I scroll down I see the end of backdrop and can access underlayer. In previous version there were no error

**Comment by kkirsche** [comment] 2015-02-18 13:27
Seems related to: #15106 and #15418

**Comment by DaSchTour** [comment] 2015-02-18 14:00
also related to: #15136 and #15314 I guess there are even a lot more related topics to the broken modal backdrop

**Comment by cvrebert** [comment] 2015-02-18 22:12
Closing as a duplicate of other open issues.

**Closed by cvrebert** 2015-02-18 22:12 UTC
Labels: css, js
