### ISSUE TITLE
Problem with dropstart

### ISSUE THREAD

**Issue by YisusCore** [twbs/bootstrap#32735] opened 2021-01-09 03:10 UTC
https://github.com/twbs/bootstrap/blob/80557b3ac02bb21823a483013d9a0af5203bb7c2/scss/_dropdown.scss#L38

```css
  // Reset positioning when positioned with Popper
  &[style] {
    right: auto#{"/* rtl:ignore */"} !important; // stylelint-disable-line declaration-no-important
  }
```

![error](https://user-images.githubusercontent.com/43710620/104081651-0ad1d980-51fe-11eb-9868-037845372e9e.png)

I solved it with:

```css
  // Reset positioning when positioned with Popper
  &:not([data-popper-placement^='left-'])[style] {
    right: auto#{"/* rtl:ignore */"} !important; // stylelint-disable-line declaration-no-important
  }
```

![success](https://user-images.githubusercontent.com/43710620/104081678-305ee300-51fe-11eb-9ab9-d8e1675f3df7.png)

**Comment by kyletsang** [comment] 2021-01-12 06:02
Duplicate of #32484

**Closed** 2021-01-13 11:09 UTC
Labels: duplicate
