### ISSUE TITLE
is-invalid style should override pseudo selectors

### ISSUE THREAD

**Issue by xyide** [twbs/bootstrap#30822] opened 2020-05-14 11:16 UTC
In the case where the `:valid` pseudo-selector is specified on a form-control along with the `is-invalid` class, then the style of the `is-valid` class should take priority.

**Example Scenario:**
A registration form is submitted and client side HTML validation is performed using `form.checkValidity()`.  The required username field is considered valid and internally has the `:valid` pseudo selector set.  An AJAX request is then submitted to the server.  The server responds saying the username is already registered, so we set the 'is-invalid' class in the form control.

At this point the border around the form control remains green instead of changing to red because the `.was-validated .form-control:valid` style is being applied and overriding style specified by `.form-control.is-invalid`.

There is a fiddle at https://jsfiddle.net/r4g06a21/ to demonstrate the issue.

To resolve this issue, I had to create the following styles:

```css
.was-validated .form-control:valid.is-invalid {
    border-color: red;
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='%23f83245' viewBox='-2 -2 7 7'%3e%3cpath stroke='%23f83245' d='M0 0l3 3m0-3L0 3'/%3e%3ccircle r='.5'/%3e%3ccircle cx='3' r='.5'/%3e%3ccircle cy='3' r='.5'/%3e%3ccircle cx='3' cy='3' r='.5'/%3e%3c/svg%3E"); 
}

.was-validated .form-control:valid:focus.is-invalid:focus {
      border-color: red; 
}
```

The fiddle at https://jsfiddle.net/bfLzvad3/ demonstrates this solution.  Not sure if it is the best approach for the fix, but it does what I need it to do.

**Comment by xyide** [comment] 2020-05-14 11:22
To resolve this issue, I had to create the following styles:

```
.was-validated .form-control:valid.is-invalid {
    border-color: red;
    background-image: url("data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' fill='%23f83245' viewBox='-2 -2 7 7'%3e%3cpath stroke='%23f83245' d='M0 0l3 3m0-3L0 3'/%3e%3ccircle r='.5'/%3e%3ccircle cx='3' r='.5'/%3e%3ccircle cy='3' r='.5'/%3e%3ccircle cx='3' cy='3' r='.5'/%3e%3c/svg%3E"); 
}

.was-validated .form-control:valid:focus.is-invalid:focus {
      border-color: red; 
}
```

The fiddle at https://jsfiddle.net/bfLzvad3/ demonstrates this solution.  Not sure if it is the best approach for the fix, but it does what I need it to do.

**Comment by XhmikosR** [comment] 2020-05-14 12:06
Confirmed for v4, I didn't test v5 so if someone checks please update the issue labels.

**Comment by mdo** [comment] 2020-05-14 16:40
These approaches were designed to be used separately, not together. Not sure I want us to go down this path. Thoughts from @twbs/css-review?

**Comment by MartijnCuppens** [comment] 2020-05-15 20:25
> These approaches were designed to be used separately, not together.

Indeed.

**Comment by xyide** [comment] 2020-05-15 21:42
> These approaches were designed to be used separately, not together. Not sure I want us to go down this path. Thoughts from @twbs/css-review?

Understood.  The styles I created are likely not the optimal solution, but I needed something working for a project.  The case remains though that a form countrol could simultaneously be in a `:valid` pseudo state and have the `has-error` class.

Normally I would think an explicit class specified on an element should override any implicit ones.

**Comment by MartijnCuppens** [comment] 2020-05-16 09:45
> Normally I would think an explicit class specified on an element should override any implicit ones.

That depends on the situation I guess. I would recommend using one way to validate field, since you're already using AJAX, I would go that way (you will need server validation anyway)

**Comment by xyide** [comment] 2020-05-16 16:14
> > ... since you're already using AJAX, I would go that way (you will need server validation anyway)

Yes, there will be server side validation, but basic client side validation (ex. making sure required fields are populated) should also be performed to avoid unnecessary round trips.  We could use javascript to manually perform some validation on the client, but this is easily handled by simply adding the `required` attribute on the input and using HTML5 form validation (i.e. form.checkValidity()).

**Comment by ffoodd** [comment] 2020-05-18 08:46
FWIW, there are at least two ways to solve this, being either hacky or verbose:
1. duplicate the class selector in the `form-validation-state-selector()` mixin to enforce the class specificity (eg  outputting `.was-validated .form-control:valid, .form-control.is-valid.is-valid.is-valid`) which should work by artificially bumping the selectors weight;
2. separate pseudo-classes and classes to output pseudo-classes (both `:valid` and `:invalid`) before every .`is-*` classes: with an equivalent specificity, the last would match — but this would in fact invert the issue if someone prefers relying on pseudo-classes instead of classes → would this case exist?

Both would increase file size, the second being less hacky (bu probably harder to implement).

The other way around is documenting more explicitly that those methods can't be used together, and promoting default validation check prevention if server side one is used.

Don't know what to do with this, though :')

**Comment by mdo** [comment] 2020-05-21 00:39
Turns out this is a duplicate of #24743, so closing as such.

**Closed by mdo** 2020-05-21 00:39 UTC
Labels: css, v4
