### ISSUE TITLE
Global variable to enable box-shadow for focused inputs/buttons (v5)

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#33413] opened 2021-03-20 07:38 UTC
Now we have `$enable-shadows`, but this var does not affect `box-shadow`s used for focus states. I vote to add additional variable `$enable-shadows-on-focus` (or something like this) to toggle `box-shadow` on focus/hover/active.

Also, I vote to add additional validation like as `@if $enable-shadows-on-focus and $input-btn-focus-box-shadow != none`.

**Comment by korki43** [comment] 2021-03-20 15:26
You can set `$input-btn-focus-width` to `0` disable box-shadows for focused buttons and inputs.

**Comment by WinterSilence** [comment] 2021-03-20 16:20
@korki43 Yes, but why do you need unnecessary properties?

**Comment by ffoodd** [comment] 2021-03-22 08:19
Duplicate of #32412, #32032 and clarified in the docs in #32685.

We set our **focus styles** using shadows, and since we couldn't ensure anyone disabling those shadows would set proper focus styles, we don't provide a way to change this.

Focus styles are mandatory, using `box-shadow` allows more theming than keeping `outline`.

**Closed by ffoodd** 2021-03-22 08:19 UTC
Labels: feature

**Comment by WinterSilence** [comment] 2021-03-22 09:26
@ffoodd

> We set our focus styles using shadows, and since we couldn't ensure anyone disabling those shadows would set proper focus styles, we don't provide a way to change this.

How can users not want any "outer glow" on focusing? Changing background and border color is enough for me.

> Focus styles are mandatory, using box-shadow allows more theming than keeping outline.

I don't dispute that.

**Comment by ffoodd** [comment] 2021-03-22 11:28
The first one is v5 and the PR too. If you've read discussions you'd noticed adding such variable has been suggested already.


Changing background and borders **is not enough** regarding accessibility, since you'd basically convey focus state with color only.

So, since we aim to enforce accessibility, we don't provide an easy way to drop focus styles.

**Comment by WinterSilence** [comment] 2021-03-22 17:48
@ffoodd  
> If you've read discussions you'd noticed adding such variable has been suggested already.

I don't found comments about new behavior variable.

> aim to enforce accessibility

I don't understand you
