### ISSUE TITLE
Banner on Official Website is not changed

### ISSUE THREAD

**Issue by skmedix** [twbs/bootstrap#20452] opened 2016-08-03 18:22 UTC
Blue banner about Bootstrap 4 on [Main Page](https://getbootstrap.com/) still pointing to the post with Alpha 2 instead of Alpha 3.

**Comment by judetucker** [comment] 2016-08-03 20:34
I think this is a duplicate of #20407

**Comment by mdo** [comment] 2016-08-04 01:22
Yup! Duplicate.

**Closed by mdo** 2016-08-04 01:22 UTC
Labels: docs, v3
