### ISSUE TITLE
 Bootstrap 5 is using a deprecated CSS property!

### ISSUE THREAD

**Issue by Allmedialab** [twbs/bootstrap#36331] opened 2022-05-11 09:37 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi,

When I install Bootstrap 5 with Codekit I get this warning:

autoprefixer: /Users/davidakinci/Library/Mobile Documents/com~apple~CloudDocs/bootstrap-test/build/styles/main.css:7528:3: Replace color-adjust to print-color-adjust. **The color-adjust shorthand is currently deprecated.**

It seems like Bootstrap 5 is using a deprecated CSS property!

Regards,
David

### Reduced test cases

Just install Bootstrap with npm!

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by coliff** [comment] 2022-05-11 10:42
This is a duplicate of https://github.com/twbs/bootstrap/issues/36259

**Closed** 2022-05-11 14:47 UTC
