### ISSUE TITLE
Navbar doesn't collapse on Android Chrome

### ISSUE THREAD

**Issue by SowmiyaPachiyappan** [twbs/bootstrap#20846] opened 2016-10-06 12:31 UTC
Before opening an issue:
- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://validator.w3.org/nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Prepare a [reduced test case](https://css-tricks.com/reduced-test-cases/) for any bugs
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

When asking general "how to" questions:
- Please do not open an issue here
- Instead, ask for help on [StackOverflow, IRC, or Slack](https://github.com/twbs/bootstrap/blob/master/README.md#community)

When reporting a bug, include:
- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)

When suggesting a feature, include:
- As much detail as possible for what we should add and why it's important to Bootstrap
- Relevant links to prior art, screenshots, or live demos whenever possible

**Comment by SowmiyaPachiyappan** [comment] 2016-10-06 12:37
I am using Android.I am testing a file in chrome browser.Bootstrap Navbar toggle button is not expanding.But in other browsers it works well.Is there any solution for this?

**Comment by cvrebert** [comment] 2016-10-07 07:03
As mentioned in the template, please state what Android version and Chrome version you are using.

**Comment by SowmiyaPachiyappan** [comment] 2016-10-09 15:50
my problem is,
In mobile chrome browser, Bootstrap navbar toggle button is not clickable.When I click a particular space of toggle button at zooming,It shows menu.How to fix this? and how to make a entire space of navbar toggle button is clickable in mobile chrome?But it works fine in other mobile and desktop browsers.

**Comment by mdo** [comment] 2016-10-10 02:05
Without an example reduced test case, we can't help. The navbar works as intended for me on all platforms with the current code in our `v4-dev` branch. Make sure you have all the correct CSS, JS, and HTML in place, and share a test case when you can.

**Comment by kayzore** [comment] 2016-10-26 13:16
Hello !
I have exactly the same problem on one of my projects. I downloaded the css files and js bootstrap v4 there for three days, I do not think I could have more recent.
The documentation does not indicate any problem with the navbar.
Have you solved your problem? If so can you tell me how?

**Comment by mdo** [comment] 2016-10-26 23:09
Until we have a reduced test case, we can't help. Please share a URL that has a reproducible example of the problem you're hitting.

**Comment by Xerillius** [comment] 2016-11-14 01:33
I would be willing to look at your source code and help you figure out what's going on. I've tested my use of bootstrap on as many desktop and mobile browsers as I can and I've run into no problems. Let me know if you would like me to have a look.

**Comment by mdo** [comment] 2016-11-26 10:28
Closing since we haven't had a reproducible test case yet. Holler when you do and we can revisit.

**Closed by mdo** 2016-11-26 10:28 UTC
Labels: awaiting reply, v4

**Comment by ifeldman0** [comment] 2017-03-06 21:51
I was having the same issue, and it was caused by my failure to include the required meta tag 
`<meta content="width=device-width,initial-scale=1" name="viewport" />`.

**Comment by biwerr** [comment] 2017-06-06 10:16
@SowmiyaPachiyappan in my Case the registered event `click.bs.collapse.data-api` was not triggered. It seems that the event is only fired if your navbar button is a html-button and not a div element.

Another strange behavoir is: if a normal click event is registered the collapse works fine, regardless which html element is used
