### ISSUE TITLE
v4 docs overflow <= 526px width

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#18484] opened 2015-12-08 19:29 UTC
![2015-12-08_21-28-17](https://cloud.githubusercontent.com/assets/349621/11665967/aebdc9fc-9df2-11e5-921f-0add8784862c.png)

/cc @mdo

**Comment by cvrebert** [comment] 2015-12-09 02:45
Seems to be caused by the `<figure>` for the Bootstrap CDN code snippet.

**Comment by mdo** [comment] 2016-01-06 04:48
Fixed in #18734.

**Closed by mdo** 2016-01-06 04:48 UTC
Labels: confirmed, css, docs, v4
