### ISSUE TITLE
Modal scrolls viewport when a ratio class has been used before

### ISSUE THREAD

**Issue by dgsiegel** [twbs/bootstrap#34482] opened 2021-07-12 13:34 UTC
- Operating system: Linux, Windows (others not tested)
- Browser: Firefox & Chrome (others not tested)

This is probably a regression happened between `5.0.0-beta3` and `5.0.0`.

Suppose you have a `div` element with the aspect ratio helper, e.g.

```
      <div class="ratio ratio-1x1">
        <div>1x1</div>
      </div>
```

If you now add a modal later in the page, the viewport will jump down about 12px (probably the default scrollbar width) when you open the modal. This only happens when the div with the `ratio` class is not visible, ie. if both the `ratio` div and the modal button are inside the visible portion of the screen everything works like expected.

Here's Bootstrap `5.0.0-beta3` working fine. Codepen: https://codepen.io/bbtz5pqoyv/pen/qBmqrvw

https://user-images.githubusercontent.com/4396895/125296103-3ad17500-e326-11eb-9a99-ef6625a84d22.mp4

Here's Bootstrap `5.0.0.` showcasing the jump when the ratio div (light blue) is no longer visible. Codepen: https://codepen.io/bbtz5pqoyv/pen/wvdoJRo

https://user-images.githubusercontent.com/4396895/125296122-402ebf80-e326-11eb-86a1-3e86ccf36008.mp4

I've also tested `5.0.1` and `5.0.2` and both behave like `5.0.0`. which hints that the bug was introduced between `5.0.0-beta3` and `5.0.0`.

**Comment by mdo** [comment] 2022-04-08 20:37
I beleive this may have been caused by the scroll padding issue, which we're fixing in v5.2.0 with #35736. Closing out.

**Closed by mdo** 2022-04-08 20:37 UTC
Labels: js, v5
