### ISSUE TITLE
Pressing key Home or End breaks Affix positioning

### ISSUE THREAD

**Issue by gustavohban** [twbs/bootstrap#15847] opened 2015-02-19 22:13 UTC
You can check this right on the Bootstrap website.
I was able to replicate this issue using Chrome and IE 11.
Firefox worked fine.

How to reproduce:

Using end key:

1 - Navigate to http://getbootstrap.com/css/
2 - Without scrolling, press the keyboard key ''end"

** The affix element is supposed to go through .affix-top to .affix-bottom, but instead the final class is .affix

![issue2-affix-1](https://cloud.githubusercontent.com/assets/6200550/6277188/1a46ae8c-b852-11e4-85eb-ba91d38e8392.jpg)

Using home key:

1 - Navigate to http://getbootstrap.com/css/
2 - Scroll down the page until you reach the bottom/footer
3 - At the bottom, press the key "home"

** Is the same problem, but now the affix element is supposed to go trough .affix-bottom to .affix-top, but again the final class is .affix

![issue-affix-5](https://cloud.githubusercontent.com/assets/6200550/6277199/35188f82-b852-11e4-9bb8-15e342c585bf.jpg)

**Comment by cvrebert** [comment] 2015-02-19 23:38
Duplicate of #9609.

**Comment by kkirsche** [comment] 2015-02-21 05:14
Is it due to performance that the Affix plugin doesn't use @fat's snippet or something similar watching for a home / end key press or is there another reason?

**Comment by cvrebert** [comment] 2015-04-09 00:47
I'm guessing he considered the missing `scroll` event to be a browser bug.
The thing is, at least on OS X, current Chrome **does** fire a `scroll` event when pressing the equivalent of Home/End, yet the Affix positioning bug still occurs.

**Comment by cvrebert** [comment] 2015-04-09 01:26
Seems to me like there's a bug in the `Affix.prototype.getState()` logic.
[When in the `bottom` state](https://github.com/twbs/bootstrap/blob/4127b250db461e47639983e2ad177963316386e1/js/affix.js#L47), `top` can *never* be returned as the new state, although that's exactly what seems to be needed here.
If you're at the bottom of the page, `this.affixed` is `bottom` and `getState` returns `bottom`.
If you then press Home to go to the top of the page, the scroll event changes the state from `bottom` to `false`, which leaves the affixed element positioned incorrectly.
If you then fire a dummy `scroll` event via `$(document).trigger('scroll')`, the state changes from `false` to `top`, which corrects the affixed element's position.

**Comment by mdo** [comment] 2016-09-05 22:24
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Closed by mdo** 2016-09-05 22:24 UTC
Labels: confirmed, js, v3
