### ISSUE TITLE
z-index of .sticky-top is above the .dropdown-menu

### ISSUE THREAD

**Issue by utilmind** [twbs/bootstrap#37184] opened 2022-09-20 21:06 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

`.dropdown-menu` with z-index: 1000 (or 1001 on BS4), appears under the `.sticky-top` panel (with z-index 1020), even when sticky-top in normal, "unsticky" state, as regular &lt;div&gt;.

### Reduced test cases

The following screenshot demonstrates the issue better than code samples:
<img src="https://utilmind.com/stuff/zindex-issue.png" width="453" height="383" border="0" />

You can see that sticky panel with labels "Retail", "Agency" and "Production cost" overlaps the dropdown menu that appears after clicking the "Columns" button over the "Bootstrap-table".

The following CSS (override) fixing the issue, but this fix probably should be canonical. Dropdown menus must appear above the sticky panels.

```
.dropdown-menu {
    z-index: 1040 !important; /* default is 1001 on BS4 or 1000 on BS5. But it supposed to be above all sticky and fixed panels. */
}
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

Tested on v4.6 and v5.2, this issue applies to both

**Comment by KORLA2** [comment] 2022-09-21 06:57
Hello I am new to open source I want to contribute  to this repo on this issue can you please tell me in which file this problem is present

**Comment by utilmind** [comment] 2022-09-21 07:03
> Hello I am new to open source I want to contribute to this repo on this issue can you please tell me in which file this problem is present

The fix should be applied to `/scss/_variables.scss` (if it will not be declined by reason I'm not aware yet).

Z-index for dropdown menus specified in `$zindex-dropdown` variable:

`$zindex-dropdown:                   1000 !default;`

**Comment by mdo** [comment] 2022-09-21 10:05
Duplicate of #31747 I think. Our z-index layers are carefully crafted for our components, but there's an assumption made on content vs navigation. Read the referenced issue for now, and we'll consider a fix for v6.

**Closed by mdo** 2022-09-21 10:05 UTC
