### ISSUE TITLE
Modals that dynamically exceed screen height cannot scroll on iOS

### ISSUE THREAD

**Issue by russplaysguitar** [twbs/bootstrap#20256] opened 2016-07-07 22:55 UTC
Steps to reproduce the issue:

1. Open test case on iOS device: https://jsbin.com/meqaguyoxi/2
2. Click button to open the modal dialog
3. Click the link in the dialog to dynamically expand the dialog's height
4. Attempt to scroll to the bottom of the dialog

Expected Results: Dialog should scroll down. 

Actual Results: Dialog does not scroll, but the document behind it does. 

I've found a workaround that seems to trick the browser into thinking that the modal is always scroll-able: 
```
    .modal-dialog {
        height: 101%;
    }
```

Issue was reproducible on iOS 8.1 Safari (iPad), iOS 9.3.2 Safari (iPhone), and iOS 9.3.2 Chrome (iPhone). 
Could not reproduce issue on Android 6.0.1 Chrome.

**Comment by cvrebert** [comment] 2016-07-08 03:31
Duplicate of #17695.

**Closed by cvrebert** 2016-07-08 03:31 UTC
Labels: browser bug, css, v3

**Comment by glaucocustodio** [comment] 2016-09-21 18:10
It is still happening on 3.3.7. Thanks for the workaround @russplaysguitar.
