### ISSUE TITLE
Table row colors (table-*) with table-stripped

### ISSUE THREAD

**Issue by csimpi** [twbs/bootstrap#28895] opened 2019-06-12 03:07 UTC
Dear Developers,
thank you for Bootstrap 4 ❤️ .

I'm not sure if this is not a bug, but as I experienced the `table-stripped` is not supported with any contextual classes like `table-primary`,`table-success` etc...

My quick CSS hack for this:
```
.table-striped tbody tr.table-primary:nth-of-type(odd) > td{
    background-color: #d6ebff !important;
}

.table-striped tbody tr.table-success:nth-of-type(odd) > td{
    background-color: #d8f2de !important;
}
```

**Comment by ysds** [comment] 2019-06-13 15:30
Thank you for reporting this, but closing since duplicate of #28725.

**Closed by ysds** 2019-06-13 15:30 UTC

**Comment by csimpi** [comment] 2019-06-13 19:55
@ysds This is not the same. I sent this as a feature request and not as a bug. I think this should be implemented but the maintainers don't want to do it, so I'd let the audience to decide if they would need this feature. 
I'd also recommend editing the referenced issue's title, I couldn't find it when I was searching for similar tickets.
