### ISSUE TITLE
Selects are STILL cut off in Chrome on Windows

### ISSUE THREAD

**Issue by kjdion84** [twbs/bootstrap#24043] opened 2017-09-21 21:38 UTC
Not to mention the padding is also STILL inconsistent with other input fields.

Screenshot:

![Imgur](https://i.imgur.com/liPJliv.png)

I am using the latest Chrome on Windows 10.

As of August 2017 Windows 10 is 36.9% of OS share.
As of August 2017 Chrome is 76.9% of browser share.

Source: https://www.w3schools.com/browsers/default.asp

**Comment by patrickhlauke** [comment] 2017-09-21 21:45
Duplicate of https://github.com/twbs/bootstrap/issues/23347

**Closed by patrickhlauke** 2017-09-21 21:45 UTC

**Comment by kjdion84** [comment] 2017-09-21 21:47
It isn't a duplicate because that thread doesn't address the padding inconsistency issues that are also present.
