### ISSUE TITLE
Update responsive navbar padding to use variables

### ISSUE THREAD

**Issue by wojtask9** [twbs/bootstrap#23034] opened 2017-07-09 23:08 UTC
Currently .nabvar-expand-* classes adds padding to .nav-link wrapped by `media-breakpoint-up`
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L168-L171

This should be moved few lines above to `media-breakpoint-down`  https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L143 

It would be great if those paddings were variables.

EDIT:
should be moved to `media-breakpoint-down`

**Comment by mdo** [comment] 2017-07-14 23:42
Without a screenshot or demo of what you're running into, I can't help more. The paddings have been built this way by design. Agreed though we need variables there.

**Comment by wojtask9** [comment] 2017-07-15 09:41
If you plan to make variables then moving to `media-breakpoint-down` is not necessary

**Comment by mdo** [comment] 2018-01-03 23:59
I believe this was closed by #25117.

**Closed by mdo** 2018-01-03 23:59 UTC
Labels: css, v4
