### ISSUE TITLE
Position of labels and checkboxes/radios bad in Firefox on KDE GNU/Linux

### ISSUE THREAD

**Issue by wolftune** [twbs/bootstrap#15791] opened 2015-02-11 05:19 UTC
From right on the Bootstrap website itself. Looks ok in Chromium but lousy in Firefox:

![bad-radio-checkbox-positions](https://cloud.githubusercontent.com/assets/2801853/6142378/3896f750-b16a-11e4-9fa6-1f44b94306ac.png)

That's just a screen-shot from http://getbootstrap.com/css/ visited in Firefox 35.0.1 on Ubuntu. Most noticeably, the vertical-alignment is off, but it also seems to lack some space between the buttons and the labels.

**Comment by kkirsche** [comment] 2015-02-11 14:02
I think this has more to do with the operating system then the theme. It's due to the larger size of the default buttons. Firefox 35.0.1 on Mac looks fine in that same part:

![screen shot 2015-02-11 at 9 02 16 am](https://cloud.githubusercontent.com/assets/947110/6148130/b50e114e-b1cc-11e4-90bf-678327d96b41.png)

Unless they override OS button styles, I'm not sure this is worth chasing.

**Comment by wolftune** [comment] 2015-02-11 16:05
This is *not* strictly OS-related because the same thing looks fine on Chromium on the same OS.

**Comment by patrickhlauke** [comment] 2015-02-11 16:13
It *is* OS-specific, as I suspect Firefox on Linux uses the OS-native form controls (they used to on Win and Mac for the longest time as well), while Chromium does its completely custom controls.

**Comment by patrickhlauke** [comment] 2015-02-11 16:19
In principle though, I agree it would be useful to ensure that even on Linux, the control + label combo is at least vertically centered somehow...

**Comment by wolftune** [comment] 2015-02-11 16:20
I don't know if this is helpful or what else to do, but it looks good on my system if I make the buttons `position: relative` instead of absolute and use `vertical-align: sub`. But that's a hacky solution it seems.

**Comment by kkirsche** [comment] 2015-02-11 16:27
Firefox on Ubuntu 14.04 Unity

![screen shot 2015-02-11 at 11 22 21 am](https://cloud.githubusercontent.com/assets/947110/6150995/d654940e-b1e0-11e4-9e52-39e7f92559e5.png)
![screen shot 2015-02-11 at 11 26 07 am](https://cloud.githubusercontent.com/assets/947110/6150996/d6557770-b1e0-11e4-9502-6a25e30b639d.png)

Will pull up my copy of KDE next.

**Comment by kkirsche** [comment] 2015-02-11 16:44
Yep, I can duplicate it only with Kubuntu 14.10 Plasma 4

![screen shot 2015-02-11 at 11 42 58 am](https://cloud.githubusercontent.com/assets/947110/6151373/3bb48974-b1e3-11e4-85ff-0c6f9585ce6f.png)

I personally would recommend filing the bug with [KDE](https://bugs.kde.org/) or [Firefox](https://bugzilla.mozilla.org/) as this seems more related to them than Bootstrap.

**Comment by wolftune** [comment] 2015-02-11 16:49
Even on that Unity screen-shot the vertical align is *a little* off…

**Comment by wolftune** [comment] 2015-02-11 16:56
I found <https://bugzilla.mozilla.org/show_bug.cgi?id=210212&GoAheadAndLogIn=1>

But that's 12 years old, and I can't tell if it's really related. Maybe a new ticket makes sense, I'm unsure.

**Comment by wolftune** [comment] 2015-02-11 17:04
Note that on a plain site with no Bootstrap at all, the look isn't super, but it's not so bad.

I used

````
<form method="get">
<input type="radio" value="Red" name="preferred_color"> Red<br>
<input type="radio" value="Blue" name="preferred_color"> Blue<br>
<input type="radio" value="Green" name="preferred_color"> Green<br>
<input type="submit" value="Submit">
</form>
````

And got 
![simpleradios](https://cloud.githubusercontent.com/assets/2801853/6151776/dccd05e6-b1cc-11e4-9832-2465e8f15498.png)

So, it's not like Firefox in KDE is just doing this stuff badly always.

**Comment by kkirsche** [comment] 2015-02-11 19:16
Same result as you just posted @wolftune after `normalize.css` is applied. Just working through identifying if this is in Bootstrap itself and making sure it's not in an upstream item they are using

**Comment by K4T** [comment] 2015-03-04 16:22
Same problem here on those browsers:
Desktop: Firefox 35, 36
Mobile: Iphone 5 newest Safari browser, native Android 4.3 browser.

Funny thing: that problem doesn`t occur on Firefox mobile. 

Are you really sure that is browser bug? Any chances to get it work?

**Comment by kkirsche** [comment] 2015-03-04 16:27
@K4T — what operating system for the Desktop browsers? Are you confirming simply for KDE based Linux systems on those versions or other operating system(s)? If other operating systems, could you please state those so they can be confirmed.

On my iPhone 5S yes it's a _tiny_ bit higher, but not nearly like in the examples shown in my opinion. Thanks for sharing your take on it though. :smiley:

**Comment by K4T** [comment] 2015-03-04 16:28
@kkirsche I tested it on Windows 8.1.

**Comment by patrickhlauke** [comment] 2015-03-04 16:59
Confirming that there is a very slight vertical misalignment here in iOS/Safari and Win8.1/Firefox - so it may indeed need a slight tweak somewhere... /cc @mdo 

![ios-safari](https://cloud.githubusercontent.com/assets/895831/6488493/d1da9c4c-c28f-11e4-9bdb-15e88d0a9608.png)

![bootstrap-radio-check-firefox](https://cloud.githubusercontent.com/assets/895831/6488502/d733937e-c28f-11e4-8d0c-a9116d544bf3.png)

**Comment by patrickhlauke** [comment] 2015-03-04 17:05
Just playing a bit, it seems adding a ``vertical-align:middle`` on the outer ``<label>`` fixed it (not thoroughly tested with long label text etc, likely to break in those scenarios though)

**Comment by mdo** [comment] 2015-03-28 06:49
There's no easy way to accomplish 100% cross browser consistency here. Some of the Linux browsers are bound to cause problems like this. Punting as a won't fix.

**Closed by mdo** 2015-03-28 06:49 UTC
Labels: browser bug, confirmed, css

**Comment by wolftune** [comment] 2015-03-28 16:19
We don't need 100% cross-browser consistency, we just need it not to be really off, as it is in KDE Firefox… The rest of the examples are just subtle and can be ignored, but please don't just lump everything together. There's a specific case that is really off and should be fixed…
