### ISSUE TITLE
Input date type open on click

### ISSUE THREAD

**Issue by happilymarrieddad** [twbs/bootstrap#24770] opened 2017-11-13 23:30 UTC
Hey guys,

Is there a way to open the calender for the input(type='date') on click?  Basically, I want a way to open the calender on click like what happened on bootstrap 3. Thanks!

This code is in BS 4, Vue 2.5.3, and BootstrapVue but it uses standard bootstrap inside the components so any bootstrap solution will work. Thanks!

![selection_103](https://user-images.githubusercontent.com/6416323/32754872-e507e186-c88f-11e7-97f8-45ecf4ac8726.png)
![selection_104](https://user-images.githubusercontent.com/6416323/32754878-e7fa630a-c88f-11e7-8e04-1c167f6aae3c.png)

**Comment by bkdotcom** [comment] 2017-11-14 02:07
Duplicate of 
https://github.com/bootstrap-vue/bootstrap-vue/issues/1342
oddly enough also opened by @happilymarrieddad

**Comment by tmorehouse** [comment] 2017-11-14 02:36
It is a native browser "feature/issue", as it varies by browser and platform (i.e. mobile browsers will immediately show datepicker if clicked, while desktop browsers one must click the caret icon inside the date input.

**Comment by mdo** [comment] 2017-11-14 03:15
Closing as not a Bootstrap bug. This is by browser.

**Closed by mdo** 2017-11-14 03:15 UTC
