### ISSUE TITLE
btb xs

### ISSUE THREAD

**Issue by harmenbos** [twbs/bootstrap#36628] opened 2022-06-23 21:14 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Can you add a btn-xs feature? This is available in BS3

in BS5 we have only btn-sm:

.btn-sm, .btn-group-sm > .btn {
  --bs-btn-padding-y: 0.25rem;
  --bs-btn-padding-x: 0.5rem;
  --bs-btn-font-size: 0.875rem;
  --bs-btn-border-radius: 0.25rem;
}

Something like this:

.btn-xs, .btn-group-xs > .btn {
  --bs-btn-padding-y: 0.15rem;
  --bs-btn-padding-x: 0.3rem;
  --bs-btn-font-size: 0.6rem;
  --bs-btn-border-radius: 0.12rem;
}

### Motivation and context

I use small buttons.

**Comment by julien-deramond** [comment] 2022-06-24 11:57
Duplicate of https://github.com/twbs/bootstrap/issues/21881. @harmenbos, an answer is provided in https://github.com/twbs/bootstrap/issues/21881#issuecomment-276604397.

**Closed** 2022-06-24 11:57 UTC
Labels: feature
