### ISSUE TITLE
Card background-variants don't play nicely with .text-muted

### ISSUE THREAD

**Issue by petetnt** [twbs/bootstrap#17244] opened 2015-08-23 12:56 UTC
Adding `card-primary` and `card-inverse` to the header + footer example results in this:

![image](https://cloud.githubusercontent.com/assets/7641760/9428253/ff07b762-49ae-11e5-8bbf-295115a50a1f.png)

Just plain `.text-muted` is also pretty ugly:

![image](https://cloud.githubusercontent.com/assets/7641760/9428264/7d648f4a-49af-11e5-9e5b-57d7b25d15a8.png)

**Comment by mdo** [comment] 2016-05-12 05:45
First image is dupe of #19841. Fix coming for that in #19885.

Second one is tough—that's a utility class, so overriding it isn't an option. Perhaps I could explore using `opacity` to mute text by fading it back, but that could present other problems, too. For now going to punt on that and suggest folks drop the muted utility there.

**Closed by mdo** 2016-05-12 05:45 UTC
Labels: css, v4

**Comment by ambischof** [comment] 2018-12-07 20:53
This was punted on over 2 years ago, is there any possibility that this will be ever fixed? It would be nice.
