### ISSUE TITLE
Dropdowns example page not working.

### ISSUE THREAD

**Issue by thatbignerdguy** [twbs/bootstrap#20483] opened 2016-08-08 05:32 UTC
Sorry, I'm not sure if this is the proper place to post this, but here it is:

The [dropdowns example page](http://v4-alpha.getbootstrap.com/components/dropdowns/) isn't currently working.

Clicking any of the dropdowns yields the following error:

> Error: Syntax error, unrecognized expression: #
> jquery.min.js (line 2, col 13136)

I've tested the code outside of getbootstrap.com and it appears to be working; the issue is only on the example page.

Firefox 48.0
Kubuntu 16.04

**Comment by bardiharborow** [comment] 2016-08-08 06:10
Duplicate of #20410, which has since been resolved.

**Comment by cvrebert** [comment] 2016-08-08 20:30
@bardiharborow Thanks! ❤️

**Closed by cvrebert** 2016-08-08 20:30 UTC
