### ISSUE TITLE
Number inputs are not fully functional on Linux/Firefox

### ISSUE THREAD

**Issue by GeoSot** [twbs/bootstrap#34021] opened 2021-05-18 07:58 UTC
**Description:**
The Arrows/Spinners of Number inputs, are not clickable 
- Operating system and version: Linux Manjaro
- Browser and version  Firefox : 88.0.1
- Bootstrap version **4.6**, **5.0**
- Live examples
[Bootstrap 4.6 example](https://codepen.io/GeosSV/pen/abJmGGw)
[Bootstrap 5.0 example](https://codepen.io/GeosSV/pen/PopGedL)

**PS:** working fine on linux/Manjaro chrome, and windows 10 firefox, chrome

**Comment by alecpl** [comment] 2021-05-18 09:23
I confirm that. Looks like related to padding.

**Comment by Y0D4RK** [comment] 2021-05-18 09:35
> I confirm that. Looks like related to padding.

Can we replace .75rem padding left and right by .4rem ? .4rem looks like good for Firefox.

**Comment by alecpl** [comment] 2021-05-18 09:40
It's not as simple as that. E.g. consider `.is-invalid` class.

**Comment by alpadev** [comment] 2021-05-18 10:20
Maybe related https://github.com/twbs/bootstrap/issues/33725

**Comment by alecpl** [comment] 2021-05-18 10:25
@alpadev, thanks. So, it looks the issue is fixed in Firefox 89 according to https://bugzilla.mozilla.org/show_bug.cgi?id=1707070

**Comment by Y0D4RK** [comment] 2021-05-18 10:25
> It's not as simple as that. E.g. consider `.is-invalid` class.

So, yes I understand. I wanted to say, we can override padding in our code:

```css
.form-control{
padding: .375rem .4rem
}
```

Waiting Firefox patch.

**Closed** 2021-05-18 12:15 UTC
Labels: css, v4, v5
