### ISSUE TITLE
Second level navigations not shown on a collapsed navbar fixed to the top

### ISSUE THREAD

**Issue by danse** [twbs/bootstrap#16102] opened 2015-03-18 13:26 UTC
When a navigation bar is fixed to the top, clicking on dropdowns will not change the navigation bar height. This way, some links will become unaccessible. If the dropdowns are the last elements in the navigation bar, their content will not be accessible

##### how to reproduce

Go to the Bootstrap doc at http://getbootstrap.com/components/#navbar, which says `Currently v3.3.4` while i am writing, with a browser with a narrow viewport. Inspect the markup and add the class `navbar-fixed-top` to the navigation bar in order to make it fixed. Click on the dropdown buttons

##### browser

I see this behaviour with Chrome 41

**Comment by zacechola** [comment] 2015-03-18 21:01
Approximate duplicate of #12738?

**Comment by cvrebert** [comment] 2015-03-18 22:33
Yes. Closing as a duplicate.

**Closed by cvrebert** 2015-03-18 22:33 UTC
Labels: confirmed, css

**Comment by danse** [comment] 2015-03-19 10:01
Not a duplicate of #12738 for me, but not a bug as well, after reading that issue. The problem here is that i did not see the scroll bar, since i am using Chrome on OSX. So this is more an usability issue, i expected the navigation bar to expand vertically as it does when it is not fixed. Anyway glad to know that i can just scroll, thanks!

**Comment by zacechola** [comment] 2015-03-19 14:39
Oh in that case:

```less
.navbar-fixed-top .navbar-collapse {
  max-height: 340px;
}
```

Override that to adjust the height of the dropdowns to your content. Know that there are issues with fixed top and the height of the viewport, though...

**Comment by danse** [comment] 2015-03-19 22:07
thanks for the hint!
