### ISSUE TITLE
Uncaught ReferenceError: Tether is not defined

### ISSUE THREAD

**Issue by 08euccs014** [twbs/bootstrap#18359] opened 2015-11-27 01:56 UTC
Showing following error when using tooltip and you hover the button then it start generating error in latest release  v4.0.0-alpha version.

![screenshot from 2015-11-27 07 25 41](https://cloud.githubusercontent.com/assets/3168866/11432627/298a4242-94d8-11e5-9b3b-773e5af9f297.png)

**Comment by wolfy1339** [comment] 2015-11-27 02:04
You need to include Tether in your HTML before Bootstrap's JavaScript

**Comment by cvrebert** [comment] 2015-11-27 02:06
Duplicate of #17273. Please search more next time.

**Closed by cvrebert** 2015-11-27 02:06 UTC
