### ISSUE TITLE
Add Glyphicons & tooltip issue

### ISSUE THREAD

**Issue by msbg93** [twbs/bootstrap#17877] opened 2015-10-10 11:30 UTC
please add Glyphicons icon fonts as in the version 3.3.5 which is best to use an appropriate icon easily while it's not available in v4-alpha.  I think its necessary and i recommend to add in v4 bootstrap. and tooltip in v4 is not working, please check.

**Comment by patrickhlauke** [comment] 2015-10-10 11:36
icon fonts pose problems out of the box - see https://speakerdeck.com/ninjanails/death-to-icon-fonts

the v4 migration guide includes information on how authors can still easily add their own icon fonts if they so wish.

and tooltip problem is a dupe of #17097

**Closed by patrickhlauke** 2015-10-10 11:36 UTC

**Comment by cvrebert** [comment] 2015-10-10 22:32
Glyphicons were deliberately dropped in v4; see http://v4-alpha.getbootstrap.com/migration/#components
Lots of folks were already using other icon fonts (e.g. Font Awesome) instead of Glyphicons with Bootstrap v3 anyway. Unbundling Glyphicons lets those folks avoid duplication in their projects.

**Comment by msbg93** [comment] 2015-10-12 14:42
i know glyphicons dropped in v4. So, what's the alternate of this?

**Comment by patrickhlauke** [comment] 2015-10-12 15:17
you add them yourself... https://github.com/twbs/bootstrap/commit/8b4925f0d8f0e3046d0f9e5264c6fdf3157f4f95

**Comment by kkirsche** [comment] 2015-10-12 17:59
@msbg93 I'd recommend reading https://fortawesome.github.io/Font-Awesome/get-started/ which does a good job of providing examples for possible workflows to integrate (their) icon font with a project. While this is specific to them, the general steps to integrate with a project should be very similar unless a very unique environment is in use. Hope this helps!
