### ISSUE TITLE
Scroll down and notice how the cursor also moves past the border of the text box

### ISSUE THREAD

**Issue by ZohidSB** [twbs/bootstrap#25889] opened 2018-03-19 07:51 UTC
IOS 11

**Comment by ZohidSB** [comment] 2018-03-19 07:52
![dcf7ffa8-3144-4d6d-b2b2-8530784daaa6](https://user-images.githubusercontent.com/37531498/37583704-46a9a482-2b74-11e8-8e98-ebbe41060562.png)
![80a2ea4d-ea65-445d-be93-4381c926cab9](https://user-images.githubusercontent.com/37531498/37583705-46dc2a56-2b74-11e8-82bf-353ed60b9efe.png)

**Comment by bakedbird** [comment] 2018-03-19 09:33
@ZohidSB I am not really sure what I am seeing here. Could you provide more details?

**Comment by rafalp** [comment] 2018-03-19 09:41
Dupe of #24352 - iOS11 Browser Bug resulting in invalid computation of caret's position.

Also reported in #25844 #25777 #25496 #24835

**Closed** 2018-03-19 09:51 UTC
