### ISSUE TITLE
4 beta 1, scss @import generates a different file than the original on getbootstrap.com

### ISSUE THREAD

**Issue by johnunclesam** [twbs/bootstrap#23629] opened 2017-08-22 21:00 UTC
I'm using `node-sass` for my project.

You can try in a simple *style.scss* file with both version (alpha6 and beta):

`@import "./node_modules/bootstrap/scss/bootstrap";`

then type this:

`node-sass style.scss style.css`

and you'll have a different css for the .btn class:

**- original one on getbootstrap.com (https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.css)**

```css
.btn {
  display: inline-block;
  font-weight: normal;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
  border: 1px solid transparent;
  padding: 0.5rem 0.75rem;
  font-size: 1rem;
  line-height: 1.25;
  border-radius: 0.25rem;
  transition: all 0.15s ease-in-out;
}
```

**- generated one**

```css
.btn {
  display: inline-block;
  font-weight: normal;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  user-select: none;
  border: 1px solid transparent;
  padding: 0.5rem 0.75rem;
  font-size: 1rem;
  line-height: 1.25;
  border-radius: 0.25rem;
  transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}
```

Look at this:

```css
transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
```

Why this differences?

**With this problem "disabled" property on a button has no transition anymore** as you can see here: https://plnkr.co/edit/LSeKKSaB2Lk2JMtoFi9K?p=preview

**Comment by XhmikosR** [comment] 2017-08-22 21:10
CC @mdo

**Comment by johnunclesam** [comment] 2017-08-22 21:16
Maybe I'm wrong. Maybe I need to execute a different process...

I'm overriding variables (for example: $enable-rounded: false; -shadows: true;), this is the reason for that @import. How to do?

**Comment by wolfy1339** [comment] 2017-08-22 23:10
you don't have autoprrfixer so it won't be the same

**Comment by johnunclesam** [comment] 2017-08-22 23:17
And autoprefix affects also the transition property?

**Comment by wolfy1339** [comment] 2017-08-22 23:19
I wouldn't think so, but it does affect the final output
________________________________

**Comment by johnunclesam** [comment] 2017-08-23 09:03
Using autoprefix (with browserlist of BS4) in my sample project I got this:

```
.btn {
  display: inline-block;
  font-weight: normal;
  text-align: center;
  white-space: nowrap;
  vertical-align: middle;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  border: 1px solid transparent;
  padding: 0.5rem 0.75rem;
  font-size: 1rem;
  line-height: 1.25;
  border-radius: 0.25rem;
  transition: background-color 0.15s ease-in-out, border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}
```

**Comment by XhmikosR** [comment] 2017-08-23 09:10
The problem isn't autoprefixer. The transition property clearly differs. My guess is that this was a hickup when @mdo packaged the release and was different that the committed files.

So, just wait for @mdo's reply.

**Comment by mdo** [comment] 2017-08-23 16:27
Yeah sounds about right. I'll have to look closer at it all when we ship Beta 2. Likely a won't fix?

**Comment by XhmikosR** [comment] 2017-08-23 16:35
Yup

**Closed** 2017-08-23 17:33 UTC
Labels: css, v4

**Comment by johnunclesam** [comment] 2017-08-24 00:58
Dear @mdo, Thank you for your commitment. Perhaps it would not be better to have a cross-check at the release stage than what's being published is actually the same as what is produced with a standard import build (as in this problem I find)?. Because the public css is used by so many online services (they do not build, they use the single css main) that then we lose our heads in trying to figure out why things do not go as they should.
