### ISSUE TITLE
Documentation for v4 - modal

### ISSUE THREAD

**Issue by constagorgan** [twbs/bootstrap#21717] opened 2017-01-14 00:31 UTC
I am not sure if this is the right place to report a problem found in the documentation, but I just want to help the community so I'll dare to describe the problem right here.

In the **modal** usage examples ( [Bootstrap documentation for v4](http://v4-alpha.getbootstrap.com/components/modal) ) - in the **"Live demo" section** - you've wrongly referenced the modal's ID (you probably kept the same modal ID from the Bootstrap v3 documentation).

The example speaks for itself:

    
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
      Launch demo modal
    </button>
    
    
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
          </div>
        </div>
      </div>
    </div>

The problem is that you are setting the button's target to **"#exampleModal"** and the modal's ID is: **"#myModal"**. I think this can be confusing for beginners.

**Comment by Quy** [comment] 2017-01-14 00:34
Duplicate of #21665. Fixed and merged.

**Closed** 2017-01-14 02:55 UTC
