### ISSUE TITLE
Flex is breaking input-group-addon with date datetime-local input types

### ISSUE THREAD

**Issue by AskMP** [twbs/bootstrap#23103] opened 2017-07-16 17:13 UTC
OS: MacOS 10.12.5
Browser: Chrome 61

Using the input-group-addon form component with a date or datetime-local input type makes the browser GUI elements go vertical due to the flex-direction being set to column in _input-group.scss on line 32. Manually unchecking the option corrects the issues and reflects the expected layout arrangement of GUI elements however it may be good to see about flagging non-date types for not having column set.

**Comment by Johann-S** [comment] 2017-07-16 18:36
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by AskMP** [comment] 2017-07-16 18:47
Bootstrap version 4.0.0.alpha-6
https://jsbin.com/vayayaresa/edit?html,output

**Comment by patrickhlauke** [comment] 2017-07-16 18:49
Confirmed in Chrome 59 / Windows 10. This smells like a browser bug to me, as Chrome should really handle the way its complex form widgets lay out and behave. /cc @rbyers

**Comment by mdo** [comment] 2017-07-16 20:32
Long since fixed. Duplicate of #21651.

**Closed by mdo** 2017-07-16 20:32 UTC
Labels: browser bug, confirmed, css, v4
