### ISSUE TITLE
Documentation search redirects to v4.0 instead of v4.1

### ISSUE THREAD

**Issue by yamenarahman** [twbs/bootstrap#26444] opened 2018-05-03 08:13 UTC
I noticed that in the latest documentation whenever I search for anything the page redirects to previous version of Bootstrap, I'm managing to fix this with a PR but I couldn't find where it is, So where can I fix this in this repo?

**Comment by sts-ryan-holton** [comment] 2018-05-04 17:49
Already mentioned this :) => https://github.com/twbs/bootstrap/issues/26441

**Comment by mdo** [comment] 2018-05-10 10:45
Closing as duplicate of #26441.

**Closed by mdo** 2018-05-10 10:45 UTC
