### ISSUE TITLE
Missing value for variable --bs-body-text-align

### ISSUE THREAD

**Issue by rodrigoreis** [twbs/bootstrap#35338] opened 2021-11-08 03:18 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Variable --bs-body-text-align doesn't have value
Cannot resolve '--bs-body-text-align' custom property 

### Reduced test cases

-

### What operating system(s) are you seeing the problem on?

Windows, Linux

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

v5.1.3

**Comment by XhmikosR** [comment] 2021-11-15 10:45
@twbs/css-review it seems we don't set this anywhere?

**Comment by ffoodd** [comment] 2021-12-01 08:03
We set it up only if `$body-text-align` is set.

So either:
1. we use the same condition before using it,
2. we set a non-null value as a default and drop the condition,
3. or we add a fallback value in the `var()` function, in that case `left` (and we'd need to double check that RTLCSS handles this right).

@mdo any thought?

**Comment by mdo** [comment] 2022-02-10 20:47
@ffoodd is correct, but we already have a Sass variable check around the custom property:

https://github.com/twbs/bootstrap/blob/d3babf7d7f684daf2fb53491b3b03c3d77fdaada/scss/_root.scss#L48-L50

I'm open to additional changes, but there should be no instance of a missing value given this current setup. We assume the browser default `left` alignment, but we could make that explicit I suppose. Thoughts?

**Comment by mdo** [comment] 2022-02-23 23:27
Closing per last comment.

**Closed by mdo** 2022-02-23 23:27 UTC
Labels: css, v5

**Comment by darkpagan** [comment] 2022-05-16 13:22
Actually the issue is still there, but is not "really" a bug of sorts.. Basically within the _reboot.scss it is stated text-align: var(--bs-body-text-align).. Of course if the variable is set to "null" then this is missed from the "_root.scss" and then an minor error occurs.
 But this will happen with anything that has a "null"  within the _root.scss" but is stated as a "var()" in other files.. The workaround is to to basically state once more in the various files where the variables are being used within the root if they are "null" or not...

**Comment by TBemrose** [comment] 2022-09-20 14:50
It would be nice if this were documented somewhere (preferably near line 96 in bootstrap.css) so we don't waste time tracking down the error and then doing our due diligence in preparation of reporting the issue. Thanks.
