### ISSUE TITLE
Gulp dist/css/bootstrap.css is missing from bower.json issue

### ISSUE THREAD

**Issue by kunalkamble** [twbs/bootstrap#18045] opened 2015-10-24 09:02 UTC
`Gulp` `main-bower-files` is missing, that is why it is not injecting css.

**Comment by cvrebert** [comment] 2015-10-24 09:30
Duplicate of #16663.
See 38861984d9035333e2b366d307a5b874df8b8759.

**Closed by cvrebert** 2015-10-24 09:30 UTC
Labels: meta, v3
