### ISSUE TITLE
Form control border in input group with button addon

### ISSUE THREAD

**Issue by ysds** [twbs/bootstrap#24453] opened 2017-10-20 04:49 UTC
This is an idea to improve appearance between the form control and the button.

#### Current(v4 bata 2)

![2](https://user-images.githubusercontent.com/4065765/31805607-141d5eca-b59d-11e7-8dd5-23be782042de.png)

![1](https://user-images.githubusercontent.com/4065765/31805604-11565d0e-b59d-11e7-9ef2-27bc9d03f5d8.gif)

![3](https://user-images.githubusercontent.com/4065765/31805924-a3e00f24-b59f-11e7-9f62-f47542d11d32.gif)

Demo:
https://jsfiddle.net/rg8t9zp7/3/

#### After

![image](https://user-images.githubusercontent.com/4065765/31805645-49261878-b59d-11e7-8fcb-0db313b72c88.png)

Demo:
https://jsfiddle.net/qyet1xyq/1/

**Comment by mdo** [comment] 2017-10-20 05:22
Changing the border color isn't the path we want to take. Changing the `z-index` is the best bet for controlling the stacking here. Feels like a duplicate of #24216?

**Closed by mdo** 2017-10-20 05:22 UTC
