### ISSUE TITLE
v4: Bootstrap Modal with tooltips and popover

### ISSUE THREAD

**Issue by mroftalp** [twbs/bootstrap#22219] opened 2017-03-20 07:11 UTC
Hover to a tooltip inside a modal and or clicking to show a popover inside a modal disable it's hide function. Can check on your documentation for the live demo of the bug: http://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers once you open the modal try to hover on a tooltip or clicking the popover button.

**Comment by mdo** [comment] 2017-03-20 16:22
Dupe of #22021.

**Closed by mdo** 2017-03-20 16:22 UTC
