### ISSUE TITLE
Object fit property is needed

### ISSUE THREAD

**Issue by prakharisg** [twbs/bootstrap#36980] opened 2022-08-18 06:10 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

please introduce object fit property

### Motivation and context

i frequently use object-fit property to reduce the use of background images

**Comment by florianlacreuse** [comment] 2022-08-18 09:43
Duplicate #36140

**Comment by mdo** [comment] 2022-08-19 09:05
Duplicate of #36140.

**Closed by mdo** 2022-08-19 09:05 UTC
Labels: feature
