### ISSUE TITLE
Text alignment off in <select> form element

### ISSUE THREAD

**Issue by mcrapts** [twbs/bootstrap#23717] opened 2017-08-28 17:20 UTC
Using Bootstrap 4.0.0 beta, the text alignment in a select box seems to be off. You can't see the difference between a g and q.

**Bootstrap 4.0.0 beta**
Codepen: https://codepen.io/anon/pen/KvGQeo
![image](https://user-images.githubusercontent.com/16231555/29784813-bc7fecaa-8c25-11e7-9b31-1c339c60f81d.png)

With Bootstrap 4.0.0 alpha 6, everything looked fine.
**Bootstrap 4.0.0 alpha 6**
Codepen: https://codepen.io/anon/pen/XaxZBO
![image](https://user-images.githubusercontent.com/16231555/29784892-f73dc77c-8c25-11e7-8233-5cc6865155ff.png)

OS: Windows 10
Browser: Chrome 60

**Comment by gijsbotje** [comment] 2017-08-28 21:29
could specify browser+version and os?
i do not see mentioned behaviour

**Comment by mcrapts** [comment] 2017-08-29 07:49
Oops, forgot to add that. I've added it to the post (Chrome 10, Windows 10).

**Comment by gijsbotje** [comment] 2017-08-29 08:01
no problems on macOS 10.12.5 with chrome 60

**beta**
![schermafbeelding 2017-08-29 om 09 59 35](https://user-images.githubusercontent.com/7714133/29810571-a14011f6-8ca0-11e7-825c-7925bdba04c4.png)

only noticible difference is that the font changes
in alpha it just says `sans-serif`, in the beta is uses the system fonts
could that be whats causing it?

**Comment by mcrapts** [comment] 2017-08-29 08:11
That is the only difference I could make out as well, so that could be the issue.

**Comment by mdo** [comment] 2017-08-29 15:35
Duplicate of #23347.

**Closed by mdo** 2017-08-29 15:35 UTC
