### ISSUE TITLE
remove warning

### ISSUE THREAD

**Issue by Ctrl-Mota** [twbs/bootstrap#39049] opened 2023-08-14 16:52 UTC
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `bootstrap@5.3.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/bootstrap/scss/mixins/_grid.scss b/node_modules/bootstrap/scss/mixins/_grid.scss
index 38e2239..f5bc2f1 100644
--- a/node_modules/bootstrap/scss/mixins/_grid.scss
+++ b/node_modules/bootstrap/scss/mixins/_grid.scss
@@ -56,7 +56,7 @@
 @mixin row-cols($count) {
   > * {
     flex: 0 0 auto;
-    width: divide(100%, $count);
+    width: divide(100, $count);
   }
 }
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by wspeirs** [comment] 2023-08-15 01:49
Appears to be the same as #39028

**Comment by XhmikosR** [comment] 2023-08-15 11:49
Duplicate of #39028

**Closed by XhmikosR** 2023-08-15 11:49 UTC
