### ISSUE TITLE
Bug: form errors don't show with input group in beta2 (or beta) but do in alpha 6

### ISSUE THREAD

**Issue by yunti** [twbs/bootstrap#24839] opened 2017-11-20 22:39 UTC
For the test form which has a input group and uses `invalid-feedback` for server side validation.
See test here https://codepen.io/anon/pen/vWdzox
The form error feedback text fails to show and is missing.

Here it can be seen working with bs4 alpha 6
https://codepen.io/anon/pen/QOQZbZ

**Comment by tmorehouse** [comment] 2017-11-20 23:54
Duplicate of https://github.com/twbs/bootstrap/issues/23454

**Comment by tmorehouse** [comment] 2017-11-21 01:30
Also note that the class `invalid-feedback`, nor class 'is-invalid', did not exist in BS V4.alpha.6 (it used 'has-error`, and 'form-feedback`, etc).

**Comment by yunti** [comment] 2017-11-21 08:49
@tmorehouse Thanks yes, same as #23454 as you mentioned (sorry didn't find that when I searched). 

This issue can be closed.

**Closed** 2017-11-21 09:21 UTC
