### ISSUE TITLE
Style is break while using input which type is date and class is form-control in input-group

### ISSUE THREAD

**Issue by lzp401** [twbs/bootstrap#22017] opened 2017-02-17 05:02 UTC
Hi, 

I'm using bs4 alpha6 

Following is my code
`<div class="form-group col-lg-6">`
`               <label class="col-form-label col-sm">Search Date</label>`
`               <div class="input-group col-sm px-0">`
`                  <input class="form-control py-0" type="date" formControlName="startDate">`
`                  <span class="input-group-addon">To</span>`
`                  <input class="form-control py-0" type="date" formControlName="endDate">`
`              </div>`
`            </div>`

Here is the screenshot
![screen shot 2017-02-17 at 12 57 26 pm](https://cloud.githubusercontent.com/assets/6505627/23052995/c0c819e2-f510-11e6-9645-24099a723805.png)

The input element is totally broken and I can't input anything in it. 

To work round with this issue, I removed input-group class and added d-flex to let my field stay horizontally.

**Comment by bardiharborow** [comment] 2017-02-21 07:25
Closing as a duplicate of #21651.

**Closed by bardiharborow** 2017-02-21 07:25 UTC
Labels: css, v4
