### ISSUE TITLE
Invalid value for $container-max-widths

### ISSUE THREAD

**Issue by tillkruss** [twbs/bootstrap#22439] opened 2017-04-13 19:04 UTC
Using this grid container:

```sass
$container-max-widths: (
    sm: 100%,
    md: 100%,
    lg: 100%,
    xl: 1140px
);
```

Works, but leads to these warnings:

```
WARNING: Invalid value for $container-max-widths: This map must be in ascending order, but key 'md' has value 100% which isn't greater than 100%, the value of the previous key 'sm' !
Backtrace:
	node_modules/bootstrap/scss/_variables.scss:53, in mixin `-assert-ascending`
	node_modules/bootstrap/scss/_variables.scss:226

WARNING: Invalid value for $container-max-widths: This map must be in ascending order, but key 'lg' has value 100% which isn't greater than 100%, the value of the previous key 'md' !
Backtrace:
	node_modules/bootstrap/scss/_variables.scss:53, in mixin `-assert-ascending`
	node_modules/bootstrap/scss/_variables.scss:226

WARNING: Potentially invalid value for $container-max-widths: This map must be in ascending order, but key 'xl' has value 1140px whose unit makes it incomparable to 100%, the value of the previous key 'lg' !
Backtrace:
	node_modules/bootstrap/scss/_variables.scss:51, in mixin `-assert-ascending`
	node_modules/bootstrap/scss/_variables.scss:226
```

**Comment by oktalk** [comment] 2017-04-14 13:59
How can I duplicate your issue in order to see what's going on?

**Comment by tillkruss** [comment] 2017-04-14 15:29
@oktalk: I just defined the exact `$container-max-widths` from above before loading BS's Sass files and when compiling those errors show up.

**Comment by mattgi** [comment] 2017-04-15 05:14
can repro here. we got the same issue

**Comment by mdo** [comment] 2017-04-16 20:45
Closing as a dupe of #19113. You need to use pixels for these for now.

**Closed by mdo** 2017-04-16 20:45 UTC
Labels: css, v4

**Comment by tillkruss** [comment] 2017-04-16 20:51
@mdo: There is no way around that?
