### ISSUE TITLE
Document search is not working on iPhone 13 - iOS chrome

### ISSUE THREAD

**Issue by sathyavikram** [twbs/bootstrap#36830] opened 2022-07-24 12:56 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When I search bootstrap documents (V5.2) from iPhone chrome, search is not working. 
Search popup opens however I am not able to type anything in search box.

Steps to re-produce:
1. Go to https://getbootstrap.com/docs/5.2/getting-started/introduction/
2. Click on Three dots icon ("...") in the header to open slidein
3. Tap on "Search" box
4. Search page (I think its popup) opens however I am not able to type anything in search box (keyboard does not pop up on mobile to type)

Doc version - (V5.2)
Reproduced URL - https://getbootstrap.com/docs/5.2/getting-started/introduction/
![IMG_1413](https://user-images.githubusercontent.com/2120744/180647963-bde67318-4a8c-49bb-ab73-2226565ae73d.PNG)

https://user-images.githubusercontent.com/2120744/180647967-815bf165-2948-4a71-bb26-a35ed98b6f1a.mp4

### Reduced test cases

![IMG_1413](https://user-images.githubusercontent.com/2120744/180647999-1bf4367a-1932-4fb7-a4a2-65190c8f8650.PNG)

### What operating system(s) are you seeing the problem on?

iOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2

**Comment by sathyavikram** [comment] 2022-07-24 12:58
Issue is re-produced in iOS chrome and iOS Safari

**Comment by julien-deramond** [comment] 2022-07-24 14:00
Thanks for reporting this issue @sathyavikram. However I'm closing it because it is a duplicate of #36822.

**Closed by julien-deramond** 2022-07-24 14:00 UTC

**Comment by sathyavikram** [comment] 2022-07-24 14:03
Awesome. Thanks
