### ISSUE TITLE
Navbar .sticky-top doesn't work

### ISSUE THREAD

**Issue by hugmanrique** [twbs/bootstrap#21919] opened 2017-02-05 19:23 UTC
According to the [navbar component guide](https://v4-alpha.getbootstrap.com/components/navbar/), in order to make a navbar sticky, you have to add the `.sticky-top` class.

I'm using Chrome 55.0.2883.87 and Bootstrap 4 beta 6 and the position rules added by bootstrap are invalid according to Chrome, therefor, nothing happens:

![Chrome image](http://i.imgur.com/MrtzXce.png)

To replicate the issue, create a navbar as so:
```html
<nav class="navbar sticky-top navbar-light bg-faded">
  <a class="navbar-brand" href="#">Sticky top</a>
</nav>
```

**Comment by Jas-n** [comment] 2017-02-06 09:20
Position sticky isn't available for Chrome 55 without enabling flags. It is available without flags in 56.

http://caniuse.com/#search=sticky

**Comment by hugmanrique** [comment] 2017-02-06 11:33
Wouldn't it be better to use `position: fixed;` and `top: 0;` for backwards compatibility?

**Comment by dkfiresky** [comment] 2017-02-06 11:50
@hugmanrique `position: sticky;` allows to ommit javascript implementation part which is required to be used with `position: fixed;` and `top: 0;`.

With the `position: fixed;` you have to automatically calculate the scroll offset and disable `position: fixed;` when the scroll offset matches with element's top offset.

**Comment by chris13524** [comment] 2017-02-14 14:49
Same issue on Firefox 50.1.0: https://jsfiddle.net/3qoe0wd0/44/

**Comment by chris13524** [comment] 2017-02-14 14:51
The `sticky-top` class doesn't work either.

**Comment by Steve62** [comment] 2017-03-14 17:20
Works okay in Chrome 56. I face this issue in Safari however.

OSX 10.12.3 - Safari 10.0.3 (12602.4.8)

**Comment by mdo** [comment] 2017-03-19 22:25
Closing as this is a browser support issue, which is indicated in the docs. Latest Safari, Chrome, and Firefox all support `position: sticky`, but latest IE, Edge, and Android don't right now.

**Closed by mdo** 2017-03-19 22:25 UTC
Labels: css, v4

**Comment by rcfrias** [comment] 2017-08-28 20:04
I am having this on all mobile browsers. It does work on desktop, but trying chrome, safari and firefox, the header moves away as if its not sticky.  Any idea why this might be happening?

**Comment by tehlivi** [comment] 2017-10-26 19:49
**My setup:**
Bootstrap@4.0.0-beta.2
macOS Sierra - Version 10.12.6 
Google Chrome - Version 62.0.3202.62 (Official Build) (64-bit)
Safari - Version 11.0 (12604.1.38.1.7)
Safari Technology Preview - Release 42 (Safari 11.1, WebKit 12605.1.10)

---

http://caniuse.com/#feat=css-sticky
Can I Use said it's supported in Safari with webkit

    .sticky-top {
        position: -webkit-sticky;
        position: sticky;
        top: 0;
        z-index: 1020;
    }

I think this should definitely be added to Bootstrap, with other vendor prefixes if they apply.

---

https://css-tricks.com/position-sticky-2/
>WebKit dropped in 2013, Firefox in 2014, and now Blink in (probably) 2016.
> MDN explains it well:
>> Sticky positioning is a hybrid of relative and fixed positioning. The element is treated as relative positioned until it crosses a specified threshold, at which point it is treated as fixed positioned.

In the codepen example shown on that page, sticky works on all browsers listed above.

---

I did some tests and found:

1. `.sticky-top` will not work if it is inside `.container` or `.container-fluid`
2. `.sticky-top` must be a container surrounding the element you want sticky


The following example worked for me:


    <div class="sticky-top">
        <nav class="navbar navbar-light bg-light p-0">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-toggler" aria-controls="navbar-toggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <a class="navbar-brand mr-auto mx-2" href="{{ site.url }}">Sticky</a>

            <div class="collapse navbar-collapse" id="navbar-toggler">
                <div class="container-fluid">
                    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li class="nav-item active">
                            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Link</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

**Comment by Alfier** [comment] 2017-11-03 11:01
.sticky-top worked like a charm even inside a <div> while I was using pingendo with bootstrap 4. When I moved to Brackets suddenly stop working unless it was on the outermost part of the <body> structure (I mean directly below the body tag. Even outside a <div> but below other code inside body it won't work and even go wild outside of screen).
I can't really solve this issue without messing the structure of the page...

**Comment by shankar722** [comment] 2017-11-06 07:22
@Alfier thank you so much, worked. Actually it doesnt work even inside header tag.

**Comment by zarqman** [comment] 2017-11-10 18:04
A quick hint to anyone who still can't get `position: sticky` working. Sometimes it's caused by the parent element having certain `overflow` or `height` settings. This explains it further: http://blog.cloud66.com/position-sticky-problem/.

Off-canvas nav frequently adds an `overflow` attribute, so that's one place to look if you can't readily find the source of the issue.

**Comment by jedbonheur** [comment] 2017-12-14 02:47
It works perfect thank you @hugmanrique @zarqman  

Few stuff i corrected
- make sure **<nav>..........</nav>**tag  is direct child ofbody
-make sure the direct parent ; (body) has no overflow property on it 

The rest is normal
if you are using bootsrap 4 :
-add sticky-top

you can use javascript tooo will work !!

**Comment by emran-shaikh** [comment] 2018-02-09 14:38
Don`t Use "position:sticky" replace it with "position:fixed" it will safe your life.

**Comment by Nekiono** [comment] 2018-03-24 10:32
I encountered this and actually had an issue with 
`body, html {
    height: 100%;
}`.
taking that out and only putting it in the actual needed location fixed it.
Reason being is that the sticky navbar is above the body, hence not visible.

hope this helps!

**Comment by ghostvar** [comment] 2018-03-31 11:12
I found position: sticky was supported in the most popular browser
but if it's still not work, you can enable through the "experimental Web Platform features" flag
and about:config preference layout.css.sticky.enabled to true in firefox

source: https://caniuse.com/#feat=css-sticky

**Comment by thornyweb** [comment] 2018-04-26 14:09
I had to add a height 100% to a ancestor div inside my container to get a div.sticky-top to work as expected

**Comment by waleedalikhan** [comment] 2019-07-07 22:23
@tehlivi Thank you Soo much I was having trouble with the .sticky-top class of bootstrap but you solved my problem by telling me that try putting .sticky-top to the parent element and it worked! Thanks alot!

**Comment by codehavoc** [comment] 2019-08-21 08:31
using sticky top in main element really did work
thanks.............

**Comment by kalevskis** [comment] 2020-01-02 10:50
I had same problem by using the navbar inside header section. Solution that fixed the problem was to set header{display:unset;}

**Comment by Marcelo-Diament** [comment] 2020-04-18 23:16
I realized .sticky-top class has no effect if the element that receives this class is immediately inside a .row element. But if you have another element (like a div) between them, it works properly.

**Comment by EhsaNK77** [comment] 2021-08-20 22:08
This problem also exists in version 5
To solve this problem, hold 'sticky-top' and put it out of the header.

**Comment by LBY89** [comment] 2022-04-20 17:52
I fixed it by remove <div></div> tags before <AppBar>, so return (<AppBar><AppBar/>), do not wrap with <div></div>.
