### ISSUE TITLE
Tooltips not working in latest Firefox

### ISSUE THREAD

**Issue by mitchelldemler** [twbs/bootstrap#17907] opened 2015-10-13 02:52 UTC
Using latest version of the dev edition of Firefox.

Content of tooltip doesn't render. Only the triangle displays, this is a screenshot of the v4 docs:

![capture](https://cloud.githubusercontent.com/assets/995053/10444383/50bdae8c-71c2-11e5-9732-505498bf3cd5.JPG)

**Comment by cvrebert** [comment] 2015-10-13 06:21
Duplicate of #17097. Please search more in the future.

**Closed by cvrebert** 2015-10-13 06:21 UTC
