### ISSUE TITLE
More than one word in navbar search button will cause the second word to wrap.

### ISSUE THREAD

**Issue by bbarrick** [twbs/bootstrap#33184] opened 2021-02-22 22:51 UTC
Windows 10
Edge - Version 88.0.705.74 (Official build) (64-bit)
Chrome Version 88.0.4324.190 (Official Build) (64-bit)

This is in testing in a new project. The navbar is the only HTML on the page. Wasn't sure if it was a bug or expected behavior but I'm testing with Bootstrap 5 locally, codepen is using 4.5 and I see the same behavior. 

https://codepen.io/binarycode/pen/PobJvOR

**Comment by bbarrick** [comment] 2021-02-22 22:54
It doesn't appear to have the same issue when using the navbar example from 4.6.1. In the above example where Codepen uses 4.5 I was using the bootstrap 5 navbar sample code.

**Comment by rexarvind** [comment] 2021-02-23 04:10
![Screenshot_2021-02-23-09-38-32-977](https://user-images.githubusercontent.com/63487995/108801138-ecac1700-75ba-11eb-8216-caf3299ebfe4.jpeg)

use non-breaking space, so it'll be a single word.

```
<button class="btn btn-outline-success" type="submit">Log&nbsp;In</button>
```

**Comment by bbarrick** [comment] 2021-02-23 04:13
@rexarvind Thanks! I didn't think to try that.

**Comment by mdo** [comment] 2021-02-23 06:09
Duplicate of https://github.com/twbs/bootstrap/issues/32383 and should've been addressed in Beta 2.

**Closed by mdo** 2021-02-23 06:09 UTC
