### ISSUE TITLE
`hidden` attribute can't be set on button class="btn"

### ISSUE THREAD

**Issue by dandv** [twbs/bootstrap#16464] opened 2015-05-13 11:27 UTC
Fiddle: http://jsbin.com/vivuxumana/3/edit

```html
<button class="btn" type="button" onclick="this.hidden=true">
  Hiding me doesn't work
</button>
<button type="button" onclick="this.hidden=true">
  Hiding me works
</button>
```

**Comment by patrickhlauke** [comment] 2015-05-13 11:57
culprit seems to be the explicit `display: inline-block` for `.btn`

**Comment by cvrebert** [comment] 2015-05-13 17:46
Approximate duplicate of #15274.

**Closed by cvrebert** 2015-05-13 17:46 UTC
Labels: confirmed, css
