### ISSUE TITLE
Bootstrap 4 Error: Bootstrap tooltips require Tether (http://github.hubspot.com/tether/)

### ISSUE THREAD

**Issue by tandon-aman** [twbs/bootstrap#19669] opened 2016-04-03 13:23 UTC
Hi,

I tried the Hello world code given in getting started section of bootstrap-4 and checked the error console and found this error. Please check.

Browser: Chrome 49.0.2623.110 (64-bit)  & Safari 9.0.3

<img width="1230" alt="screen shot 2016-04-03 at 6 52 49 pm" src="https://cloud.githubusercontent.com/assets/15096154/14232604/5221d986-f9cd-11e5-85ea-b28dd7f440c6.png">

**Comment by cvrebert** [comment] 2016-04-03 19:11
Duplicate of #18664.

**Closed by cvrebert** 2016-04-03 19:11 UTC
Labels: docs, v4

**Comment by dt-ideaenvy** [comment] 2016-12-20 07:41
Hi,
Am to faced the same issues in Bootstrap new version 4. Actually bootstrap 4 js asking tether.js to link over in bootstrap 4 js that is the problem.
Better you can use older version  **Bootstrap v3.3.7**

**Comment by cvrebert** [comment] 2016-12-20 08:34
@dt-ideaenvy Please refer to #21250 or #17201.
