### ISSUE TITLE
input-group custom-file-input browse button border-radius

### ISSUE THREAD

**Issue by zuul** [twbs/bootstrap#25513] opened 2018-01-30 15:18 UTC
The following markup, as viewed on the [documentation](https://getbootstrap.com/docs/4.0/components/input-group/#custom-file-input), keeps a border-radius on the "browse" button when we have a second button (Bootstrap 4.0.0):

```html
<div class="input-group mb-3">
  <div class="custom-file">
    <input type="file" class="custom-file-input" id="inputGroupFile02">
    <label class="custom-file-label" for="inputGroupFile02">Choose file</label>
  </div>
  <div class="input-group-append">
    <span class="input-group-text" id="">Upload</span>
  </div>
</div>
```
Sample at [JSFiddle](https://jsfiddle.net/zuul/4cydyu0d/)

**Screenshot:**
![selection_900](https://user-images.githubusercontent.com/1417381/35573886-3a9a2ec4-05d0-11e8-8624-de0c27b11851.png)

**Seen on:**
- Linux Mint 17.3 Cinnamon (64-bit)
- Firefox Quantum 57.0.4 (64-bit)
- Google Chrome 63.0.3239.132 (Official Build) (64-bit)
- Opera 50.0.2762.58

**Comment by mdo** [comment] 2018-01-31 16:38
This will be fixed in #25356.

**Closed** 2018-02-11 23:09 UTC
Labels: css, has-pr, v4

**Comment by Jayant3507** [comment] 2018-08-01 10:15
- [ ] 

1.

**Comment by Jayant3507** [comment] 2018-08-01 10:15
Duplicate of #27002
