### ISSUE TITLE
Uncaught TypeError: document.body is null

### ISSUE THREAD

**Issue by slavik117** [twbs/bootstrap#31537] opened 2020-08-25 13:45 UTC
Hello.

I use jQuery and Bootstrap.
    "bootstrap": "^5.0.0-alpha1",
    "jquery": "^3.5.1"

On page loading I get the error in browser's log:
Uncaught TypeError: document.body is null
Function - getjQuery
https://github.com/twbs/bootstrap/blob/730a0201401d22dbd1e6543dcc331a474c013cc8/js/src/util/index.js#L176

It was called before 'body' was loaded.

Below is a test page to help to recreate this error:
```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous"></script>

  </head>

  <body>
    <p>Hello</p>
  </body>
</html>
```

Thanks.

**Comment by Deckluhm** [comment] 2020-08-25 15:09
You need to import Bootstrap at the end of the `<body>` tag as shown here: https://getbootstrap.com/docs/4.5/getting-started/introduction/#starter-template

**Comment by slavik117** [comment] 2020-08-26 16:45
Yes. It works.
But, why not wait for the page to load?
```
document.addEventListener("DOMContentLoaded", function(event) { 
  //init bootstrap ...
});
```

**Comment by Hiws** [comment] 2020-08-27 08:46
Possible duplicate of: https://github.com/twbs/bootstrap/issues/31202

**Comment by XhmikosR** [comment] 2020-09-05 09:55
Duplicate of #31202

**Closed by XhmikosR** 2020-09-05 09:55 UTC
Labels: duplicate
