### ISSUE TITLE
Navigating from dropdown tab doesn't remove active state

### ISSUE THREAD

**Issue by nicolas-lindberg** [twbs/bootstrap#19647] opened 2016-03-31 10:06 UTC
When using the tab JavaScript plugin, if you select a nav item in a dropdown and then navigate to a new tab, the active state of nav items inside of the dropdown will still have the `active` class even though it's no longer selected.

You can see this behavior here:
http://v4-alpha.getbootstrap.com/components/navs/#javascript-behavior

<img width="468" alt="nav-tabs-bug" src="https://cloud.githubusercontent.com/assets/2874372/14172581/00240942-f739-11e5-84e8-b360d483d9b0.png">

**Comment by willthemoor** [comment] 2016-04-05 17:13
Note that it's not just a visual bug. It also means you can't select those items from the dropdowns a second time because of the `if(active){return}` at the top of the [`show()` method](https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tab.js#L82).

**Comment by cvrebert** [comment] 2016-08-15 22:11
Duplicate of #17371.

**Closed by cvrebert** 2016-08-15 22:11 UTC
Labels: js, v4
