### ISSUE TITLE
.navbar-collapse is not scrollable only on iOS (menu is fixed top)

### ISSUE THREAD

**Issue by gabrielcht** [twbs/bootstrap#29004] opened 2019-07-09 14:47 UTC
When I want to scroll over the navbar, is the underneath content which scrolls not the navbar-collapse content. I've tried using z-index, but nothing. I also have declared fixed heights but nothing. In Chrome for Android works well.

[issue.zip](https://github.com/twbs/bootstrap/files/3373507/issue.zip)

@media (max-width: 991px) and (max-resolution: 4dppx){
    #menuPrincipal, #navegacionPrincipal.show, .navbar-nav{
        z-index: 100;
    }   
}

@media (max-width: 991px) and (max-resolution: 4dppx){
    #navegacionPrincipal.show{
        z-index: 100;
        display: flex;
        flex-flow: column wrap;
        align-items: stretch;
        overflow-y: scroll;
        -webkit-overflow-scrolling: touch;
    }
}

@media (max-height:850px) and (max-width: 800px) and (max-resolution: 4dppx) and (orientation: portrait) {
  #navegacionPrincipal.show {
    height: 65vh;
  }
}

@media (max-height:850px) and (max-width: 800px) and (max-resolution: 4dppx) and (orientation: portrait) {
  .dropdown-menu.show a {
    white-space: pre-wrap;
  }
}

/*---------This is for iPhone------

*/
@media (max-width: 991px) and (max-resolution: 4dppx){
  #navegacionPrincipal.show .navbar-nav {
    overflow-y: scroll;
    -webkit-overflow-scrolling: touch;
    height: 65vh !important;
    max-height: 65vh!important;
  }
}

**Comment by mdo** [comment] 2019-07-10 16:04
Duplicate of #23374.

**Closed by mdo** 2019-07-10 16:04 UTC
