### ISSUE TITLE
Blurry font in modal window

### ISSUE THREAD

**Issue by Grumvol** [twbs/bootstrap#35012] opened 2021-09-18 13:04 UTC
Hi. In chromium-based browsers (e.g. google chrome) the text in the modal is blurry if the body has vertical scrolling. If the body does not have a scroll, then the text is displayed normally. Is there any way to solve this problem? It doesn't depend on the font. Unpleasant to the eyes.
- Operating system Windows 10
- Browser Chrome 93

![QIP Shot - Screen 1045](https://user-images.githubusercontent.com/20611667/133889643-714560d9-7900-4ea5-9fc0-6d42d97a57cb.png)

**Comment by shimisnow** [comment] 2021-11-08 12:51
This still occurs in Chrome 93+?

I was able to reproduce in Edge 95.0.1020.44 but no in Chrome 95.0.4638.69

**Comment by Grumvol** [comment] 2021-11-08 13:20
Chrome 95.0.4638.69. Bootstrap 5.1.3
Now the text is blurred regardless of whether there is a vertical scroll.
To remove the blur, I had to remove the border radius from .modal-content.

![QIP Shot - Screen 1178](https://user-images.githubusercontent.com/20611667/140749091-59a45b85-f0b7-4fbd-95d9-e3aac740c650.png)
![QIP Shot - Screen 1179](https://user-images.githubusercontent.com/20611667/140749115-23683658-4c79-4129-a6d1-7bbd7335490f.png)

**Comment by mdo** [comment] 2022-04-07 20:46
I can't reproduce this unfortunately in our docs, so closing as a won't/can't fix.

**Closed by mdo** 2022-04-07 20:46 UTC
