### ISSUE TITLE
Bootstrap 4 tooltips/popovers not to show in modal

### ISSUE THREAD

**Issue by neilhem** [twbs/bootstrap#18000] opened 2015-10-21 03:20 UTC
I have tooltips/popovers in content area & in modals what is the best way not to show tooltips/popovers in modal from content area? But tooltips/popovers relate to modal should stay visible.

**Comment by craft37** [comment] 2015-10-21 16:06
This default-example too tips don't show at all for me somehow.

**Comment by cvrebert** [comment] 2015-10-21 17:34
I am unable to reproduce. The example on http://v4-alpha.getbootstrap.com/components/modal/ works fine for me in OS X Chrome.
Please note that there's a Firefox-related tooltip/popover bug (#17097) that's been fixed in `v4-dev`; it'll get pushed to the hosted docs when the next alpha version gets released.

**Comment by twbs-closer** [comment] 2015-11-05 08:00
Hey there!

We're automatically closing this issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. We therefore assume that the user has lost interest or resolved the problem on their own. Closed issues that remain inactive for a long period may get automatically locked.

Don't worry though; if this is in error, let us know with a comment and we'll be happy to reopen the issue.

Thanks!

(*Please note that this is an [automated](https://github.com/twbs/no-carrier) comment.*)

**Closed by twbs-closer** 2015-11-05 08:00 UTC
Labels: awaiting reply, js, v4
