### ISSUE TITLE
making custom radio buttons to RTL results to a position problem

### ISSUE THREAD

**Issue by miranrasuli** [twbs/bootstrap#20293] opened 2016-07-13 14:03 UTC
Operating system: Ubuntu 16.04
Browser: Chrome 51

basically there is no problem with [custom radio buttons](http://v4-alpha.getbootstrap.com/components/forms/#radios) but when i add `dir="rtl"` to HTML tag and click on radio buttons, the position's width will be 1366px! So when I uncheck the position of `.c-input>input` using chrome dev-tools, the problem will be fixed.

I tried using radio buttons on Mozila Firefox but I didn't saw such a problem in firefox.

Here is a jsbin for radio buttons: http://jsbin.com/loqutu/edit?html,output

**Comment by cvrebert** [comment] 2016-07-13 15:21
We don't currently support RTL; it is on our backlog of features to add after v4 has a stable release.
Approximate duplicate of #19555.
But if you have a suggestion for a relatively simple fix, we'd gladly consider such a pull request.

**Closed by cvrebert** 2016-07-13 15:21 UTC
Labels: css, v4

**Comment by parsmizban** [comment] 2017-03-18 15:00
Hi,
You can use this patch for full RTL compatibility for both Bootstrap 3.3.7 and 4.0.0-alpha.6
https://github.com/parsmizban/RTL-Bootstrap
If you have any pre designed theme, You can use this path to make your template RTL very easy
Good luck
