### ISSUE TITLE
Navbar style nitpicking

### ISSUE THREAD

**Issue by spikeon** [twbs/bootstrap#20811] opened 2016-09-29 02:45 UTC
So, I came across an issue with how the collapsable nav works in the documentation and wanted to tell you how I changed it to work the way I wanted it to work.

1: I put assigned pull-left to the collapse button
2: I moved the navbar-brand outside the collapse, before it
3: I added: `@media (max-width: 991px) { .navbar-toggleable-xs{ clear:both; }}`

This shows the brand while the menu is closed and  then displays the items under it when it's open.  Without the clear:both; the first navigation item was appearing to the right of the brand.

I hope this helps you guys, I'm loving the alpha so far, keep up the great work!

**Comment by mdo** [comment] 2016-10-10 01:57
I think this is a dupe of #20749.

**Closed by mdo** 2016-10-10 01:57 UTC
Labels: css, v4
