### ISSUE TITLE
.row isn't 100% wide when used in a list-group in alpha-6

### ISSUE THREAD

**Issue by BrokenCrust** [twbs/bootstrap#21610] opened 2017-01-08 12:00 UTC
With alpha6 the formatting of columns inside a list group doesn't work correctly (or at least as it did in alpha-5).

I've included an minimal example below together with a row on it's own.  You can see that the row does not appear to use 100% of the width of the list-group.

I had used this successfully before (with alpha-5) inside cards to have nicely formatted rows and columns.

[JS Bin](https://jsbin.com/zuxiloquxo)

```
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous"><title>JS Bin</title>
</head>
<body>
  <div class="container-fluid">
    <ul class="list-group">
      <li class="list-group-item">
	    <div class="row">
          <div class="col-sm-6">This is column one</div>
          <div class="col-sm-4">This is column two</div>
          <div class="col-sm-1">This is column three</div>
          <div class="col-sm-1">This is column four</div>
        </div>
      </li> 
    </ul>
	<div class="row">
      <div class="col-sm-6">This is column one</div>
      <div class="col-sm-4">This is column two</div>
      <div class="col-sm-1">This is column three</div>
      <div class="col-sm-1">This is column four</div>
    </div>
  </div>
</body>
</html>
```

**Comment by Jas-n** [comment] 2017-01-08 20:59
Seems to be another issue stemming from flexbox.
Try overriding using:

.list-group,
.list-group-item{
	display:block;
}

**Comment by BrokenCrust** [comment] 2017-01-08 22:27
Thanks, that does the job.

**Comment by aRestless** [comment] 2017-01-23 13:49
A very similar thing happens to `.container > .row` in navbars, might be related.

**Comment by mdo** [comment] 2017-03-18 23:26
Duplicate of #21584. We'll be reverting to `display: block` soon for `.list-group-item`s.

**Closed by mdo** 2017-03-18 23:26 UTC
Labels: css, v4
