### ISSUE TITLE
[v4] Can navbar add justified menu

### ISSUE THREAD

**Issue by 76422937** [twbs/bootstrap#17761] opened 2015-10-02 15:01 UTC
![qq 20151002225358](https://cloud.githubusercontent.com/assets/3542138/10249620/e8891570-6958-11e5-8bc6-3cc01214ab94.png)
Like the Framework7's toolbar

**Comment by cvrebert** [comment] 2015-10-02 19:21
Duplicate of #17026 or #17631.

**Closed by cvrebert** 2015-10-02 19:21 UTC
Labels: css, feature, v4
