### ISSUE TITLE
Dropdown caret icon vertical alignment is not perfect

### ISSUE THREAD

**Issue by Nudasoft** [twbs/bootstrap#26827] opened 2018-07-09 07:46 UTC
BT version: bootstrap-4.1.1-dist
OS: Windows 10
Browser: Chrome 67.0.3396.99

How its currently display: [https://prnt.sc/k45ham](https://prnt.sc/k45ham)

How its should be: [https://prnt.sc/k45i4o](https://prnt.sc/k45i4o)

Big thanks for BT dev team :)

**Comment by Johann-S** [comment] 2018-07-09 08:01
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by Nudasoft** [comment] 2018-07-09 08:19
Bootstrap documentation can use as a demo in this case. 
[https://getbootstrap.com/docs/4.1/components/dropdowns/](https://getbootstrap.com/docs/4.1/components/dropdowns/)

**Comment by XhmikosR** [comment] 2018-07-09 12:36
This is probably the intended behavior, CC @mdo

**Comment by mdo** [comment] 2018-07-10 00:55
Duplicate of #26602.

**Closed by mdo** 2018-07-10 00:55 UTC
Labels: css, v4
