### ISSUE TITLE
v5 Popover placement jumping in accordion button

### ISSUE THREAD

**Issue by XJ346WU04** [twbs/bootstrap#32535] opened 2020-12-18 22:06 UTC
_This is my first time attempting to post an issue on github.  I attempted to do a search to see if this issue has already been identified - please forgive me if I missed it._

**Issue:** I use popovers within accordion buttons to communicate additional information to the user before they expand the collapsed accordion div.  In v4, the popovers worked great inside accordion buttons.  However, in v5, the popovers usually show up upon first hovering over the associated element, but then they either disappear quickly, disappear altogether and do not return, or jump to the top left of the screen.

**Codepen:** I have created a codepen that ideally will illustrate the problem: https://codepen.io/kj4d54xdhb/pen/ExgXEay

_(To reproduce problem using codepen, load the codepen and then hover repeatedly over the blue 'button' to see the popover.  You should see the popover try to render.  It may successfully render a few times.. but quickly it will start disappearing or jump to the top left and no longer disappear)_

**Bug encountered on:**
OS: Windows 10
Browser: Chrome 87

I am not sure if popovers are supposed to be put inside accordion buttons - I originally thought that the button functionality might conflict with the popover element, but it worked great in v4 so I am hoping it is related to a bug that can be corrected.

Please let me know if I can provide any additional information.  Thanks.

**Comment by XJ346WU04** [comment] 2020-12-18 22:24
I found this issue that seems to be similar and may have the same cause: https://github.com/twbs/bootstrap/issues/32372

**Comment by XhmikosR** [comment] 2020-12-19 06:24
Seems like a duplicate of #32372

**Closed by XhmikosR** 2020-12-19 06:24 UTC
Labels: duplicate
