### ISSUE TITLE
btn-outline-light:hover - Wrong color

### ISSUE THREAD

**Issue by eskirex** [twbs/bootstrap#23443] opened 2017-08-14 22:05 UTC
.btn-outline-light:hover {
    color: #fff;
    background-color: #f8f9fa;
    border-color: #f8f9fa;
}
http://prntscr.com/g8i8c1

**Comment by mdo** [comment] 2017-08-15 03:30
Duplicate of #23351.

**Closed by mdo** 2017-08-15 03:30 UTC
Labels: css, v4
