### ISSUE TITLE
Card deck margin is false on multiline card decks

### ISSUE THREAD

**Issue by Hannsen94** [twbs/bootstrap#22663] opened 2017-05-19 19:00 UTC
If you going to display content via card decks, there is an issue if you for example use 3 cards in a deck. If you are going to make the viewport small, the cards will resize, but on the left side in the new line it will have a false margin. I think this is related to the fact, that only the last item has no margin to the right side and all other items have margin to left and right also if they are the first items displayed in a new "line".

Example for resizing and viewing this issue:
https://www.codeply.com/go/7e5zO42ePR

**Comment by mdo** [comment] 2017-05-25 04:32
Dupe of #21976

**Closed by mdo** 2017-05-25 04:32 UTC
Labels: css, v4
