### ISSUE TITLE
iPad - Navbar dropdown links do not work

### ISSUE THREAD

**Issue by GrantBartlett** [twbs/bootstrap#15647] opened 2015-01-23 10:02 UTC
Hi,

I'm using the stock bootstrap navbar component. I add a link to "Dropdown" (called "Website test") - its just a simple link to google.com.

Testing on browsers is fine, though come to the iPad and will not actually open the link?

See fiddle and test on an iPad: http://jsfiddle.net/pjwkstnw/2/embedded/result/
 
![screen shot 2015-01-23 at 10 01 54](https://cloud.githubusercontent.com/assets/6104940/5872748/e2aaf2f6-a2e6-11e4-8e21-ac726a9beb54.png)

**Comment by twbs-lmvtfy** [comment] 2015-01-23 10:02
Hi @GrantBartlett!

You appear to have posted a live example (http://s.bootply.com/render/x2XbkQ0UQk), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 9, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.3.1
* line 96, column 9: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.2 ; saw what appears to be usage of Bootstrap 3.3.1

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by GrantBartlett** [comment] 2015-01-23 10:12
Updated fiddle to 3.3.2 http://jsfiddle.net/pjwkstnw/2/embedded/result/

**Comment by Nikita240** [comment] 2015-01-23 13:24
I think this may be a problem with jsFiddle. Testing on Ubuntu-Chrome I get `Refused to display 'https://www.yahoo.com/' in a frame because it set 'X-Frame-Options' to 'DENY'.` in the console. 

This is because jsFiddle loads the code in an iframe, and the website you are trying to reach has the `X-Frame-Options` set to deny, which tells the browser to refuse to display it in an iframe.

**Comment by Nikita240** [comment] 2015-01-23 13:29
Here, I changed it to a site which doesn't have the X-Frame header set, and it works for me in Chrome. Try it on iPad.

 http://jsfiddle.net/pjwkstnw/4/embedded/result/

**Comment by kkirsche** [comment] 2015-01-29 21:41
@Nikita240 your fiddle works fine on my iPad running iOS 8.1.2

**Comment by mdo** [comment] 2015-01-30 00:29
Closing since I, and others, can't reproduce.

**Closed by mdo** 2015-01-30 00:29 UTC
Labels: js
