### ISSUE TITLE
Make size Display Headings dependent on viewport sizes

### ISSUE THREAD

**Issue by elpescador-nl** [twbs/bootstrap#24685] opened 2017-11-05 22:46 UTC
Feature proposal:
Currently you can enlarge the size of a heading using the `display-1`-like classes. Very useful for standing out a heading!

The large size does not fit well on smaller viewports, so my suggestion is to make it viewport dependent. E.g. `display-sm-2` to apply this display-setting to the sm-breakpoint and above.

This way you could control the Heading size using something like `<h1 class="display-4 display-sm-2" ...` to fit it in a smaller viewport.

What do you think about this idea?

**Comment by mdo** [comment] 2017-11-06 17:24
Duplicate of #22104.

**Closed by mdo** 2017-11-06 17:24 UTC
Labels: css, feature, v4
