### ISSUE TITLE
Do not hard-code <ul> selector for Tabs (and allow <nav>)

### ISSUE THREAD

**Issue by tonystar** [twbs/bootstrap#19447] opened 2016-03-08 23:37 UTC
In `tab.js` we have:
```js
let ulElement = $(this._element).closest(Selector.UL)[0]
//...
if (ulElement) {
  previous = $.makeArray($(ulElement).find(Selector.ACTIVE))
  previous = previous[previous.length - 1]
}
```

This code strongly relies on `<ul>` tag for Tabs.

So it fails when using `<nav class="nav nav-tabs">` in the markup.

**Comment by cvrebert** [comment] 2016-03-09 01:00
Duplicate of #17754.

**Closed by cvrebert** 2016-03-09 01:00 UTC
Labels: js, v4
