### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by Dezmonter** [twbs/bootstrap#35364] opened 2021-11-17 08:01 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Text is displayed incorrectly when using floating form and placeholder on multiple lines
### Reduced test cases
<img src="https://i.ibb.co/1nLRg3j/image.png" alt="image" border="0">

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.1.3

**Comment by mdo** [comment] 2021-11-25 23:43
Duplicate of #32800.

**Closed by mdo** 2021-11-25 23:43 UTC
