### ISSUE TITLE
.list-inline is missing `> li` code?

### ISSUE THREAD

**Issue by mysticman** [twbs/bootstrap#20163] opened 2016-06-23 12:43 UTC
In BS3 there was a class for mainly `<ul>` elements `.list-inline`. 

BS3: type.scss
```
.list-inline {
  @include list-unstyled;
  margin-left: -5px;

  > li {
    display: inline-block;
    padding-left: 5px;
    padding-right: 5px;
  }
}
```
There is in BS4 but missing this part of the code what achieve the inline property:
BS4: type.scss
.list-inline {
  **@include list-unstyled;**
}

Please provide a solution for this also in BS4. Thanks

**Comment by bogdaniel** [comment] 2016-06-23 18:09
check this out http://v4-alpha.getbootstrap.com/content/typography/#lists I think the issue should be closed.

**Comment by mysticman** [comment] 2016-06-23 18:48
Yeah, ok I saw that, but it seems "lame" to give all the children item that class, that is why I asked. Maybe this was not an improvement since BS3.

**Comment by cvrebert** [comment] 2016-06-24 05:55
We are avoiding child selectors and tag selectors as much as possible in v4, for the sake of flexibility. We'd like our selectors to impose exact DOM structure requirements on authors as little as possible, and we want to keep CSS specificity low so that our styles can be more easily overridden. Thus, using classes is required.
Approximate duplicate of #18813 & #19690.

**Closed by cvrebert** 2016-06-24 05:55 UTC
Labels: css, v4

**Comment by mysticman** [comment] 2016-06-24 06:16
Sure I agree there are many good approach to solve things, and mainly a good aim to be more flexible. Thanks for the info.

**Comment by bogdaniel** [comment] 2016-06-28 21:51
I find it much better now how the li is made :-) seems more simple and semantic.
