### ISSUE TITLE
carousel transition problem in Firefox

### ISSUE THREAD

**Issue by ben13oit** [twbs/bootstrap#25608] opened 2018-02-13 11:36 UTC
bug here:
https://getbootstrap.com/docs/4.0/examples/carousel/

W7 pro 64
Firefox 58.0.2

irregular scrolling from right to left only.
White spaces between pics, irregular scrolling speed

**Comment by mdo** [comment] 2018-02-14 05:24
Confirmed on macOS latest Firefox, too. Affects all carousels it seems.

**Comment by tmacallister** [comment] 2018-02-21 21:11
Is there a fix for this?

**Comment by jonnysp** [comment] 2018-02-26 18:15
i wrapped the item contend in a row - col
https://jsfiddle.net/jonnysp/f3pdL9eg/

not the fine english variant - but it works

**Comment by certain2** [comment] 2018-03-27 15:06
It´s still flickering in FF while sliding. Is there any workaround?

**Comment by XhmikosR** [comment] 2018-11-06 05:37
This should be fixed in v4-dev. It'd be nice if someone could confirm.

**Comment by XhmikosR** [comment] 2018-11-21 08:15
Closing for now, since it should be fixed in v4-dev. If not leave a comment.

**Closed by XhmikosR** 2018-11-21 08:15 UTC
Labels: awaiting reply, browser bug, v4
