### ISSUE TITLE
Modal "scroll independent of the page itself" does not work

### ISSUE THREAD

**Issue by rranke** [twbs/bootstrap#24841] opened 2017-11-21 07:23 UTC
1.) "scroll independent of the page itself" does not work :-(
2.) scrolling does lack :-(  (meaning its not as fluent as scrolling the normal page without opened modal)
3.) there is a horizontal scrolling, that should not be there :-(
4.) When scrolled-down to the end of the modal, scrolling-up the modal is not possible any more :-(

tested on
https://getbootstrap.com/docs/4.0/components/modal/#scrolling-long-content
iphone 5s ios11

![img_0354](https://user-images.githubusercontent.com/5783257/33059479-ac6363cc-ce94-11e7-9b4a-ac3455ceca70.GIF)

**Comment by Johann-S** [comment] 2017-11-21 09:25
Seems related to #24737

**Comment by andresgalante** [comment] 2017-11-28 17:35
Hi @rranke modals on mobile are tricky.

Some of the problems you mention are related to #24737

The horizontal scroll is probably a problem on your implementation.

Scrolling up is probably something we can work to solve.

**Comment by mdo** [comment] 2017-12-31 04:16
Closing as duplicate of #24737.

**Closed by mdo** 2017-12-31 04:16 UTC
Labels: css, v4
