### ISSUE TITLE
add variable for RTL support

### ISSUE THREAD

**Issue by EngRajabi** [twbs/bootstrap#15717] opened 2015-01-31 18:57 UTC
add to sess and less one variable for rtl or ltr bootstarp .
With the variable easy change ltr or rtl boostratp

**Comment by cvrebert** [comment] 2015-01-31 23:13
Yet another duplicate of #14510. Please search next time!
See also #15509.

**Closed by cvrebert** 2015-01-31 23:13 UTC
Labels: css, feature

**Comment by cvrebert** [comment] 2015-01-31 23:32
And duplicate of **your own #15479**!
