### ISSUE TITLE
input group inside a table makes issue

### ISSUE THREAD

**Issue by Mahendran-Sakkarai** [twbs/bootstrap#16730] opened 2015-06-30 13:30 UTC
When i use input-group inside table, the alignment of the table is gone.

Check the fiddle.
http://jsfiddle.net/mahendranmails/7acmu8ug/3/

I used bootstrap.min.css of Bootstrap v3.3.5.

In firefox it's working fine. But in chrome the alignment is not correctly set to the table.

**Comment by cvrebert** [comment] 2015-06-30 17:09
Duplicate of #16372?

**Comment by cvrebert** [comment] 2015-06-30 21:20
Yep, closing as a duplicate.

**Closed by cvrebert** 2015-06-30 21:20 UTC
Labels: css
