### ISSUE TITLE
Resizing confuses Affix about position

### ISSUE THREAD

**Issue by Shredder121** [twbs/bootstrap#18290] opened 2015-11-19 19:19 UTC
I identified a bug which is observable in all browsers.

![image][ChrEdFi]

That is a screenshot of Chrome, Edge and Firefox.

I'll be posting screenshots of Firefox for now.

|    Step                                       |     Result                                                            |
|----------------------------------------|------------------------------------------------------------|
| Step 1 - Initial viewport             |   ![first screen][initial_viewport]                          |
| Step 2 - Scroll until affixed        |   ![scrolling until affixed][scroll_to_affix]             |
| Step 3 - Resize viewport           |   ![resize viewport][resize_viewport]                  |
| Step 4 - Scroll up                      |   ![scroll up][scroll_up]                                       |
| Step 5 - Reset viewport            |   ![reset viewport][reset_viewport]                     |

It seems this issue goes hand in hand with all other Affix issues, but to me it looks like the 'initialization' of Affix doesn't take into account the _current_ state, but _continues where it left off_.

I just wanted you to be aware of this. Keep up the good work! :+1:

[ChrEdFi]: https://cloud.githubusercontent.com/assets/4105066/11280763/b46981a2-8ef7-11e5-8e22-b89f72ae591b.png

[initial_viewport]: https://cloud.githubusercontent.com/assets/4105066/11280799/ef042d62-8ef7-11e5-8df6-cb3a9ee43e30.png
[scroll_to_affix]: https://cloud.githubusercontent.com/assets/4105066/11281162/9ddd5038-8ef9-11e5-86be-fd5ab2ffe27c.png
[resize_viewport]: https://cloud.githubusercontent.com/assets/4105066/11281199/d66dced2-8ef9-11e5-89db-33c65b37afea.png
[scroll_up]: https://cloud.githubusercontent.com/assets/4105066/11281219/f564e1ea-8ef9-11e5-8eac-16163f0b5482.png
[reset_viewport]: https://cloud.githubusercontent.com/assets/4105066/11281340/85047900-8efa-11e5-92b5-3a8430d96b73.png

**Comment by cvrebert** [comment] 2015-11-24 07:56
Duplicate of #15845.

**Closed by cvrebert** 2015-11-24 07:56 UTC
Labels: js, v3
