### ISSUE TITLE
custom-file input overflown by long filename

### ISSUE THREAD

**Issue by jonasbrief** [twbs/bootstrap#29502] opened 2019-10-08 12:55 UTC
## Environment 
**Bootstrap Version:** 4.3
**Browsers:** Chromium 73.0.3683.75 (Debian 9); Firefox 60.0.9esr, Chrome 77.0.3865.90 (Windows 10)

## Steps to reproduce 
1. Create file with very long filename (e.g. longnamelongnamelongnamelongnamelongnamelongnamelongnamelongnamelongnamelongnamelongnamelongnamelongnamelongnamelongnamelongnamelongnamelongnamelongnamelongname.txt)
2. Go to https://getbootstrap.com/docs/4.3/components/forms/#file-browser
3. Click `Browse` 
4. Select your file 

## Expected Behaviour
The filename is truncated 

## Actual Behaviour
The filename overflows the input box

**Comment by florianlacreuse** [comment] 2019-10-08 15:23
See #28897. It won't be fixed in v4.

**Comment by XhmikosR** [comment] 2019-10-08 16:23
Duplicate of #28897

**Closed by XhmikosR** 2019-10-08 16:23 UTC
