### ISSUE TITLE
Tooltip flickers and dissapears

### ISSUE THREAD

**Issue by NathalieSpierings** [twbs/bootstrap#33253] opened 2021-03-03 12:03 UTC
OS: Windows 10
Firefox: latest

In the bootstrap 5.0 beta 1 as well in beta 2 tooltips are flickering and dissapearing.
In my application it's happening all over the place. On buttons,  icons, inputs etc.

I have made an simple sample in codepen: https://codepen.io/Talsja22/pen/OJbEpGd
I have placed a tooltip on the eye svg icon. See what happens.

**Comment by mdo** [comment] 2021-03-03 21:58
Duplicate of #32372.

**Closed by mdo** 2021-03-03 21:58 UTC
