### ISSUE TITLE
Navbar dropdown is not  poppered

### ISSUE THREAD

**Issue by mzawodzinski** [twbs/bootstrap#28755] opened 2019-05-10 10:24 UTC
Tested on Bootstrap 4.0 and Bootstrap 4.3.x on documentation page /  debian 10, windows 10  / Chrome  74 / firefox 60

Dropdown in navbar should be automatically moved by popper to prevent horizontal scrolled page.
But this not work, dropdown-menu is always on this some spot.

![obraz](https://user-images.githubusercontent.com/36850550/57520362-c0f46a00-731d-11e9-9132-8c3f2c655863.png)
![obraz](https://user-images.githubusercontent.com/36850550/57520368-c782e180-731d-11e9-97dd-7905aea442fc.png)
To test it on documentation page:
- add style="width: 100%;justify-content: space-between;" to .navbar-nav
- remove last li
- remove form from nav

I found working examples on codepen but this is Bootstrap v4.0.0-alpha.6 
https://codepen.io/Johann-S/pen/RVBoGM
![obraz](https://user-images.githubusercontent.com/36850550/57520562-3eb87580-731e-11e9-8835-bc2ea2ea82df.png)

**Comment by James-T-KIRK** [comment] 2019-05-10 13:49
Interoperability of document is correct ?

**Comment by mzawodzinski** [comment] 2019-05-10 17:28
I don't know if I understood correctly,
without any errors in the console, if you asking about this.

**Comment by ysds** [comment] 2019-05-10 18:05
Please see https://getbootstrap.com/docs/4.3/components/dropdowns/#menu-alignment

**Comment by mzawodzinski** [comment] 2019-05-13 07:17
Nop,
![obraz](https://user-images.githubusercontent.com/36850550/57602545-af020980-755f-11e9-9d0a-7690f8e53960.png)
this move dropdown to left or right side but still popper not work

**Comment by ysds** [comment] 2019-05-13 09:00
That behavior is intentional and not related to popper but `.dropdown-toggle {  white-space: nowrap; }` (#28029). You can fix that by adding a `text-warp` class to the `.dropdown-toggle`.

**Comment by mzawodzinski** [comment] 2019-05-13 09:24
ok, but dropdown in navbar should use popper, yes ?
So look at this https://www.youtube.com/watch?v=RZ7XSQV1ePs
on bs page elemet is static, on codepen has dynamic change  style translate3d and this do popper.

**Comment by ysds** [comment] 2019-05-15 15:33
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/)/[JS Bin](https://jsbin.com/) or [Stackblitz](https://stackblitz.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

*This is an automated reply*

**Comment by ysds** [comment] 2019-05-17 13:41
This seems to be duplicate of #25243.

@mzawodzinski  Closing for now, but if this is not a duplicate of #25243, please comment here.

**Closed by ysds** 2019-05-17 13:41 UTC
Labels: awaiting reply
