### ISSUE TITLE
Navbar dropdown not collapsing properly. 

### ISSUE THREAD

**Issue by gpit2286** [twbs/bootstrap#17668] opened 2015-09-22 06:27 UTC
Currently, the v4 collapses menus like this. 
![screen shot 2015-09-21 at 11 24 43 pm](https://cloud.githubusercontent.com/assets/3317312/10012051/2d6b02a6-60b8-11e5-9a31-9a90862ebc3e.png)

This can also be seen in the docs.  

Is this the new way that bootstrap is going to handle Navbar menus? If it is, I will single handedly lead a campaign to bring the old behavior back.

**Comment by cvrebert** [comment] 2015-09-22 09:36
Duplicate of #17250.

**Closed by cvrebert** 2015-09-22 09:36 UTC
