### ISSUE TITLE
Red border for required input fields on Firefox

### ISSUE THREAD

**Issue by RodrigoQuesadaDev** [twbs/bootstrap#21323] opened 2016-12-09 18:21 UTC
Hi, currently a red border is displayed for required fields when using Firefox.

This doesn't occur in Bootstrap v3 because that version adds _box-shadow: inset 0 1px 1px rgba(0,0,0,.075)_ to _.form-control_ elements.

How to reproduce?

- Go to the official documentation: https://v4-alpha.getbootstrap.com/components/forms/
- Add required to any text input field.
- You might need to change/enter text into it and then remove it.

Code example:

```
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input required type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
```

Bootstrap: v4.0.0-alpha.5
OS: Linux
Browser: Firefox 50.0.2

**Comment by cvrebert** [comment] 2016-12-10 01:48
Apparently this is part of Firefox's UA stylesheet (`view-source:resource://gre-resources/forms.css`):
```css
/**
 * Set default style for invalid elements.
 */
:not(output):-moz-ui-invalid {
  box-shadow: 0 0 1.5px 1px red;
}

:not(output):-moz-ui-invalid:-moz-focusring {
  box-shadow: 0 0 2px 2px rgba(255,0,0,0.4);
}
```

**Comment by cvrebert** [comment] 2016-12-10 01:55
@RodrigoQuesadaDev And you find this problematic because...?

**Comment by barraponto** [comment] 2016-12-10 13:50
Some context on that pseudo-class: https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-ui-invalid

> This pseudo-class is applied according to the following rules:
> 
> * If the control does not have focus, and the value is invalid, apply this pseudo-class.
> * If the control has focus, and the value was valid (including empty) when it gained focus, do not apply the pseudo-class.
> * If the control has focus, and the value was invalid when it gained focus, re-validate on every keystroke.
> * If the element is required, the preceding rules apply only if the user has changed the value or attempted to submit the form.

**Comment by RodrigoQuesadaDev** [comment] 2016-12-10 19:24
I see, this kind of issues belong to that project, they don't directly concern to this framework. My mistake...

**Comment by mdo** [comment] 2017-02-27 01:16
Closing per Normalize's issue.

**Closed by mdo** 2017-02-27 01:16 UTC
Labels: css, v4

**Comment by felixfbecker** [comment] 2018-04-12 05:04
Imo this makes the native validation methods in Bootstrap unusable because they will always render a red border even without the `was-validated` class. This is extremely confusing for developers, as the Firefox dev tools don't even show where the outline comes from. Maybe this could be considered as a reset as part of reboot?

**Comment by felixfbecker** [comment] 2018-04-12 21:20
Firefox applies `:-moz-ui-invalid` as soon as it considers an input field "dirty" (i.e. changed at least once). The problem is, any assignment to the `value` property of the input field triggers this (even if it is a noop or the empty string). So if you use any frontend framework like React to sync the value with State in the component (i.e. you have a binding for the value `value={this.state.fooValue}`) the style will be triggered as soon as the component renders, because React will always assign the empty string initially.

Here's a JSFiddle showing the issue: https://jsfiddle.net/69z2wepo/173476/

![image](https://user-images.githubusercontent.com/10532611/38704284-a7e8809e-3e5a-11e8-9b06-1c5c1f68a019.png)

and when trying to use Bootstrap's form feedback styles, the styles overlay each other in an ugly way:

![2018-04-12 2 13 05 pm](https://user-images.githubusercontent.com/10532611/38704603-c05c8d7c-3e5b-11e8-9bbc-abddd28786a0.gif)
https://jsfiddle.net/7avbL29j/4/

This can be worked around by adding

```scss
:not(output):-moz-ui-invalid:not(:focus) {
  box-shadow: none;
}

:not(output):-moz-ui-invalid:-moz-focusring:not(:focus) {
  box-shadow: none;
}
```
![2018-04-12 2 19 14 pm](https://user-images.githubusercontent.com/10532611/38704862-8763a3a6-3e5c-11e8-951d-a0368ad816d4.gif)
https://jsfiddle.net/bsx2mcyy/3/

but it feels like a hack because you need to exclude the Bootstrap focus states to make sure those don't get overridden.

Given that frameworks like React (I would guess this affects Angular, Vue etc just as much) are widely used I think this is a pretty bad pitfall, especially considering that most devs might never catch this because it is only happening in Firefox. I believe Bootstrap should consider adding the above override to make the styles work as expected across browsers.

**Comment by patrickhlauke** [comment] 2018-04-12 22:10
this feels like a problem with React rather than Bootstrap in principle, as the same styling will then happen (if you inject empty string) even without Bootstrap being present at all, in vanilla pages? Probably something more suited to tackle at React's end rather than adding a hacky workaround in BS?

**Comment by NathanCH** [comment] 2018-05-09 21:30
@felixfbecker, great explanation in your previous post.

This problem is not exclusive to React, as you mention. Basic common example... <select /> is populated asynchronously and not provided a default value, the red shadow will appear. 

This can be reproduce without Bootstrap, so as discussed earlier, is it Bootstrap's responsibility to normalize experiences across browsers?

Thanks for your solution @felixfbecker.
