### ISSUE TITLE
Is there any support for mega menu with Boostrap navigation?

### ISSUE THREAD

**Issue by chauhandhruv** [twbs/bootstrap#17582] opened 2015-09-12 10:40 UTC
Is there any support for mega menu with Boostrap navigation? If no then would you please integrate it?

**Comment by cvrebert** [comment] 2015-09-12 18:50
We do not include such a widget and have to plans to add such a widget. However, if you google around, you'll find some third-party mega menu widgets for Bootstrap.
Duplicate of #2965.

**Closed by cvrebert** 2015-09-12 18:50 UTC
Labels: feature, v4
