### ISSUE TITLE
.collapse('hide') as onclick on a radiobutton   SHOWs the content

### ISSUE THREAD

**Issue by Banzai** [twbs/bootstrap#15354] opened 2014-12-12 16:58 UTC
see:
http://stackoverflow.com/questions/24466260/clicking-on-a-radio-button-explicitly-coded-to-close-all-bootstrap-accordions-op

http://jsfiddle.net/3F6TY/3/

**Comment by cvrebert** [comment] 2015-03-06 10:21
Yes; closing as a duplicate of #15315.

**Closed by cvrebert** 2015-03-06 10:21 UTC
Labels: js
