### ISSUE TITLE
v4.3 doc suggest can switch to 5.0

### ISSUE THREAD

**Issue by Yang09701194** [twbs/bootstrap#32559] opened 2020-12-20 13:59 UTC
Hi, today I google "booststrap navbar", and first search result is showing [V4.3 page](https://getbootstrap.com/docs/4.3/components/navbar/#), and I find the css class syntax of V4.3 is not compatible with latest V5.0, and when I want to switch to 5.0, I find there's no option, 

and that make me think the doc is paused at V4.3, as the screenshot:

![alt text](https://i.imgur.com/N11Vjcg.png)

But later I go to the home page and click doc, then I know that the doc has [V5.0 page](https://getbootstrap.com/docs/5.0/components/navbar/). 

So to let user easier know that the doc has V5.0 when google search visit V4.3, I suggest the doc can add V5.0 option to the V4.3 document !

**Comment by XhmikosR** [comment] 2020-12-20 15:13
Duplicate of so many issues.

**Closed by XhmikosR** 2020-12-20 15:13 UTC
Labels: feature
