### ISSUE TITLE
Issues with carousel when using SASS bootstrap

### ISSUE THREAD

**Issue by chet28** [twbs/bootstrap#15547] opened 2015-01-12 17:24 UTC
When compiling bootstrap with the SASS files I was having issues with the bootstrap carousel. The issue only happened on mobile platforms (I verified it on ipad/iphone/nexus using both chrome and safari) and the carousel would get stuck/freeze on the 2nd image. I originally thought it was one of these issues related to angular's ngAnimate module as the symptoms are the same:

https://github.com/angular-ui/bootstrap/issues/1350
https://github.com/angular-ui/bootstrap/issues/1273

However, the various demo carousels worked fine and it looked like the problem was with my site - but even when I copied all the standard demo's out there it was still an issue. The only thing different was that I was using SASS bootstrap and when I downloaded and switched to the (pre) compiled CSS the problem went away. Then started diff'ing the SASS css I was producing (based on unmodified SASS files) and the pre-compiled css I notified that the carousel css was different. In particular the -webkit-transition / -webkit-transform styles were missing when using SASS bootstrap.

Had this with 3.3.1. and 3.3.0 versions (and earlier but can't remember which) of bootstrap.

Hope this makes sense.
Chet

**Comment by cvrebert** [comment] 2015-01-12 17:44
Duplicate of  #14937.

**Closed by cvrebert** 2015-01-12 17:44 UTC

**Comment by interglobalmedia** [comment] 2016-04-12 20:08
I am having the same problems with Boostrap Sass. Previously, carousel worked beautifully with compiled CSS. But now, with Bootstrap Sass 3.3.6, not working.
