### ISSUE TITLE
jquery pre-requisite in Visual Studio NuGet

### ISSUE THREAD

**Issue by fballem** [twbs/bootstrap#20265] opened 2016-07-10 06:30 UTC
I am using Visual Studio 2015 Community edition. There is a repository, called NuGet, that contains extensions for Visual Studio, including Bootstrap.

As part of the extension, there are facilities to update Bootstrap to 3.3.6. The package includes a jQuery dependency (jQuery (>= 1.9.1 && 3.0.0)

Visual Studio 2015 has been updated recently to use jQuery 3.0.0.1, which is causing the following error to appear while attempting to update the Bootstrap extension 3.3.6: dependency: Error		Unable to resolve dependencies. 'jQuery 3.0.0.1' is not compatible with 'bootstrap 3.3.6 constraint: jQuery (>= 1.9.1 && < 3.0.0)'.

Could you please check and advise?

Many thanks,

**Comment by cvrebert** [comment] 2016-07-10 19:08
Approximate duplicate of #16834.

**Closed by cvrebert** 2016-07-10 19:08 UTC
Labels: js, meta, v3
