### ISSUE TITLE
website: (google) search brings up documentation for old versions

### ISSUE THREAD

**Issue by aavmurphy** [twbs/bootstrap#29304] opened 2019-08-25 17:32 UTC
e.g. if i search `bootstrap responsive classes`, i get the v3.4 documentation page

it would be nice if google's suggested result was the latest 4.x page

possible way to do this
- sitemap's have a priority value for each page

**Comment by mdo** [comment] 2019-08-25 20:33
Duplicate of #28581.

**Closed by mdo** 2019-08-25 20:33 UTC
