### ISSUE TITLE
Custom input file after choice file nothing change.

### ISSUE THREAD

**Issue by madmax** [twbs/bootstrap#23994] opened 2017-09-18 22:05 UTC
When we choice file nothing change (we don't see filename). 
https://getbootstrap.com/docs/4.0/components/forms/#file-browser

This should work this way? We need write JS to look change event and update filename inside custom-file-control? 

Tested on: 
Beta 4.0.0
Safari 11  and Chrome  60
MacOS 10.13

**Comment by Johann-S** [comment] 2017-09-19 07:32
That's true no update, should we add a simple plugin which handle that ? 
@mdo, @XhmikosR, @bardiharborow

**Comment by Gaurav-Kumar-Rana** [comment] 2017-09-19 10:36
Test

**Comment by tmorehouse** [comment] 2017-09-20 01:02
We have added file name update support in `<b-form-file>`, which is the Bootstrap-Vue implementation of Bootstrap's custom file input.  YOu might be able to make a plugin out of our file handler code:  https://github.com/bootstrap-vue/bootstrap-vue/blob/dev/lib/components/form-file.vue

Basically it places the file names (or file count, in the case of multiple) in a `data-*` attribute which then picks up the file name(s) via CSS `content()` selector.

![image](https://user-images.githubusercontent.com/2781561/30622149-2036c194-9d86-11e7-8aad-5882d46dbcd5.png)

**Comment by bardiharborow** [comment] 2017-09-23 00:38
I thought we had code for this at some stage (not in a core plugin, but as an optional extra). Where did that go?

**Comment by Johann-S** [comment] 2017-09-23 15:19
I don't remember if we had code about that 😯

**Comment by jplaverdure** [comment] 2017-09-25 18:58
I'm preety sure the doc mentions someplace that filename update is not implemented 

But it's fairly easy to put in place, here's a solution:
`$('.custom-file-input').on('change', function() {
    let fileName = $(this).val().split('\\').pop();
    $(this).next('.custom-file-control').addClass("selected").html(fileName);
});`

**Comment by istratos** [comment] 2017-11-01 16:43
@jplaverdure this code won't work for multiple file input.

But I agree this should be a feature, it just feels weird to use this component and not have the file name auto update.

**Comment by Superpencil** [comment] 2017-11-30 03:35
Thanks @jplaverdure

**Comment by PrinceOfAbyss** [comment] 2017-12-20 17:33
This but still exists on v4.0.0 beta2

**Comment by mdo** [comment] 2017-12-28 18:47
Closing as duplicate of #20813.

**Closed by mdo** 2017-12-28 18:47 UTC
Labels: confirmed, js, v4

**Comment by shankyb123** [comment] 2018-02-28 12:00
Thanks @jplaverdure 
$('.custom-file-input').on('change', function() { 
    let fileName = $(this).val().split('\\').pop(); 
    $(this).next('.custom-file-control').addClass("selected").html(fileName); 
});
This code is working on single file upload

**Comment by Qui13t** [comment] 2018-04-12 08:57
@jplaverdure your code isn't working for me:((

**Comment by thewebdevelopers** [comment] 2018-04-18 21:47
@bouiboui  - line 3 should target the sibling of the input requiring update, as with multiple inputs on a page your code would update all labels with the same filename.

```javascript
$('.custom-file-input').on('change', function() {
    let fileName = $(this).val().split('\\').pop();
    $(this).siblings('.custom-file-label').addClass("selected").html(fileName);
});
```

**Comment by bouiboui** [comment] 2018-04-18 21:53
Absolutely, I updated my comment.

**Comment by comniemeer** [comment] 2018-07-29 00:46
I added a few lines to the snipped so the default label text gets restored if the file is deselected.
```js
$('.custom-file-input').on('change', function() {
    let fileName = $(this).val().split('\\').pop();
    let label = $(this).siblings('.custom-file-label');
    
    if (label.data('default-title') === undefined) {
        label.data('default-title', label.html());
    }
    
    if (fileName === '') {
        label.removeClass("selected").html(label.data('default-title'));
    } else {
        label.addClass("selected").html(fileName);
    }
});
```

**Comment by proakshay** [comment] 2019-03-18 06:26
can we do the same in javascript?

**Comment by bouiboui** [comment] 2019-03-18 08:29
You mean, without jQuery? You can, but it will be a lot more verbose.
What's the context, why don't you want to use jQuery?

**Comment by Johann-S** [comment] 2019-03-18 08:49
@proakshay and @bouiboui Bootstrap use this plugin to do that: https://www.npmjs.com/package/bs-custom-file-input

**Comment by kondagariraviteja1** [comment] 2019-07-19 07:20
If i want for multiple file uploads in single page these code is not working it is working for single file upload  and it is applying for last control of file upload how can i upload multiple file uploads...

**Comment by Johann-S** [comment] 2019-07-19 07:33
@kondagariraviteja1 you should use https://www.npmjs.com/package/bs-custom-file-input it handle multi file upload, you just have to add `multiple` attribute on your input file 😉
