### ISSUE TITLE
[docs] Live Example Toast Underneath Text

### ISSUE THREAD

**Issue by andrenevesgomes** [twbs/bootstrap#37194] opened 2022-09-22 15:40 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

While triggering the button "Show live toast" the toast appears underneath the text.

### Reduced test cases

This difficultie was felt while using the resolution 1366x768

### Image attached
![image](https://user-images.githubusercontent.com/48434290/191791449-7614033d-8739-4c33-87af-45eddd65b381.png)

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What version of Bootstrap are you using?

5.2

**Comment by julien-deramond** [comment] 2022-09-22 16:26
Duplicate of #37175

**Closed** 2022-09-22 16:27 UTC
