### ISSUE TITLE
$ is not defined

### ISSUE THREAD

**Issue by LeonCv** [twbs/bootstrap#24506] opened 2017-10-22 22:31 UTC
-BS version (4.beta.2)
- Operating system and version (Windows10)
- Browser and version (Chrome61)
Using with vue single file component, v4.beta works well, showing $ is not defined when updated to beta2
![image](https://user-images.githubusercontent.com/28700378/31867087-80a6313a-b7e5-11e7-8f26-7dcd532f4324.png)
js
![image](https://user-images.githubusercontent.com/28700378/31867120-12e61fb0-b7e6-11e7-9b68-608b414f45c4.png)
css
![image](https://user-images.githubusercontent.com/28700378/31867122-1c16e330-b7e6-11e7-80d6-76909c5d3681.png)
#
dependencies
![image](https://user-images.githubusercontent.com/28700378/31867185-110c726a-b7e7-11e7-9ea8-7d32765fa434.png)

**Comment by mdo** [comment] 2017-10-23 02:22
Duplicate of #24500.

**Closed by mdo** 2017-10-23 02:22 UTC
