### ISSUE TITLE
Please add negative space default

### ISSUE THREAD

**Issue by veeruk0217** [twbs/bootstrap#32505] opened 2020-12-16 13:14 UTC
Please add negative space default

**Comment by patrickhlauke** [comment] 2020-12-16 13:29
meaning...what exactly? You'll have to provide a bit more information here rather than this very generic statement...

**Comment by Hiws** [comment] 2020-12-16 14:13
Maybe he refers to enabling the negative margin utilities by default.
The same as this issue: https://github.com/twbs/bootstrap/issues/32385

**Comment by XhmikosR** [comment] 2020-12-16 15:23
Duplicate of #32385

**Closed by XhmikosR** 2020-12-16 15:23 UTC
Labels: feature
