### ISSUE TITLE
Link to "Narrow jumbotron" on v4 Examples docs 404s

### ISSUE THREAD

**Issue by peterbe** [twbs/bootstrap#17771] opened 2015-10-04 06:40 UTC
From http://v4-alpha.getbootstrap.com/examples/ the link to 
http://v4-alpha.getbootstrap.com/examples/jumbotron-narrow/ causes a 404 not found.

**Comment by hebbet** [comment] 2015-10-04 11:42
seems to be fixed an current v4 branch

**Comment by cvrebert** [comment] 2015-10-04 16:41
Duplicate of #17174. Please search more next time. Thanks.

**Closed by cvrebert** 2015-10-04 16:41 UTC
Labels: docs, v4
