### ISSUE TITLE
[accessibility] Button plugin doesn't apply "checked"-property to checkbox/radio button when activated with the keyboard 

### ISSUE THREAD

**Issue by Lausselloic** [twbs/bootstrap#18874] opened 2016-01-13 13:26 UTC
I've seen the #18866 and I agree. 
But when the user interact with the keyboard (tab to navigate, space bar to check/uncheck) the checked property don't be updated onto radio and checkboxes.
 http://v4-alpha.getbootstrap.com/components/buttons/#checkbox-and-radio-buttons

**Comment by patrickhlauke** [comment] 2016-01-13 14:15
urgh, it seems the workarounds/fixes from https://github.com/twbs/bootstrap/pull/16226 and https://github.com/twbs/bootstrap/pull/16404 may not have been ported to v4? /cc @mdo @fat @cvrebert

**Comment by cvrebert** [comment] 2016-01-14 00:32
Implementing the suggestion from #17021 ought to fix this and make the plugin simpler in general:
> ### Buttons
> * Consider replacing `.active` with `> input:checked` (etc.) in the Buttons plugin styles to address twbs/bootstrap#11535.

**Comment by cvrebert** [comment] 2016-04-14 22:43
Implementation sketch of my suggestion: http://jsbin.com/lidedi/edit?html,css,output

**Comment by twbs-lmvtfy** [comment] 2016-04-14 22:43
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/lidedi/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickhlauke** [comment] 2016-04-15 12:43
slightly modified/expanded (stealing some of the current buttons styles) sketch http://codepen.io/patrickhlauke/pen/PNRMve

**Comment by twbs-lmvtfy** [comment] 2016-04-15 12:43
Hi @patrickhlauke!

You appear to have posted a live example (http://codepen.io/patrickhlauke/pen/PNRMve.html), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 31, column 5 thru column 50: Duplicate attribute ```` id ````.
* line 35, column 4 thru column 49: Duplicate attribute ```` id ````.
* line 39, column 3 thru column 48: Duplicate attribute ```` id ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment] 2016-04-15 19:40
It might be possible, with some fiddling, to move the `.btn` up from the `label` to the `.btn-checked`, which might allow the `.btn-group` styles to "just work" (and thus let us avoid duplicating a lot of the `.btn-group` CSS).

**Comment by patrickhlauke** [comment] 2016-05-30 22:19
@cvrebert revisited this briefly today...something like http://codepen.io/patrickhlauke/pen/QEWRpp ? /cc @mdo

**Comment by cvrebert** [comment] 2016-05-31 09:03
@patrickhlauke I think the approach is good enough for a PR, so we can start nitpicking it properly 😄

**Comment by patrickhlauke** [comment] 2016-05-31 09:09
roger roger...will get onto that this week

**Comment by patrickhlauke** [comment] 2016-05-31 23:10
@cvrebert made an attempt, but failing to get anything to work out properly with the current mixins. it also looks fairly ugly...

with a super-simplified markup of

```
<div class="btn-group">
  <input id="check1" type="checkbox" checked="" autocomplete="off"><label class="btn btn-primary" for="check1">Checkbox 1 (pre-checked)</label>
  <input id="check2" type="checkbox" autocomplete="off"><label class="btn btn-primary" for="check2">Checkbox 2</label>
  <input id="check3" type="checkbox" autocomplete="off"><label class="btn btn-primary" for="check3">Checkbox 3</label>
</div>
```

i'd conceptually would need to do something like

```
@mixin button-variant($color, $background, $border) {
  ...
  &:focus,
  &.focus,
  .btn-group input[type="checkbox"]:focus + label.#{&},
  .btn-group input[type="radio"]:focus + label.#{&}, {
    color: $color;
    background-color: $active-background;
        border-color: $active-border;
  }
  ...
}
```

but this obviously fails in Sass. not sure how to proceed without inventing completely new classes or rewriting the whole mixin approach :(

**Comment by patrickhlauke** [comment] 2016-05-31 23:23
FWIW i updated the pen http://codepen.io/patrickhlauke/pen/QEWRpp to this much simpler (from a markup and styles point of view) approach

**Comment by mdo** [comment] 2016-11-27 00:45
Fixed by #18900 I believe, and same as #16673 and #17599.

**Closed by mdo** 2016-11-27 00:45 UTC
Labels: confirmed, css, help wanted, js, v4

**Comment by AlexVentura** [comment] 2018-07-01 00:05
Hey there!
Has the issue being fixed? Because I still having it on **Bootstrap v4.1.1**. This is [my example](https://codepen.io/alexventura/pen/gKqwXr) for reference.
The `radio` inputs do not get the `checked` attribute when clicking on them.

**Comment by He3lixxx** [comment] 2018-07-02 21:14
I can also reproduce this in the [bootstrap docs example](https://getbootstrap.com/docs/4.1/components/buttons/#checkbox-and-radio-buttons), using firefox 60.0.2 and chrome 67.0.3396.99. If you click on any of the three buttons and then change your selection with the keyboard, it looks as if you've selected another button. The underlying radio input selection is not changed though.
