### ISSUE TITLE
[v4 beta-3] bug: d-print-inline not working as expected

### ISSUE THREAD

**Issue by WebDevBooster** [twbs/bootstrap#25322] opened 2018-01-16 00:23 UTC
When using this inline form: 

https://getbootstrap.com/docs/4.0/components/forms/#inline-forms

and adding either the `d-print-inline` or the `d-print-inline-block` class to the `form-inline` class, the form disappears from the screen. 

And when trying to print the disappeared form the `d-print-inline` class doesn't show the form inline to the printer i.e. the form fields and elements are stacked and not inline as expected.

**Comment by mdo** [comment] 2018-01-16 03:10
Duplicate of #25221.

**Closed by mdo** 2018-01-16 03:10 UTC
