### ISSUE TITLE
BS4 modal fade out

### ISSUE THREAD

**Issue by Iworb** [twbs/bootstrap#23288] opened 2017-08-11 07:53 UTC
[Here's](https://getbootstrap.com/docs/4.0/components/modal/) live demo example of a modal window. Hovever, closing modal windows makes background disappear instantly and other elements fading out like expected.

**Comment by Johann-S** [comment] 2017-08-11 07:55
Sorry I don't understand, what's your issue here ? It seems everything is normal

**Comment by gijsbotje** [comment] 2017-08-11 07:59
You mean the background of the modal? because i do see that happening when the modal gets is fading out

**Comment by Iworb** [comment] 2017-08-11 08:00
Open Live example modal and close it. Background of modal window will disappear instantly, but other elements will fade out as expected.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6623262/29205250-546bec08-7e84-11e7-875c-9dd2f58b784c.gif)

**Comment by RolandStuder** [comment] 2017-08-11 09:32
I did not notice at first, but the issue is, that initiating the animation the background disapears immediately so for a short moment it looks like this:

![image](https://user-images.githubusercontent.com/194364/29208036-b6bade2e-7e88-11e7-941a-c9f81817e773.png)

**Comment by XhmikosR** [comment] 2017-08-11 16:28
@Johann-S: maybe we should increase `BACKDROP_TRANSITION_DURATION`? Although to be honest doesn't seem to change anything here...

**Comment by Johann-S** [comment] 2017-08-12 17:04
is it an issue with our docs or with our component ? is it the same in a CodePen ?

**Comment by gijsbotje** [comment] 2017-08-12 18:45
@Johann-S you're right, it seems like a docs issue https://codepen.io/gijsbotje/pen/brrMQw

**Comment by XhmikosR** [comment] 2017-08-12 18:48
Well, I can't reproduce with docs either...

**Comment by gijsbotje** [comment] 2017-08-12 19:04
it's due to the z-index, this is set to 1072 form `.modal.show` but when the modal closes falls back to 1050
therefore it drops behind the docs header and the backdrop
would gladly make a PR for this

**Comment by XhmikosR** [comment] 2017-08-12 19:27
Please do so and CC me. Thanks !

**Comment by gijsbotje** [comment] 2017-08-12 19:46
done #23368

**Comment by Johann-S** [comment] 2017-08-12 20:08
Closed by #23368

**Closed by Johann-S** 2017-08-12 20:08 UTC
Labels: css, v4
