### ISSUE TITLE
Browser wont scroll to a collapsed accordion element from anchor to it elsewhere on/off page

### ISSUE THREAD

**Issue by bellwood** [twbs/bootstrap#26965] opened 2018-07-25 19:34 UTC
- OSX 10.13.6
- Chrome Version 68.0.3440.75 (Official Build) (64-bit)
- https://jsfiddle.net/ez2xLdj6/
- Bootstrap 4.1.3

When you have a longer page that scrolls, if you have an anchor that links to a specific "collapse" or accordion element that is closed, the browser will not scroll to it.

If I manually scroll, open the collapse element up, scroll back up and click the anchor, viola, the page scrolls to it

I tried working around this by adding an id to the heading that is always visible however this doesn't un-collapse the element when it's scrolled to.

Edit: Clarified title, twice even

**Comment by Johann-S** [comment] 2018-07-26 07:07
I think that's a browser behavior here, and not a bug in Bootstrap

/CC @XhmikosR or @patrickhlauke

**Comment by XhmikosR** [comment] 2018-07-30 05:45
I believe it's normal too from a quick look.

**Comment by mdo** [comment] 2018-08-24 16:02
Yup, closing as a won't fix.

**Closed by mdo** 2018-08-24 16:02 UTC
