### ISSUE TITLE
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '/c/10013' is not a valid selector.

### ISSUE THREAD

**Issue by ronit-mukherjee** [twbs/bootstrap#27939] opened 2018-12-28 05:44 UTC
I am seeing a blocking error on the load of the page.

The error appears in the bootstrap.min.js
**Bootstrap Version:-** 4.2.1

**The error is:-**
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '/c/10013' is not a valid selector.

**Screenshots are as follows:-**
![bootstrap-error](https://user-images.githubusercontent.com/39576708/50504163-b8e40e00-0a91-11e9-840c-75cf4cbdb849.PNG)
![bootstrap-error2](https://user-images.githubusercontent.com/39576708/50504164-b97ca480-0a91-11e9-8bc2-5b976d8cc841.PNG)

**Comment by XhmikosR** [comment] 2018-12-28 06:47
Duplicate of #27903, see https://github.com/twbs/bootstrap/issues/27903#issuecomment-450292043

**Closed** 2018-12-28 06:46 UTC
