### ISSUE TITLE
While modal close the modal-body text is not hiding

### ISSUE THREAD

**Issue by sibaspage** [twbs/bootstrap#23484] opened 2017-08-16 08:01 UTC
Close the modal,
But the modal-body text is hiding after the modal closed. V4 bootstrap

**Comment by Johann-S** [comment] 2017-08-16 08:42
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [JS Bin](https://jsbin.com/) or [CodePen](http://codepen.io/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by bkdotcom** [comment] 2017-08-17 15:02
dupe of #23288 ?

**Closed** 2017-10-23 05:13 UTC
Labels: awaiting reply
