### ISSUE TITLE
New jQuery version breaks bootstrap

### ISSUE THREAD

**Issue by AmitMY** [twbs/bootstrap#20108] opened 2016-06-10 16:09 UTC
jQuery released version 3.0.0 stable, no beta, official version.
Bootstrap throws this:
`Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3`

Can you release a new version for bootstrap (3, not 4) that supports version 3?

**Comment by cvrebert** [comment] 2016-06-10 16:20
Duplicate of #16834. Please search more in the future. Thanks.

**Closed by cvrebert** 2016-06-10 16:20 UTC
