### ISSUE TITLE
Tooltips are breaking the collapse in Vue 3 + Bootstrap 5

### ISSUE THREAD

**Issue by viveknz76** [twbs/bootstrap#39101] opened 2023-08-23 18:37 UTC
### Discussed in https://github.com/orgs/twbs/discussions/39100

<div type='discussions-op-text'>

<sup>Originally posted by **viveknz76** August 24, 2023</sup>
I believe there is an issue with bootstrap 5 and Vue 3.

I tried to get tooltip and collapse working on a page but implementing tooltip breaks the collapse functionality. Example, 

https://stackblitz.com/edit/vue-rhm9hw?file=src%2Fcomponents%2FHelloWorld.vue

</div>

**Comment by andrei-gheorghiu** [comment] 2023-08-23 23:08
I might have identified the cause [here](https://stackoverflow.com/a/76965237/1891677).
Next time you create a github issue which is also asked on SO, consider placing a link to the other one in each of them.

This will improve search indexing and people having the same issue will be more likely to find the answer faster.

Cheers!

**Comment by julien-deramond** [comment] 2023-08-24 05:04
Closing it since `import 'bootstrap';` instead of `import 'bootstrap/dist/js/bootstrap.bundle.min.js'` seems to do the trick in the StackBlitz reproducible link. Feel free to add comments if that's not the case.

**Closed by julien-deramond** 2023-08-24 05:04 UTC
