### ISSUE TITLE
Set 'javascript:;' or 'javascript:void(0)' to href at navigation items raises error in Angular 7+ with BS 4.2.1

### ISSUE THREAD

**Issue by feng-xiao** [twbs/bootstrap#27942] opened 2018-12-28 18:46 UTC
Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS, Win10 Mobile)
  **_Windows 10 1810_**

- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
  **_Chrome 70_**  

- [Reduced test case](https://css-tricks.com/reduced-test-cases/) and suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

I can't set **href** of navigation items to 'javascript:;' or 'javascript:void(0)' in version 4.2.1. Below is the details.
```html
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" id="navbarAdmin" href="javascript:void(0);" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin</a>
    <div class="dropdown-menu" aria-labelledby="navbarAdmin">
      ...
    </div>
  </li>
```

Got following error:
> Uncaught DOMException: Failed to execute 'querySelector' on 'Document': 'javascript:void(0);' is not a valid selector.

Error happens at following function at line 6, where it only considers '#' for non-selector value.
```javascript
 1   getSelectorFromElement: function getSelectorFromElement(element) {
 2     var selector = element.getAttribute('data-target');
 3
 4     if (!selector || selector === '#') {
 5       var hrefAttr = element.getAttribute('href');
 6       selector = hrefAttr && hrefAttr !== '#' ? hrefAttr.trim() : '';
 7     }
 8
 9     return selector && document.querySelector(selector) ? selector : null;
 10   }
```

**Comment by XhmikosR** [comment] 2018-12-29 02:46
Duplicate of #27903

**Closed** 2018-12-29 02:47 UTC
