### ISSUE TITLE
Tooltips space inconsistency when hover over

### ISSUE THREAD

**Issue by scriptsdemostack** [twbs/bootstrap#22603] opened 2017-05-11 16:29 UTC
I just noticed space inconsistency on tooltips when hover over few times on the same element. check bellow animated gif image.

<img src="http://i.imgur.com/gfxAzDm.gif">

**Comment by Johann-S** [comment] 2017-05-12 08:05
Duplicate of #22300

**Closed by Johann-S** 2017-05-12 08:05 UTC
Labels: css, v4
