### ISSUE TITLE
Add sizes or em-sizing for custom form controls

### ISSUE THREAD

**Issue by natcohen** [twbs/bootstrap#27958] opened 2019-01-01 11:58 UTC
Just like input, dropdown, pagination and button; checkbox, toggle and slider should have a class (`form-control-lg`) to increase or reduce the size.

**Comment by mdo** [comment] 2019-01-01 20:43
This will likely come in v5 with em-based sizing and consolidated form controls.

**Comment by natcohen** [comment] 2019-01-02 10:10
@mdo When is v5 release planned?

**Comment by mdo** [comment] 2019-01-02 18:39
It's our next focus after v4.3, so not too long from now I hope :).

**Comment by tmorehouse** [comment] 2019-03-01 14:17
Duplicate of #27803

**Comment by mdo** [comment] 2019-07-13 02:51
Duplicate of #27803, and also fixed in #28450.

**Closed by mdo** 2019-07-13 02:51 UTC
Labels: css, feature, v5
