### ISSUE TITLE
Make all of the classes into placeholders then hoist them when desired

### ISSUE THREAD

**Issue by jshthornton** [twbs/bootstrap#19676] opened 2016-04-06 01:47 UTC
I was thinking, a lot of people do not need all of what bootstrap has to offer. And some might want a subset of classes from a module. Take for instance if my app has no need for the outline buttons.

I am aware there are tools that exist which will scan over your site and find usage and report accordingly. But it would be a cool feature to have.

The idea is that every class definition would use the placeholder syntax, then in the variables we have a list of all classes to hoist, which we then loop over and create by extending the placeholder.

```
// _buttons.scss
%btn-outline-primary {
  ...
}

// _variables.scss
$classes-to-hoist = "btn-outline-primay", ... !default;

@each $class in $classes-to-hoist {
  .#{$class} {
    @extend %#{$class};
  }
}
```

The only pain would be maintaining this list.

Curious on other people's thoughts.

**Comment by cvrebert** [comment] 2016-04-06 01:56
Approximate duplicate of #18805.

**Closed by cvrebert** 2016-04-06 01:56 UTC
Labels: css, feature, v4
