### ISSUE TITLE
[Bootstrap 4.5] Why the class ".col" has the property "min-width: 0"?

### ISSUE THREAD

**Issue by alessandromarotta** [twbs/bootstrap#30851] opened 2020-05-19 02:34 UTC
Hello everybody!
For a rapid prototyping I'm using Bootstrap 4.5 and I have to patch the "min-width:0" property of the class ".col". 

I don't understand why and I think that it is useless and causes only problems.

Please, remove _min-width:0_ from the _.col_ class

**Comment by mdo** [comment] 2020-05-19 04:40
Duplicate of #30852

**Closed by mdo** 2020-05-19 04:40 UTC
