### ISSUE TITLE
card-img-top link IE11

### ISSUE THREAD

**Issue by NightFlash82** [twbs/bootstrap#22185] opened 2017-03-14 09:09 UTC
Bootstrap 4 alpha-6

When having a link in card-img-top and then hovering that link in IE11 the top expands in height and stays that way until refresh. Works perfectly in FF and Chrome

![bs4-error3](https://cloud.githubusercontent.com/assets/7119894/23893264/1b7be116-089e-11e7-9f71-48e5cd0589cf.jpg)

**Comment by camcam1993** [comment] 2017-03-21 09:08
Enabled package.
Custom patch available
Unmodified app
odex-file could not be found.
System Apps.

**Comment by mdo** [comment] 2017-03-28 05:28
Sounds like a dupe of #21650. Fixed with #22288.

**Closed by mdo** 2017-03-28 05:28 UTC
Labels: browser bug, css, v4
