### ISSUE TITLE
Split button dropdowns' caret is not center aligned (v4)

### ISSUE THREAD

**Issue by zhe** [twbs/bootstrap#17206] opened 2015-08-21 10:03 UTC
![screen shot 2015-08-21 at 17 53 37](https://cloud.githubusercontent.com/assets/20175/9405848/d641b6de-482d-11e5-9eab-8b145aa18313.png)
Caused by `margin-left: .25rem;`

**Comment by hnrch02** [comment] 2015-08-21 12:06
Duplicate of #17135.

**Closed by hnrch02** 2015-08-21 12:06 UTC
