### ISSUE TITLE
Floating labels in input groups

### ISSUE THREAD

**Issue by HannesWylaers** [twbs/bootstrap#36636] opened 2022-06-27 13:21 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

Regular inputs can be wrapped in a input-group. When doing this, some small css tweaks are being done e.g. setting the correct rounding on the input, increasing the z-index of the focus on the input, ...

The suggestion is to also allow floating labels to be used in an input-group.
Right now, when using a form floating input in combination with a button in an input group,
- the right-upper and right-lower corner is still rounded (when button is at end),
- the focus of the input is appearing below the button, while on regular input, the z-index is increased to 3.
![Screenshot from 2022-06-27 15-16-55](https://user-images.githubusercontent.com/15179013/175951735-8805b316-6906-449d-8be0-1ab8775c120f.png)

### Motivation and context

We are using a floating input password field in combination with a button in an input group to show/hide the password.
It's a (simple) addition on what is currently existing.

**Comment by mdo** [comment] 2022-07-19 20:36
Duplicate of #34513.

**Closed by mdo** 2022-07-19 20:36 UTC
Labels: feature, v5
