### ISSUE TITLE
forms.less incorrect parameter handover on .form-control-validation() mixin

### ISSUE THREAD

**Issue by theZieger** [twbs/bootstrap#16143] opened 2015-03-24 16:28 UTC
Hi,
I'm currently working with the available less variables and discovered that the variables `@state-info-border` and so on are not correctly handed over to the corresponding mixin `.form-control-validation()` used in `forms.less`.
Since they are available in `variables.less`, they should be used right? ;)
I discovered the bug in v3.3.2 but it's still present in tag v3.3.4.

**Comment by cvrebert** [comment] 2015-03-24 18:56
Duplicate of #14338?

**Comment by theZieger** [comment] 2015-03-24 19:22
Yep, that looks like a duplicate.
Despite @mdo answer on #14338, it doesn't seem logical to me.
If he needs it darker, couldn't this also be solved with the variables.less? Or am I wrong?
So all, who compile their one custom Bootstrap, touch the core file with each release of Bootstrap.
But if everything fails I'll solve it easily using a CSS overwrite aka bootstrap-theme.css.

**Comment by mdo** [comment] 2015-03-26 07:30
Closing as a dupe.

For now we'll leave it as-is. There's little benefit in overhauling aspects of our components like this with v4 coming. I agree it could be done better though.

**Closed by mdo** 2015-03-26 07:30 UTC
Labels: css
