### ISSUE TITLE
[BS v.3.3.5] If the text is written in All Caps, the bootstrap class ".text-capitalize" does not work.

### ISSUE THREAD

**Issue by subhban01** [twbs/bootstrap#17893] opened 2015-10-12 08:58 UTC
Create a paragraph in HTML with the text:
LOREM IPSUM DOLOR SIT AMET, CONSECTETUR ADIPISICING ELIT

Add BS class ".text-capitalize"

****************
Expected: Should convert the paragraph to sentence case, like this:
Lorem Ipsum Dolor Sit Amet, Consectetur Adipisicing Elit.

Actual:
No effect.

**Comment by patrickhlauke** [comment] 2015-10-12 09:36
I personally wouldn't expect the outcome to be as you expect it. To me at least, "capitalize" means "make sure that the first letter of every word is uppercase". If everything is already uppercase, then nothing further needs to be done. /cc @mdo

**Comment by cvrebert** [comment] 2015-10-12 18:06
Duplicate of #17672.

**Closed by cvrebert** 2015-10-12 18:06 UTC
Labels: css, feature
