### ISSUE TITLE
When add a .form-control to a date input, the height will increase unexpectedly

### ISSUE THREAD

**Issue by qiansen1386** [twbs/bootstrap#19640] opened 2016-03-30 10:25 UTC
Hi there,
I was trying out the v4-alpha and using Chrome (Haven't test for other browsers.)
I found that whenever we add .form-control class to a date tag, the control layout will mess up like this:

![image](https://cloud.githubusercontent.com/assets/1759658/14139230/5608ffb0-f6a4-11e5-887a-527f7335f51c.png)

According to the Dev tool, it is due to following media query.
![image](https://cloud.githubusercontent.com/assets/1759658/14139071/5eb96d6c-f6a3-11e5-9ef9-4ad076013374.png)

We can fix that by force the height back to 1.5rem again like other normal text input controls. 
But still, there is a 2px difference.
![image](https://cloud.githubusercontent.com/assets/1759658/14139111/a9ebf5ac-f6a3-11e5-91a9-30b945ab5f1b.png)

Is it an expected behavior? Also, how can we get around that?
O_o

**Comment by hebbet** [comment] 2016-03-30 17:14
please provide an example as noted in [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports)

**Comment by cvrebert** [comment] 2016-03-31 00:55
Assuming you're using v4.0.0-alpha.2 and not the current `v4-dev` branch, duplicate of #17308 and #18842. Please search more in the future. Thanks.

**Closed by cvrebert** 2016-03-31 00:55 UTC

**Comment by qiansen1386** [comment] 2016-03-31 02:13
So sorry... I searched but I didn't find the #18842, I thought it's new. :cry:
