### ISSUE TITLE
Card component with header and list-group inside have a thick border-top

### ISSUE THREAD

**Issue by hankir** [twbs/bootstrap#31037] opened 2020-06-15 12:55 UTC
Card component with header and list groups inside have a thick border-top. In version 4.3 works fine.

Before opening:

- [Search for duplicate or closed issues](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) - **not found**
- [Validate](https://html5.validator.nu/) and [lint](https://github.com/twbs/bootlint#in-the-browser) any HTML to avoid common problems  - **valid**
- Read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md) - **Done!**

Bug reports must include:

- Windows 10 (ver. 2004, build 19041.329)
- Microsoft Edge (ver.  83.0.478.45)
- Test case - https://codepen.io/hankir/pen/rNxMVOj or from documentation https://getbootstrap.com/docs/4.5/components/card/#list-groups

Fast fix (but i think is wrong):
.card > .list-group {
border-top: 0 !important; /* or delete border-top: inherit */
}

Broken in https://github.com/twbs/bootstrap/pull/30497

**Comment by mdo** [comment] 2020-06-15 17:01
Duplicate of #30793, fixed by #30808.

**Closed by mdo** 2020-06-15 17:01 UTC

**Comment by hankir** [comment] 2020-06-16 06:10
Thanks!
