### ISSUE TITLE
Anchor color does not update on 'bg-primary' (and bg-*)

### ISSUE THREAD

**Issue by lippuzz** [twbs/bootstrap#16265] opened 2015-04-09 11:09 UTC
When having an anchor (`<a>`) in a `<div class='bg-primairy'>`, then the text is invisible because the color does not get updated on behalf of the container bg-* class.

i would expect something like:
```css
.bg primary a{
 color: #fff;
}
```
same issue applies when using 'btn btn-link'

**Comment by zacechola** [comment] 2015-04-09 13:49
Please use back ticks for showing inline code and fencing for code blocks. [Github has a guide](https://guides.github.com/features/mastering-markdown/#syntax). 

It also helps to have a live demo as a test case. For that, you can use [this JS Bin template](http://jsbin.com/lefey/1/edit?html,output).

**Comment by zacechola** [comment] 2015-04-09 13:59
Duplicate of #12860.

Anyway, here's some extra background. The intent of the `.bg-*` helper classes is only for setting the background color. For example this is all `.bg-success` provides, simply:

```css
.bg-success {
  background-color: #dff0d8;
}
```

The one exception here is `.bg-primary` which includes  `color: #fff`. Unfortunately, specificity issues come up with anchors.

If you need to also adjust the text colors, you'll need to do so manually or use a built-in component such as an alert.

**Comment by cvrebert** [comment] 2015-04-09 17:40
What @zacechola said. The bg-* classes do exactly what their name implies, and nothing more.

**Closed by cvrebert** 2015-04-09 17:40 UTC

**Comment by lippuzz** [comment] 2015-04-10 06:21
Thanks for the background info, and sorry for not using back ticks.

The point is. Why set the color of bg-primary and leave the anchor hanging. Why not delete the color for bg-primary as well? So one way or anthor, not somewehre between the middle?
