### ISSUE TITLE
Add responsive left or right navigation

### ISSUE THREAD

**Issue by anggadarkprince** [twbs/bootstrap#19350] opened 2016-02-29 14:47 UTC
I think will be great if bootstrap gives choice how navigation getting responsive on mobile with slide-direction and some framework offer tooltips like a tour pointing element of website by sequence to help user understand web app feature or functionality of something..

**Comment by cvrebert** [comment] 2016-02-29 23:55
A "tour" feature has been rejected; see #12788.

**Comment by cvrebert** [comment] 2016-02-29 23:58
> will be great if bootstrap gives choice how navigation getting responsive on mobile with slide-direction

@anggadarkprince Are you referring to off-canvas navigation sidebars such as http://codepen.io/scottb/full/javhr/ ?

**Comment by anggadarkprince** [comment] 2016-03-01 00:47
Oh I didn't know if tour feature exist kind as bootstrap plug-ins,, 

Yes,  off - canvas navigation,  and we could determine to use both left and right either, because it gives the same experience with mobile app with touch event obviously..

**Comment by cvrebert** [comment] 2016-03-01 00:54
Duplicate of #17502 then.

**Closed by cvrebert** 2016-03-01 00:54 UTC
Labels: awaiting reply, css, feature, js, v4
