### ISSUE TITLE
Links only work once in nav-tabs dropdown menu

### ISSUE THREAD

**Issue by davidtgq** [twbs/bootstrap#21310] opened 2016-12-07 06:03 UTC
http://v4-alpha.getbootstrap.com/components/navs/#javascript-behavior

To reproduce problem:

1. click `Dropdown` > `@fat`

2. click `Dropdown` > `@mdo`

3. click `Dropdown` > `@fat`

Now both links are highlighted in primary color and neither are working.

**Comment by Starsam80** [comment] 2016-12-07 06:12
Duplicate of #17371, and see #21223 as well.

**Closed** 2016-12-07 06:15 UTC
