### ISSUE TITLE
Modal unintentionally dismissed when ending a click event outside of it to highlight text

### ISSUE THREAD

**Issue by nickalbrecht** [twbs/bootstrap#36745] opened 2022-07-15 19:23 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I'm dealing with a site I've updated from bootstrap 4.6.x to bootstrap 5.2-beta1. I'm struggling with the modal dialog because of it closing when releasing a click event outside of the dialog. Specifically anytime you are trying to click and drag to highlight text in a modal dialog to copy for use elsewhere, or highlight text in an input control to change it to something else, you have to very deliberate to not drag your mouse cursor outside of the dialog, else it will dismiss itself. Potentially losing all content/work that was in progress in the dialog (I'm loading my modal dialogs via AJAX)

Is it possible to change this behavior to only dismiss the dialog when clicking outside of the dialog, and not when ending a click event outside of it? 

Alternatively is there a customization that could be done to change this behavior on an implementation basis? I know I can disable the self dismissing behavior altogether when clicking on the backdrop, but I'd prefer to keep that functionality.

### Reduced test cases

https://web-platform-vlkvuc.stackblitz.io

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2-beta1

**Comment by nkdas91** [comment] 2022-07-16 01:43
Maybe this is a duplicate of #36394

**Comment by GeoSot** [comment] 2022-07-16 12:14
@nkdas91 nice catch, I think you are right

@nickalbrecht replace the boostrap script using this: `https://deploy-preview-36401--twbs-bootstrap.netlify.app/docs/5.2/dist/js/bootstrap.bundle.min.js` 
I suppose it will work fine. If I am correct, your issue is already solved by #36401 and will be released on 5.2 stable

**Comment by mdo** [comment] 2022-07-19 20:00
Closing as duplicate for now :).

**Closed by mdo** 2022-07-19 20:00 UTC
Labels: js, v5

**Comment by nickalbrecht** [comment] 2022-07-22 02:07
I just updated to the release of 5.2. Can confirm that the issue appears to be fixed. Apologies, I searched for other issues when I submitted this, but somehow I missed that one.
