### ISSUE TITLE
Add a "row without gutters" class

### ISSUE THREAD

**Issue by IamManchanda** [twbs/bootstrap#19107] opened 2016-02-07 07:12 UTC
There are many instances when u want the grid to don't have the gutters in it .
As it just take small 8-9 lines of code then why not 

```
.row.no-gutters {
  margin-right: 0;
  margin-left: 0;
}
.row.no-gutters > [class^="col-"],
.row.no-gutters > [class*=" col-"] {
  padding-right: 0;
  padding-left: 0;
} 
```

The SCSS/Less Version of the same 

```
.row.no-gutters {
  margin-right: 0;
  margin-left: 0;

  & > [class^="col-"],
  & > [class*=" col-"] {
    padding-right: 0;
    padding-left: 0;
  }
}
```

The scss-lint version

```
.row.no-gutters {
  margin-right: 0;
  margin-left: 0;

> [class^="col-"],
> [class*=" col-"] {
    padding-right: 0;
    padding-left: 0;
  }
}
```

Will be great if this can be added in v4 ?

**Comment by cvrebert** [comment] 2016-02-07 08:08
New features are no longer being allowed into v3.

**Comment by cvrebert** [comment] 2016-02-07 08:10
Duplicate of #15180, although that was only for v3.

**Comment by IamManchanda** [comment] 2016-02-07 09:54
Pardon that ,,, but can it be added to v4 ..
I am using this no gutter class whenever needed in my official projects from quite some time now and can tell you its a very useful method !!!
Will be a good pull request for v4 if not great!

**Comment by kevdotbadger** [comment] 2016-02-09 10:57
I think that's the point of sass. Just set the padding to 0 and recompile.

**Comment by RyanZim** [comment] 2016-05-03 21:58
Perhaps you could use the existing `.p-x-0` & `.m-x-0`.

**Comment by silvereh** [comment] 2016-08-17 20:42
I would find it super useful as well. I never thought of doing it before and created instead no-margin and no-padding classes to override the usual row behavior.

Looking at the structure of the sass files of v4, to add it should look like this:
  - in scss/mixins/_grid-framework.scss:
line 6, put gutter as 1st parameter in 
```
@mixin make-grid-columns()
```

  - in scss/_grid.scss:
change row declaration to:

```
@if $enable-grid-classes {
  .row {
    @include make-row();
  }
  .row.no-gutters {
    @include make-row(0);
    & > {
      @include make-grid-columns(0);
    }
  }
}
```

**Comment by cvrebert** [comment] 2016-08-17 21:20
CC: @mdo for feedback

**Comment by IamManchanda** [comment] 2016-09-24 14:38
+1 @silvereh

**Comment by IamManchanda** [comment] 2016-09-24 14:53
@mdo @cvrebert 
Just wanna say me and my company is using this from around a year and this works like wonders and can be a good feature if its gets added up for Bootstrap 4

**Comment by spdpiyush** [comment] 2016-09-24 17:44
Waiting For The V4

**Comment by IamManchanda** [comment] 2016-11-01 11:04
@silvereh - I am not very good in sass ( at the moment ) ... so can you please do a pull request for the same

**Comment by silvereh** [comment] 2016-11-02 16:53
@IamManchanda 
OK, I'll try. Though it's my first open source contribution and I'm not too confident with it so it might take me a bit of time.

**Comment by IamManchanda** [comment] 2016-11-04 08:04
@silvereh 
You can try this [Tutorial](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) for the same

**Comment by garygreen** [comment] 2016-11-18 15:22
+1 this really should be built into bootstrap. At the moment you cannot use the grid system without adding gutters (except with the `.no-gutter` class snippet as posted above). Would be nice to see this baked in

**Closed** 2016-11-26 20:13 UTC
Labels: css, feature, has-pr, v4

**Comment by SimonDegraeve** [comment] 2016-12-22 05:02
I think the specificity of `.no-gutters` is not high enough. It get overwritten by the `margin` in the media queries.

The margin properties of `.no-gutters` should be marked as `important` or the selector should be `.col.no-gutters`.

**Comment by IamManchanda** [comment] 2016-12-24 17:11
@SimonDegraeve if you have to ask me, i will go with `.row.no-gutters` as using `!important` is not the best option in this specific scenario
