### ISSUE TITLE
Modals with .fade class doesn't trigger shown or hidden event

### ISSUE THREAD

**Issue by DaSchTour** [twbs/bootstrap#16284] opened 2015-04-14 11:24 UTC
I discovered that modals with the .fade class don't trigger the shown and hidden event only the show and hide event. I think this is a major problem, as the shown and hidden event make most sense for modals with the .fade class.

**Comment by Johann-S** [comment] 2015-04-14 14:39
Please post a JS Bin example of the problem.

**Comment by cvrebert** [comment] 2015-04-14 19:36
@DaSchTour Unable to reproduce with http://jsbin.com/fimiru/1/edit . All 4 events are logged as expected when opening and then closing the modal.
Happy to reopen if you post a counterexample though.

**Comment by DaSchTour** [comment] 2015-04-15 07:36
Here it is: http://jsbin.com/mirohizepu/1/

**Comment by twbs-lmvtfy** [comment] 2015-04-15 07:36
Hi @DaSchTour!

You appear to have posted a live example (http://jsbin.com/mirohizepu/1/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 19, column 1 thru line 19, column 115: The ```` aria-labelledby ```` attribute must point to an element in the same document.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment] 2015-04-15 08:16
I get a `hidden` event, but indeed no `shown` event.
Presumably this is because the `$dialog` reference to the `.modal-dialog` is initialized in the Modal constructor and not set again anywhere else.

**Comment by Johann-S** [comment] 2015-04-15 12:02
The event ``bsTransitionEnd`` never triggered so the modal cannot fire ``shown.bs.modal`` event.

https://github.com/twbs/bootstrap/blob/master/js/modal.js#L102

**Comment by fat** [comment] 2015-04-25 20:09
The modal plugin wasn't designed to have it's dialog disposed of in the way done by your jsbin.

We can consider changing this for v4 - but i don't see a lot of value in changing this in v3.

Meanwhile, just don't kill the modal-dialog :)

**Closed by fat** 2015-04-25 20:09 UTC
Labels: confirmed, js

**Comment by DaSchTour** [comment] 2015-04-27 13:35
Don't kill the modal-dialog? Our developers have seen this as the only manageable way to use modals with AJAX content. I get the impression that bootstrap was designed for static HTML pages and nobody took care of the usability within Server-Driven AJAX-Web-Application. For whom do you create such a Framework that only makes problems when used in a real world?

**Comment by Johann-S** [comment] 2015-04-27 16:00
I think you can do the same as you wanted to do but let the ``.modal-dialog`` and add your content in the ``.modal-content``. I think it's the right way to full fill a modal with Ajax

**Comment by DaSchTour** [comment] 2015-05-04 14:06
That's not true. If you want to change the width of a modal you would need to add additional JavaScript that changes the .modal-dialog instead of just loading .modal-dialog with the wanted size.
