### ISSUE TITLE
Incorrect size of modal on iPad

### ISSUE THREAD

**Issue by ldesmeules** [twbs/bootstrap#19382] opened 2016-03-03 13:32 UTC
If the size of container is more little than modal, the modal is not visible correctly.
A demo here : 
http://www.kalaninformatique.fr/modal/demo.html

Test with windows 7 : IE, Firefox, Safari, Chrome => no problem
Test with Samsung Galaxy : Chrome => ok
Test with ipad : Firefox, chrome and Safari =>** BUG**

Tested in v4 : same problem

**Comment by ldesmeules** [comment] 2016-03-03 14:55
Tested with v4, the same problem.

**Comment by cvrebert** [comment] 2016-03-03 23:29
@ldesmeules 
* What version of iOS are you using?
* What model of iPad are you using?
* Could you post a screenshot of the problem?

**Comment by ldesmeules** [comment] 2016-03-04 09:09
iOS 9.2.1 Ipad2
![computer](https://cloud.githubusercontent.com/assets/14937513/13522674/2eae0f9a-e1f1-11e5-9405-6e74814bfaa8.jpg)
![ipad](https://cloud.githubusercontent.com/assets/14937513/13522675/2eafe6bc-e1f1-11e5-9dc2-cdd1b23b702b.jpg)
![phonesamsung](https://cloud.githubusercontent.com/assets/14937513/13522676/2eb1be4c-e1f1-11e5-83c1-0ae2c3c51128.jpg)

**Comment by ldesmeules** [comment] 2016-03-04 09:12
IOS 9.2.1 Ipad2
On computer:
![computer](https://cloud.githubusercontent.com/assets/14937513/13522728/8d59eb68-e1f1-11e5-8815-2387505bb3f3.jpg)
On phone samsung
![phonesamsung](https://cloud.githubusercontent.com/assets/14937513/13522736/9afbedd4-e1f1-11e5-9100-8b717a395136.jpg)
BUG on IPAD2: 
![ipad](https://cloud.githubusercontent.com/assets/14937513/13522741/a38ed998-e1f1-11e5-9405-0503c5c5926a.jpg)

**Comment by cvrebert** [comment] 2016-03-04 09:24
Apparent duplicate of https://bugs.webkit.org/show_bug.cgi?id=150715

**Closed by cvrebert** 2016-03-04 09:24 UTC
Labels: browser bug, confirmed, css, v3, v4
