### ISSUE TITLE
modal cause carousel shift

### ISSUE THREAD

**Issue by dotku** [twbs/bootstrap#17615] opened 2015-09-16 08:26 UTC
Bootstrap: modal.js v3.3.5

Here is what I have

![qq 20150916011959](https://cloud.githubusercontent.com/assets/1519232/9899826/4429fb7e-5c11-11e5-968f-44cc9d7baf3e.png)

my solution is just remove two lines:

	  Modal.prototype.setScrollbar = function () {
		var bodyPad = parseInt((this.$body.css('padding-right') || 0), 10)
		this.originalBodyPad = document.body.style.paddingRight || ''
		// 
	  }

	  Modal.prototype.resetScrollbar = function () {
		// 
	  }

**Comment by cvrebert** [comment] 2015-09-16 18:24
Duplicate of #17399. Please search existing issues more in the future.

**Closed by cvrebert** 2015-09-16 18:24 UTC
