### ISSUE TITLE
.visible-xx isn't compatible with .btn-group-justified

### ISSUE THREAD

**Issue by slorenzo** [twbs/bootstrap#18737] opened 2015-12-31 23:35 UTC
Hi,
I tried use a ```.btn-group-justified``` component with ```.visible--xx``` class but this class dont have a option with ```display: table-cell !important```.

I used this media query for mobile view and work fine but it would be very good to include a similar class on bootstrap
```
@media (max-width: 767px){
    .btn-group-justified .visible-xs{
        display: table-cell !important;
    }
}
```

Happy new year!

**Comment by cvrebert** [comment] 2016-01-01 03:38
Duplicate of #14662.

**Closed by cvrebert** 2016-01-01 03:38 UTC
