### ISSUE TITLE
Close button color cannot be changed to light mode when a parent has [data-bs-theme="dark"]

### ISSUE THREAD

**Issue by erdnaxe** [twbs/bootstrap#39563] opened 2024-01-04 12:56 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

As written in the documentation (https://getbootstrap.com/docs/5.3/customize/color-modes/#example) :
> For example, **to change the color mode** of a dropdown menu, add data-bs-theme="light" or data-bs-theme="dark" to the parent .dropdown. Now, **no matter the global color mode, these dropdowns will display with the specified theme value.**

I would expect `.btn-close` elements to also abide to this rule, but adding `[data-bs-theme="light"]` to the `.btn-close` or any parent element does not change its color to light mode if any previous parent has `[data-bs-theme="dark"]`.

I believe the code responsible for this issue is <https://github.com/twbs/bootstrap/blob/v5.3.2/scss/_close.scss#L58-L62>

#### Dirty fix for Bootstrap 5.3.2

I use the deprecated `.btn-close-white` and add a custom `.btn-close-dark` class:
```CSS
.btn-close-dark, [data-bs-theme="dark"] .btn-close-dark {
  filter: none;
}
```
This allows me to force the right color to the close buttons, regardless if the page is in light or dark mode.

### Reduced test cases

```html
<div class="toast-container position-fixed top-0 end-0 p-3 mt-5" data-bs-theme="dark">
  <div id="example" class="toast align-items-center text-bg-warning show" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="10000">
    <div class="d-flex" data-bs-theme="light">
      <div class="toast-body">Example</div>
      <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
  </div>
</div>
```
If you remove `data-bs-theme="dark"`, then the close button respect `data-bs-theme="light"`.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.3.2

**Comment by mdo** [comment] 2024-01-08 23:51
Duplicate of #39481 I think.

**Closed by mdo** 2024-01-08 23:51 UTC
Labels: css, v5, color mode
