### ISSUE TITLE
Wrong event var in Modal

### ISSUE THREAD

**Issue by WinterSilence** [twbs/bootstrap#19118] opened 2016-02-08 00:37 UTC
https://github.com/twbs/bootstrap/blob/master/dist/js/bootstrap.js#L1053

Var  `event` is not defined, `document !== event.target` replace to `document !== e.target`

**Comment by cvrebert** [comment] 2016-02-08 00:57
Duplicate of #18908. Please search more in the future. Thanks.

**Closed by cvrebert** 2016-02-08 00:57 UTC
Labels: js, v3
