### ISSUE TITLE
modal-backdrop class missing bottom value

### ISSUE THREAD

**Issue by Tarhan** [twbs/bootstrap#15950] opened 2015-03-01 02:45 UTC
Issue only for 3.3.1 and 3.3.2 version (3.3.0 is corrent)
This snippet from bootstrap.css#3.3.2 (lines 5752-5758):
.modal-backdrop {
  position: absolute;
  top: 0;
  right: 0;
  left: 0;
  background-color: #000;
}
Line "bottom: 0;" is missing in css and less files.
Because of this background of modal windows is not semi-transparent, it is just transparent.

**Comment by cvrebert** [comment] 2015-03-01 03:31
Duplicate of #15345 & friends. Please search more next time.

**Closed by cvrebert** 2015-03-01 03:31 UTC
