### ISSUE TITLE
Toggleable navbars do not transition on collapse

### ISSUE THREAD

**Issue by davidjb** [twbs/bootstrap#18868] opened 2016-01-13 04:06 UTC
Looking at the v4 documentation page for Navbars (http://v4-alpha.getbootstrap.com/components/navbar/#collapsible-content), the first collapsible content example smoothly transitions on close, but the responsive navbar (second example) collapses immediately without a transition.

Example showing with and without a clearfix: http://codepen.io/davidjb/full/NxvxGe/

The issue (assuming unintentional) appears to be related to the floats within the `.collapse` element.  With only floated elements inside (eg `.navbar-brand` and `.nav-item`), the transition occurs on open, but not on close.  By adding something like a `.clearfix` to the `collapse navbar-toggeable-*`, the issue is worked around.

The same results are seen in my testing under Firefox 45a2 and Chromium 47.0.2526.73 on Ubuntu 15.10.

**Comment by twbs-lmvtfy** [comment] 2016-01-13 04:06
Hi @davidjb!

You appear to have posted a live example (http://codepen.io/davidjb/pen/NxvxGe.html), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 9, column 1: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`
* line 35, column 1: [W012](https://github.com/twbs/bootlint/wiki/W012): `.navbar`'s first child element should always be either `.container` or `.container-fluid`

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by davidjb** [comment] 2016-01-13 04:11
Fwiw, to the @twbs-lmvtfy comments, I just copied the navbar example provided in the v4 documentation, which doesn't contain a `.container`.

**Comment by cvrebert** [comment] 2016-01-13 05:16
Yeah, ignore the bot; its v4 detection heuristic needs some work (https://github.com/twbs/bootlint/issues/337).

**Comment by mdo** [comment] 2016-07-24 07:47
Closing as dupe of #17990.

**Closed by mdo** 2016-07-24 07:47 UTC
Labels: css, v4
