### ISSUE TITLE
Please add bootstrap.css to bower.json

### ISSUE THREAD

**Issue by camposer** [twbs/bootstrap#16926] opened 2015-08-03 09:22 UTC
Guys,

I think you forgot to include "dist/css/bootstrap.css" in your bower.json's main section. I'm using yeoman with grunt and it considers this to include the css in its unique vendor.css.

Regards,

Rodolfo.

**Comment by cvrebert** [comment] 2015-08-03 09:24
We didn't forget; it's deliberate.
Duplicate of #16663.

**Closed by cvrebert** 2015-08-03 09:24 UTC
