### ISSUE TITLE
Transition issue at loading with chrome

### ISSUE THREAD

**Issue by gsouf** [twbs/bootstrap#22014] opened 2017-02-16 16:03 UTC
Hi, just spotted a bug with **bootstrap 4 alpha 6** and chrome only. The bug does not happen on both of firefox and IE. I actually tested on **chromium (v55) for linux** and **chrome for windows (v55)**.

## What is the bug?

When loading a page that contains both of a button and an input, and that does not contain javascript, the button will appear with a transition (size, backgroun color and color have a transition from initial state to the bootstrap style).
 I didn't test it much, I might be wrong on the exact conditions for the bug to happen

I could not provide a fiddle because fiddlejs injects some codes that break the conditions.
Here are 3 sample to reproduce and fixe the bug:

### Case 1: button alone [WONT have the issue]

````html
<!DOCTYPE html>
<html lang="fr">
	<head>
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
	</head>
	<body>
		<button class="btn btn-primary" role="button" type="submit">Connexion</button>
	</body>
</html>
````

### Case 2: we added an input on the page [WILL have the issue]

````html
<!DOCTYPE html>
<html lang="fr">
	<head>
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
	</head>
	<body>
		<button class="btn btn-primary" role="button" type="submit">Connexion</button>
		<input type="text">
	</body>
</html>
````

### Case 3: we added a script on the page [NO MORE issue]

````html
<!DOCTYPE html>
<html lang="fr">
	<head>
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">
	</head>
	<body>
		<button class="btn btn-primary" role="button" type="submit">Connexion</button>
		<input type="text">
                <script>
			var foo = "foo";
		</script>
	</body>
</html>
````

Please note that no matter the order  of the elments the bug will happen: the script might be at the beggining of the document or at the end, the button might be before the input or after or in parent elements, etc...

As I said that might be a bug with chrome itself that would show the DOM before it loads the CSS, I also opened an issue on the chromium side

**Comment by gsouf** [comment] 2017-03-30 10:00
This is confirmed as a bug in chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=693088

**Comment by Johann-S** [comment] 2017-03-30 11:12
I reopen the issue because we have to add this issue to the browser bug page

**Comment by gsouf** [comment] 2017-03-30 11:17
Ok, but note that the condition to reproduce the bug are very special and this bug should be extremly rare!

**Comment by danawoodman** [comment] 2017-05-07 06:50
I can confirm adding an empty script tag solves this issue for me

**Comment by danawoodman** [comment] 2017-05-07 06:52
Ok, this is even weirder... If an input has a value, the issue shows up. If the input is empty it does not. Bizarre...

**Comment by gsouf** [comment] 2017-05-07 09:11
@danawoodman  as I said the bug is confirmed on chrome side

**Comment by danawoodman** [comment] 2017-05-07 16:24
Looks like they're waiting for a reply from the submitter. Also, my point about input field contents seems relevant to the issue

**Comment by mdo** [comment] 2017-07-02 05:41
What's the status on this one? Still need to add a bug to our docs?

**Comment by gsouf** [comment] 2017-07-02 10:17
@mdo 
That's not fixed on chrome's side for the moment

**Comment by patrickhlauke** [comment] 2017-07-02 21:54
https://bugs.chromium.org/p/chromium/issues/detail?id=709718

**Comment by stealth-swift** [comment] 2020-01-12 03:37
Currently, Chrome on Windows 10 is at Version 79.0.3945.117. The previously detailed chromium bug reported id=709718 has been closed out as of 4th December 2019 as deemed working. Is this now resolved and if so, close of issue here?

**Comment by MartijnCuppens** [comment] 2020-01-14 09:20
Closing this per @stealth-swift's comment

**Closed by MartijnCuppens** 2020-01-14 09:20 UTC
Labels: browser bug, js, v4
