### ISSUE TITLE
Add sticky table header

### ISSUE THREAD

**Issue by martenlehmann** [twbs/bootstrap#19681] opened 2016-04-06 22:56 UTC
Sticky table headers are a key concept on all mobile platforms. Since the display sizes are quite small, you usually can't see the table header any more if the height of the table is bigger than the height of the screen. The project [stickyRows](http://maslianok.github.io/stickyRows/default.html) gives a good demonstration of what I mean.

This project is a bit too complicated though, because it includes handling of different types of table headers and stacking of those. What I think should really be part of Bootstrap 4, is a class like `.table-sticky-header` (similarly to `.navbar-fixed-top`) that you can add to each `.table` and then Bootstrap does the rest and always keeps the current `<thead>`-section on the top until the last row scrolled to the top or the next `<thead>`-section goes up.

**Comment by cvrebert** [comment] 2016-04-06 22:59
Duplicate of #19546.

**Closed by cvrebert** 2016-04-06 22:59 UTC
Labels: css, feature, v4
