### ISSUE TITLE
SSL cert for maxcdn.bootstrapcdn.com shows GlobalSign Intermediate CA revoked

### ISSUE THREAD

**Issue by leecookson** [twbs/bootstrap#20895] opened 2016-10-13 14:27 UTC
This URL, for example:

https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css

Common Name:  GlobalSign Domain Validation CA - SHA256 - G2

This Certificate has been revoked.

The Root CA is fine, and my test shows Chrome 54 (on OSX El Capitan) indicates on the Security tab of the debugger that "This page is secure (valid HTTPS), and "The connection to this site is using a valid, trusted server certificate".

When you drill into the cert, you see the issue with the intermediate cert, and a colleague of mine (maybe with different security settings) if blocked from using a tool that loads the URL above.

**Comment by leecookson** [comment] 2016-10-13 14:43
I heard the issue blows up pages that use maxcdn.bootstrapcdn.com for Chrome 43 on the beta channel.   "live" channel version 54 still treats it as secure.

**Comment by mdo** [comment] 2016-10-13 17:44
Pinging @jdorfman

**Comment by jdorfman** [comment] 2016-10-13 18:05
Hey all. We are working with our SSL provider to figure out what is happening: https://status.maxcdn.com/incidents/gfyr7b9flzxs

Will update once I know more.

**Comment by jdorfman** [comment] 2016-10-13 18:07
@leecookson @mdo looks to be working now. We are keeping a close eye on it: https://www.ssllabs.com/ssltest/analyze.html?d=maxcdn.bootstrapcdn.com

**Comment by jdorfman** [comment] 2016-10-13 18:33
Update: apparently this is a lot worse than I thought. I was going by the "works for me" method which is stupid. 

Here is statement from our SSL provider: https://downloads.globalsign.com/acton/fs/blocks/showLandingPage/a/2674/p/p-008f/t/page/fm/0

We are working on a solution for those who are affected.

**Comment by jdorfman** [comment] 2016-10-13 19:06
Update 2: We are purchasing a new SSL certificate format from a new vendor.

**Comment by cvrebert** [comment] 2016-10-13 21:43
Duplicate of https://github.com/MaxCDN/bootstrap-cdn/issues/779

**Comment by jdorfman** [comment] 2016-10-13 21:57
Update 3: Moving a lot slower than usual. Will update asap.

FWIW this is what happened: http://www.theregister.co.uk/2016/10/13/globalsigned_off/

**Comment by jdorfman** [comment] 2016-10-14 00:02
Update 4: We believe everything is back to normal. If you run into anymore issues please email support-at-maxcdn.com

**Comment by geoffhumphrey** [comment] 2016-10-14 15:43
Is this issue related? https://github.com/MaxCDN/bootstrap-cdn/issues/780

**Comment by jdorfman** [comment] 2016-10-14 15:47
@geoffhumphrey don't think so, check MaxCDN/bootstrap-cdn#780

**Comment by mdo** [comment] 2016-10-14 16:06
Thanks @jdorfman & team! <3

**Closed by mdo** 2016-10-14 16:06 UTC
