### ISSUE TITLE
navbar-toggler-icon-bg not in dark mode when data-bs-theme is directly set on navbar

### ISSUE THREAD

**Issue by stijn7621** [twbs/bootstrap#38190] opened 2023-03-07 13:38 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When setting data-bs-theme to dark on the navbar element, the toggler icon will show up in black instead of white. If you set it on the parent, it will show the white color as expected.

### Reduced test cases

.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Safari, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

5.3.0-alpha1

**Comment by Blueclaus13** [comment] 2023-03-08 04:29
Could I participate in this issue?

**Comment by vaish567** [comment] 2023-03-10 09:55
> ### Prerequisites
> * [x]  I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
> * [x]  I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
> * [x]  I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)
> 
> ### Describe the issue
> When setting data-bs-theme to dark on the navbar element, the toggler icon will show up in black instead of white. If you set it on the parent, it will show the white color as expected.
> 
> ### Reduced test cases
> .
> 
> ### What operating system(s) are you seeing the problem on?
> Windows
> 
> ### What browser(s) are you seeing the problem on?
> Chrome, Safari, Firefox, Microsoft Edge, Opera
> 
> ### What version of Bootstrap are you using?
> 5.3.0-alpha1

+1

**Comment by mdo** [comment] 2023-03-10 17:51
Duplicate of #37760.

**Closed by mdo** 2023-03-10 17:51 UTC
Labels: css, v5, color mode
