### ISSUE TITLE
In Firefox, Dropdown Menus in `btn-group`s with items wider than the button that triggers them have overflowing content

### ISSUE THREAD

**Issue by dfoverdx** [twbs/bootstrap#25026] opened 2017-12-16 21:54 UTC
If a dropdown menu is contained in a `.btn-group`, and its content is wider than the button that triggers it, the width the of the menu reverts to the menu's `min-width` value, which is currently `160px`.  This issue appears to be browser-specific; it works fine in Chrome and Edge, but breaks in Firefox.

The issue appears to be the `.btn-group`'s `position: relative` style.  Changing this to `position: static` fixes the issue.  Granted, I'm sure `.btn-group`'s position needs to be `relative` for other reasons, but it breaks wide dropdown menus in Firefox.

[Repro example](https://codepen.io/dfoverdx/pen/VyvBQG)

![image](https://user-images.githubusercontent.com/3087358/34074061-4f4fc8ac-e25c-11e7-9015-bbd81c0d0526.png)

**Comment by jxmai** [comment] 2017-12-17 16:53
Hi, i tried your sample in FF quantum but I couldn't replicate the issue

![snapshot1](https://user-images.githubusercontent.com/10467831/34081792-67d9d4a0-e318-11e7-84aa-13ea413061e7.png)

**Comment by Johann-S** [comment] 2017-12-18 08:38
You can use our `.position-static` class to fix your issue see : https://getbootstrap.com/docs/4.0/utilities/position/#common-values

See my CodePen : https://codepen.io/Johann-S/pen/EoPWVE

Can you specify which release of Firefox ?

**Comment by dfoverdx** [comment] 2017-12-20 21:45
I'm using Firefox ESR v52.5.2 (64-bit).  I don't actually know what ESR is (I installed FF a long time ago and never use it), so maybe that's my issue.

**Comment by jxmai** [comment] 2017-12-20 22:10
FF v57 should work well in this case.

**Comment by Johann-S** [comment] 2017-12-21 08:45
I'm unable to reproduce it in FF 52 :thinking:

**Comment by mdo** [comment] 2017-12-27 22:58
Closing since we cannot reproduce in latest FF.

**Closed by mdo** 2017-12-27 22:58 UTC
Labels: css, v4
