### ISSUE TITLE
Custom Checkbox Printing Issue

### ISSUE THREAD

**Issue by scottkuhl** [twbs/bootstrap#28483] opened 2019-03-13 20:53 UTC
Formatting of a custom checkbox in Bootstrap 4.3.1 is not working. 

Chrome: it is not shown at all when checked or shows only an outline when not checked.
Edge: boxes are always unchecked.
Firefox: it is not shown at all when checked or shows only an outline when not checked.
IE11: boxes are always unchecked.

Example:

```
<div class="custom-control custom-checkbox">
  <input class="custom-control-input" type="checkbox" checked />
  <label class="custom-control-label">This is checked.</label>
</div>
<div class="custom-control custom-checkbox">
  <input class="custom-control-input" type="checkbox" />
  <label class="custom-control-label">This is not checked.</label>
</div>

```

- Operating system and version: Windows 10 1709
- Browser and version: Google Chrome Version 72.0.3626.121 (Official Build) (32-bit)
- Browser and version: Microsoft Edge 41.16299.967.0
- Browser and version: Mozilla Firefox Version 60.5.1esr (32-bit)
- Browser and version: Internet Explorer Version 11.967.16299.0
- https://codepen.io/scottkuhl/pen/mopKQE

**Comment by jipexu** [comment] 2019-03-14 14:47
you need an id for your input and a for attribut for your label  ... to work

**Comment by scottkuhl** [comment] 2019-03-14 15:07
> you need an id for your input and a for attribut for your label ... to work

I have updated the codepen based on your suggestion and it did not make a difference.

**Comment by jipexu** [comment] 2019-03-14 15:48
it's work for me with YOUR fiddle ???

**Comment by mdo** [comment] 2019-03-14 16:00
The problem is with printing, correct? This is likely due to printing with background-images disabled in the browser's print dialog.

**Comment by scottkuhl** [comment] 2019-03-14 16:10
> The problem is with printing, correct? This is likely due to printing with background-images disabled in the browser's print dialog.

Yes, that is the issue.  I would assume that is going to be a common problem for a lot of users.  Should Bootstrap be rendering these some other way when printing by default?  Such as reverting back to the browser defaults?

**Comment by jipexu** [comment] 2019-03-14 17:28
oups sorry i was outside the answer ...(dont see printing ...)

**Comment by patrickhlauke** [comment] 2019-03-15 15:48
even though in future we're likely to scale back/drop print support, this is something that should be tackled as we don't want things outright broken. easiest here would likely be to drop the customisation in print media and just display the regular checkbox at least

**Comment by XhmikosR** [comment] 2019-05-11 09:59
PRs welcome which target v4-dev.

**Comment by mdo** [comment] 2020-05-14 17:27
Closing since #29714 was merged months ago.

**Closed by mdo** 2020-05-14 17:27 UTC
Labels: print, v4

**Comment by XhmikosR** [comment] 2020-05-14 18:10
@mdo it seems #29714 was never backported though.

@MartijnCuppens please backport #29714 to the v4-dev-xmr branch
