### ISSUE TITLE
Adding new popover positions

### ISSUE THREAD

**Issue by SMHFandA** [twbs/bootstrap#16895] opened 2015-07-27 16:41 UTC
Hi, guys. I have suggestions relatively popover positions: top-left, top-right, bottom-left, bottom-right. Something like this

![popover-bottom-left-position](https://cloud.githubusercontent.com/assets/5597196/8911832/70552ed6-3497-11e5-94ca-e8e3e71dfad3.png)

Thanks.

**Comment by kkirsche** [comment] 2015-07-27 17:14
V3 is feature frozen due to V4 alpha coming out next month. In V4 bootstrap is switching o a third party positioning library to simplify the core. Thanks for the suggestion though!

**Comment by cvrebert** [comment] 2015-07-27 20:13
Approximate duplicate of #12166.

**Closed by cvrebert** 2015-07-27 20:13 UTC
