### ISSUE TITLE
A dropup-toggle class for buttons?

### ISSUE THREAD

**Issue by bhutaninitin** [twbs/bootstrap#17909] opened 2015-10-13 12:52 UTC
In http://v4-alpha.getbootstrap.com/components/button-dropdown/#dropup-variation, dropdown-toggle on button looks counter-intuitive to me. I think it should be up arrow for dropups.

**Comment by dkfiresky** [comment] 2015-10-13 13:06
@bhutaninitin :+1: 
Current behavior:
if button is placed on bottom of the screen and `.dropdown-menu` have no space to open down, then `.dropdown-menu` should open up and the arrow in this case should be down.

Something like `.dropdown-toggle-up` and `.dropdown-toggle-down` would be great for modifying arrow direction and it solves this issue.

**Comment by tshinnic** [comment] 2015-10-20 22:19
I think this was fixed by PR #17147 as a consequence of #17144 . While still broken on v4-alpha web site, the problem is 'fixed' on web site generated with recent sources.  

Close this as dup of closed #17144 ?

**Closed** 2015-12-08 08:13 UTC
Labels: css, v4
