### ISSUE TITLE
Tooltip bug when hovering child node

### ISSUE THREAD

**Issue by vmcr** [twbs/bootstrap#32880] opened 2021-01-23 13:00 UTC
Having a bunch of elements builded in this way:

```
<button type="button" class="btn btn-primary px-3 hasTooltip" title="Tooltip text" data-toggle="tooltip">
    <i class="fas fa-user m-0"></i>                                
</button>

<button type="button" class="btn btn-primary px-3 hasTooltip" title="Other tooltip text" data-toggle="tooltip">
    <span>Any child element</span>                                
</button>
```

So when I hover a tootlip target it shows the tooltip nicely. The problem is when I hover any child element of that tooltip element.

The element suddenly dissapears or is being repositioned at the top left corner of the view, breaking the entire behaviour of this Bootstrap component. No matters if it is an icon or a simply span node.

This issue isn't reproducing in earlier versions of Bootstrap.

**Comment by bpobocha** [comment] 2021-01-23 13:46
You can add 'pointer-events: none' to all elements inside the button. It helped me.

`button *{
    pointer-events: none;
  }`

**Comment by Chipsum** [comment] 2021-01-23 15:06
I totally agree

Tooltips are not working well with v5

**Comment by joeforjoomla** [comment] 2021-01-23 16:54
Tooltips are not working well with BS5. If you try to enter/exit the mouse over a certain element even without any child node, the tooltip vanishes. This incorrect behavior can be seen also on the demo page using the latest Chrome: https://getbootstrap.com/docs/5.0/components/tooltips/

Definitely tooltips/popovers not working consistently with Popper 2 in BS5

**Comment by vmcr** [comment] 2021-01-23 19:35
> 
> 
> You can add 'pointer-events: none' to all elements inside the button. It helped me.
> 
> ```
> button *{
>     pointer-events: none;
>   }
> ```

Well it works and I would get it running like this, but still I don't think this is the proper way to do it.

It's a bug that should be fixed in the internal code of the next release. That's why I posted here.

**Comment by Chipsum** [comment] 2021-01-23 20:39
@joeforjoomla 
Exactly.
Especially if you hover over the SVG example then scroll down the tooltip stays there forever.

**Comment by joeforjoomla** [comment] 2021-01-23 22:56
@Chipsum yes indeed, I'm working intensively with tooltips and popovers, but as of now they are unusable.
Moreover with BS5 it seems that it's no longer possible to have a tooltip AND a popover on the same element as i was used to do with BS2/3/4

**Comment by XhmikosR** [comment] 2021-01-25 10:34
Duplicate of #31646

**Closed by XhmikosR** 2021-01-25 10:34 UTC
