### ISSUE TITLE
Navbar containers lose padding too soon

### ISSUE THREAD

**Issue by jonsa** [twbs/bootstrap#21735] opened 2017-01-15 13:11 UTC
When the navbar turns toggleable the brand is 15px left of the content.

See http://jsfiddle.net/2t6e0ryh/

![image](https://cloud.githubusercontent.com/assets/807381/21962683/2bac6168-db2c-11e6-9887-a829419ffd59.png)

![image](https://cloud.githubusercontent.com/assets/807381/21962686/42e956f6-db2c-11e6-8f64-d1878c42844b.png)

**Comment by vanduynslagerp** [comment] 2017-01-15 14:56
I think it's a duplicate of #21659. Which is fixed by #21729.

**Comment by vanduynslagerp** [comment] 2017-01-15 22:22
Oh right! I misread and thought you were talking about the toggle button, but it was the brand.
This is due to these lines [_navbar.scss#L134](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L134). It explicitly reset the padding of the container within a navbar when it turn toggleable.
I imagine it's a design choice from the bootstrap team ?

**Comment by AlessandroVecchi** [comment] 2017-01-25 11:16
![senza-titolo-1](https://cloud.githubusercontent.com/assets/20642463/22288591/e50c88c2-e2f7-11e6-8e39-84594d19d182.png)

Why the navbar brand and the toggle button are centered at lowest viewports?
I think it is a bug!

You can see the same problem in the bootstrap docs.

![cattura](https://cloud.githubusercontent.com/assets/20642463/22288465/4195ef58-e2f7-11e6-9b86-1cbdd714730f.JPG)

**Comment by wolfhoundjesse** [comment] 2017-01-30 21:32
@AlessandroVecchi The padding goes away at lower breakpoints, but the `margin-left: auto` and `margin-right: auto` do not. This causes your brand to appear centered.

For now I've nested the brand in the collapsible div, but I'm open to suggestions for fixing the margins as well.

**Comment by AlessandroVecchi** [comment] 2017-01-31 08:03
I added this class to the .container.

`@media (max-width:543px) {
	.fixbugbsalpha6 { width: 100%;}
}`

**Comment by mdo** [comment] 2017-03-21 04:42
Have a fix for this inbound. Demo at http://jsfiddle.net/2t6e0ryh/7/.

**Closed** 2017-03-24 06:02 UTC
Labels: css, has-pr, v4

**Comment by jonsa** [comment] 2017-03-24 08:23
Sorry about the late the response but the solution is rather inconsistent, is it not?

On large screens the content in the navbar align with the sides of the content.
![image](https://cloud.githubusercontent.com/assets/807381/24285977/2dcbd042-1073-11e7-97cb-df408a768d92.png)

On smaller screens it's outside
![image](https://cloud.githubusercontent.com/assets/807381/24285995/4513f7f2-1073-11e7-9787-044547e6d02a.png)

To go back to aligned again on really small devices
![image](https://cloud.githubusercontent.com/assets/807381/24286016/5cbcb95c-1073-11e7-896a-3aabcf2c604f.png)
