### ISSUE TITLE
Bootstrap POPOVER not updating content but run function placed as content

### ISSUE THREAD

**Issue by blaskognia** [twbs/bootstrap#35677] opened 2022-01-10 21:00 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

In options of popover you can setup CONTENT as plaintext / html or you can use function.

This function is run every time when element is clicked but content never update.

For example i have something like this

var testnumber = 0;

And as CONTENT (in options of popover) i have something like this:

function () { testnumber++; console.log(testnumber); return testnumber; }

And when element is clicked JS console said that testnumber every time is increase by one BUT content of popover still have 1.

### Reduced test cases

I don't have fix for that

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5

**Comment by ffoodd** [comment] 2022-01-11 05:55
Please provide a reduced test case of the bug on CodePen so that we can figure out what's happenning.

**Comment by ffoodd** [comment] 2022-01-11 05:56
And isn't this issue a duplicate of #35029?

**Comment by blaskognia** [comment] 2022-01-11 08:27
@ffoodd sorry, you are right #35029 is the same topic and have example of issue.

**Comment by blaskognia** [comment] 2022-01-11 08:28
@ffoodd this is very important because by that issue we cant create huuuuuge functionality like dynamic menus, elements that change by user actions etc.

It's like some delete click event from js. In my opinion this is critical bug.

**Comment by ffoodd** [comment] 2022-01-11 08:32
I'm more concern by the fact it used to work ans doesn't anymore. I'm closing this one as duplicate and encourage you to follow up #35029.

Thanks!

**Closed** 2022-01-11 08:32 UTC
Labels: awaiting-reply
