### ISSUE TITLE
V4 SCSS inclusion via an underscored file

### ISSUE THREAD

**Issue by rosskevin** [twbs/bootstrap#18350] opened 2015-11-26 00:02 UTC
In the repository, `bootstrap.scss` contains all the imports.  Unfortunately, since the file does not begin with an underscore, customization of bootstrap via variables breaks (the context is reset unless the file starts with an underscore).  Following the lead of v3 bootstrap-sass, please rename all non-underscored files as underscored files.  On the same note, you may want to change the directory structure to indicate top level vs subordinate includes.

To make v4 in the same vein as v3 bootstrap-sass:
```
bootstrap/
├── scss/
      ├── _bootstrap.scss
      ├── _bootstrap-flex.scss
      ├── _bootstrap-grid.scss
      ├── _bootstrap-reboot.scss
      ├── includes/
         ├── _variables.scss
         └── etc
```

I'm not sure if `includes` is the right subdir, anything will work...whatever makes sense.

Without this, a project customizing BS4 via variables would need to copy the contents of `bootstrap.scss` to affect all bootstrap variables and to have the app's custom styles depend on BS defined variables.

Sample usage app.scss:
```scss
$font-family-sans-serif: 'Roboto', 'Helvetica', 'Arial', sans-serif;
@import "../bower_components/bootstrap/scss/bootstrap";

.foo {
    font-size: $font-size-base;
}
```

**Comment by cvrebert** [comment] 2015-11-26 02:22
X-Ref: https://github.com/twbs/derpstrap/pull/64, https://github.com/gruntjs/grunt-contrib-sass/issues/180, https://github.com/sindresorhus/grunt-sass/issues/176

**Comment by cvrebert** [comment] 2015-11-27 08:34
> please rename all non-underscored files as underscored files.

The problem is that both of the Sass compiler Grunt plugins stubbornly refuse to (provide an option to) compile non-underscored files, and we need to do something like that to produce `dist/css/bootstrap.css`.
We could solve that problem by bypassing the Grunt plugins (npm scripts FTW!).

**Comment by kafeltz** [comment] 2015-11-27 11:04
I thought grunt would be replaced by gulp in v4.

**Comment by simonewebdesign** [comment] 2015-11-27 12:42
> We could solve that problem by bypassing the Grunt plugins (npm scripts FTW!).

How about a Makefile?

**Comment by cvrebert** [comment] 2015-11-27 19:16
> How about a Makefile?

Windows users (those poor bastards) find them inconvenient. (As we found out in Bootstrap v2.)

**Comment by rosskevin** [comment] 2015-11-30 16:02
What about having a non-underscored file for each that imports the underscored file (which has the actual `@import` list)?  That would appear to be the immediate workaround; it works around the build tool restriction and allows for reuse.

**Comment by mdo** [comment] 2015-12-06 20:55
We won't be adding more directories, duplicating files with or without underscores, or switching to a Makefile. Gulp is indeed still an option, but the complexity of our Gruntfile makes it a larger project than any of us want to tackle right now.

Using underscores for those remaining files might be an option, but we'll have to look into that.

**Comment by rosskevin** [comment] 2016-01-20 18:41
I propose you:
1.  Rename the current `bootstrap.scss` to `_core.scss`
2.  Create a new `bootstrap.scss` and `@import "core"`

It's a simple solution and all concerns appear to be covered.

**Comment by mdo** [comment] 2016-09-12 06:39
I don't think we'll be changing anything here, thanks though!

**Closed by mdo** 2016-09-12 06:39 UTC
Labels: css, v4

**Comment by ola-halima** [comment] 2021-05-09 00:05
For anyone else who may have run into this issue; what helped me was renaming the "_variables.scss" in MY project to something different e.g. "_custom_variables.scss" so that it won't clash with bootstrap's version.
