### ISSUE TITLE
V4.5 - The recent addition of 'min-width: 0' on .'col' class causing issues

### ISSUE THREAD

**Issue by STV11C** [twbs/bootstrap#31094] opened 2020-06-18 10:47 UTC
Referring to the following markup, the intended behaviour for this row setup would be when viewing at less than the SM breakpoint the two columns will stack on top of each other. As of v4.5, there seems to be an issue causing the 'col' (which should auto size) to not stack and have a width of zero appearing next to the other column. 
**I think the issue is caused from the addition of **min-width:0** on **.col** class with v4.5.**

```
<div class="row no-gutters">
    <div class="col-sm-6" style="background: orange;">col-sm-6</div>
    <div class="col" style="background: red;">Auto col</div>
</div>
```
![Untitled-1](https://user-images.githubusercontent.com/5532744/85010309-25c9f700-b1a3-11ea-989a-3ddc6ce81afa.png)

**Comment by Hiws** [comment] 2020-06-18 11:48
Looks to be a duplicate of: #30852

**Closed** 2020-06-18 15:43 UTC
Labels: duplicate
