### ISSUE TITLE
sass deprecation warning on _functions.scss with latest sass/gulp-sass version

### ISSUE THREAD

**Issue by flyke** [twbs/bootstrap#37468] opened 2022-11-10 10:22 UTC
I have a project with a main .scss file which imports:
- _variables.scss (bootstrap sass overrides for the project)
- node_modules/bootstrap/scss

package.json contains these versions:
- "bootstrap": "^5.2.2",
- "gulp-sass": "^5.1.0"
- "sass": "^1.56.1"

When my gulp file pipes the sass command to compile scss into a css file, it generates this warning:
```
[11:08:12] Starting 'sass-dev'...
Deprecation Warning: $weight: Passing a number without unit % (100) is deprecated.

To preserve current behavior: $weight * 1%

More info: https://sass-lang.com/d/function-units

    ╷
201 │   @return mix(rgba($foreground, 1), $background, opacity($foreground) * 100);
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_functions.scss 201:11            opaque()
    node_modules/bootstrap/scss/mixins/_table-variants.scss 4:28  table-variant()
    node_modules/bootstrap/scss/_tables.scss 147:3                @import
    node_modules/bootstrap/scss/bootstrap.scss 20:9               @import
    build/scss/main.scss 13:9                                     root stylesheet
```

This warning is not generated with older version of gulp-sass which did not needed to include "sass" separately into the package.json file

My suggestion is to fix this in the _functions.scss file.

**Comment by julien-deramond** [comment] 2022-11-10 10:38
Closing it. Duplicate of https://github.com/twbs/bootstrap/issues/37424 already fixed.

**Closed by julien-deramond** 2022-11-10 10:38 UTC

**Comment by AmirinNS** [comment] 2022-11-15 04:22
If you don't plans to update the Bootstrap, you can downgrade the sass version to 1.55.0
