### ISSUE TITLE
v4 - Stacked custom radio and checkbox have an extra bottom spacing

### ISSUE THREAD

**Issue by johnpozy** [twbs/bootstrap#17432] opened 2015-09-02 02:22 UTC
Just stumble on this
http://v4-alpha.getbootstrap.com/components/forms/#stacked

**Comment by Gupocca** [comment] 2015-09-02 03:00
The issue seems to be caused by the [`::after` psuedo-element of the final `.c-input`](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_custom-forms.scss#L112).

https://jsfiddle.net/sg0fwavn/

**Comment by twbs-lmvtfy** [comment] 2015-09-02 03:00
Hi @Gupocca!

You appear to have posted a live example (https://fiddle.jshell.net/sg0fwavn/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 65, column 5 thru column 64: Duplicate ID ```` radioStacked1 ````.
* line 70, column 5 thru column 64: Duplicate ID ```` radioStacked2 ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Gupocca** [comment] 2015-09-02 03:02
That's beside the point, silly bot, but here you go. ;)
https://jsfiddle.net/sg0fwavn/1/

**Comment by mdo** [comment] 2016-09-10 04:25
Should be fixed by #20671.

**Closed by mdo** 2016-09-10 04:25 UTC
Labels: css, v4
