### ISSUE TITLE
.nav-justified class is missing

### ISSUE THREAD

**Issue by bassjobsen** [twbs/bootstrap#18644] opened 2015-12-23 10:09 UTC
see also: http://stackoverflow.com/questions/34411884/justify-nav-pills-with-bootstrap-v4/34433022. Should it be add?

**Comment by cvrebert** [comment] 2015-12-23 18:21
I presume you mean `.nav-justified`. Approximate duplicate of #17723.

**Closed by cvrebert** 2015-12-23 18:21 UTC
Labels: css, v4
