### ISSUE TITLE
border-width is invisible with $font-size-root set to 12/13px (v4)

### ISSUE THREAD

**Issue by tapia** [twbs/bootstrap#17210] opened 2015-08-21 12:14 UTC
If you set $font-size-root to 12 or 13px, the .0625rem border-width in some components (form elements, .card, .list-group, etc) makes the border invisible.

.1rem make the border visible at any font-size beyond 10px, and looks good to me at > 16px font-sizes.

**Comment by mdo** [comment] 2015-08-21 17:52
I'll likely change the default border value to `1px` so it's always displayed as intended.

**Comment by tapia** [comment] 2015-08-21 19:52
Forcing `1px` is the way to go, probably, but `.1rem` also looks nice with bigger font sizes. Give it a try if you can.

**Comment by Alanaktion** [comment] 2015-08-24 16:14
Using `.1rem` would be a bit more flexible and easier to implement, since `$border-width` is used in the `$input-height` calculations, which rely on the other variables being in `rem`. `.1rem` renders borders as `1px` for me for all fonts between `10px` and `19px`.

**Comment by kscherling** [comment] 2015-08-27 17:44
We've added an additional unitless `$root` var to define the base font size which we can convert to the proper unit when consumed e.g. `$font-size-root: $root * 1px`.  For border widths, we simply use `(1 / $root) * 1rem` to always return the 1px border equivalent while maintaining the rem units for additional math operations.  This was the least potentially impactful though I like the simplicity of `.1rem` option.  I'll check it out.

**Comment by heruan** [comment] 2015-08-28 06:52
I like the unitless `$root` variable approach, thank you @kscherling :+1:

**Comment by mdo** [comment] 2015-09-16 04:12
Addressed in 85f08df.

**Closed by mdo** 2015-09-16 04:12 UTC
Labels: css, v4

**Comment by heruan** [comment] 2015-10-05 08:17
The same affects also `$card-border-width`, it's set to `.0625rem` thus disappearing with font sizes less than 16px; it should be set to `$border-width`, if possibile. Thanks!
