### ISSUE TITLE
Navbar regression in 4.1.0

### ISSUE THREAD

**Issue by brian-kephart** [twbs/bootstrap#26414] opened 2018-04-29 18:47 UTC
https://jsbin.com/welalap/edit?html,output

This regression affects a **collapsed** nav element. Size the window down until the nav collapses, note that it doesn't open. Change the Bootstrap version from 4.1.0 to 4.0.0 and it works.

This might be the same as #26365. I could not tell from the description on that issue whether it related to this, and I didn't want to hijack that issue if it didn't relate.

EDIT: This has been observed in Safari, Firefox, Chrome, and Opera for MacOS, as well as Safari for iOS, all latest versions.

**Comment by asyncdesign** [comment] 2018-04-29 19:07
Take the `collapse` class off the `<ul>` element.  You should just have `navbar-collapse navbar-nav` classes on that.

**Comment by brian-kephart** [comment] 2018-04-29 19:46
Thanks @asyncdesign, that does indeed fix it.

Even though this appears to be a non-issue, since it's still a difference in behavior between minor versions, I'll leave this issue open for the maintainers to close or follow up as they feel appropriate. Thanks to everyone maintaining this project.

**Comment by mdo** [comment] 2018-04-29 22:46
As previous comment noted, this is incorrect Bootstrap markup—you have the collapse classes on two different elements instead of just one. Closing as not a bug. Don't know why it worked before and doesn't now.

**Closed by mdo** 2018-04-29 22:46 UTC
