### ISSUE TITLE
thead not printing on every page in chrome when bootstrap css stylesheet is present

### ISSUE THREAD

**Issue by wouldBeNerd** [twbs/bootstrap#28336] opened 2019-02-21 17:33 UTC
`<thead>` doesn't print on every page when Bootstrap is loaded. See the [test case](https://codepen.io/wouldbenerd/pen/xMNJpd).

Actual:

![](https://user-images.githubusercontent.com/15325943/53188946-b1ab2d80-3606-11e9-81e4-d0ba0b4dc7be.png)

Expected:

![](https://user-images.githubusercontent.com/15325943/53189025-e323f900-3606-11e9-97ec-57e0a38c336b.png)

Operating System: Windows 10 Pro 10.0.17134
Browser: Chrome 72.0.3626.109

**Comment by bardiharborow** [comment] 2019-02-27 15:14
As far as I can tell, this is a duplicate of #13544 and is not a Bootstrap bug, but rather [Chromium bug #24826](https://bugs.chromium.org/p/chromium/issues/detail?id=24826). This doesn't work on Chrome Mac without Bootstrap loaded, and works correctly on Firefox even with Bootstrap loaded. I don't have access to Windows to test, but I doubt the issue is OS-specific. Ping me if I'm wrong here.

**Closed by bardiharborow** 2019-02-27 15:14 UTC
Labels: browser bug, css

**Comment by wouldBeNerd** [comment] 2019-02-28 13:29
Thank you for the reply. 
According too chrome issues this bug has been closed 2 years ago, seems like it might need re-opening.
Though I don't have high hopes for a immediate solution from them. 
I was hoping someone might know a workaround. 
But so far nothing I could find on the net has helped, will pick this up again when I have less deadlines.

**Comment by bardiharborow** [comment] 2019-02-28 14:30
Turns out this code from your test case is invalid HTML, and somehow kills the table header:
```html
<tfoot>
  <tr></tr>
</tfoot>
```

Error:
> Row 1 of a row group established by a `tfoot` element has no cells beginning on it.

There are a number of `<thead>` bugs outstanding in Chrome, but you are correct that this particular one was resolved (I confused Verified and Confirmed as a bug status).

**Comment by wouldBeNerd** [comment] 2019-02-28 14:41
Oh Fantastic!
Thank you so much, never in a million years would I have found this myself!

**Comment by bardiharborow** [comment] 2019-02-28 16:03
I've dug in further, this is caused by how this CSS from Bootstrap interacts with the empty `tfoot > tr` tag:

```css
table {
  border-collapse: collapse;
} 
```

**Comment by wouldBeNerd** [comment] 2019-03-01 08:55
You have my thanks @bardiharborow . 👍 
I think I need to work on my CSS debugging skills. 
Truth be told I'd much rather be playing around in JS or node any day of the week. 
Enter bootstrap as my knight in shining armor.

**Comment by bardiharborow** [comment] 2019-03-01 09:49
[Chromium bug #937227](https://bugs.chromium.org/p/chromium/issues/detail?id=937227) filed, unsure if this needs to be fixed but we'll at least see what the developers have to say.

@wouldBeNerd no worries, that's what we're here for.
