### ISSUE TITLE
Disabled Group Button checkbox/radio still selectable

### ISSUE THREAD

**Issue by myorangeca** [twbs/bootstrap#21231] opened 2016-11-28 08:15 UTC
I have tested this in Chrome, and all latest browsers, and its happening for both group button checkbox and radio. When you try to select the disabled checkbox/radio it still highlights and changes the select state to active. 

```
<div class="btn-group" data-toggle="buttons">
	<label class="btn btn-success active">
		<input type="checkbox" checked=""> Options 1
	</label>
	<label class="btn btn-success">
		<input type="checkbox"> Options 2
	</label>
	<label class="btn btn-success">
		<input type="checkbox"> Options 3
	</label>
	<label class="btn btn-success disabled">
		<input type="checkbox" disabled=""> Disabled
	</label>
</div>
```

**Comment by cvrebert** [comment] 2016-11-29 02:59
Duplicate of #21237.

**Closed by cvrebert** 2016-11-29 02:59 UTC
