### ISSUE TITLE
Chrome+Safari bug: background-image in non-1st column of multi-column layout isn't displayed

### ISSUE THREAD

**Issue by MickeyElliott** [twbs/bootstrap#19600] opened 2016-03-23 21:40 UTC
Seems like cards with a background-image set via css are not rendering the background-image in any column except the first column. `-webkit-column-count: 3;`

My data-attributes are rendering a &lt;style> in ther header.

    <div class="card-columns">
        <div class="card card-inverse">
            <div class="card-block bg-img" data-img-src="http://placehold.it/870x489" data-img-blur="5" data-img-opacity="1">
                <h5 class="card-title">Test</h5>
                <p class="card-text">xxxxxxxx xxxxxxxx </p>
            </div>
        </div>
    </div>

https://jsfiddle.net/MickeyElliott/gamy6Lrs/

**Comment by cvrebert** [comment] 2016-03-23 21:54
@MickeyElliott Please make a JS Bin or JS Fiddle that demonstrates the problem.

**Comment by MickeyElliott** [comment] 2016-03-23 22:13
Here you go!

https://jsfiddle.net/369sLa42/16/

**Comment by cvrebert** [comment] 2016-03-23 22:28
Confirmed in Safari 9.1 and Chrome Canary. Looks like a bug in WebKit/Blink's implementation of CSS multi-column layout.

**Comment by cvrebert** [comment] 2016-03-23 23:27
Reduced testcase for Chrome: https://jsfiddle.net/cvrebert/8dskgzah/

**Comment by cvrebert** [comment] 2016-03-23 23:31
Hmm, I guess Chrome has multiple bugs, at least one of which is already fixed in Canary; my testcase doesn't repro in Canary 51. Guess I'll try again.

**Comment by MickeyElliott** [comment] 2016-03-23 23:33
I'm working on a solution. I've found a partial solution so far.

https://jsfiddle.net/MickeyElliott/tukyontb/45/

**Comment by cvrebert** [comment] 2016-03-24 00:30
New reduced testcase for Safari & Chrome Canary: https://jsfiddle.net/cvrebert/fmsm1p9p/

**Comment by cvrebert** [comment] 2016-03-24 00:58
Filed Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=597471

**Comment by cvrebert** [comment] 2016-03-24 01:47
Filed WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=155823

**Comment by cvrebert** [comment] 2016-03-24 01:59
Closing since this isn't a bug in Bootstrap per se (since custom CSS is involved), and we've filed upstream bugs with the browser vendors.

**Closed by cvrebert** 2016-03-24 01:59 UTC
Labels: browser bug, confirmed, css, v4

**Comment by cvrebert** [comment] 2016-03-24 02:15
The Safari bug has already been fixed in WebKit Nightly: https://bugs.webkit.org/show_bug.cgi?id=155823#c3

**Comment by MickeyElliott** [comment] 2016-03-24 16:53
Thank you. I hope to see a fix from the vendors soon!

**Comment by cvrebert** [comment] 2016-03-27 02:53
MS Edge also seems to suffer from a `filter` bug that affects your example, though it's not related to multi-column:
https://connect.microsoft.com/IE/feedback/details/2518512/edge-border-radius-overflow-hidden-ignored-filter-blur-5px
