### ISSUE TITLE
Validation status image is behind the scroll bar

### ISSUE THREAD

**Issue by Ragavendhran-N** [twbs/bootstrap#30103] opened 2020-01-29 10:52 UTC
![image](https://user-images.githubusercontent.com/17311959/73350683-84094280-42b3-11ea-9f87-e5c7b0332d37.png)

The validation status image shows behind the scroll bar

**Comment by florianlacreuse** [comment] 2020-01-29 13:14
Duplicate of #27142.

**Comment by ysds** [comment] 2020-01-30 10:27
There is no smart way to solve this for now.

Close this but we want any ideas.

**Closed by ysds** 2020-01-30 10:27 UTC
