### ISSUE TITLE
Add max width. min width utility classes for sizing

### ISSUE THREAD

**Issue by themeix** [twbs/bootstrap#32609] opened 2020-12-24 21:41 UTC
For now there have the following code support, 

```
<div class="w-25 p-3" style="background-color: #eee;">Width 25%</div>
<div class="w-50 p-3" style="background-color: #eee;">Width 50%</div>
<div class="w-75 p-3" style="background-color: #eee;">Width 75%</div>
<div class="w-100 p-3" style="background-color: #eee;">Width 100%</div>
<div class="w-auto p-3" style="background-color: #eee;">Width auto</div>
```

Now we are expecting max-width and min-width size utility classes. 
There have now, mw-100 but that is not sufficient. We need mw-75, mw50, etc too

**Comment by XhmikosR** [comment] 2020-12-26 08:23
Duplicate of #30543

**Closed by XhmikosR** 2020-12-26 08:23 UTC
Labels: feature
