### ISSUE TITLE
Positioning error on SVG tooltips/popovers when scrolled, then clicked. 

### ISSUE THREAD

**Issue by ryanlabar** [twbs/bootstrap#20381] opened 2016-07-27 19:20 UTC
See this Pen: 

[https://codepen.io/ryan_labar/pen/zBadPB](https://codepen.io/ryan_labar/pen/zBadPB)

**Comment by cvrebert** [comment] 2016-07-27 20:44
On what browser and OS?

**Comment by ryanlabar** [comment] 2016-07-28 01:25
Chrome, Opera, Safari, Firefox, Vivaldi on MacOS (OSx). Haven't tested on Windows. If you load BS v. 3.3.6 in my CodePen the popovers works just fine.

**Comment by daniapa** [comment] 2016-08-03 04:28
In Windows also fails

**Comment by t47io** [comment] 2016-08-17 19:57
Similar here, the tooltip is indeed triggered, but can't find it anywhere in the view.

Chrome 52.0.2743.116, Mac OSX 10.11.6;
Bootstrap 3.3.7

**Comment by drewskig** [comment] 2016-08-30 02:07
jQuery version should be checked when calculating elOffset so that this doesn't break for jQuery pre-3.x. Looks like the example Pen uses 2.2.4.

**Comment by mdo** [comment] 2016-09-05 22:36
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Closed by mdo** 2016-09-05 22:36 UTC
Labels: awaiting reply, js, v3

**Comment by gabel** [comment] 2017-06-28 12:52
As this topic still works with bootstrap 3.3.5 and even on top of jquery 3.2.1 i think it's not the right way to break a former behaviour and argument not to fix it due to dev on the upcoming version that is available as ALPHA only.

**Comment by nick-lehmann** [comment] 2018-04-09 14:44
@ryanlabar, the problem is that you're still using jQuery 2. Bootstrap 3.3.7 requires you to use jQuery 3. The reason why the tooltips stopped working can be found on line 1623 in [Bootstrap 3.3.6](https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.js):

```
var isSvg = window.SVGElement && el instanceof window.SVGElement
// Avoid using $.offset() on SVGs since it gives incorrect results in jQuery 3.
// See https://github.com/twbs/bootstrap/issues/20280
var elOffset  = isBody ? { top: 0, left: 0 } : (isSvg ? null : $element.offset())
```
