### ISSUE TITLE
Text color class on card hangs the page

### ISSUE THREAD

**Issue by DigitalAndSEO** [twbs/bootstrap#35392] opened 2021-11-23 13:09 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I have the structure:

```
<div class="card border-secondary shadow">
     <h5 class="card-header text-uppercase text-light bg-secondary">MY HEADER</h5>
     <div class="card-body">
          <div class="row d-flex justify-content-evenly">
               ...
          </div>
     </div>
</div>
```

If I put the .text-secondary in the .card, or in the .card-body or in the .row, the page goes blank.

### Reduced test cases

In codepen it works perfectly.
not in GoLive.
(I use the Bundle version of Js if it helps)

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.1.3

**Comment by ffoodd** [comment] 2021-11-24 08:01
There's absolutely no reason this class would trigger anything other than CSS. Don't you have custom scripts in addition to ours?

Without a reproductible test case, moreover if everything works as expected when reducing the case, the issue is rather in your custom code or your environnent.

I'm closing this until you're able to provide a reduced test case.

**Closed by ffoodd** 2021-11-24 08:01 UTC
