### ISSUE TITLE
Media Queries

### ISSUE THREAD

**Issue by bogdaniel** [twbs/bootstrap#22034] opened 2017-02-20 15:08 UTC
Hello, i noticed that on chrome Version 56.0.2924.87 ( 64-bit ) while playing with order-sm-first class it uses the media for min width 576px using bootstrap from branch v4-dev downloaded today.

**Comment by bardiharborow** [comment] 2017-02-21 06:48
I'm unsure what the issue is here, except possibly that the currently live docs have an incorrect breakpoint of `544px`. This was fixed in #21664 and will go live after the next release.

**Closed by bardiharborow** 2017-02-21 06:48 UTC
Labels: css, v4
