### ISSUE TITLE
v4 - Accordion example uses v3 panel markup

### ISSUE THREAD

**Issue by zacechola** [twbs/bootstrap#17157] opened 2015-08-20 19:26 UTC
http://v4-alpha.getbootstrap.com/components/collapse/#accordion-example

**Comment by tshinnic** [comment] 2015-10-22 17:03
Just noticed this now in recent sources, 2 months later, so would be nice to see this PR merged, especially if alpha2 is imminent.

However, and without trying @kkirsche 's fix, why does the Accordion example **work without any of these old *or* new classes**?  They are *only* for the styling of appearance?

**Comment by tshinnic** [comment] 2015-10-22 17:16
Hmm, apparently not *just* styling, some behavior too.  As it was, with no classes operative, the accordion was a single pane open at a time.  If you clicked on another group item, it expanded while closing the previously open item.  With kkirsche's fix, now you can open/close each group independently.  This is radio button vs. checkbox behavior.   

There are actually two behaviors possible - does the documentation say which behavior is available, or how to get either behavior?

**Comment by cvrebert** [comment] 2015-12-23 22:45
Duplicate of #18375.

**Closed by cvrebert** 2015-12-23 22:45 UTC
Labels: confirmed, docs, js, v4
