### ISSUE TITLE
Modal may move your background to left

### ISSUE THREAD

**Issue by zhaiduo** [twbs/bootstrap#15229] opened 2014-11-26 02:05 UTC
https://github.com/twbs/bootstrap/blob/master/js/modal.js#L257

The login Modal moves my page background to left for 17px with padding-right property. My solution is comment it.

**Comment by martin-g** [comment] 2015-01-23 12:59
Here is a live demo of the problem: http://wb-mgrigorov.rhcloud.com/js#modals
Click on "Launch demo modal" button and you will see how the navbar moves to the left because of the (dis)appearing window scroll.
This behavior started with Bootstrap 3.3.2.

**Comment by jrasanen** [comment] 2015-01-24 13:53
Real annoying indeed, happens everytime the modal hides the scrollbar.

**Comment by liunewshine** [comment] 2015-01-26 09:23
.modal-open {
  padding-right: 0 !important;
}
well on ie11,but cause Chrome shift to right

**Comment by KAKwit** [comment] 2015-02-04 21:27
Hi, this is my first ever comment on GitHub so please excuse me if I do something wrong.

I noticed this issue with IE11 just as we updated Bootstrap and did something which *seemed* to work okay (haven’t been able to test it fully yet) but perhaps might prompt someone more knowledgeable to provide a better solution.  The issue is that for some browsers the scrollbar is floating above the content and doesn’t subtract from its width. When the modal-open class is applied to the body and overflow is set to clip, bootstrap attempts to compensate for the removal of the scrollbar by adding the scrollbar width as padding-right to the body.  If the browser never included the scrollbar width in the first place then it causes the body to jump left.

So to fix that I tried getting the width of the body just before it adds the modal-open class in Modal.prototype.show, and then again straight after.  If the two are not the same then keep something to remember that it has scrollbar width.  Then in Modal.prototype.setScrollbar just check it along with this.bodyIsOverflowing to determine whether or not to apply the padding-right.

So … in Modal.prototype.show the bit from this.checkScrollbar() to this.resize() would become something like:

```javascript
this.checkScrollbar()
var oldWidth = this.$body.width();
this.$body.addClass('modal-open')
this.hasScrollbarWidth = this.$body.width() != oldWidth;
this.setScrollbar()
this.escape()
this.resize()
```

And in Modal.prototype.setScrollbar the line which adds the padding-right would become:

```javascript
if (this.bodyIsOverflowing && this.hasScrollbarWidth) this.$body.css('padding-right', bodyPad + this.scrollbarWidth)
```

**Comment by hnrch02** [comment] 2015-02-21 17:37
@KAKwit Could you test if the changes from #15378 fix the problem for you?

**Comment by tchoulihan** [comment] 2015-03-06 18:57
This is still an issue.

**Comment by hnrch02** [comment] 2015-03-11 15:13
@tchoulihan Have you tested this with the latest code from master?

**Comment by tchoulihan** [comment] 2015-03-11 20:07
@hnrch02 Yep, this is still an issue on 3.3.2 .

**Comment by hnrch02** [comment] 2015-03-15 20:30
@tchoulihan I was talking about the most recent code from the `master` branch, the unreleased next version.

**Comment by cvrebert** [comment] 2015-03-15 21:08
After fiddling around with [the visual test for modals](https://github.com/twbs/bootstrap/blob/master/js/tests/visual/modal.html), I am reasonably sure that this has been fixed in `master`. Regardless of whether the page body or the modal are long/short enough to have/lack scrollbars, I don't see the page body shifting laterally when showing/hiding the modal (modulo `position: fixed` elements, which are covered by #14040).

**Closed by cvrebert** 2015-03-15 21:08 UTC
Labels: js

**Comment by TronicLabs** [comment] 2015-03-28 23:50
with the `navbar-fixed-top` the right content shift always on the right.

**Comment by coderdave** [comment] 2015-04-11 19:10
This is still an issue in v3.3.4.

**Comment by cvrebert** [comment] 2015-04-11 19:31
@coderdave Presumably your example involves fixed-position elements?

**Comment by coderdave** [comment] 2015-04-11 19:42
@cvrebert Yes, I am also using `navbar-fixed-top`

**Comment by cvrebert** [comment] 2015-04-11 21:46
@coderdave Then, as stated above, that's a separate bug: #14040.

**Comment by kdniazi** [comment] 2015-04-24 08:20
Model add in line css in body tag     "padding-right:17px"
To solve this issue, we can call a action on model hide

$(document).ready(function(e) {
    $('#question_model').on('hidden.bs.modal', function () {
  		$("body").removeAttr("style")
	});
});
