### ISSUE TITLE
collapse (accordion) does not work properly with parent

### ISSUE THREAD

**Issue by diaksid** [twbs/bootstrap#19866] opened 2016-05-09 04:48 UTC
js/src/collapse.js/collapse.js str. 124:

`actives = $.makeArray($(Selector.ACTIVES))`

should be changed to

`actives = $.makeArray($(Selector.ACTIVES, this._parent));`

**Comment by Johann-S** [comment] 2016-05-09 07:23
Exactly this PR : https://github.com/twbs/bootstrap/pull/18847 will fix it

**Comment by RyanZim** [comment] 2016-05-09 12:45
Duplicate of https://github.com/twbs/bootstrap/issues/18824. Please close this. Thanks!

**Closed** 2016-05-09 12:51 UTC
