### ISSUE TITLE
Problems with npm in beta 3

### ISSUE THREAD

**Issue by tavo962** [twbs/bootstrap#25132] opened 2017-12-30 03:44 UTC
Hello,

**I want to report the following:**

**I have tried to install the Bootstrap 4 in beta 3 to use it with Angular CLI.**

`npm install --save bootstrap@4.0.0-beta.3`

But it does not work when including the files in the .angular-cli.json mark the following error:

`ERROR in ./node_modules/css-loader?{"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"ident":"postcss","sourceMap":false}!./node_modules/bootstrap/dist/css/bootstrap.min.css
Module build failed: BrowserslistError: Unknown browser major
    at error (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/browserslist/index.js:37:11)
    at Function.browserslist.checkName (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/browserslist/index.js:320:18)
    at Function.select (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/browserslist/index.js:438:37)
    at /Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/browserslist/index.js:207:41
    at Array.forEach (<anonymous>)
    at browserslist (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/browserslist/index.js:196:13)
    at Browsers.parse (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/autoprefixer/lib/browsers.js:44:14)
    at new Browsers (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/autoprefixer/lib/browsers.js:39:28)
    at loadPrefixes (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/autoprefixer/lib/autoprefixer.js:56:18)
    at plugin (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/autoprefixer/lib/autoprefixer.js:62:18)
    at LazyResult.run (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:270:20)
    at LazyResult.asyncTick (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:185:32)
    at LazyResult.asyncTick (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:197:22)
    at processing.Promise.then._this2.processed (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:224:20)
    at new Promise (<anonymous>)
    at LazyResult.async (/Users/tavo962/Desktop/git/Learning-Angular/SpotiApp/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:221:27)
 @ ./node_modules/bootstrap/dist/css/bootstrap.min.css 4:14-131
 @ multi ./src/styles.css ./node_modules/bootstrap/dist/css/bootstrap.min.css`

## File .angular-cli.json
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "project": {
    "name": "spoti-app"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.app.json",
      "testTsconfig": "tsconfig.spec.json",
      "prefix": "app",
      "styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css"
      ],
      "scripts": [
        "../node_modules/jquery/dist/jquery.slim.min.js",
        "../node_modules/popper.js/dist/umd/popper.min.js",
        "../node_modules/bootstrap/dist/js/bootstrap.min.js"
      ],
      "environmentSource": "environments/environment.ts",
      "environments": {
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "project": "src/tsconfig.app.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "src/tsconfig.spec.json",
      "exclude": "**/node_modules/**"
    },
    {
      "project": "e2e/tsconfig.e2e.json",
      "exclude": "**/node_modules/**"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "component": {}
  }
}`

With beta 2 it works correctly.

Notes:

1. The Angular CLI version is the most recent.
2. The Angular application is new.

Best Regards
@tavo962

**Comment by wolfy1339** [comment] 2017-12-30 04:47
Duplicate of #25118
Please report this problem to the angular folks. This is not a bootstrap bug.

**Closed** 2017-12-30 15:00 UTC
