### ISSUE TITLE
RTL Official support

### ISSUE THREAD

**Issue by Alirezamohammadi** [twbs/bootstrap#27123] opened 2018-08-23 19:47 UTC
Hi, Does the Bootstrap developers team intend to add right-to-left support for this project?
Unofficial tools are mostly out of dated or don't work properly. A great community of bootstrap users with right-to-left languages (like Persian, Arabic & ...) are facing this problem for several years. please pay attention to us 😥 .

**Comment by alecpl** [comment] 2018-08-30 06:09
Duplicate of #24807.

**Comment by Alirezamohammadi** [comment] 2018-08-30 10:03
@alecpl Yes that's right, I see had seen this issue before but no clear answer was given, so I opened a new issue.

**Closed** 2018-09-25 15:52 UTC

**Comment by mRizvandi** [comment] 2019-05-04 03:39
RTL and LTR version:
https://github.com/mRizvandi/AryaBootstrap/blob/master/ReadMe.En.md
