### ISSUE TITLE
Bootstrap Turkey

### ISSUE THREAD

**Issue by trbootstrap** [twbs/bootstrap#16239] opened 2015-04-06 12:50 UTC
Hello,
I http://getbootstrap.com/ for the with your permission web site turkey  to open ..

Domain : ***

I will start immediately after your approval ..

**Comment by MGaetan89** [comment] 2015-04-06 13:12
http://getbootstrap.com/getting-started/#translations

I think you can go ahead

**Comment by trbootstrap** [comment] 2015-04-06 13:16
Thank You, MGaetan89 domain registart, after translation to start.

Is it true you add after you finish?
http://getbootstrap.com/getting-started/#translations

**Comment by MGaetan89** [comment] 2015-04-06 13:18
I'm not part of the project, so don't take my word for it.
But according to that page, it looks like yes.

**Comment by trbootstrap** [comment] 2015-04-06 13:19
Yes, staff Answer wait.

**Comment by juthilo** [comment] 2015-04-06 16:07
Duplicate of https://github.com/twbs/bootstrap/issues/11342#issuecomment-27631601.

**Closed by juthilo** 2015-04-06 16:07 UTC
