### ISSUE TITLE
Documentation examples of forms doesn't close input tags

### ISSUE THREAD

**Issue by 28raining** [twbs/bootstrap#37579] opened 2022-12-03 17:52 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Here's the example code. The input tag is left open, no </input> or <input ... />.

In Preact + HTM this causes a problem. Where template strings are converted to html tree's in js.

```
<div class="input-group mb-3">
  <span class="input-group-text" id="basic-addon1">@</span>
  <input type="text" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
</div>
```

### Reduced test cases

https://codepen.io/28raining/pen/xxzQXJz

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1.0

**Comment by julien-deramond** [comment] 2022-12-03 19:05
Closing this one. Duplicate of #36666.

**Closed by julien-deramond** 2022-12-03 19:05 UTC
