### ISSUE TITLE
Tooltip does not disappear on disabled button

### ISSUE THREAD

**Issue by toby-howell** [twbs/bootstrap#21232] opened 2016-11-28 15:45 UTC
I have a tooltip on a `<button>` which disappears once the mouse leaves the button. However, if the button becomes disabled (using the `disabled` attribute) whilst the tooltip is visible, the tooltip is not removed when the mouse leaves the button. This is a Bootstrap feature &mdash; not functionality that I have implemented myself. I encountered this on Windows 10 Pro x64 using Bootstrap v4.0.0-alpha.5.

<details>
	<summary>This affects every desktop browser I have installed.</summary>
	<ul>
		<li>Chrome 54.0.2840.99 m</li>
		<li>Firefox 50.0</li>
		<li>Microsoft Edge 38.14393.0.0</li>
		<li>Opera 41.0.2353.69</li>
		<li>Internet Explorer 11.447.14393.0</li>
		<li>Safari 5.1.7</li>
	</ul>
</details>

<hr/>

Chrome does not fire mouse events for disabled buttons, and possibly other disabled elements (`<input>` etc). Firefox _does_ fire mouse events for disabled buttons, but is still somehow affected by this issue.

As a result of the `mouseleave` not firing, Bootstrap does not remove the tooltip.

Instead of listening for the `mouseleave` event from the button, we could listen for the `mousemove` event from the document. As Firefox _does_ fire `mousemove` events for disabled buttons, we also need to ensure that the `mousemove` event did not bubble from the button in question.

Here's an example of the bug and the above `mousemove` approach: [https://jsbin.com/dobucebiwi](https://jsbin.com/dobucebiwi/edit?js,output)

The `.btn-danger` button does not use this workaround, and the `.btn-success` button does. Mouse-over the buttons to see their tooltips. Click buttons to disable them. You should observe that the `.btn-success` button's tooltip is removed when the mouse leaves the disabled button.

**Comment by tskaiser** [comment] 2017-07-25 11:43
The same problem exists with elements that are removed ie. their tooltip gets left behind and stuck.

As an aside, is there are way to disable bootstrap tooltips entirely and restore the original behavior of the browser (which works)?

**Comment by patrickhlauke** [comment] 2017-07-25 15:30
>As an aside: is there any way to disable bootstrap tooltips entirely and restore the original behavior of the browser (which works)?

as tooltips are "opt-in" and you must initialize them yourself, the answer is: don't initialize them yourself...

**Comment by abdulrazakshaikh** [comment] 2018-11-28 10:37
**you can use like this below**

<style type="text/css">
[disabled]{pointer-events: none}
.tooltip-disabled{pointer-events: none}
</style>


<button type="button" class="btn btn-secondary tooltip-disabled" disabled="disabled" data-toggle="tooltip" data-placement="top" title="Tooltip on top">Tooltip on top</button>

**Comment by alecpl** [comment] 2019-11-07 07:04
This is a duplicate of #22380.

**Comment by mdo** [comment] 2020-09-18 21:44
This is an old one, but as mentioned in our docs at https://getbootstrap.com/docs/4.5/components/tooltips/#overview:

> Tooltips for .disabled or disabled elements must be triggered on a wrapper element.

**Closed by mdo** 2020-09-18 21:44 UTC
Labels: feature, js, v4
