### ISSUE TITLE
tooltips break after hovering a few times.

### ISSUE THREAD

**Issue by Kloptoe** [twbs/bootstrap#33057] opened 2021-02-11 22:51 UTC
Bootstrap5 Tooltips break after hovering or break after trying to hover again

https://gyazo.com/c4b43a6ad69e8ca0daea0780a348bc99

**Comment by mdo** [comment] 2021-02-11 23:20
Duplicate of #32372, which is pinned to the top of our issues list and hard not to miss ;).

**Comment by mdo** [comment] 2021-02-11 23:21
Aiming to have it fixed in Beta 3 btw!

**Closed by mdo** 2021-02-11 23:20 UTC

**Comment by joeforjoomla** [comment] 2021-02-12 09:08
Just checked the Beta 2 version but the problem with tooltips changed but it's still here! Now when the pointer enters an element with a tooltip on the same side of the tooltip, as a result the tooltip and the arrow are broken and divided, the main tooltip body is positioned outside in a wrong position or disappears.
