### ISSUE TITLE
Popover position on resize in the documentation

### ISSUE THREAD

**Issue by Erikmitk** [twbs/bootstrap#16622] opened 2015-06-11 10:48 UTC
The four placement [example Popovers](http://getbootstrap.com/javascript/#popovers-examples) in the documentation do not keep their correct position while resizing the browser window. Since the other popover examples do that correctly, I believe that should be fixed.

![popover](https://cloud.githubusercontent.com/assets/180686/8105188/40c4c728-1037-11e5-8635-7dbe1a4ab2f3.png)

**Comment by kkirsche** [comment] 2015-06-12 00:29
This is due to popovers being absolutely positioned and the JS is not actively monitoring screen size to make those adjustments after they have been rendered. As this is a pretty major change (as I think of it, it would fall under a major change as it's not backwards compatible and if apps have adjusted for the current behavior this would break all of their changes), my guess is that it wouldn't be able to be done in V3 but may be something which gets addressed if reasonably possible in V4.

**Comment by cvrebert** [comment] 2015-06-12 04:26
Duplicate of #12799.

**Closed by cvrebert** 2015-06-12 04:26 UTC
