### ISSUE TITLE
[v4-beta 3] Navbar fixed-top problem and non scrollable or visible drowpdown menu links > bug ? 

### ISSUE THREAD

**Issue by poilozorey** [twbs/bootstrap#25205] opened 2018-01-05 09:53 UTC
Hello
There is a problem with the menu "**dropdown**" in navbar "**fixed-top**" and the small resolutions (cell phone or smartphone).

When the dropdown menu contains, for example, more than 10 links (categories or other ...), on small resolutions (less than 768px in height) the menu comes out of the visible area of the screen.
The navigation bar is "**fixed**" and does not move, there is no scroll to get the links of the drop-down menu (drowpdown) that are outside the visible area and these links are invisible or not scrollable.

**Is there a way to make menu links visible or scrollable?**

**Look at the examples below**
On desktop screen we can see the 10 links of the dropdown menu
But on cell phone (less than 768px in height) the links are inaccessible and invisible (no scrolls possible).

**Firefox (same think on Chrome) desktop large screen** :
![firefox-desktop](https://user-images.githubusercontent.com/32791447/34603614-f338bebc-f204-11e7-9572-d00d39d6a2f8.jpg)
**Smart phone resolution (less than 768px) height** : 
![resolution-height](https://user-images.githubusercontent.com/32791447/34603684-48ad0baa-f205-11e7-92bf-f64dd35df572.jpg)
**Smart phone resolution (less than 768px) width** : 
![reso-witdh](https://user-images.githubusercontent.com/32791447/34603716-688eb234-f205-11e7-9328-bf22e57482cd.jpg)

**Comment by Johann-S** [comment] 2018-01-05 14:18
Bug reports must include a live demo of the problem. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/v4-dev/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and OS details.

**Comment by poilozorey** [comment] 2018-01-05 15:25
Here the code with a "**default navbar**" and  "**drop-down menu links**" visible and scrollable.
[](https://codepen.io/poilozorey/pen/baoJvE)
Here the code with a "**fixed-top navbar**" and "**drop-down menu links**" not visible or not scrollable
[](https://codepen.io/poilozorey/pen/goGyRN)

On desktop screen when the page height allows it with "**default navbar**" the "**dropdown links**" are visible and accessible.
But when one tries with a "**fixed-top navbar**", the "**dropdown links**" are not accessible, not visible and not scrollable.

**Comment by Johann-S** [comment] 2018-01-05 15:32
Not sure if it's a CSS or JS issue here 🤔

**Comment by poilozorey** [comment] 2018-01-05 15:51
I do not know if the problem is .CSS or .JS, but the problem is there.
Unfortunately this makes the "navbar fixed-top" unusable for sites that have a lot of dropdown links !

You might consider giving a property when a "dropdown show" comes out of the screen, like for a "default navbar", make sure that if the dropdown links come out of the screen the dropdown menu goes into visible ...

Or, although this solution is less convenient for cell phones, to ensure that the links are scrollable inside the menu ???

**Comment by 719media** [comment] 2018-01-05 21:18
it seems css to me. simplified version with no js:

https://codepen.io/anon/pen/PEOqGz

if you're willing to sacrifice some ie/edge users, you can always use position: sticky instead of position: fixed...

https://caniuse.com/#feat=css-sticky

alternatively, you could just add something like max-height:300px;overflow:auto; to the dropdown-menu... I always figured bootstrap would have some sort of sane default for dropdown-menu, but I suppose the ideal dropdown height could drastically differ if you are developing a desktop-only admin application vs universal responsive site. Perhaps a variable in _variables.scss could be created for this purpose?

**Comment by poilozorey** [comment] 2018-01-06 08:11
Still today with **bootstrap v4.0.0-beta.3** in small resolutions **(cell phones less than 768px in height**) the "**dropdown menu**" (_in a navbar fixed-top_) when it contains too many links comes out of the visible area of ​​the screen and makes the links unreachable and invisible .

So currently we can not use **Bootsrap v4.0.0-beta-3** for these reasons:
-> **navbar fixed-top**.
-> **full of links in dropdown menu**.
-> **small resolutions of cell phones**.

**719media**
I tested added "**overflow: auto; max-height: 300px;**" to the "**dropdown menu**" but it does not work.
When to remove the **.JS**, it is not possible, especially when it comes to dress a theme for **wordpress**, **joomla** or **dotclear**.

**Comment by Ghost180195** [comment] 2018-01-06 14:54
Possible solution of the problem:
https://codepen.io/anon/pen/vpWZap
It would be nice if  there was a block .navbar-header that wraps around here .navbar-brand and navbar-toggle so as not to calculate which length is higher. In this example navbar is expanded before xl screen so it would be nice if we could detect current breakpoint with js to add `max-height` to .navbar-collapse in all screen except xl screen.

**Comment by 719media** [comment] 2018-01-06 17:49
@poilozorey the intent behind the no JS example was just isolating the cause, not suggesting it would work for your use case. The underlying issue is that if you have a position fixed container that contains a position absolute container (your dropdown), which means the dropdown is not affecting DOM layout. So you need to set a height on the dropdown to get scroll. Using your example, like so:

https://codepen.io/anon/pen/eyeezw

This is true whether or not you are using popper or not. Coincidentally, you are actually not using popper, as bootstrap docs state `Popper.js isn’t used to position dropdowns in navbars though as dynamic positioning isn’t required.` I'm not exactly sure why popper isn't used for navbars, but regardless, it should not really matter to your example. Just set an overflow. In my opinion, this is good interface design even if you aren't using fixed navbar.

**Comment by poilozorey** [comment] 2018-01-06 17:55
**Ghost180195** 
your example does not seem to guarantee a solution, especially with regard to the dropdown.

I tried to include in your solution a dropdown menu that contains 10 links but it did not work.
Unless I did it right ...

Would you submit another example with **15 links or more** in a **dropdown menu** in a "**navbar fixed-top**" to see if the links are visible and accessible on small resolutions (**cell phones less 768px in height**) ???

**Comment by Ghost180195** [comment] 2018-01-06 18:13
Works fine in all screens except xl screen:

https://codepen.io/anon/pen/vpWZap

In xl screen we should not add `max-heigh` to **.navbar-collapse** and for this we must detect current breakpoint with js.

**Comment by Ghost180195** [comment] 2018-01-06 18:43
Final version:

https://codepen.io/anon/pen/xpPpqP

**Comment by 719media** [comment] 2018-01-06 18:52
@poilozorey yes, at some point you have to actually do a little code yourself.

you have many options:
1) utilize @Ghost180195 examples on how to calculate remaining height for the viewport.
2) or create your own media queries
3) or dynamically adjust using vh units like:

https://codepen.io/anon/pen/baYaoG

4) use position: sticky at the expense of some older browser users. The site would still be useable for them, they just would get a navbar that wouldn't stick on scroll. And no additional JS required for solution which is nice.

**Comment by Ghost180195** [comment] 2018-01-06 18:58
my examples are for **.navbar-collapse**.
For **.nav-item dropdown** you can use @719media method.

**Comment by mdo** [comment] 2018-01-07 00:11
Is this related to #24920 at all?

**Comment by 719media** [comment] 2018-01-07 03:50
Not really. This issue does *not* use popper (it is in the nav, which avoids popper here (https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js#L150). #24920 is an issue dealing with how popper is calculating the placement of the dropdown

**Comment by poilozorey** [comment] 2018-01-07 12:57
**719media**
According to your example : 
https://codepen.io/anon/pen/baYaoG
would it be possible to see a solution like this (like your example) add in native to bootstrap 4?

**Comment by poilozorey** [comment] 2018-01-07 14:24
I see another problem with "**navbar fixed-top**".
When the navbar contains too many links, in small resolution (_cell phones less than 768px in height_) the links are no longer visible because they come out of the frame of the screen, in this example, ditto for the search field.

So finally, I do not think that only the "**dropdown menu**" which contains a lot of links and that it is used with "**navbar fixed-top**" in small resolution (_cell phones less than 768px in height_) ...
I think it's "**navbar fixed-top**" that lacks a "**patch**".
(_a bit like the one you submitted for the "dropdown" with overflow: auto and addition .JS that should be adapted to the function "navbar fixed-top"_)

If you adjust the size of the window, you will see the bug of "navbar fixed-top" links coming out of the visible area of ​​the screen.
https://codepen.io/anon/pen/baYZrj

look here
When the "**navbar**" is "**default**" (not _fixed-top_) the scroll becomes automatic and allows to see all the contents of the navbar (links, menu dropdown search form etc ...)
https://codepen.io/anon/pen/GyOeyy
**Why this function is not applied to "navbar fixed-top"?**

Here are also in picture ...
**Nokia Lumia 520 (320x533) in height :** 
![hauteur](https://user-images.githubusercontent.com/32791447/34650102-71df22ee-f3bb-11e7-9587-00f5329c5477.jpg)
**Nokia Lumia 520 (533x320) in width :** 
![lageur](https://user-images.githubusercontent.com/32791447/34650108-88c8aa98-f3bb-11e7-832d-ba957e700602.jpg)

We see that the links of the "**navbar fixed-top**" come out of the visible area of ​​the screen and become **invisible** and **unaccessible**.

**Comment by 719media** [comment] 2018-01-07 17:43
@mdo another solution here staring me in the face and didn't realize: just setting the z-index higher. I mean really, when you think about this problem, popper doesn't avoid randomly positioned fixed elements like navbar-fixed. That's an issue for z-index to solve.

I'm not familiar with why the z-index values were selected the way they were for bootstrap: https://getbootstrap.com/docs/4.0/layout/overview/#z-index

So I'm not sure why `$zindex-dropdown` is lower than `$zindex-fixed` and `$zindex-sticky`

**Comment by 719media** [comment] 2018-01-07 18:22
@poilozorey I don't think the solution I provided should be applied to bootstrap native.

The issue with the link scroll collapse _could_ be fixed by applying `max-height: 100%` and `overflow: auto;` to .fixed-top, but then that breaks the dropdown. Now, the dropdown breakage COULD be avoided if the navbar used popper for dropdowns, which it doesn't for some reason. I'm not sure why, you'd have to ask @Johann-S or @mdo about the dropdown.js navbar exception (they seem the most familiar with this code):

https://github.com/twbs/bootstrap/commit/af93db294b8670dabefbe481603a74e02c84dc0a#diff-bfe9dc603f82b0c51ba7430c1fe4c558

which has since survived a few rewrites and currently exists as just a "don't use popper in navbar" form.

Perhaps it may be unnecessary now, it looks like it may have been applied back before bootstrap was using display: flex everywhere? I bet it would be removed and whatever exception it was trying to avoid, if it still exists, could just be handled inside of popper. Either way, I'm not sure of the reason for lack of popper in navbar.

In my opinion, having _some_ dropdowns use popper, and _others_ not, is worse than just having everything use popper just for maintainability reasons, let alone the advantages that popper generally brings (like it would to your use case).

So, in summary, I would propose that:
  1) The exception for navbar popper avoidance be removed for reasons stated above
  2) A setting for `max-height: 100%;` and `overflow: auto;` (or `overflow-x: auto;`) be applied to .fixed-top
  3) Now, the above 2 will only fix the collapse. You still need to completely fix the dropdown, as the above only allows the dropdown to escape the fixed position overflow and the scroll will still be a problem. The scroll can be fixed on your own by applying the vh calculation earlier in this thread, or a static dropdown-menu height and overflow.


For now, I really recommend you just use `sticky-top` instead of `fixed-top` which would fix all of your problems unless there is good reason to support legacy browsers. That will fix all of your issues for now. `sticky-top` is good because legacy browser users will still get the navbar at the top of the page, it just won't scroll. Personally, I think fixed-top should just die, and we wouldn't have to worry about any of this :) if only ie/edge would have implemented it sooner... and bootstrap supports IE 10+ so it must stay...

**Comment by poilozorey** [comment] 2018-01-08 08:28
**719media**
For your proposal to replace "fixed-top" by "sticky-top" ..check me, it does not work, I explain myself ...

The navbar "sticky-top" has the same behavior as the "navbar default".
when scrolling down, the navbar disappears above the screen area.
(she should always stay at the top of the screen not ???)

Regarding your first proposal, I did:
1 - added the class ".dropwdown-menu-scroll" to ".drowpdown-menu"
2 - added rule "overflow-x: auto;".
3 - added your piece of .JS
It works!

Then ...

4 - added to the class ".fixed-top" the rules "max-height: 100%;" and "overflow: auto" (or "overflow-y: auto;").

Indeed, the navbar is broken.
But I can not understand the next step or you seem to say that we must disable functions of "Popper", how should I do that?

Do you have the kindness to show me an example on CodePen for example?

**Comment by mdo** [comment] 2018-04-01 02:13
Closing this as a stale issue that's also not a bug. Adding some navbar overflow scrolling is being tracked in another issue at #24796.

**Closed by mdo** 2018-04-01 02:13 UTC
Labels: css, v4

**Comment by rodryLeon** [comment] 2020-08-05 15:39
i fixed it with overflow:hidden in the content block
{
overflow:hidden
}
