### ISSUE TITLE
Modal has a bug when triggered with javascript

### ISSUE THREAD

**Issue by thehitechpanky** [twbs/bootstrap#33962] opened 2021-05-13 07:18 UTC
Uncaught TypeError: BACKDROP: Option "rootElement" provided type "null" but expected type "element".
    at index.js:130
    at Array.forEach (<anonymous>)
    at l (index.js:124)
    at xe._getConfig (backdrop.js:92)
    at new xe (backdrop.js:33)
    at Ne._initializeBackDrop (modal.js:218)
    at new Ne (modal.js:84)
    at S (main.js:1)
    at HTMLInputElement.onSelect (main.js:1)
    at b.onSelect (jquery.autocomplete.min.js:8)

**Comment by GeoSot** [comment] 2021-05-13 07:27
Duplicate of #33840

**Closed by GeoSot** 2021-05-13 07:27 UTC
Labels: duplicate
