### ISSUE TITLE
Toggle button states are visually indistinguishable (from focus state)

### ISSUE THREAD

**Issue by speller** [twbs/bootstrap#23897] opened 2017-09-10 11:39 UTC
Toggled button states are totally visually indistinguishable. It is no way to tell the end user is button toggled or not. Do you plan to change it?

**Comment by andresgalante** [comment] 2017-09-11 03:20
Hi @speller to me this is a visual bug.

Toggle state is the same as active 
Active is the same as hover. 

This means that if you are hover a btn, and you toggle it you won't be able if it's on or off because  it will always look like hover.

@mdo If you think it's worth working on this one I'll try experiment with colors and find a good solution for this one.

**Comment by speller** [comment] 2017-09-11 04:19
@andresgalante Thank you for your answer. It is not a bug, but visual issue. 

As I imagine users should intuitevely recognise is toggled button on or off. Docs explain checkboxes can be visually represented as toggle buttons, but its appearance is not intuitive and visually hard to recognise. But it should be intuitive like standard checkbox itself. Without this every developer who want to use non-standard checkbox or toggle button will have to make its own custom controls. I think Bootstrap should provide such basic controls out of the box. Toggle buttons and checkboxes are used to show something on or off, and currently it is no way to do that without custom modifications.

As a suggestion it may be useful to make additional feature to allow developers to define state icons. As Bootstrap is not linked to any predefined icon set it will be good enough to set just two icons of developer's favorite icon set and buttons will automatically show them. But it should be an addition to basic visual states defferetiation. 

Bootstrap 4 is fresh and modern framework and I hope it will be as complete as possible to avoid wasting time for basic controls development.

**Comment by ysds** [comment] 2017-09-14 00:02
Probably duplicate of #23710

**Closed** 2017-09-23 20:45 UTC
Labels: css, v4
