### ISSUE TITLE
Double-сlicking on the container selects all texts

### ISSUE THREAD

**Issue by studio-marweb** [twbs/bootstrap#16326] opened 2015-04-22 07:32 UTC
Please, see video: http://screencast.com/t/xaiXeHyl6

**Comment by patrickhlauke** [comment] 2015-04-22 09:30
Cannot reproduce on Win8.1 with Chrome, Firefox, IE11. What OS/browser are you experiencing this?

**Comment by studio-marweb** [comment] 2015-04-22 13:04
I used Win7/Firefox. Btw, in chrome this problem does not appear.

**Comment by patrickhlauke** [comment] 2015-04-22 13:43
Tested with Win7/Firefox, and it seems this is Firefox's own strange text selection behavior - double (and sometimes triple) clicking on a container selects, depending on the underlying structure, all content. It also behaves this way on several other non-Bootstrap sites I tested, so closing as not a Bootstrap issue

**Closed by patrickhlauke** 2015-04-22 13:43 UTC
