### ISSUE TITLE
Null Variable

### ISSUE THREAD

**Issue by rbsdotnet** [twbs/bootstrap#37013] opened 2022-08-23 18:53 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi Dear,
when use Version 5.2 error in Bundle & Minifier in Visual Stuido :

Expected expression, found ';'

find any variable set null data :

for Example:
$input-btn-font-family:       null !default;

### Reduced test cases

$form-select-disabled-color:        null !default;

  --bs-btn-font-family: ;

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What version of Bootstrap are you using?

v5.2

**Comment by julien-deramond** [comment] 2022-08-24 06:22
Duplicate of #36595

**Closed by julien-deramond** 2022-08-24 06:22 UTC
