### ISSUE TITLE
v4: Modal widths exceed viewport

### ISSUE THREAD

**Issue by idleberg** [twbs/bootstrap#19025] opened 2016-01-25 23:30 UTC
Whenever a new breakpoint is reached, a modal's width will exceed the width of the viewport for several pixels.

Viewport | Modal
---------|------
544      | 600
768      | 900

For reference, a look at how Bootstrap 3 handled this:

Viewport | Modal
---------|------
768      | 600
992      | 900

Wondering if this was intentional, even though I doubt it. Anyway, no pull request as this decision should remain in your domain.

**Comment by cvrebert** [comment] 2016-01-26 02:45
Duplicate of #17581.

**Closed by cvrebert** 2016-01-26 02:45 UTC
Labels: css, v4
