### ISSUE TITLE
Google search still goes to 4.x docs

### ISSUE THREAD

**Issue by mariusa** [twbs/bootstrap#38055] opened 2023-02-14 16:23 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Searching bootstrap something on google (eg what's the syntax for bold font) still goes to 4.x docs most of the time. Example:
https://www.google.com/search?q=bootstrap+bold+text
(can't even switch to v5 there)

Please make BS 5 the default for Google (via SEO markup for the docs site)

Thanks

### Reduced test cases

https://www.google.com/search?q=bootstrap+bold+text

### What operating system(s) are you seeing the problem on?

Linux

### What version of Bootstrap are you using?

5

**Comment by khaledzaoui634** [comment] 2023-02-14 20:57
Intelligence works miracles

**Comment by folknor** [comment] 2023-02-18 13:41
> (can't even switch to v5 there)

This would be fixed by https://github.com/twbs/bootstrap/issues/31980#issuecomment-1102842817 / https://github.com/twbs/bootstrap/issues/31980#issuecomment-1228347533 / https://github.com/twbs/bootstrap/issues/36189 but I'm not sure I've made my point clearly in those comments.

Also relevant: https://github.com/twbs/bootstrap/pull/36805

**Comment by Alex-Toucan** [comment] 2023-03-03 18:39
A lot of people still use Bootstrap 4 and even 3. Possibly, they can edit how they can be looked up by their meta (or equivalent) tags.

**Comment by XhmikosR** [comment] 2023-03-23 08:21
Duplicate of many other related issues.

**Closed by XhmikosR** 2023-03-23 08:21 UTC
Labels: docs, v5
