### ISSUE TITLE
getbootstrap.com examples link goes to 404

### ISSUE THREAD

**Issue by AucT** [twbs/bootstrap#23646] opened 2017-08-24 05:14 UTC
At the bottom of main site (http://getbootstrap.com/) link examples go to 404 not found http://getbootstrap.com/examples/

**Comment by fleumari** [comment] 2017-08-24 05:27
Should be replaced with this link: http://getbootstrap.com/docs/4.0/examples/

**Comment by chiraggmodi** [comment] 2017-08-24 05:43
This is corrected in latest version of beta. I think latest git repo is pending to push on live site.

**Comment by mdo** [comment] 2017-08-24 05:48
Duplicate of #23555.

**Closed by mdo** 2017-08-24 05:48 UTC
Labels: docs, v4
