### ISSUE TITLE
v4: progressbars with labels

### ISSUE THREAD

**Issue by tapia** [twbs/bootstrap#19061] opened 2016-02-01 18:42 UTC
Progressbars in v3 allow a label over the progressbar. The v4 version don't. For example, in the documentation you can see this example:

    <progress class="progress" value="50" max="100">50%</progress>

I'd expect to see a "50%" label over the progressbar, but instead there's nothing, just the bar.

**Comment by cvrebert** [comment] 2016-02-01 20:09
Duplicate of #17264.

**Closed by cvrebert** 2016-02-01 20:09 UTC
