### ISSUE TITLE
Strange bug with validation icon on form input

### ISSUE THREAD

**Issue by scandinave** [twbs/bootstrap#21246] opened 2016-11-29 09:53 UTC
HI,
I'm facing a strange bug. It concern validation icon on input. They suddenly stop to display on my web app and on the official bootstrap documentation.

You can see the bug here : [http://v4-alpha.getbootstrap.com/components/forms/#validation](http://v4-alpha.getbootstrap.com/components/forms/#validation)
This icons are display with svg code : 

`background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 8 8'%3E%3Cpath fill='#5cb85c' d='M2.3 6.73L.6 4.53c-.4-1.04.46-1.4 1.1-.8l1.1 1.4 3.4-3.8c.6-.63 1.6-.27 1.2.7l-4 4.6c-.43.5-.8.4-1.1.1z'/%3E%3C/svg%3E");`

I have test with Firefox 45 esr, 49 and 50, Firefox 50 Mobile, and Safari 8, on Debian and Mac OS X and Android. But it works with Chromium on Debian.

Any Solution to this strange bug?
P.S This icons was display just 2 days ago inside Firefox 49.

**Comment by patrickhlauke** [comment] 2016-11-29 10:17
duplicate of https://github.com/twbs/bootstrap/issues/20956 which was addressed by https://github.com/twbs/bootstrap/pull/20962

**Closed by patrickhlauke** 2016-11-29 10:17 UTC
