### ISSUE TITLE
http://getbootstrap.com/docs/4.0/content/tables/#contextual-classes

### ISSUE THREAD

**Issue by LarryAzevedo** [twbs/bootstrap#25535] opened 2018-02-02 01:51 UTC
The background color on the [Contextual clases section on the Tables page](http://getbootstrap.com/docs/4.0/content/tables/#contextual-classes) is incorrect.  It uses `<tr class="table-dark">...</tr>` but it's getting overwritten by:

```css
.table-dark, .table-dark > td, .table-dark > th {
	background-color: #c6c8ca;
}
```
I'm not sure if that CSS block above should even exist.

![screen shot 2018-02-01 at 8 38 44 pm](https://user-images.githubusercontent.com/2222751/35712509-564ce960-0790-11e8-985d-8feac338999b.png)

**Comment by ysds** [comment] 2018-02-02 14:10
I think this problem is not a **docs** issue. It is certainly a **css** bug.

Demo: https://codepen.io/anon/pen/YewNzM

**Comment by mdo** [comment] 2018-02-03 06:50
Duplicate of #24529.

**Closed by mdo** 2018-02-03 06:50 UTC
Labels: docs, v4

**Comment by ysds** [comment] 2018-02-03 08:10
I'm not sure it is a duplicate. And sorry, it may not be a CSS bug but a issue of **design specification**.

The background color seems correct when add  `.table-dark` to `.table`.

**Dark table (Inverted table)**
```html
<table class="table table-dark">
    <tr><td>.table-dark to table</td></tr>
</table>
```

<img width="457" alt="2018-02-03 16 46 52" src="https://user-images.githubusercontent.com/4065765/35765160-f01eb84e-0901-11e8-8f67-e3f5d202096d.png">

But what color is the correct background color when using `.table-dark` as a contextual class with a row or cell? Dark or light dark?

In SCSS:

https://github.com/twbs/bootstrap/blob/5158338b7c0b12f2e01891e5b5bef18c8e64a1c0/scss/_tables.scss#L103-L105

The `theme-color-level ($ color, -9)` converts the given **dark black** to **light black**.

<img width="316" alt="2018-02-03 17 07 34" src="https://user-images.githubusercontent.com/4065765/35765337-cdc19f70-0904-11e8-8103-2fe5f01eed70.png">


So, from a source of SCSS, `.table-dark` as a contextual class seems to be correct with light gray background color:

**Contextual dark**
<img width="460" alt="2018-02-03 17 03 50" src="https://user-images.githubusercontent.com/4065765/35765307-47e5fcac-0904-11e8-832f-8f0bfa65a668.png">

However, this light gray has a sense of incongruity intuitively.

@mdo Which is the correct color when use `.table-dark` as a contextual class, dark gray or light gray?
