### ISSUE TITLE
input-group sizing issue in Chrome

### ISSUE THREAD

**Issue by ruslandzhumaev** [twbs/bootstrap#18125] opened 2015-11-02 02:08 UTC
Guys, please take a look at http://v4-alpha.getbootstrap.com/components/input-group/#sizing
Screenshot: http://i.imgur.com/fJtcCbE.png
As I understand it is a padding problem:

    .input-group-addon.form-control-lg, .input-group-lg>.input-group-addon, .input-group-lg>.input-group-btn>.input-group-addon.btn {
        padding: 1.25rem; /* It works fine when I disable this property */
        font-size: 1.25rem;
        border-radius: .3rem;
    }

P.S. Win7 / Google Chrome

**Comment by cvrebert** [comment] 2015-11-02 05:10
Duplicate of #17035. Please search more in the future.

**Closed by cvrebert** 2015-11-02 05:10 UTC
Labels: css, v4
