### ISSUE TITLE
Bootstrap 4 Modals: data-dismiss="modal" won't work if fade is present

### ISSUE THREAD

**Issue by derwaldgeist** [twbs/bootstrap#30569] opened 2020-04-13 12:28 UTC
I'm migrating a Bootstrap 3 app to Bootstrap 4 and noticed that the close button does not work anymore. After some googling, I found this answer on Stackoverflow where someone noted it would work if you remove the `fade` on the modal:

https://stackoverflow.com/questions/38537651/bootstrap-close-modal-not-working

And in fact, this is true. As soon as I remove `fade`, the close buttons works again. Alas, I'd like to keep the nice fade in effect, so I am wondering how both could be combined again?

My guess is that Bootstrap 4 changed the way the event hooks are setup. In my case, the modal content is rendered dynamically, depending on the actual dialog content I need. This includes the close button.

**Comment by morrissey-ingenious** [comment] 2020-04-13 20:14
can you provide an example of this, I don't seem to have an issue.

**Comment by alanmehio** [comment] 2020-04-13 20:14
I have checked the https://getbootstrap.com/ and the model based on version 4.3. from a sample which were taken from this link https://getbootstrap.com/docs/4.0/components/modal/  
I did a fiddle on this link [https://jsfiddle.net/alanmehio/outv8gfb/1/] and I have realized it is working and there is no issue with  class="modal fade"

**Comment by VincentLanglet** [comment] 2020-04-17 16:59
I have the same issue.

This is an example with the issue https://jsfiddle.net/fL2vox8d/

It seems like the class `modal-dialog` is necessary.

**Comment by morrissey-ingenious** [comment] 2020-04-17 17:24
@VincentLanglet if you aren't using the documented markup it's not a bug.

[https://getbootstrap.com/docs/4.4/components/modal/#modal-components](https://getbootstrap.com/docs/4.4/components/modal/#modal-components)

**Comment by VincentLanglet** [comment] 2020-04-17 17:30
> I would still say that the complete markup for a modal should be used instead of these custom instances where that are being created.

It's still weird that `modal-dialog` is not mandatory without `fade`.

And a link to the bootstrap 4 isn't helping.
When you try to migrate from bootstrap 3 to bootstrap 4, you can't rewrite all your code, so you're looking for the minimal necessary changes.

**Comment by mdo** [comment] 2020-06-16 03:36
Closing this as a v3 to v4 migration issue. The two are not compatible, so make sure you replace the HTML, CSS, and JS entirely during your migration.

**Closed by mdo** 2020-06-16 03:36 UTC
