### ISSUE TITLE
.form-control in input-group missing right border on focus

### ISSUE THREAD

**Issue by bitcity** [twbs/bootstrap#18247] opened 2015-11-14 18:35 UTC
When btn is on the right of the input, the blue border/shadow are missing on the right edge of input. This was fixed in https://github.com/twbs/bootstrap/issues/12349 , however it appears to show up again (as also reported by https://github.com/twbs/bootstrap/issues/12349#issuecomment-144362982 )

P.S. Tested on Chrome 46 (Ubuntu), Safari & Chrome (iOS 8)

Example : http://getbootstrap.com/components/#input-groups-buttons
![image](https://cloud.githubusercontent.com/assets/4221404/11165114/c245baea-8b2b-11e5-81ff-ee0256d2df23.png)

![image](https://cloud.githubusercontent.com/assets/4221404/11165115/cc13b5c2-8b2b-11e5-9215-8ec5b755d3a9.png)

**Comment by cvrebert** [comment] 2015-11-14 22:08
Duplicate of #17001.

**Closed by cvrebert** 2015-11-14 22:08 UTC
Labels: css, v3
