### ISSUE TITLE
Why is v4 beta blocked?

### ISSUE THREAD

**Issue by tx8821** [twbs/bootstrap#23237] opened 2017-08-07 12:11 UTC
v4.0.0-beta milestone is stuck at 99% for months. There seems no apparent reason why the team is not releasing at least the beta. We are stuck with alpha6 for 8+ months now. I (and thousands of other people) would like to integrate any changes/bugfixes that accumulated during those months. We started using v4 for business apps that were planned to be production-ready now. It's been YEARS of v4 development and nobody would have predicted that we'd be stuck with alpha 6 at the end of 2017!

Please be kind to answer:

- What is the reason of not releasing at least v4.0.0-beta (or call it alpha 7 if its still messy).
- Is this project abandoned / essentially unsuited for future-oriented projects...

I know you (devs) have no obligation to anyone whatsoever... I have no right to demand anything. But I think I have a right to be answered. I did bet on your project and I'm having difficulties in soon-to-be-production projects.

Please don't close this thread. Let us have at least one place where we could talk about this. You're not updating your milestones, you're not updating the blog, you're closing any question that asks for more info.... This is a symptoms of abandoned projects. Bootstrap is what it is because of love from its users. Now you are shutting the door in their face. Please don't do that.

**Comment by Johann-S** [comment] 2017-08-07 12:16
Bootstrap isn't an abandoned projects they are regularly new commits on our `v4-dev` branch, we just have to find time to launch our Beta 1, that's all

**Comment by jensamunch** [comment] 2017-08-07 12:24
I guess a valid question might be - would it be helpful to cut Alpha 7 as an interim solution?

We're currently using a manual download of v4-dev in a production website - not optimal.

Alternatively - would it be possible to have an NPM package tied to v4-dev?

**Comment by Johann-S** [comment] 2017-08-07 12:30
@jensamunch see : https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

We already shipped 6 alphas, I think it's enough, it's time to ship our first beta (and maybe after that a second one)

**Comment by jensamunch** [comment] 2017-08-07 12:42
thanks - i tried
npm install twbs/bootstrap#v4-dev
npm install --save git+https://github.com/twbs/bootstrap.git#v4-dev

And it only gives me Alpha 6.

How do I get the most recent v4-dev?

**Comment by Manrix** [comment] 2017-08-07 12:44
Is documentation for beta available online ? Or we can only compile it ? Thanks.

**Comment by jensamunch** [comment] 2017-08-07 12:52
@Johann-S 

Sorry to ask but what should we use for NPM install of v4-dev? I'm only getting alpha-6 whatever I try..

**Comment by bardiharborow** [comment] 2017-08-07 12:55
@jensamunch Are you sure that gives you Alpha 6? The package.json will say Alpha 6 because we haven't shipped a new version, but the code should still be bleeding edge.

**Comment by bardiharborow** [comment] 2017-08-07 13:01
@tx8821 This issue is a duplicate of #19362, #22576, #23027, #23054, #23120, #23129 and #23223. All of those issues are closed, but closed issues are not locked, and you're very welcome to comment there. If a project maintainer closes an issue however, it's not helpful to create yet more duplicates.

> v4.0.0-beta milestone is stuck at 99% for months.

And yet commits continue to be made to `v4-dev`. I'm not sure what definition of stuck you're using, but simply because the milestone doesn't have a lot of open issues assigned, doesn't mean things aren't being assigned as they are being merged. Normally when I'm managing PRs, I don't know if it's going to ship in Beta 1 until five minutes before I merge it, and hence no, it won't have been assigned to the milestone earlier.

> I'm having difficulties in soon-to-be-production projects.

What difficulties are you having? If the code isn't working for you, then please file a bug report.

**Comment by JacobLett** [comment] 2017-08-07 13:15
**Don't Stop Believin'** 
https://www.youtube.com/watch?time_continue=77&v=1k8craCGpgs

> "Great works are performed not by strength but by perseverance." Samuel Johnson

**Comment by jensamunch** [comment] 2017-08-07 14:02
thanks @bardiharborow 
you're right - npm install twbs/bootstrap#v4-dev
does work

**Comment by prowei** [comment] 2017-08-07 14:26
any roadmap？？

**Comment by coliff** [comment] 2017-08-07 14:51
@prowei - yes there are: https://github.com/twbs/bootstrap/projects

**Comment by kolkov** [comment] 2017-08-07 17:25
I took the last SCSS to do the markup and now I can not use @ng-bootstrap/ng-bootstrap, since the drop-down lists do not work now. The developers are waiting for the next release. (((

**Comment by pkozlowski-opensource** [comment] 2017-08-07 17:34
@kolkov we've got a [compatibility branch](https://github.com/ng-bootstrap/ng-bootstrap/tree/bootstrap4_beta) if you want to use [ng-bootstrap](https://ng-bootstrap.github.io) with the HEAD of the Bootstrap repo. At the moment the only remaining issue is in dropdowns and we should have it covered this week (you can track progress here: https://github.com/ng-bootstrap/ng-bootstrap/issues/1679)

Finally, as an open source project maintainer, I would like to say that I understand how hard is to estimate progress, give realistic schedule update etc. As such I think that we, as the community should say "folks, thanks for everything you are doing on Bootstrap 4 and we are here for you if you need us". I don't think that putting more pressure on people will help and issues like this one are just  draining brain cycles that otherwise could be spent on improving code.

So, my deepest THANK YOU for the Bootstrap maintainers. And if you guys can chop off some work for the community, I'm sure that there would be many who could step in and help.

**Comment by chicheng** [comment] 2017-08-08 03:59
Aren't they waiting [the sixth birthday](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/) to release the beta?

**Comment by mdo** [comment] 2017-08-08 04:14
> Aren't they waiting the sixth birthday to release the beta?

Nope! Purely coincidence that it's taken this long to get together anything close to a release :).

**Comment by C-Lodder** [comment] 2017-08-09 16:47
I too thought an Alpha 7 would have been the best approach in the interim, until beta 1 is out. I fully understand that you want to ensure no B/C breaks are made once beta 1 is out, but an alpha 7 would have (still can) be a good move, and ensure people sleep well at night.

As it stands, we started using the very early alpha in the Joomla 4.0, which is still in development. So even for us, an alpha 7 would be lovely as there are a log of small bugs that we've had to manually iron out.

Keep up the good work!

**Comment by borgfriend** [comment] 2017-08-10 17:08
I do not think that the problem is that the Beta is not being shipped, it is more that you take a look at the Milestone thing and it is for months at 99%. It is unclear how to help or what needs to be done to move the project forward. 

When you want to support development by reporting a bug with a fix you only discover that the bug has been fixed months ago. 

While at the same time, milestones for 4.3 are being opened, and issues for 4.1 are already resolved, like What the hell is going on?, why are you not shipping anything, while at the same time having 5 milestones into the future and doing already stuff for those future releases. 
That makes the Roadmap/Milestone thing utterly meaningless.

An Alpha 7 would at least clear up that, progress is being made but the team wants to keep the option available for change breaking stuff.

Even if Beta would be shipped, the big question then is will we be put into the same situation again, 99% of Bootstrap 4 is done but no final 4.0. without clear communication of what is actually going on.

For me it does not really matter when the Beta is shipped, It would be just great if the communication of what is going on would be a little clearer.

**Comment by rafalp** [comment] 2017-08-10 17:49
> It would be just great if the communication of what is going on would be a little clearer.

AFAIR at this point best way to help is to play with current master and report back issues you've encountered. Quite a lot has happened in master that the team would love to have feedback on.

It was discussed week or two back that that's the todo left for Beta 1. This is why you see it as 99%. Its done, but here and there things pop up that require fixing.

On sidenote quite a bit of issues reported on github those times are of "hey, something is weird on your docs!" "you fixed it on master? oh..." ;)

**Comment by mdo** [comment] 2017-08-10 23:23
> What the hell is going on?, why are you not shipping anything, while at the same time having 5 milestones into the future and doing already stuff for those future releases. That makes the Roadmap/Milestone thing utterly meaningless.

Managing expectations of when an open issue or pull request might be closed is just as important as merging things for an imminent release. I've provided the next few releases to bucket work, to ensure that we don't keep tackling todos without shipping as we've done to date. It doesn't make it meaningless, and gives me as maintainer a clear path forward after we ship an update.

It might not seem like much to you, but planning that far out is huge. You see it as getting in the way of a release, whereas I see it as a way to clear my head and see these groups of issues and PRs as separate efforts.

Hope that helps clarify the use of projects.

**Comment by davhdavh** [comment] 2017-08-11 02:15
If the issue holding back beta 1 is feedback, then the proper solution is ofcourse to release an alpha 7 and try to do minimal changes for beta 1, instead of trying to perfect a beta 1 and being stuck in having to do breaking changes for beta 2.

**Comment by mdo** [comment] 2017-08-11 03:32
It's feedback, it's testing, it's planning, it's having time to do a full release and be around in case anything goes wrong, it's writing the blog post for the release, it's answering follow up tweets and HN comments, it's second guessing yourself after years of development, it's saying there wouldn't be anymore alphas last time.

Beta 1, and every release before it, has been held back for a lot of reasons.

**Comment by karbassi** [comment] 2017-08-11 04:14
>It's feedback, it's testing, it's planning, it's having time to do a full release and be around in case anything goes wrong, it's writing the blog post for the release, it's answering follow up tweets and HN comments, it's second guessing yourself after years of development, it's saying there wouldn't be anymore alphas last time.

@mdo, maybe it's time to delegate some of those tasks, that is if they aren't haven't been. I understanding working in the public eye is stressful, but ask for help if you need it. 

There are so many people here willing to help out as much as they can. Do you need someone to draft up a blog post so you (team?) can review it? Need a community manager to step in and take care of tweets and HN/Reddit comments that aren't pressing?

Honestly, the community is here to help clear the road so you (and the core team) can focus on what you do best.

We ❤️ bootstrap and want it to grow.

**Comment by karbassi** [comment] 2017-08-11 04:30
@mdo don't forget to close this and pour yourself a 🍺 .

**Comment by mdo** [comment] 2017-08-11 05:06
:grin: http://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/

**Closed by mdo** 2017-08-11 05:06 UTC
Labels: meta, v4
