### ISSUE TITLE
Bootstrap v4 navbar hiding

### ISSUE THREAD

**Issue by berkaybeyaz1** [twbs/bootstrap#17375] opened 2015-08-27 22:34 UTC
Hi , this my code.. 
```
<div class="container-fluid">
	<nav class="navbar navbar-light bg-faded navbar-fixed-top">
  <a class="navbar-brand" href="#">Navbar</a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Features</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Pricing</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">About</a>
    </li>
  </ul>
  <form class="form-inline navbar-form pull-right">
    <input class="form-control" type="text" placeholder="Search">
    <button class="btn btn-success-outline" type="submit">Search</button>
  </form>
</nav>
</div>
<div class="container-fluid">
	<div class="row">
	<div class="col-md-6">Text 1</div>
	<div class="col-md-6">Text 2</div>
</div>
</div>
```
but i dont seen is my text

**Comment by patrickhlauke** [comment] 2015-08-27 22:35
duplicate of https://github.com/twbs/bootstrap/issues/17374

**Closed by patrickhlauke** 2015-08-27 22:35 UTC
