### ISSUE TITLE
Allow prefix on getbootstrap.com/customize/

### ISSUE THREAD

**Issue by shaneshuford** [twbs/bootstrap#16740] opened 2015-07-01 19:05 UTC
Downloading the bootstrap LESS files, then compiling them inside of 

    .bs-styles {
        @import "less/bootstrap.less";
    }

or similar works, but it would be great if you could set a prefix on the customize page on the getbootstrap.com website.

This way bootstrap styling dosn't have to be sitewide, and can be contained to an individual element, or group of elements.

    <div class="bs-styles">
        <div class="container">
        </div>
    </div>

**Comment by cvrebert** [comment] 2015-07-01 21:22
Duplicate of #12654.

**Closed by cvrebert** 2015-07-01 21:22 UTC
Labels: css, customizer, feature
