### ISSUE TITLE
Input height has unvalid height

### ISSUE THREAD

**Issue by piernik** [twbs/bootstrap#29752] opened 2019-11-27 12:01 UTC
In `bootstrap@4.4.0` there is problem with `form-control`'s height. In chrome's console I see that: `calc(1.5em + 0.75rem2px)`.

I suppose it should be `calc(1.5em + 0.75rem - 2px)`.

I'm using `scss` version with `@import "~bootstrap/scss/bootstrap";`

**Comment by nicolomonili** [comment] 2019-11-27 12:50
duplicate of [https://github.com/twbs/bootstrap/issues/29743](https://github.com/twbs/bootstrap/issues/29743)

**Closed** 2019-11-27 13:00 UTC
Labels: duplicate
