### ISSUE TITLE
Weird bouncing carousel

### ISSUE THREAD

**Issue by SamThilmany** [twbs/bootstrap#22420] opened 2017-04-12 11:33 UTC
The carousel has a weird bouncing effect when sliding to a new image. On my website it's even stronger than in the [pen](http://codepen.io/SamThilmany/full/aWbzRy/), but you can still notice what I mean. Watch my short [screen-capture video](http://de.tinypic.com/r/2q3t1c6/9) (requires Flash 9 or later), to see the stronger effect on my website.

The new slide comes in, then seems to go back for 5 pixels or so and then slides forward again very gently to fill up it's space. On my website it slides back for approx. 15 to 20 pixels which looks very weird. I'm using the second method (divs with a `background-image`) shown in my pen on my website. The stronger effect may be caused by the bigger picture or something else. After all, I think that the slides should come in without any bouncing...

---

Little tip: To make Bootstrap V4 even better, how about adding different effects to the carousel? A fading effect for example would be cool to have build in.

**Comment by oktalk** [comment] 2017-04-12 15:01
I'm thinking this issue has been solved already. However, there hasn't been a new release cut from dev in a while. I've updated your pen by removing the old released version of Bootstrap and replacing it with the latest dist from dev. You can see that the bouncing (or gradually sliding issue that I was seeing) is not present:
https://codepen.io/oktalk/pen/eWYBJR

Could you retest your issue using the latest dist from the repo? It would help confirm whether or not the issue still exists: https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.min.css

There has been 250 commits since the last release. I think we should cut a new one.

**Comment by SamThilmany** [comment] 2017-04-12 15:25
As I'm working with SCSS, I just downloaded the latest `.zip`-file. The [result](http://de.tinypic.com/r/29yo1gy/9) ist less extreme, but still there. In addition, my navigation is now immediately in mobile mode although it contains the class `navbar-toggleable-md` ...

Seems to be pretty buggy 😒

**Comment by mdo** [comment] 2017-04-13 02:01
Dupe of #21685. Should be fixed in latest `v4-dev`.

**Closed by mdo** 2017-04-13 02:01 UTC
