### ISSUE TITLE
Several Rows in Container - Not all rows equal

### ISSUE THREAD

**Issue by CHBIV007** [twbs/bootstrap#27260] opened 2018-09-17 23:12 UTC
I have a container, in it are 5 rows of buttons. I cannot for the life of me figure out why they are not all equal when i am not specifying a width at all. can anyone please help??

See enclosed files. 

thank you very much. 

![button spacing](https://user-images.githubusercontent.com/17656234/45655297-3ad89a00-ba94-11e8-8684-fa39ebbbdc50.png)
[button spacing code.txt](https://github.com/twbs/bootstrap/files/2390563/button.spacing.code.txt)

**Comment by mdo** [comment] 2018-09-18 04:56
Next time, share your demo code in a CodePen or JS Bin, please.

Looking at it, you apparently have some markup issues. You're not properly closing the row after closing the column. Take a look at https://codepen.io/anon/pen/MqPLqg which shows this working as intended.

**Closed by mdo** 2018-09-18 04:56 UTC
