### ISSUE TITLE
Placeholder (no href) <a> btn has different text color than non-placeholder <a>

### ISSUE THREAD

**Issue by gslender** [twbs/bootstrap#19726] opened 2016-04-12 23:40 UTC
Hi, using Alpha 2 with no major issues. Figured I'd try switching the current Dev V4 branch (as of April 11th) and few things have changed (most obvious is font sizes) but major issue seems to be font color when using icons (FontAwesome) are black on dark button color instead of white. Not sure why and how this occurred, but switching back to the Alpha 2 css/js and all looks fine again.

**Comment by cvrebert** [comment] 2016-04-12 23:54
We are unable to provide assistance with third-party libraries such as FontAwesome. Sorry.

Also, icon fonts are apparently The Wrong Approach™ now; see the links in https://github.com/twbs/bootstrap/issues/18588#issue-122513421

**Comment by gslender** [comment] 2016-04-12 23:59
Seriously? You are going to launch with Alpha 3 and essentially leave issues with FontAwesome not working with no explanation at all ??? Especially considering it  worked fine in BS3 and BS4 Alpha 2 ????  

This just makes me rethink using Bootstrap V4 and stick with V3 or move on to another framework.

Also, why bother reporting issues at all if the effort to respond is "sorry can't help" when in the past it was working fine. I'm certainly discouraged to bother reporting bugs and again, just move on to another framework that is more open to bug reporting.

**Comment by cvrebert** [comment] 2016-04-13 00:07
Can you post a demo of the problem?

**Comment by patrickhlauke** [comment] 2016-04-13 10:11
> issues with FontAwesome not working with no explanation at all

as previously Bootstrap wasn't, to my knowledge, doing anything specific to ensure it works with FA, the issue is either with FA or with the specific way in which FA is being used together with Bootstrap. And yes, without a live reduced test case showing the problem there's little that can be done - and even then, it's likely that the fix is not something that needs to be done in Bootstrap, but rather a change/addition to how FA is being used.

**Comment by gslender** [comment] 2016-04-13 11:45
I'll work on posting a demo when I can - will take me a bit as I can't easily get the current Dev branch up anywhere to show a demo. None of the fiddle or bootply places will work on Github hosted code!! Do you know of a simple way to show a demo using the current Dev V4 branch ??

I've reported it. If I'm wrong and the issue is with me or with a broken aspect of FA then all good. But if not, then you've at least had it reported. The fact you can't be bothered isn't really my problem - I'm sure you'd be 1000x faster than me to bring a few button examples with FA icons together.

So far, everything in Alpha2 seems to work well enough that it isn't bothering me that much - was just interested to see how the current Dev branch was going and this bug / issue showed up fairly quickly. I was thinking that if it was a FA issue then it wouldn't have worked in Alpha2, but I guess you changed something for Alpha3 that you've yet to pass onto the broader group that breaks FA etc... up to you to decide how to manage that change. I'm sure you know the guys there to ping and let them know.

**Comment by patrickhlauke** [comment] 2016-04-13 12:15
using local build of latest v4-dev branch, and the MaxCDN version of FA `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">`, it all seems to be working fine. as such, i'd suggest it's something with your specific implementation/use of FA...

<img width="845" alt="capture" src="https://cloud.githubusercontent.com/assets/895831/14492805/a5ee0ed2-0179-11e6-9cc3-d1f2a2ec0eb0.PNG">

**Comment by cvrebert** [comment] 2016-04-13 12:50
> Do you know of a simple way to show a demo using the current Dev V4 branch ??

I usually just copy-paste the contents of https://raw.githubusercontent.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css into the CSS editor area of JSFiddle.

**Comment by gslender** [comment] 2016-04-13 21:43
There you go....
https://jsfiddle.net/48njm6yk/

**Comment by patrickhlauke** [comment] 2016-04-13 22:08
That issue is due to the (mis)use of `<a>` without an `href` attribute, meaning that it's a named anchor rather than a link. (though it's generally even more advisable to use an actual `<button>` element. see all examples on http://v4-alpha.getbootstrap.com/components/buttons/

**Comment by cvrebert** [comment] 2016-04-13 23:35
Yeah, the `a:not([href]) { color: inherit; }` reset is trumping `.btn-danger { color: #fff; }` due to specificity.

**Comment by cvrebert** [comment] 2016-04-13 23:37
(And the FontAwesome part turned out to be a red herring. This problem isn't specific to icons at all.)

**Comment by gslender** [comment] 2016-04-13 23:44
Well, glad the issue turned out to a) be real b) be relevant and c) not be with my code. I'll probably swap to `<button>` tags where I can and ensure any remaining `<a>` links have hrefs

**Comment by ItsJonQ** [comment] 2016-04-23 19:24
To fix this specifically for `.btn` usage (but also keep `:not([href])` in the reset), the following can be added to `.btn` as well as the end of the `button-variant` and `button-outline-variant` mixins.

```
  &:not([href]) {
    color: $color;
  }
```

**Comment by mdo** [comment] 2016-10-28 04:54
Closing as a won't fix. I don't want to go down the path of overriding that gnarly selector if it's not absolutely necessary.

**Closed by mdo** 2016-10-28 04:54 UTC
Labels: confirmed, css, v4
