### ISSUE TITLE
v4 - Consider adding tabs to cards

### ISSUE THREAD

**Issue by abitdodgy** [twbs/bootstrap#17123] opened 2015-08-20 12:30 UTC
I'm just putting this out there. This was an often requested feature in v3, to have tabs be embeddable in panels. Since panels are gone in favor of cards, I wonder if it makes sense to have them in cards? See https://github.com/twbs/bootstrap/issues/16934

**Comment by hnrch02** [comment] 2015-08-20 13:54
I'll close this a duplicate of #16934.

**Closed by hnrch02** 2015-08-20 13:54 UTC
