### ISSUE TITLE
btn and btn-outline colors not matching

### ISSUE THREAD

**Issue by nizar787** [twbs/bootstrap#38817] opened 2023-06-23 18:33 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I'm sure it's intentional so far, but I think - especially when a filled button and an outline button are next to each other - it's a bit confusing that the colors are different for hover and active on both buttons. So my idea would be that also an outline button gets the same color for :hover and :active as the normal button.

### Reduced test cases

test case 

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.1

**Comment by mdo** [comment] 2023-06-25 17:59
Duplicate of #38670.

**Closed by mdo** 2023-06-25 17:59 UTC
Labels: v5, design
