### ISSUE TITLE
Scrollspy: highlights wrong navigation item when a page is reloaded.

### ISSUE THREAD

**Issue by DeboBuiz** [twbs/bootstrap#32496] opened 2020-12-15 19:25 UTC
- Operating system and version : Windows 10
- Browser and version: Chrome latest

https://codepen.io/debobuiz/pen/ZEpempL

**Issue:** Please refer the screenshot. I have scrolled the page to Item 1. But in the navbar, "Item 3" is highlighted.

![image](https://user-images.githubusercontent.com/9299145/102262196-bc038d80-3f38-11eb-9750-d6f9785af196.png)

**How to reproduce the issue:**
When the page is opened initially, things will be fine. Scroll the page to item 3 or item 4. Then right-click and "reload frame" in the codepen.io preview section. Now, when you scroll the page through various items, the correct item will not be highlighted in the navbar.

**Comment by Neelam-Nishad** [comment] 2020-12-15 19:57
I want to work on this

**Comment by Neelam-Nishad** [comment] 2020-12-15 20:01
I refreshed 2-3 times and its working fine

**Comment by DeboBuiz** [comment] 2020-12-15 20:06
Did you reload the whole page 3 times? You need to right click on the html
output in the codepen.io and select the "reload frame " option. Before
reloading scroll the page to a different section, say item 3 or 4

**Comment by DeboBuiz** [comment] 2020-12-15 20:10
You may copy the code in a local html file too and recreate the issue by scrolling to a different section and reloading the page.

**Comment by Neelam-Nishad** [comment] 2020-12-15 20:27
yes I understand the problem now

**Comment by Neelam-Nishad** [comment] 2020-12-15 20:32
> You may copy the code in a local html file too and recreate the issue by scrolling to a different section and reloading the page.

I copied the code in my local, and its really working fine there , even after reloads. may be the problem is with codepen.io.

**Comment by DeboBuiz** [comment] 2020-12-16 03:07
I found the issue while working on a project. In order to report the bug, I
created the demo in codepen. In fact, I copied the codepen code in the
local file and tested the issue locally too. I don't know how you tested
it. As I said, you need to scroll the page to a different section. Then
click on the browser refresh button. Now, you would observe that incorrect
navigation items are highlighted, when you scroll the page through
different sections.

**Comment by DeboBuiz** [comment] 2020-12-16 04:16
@Neelam-Nishad  I have pasted the complete demo code here. you may copy this to you local file and test it out.

`<!doctype html>
<html lang="en">
<head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>

  <body data-bs-spy="scroll" data-bs-target="#navbarResponsive" data-bs-offset="100" style="padding-top: 100px;">
    <nav class="navbar navbar-light navbar-expand-lg fixed-top bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#page-top">
          DEMO
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto me-2">
            <li class="nav-item"><a class="nav-link " href="#item1">Item 1</a></li>
            <li class="nav-item"><a class="nav-link " href="#item2">Item 2</a></li>
            <li class="nav-item"><a class="nav-link " href="#item3">Item 3</a></li>
            <li class="nav-item"><a class="nav-link " href="#item4">Item 4</a></li>
            <li class="nav-item"><a class="nav-link " href="#item5">Item 5</a></li>
          </ul>

        </div>
      </div>
    </nav>
    
    <section class="border border-5 bg-warning w-100 text-center display-1" id="item1" style="height: 500px;">Item 1</section>
    <section class="border border-5 bg-info  w-100 text-center display-1" id="item2" style="height: 500px;">Item 2</section>
     <section class="border border-5 bg-warning w-100 text-center display-1" id="item3" style="height: 500px;">Item 3</section>
     <section class="border border-5 bg-info w-100 text-center display-1" id="item4" style="height: 500px;">Item 4</section>
     <section class="border border-5 bg-warning w-100 text-center display-1" id="item5" style="height: 200vh;">Item 5</section>

    

    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
  </html>`

**Comment by NightZan999** [comment] 2020-12-18 07:09
Same thing happens with me!

**Comment by aribudin** [comment] 2020-12-19 01:40
Same problem
if you scroll down (content 3 and navlink 3) and reload the page, after reloading the page scroll again to top. You will get the problem ( content 1 in navlink 3 )

**Comment by harnishdesign** [comment] 2020-12-19 10:40
I am working on my project for migration v4 to v5. This is same happens with me in v5 after reloading the page scroll again. It was working fine in v4.

**Comment by sormiston** [comment] 2020-12-23 05:32
This is not isolated.  Scrollspy is extremely buggy.

**Comment by aribudin** [comment] 2020-12-23 07:26
I hope this problem will fixed in stable release version

**Comment by NightZan999** [comment] 2020-12-24 12:39
> This is not isolated. Scrollspy is extremely buggy.

Exactly! Scrollspy has like 170 issues currently which have not been resolved. Normal scrollspy (not using bs4 to do them) might be a better option. Only that when working with BS you can't use normal scrollspy because of overrides! 

**If you migrate your project to v5 it may not happen, although I am not sure of this**

**Comment by NightZan999** [comment] 2020-12-24 12:43
I am pretty sure this is actually a problem with the javascript of bootsrap scrollspy check #32600 about the same. Shows in depth details about the javascript and source code. **I might legit fork this and correct and make some changes.**

**Comment by NightZan999** [comment] 2020-12-24 12:57
So basically, the last refreshed item when reloaded gets highlighted. This is because bootstrap logs the last scroll and puts a certain item in the navbar (class: nav-item) with it! Then sees last scroll made and highlights the nav-item which is paired with it. 

The javascript has to be reworked on because, scrollspy is very glitchy.

**Comment by AvWoN** [comment] 2021-01-17 04:10
> So basically, the last refreshed item when reloaded gets highlighted. This is because bootstrap logs the last scroll and puts a certain item in the navbar (class: nav-item) with it! Then sees last scroll made and highlights the nav-item which is paired with it.

I don't think this is the issue. From inspecting the scrollspy element, to me it looks like target offsets (stored in '_offsets') are recalculated from the current scroll position instead of from the 0 scroll position, so when the page loads with a scroll position that is not the top, or 0, it will calculate faulty offsets. Didn't look into the code but I am assuming its because the code to get elements offset on page (which i think is deperecated code) was replaced with code like .getBoundingClientRect().top (which i think is new standard and more accurate) but which gets relative offset to current scroll. The problem is that we do not stick to either scheme (we either have to stick to current relative window offset solution or the old scroll page offset solution)

The hot fix seems extremely simple, when computing offsets, simply add current scroll position to the relative offset value we have right now. For example, we load/reload page into scroll position 1000, we have a elements at page offsets [200, 600, 1500], but does computed offset will be [-800, -500, 500] so simply add the current position and you will get the original values.

```
function hotfixScrollSpy() {
    var dataSpyList = [].slice.call(document.querySelectorAll('[data-bs-spy="scroll"]'))
    let curScroll = getCurrentScroll();
    dataSpyList.forEach(function (dataSpyEl) {
        let offsets = bootstrap.ScrollSpy.getInstance(dataSpyEl)['_offsets'];
        for(let i = 0; i < offsets.length; i++){
            offsets[i] += curScroll;
        }
    })
}

function getCurrentScroll() {
    return window.pageYOffset || document.documentElement.scrollTop;
}

window.onload = function () {
    hotfixScrollSpy();
}
```
Im fairly new to web dev so might be wrong about some things. Also one issue is that the initial header is going to be calculated wrong but as soon as you scroll it will correct itself, this is just a quick hotfix, not a solution, but this might lend someone to implement a solution within bootstrap itself. Sad thing is I thought this was my problem (as in I did something wrong) in the beginning and I didnt know what was going on and that was very demotivating. Didn't really work on my project for more than a week cuz everytime I tried I got nowhere, and if I simply never knew about scroll spy I would have made my own equivalent implementation of this concept in only a day or two, and not fumble around for a week until you accidentally notice that the first scroll spy example in the v5.0 docs also has the issue and thus I am not at fault. I guess that what u get for mucking around with WIP libraries :)

**Comment by DigiLive** [comment] 2021-03-14 00:18
> Im fairly new to web dev so might be wrong about some things. Also one issue is that the initial header is going to be calculated wrong but as soon as you scroll it will correct itself, this is just a quick hotfix, not a solution.

Chapeau on finding this, especially when stating yourself as fairly new.
I'm gonna use this for now and scroll the page 1px with java script to 'fix' the remaining issue.
```js
window.onload = function () {
    hotfixScrollSpy();
    window.scrollBy(0,1);
}
```
Hopefully the developers will take notice and fix the bootstrap component soon.

**Comment by UnHumbleBen** [comment] 2021-03-20 04:40
@AvWoN @DigiLive thanks for finding a hotfix!

The solution makes sense in principle, but I'm running into an issue with the `getInstance` function, which is returning `none`. Does `getInstance` fail if Scrollspy element is set to `<body>`? Did you encounter this issue?

**Comment by DigiLive** [comment] 2021-03-20 08:56
I'm no expert either, but this is my 5 cents...

`getInstance` returns `null` when the bootstrap library is not finished with loading while calling it.
I guess if you make the call manually at some later moment, it doesn't return `null`.

At first I tried to apply the hotfix at `$(function(){});` (document ready), which fires at DOM ready, but it is to soon.
DOM loading is finished before content loading, hence `window.onload` or `$(window).on('load', function() {});`.

**Comment by PetersOtto** [comment] 2021-03-20 18:03
Same problem here. The hotfix do not solve the problem for me.

**Comment by UnHumbleBen** [comment] 2021-03-20 19:59
> Same problem here. The hotfix do not solve the problem 

What exactly is the problem with the hot fix? Is there an error in the console?

**Comment by PetersOtto** [comment] 2021-03-21 08:22
Hello UnHumbleBen,
no, there are no errors in the console.

On my website scrollspy is working fine. However when I resize the browser, scrollspy crashes. 
When I scroll to the top of the page and reload it, it works again (so long I resize the window)

Have a look to the Screenshot. Active is "Referenzen" but "Home" should be active.
![ScrollSpyBs5](https://user-images.githubusercontent.com/52236754/111898493-ac5b7f80-8a26-11eb-84af-086c6072fa39.png)

In my opinion that is exactly the problem that is described above.

I use the following js code but it does not work.

`


function hotfixScrollSpy() {
  var dataSpyList = [].slice.call(document.querySelectorAll('[data-bs-spy="scroll"]'))
  let curScroll = getCurrentScroll();
  dataSpyList.forEach(function (dataSpyEl) {
      let offsets = bootstrap.ScrollSpy.getInstance(dataSpyEl)['_offsets'];
      for(let i = 0; i < offsets.length; i++){
          offsets[i] += curScroll;
      }
  })
}

function getCurrentScroll() {
  return window.pageYOffset || document.documentElement.scrollTop;
}

window.onload = function () {
  new bootstrap.ScrollSpy(document.body, {
    target: '.navbar',
    offset: 20
  });  hotfixScrollSpy();
  window.scrollBy(0,1);
}

`

**Comment by UnHumbleBen** [comment] 2021-03-22 03:08
@PetersOtto 

Same issue. The hotfix only corrects offsets when page is reloaded but not when it is resized. Been trying to come up with with a hotfix for resizing but no luck so far

**Comment by DigiLive** [comment] 2021-03-22 08:24
Since the issue was about a reload, it doesn't take a resize in consideration.
Maybe you can use the window.resize event to refresh the spies and apply the hotfix again.
```js
$(window).resize(function() {
  'use strict';
  const dataSpyList = [].slice.call(document.querySelectorAll('[data-bs-spy="scroll"]'));
  dataSpyList.forEach(function(dataSpyEl) {
    bootstrap.ScrollSpy.getInstance(dataSpyEl).refresh();
  });
  hotfixScrollSpy();
  window.scrollBy(0, 1);
});
```

**Comment by harnishdesign** [comment] 2021-03-30 10:09
Issue is still in **bootstrap-5-beta-3**. have you finally any fixed by officially ?

**Comment by mw-itworks** [comment] 2021-05-26 08:21
Using Bootstrap 5.1 I also stumbled over this issue.

To get the suggested hotfixScrollSpy function (including the window.scrollBy(0,1) added by unHumbleBen) to work, I have simply postponed calling hotfixScrollSpy() using setTimeout - a delay of 50 ms worked for me.

Maybe this helps others here as well...

**Comment by ali-dev-code** [comment] 2021-06-16 20:42
I am also having issue with bootstrap 5.0.1 scroll spy with list group,
when I refresh the page scroll spy the active wrong links.
Please solve it? anyone has solved it?
Thanks

**Comment by kentangbakar89** [comment] 2021-06-22 07:26
> I am also having issue with bootstrap 5.0.1 scroll spy with list group,
> when I refresh the page scroll spy the active wrong links.
> Please solve it? anyone has solved it?
> Thanks

I think 5.0.1 version is more stable than 5.0.0 or beta version. Have you tried scrollspy on 5.0.0 version too? I don't have the CDN (css & js) links. So, i hope someone can help me here

**Comment by ali-dev-code** [comment] 2021-06-22 16:52
I tried bootstrap 4.6. Scrollspy works perfectly with 4.6.

**Comment by Kim-Theng** [comment] 2021-06-23 17:16
> I tried bootstrap 4.6. Scrollspy works perfectly with 4.6.

Thank you

**Closed** 2021-07-28 14:23 UTC
Labels: js

**Comment by IlliaOstrovskyi** [comment] 2021-09-14 10:05
I tried bootstrap 5.1.1. Seems it's fixed.

**Comment by AvWoN** [comment] 2021-09-14 14:00
> 
> 
> I tried bootstrap 5.1.1. Seems it's fixed.

FINALLY, can confirm, only took 9 months :). Thank you @alpadev , much appreciated!

**Comment by umer936** [comment] 2022-03-25 17:26
This still appears to be the case for me on 5.1.3 

On page load, it highlights the last nav-item
