### ISSUE TITLE
How to disable ul-li borders in card?

### ISSUE THREAD

**Issue by kolkov** [twbs/bootstrap#20680] opened 2016-09-08 21:36 UTC
Is it possible to remove left and right border from `<ul>-<li>` elements in card natively?

![image](https://cloud.githubusercontent.com/assets/3740898/18367438/d42be0e8-7623-11e6-8b12-2c91a968cb4d.png)
http://v4-alpha.getbootstrap.com/components/card/#content-types

I think that this looks more elegant:
![image](https://cloud.githubusercontent.com/assets/3740898/18367490/14bee15a-7624-11e6-9b94-a36f39a0109b.png)
but is this case I use addition styles on `<li>` elements.
`<li class="list-group-item text-xs-right" style="border-right: none; border-left: none">`

Thanks an advance!

**Comment by wolfy1339** [comment] 2016-09-08 21:58
The borders are applied because of the `.list-group-item` class

**Comment by Starsam80** [comment] 2016-09-08 22:28
I think this is a duplicate of #20395

**Comment by wolfy1339** [comment] 2016-09-09 00:09
Yes, I agree that it is

**Comment by cvrebert** [comment] 2016-09-09 03:29
Closing as duplicate.

**Closed by cvrebert** 2016-09-09 03:29 UTC
