### ISSUE TITLE
a class="btn" in div class="well" - background disappears by hover event in IE

### ISSUE THREAD

**Issue by petrfox** [twbs/bootstrap#19457] opened 2016-03-10 08:46 UTC
http://jsfiddle.net/goe3b681/

**Comment by twbs-lmvtfy** [comment] 2016-03-10 08:46
Hi @petrfox!

You appear to have posted a live example (http://fiddle.jshell.net/goe3b681/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 74, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`
* line 33, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.0.0
* line 37, column 7: [W013](https://github.com/twbs/bootlint/wiki/W013): Bootstrap version might be outdated. Latest version is at least 3.3.6 ; saw what appears to be usage of Bootstrap 3.0.0

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by patrickhlauke** [comment] 2016-03-10 08:53
cannot reproduce any strange effect in IE11. what exactly is the problem you're seeing, which version of IE, and does it just happen in IE or other browsers as well?

**Comment by Ruffio** [comment] 2016-03-10 09:28
Using Edge 25.10586.0.0 I can't reproduce any strange behaviour either.

**Comment by petrfox** [comment] 2016-03-10 09:42
Hi,

a new jsfiddle example with Bootstrap 3.3.6 : 
https://jsfiddle.net/petrfox/rxknoosL/ . Bug is in IE 11.

Petr Fox

Dne 10.3.2016 v 9:51 twbs-lmvtfy napsal(a):

**Comment by twbs-lmvtfy** [comment] 2016-03-10 09:42
Hi @petrfox!

You appear to have posted a live example (https://fiddle.jshell.net/petrfox/rxknoosL/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 62, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by petrfox** [comment] 2016-03-10 09:43
Hi,

a new jsfiddle example with Bootstrap 3.3.6 : 
https://jsfiddle.net/petrfox/rxknoosL/ . Bug is in IE 11 only.

Petr Fox


Dne 10.3.2016 v 9:56 Patrick H. Lauke napsal(a):

**Comment by twbs-lmvtfy** [comment] 2016-03-10 09:43
Hi @petrfox!

You appear to have posted a live example (https://fiddle.jshell.net/petrfox/rxknoosL/show/light/), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* line 62, column 3: [E003](https://github.com/twbs/bootlint/wiki/E003): Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`
* [W005](https://github.com/twbs/bootlint/wiki/W005): Unable to locate jQuery, which is required for Bootstrap's JavaScript plugins to work

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by Ruffio** [comment] 2016-03-10 09:48
[2016-03-10 10h46_45.zip](https://github.com/twbs/bootstrap/files/166877/2016-03-10.10h46_45.zip)

I still can't see anything wrong.

**Comment by patrickhlauke** [comment] 2016-03-10 09:49
> Bug is in IE 11 only.

describe your bug. not seeing anything wrong (in any browser, including IE 11)

**Comment by petrfox** [comment] 2016-03-10 10:06
https://jsfiddle.net/petrfox/5cz8a3p5/

Only for IE 11






Dne 10.3.2016 v 10:52 Patrick H. Lauke napsal(a):

**Comment by Ruffio** [comment] 2016-03-10 10:11
Still no problem:

[2016-03-10 11h10_49.zip](https://github.com/twbs/bootstrap/files/166909/2016-03-10.11h10_49.zip)

**Comment by petrfox** [comment] 2016-03-10 11:01
I have a problem yet...

Dne 10.3.2016 v 11:15 Rasmus Christiansen napsal(a):

**Comment by patrickhlauke** [comment] 2016-03-10 11:07
Sorry, but as you're not explaining (after repeated requests) what your actual problem is, and we can't actually reproduce any broken/problematic behavior from your fiddle, I'm closing this.

**Closed by patrickhlauke** 2016-03-10 11:07 UTC
Labels: awaiting reply
