### ISSUE TITLE
Accordion example Parent Issue

### ISSUE THREAD

**Issue by eoflexweb** [twbs/bootstrap#16925] opened 2015-08-03 04:18 UTC
Dear Team,
Hi, I just using Accordion example with data-parent.But if we can use same format which is given in your website.Its working fine but if we can use without panel then this is not working perfectly.
I have solution for that.You can replace 577 line in bootstrap.js which is "var actives = this.$parent && this.$parent.children('.panel').children('.in, .collapsing')" with "var actives = this.$parent && this.$parent.find('.panel-collapse.in, .panel-collapse.collapsing')".Its working in both part.
Thank you.

**Comment by cvrebert** [comment] 2015-08-03 04:43
Duplicate of #10966.

**Closed by cvrebert** 2015-08-03 04:43 UTC
