### ISSUE TITLE
Breakpoints behave differently after build bootstrap v5

### ISSUE THREAD

**Issue by marcio1002** [twbs/bootstrap#36729] opened 2022-07-13 01:11 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

**Hi!**
I came across the same bug issue several times with breakpoints behaving differently when built. For example if I write like this:
```html
  <div class="col-12 col-lg-5">my div</div>
```
Em testes locais o css se comporta como esperado, dez do extra grande para o mais largo serão 5 colunas, abaixo disso ocupará 12 colunas. But after being built (when the platform is in production), the css is not as expected, it seems that the `col-12` class ends up being preferred over the `col-lg-5` class when it is in a large width. It's not just the `col` breakpoints but also the margins and others.

### Reduced test cases

https://codepen.io/marcio1002-the-typescripter/pen/PoRGOKj

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v4

**Comment by julien-deramond** [comment] 2022-07-13 05:50
I'm not sure to understand the issue here. In the description is mentioned `<div class="col-12 col-lg-5">my div</div>` and in the CodePen we can find `<div class="col-11 col-lg-8 mx-auto mx-lg-0 py-5">` which seems to work as expected on Linux + Firefox.
Could you please add some details?

**Comment by marcio1002** [comment] 2022-07-13 13:52
I didn't mention that this happened in a vuejs application. I don't know if it also has to do with CSS scope preferences defined in these frameworks/libs. In CodPen I put it the way it would work, and it is in a pure page with HTML, I would need to test it on a site developed with vuejs.
I'm sorry I put version 5 of bootstrap but it's 4

**Comment by marcio1002** [comment] 2022-07-13 13:57
This is the version I'm using.

**bootstrap:** ^4.5.2
**bootstrap-vue**: "^2.21.2"

**Comment by mdo** [comment] 2022-07-19 20:02
Closing as not a bug in Bootstrap for now :).

**Closed by mdo** 2022-07-19 20:02 UTC
Labels: awaiting-reply, v4, needs-example
