### ISSUE TITLE
Scrollbar overlaps content on desktop IE

### ISSUE THREAD

**Issue by usefulBee** [twbs/bootstrap#18543] opened 2015-12-11 19:15 UTC
This issue is still going on even in IE 11. 

The issue comes down to the following bootstrap.css rule:
@-ms-viewport {
  width: device-width;
}

The temporary solution is to override the rule in another css file:
@-ms-viewport{
    width:auto!important;
} 

It would be nice to see this issue taken into consideration in future releases.

Thank you.

**Comment by patrickhlauke** [comment] 2015-12-11 20:09
do you have a reduced test case (in jsfiddle or similar)? IE11 on mobile or desktop/laptop?

**Comment by usefulBee** [comment] 2015-12-11 21:20
@patrickhlauke, I am afraid it would be difficult to replicate the issue in jsfiddle since jsfiddle has its own containers and therefor the issue does not appear. For example, I edited the following example, so there would be many table columns and rows, but that is not enough to trigger IE scrollbar to show up"
http://jsfiddle.net/L46FX/1965/

I experienced the issue on IE11 desktop/laptop.

**Comment by twbs-lmvtfy** [comment] 2015-12-11 21:20
Hi @usefulBee!

You appear to have posted a live example (http://fiddle.jshell.net/L46FX/1965/show/light/), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 51, column 25 thru line 52, column 13: Saw ```` < ```` when expecting an attribute name. Probable cause: Missing ```` > ```` immediately before.
* line 51, column 25 thru line 52, column 16: End tag had attributes.
* line 52, column 17 thru column 29: Misplaced non-space characters insided a table.
* line 52, column 17 thru column 29: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment] 2015-12-12 07:53
@usefulBee Try JS Bin then. It has no such containers in its output view (e.g. http://output.jsbin.com/vujito ).
(And also, please fix the HTML as @twbs-lmvtfy pointed out.)

**Comment by twbs-lmvtfy** [comment] 2015-12-12 07:53
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/vujito/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 16, column 6 thru column 23: The ```` align ```` attribute on the ```` div ```` element is obsolete. Use CSS instead.
* line 22, column 8 thru line 23, column 19: The ```` align ```` attribute on the ```` tr ```` element is obsolete. Use CSS instead.
* line 23, column 20 thru line 24, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 24, column 21 thru column 24: Stray end tag ```` a ````.
* line 24, column 30 thru line 25, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 25, column 26 thru column 29: Stray end tag ```` a ````.
* line 25, column 35 thru line 26, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 26, column 22 thru column 25: Stray end tag ```` a ````.
* line 26, column 31 thru line 27, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 27, column 24 thru column 27: Stray end tag ```` a ````.
* line 27, column 33 thru line 28, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 28, column 21 thru column 24: Stray end tag ```` a ````.
* line 28, column 30 thru line 29, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 29, column 24 thru column 27: Stray end tag ```` a ````.
* line 29, column 33 thru line 30, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 30, column 25 thru column 28: Stray end tag ```` a ````.
* line 30, column 34 thru line 31, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 31, column 24 thru column 27: Stray end tag ```` a ````.
* line 31, column 33 thru line 32, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 32, column 23 thru column 26: Stray end tag ```` a ````.
* line 32, column 32 thru line 33, column 16: The ```` align ```` attribute on the ```` td ```` element is obsolete. Use CSS instead.
* line 33, column 28 thru column 31: Stray end tag ```` a ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by usefulBee** [comment] 2015-12-15 18:19
@cvrebert , thank you for the alternative. I managed to replicate the issue using jsbin and applying custom css rule of width: device-width; (http://output.jsbin.com/kixuduhupa)

In the attached screenshot, the far right column is overlapped by IE scrolling bar.
![2015-12-15_1313](https://cloud.githubusercontent.com/assets/7525928/11819495/274918d2-a32e-11e5-8259-476b6ddbc29b.png)

**Comment by twbs-lmvtfy** [comment] 2015-12-15 18:19
Hi @usefulBee!

You appear to have posted a live example (http://jsbin.com/kixuduhupa/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 14, column 25 thru line 15, column 13: Saw ```` < ```` when expecting an attribute name. Probable cause: Missing ```` > ```` immediately before.
* line 14, column 25 thru line 15, column 16: End tag had attributes.
* line 15, column 17 thru column 29: Misplaced non-space characters insided a table.
* line 15, column 17 thru column 29: Cannot recover after last error. Any further errors will be ignored.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment] 2015-12-16 09:17
Forcing revalidation: http://output.jsbin.com/kixuduhupa

**Comment by twbs-lmvtfy** [comment] 2015-12-16 09:17
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/kixuduhupa/edit), which is always a good first step. However, according to [Bootlint](https://github.com/twbs/bootlint), **your example has some Bootstrap usage errors**, which might potentially be causing your issue:
* [W002](https://github.com/twbs/bootlint/wiki/W002): `<head>` is missing X-UA-Compatible `<meta>` tag that disables old IE compatibility modes
* [W003](https://github.com/twbs/bootlint/wiki/W003): `<head>` is missing viewport `<meta>` tag that enables responsiveness

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by cvrebert** [comment] 2015-12-16 09:21
You appear to be referring to the IE10 Mobile bug (http://v4-alpha.getbootstrap.com/getting-started/browsers-devices/#internet-explorer-10-in-windows-phone-8 ), but on desktop somehow...

**Comment by cvrebert** [comment] 2015-12-16 09:24
(Edited your bin to add the two recommended `<meta>` tags.)

**Comment by cvrebert** [comment] 2015-12-16 09:29
@usefulBee What version of Windows are you using? On vanilla Windows 10, IE11 has auto-hiding scrollbars, so this isn't really an issue there.

**Comment by patrickhlauke** [comment] 2015-12-16 09:36
Unless I'm mistaken, I suspect @usefulBee is actually referring to the fact that the scrollbar in IE is semi-transparent (and not anything to do with scrollbars appearing unnecessarily).

The current behavior is intentional, but can be suppressed/changed by adding

```
-ms-overflow-style: scrollbar;
```

to `body`, for instance.

see http://stackoverflow.com/questions/17045132/scrollbar-overlay-in-ie10-how-do-you-stop-that

**Comment by patrickhlauke** [comment] 2015-12-16 09:49
![ie11-transparent](https://cloud.githubusercontent.com/assets/895831/11837661/40872f62-a3da-11e5-81a7-cab5b00f99ae.png)

**Comment by cvrebert** [comment] 2015-12-16 10:03
My understanding of their complaint is that the scrollbars, when visible, overlap the content (as opposed to the alternative browser behavior of making the viewport's right boundary be the left edge of the scrollbar; i.e. making the viewport narrower).

In my testing, Win10 IE11 behaved similar to OS X's default scrollbars, which is to say that they overlap the content while they're visible, but once you stop scrolling, after a small delay, they hide themselves, thus no longer obscuring the content they overlapped with.

My take is: Why care about scrollbars overlapping content when the scrollbars are transient anyway? Nobody is perpetually scrolling; the user will be able to access the obscured content shortly after they finish scrolling.

**Comment by patrickhlauke** [comment] 2015-12-16 10:10
Sure, I don't have a particular problem with the current behavior in IE11, and am happy to keep it as is. Just clarifying the slightly vague (to me) problem description.

**Comment by usefulBee** [comment] 2015-12-16 17:03
System:  IE11 on Windows 8.1 Pro and Windows7, using a desktop and a laptop.
As mentioned in the first post, width:auto!important; solves the issue, but a complete instant visibility of the last element/column is not really the only issue, another example of a problem is that if the last column header contains a filter icon. Even if you manage to click the icon, the filter popup window in this case will be partially hidden....what is worse is that IE ScrollBar won't disappear.

**Comment by cvrebert** [comment] 2015-12-16 20:25
> another example of a problem is that if the last column header contains a filter icon. Even if you managed to click the icon, the filter popup window in this case will be partially hidden....what is worse is that IE ScrollBar won't disappear.

Could you post a demonstration?

**Comment by patrickhlauke** [comment] 2015-12-16 21:02
I can confirm that if there is something clickable right up against the edge of the browser, it's not possible to click it (easily) as at the slightest movement the scrollbar will reappear and swallow the click.

I would, however, be wary of simply replacing `width: device-width;` with `width:auto!important;` - the former is there for a specific reason. Perhaps adding `-ms-overflow-style: scrollbar;` is still the best option (as then the scrollbar will also behave the same way as in other browsers - including MS Edge - on Windows)

**Comment by cvrebert** [comment] 2015-12-16 21:36
> Perhaps adding `-ms-overflow-style: scrollbar;` is still the best option

Yeah, looks that way.
The fact that setting the viewport also affects the scrollbar style in a desktop browser seems like an arguable bug to me.

**Comment by cvrebert** [comment] 2015-12-16 21:45
Pinged some Edge folks in case they have anything to add: https://twitter.com/cvrebert/status/677242861679693824

**Comment by patrickhlauke** [comment] 2015-12-16 22:26
Edge seems to have the same behavior, but its auto-hiding/showing seems less trigger-happy, allowing for some mouse movement into the edge area before showing it again.

**Comment by gregwhitworth** [comment] 2015-12-16 22:49
Just so you don't think we're not looking into this, I sent an email to the person that knows the most about `-ms-viewport` but it will be a bit due to the holidays. I suggest using the `-ms-overflow-style` suggestion as that's its intention, but we'll respond back here once we know why the styles are changing due to the width setting within the `@viewport`

**Comment by usefulBee** [comment] 2015-12-17 18:09
Just stopping quickly to confirm that body { -ms-overflow-style: scrollbar; }  does solve the problem.
I wonder if there is any possibility that this line would be somehow injected with a future Bootstrap. And hey, before I forget, I really appreciate your commitment everyone and proud of your professionalism!

**Comment by cvrebert** [comment] 2016-01-09 09:44
Fixed by #18775.

**Closed by cvrebert** 2016-01-09 09:44 UTC
Labels: confirmed, css, v4

**Comment by cvrebert** [comment] 2016-01-18 11:37
@gregwhitworth Filed a Connect Feedback bug to track this: https://connect.microsoft.com/IE/feedback/details/2256049/edge-ie11-viewport-rule-has-side-effect-of-making-scrollbars-auto-hide

**Comment by gregwhitworth** [comment] 2016-01-20 01:04
@cvrebert Thanks, I spoke with the Comp team since this is something they own, they have a bug on it already so don't be surprised if yours gets closed for the older one. They aren't as inclined to fix it yet since most browsers don't support the `@viewport` yet. I've added the comments regarding this discussion though for the team to take into consideration when triaging. Thanks again for reaching out regarding it.
