### ISSUE TITLE
Navbar right justified inline forms extend too far right in IE 10

### ISSUE THREAD

**Issue by fathert** [twbs/bootstrap#22109] opened 2017-03-03 16:20 UTC
In Bootstrap 4-alpha 6 inline forms on the right hand side of the navbar extend too far right and outside the confines of the navbar itself when viewed with Internet Explorer 10. This can be seen in the example here http://v4-alpha.getbootstrap.com/components/navbar/

![image](https://cloud.githubusercontent.com/assets/8808151/23558904/9f1c8898-0035-11e7-883e-35d608fa949f.png)

**Comment by mdo** [comment] 2017-03-24 05:15
Dupe of #21745.

**Closed by mdo** 2017-03-24 05:15 UTC
Labels: css, v4
