### ISSUE TITLE
Jumbotron : Padding fail

### ISSUE THREAD

**Issue by NEQII** [twbs/bootstrap#16972] opened 2015-08-12 08:29 UTC
A'm I the only one, who got trouble with the class (jumbotron). It has no padding when i resize the screen to "XS (Extra Small)".

They wrote the padding into the class: .jumbotron
But they have to do it directly into the .jumbotron like this: 

.container .jumbotron, .container-fluid .jumbotron
{
       padding: 20px;
};

**Comment by kkirsche** [comment] 2015-08-12 10:43
Duplicate of #16779

**Closed** 2015-08-12 11:38 UTC
