### ISSUE TITLE
add tags input field

### ISSUE THREAD

**Issue by withrvr** [twbs/bootstrap#34193] opened 2021-06-06 19:01 UTC
something like that
https://stackoverflow.com/questions/10839570/how-does-stackoverflow-make-its-tag-input-field

so that we don't have to use external plugins and
 the style also doesn't change

and easy for programmers

**Comment by mdo** [comment] 2021-06-07 19:49
Duplicate of #31033.

**Closed by mdo** 2021-06-07 19:49 UTC
Labels: feature
