### ISSUE TITLE
(v4 beta) some changes are missing in the npm package

### ISSUE THREAD

**Issue by changLiuUNSW** [twbs/bootstrap#23740] opened 2017-08-30 05:27 UTC
I use ```npm install bootstrap@4.0.0-beta``` to download Bootstrap into my local repo.
I found some changes are missing for some components eg: 
```_porgress.scss``` via ```npm install```:
```
@keyframes progress-bar-stripes {
  from { background-position: $progress-height 0; }
  to { background-position: 0 0; }
}

.progress {
  display: flex;
  height: $progress-height;
  overflow: hidden; // force rounded corners by cropping it
  font-size: $progress-font-size;
  background-color: $progress-bg;
  @include border-radius($progress-border-radius);
}

.progress-bar {
  display: flex;
  align-items: center;
  justify-content: center;
  color: $progress-bar-color;
  background-color: $progress-bar-bg;
}

.progress-bar-striped {
  @include gradient-striped();
  background-size: $progress-height $progress-height;
}

.progress-bar-animated {
  animation: progress-bar-stripes $progress-bar-animation-timing;
}

```
```_porgress.scss``` in the Bootstrap Repo ```v4.0.0-beta```:
https://github.com/twbs/bootstrap/blob/v4.0.0-beta/scss/_progress.scss
```
@keyframes progress-bar-stripes {
  from { background-position: $progress-height 0; }
  to { background-position: 0 0; }
}

.progress {
  display: flex;
  overflow: hidden; // force rounded corners by cropping it
  font-size: $progress-font-size;
  line-height: $progress-height;
  text-align: center;
  background-color: $progress-bg;
  @include border-radius($progress-border-radius);
  @include box-shadow($progress-box-shadow);
}

.progress-bar {
  height: $progress-height;
  line-height: $progress-height;
  color: $progress-bar-color;
  background-color: $progress-bar-bg;
  @include transition($progress-bar-transition);
}

.progress-bar-striped {
  @include gradient-striped();
  background-size: $progress-height $progress-height;
}

.progress-bar-animated {
  animation: progress-bar-stripes $progress-bar-animation-timing;
}
```

You can find some styling and variables eg: ```line-height``` and  ```@include transition($progress-bar-transition)``` are missing in the npm package.

Does anyone have the same issue with me?

**Comment by danimalweb** [comment] 2017-08-30 22:20
Yep, I have the same issue.

**Comment by changLiuUNSW** [comment] 2017-09-03 01:25
Any updates on this?

**Comment by sebhiticas** [comment] 2017-09-06 14:01
I have a similar issue with the `_input-group.scss` file.

In the Github repo:
https://github.com/twbs/bootstrap/blob/v4.0.0-beta/scss/_input-group.scss
```
.input-group-btn {
  position: relative;
  // Jankily prevent input button groups from wrapping with `white-space` and
  // `font-size` in combination with `inline-block` on buttons.
  font-size: 0;
  white-space: nowrap;

  // Negative margin for spacing, position for bringing hovered/focused/actived
  // element above the siblings.
  > .btn {
    position: relative;
    
    + .btn {
      margin-left: (-$input-btn-border-width);
    }

    // Bring the "active" button to the front
    @include hover-focus-active {
      z-index: 3;
    }
  }

  // Negative margin to only have a single, shared border between the two
  &:not(:last-child) {
    > .btn,
    > .btn-group {
      margin-right: (-$input-btn-border-width);
    }
  }
  &:not(:first-child) {
    > .btn,
    > .btn-group {
      z-index: 2;
      margin-left: (-$input-btn-border-width);
      // Because specificity
      @include hover-focus-active {
        z-index: 3;
      }
    }
  }
}
```

In the npm repo
```
.input-group-btn {
  position: relative;
  // Jankily prevent input button groups from wrapping with `white-space` and
  // `font-size` in combination with `inline-block` on buttons.
  font-size: 0;
  white-space: nowrap;

  // Negative margin for spacing, position for bringing hovered/focused/actived
  // element above the siblings.
  > .btn {
    position: relative;
    /*****************************************************************
    SHOULD NOT BE THERE
    ******************************************************************
    background-clip: padding-box;
    border: $input-btn-border-width solid $input-group-btn-border-color;
    *****************************************************************
    ******************************************************************/
    + .btn {
      margin-left: (-$input-btn-border-width);
    }

    // Bring the "active" button to the front
    @include hover-focus-active {
      z-index: 3;
    }
  }

  // Negative margin to only have a single, shared border between the two
  &:not(:last-child) {
    > .btn,
    > .btn-group {
      margin-right: (-$input-btn-border-width);
    }
  }
  &:not(:first-child) {
    > .btn,
    > .btn-group {
      z-index: 2;
      margin-left: (-$input-btn-border-width);
      // Because specificity
      @include hover-focus-active {
        z-index: 3;
      }
    }
  }
}
```

**Comment by diego-rlima** [comment] 2017-09-09 07:12
In the NPM repository, this commit does not yet exist:
https://github.com/twbs/bootstrap/commit/70ca04bbdca2c61679c8ce28a61021754bacffb9

**Comment by hmhrex** [comment] 2017-09-18 13:58
I was wondering my colored input-group buttons had weird borders.
![button](https://user-images.githubusercontent.com/6685680/30545504-cfb9171e-9c57-11e7-9d73-9e739ed62408.PNG)
Would love an update as to when this will be fixed. Have a site launching soon that we want to use Beta on, but we're thinking about reverting back to Alpha 6.

**Comment by patrickheck** [comment] 2017-09-20 07:33
Actually there is a lot differing. Here is the full list of scss files:

I generated it this way:
```
npm install bootstrap@4.0.0-beta
git clone https://github.com/twbs/bootstrap.git
cd bootstrap
git checkout v4.0.0-beta
diff -qr scss ../node_modules/bootstrap/scss
```

**Output**
```
Files node_modules/bootstrap/scss/_breadcrumb.scss and bootstrap/scss/_breadcrumb.scss differ
Files node_modules/bootstrap/scss/_custom-forms.scss and bootstrap/scss/_custom-forms.scss differ
Files node_modules/bootstrap/scss/_forms.scss and bootstrap/scss/_forms.scss differ
Files node_modules/bootstrap/scss/_input-group.scss and bootstrap/scss/_input-group.scss differ
Files node_modules/bootstrap/scss/_modal.scss and bootstrap/scss/_modal.scss differ
Files node_modules/bootstrap/scss/_progress.scss and bootstrap/scss/_progress.scss differ
Files node_modules/bootstrap/scss/_reboot.scss and bootstrap/scss/_reboot.scss differ
Files node_modules/bootstrap/scss/_variables.scss and bootstrap/scss/_variables.scss differ
Files node_modules/bootstrap/scss/utilities/_borders.scss and bootstrap/scss/utilities/_borders.scss differ
Files node_modules/bootstrap/scss/utilities/_position.scss and bootstrap/scss/utilities/_position.scss differ
Files node_modules/bootstrap/scss/utilities/_spacing.scss and bootstrap/scss/utilities/_spacing.scss differ
Files node_modules/bootstrap/scss/utilities/_text.scss and bootstrap/scss/utilities/_text.scss differ
```

It would be really great if this is fixed soon. Especially the fact that the docs are not matching the deployed artifacts is quite unfortunate.

**Comment by bardiharborow** [comment] 2017-09-20 07:51
Confirmed that the version of _breadcrumb.scss [on NPM](https://unpkg.com/bootstrap@4.0.0-beta/scss/_breadcrumb.scss) and [on Git](https://raw.githubusercontent.com/twbs/bootstrap/v4.0.0-beta/scss/_breadcrumb.scss) differ. Something's gone wrong here. /cc @mdo

**Comment by patrickheck** [comment] 2017-09-20 08:00
After browsing the commit history I found out that the NPM version seems to be from this commit:
https://github.com/twbs/bootstrap/commit/a0521efbb59aefeb447a0ef6927aadf1999fee07

**Comment by mdo** [comment] 2017-10-02 04:55
Weird. We're closing in on a Beta 2, so probably not worth addressing?

**Comment by hmhrex** [comment] 2017-10-02 18:35
@mdo What's the timeline on Beta 2? Also, could this be a bug that happens again with Beta 2?

**Comment by mdo** [comment] 2017-10-03 04:55
I imagine I just had the wrong git history locally. Beta 2 hopefully this week.

**Comment by hmhrex** [comment] 2017-10-03 12:00
@mdo Awesome! Looking forward to Beta 2! Thanks for all your hard work!

**Comment by mdo** [comment] 2017-10-20 05:16
Closing because Beta 2.

**Closed by mdo** 2017-10-20 05:16 UTC
Labels: confirmed, meta, v4
