### ISSUE TITLE
Investigate & probably file Firefox bug regarding Customizer file saving problem

### ISSUE THREAD

**Issue by cvrebert** [twbs/bootstrap#15016] opened 2014-11-04 18:53 UTC
Successor of #14750, since the setTimeout still hasn't fully fixed the problem.

**Comment by rajlaksh** [comment] 2015-02-01 07:35
I got a trick. Just Press ALT to download file and works. Without it it fails to download archive.

**Comment by XhmikosR** [comment] 2015-02-03 06:57
Interestingly, <kbd>Alt</kbd> + left click seems to indeed fix the issue.

**Comment by miketaylr** [comment] 2015-05-21 04:05
Hi there, I work on compat stuff in Firefox and noticed the big banner tonight. I'm trying to find some STR, and just to confirm, this only happens on Windows? I'd like to get to the bottom of the bug and get it fixed in Gecko/Firefox, if possible.

**Comment by XhmikosR** [comment] 2015-05-21 04:09
Personally, I can't really reproduce this anymore.

**Comment by jdavies322** [comment] 2015-05-21 14:05
It's no longer an issue for me, but FYI it was Mac OS Firefox

**Comment by XhmikosR** [comment] 2015-05-21 14:13
It happened on Windows too.

**Comment by Mithgol** [comment] 2015-05-21 14:19
It happens to me if FlashGot is intalled. Alt+Shift+click helps the download to bypass FlashGot and thus to bypass this issue.

**Comment by miketaylr** [comment] 2015-05-21 14:47
@Mithgol which platform and version?

**Comment by miketaylr** [comment] 2015-05-21 16:53
I can't reproduce with FlashGot on OSX. If it only happens with this add-on, it's probably an AddOn bug and should be reported here: https://forums.informaction.com/viewforum.php?f=2.

@mlissner, @sistanoman, @jdavies322 can you all test again? Do you happen to have FlashGot installed as well?

**Comment by Mithgol** [comment] 2015-05-22 11:12
@miketaylr I am sure it happened on Windows XP. (I also have a vague memory of the same issue on Windows 7 64-bit, but that may be a false memory.)

However, I've just tried to reproduce this issue and could not experience this problem in Firefox 38.0.1 on Windows XP Professional SP3, though FlashGot 1.5.6.12 is installed.

Something is fixed.

**Comment by miketaylr** [comment] 2015-05-22 14:21
Thanks for checking @Mithgol. Let's wait to hear from others to confirm, but it sounds like this bug disappeared.

**Comment by patrickhlauke** [comment] 2015-05-22 14:25
@miketaylr the best kind of bug, eh?

**Comment by mlissner** [comment] 2015-05-22 17:07
Yeah, I can't reproduce this anymore on Ubuntu, whereas I could consistently before. Perhaps it's time to remove the warning banner.

I'm on FF 38.0.

**Comment by miketaylr** [comment] 2015-05-22 17:11
@pamelafox :)

Thanks @mlissner. I'll go ahead and open a PR to remove the warning.

**Closed** 2015-05-22 17:39 UTC
Labels: browser bug, customizer
