### ISSUE TITLE
Incomplete page on the new documentation

### ISSUE THREAD

**Issue by Biuni** [twbs/bootstrap#23636] opened 2017-08-23 12:47 UTC
I have found this incomplete page http://getbootstrap.com/docs/4.0/extend/ linked by the fourth element on this list https://getbootstrap.com/docs/4.0/migration/#components .

PS: Another problem is the link "card" in the first paragraph. The page returned is 404 because the true link is https://getbootstrap.com/docs/4.0/components/card/ and not https://getbootstrap.com/docs/4.0/components/cards/

**Comment by mdo** [comment] 2017-08-23 16:25
Duplicate of #23369.

**Closed by mdo** 2017-08-23 16:25 UTC
Labels: docs, v4
