### ISSUE TITLE
input-group-addon broken for input type date

### ISSUE THREAD

**Issue by Enalmada** [twbs/bootstrap#21767] opened 2017-01-18 09:04 UTC
The height is huge and it looks funny.

Tested on Chrome Windows on b4a6.  Worked fine on b4a5.

```
  <div class="input-group">
    <div class="input-group-addon">@</div>
    <input type="date" class="form-control">
  </div>
```

**Comment by bardiharborow** [comment] 2017-01-19 12:54
Duplicate of #21651.

**Closed by bardiharborow** 2017-01-19 12:54 UTC
Labels: css, v4
