### ISSUE TITLE
single button dropdown's border-radius changes on toggle on Win10 Chrome

### ISSUE THREAD

**Issue by murraybiscuit** [twbs/bootstrap#20098] opened 2016-06-08 17:48 UTC
**Steps to reproduce:**
1. Go to BS4 [button dropdown demo page](http://v4-alpha.getbootstrap.com/components/button-dropdown/)
2. Click single button dropdown
3. Top left and bottom left radius is removed on toggle.

**Expected behaviour:** 

Border radius should not change

**Cause:**

CSS selector

```
.btn-group>.btn:last-child:not(:first-child), **.btn-group>.dropdown-toggle:not(:first-child)** {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
}
```

The not(:first-child) selector gets applied because dropdown.js inserts a .dropdown-backdrop div in the dom before.

bootstrap/js/src/dropdown.js - line 103

`$(dropdown).insertBefore(this)`

**Suggested fix (untested):**

Change the above line in dropdown.js to insert after:

$(dropdown).insertAfter(this)

**Comment by cvrebert** [comment] 2016-06-08 20:03
* What browser and OS are you using?
* What version of Bootstrap are you using?
* Are you referring to http://v4-alpha.getbootstrap.com/components/button-dropdown/#single-button-dropdowns ? I can't seem to reproduce. Are you running the docs locally?

**Comment by murraybiscuit** [comment] 2016-06-09 06:39
Sorry Chris

Browser: Windows 10, Chrome (this doesn't seem to affect latest versions of
Edge, IE or FF)
BS version: the v4 alpha docs online.
That dropdown-backdrop seems to only get injected into the DOM for mobile
devices IIRC...
So perhaps there's a mobile detect that's going wonky.

I'll to a bit more digging in the JS.

**Comment by murraybiscuit** [comment] 2016-06-09 06:44
Ok, so I looked at the js that triggers this - on line 97 here:
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/dropdown.js

```
if ('ontouchstart' in document.documentElement &&
         (!$(parent).closest(Selector.NAVBAR_NAV).length)) {
```
Chrome on Win10 has the ontouchstart event on the document element. The other browsers don't. Perhaps 'ontouchstart' isn't the best event for detection?

**Comment by cvrebert** [comment] 2016-06-09 06:54
@patrickhlauke I believe you have access to a Win10 laplet suitable for testing this?

**Comment by patrickhlauke** [comment] 2016-06-09 06:59
confirming the issue. FWIW you can force Chrome to expose touch events API even when there's no physical touchscreen by going to chrome://flags/#touch-events
![capturewin10chrometouch](https://cloud.githubusercontent.com/assets/895831/15921245/09ee2fa0-2e18-11e6-803e-625bc6abcfb3.PNG)

and yes, using `ontouchstart` as an indirect indicator that we're on mobile/click won't delegate is going to get us into problems on multi-input devices that happen to have touch AND delegation

**Comment by mdo** [comment] 2017-04-08 19:39
Wondering if it's possible to move the `.dropdown-backdrop` to come after the menu?

**Comment by gijsbotje** [comment] 2017-07-06 20:20
looks like it has been fixed in the cuurent v4-dev branch
https://twbs.github.io/staging/docs/4.0/components/dropdowns/

**Comment by patrickhlauke** [comment] 2017-07-12 23:30
@gijsbotje yup, seems a side effect from my work on dropdowns. closing.

**Closed by patrickhlauke** 2017-07-12 23:30 UTC
Labels: js, v4
