### ISSUE TITLE
V5 Components : Add Skeleton Component

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#33410] opened 2021-03-19 18:44 UTC
**What is Skeleton Component?**

it's a component to Display a placeholder preview of your content before the data gets loaded to reduce load-time frustration.

**Example :**

https://codesandbox.io/s/r6ddt

**Comment by mdo** [comment] 2021-03-19 19:19
Duplicate of #31665, and being worked on in #31859.

**Closed by mdo** 2021-03-19 19:19 UTC
Labels: feature
