### ISSUE TITLE
Bootstrap 3 jspm jquery dependency issue

### ISSUE THREAD

**Issue by chinookproject** [twbs/bootstrap#20159] opened 2016-06-22 20:06 UTC
When I install Bootstrap with `jspm` it also downloads `jquery` for me because that dependency is listed in the `package.json` of Bootstrap. But there is no version specified in the `package.json` for jquery, so it's downloading the latest jQuery 3.0.0. But that version isn't compatible with Bootstrap 3.3.6 which leads to problems.

Can the `package.json` be updated so that is specifically targets the latest jquery 2.x.x version?

**Comment by cvrebert** [comment] 2016-06-22 20:45
Going to call this a duplicate of 16834. Accounting for the overhead of shipping a release, it'll be faster to just properly fix the incompatibility. I'll try to get it done this week.

**Closed by cvrebert** 2016-06-22 20:45 UTC
Labels: js, meta, v3
