### ISSUE TITLE
Make documentation navbar fixed to top of viewport

### ISSUE THREAD

**Issue by B1aZer** [twbs/bootstrap#15804] opened 2015-02-13 10:08 UTC
Please make header on the main page http://getbootstrap.com/ affix or fixed as it was on v.2.

I often need to go to next page and I have to scroll all the way up to do this. This is very annoying, especially when I'm doing this several times a day. Maybe I'm missing something ?

**Comment by kkirsche** [comment] 2015-02-13 13:46
I can understand making the navbar potentially fixed, the header though implies the entire top section.

A great tool for reading documentation that I use is [Dash for Mac](http://kapeli.com/dash) not sure what system you are on but there may be similar software :+1: Good luck!

**Comment by B1aZer** [comment] 2015-02-13 14:02
Yes, of course I mean navbar.

Thanks for a tip. I will try out zeal.

**Comment by cvrebert** [comment] 2015-02-13 15:45
Duplicate of #12626.

**Comment by mdo** [comment] 2015-02-25 00:31
Closing per this being a dupe.

**Comment by licatajustin** [comment] 2015-02-25 00:48
@B1aZer, if you want it fixed, you could always just use something like [Stylish](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) for Chrome and write your own CSS...

    body {
      padding-top: 50px;
    }

    .bs-docs-nav {
      position: fixed;
      right: 0;
      left: 0;
      top: 0;
      border-bottom: 0;
      box-shadow: 0 1px 2px rgba(0, 0, 0, 0.25);
      z-index: 1030;
    }

    .bs-docs-sidebar.affix {
      top: 60px;
    }

**Closed** 2015-02-25 00:51 UTC
Labels: docs
