### ISSUE TITLE
Better handling of remote Modal content with transitions

### ISSUE THREAD

**Issue by joshreed** [twbs/bootstrap#18275] opened 2015-11-16 22:35 UTC
Currently, remote content, unless loaded really quickly, or already cached in-browser, will not always show the (CSS) transitions, which is a nuisance. This is because the transition "starts" using an empty DIV, and often the content hasn't arrived until after the div has already been "transitioned" in.

I have a Pull Request with a fix, however it currently is failing on the @twbs-savage test, it errors with a 10 minute timeout in trying to connect. Is this an issue with the continuous-integration process, or the code itself?

https://github.com/twbs/bootstrap/pull/18274

In any case, I'm not tied to this particular solution presented in the Pull Request, but I figured it'd be valuable to not only supply a "complaint" but also a way to fix it! If there's a different preferred implementation that fixes the root issue, I'm certainly open to it.

**Comment by cvrebert** [comment] 2015-11-17 01:13
The `remote` option is deprecated (see http://getbootstrap.com/javascript/#modals-options & #14034) and Bootstrap v3 is in maintenance mode at this point so we can focus on v4.
Since the issue isn't a showstopper and concerns a deprecated feature, I'm calling this WontFix. Sorry!

**Closed by cvrebert** 2015-11-17 01:13 UTC
Labels: js, v3
