### ISSUE TITLE
Dropdown as "block level button" will not open menu

### ISSUE THREAD

**Issue by john-999** [twbs/bootstrap#36426] opened 2022-05-23 15:02 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

1. Decide you want to have a "block level button" as the trigger element for the dropdown menu
2. Wrap a `<div class="d-grid">` around the trigger element
3. Click the trigger element: The dropdown menu will not open (a JS error is thrown).

### Reduced test cases

```
<div class="dropdown">
  <div class="d-grid">   <!--  <<<<------ THIS will prevent the menu from opening (JS error) -->
     <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown">
       Dropdown link
     </a>
  </div>

  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="#">Action</a></li>
    <li><a class="dropdown-item" href="#">Another action</a></li>
    <li><a class="dropdown-item" href="#">Something else here</a></li>
  </ul>
</div>
```

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v.5.1.3

**Comment by julien-deramond** [comment] 2022-05-23 15:45
The encountered issue comes probably from https://github.com/twbs/bootstrap/blob/427c089961c8773386de0503a1da8b586587df38/js/src/dropdown.js#L98
which expects that the direct parent contains any `.dropdown-menu`. It confirms technically that adding an extra `<div>` in the middle causes unexpected results.

Maybe it is a bit difficult to silent this JS error @GeoSot isn't it?

In the [Dropdowns - Examples documentation](https://twbs-bootstrap.netlify.app/docs/5.2/components/dropdowns/#examples):
> Wrap the dropdown’s toggle (your button or link) and the dropdown menu within .dropdown

Maybe it worth adding more details about the HTML structure to respect or adding another example with `<div class="dropdown d-grid">`  if it represents a common use case for Bootstrap users.

---

_Even if the issue is fixed I let it open for the moment to see if some improvements can be made and to have other opinions_

**Comment by mdo** [comment] 2022-12-29 07:28
I think our docs are clear on the required markup for components like this. Closing as a won’t fix.

**Closed by mdo** 2022-12-29 07:28 UTC
Labels: docs, js, v5
