### ISSUE TITLE
Javascript Error in dropdown-menu

### ISSUE THREAD

**Issue by Knud13** [twbs/bootstrap#40660] opened 2024-07-24 03:42 UTC
### Discussed in https://github.com/orgs/twbs/discussions/40658

<div type='discussions-op-text'>

<sup>Originally posted by **Knud13** July 24, 2024</sup>
I've found a small javascript error in the dropdown-menu e.g.
```html
<div class="dropdown-menu">
  <a class="dropdown-item" href="#">New around here? Sign up</a>
  <a class="dropdown-item" href="#">Forgot password?</a>
</div>
```
Keyboard Tab into the dropdown menu works but if you then use the arrow keys it will generate an error

```
>  Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode') dropdown.js:98
    at new qi (dropdown.js:98:34)
    at qi.getOrCreateInstance (base-component.js:65:41)
    at HTMLDivElement.dataApiKeydownHandler (dropdown.js:419:31)
    at HTMLDocument.n (event-handler.js:118:19)
```
you can reproduce the error on the bootstrap docs page 
[https://getbootstrap.com/docs/5.3/components/dropdowns/#forms](https://getbootstrap.com/docs/5.3/components/dropdowns/#forms)
just navigate to the "New around here? Sign up" dropdown-item via keyboard so it has focus and use the arrow keys.

I assume the dropdown-item is looking for a parent <li> since most dropdown-item are in the format
```html
<ul class="dropdown-menu">
  <li><a class="dropdown-item" href="#">New around here? Sign up</a></li>
  <li><a class="dropdown-item" href="#">Forgot password?</a></li>
</ul>
```

**Comment by julien-deramond** [comment] 2024-07-24 05:48
Thanks for reporting this issue @Knud13 
It's not easy to find, but this is actually a duplicate of https://github.com/twbs/bootstrap/issues/37428 (mentioned in https://github.com/twbs/bootstrap/issues/37428#issuecomment-2025934169 for instance). The error only happens in the documentation that shows the dropdown menus with their dropdown button, just to see easily the rendering; it won't happen in the real life.
https://github.com/twbs/bootstrap/pull/37755 might fix this issue.

**Closed by julien-deramond** 2024-07-24 05:48 UTC
Labels: docs, js

**Comment by Knud13** [comment] 2024-07-24 23:14
Thanks Julien, seems you are correct. In my situation we were using the dropdown-menu as a menu on the page without a toggle button. It appears you need to use a dropdown-menu in a dropdown. I could reproduce the error on the demo page obviously as it's just showing the layout as an example.
