### ISSUE TITLE
Popover's container option no longer works

### ISSUE THREAD

**Issue by cheneveld** [twbs/bootstrap#19922] opened 2016-05-16 22:40 UTC
popover container attribute no longer works.  

Looks like the body selector is hardcoded here -> https://github.com/twbs/bootstrap-rubygem/blob/master/assets/javascripts/bootstrap/tooltip.js#L250.

**Comment by cvrebert** [comment] 2016-05-17 16:23
Duplicate of #17755. Please search more in the future.

**Closed by cvrebert** 2016-05-17 16:23 UTC
Labels: js, v4
