### ISSUE TITLE
Is there more RTL support in Bootstrap 4 or at least planned to be?

### ISSUE THREAD

**Issue by Benosika** [twbs/bootstrap#19748] opened 2016-04-16 18:38 UTC
Hi, I use Bootstrap 3 in many occasions. I'm not sure if the RTL problems I fix are caused due to the Drupal Bootstrap themes that are built in a total LTR paradigm, or it is the Bootstrap 3 release that itself doesn't fully support RTL...

Is Bootstrap 4 going to be different in that manner? Maybe I could report and contribute fixes that deals with RTL if not...

**Comment by RyanZim** [comment] 2016-04-16 19:05
@Benosika Duplicate of #19703. Please close this.

**Comment by hebbet** [comment] 2016-04-16 19:05
i quote @cvrebert:
"RTL support is currently slated for a future minor release after v4.0.0 has a stable release."

[19545#comment](https://github.com/twbs/bootstrap/issues/19545#issuecomment-196990781)

**Comment by cvrebert** [comment] 2016-04-16 19:11
> or it is the Bootstrap 3 release that itself doesn't fully support RTL...

Just for the record, Bootstrap 3 has no built-in RTL support.

Closing this per the previous comments.

**Closed by cvrebert** 2016-04-16 19:11 UTC
Labels: css, feature, v4

**Comment by parsmizban** [comment] 2017-03-18 15:01
Hi,
You can use this patch for full RTL compatibility for both Bootstrap 3.3.7 and 4.0.0-alpha.6
https://github.com/parsmizban/RTL-Bootstrap
If you have any pre designed theme, You can use this path to make your template RTL very easy
Good luck
