### ISSUE TITLE
Validation icons problem

### ISSUE THREAD

**Issue by LaySoft** [twbs/bootstrap#21410] opened 2016-12-23 08:58 UTC
Validation icons don't see in alpha5 under Firefox. Other browsers, or Firefox with alpha4 is good.

http://v4-alpha.getbootstrap.com/components/forms/#validation

**Comment by Starsam80** [comment] 2016-12-23 09:06
Assuming this is a duplicate of #20956, which is fixed by #20962

**Closed** 2016-12-23 10:57 UTC
