### ISSUE TITLE
Buttons in input group have incorrect padding

### ISSUE THREAD

**Issue by Kopyov** [twbs/bootstrap#26334] opened 2018-04-18 07:37 UTC
Large and small buttons in input group extend form controls, not buttons. So if i want to change horizontal padding for input fields, buttons in 2 sizes adjust paddings accordingly. Is this an expected behaviour or a bug?

**Comment by andresgalante** [comment] 2018-04-18 12:40
Hi @Kopyov,

I'd say that the padding-y is by design, you'd always want the btn to be the same height as the field.

Now, I see how an author would want to change padding-x of the input without affecting the btn. 

Nice catch!

**Comment by mdo** [comment] 2018-12-17 02:31
Closing per https://github.com/twbs/bootstrap/pull/26338#issuecomment-439974199.

**Closed by mdo** 2018-12-17 02:31 UTC
Labels: css, has-pr, v4
