### ISSUE TITLE
Navbar right padding broken when using navbar-text, navbar-right and navbar-fixed-top

### ISSUE THREAD

**Issue by eszstuff** [twbs/bootstrap#17598] opened 2015-09-14 14:39 UTC
Issue similiar to https://github.com/twbs/bootstrap/issues/11783 but occurs with classes "navbar-text navbar-right" and navbar-fixed-top. 

Example: http://jsbin.com/puhivomaca/edit?html,output

Tested with version 3.3.5.

**Comment by rifton007** [comment] 2015-11-26 08:42
For me too, it is not fixed.

**Comment by cvrebert** [comment] 2015-11-28 04:31
X-Ref: #18362

**Comment by cvrebert** [comment] 2015-11-28 04:43
Duplicate of #16694, which is WontFix. The v3 navbar is admittedly kinda sucky, too much so to be feasibly fixable while maintaining backward-compatibility; we're hoping to do better with Bootstrap v4's navbar.

**Closed by cvrebert** 2015-11-28 04:43 UTC
Labels: css, v3
