### ISSUE TITLE
No event.relatedTarget for Collapse

### ISSUE THREAD

**Issue by aguegu** [twbs/bootstrap#16724] opened 2015-06-29 08:08 UTC
I have a form in a moral to do the edit job. And then the form become too big that it does not fit in the modal. Then I realise that collapse could be a good alternative for the modal. 

And then I noticed that collapse event does not have the .relatedTarget property as modal events. I have to get some data from the relatedTarget to render the form.

**Comment by cvrebert** [comment] 2015-06-29 17:30
Approximate duplicate of #15393.

**Closed by cvrebert** 2015-06-29 17:30 UTC
Labels: feature, js
