### ISSUE TITLE
Autosize.js broken since 5.0.0 release (css issue)

### ISSUE THREAD

**Issue by dev1z** [twbs/bootstrap#33910] opened 2021-05-09 09:16 UTC
- Operating system and version (Windows, macOS, Android, iOS) : Windows / Android
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser) Latest Firefox, Chrome, Edge.
- When using https://www.jacklmoore.com/autosize/ and textarea is expanded by autosize() on typing, there is some scroll issue so you can't type characters. Page is misbehaving and going up/down per letter input. The problem is in CSS file.

Demo: https://jsbin.com/fuginitere/edit?html,js,output

**Comment by ffoodd** [comment] 2021-05-10 12:53
Yeah, but why :D? AFAIK the issue could be a browser bug, an autosize bug, etc. Need to dig this a bit more I guess, unless everyone agrees to simply drop `scroll-behavior`.

**Comment by alpadev** [comment] 2021-05-10 13:19
The other issue was with form validation IIRC.

And judging from the autosize source it resets the height and then scrolls to its last position (https://github.com/jackmoore/autosize/blob/master/src/autosize.js#L108-L120). Normally this would happen more or less instantly but because of that smooth scroll-behavior I guess it becomes noticable.

**Comment by jackmoore** [comment] 2021-05-10 16:53
@alpadev Hi, author of Autosize here. Your summary of the mechanics of this sounds accurate to me. Not a bug with bootstrap, it's just the approach that autosize uses isn't compatible with smooth scrolling (or CSS transitions on height).

**Comment by GeoSot** [comment] 2021-05-10 20:17
Closed as per above

**Closed by GeoSot** 2021-05-10 20:17 UTC
Labels: confirmed, css, v5
