### ISSUE TITLE
Including Apple Color Emoji in font stack prevents coloring unicode

### ISSUE THREAD

**Issue by paulschreiber** [twbs/bootstrap#31860] opened 2020-10-09 18:07 UTC
Before opening:
Including `Apple Color Emoji` in the font stack prevents coloring unicode, such as the ✖.

### Config
- Operating system and version: macOS 10.15.7
- Browser and version Chrome 85, Firefox 81

### Codepen
https://codepen.io/paulschreiber/pen/NWrPOjg

### Sample CSS
```css
.remove {
  color: yellow;
  background: black;
}
.fonts {
  font-family: sans-serif;
}
```

### Sample HTML
```html
<span class="remove">✖</span> 
<span class="remove fonts">✖</span>
```

### Actual
![image](https://user-images.githubusercontent.com/86784/95616929-9dfd4680-0a38-11eb-8962-8a2e015801eb.png)

### Expected
![image](https://user-images.githubusercontent.com/86784/95616959-ac4b6280-0a38-11eb-8e80-aa3454af1e9f.png)

**Comment by ffoodd** [comment] 2020-10-14 15:28
It's already in [our font-stack](https://github.com/twbs/bootstrap/blob/main/scss/_variables.scss#L395). Is there anything you'd want to change? Your issue is not very clear.

**Comment by patrickhlauke** [comment] 2020-10-14 15:36
i believe the issue is that because it *is* included, it overrides the regular unicode characters, and should be removed.

**Comment by ffoodd** [comment] 2020-10-14 16:34
Oh I see. I think it's the primary goal of using those emoji fonts though, so if we consider removing them it may lead to unexpected changes.

**Comment by patrickhlauke** [comment] 2020-10-14 16:54
i'd remove them, just leads to weirdness when somebody develops on non-macOS/iOS devices, then finds that on apple devices things look all weird and funky. as long as we can still make breaking changes, let's make them now and signpost it in the migration guide (i.e. if you still want them, add them yourself to your font stack)

**Comment by ffoodd** [comment] 2020-10-15 08:54
@patrickhlauke After reading ["When fonts fall" by Marcin Wichary](https://www.figma.com/blog/when-fonts-fall/), I'm not so sure about this.

The goal is to ensure the best possible support for unicode characters, and by removing our fallbacks it could lead to undefined characters in the wild.

What you're saying about switching system (temporarily) is true for our whole font-stack, since it's meant to display the main system UI font and won't look the same everywhere. I'll spare you the "not a bug, it's a feature" thing, but that's definetly intentionnal.

IMHO this should stay as-is, since it's pretty easily overriden through Sass in v4 and through both Sass and CSS custom properties in v5. But I'd like to hear other opinions on this, very interesting topic!

**Comment by mdo** [comment] 2020-10-22 18:59
> IMHO this should stay as-is, since it's pretty easily overriden through Sass in v4 and through both Sass and CSS custom properties in v5. But I'd like to hear other opinions on this, very interesting topic!

I'm in agreement overall.

**Comment by paulschreiber** [comment] 2020-10-22 19:05
This was difficult to debug and was definitely not expected behaviour. If you keep this, it would be good to call this out prominently in the documentation. It's very rare for people to include the emoji font in their font stacks.

**Comment by ffoodd** [comment] 2020-10-23 08:22
This is [mentionned and documented with a link to a Smashing Magazine post about system fonts](https://v5.getbootstrap.com/docs/5.0/content/reboot/#native-font-stack).

We might add a sentence about the emoji fonts, but that's explained and shown in the code block. Would you have any suggestion about making this more prominent? Maybe an example, or even a screnshot?

BTW, it's related to #31322 (that we may fix alongside improving our docs) and a duplicate of #27405 which got closed for the reason I gave—but improving our docs would help people struggling with this to understand faster what's unexpected.

**Comment by patrickhlauke** [comment] 2020-10-23 09:22
it's probably worth at least adding a bullet-point about the presence/use of emoji fonts (which generally replace unicode characters with coloured emoji/pictograms, and differ from platform to platform) at the start of https://v5.getbootstrap.com/docs/5.0/content/typography/ / https://getbootstrap.com/docs/4.5/content/typography/ at least. maybe even adding an extra little section that gives some representative examples

**Comment by mdo** [comment] 2020-10-23 22:16
Agreed on mentioning this in our docs. I'm thinking it'd be nice to include on the Reboot page, near the font stack section: https://twbs-bootstrap.netlify.app/docs/5.0/content/reboot/#native-font-stack. Maybe a subheading under there?

**Closed** 2020-10-25 19:21 UTC
Labels: css, docs, has-pr
