### ISSUE TITLE
Custom Validation Not Working with Input-Groups

### ISSUE THREAD

**Issue by jehugaleahsa** [twbs/bootstrap#24709] opened 2017-11-07 18:35 UTC
- Operating system and version: Windows 10
- Browser: Chrome, Firefox, etc.

I have to use the custom validation classes (http://getbootstrap.com/docs/4.0/components/forms/#server-side) since some of my validation isn't covered by the browser, via `is-valid`, `is-invalid` and `invalid-feedback`. I should point out this type of validation isn't strictly "server side", just manual.

My issue involves input-groups and the `invalid-feedback` CSS classes. Currently, the CSS to display `invalid-feedback` requires the the control to be `:invalid` inside of the `.was-validated` class or that it be right next to the `<input />`, via the `~` CSS selector and `.is-invalid`.

I can't use `.was-validated` since the validation is manual and the `:valid` pseudo class will be applied. And since I am using an `input-group`, the `<div class="invalid-feedback">` isn't directly next to the `<input />`. It would be nice if additional CSS rules could be added to handle adjacent `input-group`s.

As a workaround, I am just setting `display: block` whenever I set `is-invalid`.

**Comment by mdo** [comment] 2017-11-08 05:29
Duplicate of #23454.

**Closed by mdo** 2017-11-08 05:29 UTC
