### ISSUE TITLE
Bootstrap 4 DropDown scrolling issue in IE

### ISSUE THREAD

**Issue by PeteCozens** [twbs/bootstrap#28693] opened 2019-04-26 14:15 UTC
When the **_overflow-y:auto_** style is applied to a dropdown-menu it experiences issues when displayed in Internet Explorer (testing in v 11.2791.14393.0)

1) The scroll bar cannot be dragged up or down using the mouse, nor will it react to using the scroll buttons (asides from to close the dropdown)
2) When scrolling using the wheel there is an annoying flicker that displays content behind the drop-down and also displays menu items out of sequence

The issue is demonstrated in the following fiddle and also in the attached .html file

https://jsfiddle.net/8c6xwd41/

[ScrollingDropDown.txt](https://github.com/twbs/bootstrap/files/3121657/ScrollingDropDown.txt)

**Comment by ysds** [comment] 2019-05-07 02:05
Duplicate of #26936

Quick answer: add `data-display="static"` to the dropdown button

**Closed by ysds** 2019-05-07 02:05 UTC
Labels: v4
