### ISSUE TITLE
that._ignoreBackdropClick = true;  that is not defined

### ISSUE THREAD

**Issue by jsoncode** [twbs/bootstrap#19956] opened 2016-05-23 02:14 UTC
v4.0.0-alpha
```
$(this._dialog).on(Event.MOUSEDOWN_DISMISS, function () {
    $(_this7._element).one(Event.MOUSEUP_DISMISS, function (event) {
        if ($(event.target).is(_this7._element)) {
            that._ignoreBackdropClick = true;
        }
    });
});
```

 what is the mean of "that"?
//Uncaught ReferenceError: that is not defined

**Comment by cvrebert** [comment] 2016-05-23 20:21
v4.0.0-alpha.2 is the latest version. Please upgrade.
Duplicate of #18146.

**Closed by cvrebert** 2016-05-23 20:21 UTC
Labels: js, v4
