### ISSUE TITLE
Appending content to a modal that is already displayed does not update the backdrop height

### ISSUE THREAD

**Issue by moodysalem** [twbs/bootstrap#15418] opened 2014-12-20 16:58 UTC
Per the title, using jquery to append content to the modal content as of 3.3.0 causes the modal to become longer and can cause the page to need scrolling, but the backdrop does not cover the full length of the scrollable area

**Comment by yahyazini** [comment] 2015-01-04 05:11
One thing that might work is adding a max-height and an overflow-y auto. That way you can use specific dimensions that you can control using media queries instead of letting the content control the height!

**Comment by hnrch02** [comment] 2015-02-24 00:34
Closing as a duplicate of #15136. Potential fix at #15881.

**Closed by hnrch02** 2015-02-24 00:34 UTC
Labels: css, js
