### ISSUE TITLE
Popover stays 'live' when you close a modal containing it via clicking on the backdrop.

### ISSUE THREAD

**Issue by macbem** [twbs/bootstrap#20568] opened 2016-08-23 16:14 UTC
When you create a modal with a popover inside and you close the modal via clicking on the backdrop, the popover is still alive and has left: 0; and top: 0;.

I've tested this on OS X El Capitan in Chrome and on Ubuntu 14.04 in Chromium.

The issue can be reproduced in your example modal that's embedded into the documentation - http://v4-alpha.getbootstrap.com/components/modal/#live-demo

**Comment by bardiharborow** [comment] 2016-08-25 07:13
Confirmed on `Mac OS X 10.11.5 Chrome 53.0.2785.70`. I haven't gone through the popover code yet, but could we use some sort of DOM event to cascade down from the modal and then listen for that event on popovers?

**Comment by bardiharborow** [comment] 2016-08-28 06:44
Actually, this is a duplicate of #20093.

**Closed** 2016-11-29 17:44 UTC
Labels: js, v4
