### ISSUE TITLE
A class for fixed first column of table

### ISSUE THREAD

**Issue by mznet** [twbs/bootstrap#31423] opened 2020-08-04 09:19 UTC
With `table-responsive` class, scrolling right and left moves its contents horizontally. Its readability would be not good when entire contents are being moved horizontally. The readability get worse when its contents get wider.

To fix first column of table could solve its problem. Many sports websites already provide fixed first column style table to display much information on a table like below.

![Aug-04-2020 18-00-30](https://user-images.githubusercontent.com/9622730/89274870-7971a080-d67c-11ea-932c-2386aa2cdcf8.gif)

**Comment by mdo** [comment] 2020-08-17 23:42
Duplicate of #31458.

**Closed by mdo** 2020-08-17 23:42 UTC
Labels: feature
