### ISSUE TITLE
input-group validation, border issue

### ISSUE THREAD

**Issue by chr1stianC** [twbs/bootstrap#29775] opened 2019-11-29 21:50 UTC
The issue can be seen in the [v4.4 documentation](https://getbootstrap.com/docs/4.4/components/forms/#custom-styles), check the "username" input-group.
```
<label for="validationCustomUsername">Username</label>
<div class="input-group">
  <div class="input-group-prepend">
    <span class="input-group-text" id="inputGroupPrepend">@</span>
  </div>
  <input type="text" class="form-control" id="validationCustomUsername" aria-describedby="inputGroupPrepend" required>
  <div class="invalid-feedback">
    Please choose a username.
  </div>
</div>
```
`border-[top|bottom]-right` are not displayed.

**Comment by ysds** [comment] 2019-11-30 01:29
Duplicate of #25110

**Closed by ysds** 2019-11-30 01:29 UTC
