### ISSUE TITLE
Any website we implement bootstrap all font show bold

### ISSUE THREAD

**Issue by KrissyKoo** [twbs/bootstrap#17351] opened 2015-08-26 20:04 UTC
We love bootstrap, so we're implementing it on our websites. However, I've realized that every website I go to that has bootstrap (including getbootstrap) all of the font across the pages show bold for me in all browsers.  

Windows 8.1, 64-bit
in IE 11, Chrome Version 44.0.2403.157  or FireFox 40.0.2
Same behavior, everything bolded

No other website is bolded, just the ones with bootstrap. 

Any thoughts?

![get bootrtap bold](https://cloud.githubusercontent.com/assets/13987267/9504501/f21237ea-4c0a-11e5-9310-9bdeffc817cf.jpg)

**Comment by tip2tail** [comment] 2015-08-26 20:10
More than likely this is a local issue with the fonts on your Windows PC.

Have you tried the same sites on another PC?

**Comment by KrissyKoo** [comment] 2015-08-26 20:13
Yes, I figured it was a font issue, but I've restored my fonts to original fonts twice now with no luck.

**Comment by cvrebert** [comment] 2015-08-26 20:20
Approximate duplicate of #13823. Your probably-non-genuine copy of Helvetica Neue is bad. Either delete it or install a better one. Windows doesn't come with it normally.

**Closed by cvrebert** 2015-08-26 20:20 UTC
