### ISSUE TITLE
search field on website

### ISSUE THREAD

**Issue by virtualgadjo** [twbs/bootstrap#26464] opened 2018-05-07 14:18 UTC
hi guys,
just a word to say that on 4.1 docs website, the menu is ok but the suggested search results are still towards 4.0 url :)
all the best
chris

**Comment by sts-ryan-holton** [comment] 2018-05-07 15:10
Hi :) already mentioned this problem here => https://github.com/twbs/bootstrap/issues/26441

No response yet and this problem is frustrating :/

**Comment by virtualgadjo** [comment] 2018-05-07 16:47
aww sorry, hadn't seen it... well, let's hope the more we are to submit this little issue, the more attention they will pay to it :)
@sts-ryan-holton 
have a nice day :)

**Comment by mdo** [comment] 2018-05-10 10:45
Closing as duplicate of #26441.

**Closed by mdo** 2018-05-10 10:45 UTC
