### ISSUE TITLE
v4 - Change media query breakpoint units from em to px

### ISSUE THREAD

**Issue by niutech** [twbs/bootstrap#17366] opened 2015-08-27 13:26 UTC
Bootstrap 4 uses *em* units when setting breakpoints in media queries, which is inconsintent with screen sizes mesured in *px* and adds unnecessary complexity when converting from *px* to *em*. Does `@media (min-width: 48em) {}` equal well-known 768px? It is hard to tell from the first sight.
Therefore I am asking to bring back the old pixel units in media query breakpoints, unless there is an important reason not to do so. The old [bug](https://bugs.webkit.org/show_bug.cgi?id=53186) with zooming in was fixed long time ago.

Even @mdo (project owner) [said](https://github.com/twbs/bootstrap/issues/1943#issuecomment-3942792):
 > Nope, no em units. They complicate simple values and scales unnecessarily and for little reward. Pixels are fine as browsers just zoom the page without any problem.

and:

 >   Pixels provide absolute control and consistent rendering across every browser.
 >   Designers still mostly think and operate in pixels.
 >   Browsers scale up entire pages these days, so it's not an issue with type scaling or anything.
 >   (...)
 >   In the future, we'll likely use ems for type sizing, perhaps rems even, but not for anything else. This is also debatable on font sizes for inputs and the like. It's just not how folks build pixel perfect sites.

**Comment by kkirsche** [comment] 2015-08-27 13:36
Is this a duplicate of #17070?

**Comment by niutech** [comment] 2015-08-27 13:37
This issue is specifically about media queries, not font sizes.

**Comment by janzelc** [comment] 2015-08-27 21:10
I was originally going to comment noting that em-based media queries work better with browser zooming, but apparently browsers have fixed that behavior.

Therefore, there is no need for em-based media queries, according to https://css-tricks.com/em-based-media-queries-are-based-on/ (see sources linked there).

**Comment by mdo** [comment] 2015-09-02 04:17
Closing for #17403, which will very likely merge.

**Closed by mdo** 2015-09-02 04:17 UTC
Labels: css, v4

**Comment by DanielPintilei** [comment] 2016-03-18 08:29
@mdo http://zellwk.com/blog/media-query-units/

**Comment by niutech** [comment] 2016-03-18 09:00
I'm still certain that screen sizes are measured in *px*, and so should media queries be measured.

**Comment by thibautsapient** [comment] 2016-03-29 11:53
@niutech I'm still certain you haven't read Daniel's link.
