### ISSUE TITLE
Diffence view of  checkbox and radio in chrome and Firefox

### ISSUE THREAD

**Issue by putheakhem** [twbs/bootstrap#19837] opened 2016-05-03 10:43 UTC
In firefox
![screenshot from 2016-05-03 17 39 59](https://cloud.githubusercontent.com/assets/8064772/14980992/52f3dabc-1156-11e6-8c05-f2cbc76ff86b.png)

in chrome
![capture 2016-05-02 at 17 39 40](https://cloud.githubusercontent.com/assets/8064772/14981014/8a59554a-1156-11e6-8b0c-3be1b2f9e3f3.png)

**Comment by PauloFrancaLacerda** [comment] 2016-05-03 11:02
Where is the radio mentioned in the topic title? :)

**Comment by RyanZim** [comment] 2016-05-03 13:38
@putheakhem: Bootstrap doesn't override the browser's default radios and checkboxes. This is also dependent on the OS; I'm on Firefox for Windows and the checkboxes look totally different.

Please close this issue since this is the intended behavior.

**Comment by cvrebert** [comment] 2016-05-03 20:42
Approximate duplicate of #18797.

**Closed by cvrebert** 2016-05-03 20:42 UTC
