### ISSUE TITLE
progress not animating, button state text not working

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [twbs/bootstrap#17226] opened 2015-08-22 08:05 UTC
The progress bar is not animating for me neither on Windows 10 nor Mac Yosemite, both running Chrome 44.

Also, the button state-text toggle (js) is not working for me too. Documentation also has only code example, not a working preview. Maybe because there is an issue as of yet.

**Comment by dtamm** [comment] 2015-08-22 10:24
Not working for me aswell on Windows 7, Firefox 40 and Android 5 with installed Chrome browser!

**Comment by kkirsche** [comment] 2015-08-22 14:25
Duplicate of #17148 please search before creating an issue.

**Comment by hnrch02** [comment] 2015-08-22 16:51
Closing as a duplicate of #17148. Also, stateful button toggles have been removed in v4.

**Closed by hnrch02** 2015-08-22 16:51 UTC
