### ISSUE TITLE
"Sign In" - v4 - Example on shorter screens bleeds off the top of the screen

### ISSUE THREAD

**Issue by stuartaccent** [twbs/bootstrap#25615] opened 2018-02-13 19:24 UTC
Hi,

Due to the use of `align-items: center` when the screen height is too short to fit the content of the form it disappears off the top of the screen like below with no way to scroll to it:

![screen shot 2018-02-13 at 19 05 58](https://user-images.githubusercontent.com/20105514/36168770-1dc5524c-10f2-11e8-8b5d-c01e79f1f6bf.png)

One simple solutions would be to just use a combination of `display: flex` and `margin: auto`, eg

```
html, body {
    height: 100%;
}

body {
    display: flex;
}

form {
    margin: auto;
}
```

![screen shot 2018-02-13 at 19 07 01](https://user-images.githubusercontent.com/20105514/36168927-a285c386-10f2-11e8-99c5-16978328e2b1.png)
![screen shot 2018-02-13 at 19 07 16](https://user-images.githubusercontent.com/20105514/36168930-a61953d2-10f2-11e8-8a5a-0b48b6b2cb00.png)

This will ensure the form will stay centre both x and y and will stick to the top of the page if the page is too short. Then just add what ever padding you want top and bottom of the form to pull it away from the hard edge of the window.

Not sure if there is any side effect to this, ive not seen any so far.

Cheers, Stu

**Comment by mdo** [comment] 2018-02-13 20:30
Duplicate of #25388.

**Closed by mdo** 2018-02-13 20:30 UTC
