### ISSUE TITLE
_process func in scrollspy defaults last nav-item to be active

### ISSUE THREAD

**Issue by hkung77** [twbs/bootstrap#32600] opened 2020-12-23 08:44 UTC
OS: MacOS BigSur v11.1 
Bootstrap Version: 4.5.3
Browser: Chrome Version 87.0.4280.88 (Official Build) (x86_64)

Currently my website (https://hkung.me) if you want to see it reproduced. 
The third nav-item element is always being defaulted to active. 

I found the source to be here: 
https://github.com/twbs/bootstrap/blob/v4.5.3/js/src/scrollspy.js#L203
Where it's defaulting the last item, Perhaps there was a reason why...  
why my max-height and scroll-height are canceling each other 

Here is a screenshot of my debugger when figuring out whats happening.
<img width="933" alt="Screen Shot 2020-12-23 at 5 31 22 PM" src="https://user-images.githubusercontent.com/11062971/102976820-7b61d080-4545-11eb-84e3-fa4f126debbd.png">

Maybe it should default to the first one instead? 
I'm not entirely sure the depth of how much scrollspy is used so perhaps my answer is not well informed enough..

**Comment by NightZan999** [comment] 2020-12-24 05:05
It should ideally default to the current item being scrolled when the page was last reloaded or scrolled. 
But, what they were thinking when working was that it goes to the **last active nav-item** rather than the last one. 
This may be the cause of other scrollspy problems. But as far this issue goes its fixed!

**Comment by hkung77** [comment] 2020-12-24 05:31
Do you mean fixed in v5? or there is a pending pull request?  I will double check :)

**Comment by harnishdesign** [comment] 2020-12-24 06:47
Duplicate of #32496

**Comment by NightZan999** [comment] 2020-12-24 08:40
@hkung77 migrate your project to v5 yes. In v5 it mainly deals with scrollspy and navbars, getting a bit more responsive as well! 
Migrate your project fast, cause there are a ton of changes that are being worked on!

**Closed** 2020-12-29 06:30 UTC
