### ISSUE TITLE
Tabs sometimes not work

### ISSUE THREAD

**Issue by tool321** [twbs/bootstrap#20205] opened 2016-06-29 08:55 UTC
I apply b4-alpha2 on my site [Tool321](http://www.tool321.com/cn/index.html) about 2weeks,but found a bug that the tabs component didn't always work under all of browser(chrome,firefox,edge,etc...),sometimes it valid but sometimes it not ,never found this problem on my old [b3 statble index page](http://www.tool321.com/cn/index_v3.html).

**Comment by cvrebert** [comment] 2016-06-29 17:21
Please be more specific about how it "doesn't work". What actually happens vs. what's supposed to happen?
You've only tested on Windows, correct?

**Comment by tool321** [comment] 2016-07-01 01:31
Only tested on Windows,Safari not included yet,will summit the test result on mac and safari later...
What's supposed to happen is when I click the tabs2-6 ,the tabs1 content shall be hidden and the tabs2-6 content I click shall be displayed ,but actually it didn't work(Still remain on the tabs1) everytime on the same browser(currently tested on chrome 51.0.2704,360 security browser 8.1,firefox developer version 49.0a2 ,edge , all under windows 10.).

just tested My iphone safari  no work either but index_v3 work.

**Comment by patrickhlauke** [comment] 2016-07-01 08:46
cannot reproduce - the tabs worked fine for me on http://www.tool321.com/cn/index.html using Chrome 51.0.2704.106 on Windows 10

**Comment by tool321** [comment] 2016-07-25 05:30
I try to open [http://www.tool321.com/cn/index.html](http://www.tool321.com/cn/index.html) on my PC(Windows10+EDGE,Chrome 51.0.2704.103,etc),each one refresh about 10times,and the bug still reproduce.
And actually I have two PC(one Macbook airbook,one Windows 10 notebook),they both failure if I refresh the page times. Not always work as I described.
Also today one user feedback me the bug and ask me why today.
Maybe u could try this method to reproduce,open the  [http://www.tool321.com/cn/index.html](http://www.tool321.com/cn/index.html) and test the tab,then close the browser,reopen the browser and reopen the  [http://www.tool321.com/cn/index.html](http://www.tool321.com/cn/index.html) then test,repeat for 10times,it should be reproduced as I tested.

**Comment by patrickhlauke** [comment] 2016-07-25 07:33
sorry, but i still cannot reproduce any problems with this. closing this for now. i would suggest creating an isolated test case on jsfiddle.net or similar that shows ONLY the tab component, and reproduces the problem you're describing. otherwise, it's highly likely that the problem is not with bootstrap itself, but with some other part of your site.

**Closed by patrickhlauke** 2016-07-25 07:33 UTC
Labels: awaiting reply, js, v4
