### ISSUE TITLE
4.0.0.beta6: navbar flex-direction set to column

### ISSUE THREAD

**Issue by ssljivic** [twbs/bootstrap#21783] opened 2017-01-19 18:20 UTC
Why is navbar having a flex-direction = column in version 4.0.0.beta6?

**Comment by CyrilWork** [comment] 2017-01-19 18:43
i think to display items from left to right (and not from top to bottom)

**Comment by Olivia101** [comment] 2017-01-20 03:08
@CyrilWork if that was the case then it should be flex-direction: row in order to place the items in horizontal rows (from left to right) instead of vertical columns (from top to bottom) as per the [flexbox guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

**Comment by vanduynslagerp** [comment] 2017-01-23 06:05
This is because by default the navbar is displayed as collapsed (with the burger icon and the menu item hidden and accessible in the dropdown).
When you use `.navbar-toggleable-*` to make the navbar to be expanded (no burger icon) above a certain breakpoint, the `flex-direction` is `row`.

See [_navbar.scss#L147](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_navbar.scss#L147).

**Comment by mdo** [comment] 2017-03-07 06:41
Unsure why this had a milestone assigned to it, but closing out since this was a question and not a bug report with expected changes.

**Closed by mdo** 2017-03-07 06:41 UTC
Labels: css, v4
