### ISSUE TITLE
image display with space in IE10/11

### ISSUE THREAD

**Issue by pcodedviral** [twbs/bootstrap#28857] opened 2019-06-01 05:43 UTC
hello sir,

I am using **windows 10** with **chrome and IE lettest** version browse.

when I am using an **image** inside a **card** so it will make **bottom space in the card** in the **smaller column**.

- please **check** the code in **IE10/11**

https://codepen.io/pcodedviral/pen/RmEpNg

- I have previously created one another bug in **Carousel** ( https://github.com/twbs/bootstrap/issues/28839 ).
- I think **both are a problem is related to one thing**.

thanks. . .

**Comment by ysds** [comment] 2019-06-01 09:41
Duplicate of #22448

**Closed by ysds** 2019-06-01 09:41 UTC
