### ISSUE TITLE
Affix breaks when snapping to the top of page.

### ISSUE THREAD

**Issue by sigmaben** [twbs/bootstrap#16826] opened 2015-07-15 10:04 UTC
I know this is an edge case, but when you scroll to the bottom of a page with an affix nav, then drag the cursor outside the window and back in toward the top of the page in Chrome, the page 'snaps' back to the top of the page. The affixed nav doesn't re-apply the affix-top class as it hasn't scrolled up.

Here is it happening on the Bootstrap site:
![bootstrap](https://cloud.githubusercontent.com/assets/9033679/8696068/3f0e6438-2ae1-11e5-8eb0-e8cc2bec4231.gif)

**Comment by cvrebert** [comment] 2015-07-16 03:07
Duplicate of #15847.

**Closed by cvrebert** 2015-07-16 03:07 UTC
Labels: js
