### ISSUE TITLE
Placeholder images aren't showing as holder.min.js is missing (Label: examples)

### ISSUE THREAD

**Issue by mkrdip** [twbs/bootstrap#16845] opened 2015-07-18 20:38 UTC
The holder.min.js  file is missing from here: https://github.com/twbs/bootstrap/tree/gh-pages/assets/js/vendor 

Screenshot: 
![image](https://cloud.githubusercontent.com/assets/3819579/8763459/d23566d2-2dbe-11e5-9c10-634ac3b92303.png)

For this cause the thumbnails aren't generated here: http://getbootstrap.com/examples/carousel/ & few other places. 

Screenshot: 
![image](https://cloud.githubusercontent.com/assets/3819579/8763463/ff50181a-2dbe-11e5-8ed5-0ec960908f9b.png)

**Comment by cvrebert** [comment] 2015-07-19 00:50
Duplicate of #16699. Please search more next time. Thanks!

**Closed by cvrebert** 2015-07-19 00:50 UTC
