### ISSUE TITLE
Text in <input>s can be vertically scrolled in IE9-11

### ISSUE THREAD

**Issue by asnoba** [twbs/bootstrap#18103] opened 2015-10-29 21:12 UTC
Text in text fields can be dragged up and down in Internet Explorer 9, 10, and 11:
![ie9-cursor](https://cloud.githubusercontent.com/assets/361101/10831926/a8a03afc-7e88-11e5-8479-a9dd8505eb10.png)

By default the text is aligned at the bottom instead of in the middle (but can be dragged up and down): 
![ie9-text](https://cloud.githubusercontent.com/assets/361101/10832025/190c024e-7e89-11e5-88fc-bf1117836b0a.png)

Edge is not affected.

**Comment by cvrebert** [comment] 2015-10-29 21:48
(The "dragging" refers to selecting some text, keeping the mouse button depressed, and moving the pointer above or below the input field.)

**Comment by cvrebert** [comment] 2015-11-23 20:43
CC: @mdo

**Comment by mdo** [comment] 2016-12-25 08:42
Was unable to reproduce this with the latest from `v4-dev` in my Windows 10 VM with IE11 or on Windows 7 VM with IE10. Closing out, but if there's something I've missed, please holler and we can revisit.

**Closed by mdo** 2016-12-25 08:42 UTC
Labels: confirmed, css, v4
