### ISSUE TITLE
.floating-label textareas overlapping text on scroll

### ISSUE THREAD

**Issue by bjCorrosionInstruments** [twbs/bootstrap#37539] opened 2022-11-24 06:19 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Floating-label textareas have overlapping text when text exceeds size of textarea (scrollbar is on).
![image](https://user-images.githubusercontent.com/103553898/203708636-b58f7af2-4eb3-4cfe-834b-123c7bdd36a3.png)

### Reduced test cases

To test: 
https://getbootstrap.com/docs/5.2/forms/floating-labels/#textareas - enter text that exceeds size of textbox.

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.2.0

**Comment by julien-deramond** [comment] 2022-11-24 07:42
My bad. Caused by https://github.com/twbs/bootstrap/commit/06bed9b45af290b05fed9ec003a89af1d3baf6a4 when fixing the disabled behavior.

**Comment by sharmadhiraj86** [comment] 2022-11-25 12:08
Is this issue solved? @julien-deramond

**Comment by julien-deramond** [comment] 2022-11-25 12:18
> Is this issue solved? @julien-deramond

This issue is still opened so not yet.

**Comment by sharmadhiraj86** [comment] 2022-11-25 18:23
So please can you assign this issue to me@julien-deramond ?

**Comment by julien-deramond** [comment] 2022-11-25 18:29
> So please can you assign this issue to me@julien-deramond ?

We don't assign issues. You can create a PR and link it to this issue, no problem :)

**Comment by sharmadhiraj86** [comment] 2022-11-25 18:42
Once we are typing should we remove that comment string or should we let it be and adjust the scrolling accordingly.

**Comment by sharmadhiraj86** [comment] 2022-11-25 18:43
Can you let me know in which file the code related to this section is present.

**Comment by bjCorrosionInstruments** [comment] 2022-11-27 23:11
> Once we are typing should we remove that comment string or should we let it be and adjust the scrolling accordingly.

I'd assume the same behaviour as a text-area in Material: https://material.angular.io/components/form-field/overview
![image](https://user-images.githubusercontent.com/103553898/204164767-2bce9d09-15d3-4125-9b4c-fd8636fc527b.png)

**Comment by sharmadhiraj86** [comment] 2022-11-29 18:11
@bjCorrosionInstruments ok got it .
@julien-deramond can you let me know which line you have added might have caused this issue.

**Comment by julien-deramond** [comment] 2022-11-30 15:04
> @julien-deramond can you let me know which line you have added might have caused this issue.

You already have the information in https://github.com/twbs/bootstrap/issues/37539#issuecomment-1326066037.

> @julien-deramond can you let me know which line you have added might have caused this issue.

I'm sorry @sharmadhiraj86 but I don't have the time to help you precisely on how to tackle this issue. I'll review the PR if you create one. Please don't tag me if I don't answer right away, there are 249 issues and 116 PRs and I'm contributing on my spare time.

**Comment by sharmadhiraj86** [comment] 2022-12-08 09:16
@bjCorrosionInstruments Can you confirm which scss file is linked to floating-labels.md ??

**Comment by julien-deramond** [comment] 2022-12-08 09:19
Again, as you can see in https://github.com/twbs/bootstrap/commit/06bed9b45af290b05fed9ec003a89af1d3baf6a4, it is `scss/forms/_floating-labels.scss`.

**Comment by sharmadhiraj86** [comment] 2022-12-08 09:29
I was working on the same file but the changes that are done in that scss file are not being reflected in localhost.

**Comment by sharmadhiraj86** [comment] 2022-12-08 17:25
One option I think is to make the label position sticky and make the by color of label white. Is this approach fine or do you recommend any other approach?

**Comment by mdo** [comment] 2023-04-02 21:12
We're shipping #38313 in the next alpha release of v5.3.0 and it will address this.

**Closed by mdo** 2023-04-02 21:12 UTC
Labels: css, confirmed, v5
