### ISSUE TITLE
Add Date & Time Picker Support

### ISSUE THREAD

**Issue by Shifrin** [twbs/bootstrap#17503] opened 2015-09-07 09:50 UTC
Many developers & designers like me, try to use date and time pickers in their projects. Therefore, we always need to include separate JS and CSS for the pickers. So I am thinking if it is already attached as a component in Bootstrap like in UI-Kit it will be very useful for the developers & designers.

If it's already requested by someone please ignore this feature request.

**Comment by cvrebert** [comment] 2015-09-07 20:32
Duplicate of #445.
Available third-party libraries for this include https://github.com/eternicode/bootstrap-datepicker

**Closed by cvrebert** 2015-09-07 20:32 UTC
Labels: feature, v4

**Comment by rosieks** [comment] 2017-06-04 19:26
Maybe it's worth mentioning about that date picker at official website?
