### ISSUE TITLE
Carousel with multiple items

### ISSUE THREAD

**Issue by Rufy86** [twbs/bootstrap#37723] opened 2022-12-26 17:16 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I propose a feature that let you to choice how many item show in the carousel per time. if one it is full-width screen, otherwise every element is width as necessary. the beautiful this is let you to customize the prev and next button, not only in appearance but also in position (external, internal to carousel)

### Motivation and context

This feature let you to handle many situations that currently you can't handle without a third-part framework. for example, actually with carousel  you can show just one element per time and full-width screen. this is useful in some situations. but if you have for example 10 element with a little image and little piece of text and you want to show 3-4 element per time, you can't do it. imagine in a website in which you want to show a carousel with 4-5 products in home page to show to the clients some special offers or some little preview about some feature in a landing page of your app or your service. You can't with the current carousel. but with this feature you can do it

**Comment by mdo** [comment] 2022-12-26 17:23
Duplicate of #27652.

**Closed by mdo** 2022-12-26 17:23 UTC
Labels: feature
