### ISSUE TITLE
table responsive is broken

### ISSUE THREAD

**Issue by ppazos** [twbs/bootstrap#23124] opened 2017-07-20 02:53 UTC
Tested on MacOs / Chrome. The table-responsive display: block style makes the table contents to be less than the 100% of the width of the table.

Example, rename to html

[test_responsive_table.html.txt](https://github.com/twbs/bootstrap/files/1161004/test_responsive_table.html.txt)

**Comment by gijsbotje** [comment] 2017-07-20 05:31
have you checked the staging docs? https://twbs.github.io/staging/docs/4.0/content/tables/#responsive-tables

**Comment by H0WARDDD** [comment] 2017-07-20 06:04
I think it happens when the column's width is shorter than the table width: https://jsfiddle.net/bncasp9q/

**Comment by gijsbotje** [comment] 2017-07-20 06:34
Sorry, my point was: have you checked the v4-dev branch if this still happens?
i updated the fiddle with the staging dist css file https://jsfiddle.net/bncasp9q/1/

**Comment by H0WARDDD** [comment] 2017-07-24 03:30
Yes, it still happens

**Comment by mdo** [comment] 2017-08-08 05:16
Dupe of #21577.

**Closed by mdo** 2017-08-08 05:16 UTC
Labels: css, v4
