### ISSUE TITLE
Custom file input overflow when selecting multiple files

### ISSUE THREAD

**Issue by jackmu95** [twbs/bootstrap#31577] opened 2020-09-02 13:03 UTC
When the `multiple' property on a custom file input is enabled and a user selects a lot of files, the filenames overflow the file input.

```html
<div class="custom-file">
  <input type="file" class="custom-file-input" id="customFiles" multiple>
  <label class="custom-file-label" for="customFile">Choose files</label>
</div>
```

![getbootstrap com_docs_4 5_components_forms_(iPad Pro)](https://user-images.githubusercontent.com/2737132/91986488-074cb400-ed2d-11ea-817e-068f45ce356b.png)

This overflow issues can be easy fixed by adjusting the `.custom-file-label` styles a bit:

```scss
.custom-file-label {
  white-space: nowrap;
  overflow-x: hidden;
}
```

![getbootstrap com_docs_4 5_components_forms_(iPad Pro) (1)](https://user-images.githubusercontent.com/2737132/91986764-6ad6e180-ed2d-11ea-84d6-83940308ed4a.png)

**Comment by mdo** [comment] 2020-09-04 02:41
This likely needs two separate patches, one for v4.x and one for v5 since we rewrote the component there.

**Comment by ms-yogi** [comment] 2020-09-09 04:24
@mdo Can I take this?

**Comment by mdo** [comment] 2020-09-17 20:06
@ms-yogi Go for it!

**Comment by XhmikosR** [comment] 2020-11-15 05:57
Is this still an issue with the latest v4-dev? We landed a patch recently #32145.

@patrickhlauke

**Comment by patrickhlauke** [comment] 2020-11-15 15:13
the patch #32145 fixed the size of the hidden input, not the visible label, so the issue is/was still there. made a patch https://github.com/twbs/bootstrap/pull/32160 (but only added `overflow:hidden` ... not sure what the benefit/use of the suggested `white-space:nowrap` was ... happy to add that too if that can be explained a bit?)

v5 is unaffected by this problem, as it uses a completely different approach

> ![Screenshot of v5 new file input - when multiple files are selected, it only shows the number of files and the actual filenames as tooltip](https://user-images.githubusercontent.com/895831/99188671-1a302b80-2755-11eb-9bc9-9e1eaefe1400.png)

**Comment by XhmikosR** [comment] 2020-11-19 14:30
#32160 was merged, thanks @patrickhlauke!

**Closed by XhmikosR** 2020-11-19 14:30 UTC
Labels: css, v4
