### ISSUE TITLE
Bootstrap 4 Carousel - Vertical Scroll Bar displayed when full-width images transition (Chrome)

### ISSUE THREAD

**Issue by J0nKn1ght** [twbs/bootstrap#24951] opened 2017-12-05 16:23 UTC
There seems to be an issue with the Carousel control in Chrome when used full width, at certain sizes.

Here's an example (thanks to Jacob Lett! https://codepen.io/JacobLett/full/PjKLgK/):

![bootstrap 4 carousel issue - chrome](https://user-images.githubusercontent.com/11074901/33617154-e4d49e04-d9d6-11e7-94ab-aa6d59633f08.gif)

It seems to be when you size the window so that the vertical scroll bar changes from having a thumb to being in the disabled state.  At that point, every transition displays the scroll bar whilst it occurs, and then the scroll bar is hidden when the transition is complete.

Here are the version details:
- Operating system and version: Windows 10 Pro (64-bit) Build 15063.726
- Browser and version: Chrome 62.0.3202.94
- The Bootstrap version in Jacob Lett's codepen is alpha 6, but I've tried it with beta 2, and it is still there

I've tried it in Firefox (56.0 & 57.0), and it works fine.
In Microsoft Edge, it does not show the scroll bar, but there are occasional glitches where it seems to skip to the right slightly at the end of the animation, which is probably down to a different issue:
![bootstrap 4 carousel issue - edge](https://user-images.githubusercontent.com/11074901/33617297-444946dc-d9d7-11e7-9fd5-efb923fbe068.gif)

Does anyone have any ideas on how to fix this?

**Comment by kaungmyatlwin** [comment] 2017-12-06 03:37
I tried to reproduce your bug, and I've found another one!

In my case it is a reverse bug. Look at gif.
![dec-06-2017 10-07-10](https://user-images.githubusercontent.com/11173080/33643407-40ec8602-da6d-11e7-8984-6c2a0a9c5bb2.gif)

**Comment by Johann-S** [comment] 2017-12-06 09:10
Is it something present in our current beta 2 ? Because your codepen use our Alpha 6

**Comment by Johann-S** [comment] 2017-12-06 09:30
Ok I made a Codepen with our current beta 2 see : https://codepen.io/Johann-S/pen/YEMmzR
But I'm unable to reproduce that issue on Chrome 62

**Comment by J0nKn1ght** [comment] 2017-12-06 10:00
Hi Johann,
Thanks for creating the new codepen.
Just load it up in Chrome, make sure you're not displaying any additional toolbars, open dev tools (so you can see the window width and height when you resize), and then resize your browser window to 950 x 617, as shown below:
![bootstrap 4 carousel issue - chrome2](https://user-images.githubusercontent.com/11074901/33655686-accf8308-da6b-11e7-8fdb-da8ebcd6e7dd.gif)

It's obviously the aspect ratio that is the determining factor, so as I mentioned before, for any given window width, you just need to increase the window height until the thumb in the vertical scroll bar is removed, and the scroll bar disabled.

**Comment by Johann-S** [comment] 2017-12-06 10:14
Ok saw it thank you :+1:

**Comment by mdo** [comment] 2017-12-27 23:37
You're running into an issue where the browser is unsure of the dimensions of the viewport. I don't know why exactly, but it appears to be resolved when you change your `margin: 30px auto` to use `padding` for the vertical spacing. My guess is the viewport is wanting to collapse the vertical margin when loading the new slide in.

Change to vertical `padding` and you should be okay. Closing out given this isn't a carousel bug.

**Closed by mdo** 2017-12-27 23:37 UTC
Labels: css, v4
