### ISSUE TITLE
Text break on table broke in v4.5

### ISSUE THREAD

**Issue by MitchellCash** [twbs/bootstrap#30963] opened 2020-06-04 08:46 UTC
When dealing with long lines of continuos text in a table I would use the `text-break` class. Since updating to `v4.5` my lines are now overflowing the table when I don't think they should be. Examples below:

| Bootstrap Version | JSFiddle Link | 
|-------------------|---------------|
| Bootstrap v4.5 (long text line overflows table) | [JSFiddle Link](https://jsfiddle.net/v8dteoh1/1/) |
| Bootstrap v4.4 (works as expected) | [JSFiddle Link](https://jsfiddle.net/on9dumtg/1/) |

**Comment by ffoodd** [comment] 2020-06-04 09:38
Duplicate of #30932 — FYI it's been fixed in #30932, so the next v4 release will include the patch.

**Closed by ffoodd** 2020-06-04 09:38 UTC
