### ISSUE TITLE
Click-triggered popover not shown after click following being hidden programmatically.

### ISSUE THREAD

**Issue by Herst** [twbs/bootstrap#16862] opened 2015-07-22 14:00 UTC
1. Go to https://jsfiddle.net/Herst/hmuo38z9/
2. Click 1st button from the left, see popover appearing.
3. Click 2nd button, another popover appearing.
4. Close buttons through scripting by clicking the third button.
5. Click the 1st button again. **Unexpectedly, no popover appears this time!**
6. Click the 2nd button, its popover is back though.
7. Click the 1st button again, you see that its popover is also back (it's the second click that makes the difference).

**Comment by Herst** [comment] 2015-07-22 14:07
If you wonder how this issue can be triggered in real projects then think about the case where one wants popovers that can be dismissed through clicking outside it while also having clickable content in it (which is why trigger wouldn't work). Solution like the numerous ones presented at e.g.: http://stackoverflow.com/a/14857326/2261442 would then close the popover programmatically.

**Comment by Herst** [comment] 2015-07-22 22:34
Does not happen in 3.3.4, so it seems like a regression: https://jsfiddle.net/ot8azoeh/

**Comment by cvrebert** [comment] 2015-07-23 00:57
Duplicate of #16732. Please search more next time.

**Closed by cvrebert** 2015-07-23 00:57 UTC
Labels: js

**Comment by erashishmehta** [comment] 2016-06-09 10:52
@Herst 
without update JS

$('[data-toggle="popover"]').popover(); // unnecessary for the manually triggered one I guess?

$('#btn-show-popover-nobug').click(function () {
    $(this).popover('toggle');
});

$('#btn-hide-popover').click(function () {
    $('#btn-show-popover-bug').popover('hide');
    $('#btn-show-popover-bug').data("bs.popover").inState.click = false;
    $('#btn-show-popover-nobug').popover('hide');
    $('#btn-show-popover-nobug').data("bs.popover").inState.click = false;
});

**Comment by mantuonweb** [comment] 2020-08-27 08:44
@erashishmehta Thanks it helps
