### ISSUE TITLE
Add off-canvas classes or example

### ISSUE THREAD

**Issue by VinnyVicious** [twbs/bootstrap#20251] opened 2016-07-07 02:40 UTC
Off-canvas classes and navigation are essential for true responsive navigation and it's something that seems to be missing for V4.

**Comment by cvrebert** [comment] 2016-07-07 03:43
We already have an example for it: https://github.com/twbs/bootstrap/tree/v4-dev/docs/examples/offcanvas
Duplicate of #17502.

**Closed by cvrebert** 2016-07-07 03:43 UTC
Labels: css, examples, feature, v4
