### ISSUE TITLE
http://v4-alpha.getbootstrap.com/about/accessibility returns 404

### ISSUE THREAD

**Issue by vantienhoven** [twbs/bootstrap#19761] opened 2016-04-18 14:20 UTC
Hi Guys,

Not sure if this is correct , but the following link returns a 404: 

http://v4-alpha.getbootstrap.com/about/accessibility

Thank you, Sacha

**Comment by RyanZim** [comment] 2016-04-18 14:41
Duplicate of #19540; Please close this.

**Comment by patrickhlauke** [comment] 2016-04-18 14:45
indeed. and fixed already in https://github.com/twbs/bootstrap/pull/18819

**Closed by patrickhlauke** 2016-04-18 14:45 UTC
