### ISSUE TITLE
PRE inside LI behavior differs between browsers.

### ISSUE THREAD

**Issue by will-in-wi** [twbs/bootstrap#24364] opened 2017-10-13 18:01 UTC
When `<pre/>` is inside `<li/>`, the bullet is offset in Chrome, but lined up in Firefox.

Reduced test case:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bug reproduction</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous" />
</head>
<body>
  <div class="container">
    <ul>
      <li><pre>This is a test</pre></li>
      <li><pre>This is another test</pre></li>
    </ul>
  </div>
</body>
</html>
```

Firefox screenshot (57.0b8 (64-bit)):
<img width="276" alt="screen shot 2017-10-13 at 12 58 40 pm" src="https://user-images.githubusercontent.com/1298231/31559462-53e9c9a8-b016-11e7-9276-f441f125ff1e.png">

Chrome screenshot (61.0.3163.100 (Official Build) (64-bit)):
<img width="246" alt="screen shot 2017-10-13 at 12 59 51 pm" src="https://user-images.githubusercontent.com/1298231/31559488-6b8e295a-b016-11e7-93fb-4ed981ea2df1.png">

Both on Mac OS X Sierra.

I hope this is helpful!

**Comment by andresgalante** [comment] 2017-10-13 18:40
Hi @will-in-wi Thanks for reporting this.

You are right, this appears only on Chrome and it seems to be a problem on our CSS since browser defaults are ok: https://codepen.io/andresgalante/pen/XePVMG

I took a quick look and I can't spot where the problem is yet

Now, for a single line code you can use `code`:
```html
<li><code>This is another test</code></li>
```

and it'll work better, even in chrome.

**Comment by will-in-wi** [comment] 2017-10-13 18:45
I'm not sure this is a preferred fix, but it looks like the following works around the issue for me:

```html
<li style="line-height: 1rem;">
    <pre style="display: inline-block; vertical-align: top;">Content</pre>
</li>
```

**Comment by andresgalante** [comment] 2017-10-13 18:52
Yeap, for your implementation, just by `display: inline` the `pre` you will fix it. I am trying to see the root of the problem on bootstrap's codebase.

**Comment by MartijnCuppens** [comment] 2019-01-05 23:51
This was fixed in Chrome 64 🎉

**Closed by MartijnCuppens** 2019-01-05 23:51 UTC
Labels: css, v4
