### ISSUE TITLE
.navbar-form moves to new line in Chrome when refreshing page

### ISSUE THREAD

**Issue by chehine1** [twbs/bootstrap#17714] opened 2015-09-27 14:20 UTC
as the title I have problems with the navbar form , in particular with the search form
here is an exemple of the code and next the video showing my problem 
ps : this is only with chrome , on firefox it works perfectly 

code : 
```
<nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
        <ul class="nav navbar-nav">
        <a class="navbar-brand" href="#">Brand</a>
        <li><a href="">Link</a></li>
        <li><a href="">Link</a></li>
        <li><a href="">Link</a></li>
        <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      </ul>

    </div>
    </nav>
```
private video : 
https://youtu.be/IZOpz8AGKHA

**Comment by patrickhlauke** [comment] 2015-09-27 14:27
(updated comment to actually make the markup appear...)

**Comment by patrickhlauke** [comment] 2015-09-27 14:27
please post a reduced testcase showing the problem on http://jsfiddle.net/ or similar

**Comment by chehine1** [comment] 2015-09-27 14:35
http://jsfiddle.net/#&togetherjs=1lMc1SBG9K

**Comment by chehine1** [comment] 2015-09-27 14:46
it works correctly when i run it on http://jsfiddle.net/
( i'm still a beginer on html and css , i am learning so i may don't undrestand you :laughing:

**Comment by cvrebert** [comment] 2015-09-27 19:59
So, that means that the bug presumably lies in your site's code rather than in Bootstrap itself.
For personal support questions like this, please ask your question on StackOverflow, IRC, or Slack; see https://github.com/twbs/bootstrap/blob/master/README.md#community for links.
Thanks, and good luck!

**Comment by TomDoesRUG** [comment] 2015-10-07 09:43
I'm encountering the same problem in chrome. I'm not sure it's a 3.3.5 or chrome issue. Never had this issue in earlier versions

**Comment by cvrebert** [comment] 2015-10-07 20:25
@TomDoesRUG Please post a JS Fiddle or JS Bin that demonstrates the bug.

**Comment by TomDoesRUG** [comment] 2015-10-08 12:22
I'm having trouble reproducing the problem in a JS Fiddle. However the stacking occurs because the <li> elements for my buttons get stacked all of sudden. I've fixed it by overriding the css with:

.navbar-nav>li {
        float: none;
        display: inline-block;
    }

Still its weird this is occurring in an application which has been running for more than a year and the code hasn't changed. Only the bootstrap version and my Chrome version.

**Comment by cvrebert** [comment] 2015-10-23 18:39
Closing due to lack of a reproducible testcase.

**Closed by cvrebert** 2015-10-23 18:39 UTC
Labels: awaiting reply, css, v3

**Comment by digitalprecision** [comment] 2015-11-06 06:33
Damn having same issue, code worked fine, then after upgrade to 3.3.5, and only on Windows Chrome, and only on certain pages, and only on first load those pages does this issue occur. What a PITA. I tried @TomDoesRUG fix, but to no avail...

**Comment by cvrebert** [comment] 2015-11-06 07:13
@digitalprecision We're still open to investigating this if you or someone else can post a reproducible test case. ("Always fails on first load" or "Happens every once in a while if you refresh the page several times" would still count as reproducible for our purposes.)
It can be raw HTML source code, or a JSBin/JSFiddle/CodePen/etc.

**Comment by UsamaIslam** [comment] 2018-03-23 08:59
.input-group .form-control, .input-group-addon, .input-group-btn {
     display: list-item; 
}

this solved my issue
