### ISSUE TITLE
Opening a modal from another modal and modal-open

### ISSUE THREAD

**Issue by AdamSGit** [twbs/bootstrap#20607] opened 2016-09-01 14:59 UTC
When you open a modal from a link in another modal, it close the first modal to switch to the new one, but the body lose his "modal-open" class in the process.

**Comment by patrickhlauke** [comment] 2016-09-01 16:04
Multiple modals are currently not supported.

**Comment by AdamSGit** [comment] 2016-09-01 16:09
Yes I know, it's not the point. The issue is about the body class modal-open.

**Comment by cvrebert** [comment] 2016-09-01 20:49
Duplicate of # 17956.

**Closed by cvrebert** 2016-09-01 20:49 UTC
Labels: js

**Comment by Fusty** [comment] 2016-09-16 19:43
Anyone looking to solve this, it's stupidly easy.  Not sure why they're not implementing something similar to this.  I think I'll submit a pull request for this if I can.

`//Watch for closing modals
$('.modal').on('hidden.bs.modal', function () {
    //If there are any visible
    if($(".modal:visible").length > 0) {
        //Slap the class on it (wait a moment for things to settle)
        setTimeout(function() {
            $('body').addClass('modal-open');
        },200)
    }
});`

**Comment by Metalchocobo** [comment] 2016-10-22 09:32
@Fusty it's no a good solution. In my web app i keep permanently a padding on right of body after close the second modal.

**Comment by Metalchocobo** [comment] 2016-10-22 09:34
@Fusty it's no a coplete solution. In my web app i keep permanently a padding on right of body after close the second modal.

**Comment by john-kamau01** [comment] 2018-04-10 09:30
Try putting the second modal outside the first modal.

**Comment by fahmisabar** [comment] 2018-07-11 09:28
@Fusty Thankyou very much!!

**Comment by k-suresh** [comment] 2018-09-04 09:54
A detailed blog with an example: http://wp.me/p3Osmq-uf

**Comment by Adria-indico** [comment] 2022-08-24 13:40
This worked for me:
Open your second modal programmatically through a click event. That is, remove _data-bs-toggle="modal" and  data-bs-target="#yourModal"_ and do instead:

buttonClick{
    **$(#yourModal).modal('show')**
}
