### ISSUE TITLE
:focus and .active styles indistinguishable on toggle buttons

### ISSUE THREAD

**Issue by gmox** [twbs/bootstrap#15487] opened 2015-01-04 08:25 UTC
PoC: http://getbootstrap.com/javascript/#buttons-single-toggle

In Firefox 33.0 Ubuntu 14.06 LTS and Chrome 38 Ubuntu 14.06 LTS, the active button stays active until it is unfocused.

**Comment by patrickhlauke** [comment] 2015-01-04 12:45
yes, this is a shortcoming of the current styles - ``:focus`` and ``.active`` are indistinguishable, and since even when clicking with the mouse (rather than just moving to the button with the keyboard) the button receives ``:focus``, it's hard to tell the difference between a toggled button and one that's just been switched off... may have a look at this when I get a chance /cc @cvrebert

**Comment by cvrebert** [comment] 2015-01-04 13:21
Duplicate of #13971?

**Comment by patrickhlauke** [comment] 2015-01-04 13:42
Yup - sorry, should have checked for dupes. Closing this, but rest assured we'll be working on this, as it's something that bugged me recently as well :)

**Closed** 2015-01-04 13:43 UTC
Labels: css
