### ISSUE TITLE
Black lines in modal on IE 11, Bootstrap version 3.3.2

### ISSUE THREAD

**Issue by Tiscs** [twbs/bootstrap#15677] opened 2015-01-27 10:34 UTC
Hi, I used bootstrap version 3.3.2 on IE 11, there was some black lines in modal, see the picture below.
![twbsissues](https://cloud.githubusercontent.com/assets/2810237/5916044/7fab2cd4-a647-11e4-8fa3-66a1b34b07c5.png)
Thanks.

**Comment by ggbhat** [comment] 2015-01-27 11:52
@Tiscs I have tested it on my machine everything is working fine. Here is screen shot.
![ie-11-bs](https://cloud.githubusercontent.com/assets/4777119/5917966/f566f7b8-a648-11e4-8469-4da25d61df44.PNG)

**Comment by patrickhlauke** [comment] 2015-01-27 12:05
Confirming that I don't see any black lines in my IE11 either...

**Comment by Tiscs** [comment] 2015-01-27 14:16
Black lines shown when mouse hovered the button, link, or close button, I test on my surface pro 3 and an other virtual machine running windows server 2012 R2.

**Comment by ggbhat** [comment] 2015-01-28 09:07
Again confirming that I don't see any black lines in my IE11 either on hover over any button or link

**Comment by cvrebert** [comment] 2015-01-28 16:47
@patrickhlauke Does hovering make a difference for you?

**Comment by patrickhlauke** [comment] 2015-01-28 16:51
No it doesn't. I cannot seem to replicate this issue, I'm afraid

**Comment by cvrebert** [comment] 2015-01-28 17:32
@XhmikosR Are you able to reproduce this?

**Comment by XhmikosR** [comment] 2015-01-28 17:39
Nope, works fine here.

**Comment by cvrebert** [comment] 2015-01-28 18:04
Closing since we're unable to reproduce the problem.

**Closed by cvrebert** 2015-01-28 18:04 UTC
Labels: css

**Comment by jamiebeech** [comment] 2015-06-28 10:07
I had this issue when testing a web app using V3.3.2 on MS Surface  - IE11. It turns out that IE was set to 150% zoom which was causing these random black lines to appear. Set the browser zoom to 100% and the lines should disappear. I've seen this zoom cause so many random errors on the web that just don't make any sense.
![screen shot 2015-06-28 at 11 05 54](https://cloud.githubusercontent.com/assets/5319622/8395909/cc0194f0-1d85-11e5-9de7-6ded0a253922.png)

**Comment by cvrebert** [comment] 2015-06-30 17:20
@jamiebeech And as noted in our docs, Bootstrap (and a lot of the Web generally) doesn't support that type of non-pinch zooming.
