### ISSUE TITLE
Dropdown icon does not display correctly in Chrome, OSX

### ISSUE THREAD

**Issue by marekmez** [twbs/bootstrap#34046] opened 2021-05-20 14:26 UTC
Dropdown arrow is not displayed correctly in Chrome 90, OSX Mojave. Please see attached screenshot. Icon looks like it has been chopped. This is not a problem in Chrome WIN 10.
<img width="618" alt="Screen Shot 2021-05-20 at 9 21 32 am" src="https://user-images.githubusercontent.com/18588122/118996271-63a04400-b94d-11eb-85bc-122badc14f0a.png">

**Comment by aksdevac** [comment] 2021-05-27 06:34
Yes I can confirm this on current latest Chrome (91.0.4472.77) & Current latest Mac OS (11.4). It looks fine on Safari.
Checked on this link: https://getbootstrap.com/docs/5.0/components/dropdowns/

**Comment by 5ulo** [comment] 2021-07-18 20:46
I can confirm this issue too.

Opera Version:77.0.4054.203 (x86_64)
System:macOS Version 11.3.1 (Build 20E241) 11.3.1 x86_64

0.3em (default)
![Screenshot 2021-07-18 at 22 42 48](https://user-images.githubusercontent.com/4980919/126081662-e54cfde1-3c46-41c0-8c3e-88b55d099200.png)

0.2em
![Screenshot 2021-07-18 at 22 43 09](https://user-images.githubusercontent.com/4980919/126081661-5e14d0b4-cb7d-4394-811f-26bcd251646d.png)

0.4em
![Screenshot 2021-07-18 at 22 44 01](https://user-images.githubusercontent.com/4980919/126081659-00a809d7-d41d-461f-99a9-b74910765dd6.png)

**Comment by mdo** [comment] 2022-02-24 03:35
This seems to be fixed as of at least Chrome 98.

**Closed by mdo** 2022-02-24 03:35 UTC
Labels: css, v5
