### ISSUE TITLE
tabs/pill panel "double display"

### ISSUE THREAD

**Issue by Zophiss** [twbs/bootstrap#16980] opened 2015-08-13 10:20 UTC
Hello.

Found a little issue.
When u do a tab or a pill panel, if u're quick enough to switch between 2 tabs (in fact it seems to be between the begining and the end of the animation) you'll got the data of both in the tab content.

**Comment by kkirsche** [comment] 2015-08-13 13:12
It sounds like this is a race condition. Per [CONTRIBUTING.md](https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#bug-reports), bug reports should include an isolated example of the problem with instructions (as necessary) for us to reproduce the problem. The following can be used as a template on [JSBin](http://jsbin.com/lefey/1/edit?html,output) if that would be helpful.

Thanks for your understanding and cooperation!

**Comment by Zophiss** [comment] 2015-08-13 14:34
Ok
So there is an example : http://jsbin.com/lejukoreki/edit?html,output
To reproduce the problem, u just need to click quickly on tab1 and tab2.
Sorry for not following the rules at first, did not saw them.

**Comment by kkirsche** [comment] 2015-08-13 18:17
I wasn't able to duplicate the bug, though that's not to say it's not happening. @Zophiss what OS / Browser are you using?

**Comment by Zophiss** [comment] 2015-08-13 18:37
I found the problem on Mac OS X, chrome, while working. i also tried on my laptop, Linux mint, chrome too and i was able to reproduce the bug (even on the example tab page of  bootstrap)

I'll explain again what i did. got the focus on the second tab then i click on the 1st tab, then the second tab very quickly, and i got the content of both panels in a single one.

**Comment by cvrebert** [comment] 2015-08-17 19:30
Demo: http://jsbin.com/tariqa/edit?html,js,output

**Comment by kkirsche** [comment] 2015-08-17 19:44
@cvrebert a cursory read over the Tabs JS makes it seem like using a semaphore like "transitioning" to ensure that if transitioning is occurring, don't trigger another instance. Does sound accurate to you?

**Comment by Zophiss** [comment] 2015-08-17 20:03
If it sounds like a decent solution, why not disabling the click event on the others tabs of the panel while transitionning?

**Comment by cvrebert** [comment] 2015-08-17 20:23
@kkirsche We should probably pull the same trick that Carousel does in the analogous case: https://github.com/twbs/bootstrap/blob/767cbef6d43fc773461ab178162bdf3ace6e750c/js/carousel.js#L88

@Zophiss I'm no UX designer, but that seems like it has the potential to frustrate the user.

**Comment by kkirsche** [comment] 2015-08-17 22:39
Well, after an hour and a half of looking at the tooltip and carousel, apparently I don't understand what's occurring from an event perspective here. 

I understand in carousel that if `this.sliding` is true (meaning `.slide` was called), we want to only call the `that.to(pos)` once and not allow that to happen again. Sounds simple enough.

In the tabs though is where I lose what is happening. My thought process is that "showing" occurs once `Tab.prototype.activate` is called on [line 54](https://github.com/twbs/bootstrap/blob/master/js/tab.js#L54). Once that's called, we can set `this.element.showing = true`. We allow that to continue as it would. If `Tab.prototype.show` is called again, we want to stop it since there is already an event in progress. My thought is that we should be able to tell it `if (this.showing) return` since we don't need to call anything again. Apparently though from walking through what's happening, it seems to me that the duplicate is somehow occurring in the callback (though I could be misunderstanding the Chrome Dev Tools break point since the build tool makes using console.log for debugging difficult).

Ultimately, I'd love to put together a PR for this and better understand it, but I understand it may be more work for you guys than to take care of it yourself. Happy to keep working on it with any guidance though or a hint of the right right direction.

My not-fixed thought: https://github.com/kkirsche/bootstrap/commit/5c723beff573c7c70e0570a31f27ecdd8b575f6e

**Comment by mdo** [comment] 2016-09-05 22:26
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Closed by mdo** 2016-09-05 22:26 UTC
Labels: confirmed, js, v3
