### ISSUE TITLE
holder.min.js script is returning a 404 in all examples that use it

### ISSUE THREAD

**Issue by binlabs** [twbs/bootstrap#18107] opened 2015-10-30 01:03 UTC
The example pages that use holder.min.js are returning a 404 for that script:

http://getbootstrap.com/examples/carousel/
http://getbootstrap.com/examples/dashboard/

![image](https://cloud.githubusercontent.com/assets/1139848/10836132/0ee69916-7e78-11e5-9c90-51920370ab63.png)

**Comment by cvrebert** [comment] 2015-10-30 02:15
Duplicate of #16699.

**Closed by cvrebert** 2015-10-30 02:15 UTC
Labels: examples, v3
