### ISSUE TITLE
grunt-babel 5.0.3 why not using 6.0.0

### ISSUE THREAD

**Issue by Johann-S** [twbs/bootstrap#18387] opened 2015-11-30 10:48 UTC
It's just a question, why not updating grunt-babel to 6.0.0 ?

**Comment by cvrebert** [comment] 2015-11-30 22:07
Because there are breaking changes that make it a nontrivial upgrade. It's on our TODO list.
Duplicate of #18212.

**Closed by cvrebert** 2015-11-30 22:07 UTC
Labels: grunt, v4

**Comment by Johann-S** [comment] 2015-11-30 22:11
Thank you
