### ISSUE TITLE
Add responsive margin utility classes

### ISSUE THREAD

**Issue by vinpac** [twbs/bootstrap#20777] opened 2016-09-24 18:26 UTC
Dealing with breakpoints and re-positioning elements, we always face problems with spacing. In one of my projects ( https://github.com/vinpac/base-kit ) I've created a margin-framework that work with breakpoints to solve this and it's been great. So I'm here to suggest this feature.

Example:

```
<div className="col-lg mg-md-bottom-1 col-fill">
  <div className="pull-xs-left pull-lg-none mg-lg-bottom-1">
    <a  href="" className="text-weight-semibold text-accent">
      <i className="fa fa-location-arrow mg-xs-right-2" />
      United States
    </a>
  </div>
  <div className="pull-xs-left pull-lg-none mg-xs-left-3 mg-lg-left-none">
    <a href="" className="text-weight-semibold text-accent">
      <i className="fa fa-comment mg-xs-right-2" />
      English
    </a>
  </div>
</div>
```

--------------------------------------

_variables.scss
```
$margin-horizontal: .5rem .8rem 1.25rem !default;
$margin-vertical: 1rem 2rem 2.5rem !default;
```

_margin-framework.scss
```
@mixin make-margins($position, $margin-list, $breakpoints: $grid-breakpoints) {
  @each $breakpoint in map-keys($breakpoints) {
    @include media-breakpoint-up($breakpoint, $breakpoints) {
      .mg-#{$breakpoint}-#{$position}-none {
        margin-#{$position}: 0 !important;
      }

      @for $i from 1 through length($margin-list) {
        .mg-#{$breakpoint}-#{$position}-#{$i} {
          margin-#{$position}: nth($margin-list, $i);
        }
      }
    }
  }
}
```

_margin.scss
```
@include make-margins(left, $margin-horizontal);
@include make-margins(right, $margin-horizontal);
@include make-margins(top, $margin-vertical);
@include make-margins(bottom, $margin-vertical);

.no-margin {
  margin: 0 !important;
}
```

**Comment by cvrebert** [comment] 2016-09-25 08:09
Approximate duplicate of #18490.

**Closed by cvrebert** 2016-09-25 08:09 UTC
Labels: css, feature, v4
