### ISSUE TITLE
Bootstrap collapse no longer works with 'yarn install'

### ISSUE THREAD

**Issue by ronakrathod18** [twbs/bootstrap#30570] opened 2020-04-13 17:00 UTC
Hello,

Bootstrap collapse does not work with yarn install. **It works without any issues when using npm**. This is not a build time error, I encounter javascript errors on the run-time when collapse button is hit to show and hide.

1. Cannot convert object to primitive value
![image](https://user-images.githubusercontent.com/25513329/79140147-86911980-7d85-11ea-90a4-d26f6e149271.png)

2. Happens here:
![image](https://user-images.githubusercontent.com/25513329/79140266-b5a78b00-7d85-11ea-9931-1de2cf6b584e.png)

Yarn version: 1.22.4
node version: 12.13.0
npm version: 6.12.0
bootstrap version: 4.3.1
Browsers: All browsers

**Comment by mdo** [comment] 2020-04-13 17:42
Try with the latest version of Bootstrap—we're on v4.4.1.

**Comment by ronakrathod18** [comment] 2020-04-13 18:14
Upgraded to 4.4.1 and it does not fix it.  On investigating further what I found was, its actually JQuery 3.5.0 is what is causing the issue. I downgraded to 3.4.1 and it is working fine. My package json has JQuery ^3.4.1, for some reason npm still sticks to 3.4.1 (ideally should upgrade to the next minor version with the ^) while yarn installs 3.5.0

**Comment by XhmikosR** [comment] 2020-04-13 18:23
Duplicate of #30553

**Closed by XhmikosR** 2020-04-13 18:23 UTC
Labels: duplicate
