### ISSUE TITLE
Add/allow center position for tooltip/popover

### ISSUE THREAD

**Issue by cheneveld** [twbs/bootstrap#19921] opened 2016-05-16 22:26 UTC
I would like to use a popover but pass 'center middle' as the attachment value to Tether.

The tooltip AttachmentMap only allows 4 values. Would it be possible to pass the input value through if it is not found in the AttachmentMap? Or maybe add a center mapping?

**Comment by 0x3333** [comment] 2016-05-21 13:18
I don't know If I should create another Issue, but this one seems to fit.

I also would like to position it like, right top, currently I can only position as right middle.

Maybe we could accept `attachment` and `targetAttachment` as Tether already supports it.

Are you guys open for a PR? Or should I go for a plugin?

**Comment by alecpl** [comment] 2017-05-23 09:35
Looks to me as a duplicate of #17759

**Comment by mdo** [comment] 2017-07-02 03:51
Closing for #22962.

**Closed by mdo** 2017-07-02 03:51 UTC
Labels: feature, js, v4
