### ISSUE TITLE
Carousel More Gallery

### ISSUE THREAD

**Issue by HUiTHEME** [twbs/bootstrap#39909] opened 2024-04-17 01:25 UTC
### Prerequisites

- [ ] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [ ] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I want to display 4 pictures in a row, and only switch one picture each time I switch left and right. This requirement is very popular.

Currently, it is possible to display 4 pictures on one screen, but the switching is done one screen at a time. It is not possible to switch one picture at a time. Maybe I am not skilled enough.

### Motivation and context

Similar to swiper;
Although you can use swiper directly;
But if Bootstrap supports it, one less plug-in can be used for development.

**Comment by louismaximepiton** [comment] 2024-04-19 09:29
Duplicate of #29130.

**Closed by louismaximepiton** 2024-04-19 09:29 UTC
Labels: feature
