### ISSUE TITLE
.input-group-btn button height is broken in IE11

### ISSUE THREAD

**Issue by roysanchez** [twbs/bootstrap#17890] opened 2015-10-11 18:04 UTC
The buttons and the input text are misaligned in Internet Explorer. You can see it in the documentation http://v4-alpha.getbootstrap.com/components/input-group/

Tested in IE11.0.23, Windows 8.1

![14](https://cloud.githubusercontent.com/assets/14031944/10418110/afeb3e0a-701f-11e5-9ceb-af2c99cb6593.PNG)
![15](https://cloud.githubusercontent.com/assets/14031944/10418111/afecaa92-701f-11e5-9dcc-d0735d4adca9.PNG)
![16](https://cloud.githubusercontent.com/assets/14031944/10418112/afee72dc-701f-11e5-86e9-25847a2bd99d.PNG)

**Comment by gotoGosub** [comment] 2015-10-19 11:57
Got the same problem (even with less intensity) on Opera 32.0.1948.69 (Windows 10 64-bit)

![bootstrap4_opera](https://cloud.githubusercontent.com/assets/7568389/10577167/1d2ca1c6-7669-11e5-82be-6ce73db51de5.png)

**Comment by twmobius** [comment] 2015-11-24 09:00
Same on Chrome 46.0.2490.86 (OSX 10.10.5)

**Comment by cvrebert** [comment] 2015-12-15 07:57
With Bootstrap v4.0.0-alpha.2, the dropdown btns and `.input-group-lg` now render correctly in Chrome & Blink!Opera.
`.input-group-sm` is still slightly off though.

**Comment by cvrebert** [comment] 2015-12-15 08:00
Closing this as a duplicate of #18083.

**Closed by cvrebert** 2015-12-15 08:00 UTC
Labels: confirmed, css, v4

**Comment by cvrebert** [comment] 2015-12-15 08:05
(The text in the `.form-control`s isn't vertically centered in IE, but that's covered by #18103.)

**Comment by cvrebert** [comment] 2015-12-15 08:19
Filed #18577 regarding the `.input-group-sm` problem in Chrome.
