### ISSUE TITLE
IE 11 Modal input focus weird caret

### ISSUE THREAD

**Issue by etiennejcharles** [twbs/bootstrap#27691] opened 2018-11-19 22:27 UTC
Hello guys :D 

I'm having troubles with my caret 🤕 ~
Left is Chrome, Right is IE11

- [Reduced test case](https://codepen.io/anon/pen/jQaBYW/)

![problem](https://user-images.githubusercontent.com/2872476/48738613-8b4caf00-ec1f-11e8-8da2-1d397535efe7.gif)

Happens on Edge and IE, would the community have an idea why that would happen? I'de gadly PR myself unto this ;) 

The only fix I found is to use a "setTimeout" around IE when using a modal, as we know setTimeouts are weird for animation handling.

I'm just wondering what's the community's take on this.  

- Operating system and version : **Windows 10**
- Browser and version  **IE 11, Edge**,

**Comment by XhmikosR** [comment] 2018-11-21 08:14
I wonder if this happens with the latestv4-dev. @Johann-S @MartijnCuppens  can you check?

**Comment by Johann-S** [comment] 2018-11-21 09:52
I can reproduce it here: https://s.codepen.io/Johann-S/debug/PxEgLL on IE 11 😲

**Comment by MartijnCuppens** [comment] 2018-11-21 18:08
This is clearly a browser bug which is caused by the transitioning of the modal. I don't think we can do anything about this (unless we postpone the autofocus to when the transition is completed)?

**Comment by bkdotcom** [comment] 2018-11-28 17:23
FWIW, there's a pull request that adds out-of-the-box autofocus support to modals
#25651

The focus is performed when the transition completes

**Comment by etiennejcharles** [comment] 2019-01-28 20:49
My temporary fix looks like so. 

```JS
$('#modal').on('shown.bs.modal', function() {
    // Bug fix for focus
    // https://github.com/twbs/bootstrap/issues/27691
    waitBeforeFocusIfIE(focusOnSearch);
});

function waitBeforeFocusIfIE(callback) {
    // Wait 200 seconds before focusing on the search input,
    // because IE can't handle animations so well.
    if (isIE()) {
        var TIMING_MILLISECONDS = 160;
        setTimeout(function() {
            callback();
        }, TIMING_MILLISECONDS);
        return;
    }
    callback();
}

function isIE() {
    return /*@cc_on!@*/ false || !!document.documentMode; // At least IE6
}
```
@bkdotcom: Does your PR, fix that sepcific use case ?

**Comment by bkdotcom** [comment] 2019-01-28 21:11
@etiennejcharles   sorry...  when I originally posted that I thought that internally bootstrap was firing the modal.shown event after the transition ends...  (it's fired from within a `transitionEnd()` method)

it appears that boostrap determines when the transition ends via emulation via a timeout
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/util.js#L92

My guess is a few additional ms should be added to the return value to account for "browser implementation issues"

**Comment by etiennejcharles** [comment] 2019-02-23 19:54
So if I understand the best fix for this, would be to do a PR for it, is that correct ? 
@Johann-S @MartijnCuppens

**Comment by Manuel-Suarez-Abascal** [comment] 2019-05-01 04:46
Hi, 

Does this issue has been resolved? I have tried to recreate the bug to work on it, but I couldn't...
https://s.codepen.io/manuelsuarezabascal/debug/vMwwQE/NQkzYqeaxWvA
 If it is resolved, can we close this issue?

**Comment by mdo** [comment] 2020-03-23 20:16
This is indeed not an issue in v4.4.1 in IE11. Confirmed on my PC here.

**Closed by mdo** 2020-03-23 20:16 UTC
Labels: browser bug, confirmed, css, v4
