### ISSUE TITLE
Navbar screwed up in this example

### ISSUE THREAD

**Issue by jaycbrf4** [twbs/bootstrap#18526] opened 2015-12-10 14:47 UTC
http://v4-alpha.getbootstrap.com/examples/justified-nav/

Still can not understand why you would remove the way the responsive navbar worked in v3. It was one of the best features of Bootstrap-

**Comment by mdo** [comment] 2015-12-10 17:01
Dupe of #17723.

**Closed by mdo** 2015-12-10 17:01 UTC
