### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by rxbracho** [twbs/bootstrap#37308] opened 2022-10-12 16:52 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

The CSS .navbar-nav class has an empty setting  of "--bs-nav-link-font-weight"

### Reduced test cases

The definition is:
`  --bs-nav-link-font-weight: ;`
when it probably should have something like '400' or '600'.

### What operating system(s) are you seeing the problem on?

Windows, Android, Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of Bootstrap are you using?

v5.2.1

**Comment by mdo** [comment] 2022-10-12 19:00
Duplicate of #36595.

**Closed by mdo** 2022-10-12 19:00 UTC
