### ISSUE TITLE
.has-error can't be directly applied to .form-control

### ISSUE THREAD

**Issue by bhantol** [twbs/bootstrap#18713] opened 2015-12-28 21:30 UTC
In order to get a red border and the shadow ``` box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);``` on inputs/selects one needs to wrap these elements into a div so that has-error can be added as a class to this parent.  

Sometimes the form-control may be inside an element that may have other form-controls. In such cases we have to encapsulate form-control into a new div. This requires creating other div to match the CSS selector in bootstrap.css OR one must rewrite the bootstrap css in your code.

Currently we have the bootstrap css as follows:

```
.has-error .form-control {
  border-color: #883333;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
}
.has-error .form-control:focus {
  border-color: #632525;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #c35e5e;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #c35e5e;
}
```

In order for 
```<input class="has-error form-control">``` to work
we need something along the lines as shown below

```
.has-error.form-control,
.has-error .form-control {
  border-color: #883333;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
}
.has-error.form-control:focus,
.has-error .form-control:focus {
  border-color: #632525;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #c35e5e;
  box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 6px #c35e5e;
}
```

**Comment by bassjobsen** [comment] 2015-12-29 23:07
you should compile your own CSS using Less. Enter the following Less code at the and of the `bootstrap.less` file:

    .has-error.form-control {
      &:extend(.has-error .form-control all);
    }

**Comment by cvrebert** [comment] 2015-12-31 21:09
> Sometimes the form-control may be inside an element that may have other form-controls. In such cases we have to encapsulate form-control into a new div. This requires creating other div to match the CSS selector in bootstrap.css

IMHO the tiny "burden" of adding a single div isn't worth adding a special case and more selectors to our CSS.

**Comment by cvrebert** [comment] 2015-12-31 21:14
Actually, this is a duplicate of #16421 and is planned to be addressed in v4.
No plans to address it in v3 though.

**Closed by cvrebert** 2015-12-31 21:14 UTC
Labels: css, v3
