### ISSUE TITLE
List Group Badges Bug

### ISSUE THREAD

**Issue by chasingtheflow** [twbs/bootstrap#24171] opened 2017-09-29 13:51 UTC
I noticed the following issue in the docs where the list group badges are not appearing properly:

![image](https://user-images.githubusercontent.com/718368/31018829-b28f9490-a52d-11e7-94a0-fc4f0e470469.png)

Highlighting the text shows that the numbers are there (in white) but the pills are not rendering:

![image](https://user-images.githubusercontent.com/718368/31018866-da5a983a-a52d-11e7-9740-e56b72e10a74.png)

Inspecting in the console reveals that the entire `badge-default` class may be missing?

Mac OS 10.12.6
Google Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by jipexu** [comment] 2017-09-30 08:28
Hi thanks this is already fixed.

**Comment by mdo** [comment] 2017-09-30 21:02
Duplicate of #23291.

**Closed by mdo** 2017-09-30 21:02 UTC
Labels: css, v4
