### ISSUE TITLE
Vertical alignment of radio/checkbox broken

### ISSUE THREAD

**Issue by drauch** [twbs/bootstrap#27755] opened 2018-12-03 13:43 UTC
Bug reports must include:

- Operating system and version: Windows 10
- Browser and version: Chrome 70
- Reduced testcase: https://getbootstrap.com/docs/4.0/components/forms/#default-stacked

Even in the default theme it is visible that the radio/checkbox controls are slightly located upwards compared to the label text. It becomes more apparent if you use a custom theme.

**Comment by XhmikosR** [comment] 2018-12-03 18:19
Confirmed, just note that v4.0 is quite old.

Current v4-dev live preview https://twbs-bootstrap4.netlify.com/docs/4.1/components/forms/#default-stacked

**Comment by XhmikosR** [comment] 2018-12-03 18:32
@twbs/css-review: using `margin-top: .5rem` fixes the issue for me, but I'm not sure about other OS'es.

**Comment by MartijnCuppens** [comment] 2018-12-03 19:23
Chrome on windows:
<img src="https://user-images.githubusercontent.com/11559216/49394388-03dd6080-f734-11e8-9855-905046b07768.png" width="188" >

Chrome on mac:
<img src="https://user-images.githubusercontent.com/11559216/49394404-122b7c80-f734-11e8-9448-82c576ce56ad.png" width="193">

The height and width of the checkbox on windows is 13px, on mac it's 14px. I don't know if there is a way to create a solution for all OS'es 🤔

**Comment by trollwinner** [comment] 2020-03-25 07:44
Hello everyone!

I don't know if somebody met this issue before but I see the custom controls might have a problem with the alignment with some font-families. Here is an example of "monospace":

![Forms · Bootstrap](https://user-images.githubusercontent.com/5583278/77512302-cb5f1a00-6e83-11ea-9954-521c2fe78def.png)

This extra property should help with it.

```scss
.custom-control-label {
    line-height: $font-size-base * $line-height-base;
}
```

![Forms · Bootstrap (1)](https://user-images.githubusercontent.com/5583278/77512940-09a90900-6e85-11ea-990c-911c528953c4.png)

**Comment by arcanisgk** [comment] 2020-10-28 19:11
I have detected in V4.5 that it is not the only problem; even if we want to place the checkbox in the same row as an input or a Label of normal dimensions; it turns out that the checkbox goes crazy and does not align vertically or horizontally in the markup:

https://stackoverflow.com/questions/64579724/bootstraps-v4-5-checkbox-cannot-be-aligned-horizontally-or-vertically-when-next


![image](https://user-images.githubusercontent.com/1207306/97484940-6989f580-1927-11eb-849f-f8e9eca5c3e2.png)

**Comment by mdo** [comment] 2021-01-10 06:06
Going to consider this one a won't fix given v5 revamped our checks and radios to be custom, consistent sizes.

**Comment by XhmikosR** [comment] 2021-01-10 06:10
I'd say this is still a valid 4.x bug and should be tackled @mdo.

**Comment by mdo** [comment] 2021-01-10 06:22
Given how the components are built, there's not really much flexibility here when v4 has two checkbox and radio components. We're absolutely positioning elements that have variable sizes. The only solution really is the custom forms in v4 and our unified forms in v5. You can see the referenced PR from @MartijnCuppens was closed too because it introduced new issues.

**Comment by XhmikosR** [comment] 2021-01-10 06:28
All right, closing then. I wish there was a way to fix this issue in v4 too.

**Closed by XhmikosR** 2021-01-10 06:28 UTC
Labels: confirmed, css, v4, v5
