### ISSUE TITLE
A potential IE compatibility issue

### ISSUE THREAD

**Issue by bhsstudio** [twbs/bootstrap#19944] opened 2016-05-20 14:55 UTC
Hello there, I notice a potential compatibility issue.This issue only take places in IE. I have tested Firefox and Google Chrome and they are all fine.

Web browser: IE 11
Operation System: Windows server 2012

The problem:

I have two Divs. 

The first one contains a drop down list.

The second one contains a text box and it is set to disabled. In other word, when user move the mouse over the text box, the user will see the mouse pointer turns to a disabled icon.

**The normal view**
![normalview](https://cloud.githubusercontent.com/assets/13529794/15431286/24d78326-1e77-11e6-884e-3df3cbe0f270.png)

**The expanded view**
![expanded](https://cloud.githubusercontent.com/assets/13529794/15431351/6f233614-1e77-11e6-86b8-b62cd14f3fad.png)

The problem is, when you move the mouse onto the "Statute or Regulation" from the dropdown list, the mouse pointer turns form the regular icon to the disabled icon. My guess is because the content "Statute or Regulation" is right on top of the second div and the second div is set to disabled. That explains why the mouse pointer turns to the disabled icon. This only happens to IE.

I tried to take the screen shot but the disabled icon/mouser pointer will not be displayed, sorry about it.

Do you have any suggestion how I can fix it or you guys will fix it? Thank you.

**Comment by cvrebert** [comment] 2016-05-20 15:37
Duplicate of #14528.
It's a bug in IE/Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/817822/
We can't do anything about it on our side.
Workarounds include negating the `cursor: not-allowed` CSS on disabled inputs, or adjusting the layout of forms to eliminate overlaps between `<select>` menus and disabled inputs.

We'd greatly appreciate if you could login and click the "Me too" link on https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/817822/ to let Microsoft know that you care about the bug, so that they'll fix it sooner.

**Closed by cvrebert** 2016-05-20 15:37 UTC
Labels: browser bug, css, v3

**Comment by ajay1008** [comment] 2016-07-25 14:56
Yes, me too facing same issue
