### ISSUE TITLE
Tooltip not working (v4)

### ISSUE THREAD

**Issue by EugeneVdovenko** [twbs/bootstrap#17825] opened 2015-10-09 09:19 UTC
Tooltip not working in Firefox last version. In alpha-docs (http://v4-alpha.getbootstrap.com/components/tooltips/#interactive-demo) too.

**Comment by cvrebert** [comment] 2015-10-09 18:43
Duplicate of #17097. Please search more in the future.

**Closed by cvrebert** 2015-10-09 18:43 UTC
Labels: js, v4
