### ISSUE TITLE
Support Sass Module System (deprecation of @import)

### ISSUE THREAD

**Issue by karen-kua** [twbs/bootstrap#35906] opened 2022-02-25 14:02 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

The Sass maintainers are planning to deprecate `@import` for `@use` and `@forward`. This aligns with their plan to have Sass become more modularized.  The plan is currently to have `@import` deprecated by around October 2022.  As Bootstrap is currently using `@import`, a future release should support the new Sass module system.  

### Motivation and context

Sass maintainers' timeline: https://github.com/sass/sass/blob/main/accepted/module-system.md#timeline

**Comment by stof** [comment] 2022-02-25 23:11
The timeline linked there was mostly about the support of `@use`. The part about deprecating `@import` was only tentative dates suggested in this proposal. And `@import` has **not** been deprecated on October 2021.

**Comment by deadalnix** [comment] 2022-02-26 21:51
Yes please. I ran into problems related to this today, so this is very à propos.

**Comment by mdo** [comment] 2022-02-27 19:24
Duplicate of #29853

**Closed by mdo** 2022-02-27 19:25 UTC
Labels: feature
