### ISSUE TITLE
Text field pushed off screen when modal on a long page with the scroll bar at the bottom of the page. 

### ISSUE THREAD

**Issue by tony1377** [twbs/bootstrap#30291] opened 2020-02-26 20:51 UTC
Steps to recreate

- go to https://115sz.csb.app/
- scroll down to the bottom of the page
- click on the button to open a modal
- focus the element at the top of the modal

expected - first focused element is in view
actual - very bottom of modal is in view, focused elmeent is out of view at the very top of the page. When user presses first letter phone corrects itself and focuses the input.

Devices tested on 
* One Plus 3T, android 9, chrome 80 
* Samsung Galaxy S10, Android v9, Chrome 78

**Comment by ysds** [comment] 2020-02-26 22:15
duplicate of #29438

**Closed by ysds** 2020-02-26 22:15 UTC
