### ISSUE TITLE
Bootstrap icons in sass file not working !!

### ISSUE THREAD

**Issue by adarshmahe** [twbs/bootstrap#15794] opened 2015-02-11 12:29 UTC
The issue is beacuse there need to be double colon(" ") or single colon(' ') on each icon code. Currently only first two icons have double colons.  

stylesheets\bootstrap\_glyphicons.scss

**Comment by patrickhlauke** [comment] 2015-02-11 12:49
duplicate of #15780

**Closed by patrickhlauke** 2015-02-11 12:49 UTC

**Comment by adarshmahe** [comment] 2015-02-11 14:04
@patrickhlauke ok thanks :) ...  didn't see that...
