### ISSUE TITLE
Search in v4.1 Reverts Version Shown in Nav to v4.0

### ISSUE THREAD

**Issue by chrisbo** [twbs/bootstrap#26248] opened 2018-04-10 17:29 UTC
Search in v4.1 reverts version shown in nav to v4.0

**Comment by guar47** [comment] 2018-04-11 14:00
It related to all the 4.1 docs. All links from search go to the 4.0 docs pages (https://getbootstrap.com/docs/4.0/)

**Comment by mdo** [comment] 2018-04-16 02:53
Duplicate of #26224.

**Closed by mdo** 2018-04-16 02:53 UTC
