### ISSUE TITLE
Responsive spacing and flex utilities not working

### ISSUE THREAD

**Issue by trish77** [twbs/bootstrap#26520] opened 2018-05-15 18:23 UTC
Do you plan on fixing the responsive spacing utilities and responsive flex utilities? I cannot get something like pt-sm-3 pt-0 to work and I also tried using d-sm-flex flex-sm-row on a grid structure with col-md-4 col-lg-3 on it and this worked in mobile but messed up the grid in regular responsive desktop or tablet sizes. So I am going to have to write custom spacing classes and flex classes for my mobile layout. Thanks for all your work.

**Comment by trish77** [comment] 2018-05-15 19:56
I did find out how to use them. The documentation is rather confusing. This helped:: https://stackoverflow.com/questions/47446225/bootstrap-4-responsive-spacing-not-working
Now if I can figure out the responsive flex utilities.

**Comment by andresgalante** [comment] 2018-05-16 12:17
Hi @trish77 would you like to send a PR to improve the docs?

**Comment by mdo** [comment] 2018-05-20 22:56
Closing given nothing specific to follow up on and not a bug.

**Closed by mdo** 2018-05-20 22:56 UTC
Labels: docs, v4
