### ISSUE TITLE
docs for target/relatedTarget of Tab events are somewhat unclear

### ISSUE THREAD

**Issue by mrbacay** [twbs/bootstrap#16910] opened 2015-07-30 07:27 UTC
Not sure if I understood the documentation correctly. Did I not?

`jQuery('#list-features').on('shown.bs.tab', function(e) { console.log(e.relatedTarget); })`

**Comment by cvrebert** [comment] 2015-07-30 08:04
It is working as intended. Visually speaking, the anchor is the part that looks like a tab.
However, I agree that the docs' phrasing is somewhat ambiguous and could stand to be clarified.

**Comment by mrbacay** [comment] 2015-07-30 23:52
Thanks for clarifying it

**Comment by mdo** [comment] 2015-11-15 04:42
Punting as a won't fix unless someone has a specific suggestion in a PR to share. <3

**Closed by mdo** 2015-11-15 04:42 UTC
Labels: docs, v3
