### ISSUE TITLE
Tooltip won't show up on official website

### ISSUE THREAD

**Issue by RandomPiche** [twbs/bootstrap#21571] opened 2017-01-06 17:36 UTC
Expected behavior : Tooltip should show up on page http://v4-alpha.getbootstrap.com/components/tooltips/#

Tested on Mac OS X Sierra 10.12.2
On Opera(42.0.2393.94) , Firefox (50.1.0), Chrome (55.0.2883.95)

Console shows those errors : 
`````
docs.min.js:21 jQuery.Deferred exception: e(...).tooltip is not a function TypeError: e(...).tooltip is not a function
    at HTMLDocument.<anonymous> (http://v4-alpha.getbootstrap.com/assets/js/docs.min.js:29:58)
    at f (http://v4-alpha.getbootstrap.com/assets/js/docs.min.js:21:4456)
    at d (http://v4-alpha.getbootstrap.com/assets/js/docs.min.js:21:4771) undefined
te.Deferred.exceptionHook @ docs.min.js:21
d @ docs.min.js:21
C6AILKT.json?segment=placement:getbootstrapcom&callback=_carbonads_go:1 Uncaught SyntaxError: Unexpected token :
docs.min.js:29 Uncaught TypeError: e(...).tooltip is not a function
    at HTMLDocument.<anonymous> (docs.min.js:29)
    at f (docs.min.js:21)
    at d (docs.min.js:21)
(anonymous) @ docs.min.js:29
f @ docs.min.js:21
d @ docs.min.js:21

**Comment by mdo** [comment] 2017-01-06 17:41
Dupe of #21570.

**Closed by mdo** 2017-01-06 17:41 UTC
