### ISSUE TITLE
Customized bootstrap is 3.3.5 while release is 3.3.6

### ISSUE THREAD

**Issue by daute** [twbs/bootstrap#19970] opened 2016-05-26 07:25 UTC
Dear Bootstrap-team,
when I create a customized version at https://getbootstrap.com/customize/ then I still get a version 3.3.5 as download, but the current release is 3.3.6.

Best regards, Wolfgang

**Comment by XhmikosR** [comment] 2016-05-26 12:42
It's the same version, the number only differs.

/CC @cvrebert @mdo

**Comment by cvrebert** [comment] 2016-05-26 16:48
Duplicate of #19320.

**Closed by cvrebert** 2016-05-26 16:48 UTC
Labels: customizer, v3
