### ISSUE TITLE
Can Bootstrap support the Offcanvas in Examples / Experiments

### ISSUE THREAD

**Issue by viktorsmari** [twbs/bootstrap#27721] opened 2018-11-25 09:42 UTC
I have been trying out the **offcanvas** experiment example  with great success under:
https://getbootstrap.com/docs/4.1/examples/offcanvas/

I think these navbar provide the best user experience and I plan to add this to all of the websites I work on. I added a slight modification, make it slide ~80% instead of 100% so you still see the content behind the nav menu.

My **request** is that this will be supported by giving it a section in the 'normal' docs + with code examples. It took me an hour to hack it into my page + finding a way to close the menu by clicking outside the navbar (the last 20% on the screen)

Code example to close the menu by clicking outside found online + slight modification:
```
    $(document).click(function (event) {
      var clickover = $(event.target);
      var _opened = $(".offcanvas-collapse").hasClass("open");
      if (_opened === true && !clickover.hasClass("navbar-toggler-icon")) {
        $('.offcanvas-collapse').toggleClass('open');
      }
    });
```

This is related to a lot of discussion, for example:
#24718 

I could not find why is this an experiment, but not a feature? Are there plans to add it?
I also saw a discussion about creating a new component, but this seems almost complete to me.

**Comment by XhmikosR** [comment] 2018-11-25 11:49
The thing is this can have many variations.

The JS part is very simple, the problem is having this as a CSS component mostly.

/CC @twbs/css-review

**Comment by viktorsmari** [comment] 2018-11-25 17:34
Another suggestion: what about being able to **collapse** to the sides, instead of only _down_ like the current navbar does now?
So when using the navbar, it could be possible to use `.navbar-collapse-right-left` or `.navbar-collapse-left-right` 

Has something like this be discussed before?

Then the developer could just override CSS, for how far he wants to slide the menu like I mentioned above (I personally slide it 70-80% etc.)
Default right / left slide could be 80% or even 100%.

Is the left-right collapse so much different from the currently used up-down, that we cannot offer it?

https://getbootstrap.com/docs/4.1/components/navbar/

**Comment by mdo** [comment] 2018-11-26 20:11
There are other issues and PRs open for an offcanvas, drawer style component. Closing this one out since yes, we do want it, but we need to decide how best to implement it.

**Closed by mdo** 2018-11-26 20:11 UTC
