### ISSUE TITLE
Navbars not working in v4 alpha

### ISSUE THREAD

**Issue by ameenC** [twbs/bootstrap#17870] opened 2015-10-09 14:06 UTC
Hello,
I can't get the navbars to work as expected. Most examples themselves seem to be broken. 
http://v4-alpha.getbootstrap.com/examples/sticky-footer-navbar/
http://v4-alpha.getbootstrap.com/examples/justified-nav/
http://v4-alpha.getbootstrap.com/examples/dashboard/ 

The narrow jumbotron examples gives a 404.
http://v4-alpha.getbootstrap.com/examples/jumbotron-narrow/

Thanks for any suggestion on how to fix the navbars.

**Comment by kkirsche** [comment] 2015-10-09 14:16
Please take a look at the navbar examples found here:
http://v4-alpha.getbootstrap.com/components/navbar/

Also, some of these nabbers have been fixed in the v4-dev branch and can be viewed by cloning the repo and opening them manually. When the next website update gets pushed, then the current state of the examples will be reflected in the links you shared.

**Comment by ameenC** [comment] 2015-10-09 14:38
Thanks a lot @kkirsche those ones seem to be working fine. I noticed they changed the default navigation style for mobile. The navigation is no longer vertical for small screens. It basically just resizes but remains horizontal. Do you know if they're going to drop the old style or keep both?

**Comment by cvrebert** [comment] 2015-10-09 18:59
v4's navbar widget is still a work-in-progress.

> http://v4-alpha.getbootstrap.com/examples/sticky-footer-navbar/
> http://v4-alpha.getbootstrap.com/examples/justified-nav/

Duplicate of #17026.

> http://v4-alpha.getbootstrap.com/examples/dashboard/

Duplicate of #17816.

> The narrow jumbotron examples gives a 404.

Duplicate of #17771.

**Closed by cvrebert** 2015-10-09 18:59 UTC
Labels: examples, v4
