### ISSUE TITLE
v4: container not going full width on xs screens with short text inside

### ISSUE THREAD

**Issue by followthemadhat** [twbs/bootstrap#22268] opened 2017-03-25 14:48 UTC
i noticed, that on extra small screens bootstrap 4 container not going full width if it contains short text. i happen to reproduced the issue with having the short heading and the form inside a container. the form didn't go full width, but as soon as i add the p tag with some text, it goes full width.

**Comment by mdo** [comment] 2017-03-25 17:17
Probably a duplicate of https://github.com/twbs/bootstrap/issues/21590. That said, if this is a bug report...

---

Bug reports must include a live demo of the problem. Per our contributing guidelines, please create a reduced test case via [JS Bin](https://jsbinc.om) and report back with your link, Bootstrap version, and specific browser and OS details.

---

_This is a saved reply._

**Closed by mdo** 2017-03-25 17:17 UTC
Labels: css, v4
