### ISSUE TITLE
<select> input field crops bottom text in beta

### ISSUE THREAD

**Issue by Borkason** [twbs/bootstrap#24037] opened 2017-09-21 14:41 UTC
![grafik](https://user-images.githubusercontent.com/2971735/30701787-74712d06-9eeb-11e7-9061-5f15469da441.png)

Source: https://getbootstrap.com/docs/4.0/components/forms/

I used Mozilla Developer Tools to swap the first `<option>1</option>` on exampleFormControlSelect1 with the alphabet. So the underlying code is 100% correct. The issue came with the beta. Was working fine in alpha.

Windows 10
Firefox 55.0.3

**Comment by andresgalante** [comment] 2017-09-21 14:44
This issue has been reported a few times, This is one of them: #23769 

Unfortunately I can't reproduce it, but it would be great if you can PR to fix it 😄

**Comment by Johann-S** [comment] 2017-09-21 14:59
Closing as duplicate of : #23769

**Closed by Johann-S** 2017-09-21 14:59 UTC
