### ISSUE TITLE
abbr[title] should not have border-bottom

### ISSUE THREAD

**Issue by Rewt0r** [twbs/bootstrap#16574] opened 2015-06-02 11:20 UTC
On the latest Firefox releases this is showing 2 underlines on abbr elements, the specification states that the default CSS for abbr[title] should be:

```css
abbr[title], acronym[title] { text-decoration: dotted underline; }
```

Therefore this is not required in Bootstrap.

Refer to: http://www.w3.org/TR/html5/rendering.html#phrasing-content-0

**Comment by kkirsche** [comment] 2015-06-02 14:35
@Rewt0r I think potentially instead of removing it, it would make more sense to use the `border-bottom` and modify the Firefox one instead of adding the text decoration. This is how it works in the latest Chrome AFAIK.

**Comment by kkirsche** [comment] 2015-06-03 01:59
@Rewt0r would you be able to post an exact browser version where this issue occurs, the operating system which you use, and a JSBin demonstrating the issue? This will make it easier for the core team to quickly test and confirm the issue which you mention.

**Comment by Rewt0r** [comment] 2015-06-03 08:56
@kkirsche Chrome does it that way as it doesn't support the above CSS, not conforming to specification, see [here](https://code.google.com/p/chromium/issues/detail?id=480213).

This affects Firefox 40+, there is no need for JSBin as running the latest Firefox you can see the double underline on the [this page](http://getbootstrap.com/css/#type-abbreviations).

![untitled](https://cloud.githubusercontent.com/assets/2598704/7956279/c7b166c2-09d6-11e5-8ac5-efec4f0acf64.png)

**Comment by cvrebert** [comment] 2015-06-04 01:50
Relevant Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1157083

**Comment by cvrebert** [comment] 2015-06-04 01:56
@Rewt0r Ah, link to your bug next time :-) https://bugzilla.mozilla.org/show_bug.cgi?id=1170480

**Comment by cvrebert** [comment] 2015-06-04 02:23
X-Ref: https://github.com/necolas/normalize.css/pull/451

**Comment by kkirsche** [comment] 2015-06-05 01:12
X-Ref Pull Request: necolas/normalize.css#456

**Comment by mathiasbynens** [comment] 2015-06-10 11:41
@kkirsche 

> I think potentially instead of removing it, it would make more sense to use the `border-bottom` and modify the Firefox one instead of adding the text decoration. This is how it works in the latest Chrome AFAIK.

Mozilla didn’t make the change at random. There’s two reasons behind it:

1. https://bugzilla.mozilla.org/show_bug.cgi?id=1157083 indicates the `border-bottom`-based solution that Firefox previously used doesn’t look very good when used with the Japanese Meiryo (メイリオ) font that is pre-installed on Windows versions since Vista.

2. [The UA stylesheet in the HTML spec](https://html.spec.whatwg.org/multipage/rendering.html#phrasing-content-3) suggests to use `abbr[title], acronym[title] { text-decoration: dotted underline; }`. This change matches the spec.

Hopefully this explains why your proposal is not a good solution.

**Comment by kkirsche** [comment] 2015-06-10 11:58
Yep, saw that in the x-ref which explained all of that :) thanks for the links though

**Comment by mdo** [comment] 2015-06-18 23:14
Can we close since this doesn't appear to be something we'll be fixing in Bootstrap?

**Comment by XhmikosR** [comment] 2015-07-05 07:45
I just hit this with FF 40 beta. Not sure what we can do but currently it's not right either.

**Comment by cvrebert** [comment] 2015-07-05 08:14
In addition to being affected by this due to Normalize.css, Bootstrap is also directly affected due to https://github.com/twbs/bootstrap/blob/0db18386a295a3fc6bf7bd48a047c0d8aa10a77e/less/type.less#L237

**Comment by XhmikosR** [comment] 2015-07-05 08:20
True that.

What do you think we should do @cvrebert? I mean, we should address this as soon as possible since it just looks bad on Firefox. On the other hand, I know Firefox doesn't have the user share Chrome has, but since I use it personally, I'd like to sort this out as soon as possible :)

How about we just use [@supports](http://caniuse.com/#search=supports)?

**Comment by XhmikosR** [comment] 2015-07-05 08:22
For the tooltip plugin, we could move that style to JS and inject it according to the browser, although I'm not sure I like browser sniffing.

**Comment by cvrebert** [comment] 2015-07-05 08:36
@XhmikosR Yeah, I think we should apply either `@supports` or https://github.com/necolas/normalize.css/pull/451 in `type.less` & `normalize.less`.

**Comment by XhmikosR** [comment] 2015-07-05 08:43
But what about other browsers? I mean, they don't all implement this. So `@supports` seems like the best solution at this point, right?

**Comment by patrickhlauke** [comment] 2015-07-05 08:47
`@supports` seems the cleanest solution to me (from a philosophical point of view, not thoroughly tested yet)

**Comment by cvrebert** [comment] 2015-07-05 08:48
\*shrug* I defer to @mdo on which of the 2 methods to use.

**Comment by mdo** [comment] 2015-07-06 01:09
I'm in favor of necolas/normalize.css#451.

**Comment by XhmikosR** [comment] 2015-07-06 05:41
But that would remove the border for all browsers, even those which don't have it...

**Comment by cvrebert** [comment] 2015-07-06 06:01
@XhmikosR So what? It's a harmless no-op if the browser doesn't support `text-decoration`.

**Comment by XhmikosR** [comment] 2015-07-06 06:07
Well, the browsers that don't have this are the all except for Firefox 40+, right?

**Comment by XhmikosR** [comment] 2015-07-06 06:08
Ah, never mind, I thought that normalize.css patch was just removing `border`. That solution seems fine with most browsers indeed, so I say we go with that for now too.

**Comment by patrickhlauke** [comment] 2015-07-06 07:38
> Well, the browsers that don't have this are the all except for Firefox 40+, right?

Ah, thinking it through myself, if the end result would be something like

```
abbr[title], acronym[title] { border-bottom: ... }

@supports (text-decoration: dotted underline) {
	abbr[title], acronym[title] { text-decoration: dotted underline; border-bottom: none; }
}
```

then yeh, that'd work nicely. :+1:

**Comment by mdo** [comment] 2015-08-05 03:26
Closing for now—we'll get the fix from Normalize whenever it happens <3.

**Comment by jonathantneal** [comment] 2016-01-23 02:04
This issue has been resolved by necolas/normalize.css@5304c78 and a new release will be coming soon.

**Comment by niemyjski** [comment] 2016-04-12 20:42
can this get back ported to v3

**Comment by jonathantneal** [comment] 2016-04-12 20:50
@niemyjski, I think it’s possible, but is there any reason you couldn’t use v4?

**Comment by niemyjski** [comment] 2016-04-12 21:01
@jonathantneal Yes my app is deployed in production and our customers are seeing this with firefox and opera. Also v4 is alpha and will break a lot of stuff on top of it I'm using less.

**Comment by XhmikosR** [comment] 2016-04-12 21:09
Last time I tried this in Chrome it resulted in a black solid line for
abbr. I will need to check again. Also I was under the impression we had
backported this but apparently not.

**Comment by jonathantneal** [comment] 2016-04-12 21:09
I don’t know about “alpha”, but normalize.css v4 has had a proper release. A lot of people and time and testing went into v4. There were also a lot of [fixes](https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md#400-march-19-2016) beyond that particular issue. I also understand if you would want to just patch this one thing; and in that case I would recommend adding this line to your CSS.

```css
 abbr[title] {
   border-bottom: none;
   text-decoration: underline;
   text-decoration: underline dotted;
  }
```

**Comment by niemyjski** [comment] 2016-04-12 21:16
Works in firefox but results in solid underline on chrome and others

**Comment by XhmikosR** [comment] 2016-04-12 21:21
Yeah that is what I said above too.

**Comment by jonathantneal** [comment] 2016-04-12 21:46
Chrome and Firefox are implementing `abbr[title], acronym[title] { text-decoration: dotted underline; }` per the W3C specification [HTML5 Section 10.3.4](https://www.w3.org/TR/html5/rendering.html#phrasing-content-0). Firefox has already released this change. Other browsers have not.

Remember, other browsers never styled `abbr` to begin with. The style you know from normalize.css v3 came from the Firefox style, and Firefox has since changed that style to match the spec. Therefore, normalize.css should not invent a normalization that does not follow any browser or specification.

As for the solid line; the nearest fallback for `text-decoration: underline dotted` is `underline`, which is equivalent to `underline solid`. This is why you see a solid line. You are experiencing the same thing your IE visitors have been experiencing for years, which is being a little behind the curve and getting the fallback.

As [Chrome adds this update](https://codereview.chromium.org/1641703006/) (which might come sooner if you ask them for it), your visitors will receive the `dotted` experience. Does this help clarify the situation?

**Comment by niemyjski** [comment] 2016-04-13 14:07
@jonathantneal Thanks! that did the trick and I also left a message on the chrome issue tracker

**Comment by mdo** [comment] 2016-09-05 22:25
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Closed by mdo** 2016-09-05 22:25 UTC
Labels: confirmed, css, v3

**Comment by davidstosik** [comment] 2016-10-16 05:01
The problem is still here on v4-dev. I get underline and dotted border-bottom.

![image](https://cloud.githubusercontent.com/assets/816901/19415313/a01c0782-93a7-11e6-9306-2e2293e1cf85.png)

(Screenshot taken on Chrome v53 for Mac.)

[_reboot.scss:114](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_reboot.scss#L114)

```scss
// Abbreviations and acronyms
abbr[title],
// Add data-* attribute to help out our tooltip plugin, per https://github.com/twbs/bootstrap/issues/5257
abbr[data-original-title] {
  cursor: help;
  border-bottom: 1px dotted $abbr-border-color;
}
```

[_normalize.scss:112](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_normalize.scss#112)

```scss
//
// 1. Remove the bottom border in Firefox 39-.
// 2. Add the correct text decoration in Chrome, Edge, IE, Opera, and Safari.
//

abbr[title] {
  border-bottom: none; // 1
  text-decoration: underline; // 2
  text-decoration: underline dotted; // 2
}
```

In the resulting `boostrap.css`, the [reboot part](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L351) goes lower than the [normalize part](https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L65), and the border ends up being shown.
