### ISSUE TITLE
bootstrap 4 missing examples

### ISSUE THREAD

**Issue by marcustisater** [twbs/bootstrap#17406] opened 2015-08-31 06:57 UTC
missing example link http://v4-alpha.getbootstrap.com/examples/jumbotron-narrow/

**Comment by cvrebert** [comment] 2015-08-31 08:45
Duplicate of #17174. Please search next time!

**Closed by cvrebert** 2015-08-31 08:45 UTC

**Comment by marcustisater** [comment] 2015-08-31 12:44
Sorry, thank you.
