### ISSUE TITLE
Floated nav-item dropdown placement issues.

### ISSUE THREAD

**Issue by dmbuchta** [twbs/bootstrap#21165] opened 2016-11-19 00:02 UTC
A floated right nav-item, with a dropdown menu appears off the page.

```
<nav class="navbar navbar-dark bg-inverse navbar-fixed-top">
<ul class="nav navbar-nav">
<li class="nav-item dropdown float-xs-right">
    <a class="nav-link dropdown-toggle" href="#" id="userActionsDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-list"></i>
    </a>
    <div class="dropdown-menu" aria-labelledby="userActionsDropdown">
        <a class="dropdown-item" href="#">Logout</a>
    </div>
</li>
</ul>
</nav>
```

I've identified the issue is with the following css:

```
.dropdown-menu {
...
...
left: 0
...
}
```

**Comment by bardiharborow** [comment] 2016-11-20 02:18
Duplicate of #17167.

**Closed** 2016-11-20 17:28 UTC
