### ISSUE TITLE
Deprecation Warning Sass 1.56 Passing a number without unit 

### ISSUE THREAD

**Issue by snmabaur** [twbs/bootstrap#37441] opened 2022-11-07 14:56 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I've updated SASS to 1.56 and get the following deprecation warning

```
Deprecation Warning: $weight: Passing a number without unit % (100) is deprecated.

To preserve current behavior: $weight * 1%

More info: https://sass-lang.com/d/function-units

    ╷
201 │   @return mix(rgba($foreground, 1), $background, opacity($foreground) * 100);
    │           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/bootstrap/scss/_functions.scss 201:11            opaque()
    node_modules/bootstrap/scss/mixins/_table-variants.scss 4:28  table-variant()
    node_modules/bootstrap/scss/_tables.scss 147:3                @import
    node_modules/bootstrap/scss/bootstrap.scss 20:9               @import
```

### Reduced test cases

Add unit (100%)
`
@function opaque($background, $foreground) {
  @return mix(rgba($foreground, 1), $background, opacity($foreground) * 100%);
}
`

### What operating system(s) are you seeing the problem on?

macOS

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

5.2.2

**Comment by julien-deramond** [comment] 2022-11-07 16:14
Duplicate of #37424

**Closed by julien-deramond** 2022-11-07 16:14 UTC
