### ISSUE TITLE
Add off-canvas menu

### ISSUE THREAD

**Issue by maghrab** [twbs/bootstrap#17920] opened 2015-10-14 02:19 UTC
I would like to implement a (slide/push) menu feature into Bootstrap. I am looking to get approval before I start integrating the feature.

**Comment by kkirsche** [comment] 2015-10-14 02:31
Would you be able to provide an example of what you mean? Do you mean an off canvas navigation option similar to the provided example? Note that the public website is not accurate for the example and the current version on git should be used as it has been updated since alpha 1 was released.

**Comment by maghrab** [comment] 2015-10-14 02:51
Yes, similar to the example. But it would be the main menu instead. So for example, you would have " glyphicon glyphicon-menu-hamburger " at the top left or right depending on what the user wants and then if you click on it it would either push the screen or cover it. That, of course, should be responsive and work with any screen size.

**Comment by cvrebert** [comment] 2015-10-14 04:43
Duplicate of #17502. @mdo would be the guy to ask for approval from.

**Closed by cvrebert** 2015-10-14 04:43 UTC
Labels: feature, v4
