### ISSUE TITLE
Breakpoints and container width

### ISSUE THREAD

**Issue by chaofix** [twbs/bootstrap#18517] opened 2015-12-10 07:07 UTC
Hi

I saw that the $grid-breakpoints list and $container-max-widths list and saw that the width of sm is odd to me.

on the $grid-breakpoints the size is: 544px
on the $container-max-widths the size is: 576px

the other sizes are ($grid-breakpoints / $container-max-widths): 768px / 720px (md) 992px / 940px (lg) and 1200px / 1140px (xl).
How is it that all of the sizes of the $container-max-widths are lower than the $grid-breakpoints but on the SM is different?

Is it a bug?
![2015-12-10_08h50_06](https://cloud.githubusercontent.com/assets/7779923/11709107/686e8154-9f1d-11e5-83f0-1a8564e82868.png)

**Comment by cvrebert** [comment] 2015-12-10 08:20
Duplicate of #18054. Please search more in the future.

**Closed by cvrebert** 2015-12-10 08:20 UTC
Labels: css, v4
