### ISSUE TITLE
main pointing to less file..

### ISSUE THREAD

**Issue by bialikover** [twbs/bootstrap#16992] opened 2015-08-15 18:55 UTC
I know that everybody is using less but...
shouldn't be the main bower.json file pointing to the dist/css instead less folder?
https://github.com/twbs/bootstrap/blob/master/bower.json#L18

``` json
"main": [
    "less/bootstrap.less", 
    "dist/js/bootstrap.js"
  ],
```

I discover this because I'm using wiredep to inject my css and js files, and the css in dist is not being injected.

Any thoughts?

**Comment by kkirsche** [comment] 2015-08-15 19:09
We didn't forget; it's deliberate.
Duplicate of #16663.

**Closed** 2015-08-15 19:26 UTC
