### ISSUE TITLE
Progress Bar animation not working

### ISSUE THREAD

**Issue by mtrstudio** [twbs/bootstrap#20200] opened 2016-06-28 21:03 UTC
Hi I am using Chrome on windows 10,
It seems the progress bar does not animate itself on v4-bootstrap documentation page (http://v4-alpha.getbootstrap.com/components/progress/)

But it works fine on bootstrap3 page (http://getbootstrap.com/components/#progress).

Is this a bug?

**Comment by cvrebert** [comment] 2016-06-28 23:14
Duplicate of #17148. Please search more in the future. Thanks.

**Closed by cvrebert** 2016-06-28 23:14 UTC
Labels: css, v4
