### ISSUE TITLE
Preceding button in Button addons has extra border visible in low DPI screens

### ISSUE THREAD

**Issue by kushalpandya** [twbs/bootstrap#20427] opened 2016-08-01 06:44 UTC
Preceding (or prefix?) buttons in  [Button addons](http://v4-alpha.getbootstrap.com/components/input-group/#button-addons) have extra margin which makes it appear as if it has thick borders (actually 2 borders of button and input box).

It appears clearly only on low DPI screen, I tested on **20 inch 1080p monitor**.

Here's a screenshot. Direct link to image is [here](http://imgur.com/fSvWS5Z).
![Button addons](http://i.imgur.com/fSvWS5Z.png)

- Affects Bootstrap Version: **v4 Alpha 3**
- Tested on: **Chrome 52 (64Bit)** on **Windows 7**.
- Screen: **21" Dell Monitor, 1080p**.

This glitch was present in v4 alpha 2, and also is present in alpha 3.

**Comment by utkarshkukreti** [comment] 2016-08-01 09:06
I can reproduce this on the current v4-alpha site on Chrome 51 on OS X 10.11.4 on a 2880x1800 15" Retina Macbook Pro. This does _not_ happen on Firefox 47 on the same system.

Screenshot on Chrome 51:
<img width="858" alt="screen shot 2016-08-01 at 2 30 05 pm" src="https://cloud.githubusercontent.com/assets/217126/17288880/c8ebda28-57f4-11e6-804a-5485ea364bba.png">

**Comment by cvrebert** [comment] 2016-08-01 16:07
Duplicate of #14237.
Acknowledged bug in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=534750

**Closed by cvrebert** 2016-08-01 16:07 UTC
