### ISSUE TITLE
Android font boosting woes

### ISSUE THREAD

**Issue by florinhangu** [twbs/bootstrap#17715] opened 2015-09-27 14:43 UTC
Hello. I do use bootstraps 3.5 and i have one issue.. If i add more words, my text is larger.. I dont know why.. Please, help me...

I do that from my phone, but media width is not activated.. I get this..

http://s17.postimg.org/n85cbngen/Screenshot_2015_09_27_17_41_31.png

**Comment by florinhangu** [comment] 2015-09-27 14:46
This is how it looks with only few words...


http://s15.postimg.org/3zy4jjvqj/Screenshot_2015_09_27_17_44_24.png

**Comment by florinhangu** [comment] 2015-09-27 15:08
Even more.. Idk what i did.. Now even dropdown dont work anymore...

**Comment by mdo** [comment] 2015-09-27 16:06
The test sizing is an Android feature I believe. Unsure how to disable it.

**Comment by florinhangu** [comment] 2015-09-27 16:25
Okai.. Then why my dropdown dont work anymore?

**Comment by kkirsche** [comment] 2015-09-27 16:44
Instead of PNGs can you share a live example such as a JSBin or JSFiddle of isolated problem code? That would be greatly appreciated while debugging :)

**Comment by florinhangu** [comment] 2015-09-27 16:54
https://jsbin.com/woxomajide/edit?html,css,output

**Comment by cvrebert** [comment] 2015-09-27 20:16
Probable duplicate of #11472.
See also https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust and http://stackoverflow.com/questions/13430897/how-to-override-font-boosting-in-mobile-chrome

**Comment by florinhangu** [comment] 2015-09-27 20:30
I did add "text-size-adjust: none;" line. And i did my lines shorter using paragraphe for each. I have no issue right now with text.. I do have with dropdown menu.. Dont show anymore...

**Comment by patrickhlauke** [comment] 2015-09-27 20:59
maybe because your jsbin, at least, does not seem to actually include the bootstrap JS file?

**Comment by florinhangu** [comment] 2015-09-28 06:51
I see... No js.. No dropdown menu...

**Comment by mdo** [comment] 2015-09-28 16:17
Yup, you need the JS plugins we provide for our dropdowns.

**Closed by mdo** 2015-09-28 16:17 UTC
Labels: css, v3
