### ISSUE TITLE
Large floating select cuts off text

### ISSUE THREAD

**Issue by abibell** [twbs/bootstrap#33033] opened 2021-02-10 01:09 UTC
**Large floating select** cuts off the bottom part of the text
- Doesn't seem to occur if the select is not large
- Windows & Chrome latest
- See [JS Bin](https://jsbin.com/jeyukohefu/1/edit?html,output)
- v5.0.0-beta1

![image](https://user-images.githubusercontent.com/544653/107450077-bae98800-6b98-11eb-83ab-e1573af49fc3.png)

**Comment by XhmikosR** [comment] 2021-02-10 13:08
It seems fixed on main, tested with `https://twbs-bootstrap.netlify.app/docs/5.0/dist/css/bootstrap.min.css`

**Comment by XhmikosR** [comment] 2021-02-10 13:09
Oops NVM, I mixed the browsers while testing. I can reproduce with Edge Chromium on  Windows

**Comment by vincentcaitech** [comment] 2021-02-13 02:02
Hi, I'm currently working on this issue. I was able to reproduce it.

**Comment by alecpl** [comment] 2021-03-06 13:51
Duplicate of #32672 ?

**Comment by ffoodd** [comment] 2021-03-08 12:59
@alecpl is right, closing this as duplicate. Feel free to comment again in the initial issue.

**Closed** 2021-03-08 13:00 UTC
Labels: css, v5

**Comment by jaxramus** [comment] 2022-06-24 12:14
yeah this is still happening even on the latest version: https://stackblitz.com/edit/hxnclf?file=index.html
