### ISSUE TITLE
dropdown-menu-center  add feature

### ISSUE THREAD

**Issue by eturerer** [twbs/bootstrap#30174] opened 2020-02-14 18:31 UTC
dropdown-menu-center  add feature

https://jsfiddle.net/VovanR/2ao5b22h/

**Comment by florianlacreuse** [comment] 2020-02-17 21:59
Related to #22962.

**Comment by mdo** [comment] 2020-03-20 16:08
Closing as dupe of #22962.

**Closed by mdo** 2020-03-20 16:08 UTC
