### ISSUE TITLE
Feature request: Touch Swipe in Carousel Bootstrap 4

### ISSUE THREAD

**Issue by VadymVolos** [twbs/bootstrap#23536] opened 2017-08-18 06:42 UTC
Hi!

Please, need:
Touch Swipe in [Carousel Bootstrap 4](https://getbootstrap.com/docs/4.0/components/carousel/) (for Desktop and Mobile).

Example 1: http://www.masterslider.com/wordpress/pro/templates/creative-agency-slider/
Example 2: http://www.masterslider.com/features/templates/staff-carousel-version-2/
Example 3: http://www.masterslider.com/wordpress/pro/templates/fashion-slider/

I read #17750
But there's no what I need.

**Comment by Johann-S** [comment] 2017-08-18 07:41
Duplicate of #17118

**Closed by Johann-S** 2017-08-18 07:41 UTC
