### ISSUE TITLE
Margin of right narbar item

### ISSUE THREAD

**Issue by fredgate** [twbs/bootstrap#18743] opened 2016-01-01 19:51 UTC
In a navbar, why items that are floated to left have a left margin and this floated to right do not have ? This produces a difference between the two extreme items.

See line 382 in the navbar.less file :
```
// Component alignment
//
// Repurpose the pull utilities as their own navbar utilities to avoid specificity
// issues with parents and chaining. Only do this when the navbar is uncollapsed
// though so that navbar contents properly stack and align in mobile.
//
// Declared after the navbar components to ensure more specificity on the margins.

@media (min-width: @grid-float-breakpoint) {
  .navbar-left  { .pull-left(); }
  .navbar-right {
    .pull-right();
    margin-right: -@navbar-padding-horizontal;       // Why this ?

    ~ .navbar-right {
      margin-right: 0;
    }
  }
}
```

**Comment by cvrebert** [comment] 2016-01-01 19:58
Duplicate of #18355.

**Closed by cvrebert** 2016-01-01 19:58 UTC
Labels: css, v3
