### ISSUE TITLE
After beta2 table-responsive isn't 100% wide

### ISSUE THREAD

**Issue by dushkostanoeski** [twbs/bootstrap#24462] opened 2017-10-20 08:28 UTC
Before the update, all my tables were responsive and 100% wide. After the update to beta2 it is not the case. I'm not sure but I think that this isn't a desired outcome.

https://jsfiddle.net/25Lebsmm/1/

**Comment by Johann-S** [comment] 2017-10-20 08:36
See : https://getbootstrap.com/docs/4.0/content/tables/#responsive-tables

**Comment by alecpl** [comment] 2017-10-20 08:57
See also #24256. Looks like an intentional change.

**Comment by dushkostanoeski** [comment] 2017-10-20 09:03
Should have clarified a bit more. The table is responsive, scrolls horizontally and and looks good on mobile, but it isn't 100% wide on big screens. And yes, it looks like a duplicate of #24256, my bad.

So this means that if I want a responsive table, I can't have it 100% wide if it doesn't fit the screen?

**Comment by dushkostanoeski** [comment] 2017-10-20 13:17
[This](https://github.com/twbs/bootstrap/issues/24256#issuecomment-334835123) is a viable workaround for now, but it should be marked as a bug since the table is expected to have 100% width.

**Comment by mdo** [comment] 2017-10-22 19:14
Duplicate of #24256.

**Closed by mdo** 2017-10-22 19:14 UTC
Labels: awaiting reply, css, v4
