### ISSUE TITLE
Table-dark doesn't have rounded corners

### ISSUE THREAD

**Issue by joel6653** [twbs/bootstrap#33265] opened 2021-03-05 02:17 UTC
macOS 11.2.2
Safari 14.0.3

`<table class="table rounded-3">`
   ...
`</table>`

gets rounded corners

`<table class="table table-dark rounded-3">`
   ...
`</table>`

does not

(it does not matter what the actual table content, represented by ellipses above, consists of)

**Comment by ffoodd** [comment] 2021-03-05 06:31
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by joel6653** [comment] 2021-03-05 13:22
Bootstrap 5 beta 2
browser and OS already supplied
codepen: https://codepen.io/joel6653/pen/abBjXJJ

please note that the bottom border of the table also interferes with the rounded corners on the "good" (light) version of the table

**Comment by joel6653** [comment] 2021-03-05 13:28
In BS4, table cells had a border at the top by default. In BS5, this border has been moved to the bottom of each cell. The THEAD row has a thick border under it, which, if removed, causes the THEAD row to be indistinguishable from the first row of the table (whereas, in BS4, the first row had a border at its top that served nicely). The BS5 border-at-the-bottom also causes the last row of the table to have a border at the bottom that interferes with rounded corners (when they work at all).

**Comment by alecpl** [comment] 2021-03-05 13:54
The issue is caused by the fact that Bootstrap sets background on th/td elements not the table itself. You can workaround this by adding `overflow:hidden` on the table.

To workaround the other issue add .rounded-0 to the last tr element in the table.

I'm not sure Bootstrap will see these cases as something that should be supported.

**Comment by joel6653** [comment] 2021-03-05 15:57
@alecpl this change in v5 (moving cell border from top to bottom) broke what worked fine in v4. Adding something to the last row of a table is possible but quite impractical when the rows are generated dynamically from a data source.

**Comment by joel6653** [comment] 2021-03-05 16:05
I can open another issue for this, but has anyone noticed what happens when you try to PRINT a dark table? In light (regular) mode, the lines between rows come out as very light separators (which is good). In dark mode, the printed lines are very thick and dark, sort of overwhelming the table's actual content. I know that this can all be overridden which additional css, but why not make extra code unnecessary?

**Comment by alecpl** [comment] 2021-03-06 06:55
@joel6653 create another ticket for the printing issue.

**Comment by mdo** [comment] 2021-03-10 03:46
Sounds like this was resolved in previous comments—you'll need to customize things further with tables as they have different border styles that make it slightly more complex. Printing-wise, we don't provide default printing styles in v5 anymore, so that's something you'll need to address.

**Closed by mdo** 2021-03-10 03:46 UTC
Labels: awaiting-reply
