### ISSUE TITLE
Numerous sass deprecation warnings

### ISSUE THREAD

**Issue by Larsschoen** [twbs/bootstrap#40761] opened 2024-08-22 13:01 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I'm using bootstrap in my react project. While bundling the app via [ParcelJS](https://parceljs.org/) I'm getting some sass deprection warnings. One might look like this:

```
DEPRECATION WARNING: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

    ┌──> node_modules/bootstrap/scss/_reboot.scss
503 │     font-weight: $legend-font-weight;
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
    ╵
    ┌──> node_modules/bootstrap/scss/vendor/_rfs.scss
136 │ ┌     @media (#{$rfs-mq-property-width}: #{$rfs-mq-value}) {
137 │ │       @content;
138 │ │     }
    │ └─── nested rule
    ╵
    node_modules/bootstrap/scss/_reboot.scss 503:3   @import
    node_modules/bootstrap/scss/bootstrap.scss 16:9  @import
```

Bootstrap: 5.3.3
NodeJS: 22.6.0
npm: 10.8.2

### Reduced test cases

-

### What operating system(s) are you seeing the problem on?

macOS, Linux

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.3

**Comment by louismaximepiton** [comment] 2024-08-22 13:32
Duplicate of #40621. A patch has already been merged and will be in the next release, in the mean time, you can have some more information in the linked issue.

**Closed by louismaximepiton** 2024-08-22 13:32 UTC
Labels: duplicate
