### ISSUE TITLE
Dropdown examples in docs are broken

### ISSUE THREAD

**Issue by altermine** [twbs/bootstrap#20410] opened 2016-07-29 17:47 UTC
http://v4-alpha.getbootstrap.com/components/dropdowns/

Clicking any dropdown button on this documentation page gives you only a jQuery error:
<code>
Uncaught Error: Syntax error, unrecognized expression: #
</code>

**Comment by judetucker** [comment] 2016-07-29 19:00
This appears to be a docs-only issue. I can confirm that the code is working as intended both locally and here: http://codepen.io/anon/pen/JKBWGY

You should probably change the title of this issue to mention that it is only related to the hosted docs.

**Comment by mdo** [comment] 2016-08-02 04:03
@cvrebert Any idea what changed here to cause this? I feel like it must've been recent, otherwise we would've received some notices from folks on the bleeding edge.

**Comment by cvrebert** [comment] 2016-08-02 04:07
Probably the update to using jQuery 3 in the docs.

**Comment by mdo** [comment] 2016-08-02 04:09
@cvrebert Sorry, should've been more direct :grin:. I figured that was the case, but was curious if you had something more specific from merging those PRs. Is this something you could look into or do we need someone else?

**Comment by judetucker** [comment] 2016-08-02 05:10
Hi guys, I actually just spun up the docs using jQuery 2.2.4 and this issue still remains. I think it is the result of combining Dropdowns and Button Dropdowns into the same page in the docs.

Suspect commit https://github.com/twbs/bootstrap/commit/7cc802ea781997cdce09c5ab74b878c84301ebab#diff-20fdbd52708955c366427885955c94c1R39

Hope this helps!

**Comment by vanduynslagerp** [comment] 2016-08-02 05:14
Hi, the problem is due to the static dropdown having `data-target="#"`.
Just remove it and it should work. I can push a PR tomorrow if you'd like.

**Comment by vanduynslagerp** [comment] 2016-08-02 05:41
It was faster than expect :-) Here is the PR #20434.
If I may, I would also suggest to look at #19864,  #19953 and #19978 that fix other dropdown issues.

**Comment by mdo** [comment] 2016-08-04 01:32
Resolved with #20434.

**Closed by mdo** 2016-08-04 01:32 UTC
Labels: docs, v4
