### ISSUE TITLE
Needless white space on right side of docs pages

### ISSUE THREAD

**Issue by ZDroid** [twbs/bootstrap#16552] opened 2015-05-28 11:28 UTC
There is some needless white space on the right side of page. It is related to extra pixels of ad border (see images).

Notes:
- I tested it in Chrome 43.0.2357.81 on Ubuntu 14.04.
- It appears on very small mobile screen sizes, under 476 px (I am not sure what's the exact size).

![White space issue 1](https://cloud.githubusercontent.com/assets/2725611/7859197/f3eeecb0-053e-11e5-99c2-c74114c5fa31.png)

Sometimes it's like this, with more white space:

![White space issue 2](https://cloud.githubusercontent.com/assets/2725611/7858943/c721ed42-053c-11e5-95f9-7bcf8b2890ba.png)

**Comment by kkirsche** [comment] 2015-05-28 11:37
What browser and operating system are you using?

**Comment by ZDroid** [comment] 2015-05-28 11:41
I've updated issue text to provide more details. :smile:

**Comment by patrickhlauke** [comment] 2015-05-28 11:43
Can't reproduce in Chrome 43.0.2357.81 / Win8.1

**Comment by ZDroid** [comment] 2015-05-28 11:44
Have you tried it with all Bootstrap pages? Also, don't forget it happens on the smallest screen sizes, under 476px.

**Comment by patrickhlauke** [comment] 2015-05-28 11:45
Yes.
![capture](https://cloud.githubusercontent.com/assets/895831/7859294/6be03ae2-0537-11e5-88a5-66b7ed323e59.PNG)

**Comment by ZDroid** [comment] 2015-05-28 11:46
Then what's that scroll on the right side of the page? :p I see you have horizontal scroll which isn't supposed to be there.

**Comment by patrickhlauke** [comment] 2015-05-28 11:47
Ah, good point, admit I missed that. Reopened

**Comment by patrickhlauke** [comment] 2015-05-28 12:01
The issue seems in part due to the `<div id="carbonads-container">`, but the biggest culprit is an `<svg>` that somehow seems to get injected at the end of the document. @mdo, any ideas?

**Comment by cvrebert** [comment] 2015-05-28 16:45
IIRC, the SVG is from holder.js

**Comment by patrickhlauke** [comment] 2015-05-28 20:07
wondering if holder.js needs updating? what that `<svg>` is really missing is a `display:none` in its style. looking at http://imsky.github.io/holder/ the injected `<svg>` there *does* have `display:none`. that would then only leave the Carbon ads to deal with...

**Comment by cvrebert** [comment] 2015-05-28 20:14
> wondering if holder.js needs updating?

We updated it fairly recently in `master` (see 69308dc883a18f9c2465d8cea8b930e4e1ffda06). Could someone check whether this still repros with the current `master`?

**Comment by kkirsche** [comment] 2015-05-28 20:28
@cvrebert holder.js is currently at 2.7.0 externally (per https://imsky.github.io/holder/). The linked commit is Version 2.6.0+51ebp

**Comment by patrickhlauke** [comment] 2015-05-28 20:28
Sorry, after posting the above I actually went and checked our latest master locally. The problem is indeed resolved (for holder.js) there. That just leaves the Carbon ads

![capture](https://cloud.githubusercontent.com/assets/895831/7870328/8251ec78-0580-11e5-926e-6b85b737b98a.png)

**Comment by TimothyGu** [comment] 2015-05-30 22:00
Fixed in #16565.

![image](https://cloud.githubusercontent.com/assets/1538624/7899558/7ee17c7c-06dc-11e5-9c0c-f9c22c73531a.png)

**Closed** 2015-05-30 22:08 UTC
Labels: docs

**Comment by ZDroid** [comment] 2015-05-31 06:52
Nice :)

2015-05-31 0:10 GMT+02:00 Mark Otto <notifications@github.com>:

> Closed #16552 <https://github.com/twbs/bootstrap/issues/16552> via #16565
> <https://github.com/twbs/bootstrap/pull/16565>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twbs/bootstrap/issues/16552#event-317982636>.
>



-- 
Zlatan Vasović - *ZDroid*
