### ISSUE TITLE
Why don't we have a jQuery free version?

### ISSUE THREAD

**Issue by thednp** [twbs/bootstrap#15897] opened 2015-02-24 12:46 UTC
We have both SASS and LESS sources but we don't have a jQuery free javascript. Not that it doesn't work properly, just that other scripts would have superior performance.

Thanks for any reply.

**Comment by kkirsche** [comment] 2015-02-24 15:15
I can say with certainty but I believe it has to do with both convenience and effects for items like the carousel or collapse. An admin would have to say for sure though.

When you say superior performance, I believe the Bootstrap team would be open to pull requests making code changes which improve performance as long as the necessary test code is included and passing.

**Comment by thednp** [comment] 2015-02-24 15:23
The only things jQuery is really needed:
* the responsive menu toggle view
* tabs toggle
* carousel toggle
* accordion toggle

But all this can be achieved with class toggling and CSS transitions. Do we have to support <IE9 animations?

**Comment by kkirsche** [comment] 2015-02-24 15:25
Currently, V3 of bootstrap supports IE9 and I can almost guarantee it will continue to do so. It even supports IE8 with the inclusion of Respond.js.

**Comment by thednp** [comment] 2015-02-24 15:32
But we don't need to animate anything in <IE10, really. For performance we really don't need convenience or supporting animation for older browsers.

In my experience, and I believe many more others, the user feels more satisfied with a smooth experience, all done with high performance render. 

Still, if you need convenience, build your own pseudo jQuery like this http://youmightnotneedjquery.com/

jQuery is too slow. I think we should drop it very soon. I am all in, currently cleaning my code.

**Comment by MichaelRushton** [comment] 2015-02-24 18:58
I agree. The less dependencies the better. Any extra code required to replace it is worth not having to include an entire, and possibly unwanted, third-party library.

**Comment by cvrebert** [comment] 2015-02-24 19:56
Approximate duplicate of #15068.

**Closed by cvrebert** 2015-02-24 19:56 UTC
Labels: js

**Comment by thednp** [comment] 2015-03-04 18:24
https://github.com/thednp/Bootrstrap-Vanilla-JS
