### ISSUE TITLE
invalidity-icon overlaps with scrollbar in textarea

### ISSUE THREAD

**Issue by dimitrijuchtmans** [twbs/bootstrap#29874] opened 2019-12-18 08:06 UTC
On this part of the demosite: https://getbootstrap.com/docs/4.4/components/forms/
- Add enough text in the textarea for the scrollbar to appear
- manually add is-invalid class to textarea
result: 
![image](https://user-images.githubusercontent.com/6793282/71067838-956c1480-2175-11ea-9ae8-7e0d7bcd8f41.png)

Is this worked as designed or just an UI-bug?

**Comment by mdo** [comment] 2019-12-18 18:38
Duplicate of #27142.

**Closed by mdo** 2019-12-18 18:38 UTC
