### ISSUE TITLE
Dropdown in navbar fixed-top is not scrollable

### ISSUE THREAD

**Issue by zwantE** [twbs/bootstrap#28575] opened 2019-03-29 18:16 UTC
i use a bootstrap 4 navbar-fixed-top with a dropdown inside and when the drobdown is higher as the page, the dropdown-content is not scrollable.

I create a demo with original bootstrap files without any changes, and there is the same problem :/

take a look in this demo...

how can i solve the problem? its really sad

https://jsbin.com/sitozuzayu/edit?html,output

_w10 x64 chrome 73.0.3683.86_

**Comment by herbalite** [comment] 2019-03-30 08:43
You could add a css rule to the document:
```
div[aria-labelledby="navbarDropdown"] {
  overflow-y: auto;
  height: 1000%;
}

**Comment by zwantE** [comment] 2019-04-01 07:53
dont work with collapsed navbar :/

**Comment by herbalite** [comment] 2019-04-01 08:52
hmm, when I worked this out with your JS-Bin I forgot to mention something else. Sorry about that. If you still have issues, I've added those styles directly to the div element with the id="navbarDropwdown" with style="overflow-y: ..." 

```
div[aria-labelledby="navbarDropdown"] {
  overflow-y: auto;
  height: 1000%;
  position: absolute;
}

**Comment by ysds** [comment] 2019-05-17 15:53
Duplicate of #23374

**Closed by ysds** 2019-05-17 15:53 UTC
