### ISSUE TITLE
Problem with creating automated utility bg and text class with custom colors in v5.1.0

### ISSUE THREAD

**Issue by isaumya** [twbs/bootstrap#34734] opened 2021-08-11 18:34 UTC
Hi,
I'm facing a major issue in Bootstrap v5.1.0 regarding autogenerating bg and text utility classes.
So, in Bootstrap v5.0.1 (which I majorly use on al of my projects) I have the following structure:

in `common.scss` which is what gets added to the frontend, I add all the bootstrap file calls, e.g.:

```scss
### common.scss
@import "./libs/bootstrap/functions";

@import "./helpers/bootstrap-variables-with-overwrites";
@import "./libs/bootstrap/mixins";
@import "./libs/bootstrap/utilities";
## and so on...
```

Now inside `bootstrap-variables-with-overwrites.scss` I can create a bunch of custom colours and merge that with theme colours. For example:

```scss
$color1: red;
$color2: blue;

@import "../libs/bootstrap/variables";

$extra-theme-colors: (
	"gray-dark":   $gray-800,
	"color1":   $color1,
	"color2": $color2
);

$colors: map-remove( $colors, "gray-dark" );

$theme-colors: map-merge($theme-colors, $extra-theme-colors );
```

With that above implementation, in v5.0.1 these new custom colors in `$extra-theme-colors` gets added to `$theme-colors` and so naturally, when I compile it creates all the custom classes like `.bg-color1`, `.bg-color2` and so on among other things along with having the default color classes added by Bootstrap.

But as soon as updated to Bootstrap v5.1.0 this system stopped working and I got no more custom classes for the custom colours. I have tried almost everything and none worked.

Is this a bug? Can someone let me know what's going on and how to make sure that the same can be implemented in v5.1.0? This is super important to all of my projects.

**Comment by nsmeele** [comment] 2021-08-11 21:30
;TLDR
_Also not working after manually merging the variables._

---

Also experiencing this problem in 5.1. This is my code

````scss
@import 'lib/variables';

// Bootstrap include base
@import "../../node_modules/bootstrap/scss/functions";
@import "../../node_modules/bootstrap/scss/variables";

$theme-colors: map-merge($theme-colors, (
    'primary-dark' : shade-color($blue, 20%),
    'primary-light' : tint-color($blue, 20%),
    'purple' : $indigo,
    'purple-dark' : shade-color($indigo, 20%),
    'purple-light' : tint-color($indigo, 10%),
));

@import "../../node_modules/bootstrap/scss/mixins";
@import "../../node_modules/bootstrap/scss/utilities";

// Layout & components
@import "../../node_modules/bootstrap/scss/root";
@import "../../node_modules/bootstrap/scss/reboot";

// ..the rest

````
When I run a debug on $utilities-colors the result is this:
`
DEBUG: ("primary": 13, 110, 253, "secondary": 108, 117, 125, "success": 25, 135, 84, "info": 13, 202, 240, "warning": 255, 193, 7, "danger": 220, 53, 69, "light": 248, 249, 250, "dark": 33, 37, 41, "black": 0, 0, 0, "white": 255, 255, 255, "body": 33, 37, 41)
`

Ergo the map contains the original variables. SInce I want the original + the new colors I thought lets merge the two of them. But when I specifically merge the variables like this: 

````scss
$utilities-colors: map-merge($theme-colors, $utilities-colors)

// copied from the bootstrap variables file
$utilities-bg-colors: map-loop($utilities-colors, rgba-css-var, "$key", "bg");
````
and run a debug on $utilities-colors now, it's actually added to the map.

`DEBUG: ("primary": 13, 110, 253, "secondary": 108, 117, 125, "success": 25, 135, 84, "info": 13, 202, 240, "warning": 255, 193, 7, "danger": 220, 53, 69, "light": 248, 249, 250, "dark": 33, 37, 41, "primary-dark": #0a58ca, "primary-light": #3d8bfd, "purple": #6610f2, "purple-dark": #520dc2, "purple-light": #7528f3, "black": 0, 0, 0, "white": 255, 255, 255, "body": 33, 37, 41)` 

This CSS is loaded in the browser on the .bg-purple-dark selector

````css
.bg-purple-dark {
    --bs-bg-opacity: 1;
    background-color: rgba(var(--bs-purple-dark-rgb), var(--bs-bg-opacity)) !important;
}
````
Firefox is telling another problem: `--bs-purple-dark-rgb` is not set.

**Comment by wpchannel** [comment] 2021-08-12 06:15
Hi there, maybe this issue is similar to #34680.

On my side, here is what I'm doing to generate text- and bg- with custom colours.

```
@import "../../node_modules/bootstrap/scss/functions";

$primary: #4e21e7;
$secondary: #e8e7ff;
$light: #f8f9fb;
$white: #fff;
$dark: #0c082f;
$dark-light: rgba($white, .1);
$green: #0da49a;
$green-light: #e6f6f5;
$blue: #334eff;
$blue-light: #d9deff;
$blue-dark: #13334b;
$red: #ee485f;
$danger: #f5c6cb;
$red-light: #ffebf4;
$red-dark: rgba($dark, .1);
$gray-300: rgba(12, 8, 47, .8);

@import "../../node_modules/bootstrap/scss/variables";
@import "../../node_modules/bootstrap/scss/mixins";

$theme-colors: map-remove($theme-colors, 'info', 'warning');
$custom-colors: (
	'green': $green,
	'green-light': $green-light,
	'green-dark': $dark,
	'blue': $blue,
	'blue-light': $blue-light,
	'blue-dark': $blue-dark,
	'red': $red,
	'red-light': $red-light,
	'red-dark': $red-dark,
	'dark-light': $dark-light
);
$theme-colors: map-merge($theme-colors, $custom-colors);

@each $custom-color, $link-color in $theme-colors {
	.link-custom-#{$custom-color} {
		a {
			color: $link-color;

			&:hover, &:focus {
				color: rgba($link-color, .7);
			}
		}
	}
}

@import "../../node_modules/bootstrap/scss/root";
@import "../../node_modules/bootstrap/scss/reboot";
@import "../../node_modules/bootstrap/scss/type";
@import "../../node_modules/bootstrap/scss/images";
@import "../../node_modules/bootstrap/scss/containers";
@import "../../node_modules/bootstrap/scss/grid";
@import "../../node_modules/bootstrap/scss/buttons";
@import "../../node_modules/bootstrap/scss/button-group";
@import "../../node_modules/bootstrap/scss/nav";
@import "../../node_modules/bootstrap/scss/navbar";
@import "../../node_modules/bootstrap/scss/breadcrumb";
@import "../../node_modules/bootstrap/scss/dropdown";
@import "../../node_modules/bootstrap/scss/transitions";
@import "../../node_modules/bootstrap/scss/forms";
@import "../../node_modules/bootstrap/scss/list-group";
@import "../../node_modules/bootstrap/scss/alert";
@import "../../node_modules/bootstrap/scss/badge";
@import "../../node_modules/bootstrap/scss/pagination";
@import "../../node_modules/bootstrap/scss/accordion";
@import "../../node_modules/bootstrap/scss/card";
@import "../../node_modules/bootstrap/scss/tables";
@import "../../node_modules/bootstrap/scss/modal";
@import "../../node_modules/bootstrap/scss/close";
@import "../../node_modules/bootstrap/scss/helpers";
@import "../../node_modules/bootstrap/scss/utilities";

$all-colors: map-merge-multiple($theme-colors);
$utilities: map-merge(
	$utilities,
	(
		"color": map-merge(
			map-get($utilities, "color"),
			(
				values: map-merge(
					map-get(map-get($utilities, "color"), "values"),
					(
						$all-colors
					),
				),
			),
		),
		"background-color": map-merge(
			map-get($utilities, "background-color"),
			(
				values: map-merge(
					map-get(map-get($utilities, "background-color"), "values"),
					(
						$all-colors
					),
				),
			),
		)
	)
);

@import "../../node_modules/bootstrap/scss/utilities/api";
```

**Comment by isaumya** [comment] 2021-08-12 07:39
I think the method mentioned by @nsmeele works great.
That after:

```scss
$theme-colors: map-merge($theme-colors, $extra-theme-colors );
```

we also need to add these 4 lines:

```scss
$theme-colors-rgb: map-loop($theme-colors, to-rgb, "$value");
$utilities-colors: map-merge($theme-colors, $utilities-colors);
$utilities-text-colors: map-loop($utilities-colors, rgba-css-var, "$key", "text");
$utilities-bg-colors: map-loop($utilities-colors, rgba-css-var, "$key", "bg");
```

and all the color classes gets generated properly.

I've also looked at [this documentation](https://getbootstrap.com/docs/5.1/customize/color/#generating-utilities) and it works well as well, but the problem with this is that this should only be used when you have some color for which you only need the background and text classes but not the buttons and other things. Also, this approach will not generate the `rgb` values. So, all the classes will have `--bs-bg-opacity: 1` which will remain unused.

**Comment by artemnih** [comment] 2021-09-09 17:16
This should have been a `MAJOR` version shift, not just `MINOR`

**Comment by mdo** [comment] 2021-09-09 17:22
After investigating a bit more, I think the best path forward might to split out some of our reassigned Sass maps into a separate `_maps.scss` file, and import that after the `_variables.scss` file. This would allow folks to insert new additions to the `$theme-colors` map that would be reflected in the subsequent maps.

For example:

```scss
// Configuration
@import "functions";
@import "variables";

$starorange: #df711b !default;

$custom-theme-colors: (
  "starorange": $starorange
) !default;

$theme-colors: map-merge($theme-colors, $custom-theme-colors); // stylelint-disable-line scss/dollar-variable-default

@import "maps";
@import "mixins";
@import "utilities";

// Layout & components
// ...
```

Inside `_maps.scss` would be the Sass maps for `$theme-colors-rgb`, `$utilities-colors`, `$utilities-text`, and `$utilities-bg`. I tried this locally and it works for me—both button variants and utilities are generated for the custom color.

**Comment by mdo** [comment] 2021-09-09 18:06
Closing as duplicate of #34756 where more convo has been happening.

@isaumya Yes, my plan would be to include in v5.2.0 and potentially fast track that release instead of v5.1.2 being the next update.

**Closed by mdo** 2021-09-09 18:06 UTC
