### ISSUE TITLE
data-target with multiple target doesn't work

### ISSUE THREAD

**Issue by stassinari** [twbs/bootstrap#19813] opened 2016-04-27 13:53 UTC
When trying to use multiple targets with the data-target attribute, it seems like only the first one is triggered and the remaining ones are discarded.
This happens with either a class targeting multiple elements, or with multiple IDs as attribute value.

I've created two pens on CodePen to reproduce the behaviour.
The HTML is identical, but the configuration points to different Bootstrap versions:

v4 with bug: http://codepen.io/stassinari-andiamo/pen/jqvgPW
v3 working: http://codepen.io/stassinari-andiamo/pen/dMqxYj

There's a (closed) issue raised for version 3.2.0 (#18342), where another user finds this behaviour in v4. There's a snippet of code in there, pointing to the actual JS code responsible for the handling.

I hope this feature will be kept (unlike @cvrebert), because being able to target multiple elements without the use of JavaScript is a nice feature, IMO.

**Comment by RyanZim** [comment] 2016-04-27 15:38
> being able to target multiple elements without the use of JavaScript is a nice feature, IMO.

I agree, however, it may be wise to only accept IDs instead of arbitrary selectors (to avoid unwanted conflicts). How about this:
```
<a data-toggle="collapse" data-target="#c1 #c2">Click me</a>

<p id="c1" class="collapse collapsible">First paragraph</p>
<p id="c2" class="collapse collapsible">Second paragraph</p>
```

**Comment by stassinari** [comment] 2016-05-03 15:24
I understand that accepting only IDs is safer, but there are cases (like in the page I'm working on now) where filling a page with dozens of IDs doesn't really make sense.
What I did is create a custom data attribute mimicking the data-target I'd like to use (the one with a class), and then reimplement the collapsing logic in my own JS.

**Comment by stassinari** [comment] 2016-05-03 15:25
I'd like to point out that, regardless of the class dispute, this is still an issue, because multiple IDs are not currently working with the alpha version.
I've updated the Pens to reflect this.

**Comment by jitendra8799** [comment] 2016-09-20 12:15
<a data-toggle="collapse" data-target="#c1,#c2">Click me</a>

**Comment by mdo** [comment] 2016-10-28 04:51
I feel like this is an edge case we don't want to explicitly support. Closing out for now, but happy to revisit if enough folks would like to see this changed. Thanks!

**Closed by mdo** 2016-10-28 04:51 UTC
Labels: js, v4

**Comment by kutenai** [comment] 2017-01-06 00:46
Ack! I just found this thread. Am I to understand this won't be supported in v4? This is a desirable feature if I can put my 2 cents in..

**Comment by alexcasalboni** [comment] 2017-01-10 16:10
+1

**Comment by plusz** [comment] 2017-01-18 18:28
it losk that there are also issues when using class selector instead of id
data-target='.someselector'

It is expanding and collapsing elements, but aria-expanded and .collapse() doesn't work
it may be helpful functionality to show/hide multiple rows in a table.

**Comment by vanduynslagerp** [comment] 2017-01-18 19:26
X-Ref #21692

**Comment by rscs** [comment] 2017-02-23 22:06
Spent over 2 hours trying to figure out why using a class selector targeting multiple collapsed table rows was only expanding the first row and not all of them.

I will try the ID approach, but it's going to make my code a lot messier and bigger. Why was this functionality removed in v4 when it works fine in v3?

**Comment by PhantomWatson** [comment] 2017-03-30 00:02
[The docs](collapse) currently imply that this issue is fixed (or never existed) and that the target _could_ be a selector that applies to multiple elements:

> **if** your control element is targeting **a single collapsible element** – i.e. the data-target attribute is pointing to an id selector...

**Comment by robline** [comment] 2017-05-11 13:02
I don't consider this an edge case.  I use it for content and context-based help text, among other things. It's also a regression. +1

**Comment by acamilicko** [comment] 2017-05-26 20:40
I use it in responsive menus - sometimes you must put several menus in single collapse for mobiles. +1

**Comment by antibrick** [comment] 2018-05-07 14:41
That's quite an annoying issue… Please fix it! (Or at least update the docs, I wasted the last hour because of this…)

**Comment by mikemichalak** [comment] 2018-05-07 14:48
Are there any other docs that outline this?

**Comment by andrewlamyw** [comment] 2018-07-30 18:28
What is the solution to this?

**Comment by urirahimi** [comment] 2018-09-22 02:02
This is so annoying, lost three hours trying to figure this out. How can I target multiple div in a button's  data-target?
