### ISSUE TITLE
popovers: "dismiss on next click" should still toggle

### ISSUE THREAD

**Issue by inwardmovement** [twbs/bootstrap#31275] opened 2020-07-10 19:07 UTC
To complement https://github.com/twbs/bootstrap/issues/31088, I think [popovers dismissed on next click](https://getbootstrap.com/docs/4.5/components/popovers/#dismiss-on-next-click) should still toggle, which is not the case now.

![popover](https://user-images.githubusercontent.com/9438102/87189662-53f9ad00-c2f1-11ea-8cd3-fab3b66e8742.gif)

**Comment by techboyg5** [comment] 2020-08-03 23:41
Use `data-trigger="focus click"`. That will do it.

**Comment by inwardmovement** [comment] 2020-08-06 08:10
> Use `data-trigger="focus click"`. That will do it.

It doesn't work.

**Comment by sijusamson** [comment] 2021-01-19 16:33
@mdo Is this a bug? As per the docs mentioned **Use the focus trigger to dismiss popovers on the user’s next click of a different element than the toggle element**, and currently it is occurring like that only. 
So currently if the focus goes from the button, popover gets dismissed.

**Comment by rohit2sharma95** [comment] 2021-01-19 17:52
Since the trigger for the popover is the `'focus'`, the popover can not be hidden until the focus is removed from the button. And clicking again on the button can not remove the focus from the button.

So if you **click on a different element than the toggle element**, the focus will be removed from the button and the popover will be hidden. It is not an issue IMO :thinking: 

/CC @XhmikosR

**Comment by mdo** [comment] 2021-01-20 01:17
Closing as a won't fix / not a bug with those last two comments. Thanks folks!

**Closed by mdo** 2021-01-20 01:17 UTC
Labels: help wanted, js, v5

**Comment by inwardmovement** [comment] 2021-01-20 07:51
I understand that when the trigger is "focus", then it should not toggle on click.

But when the trigger is "click" or "focus click", in my opinion for a coherent UX the toggle should toggle, no matter where is the focus, which is not the case now (with trigger click).

**Comment by rohit2sharma95** [comment] 2021-01-20 17:36
Using the `'click'` trigger with `'focus'` trigger is not required (also should not be required). Clicking the button will set the focus and the popover will be shown.

And if you use only `'click'` trigger, popover is toggled on clicking again.

**Comment by inwardmovement** [comment] 2021-01-22 10:15
Is there something I'm missing?
How can I have the popover both a) toggle on click (always) and b) dismiss on next click?
The user should be able to toggle on click (always) + dismiss on next click outside the element.

![bs](https://user-images.githubusercontent.com/9438102/105477847-b53c0900-5ca2-11eb-9e9e-6b58e9640e3f.gif)

**Comment by oselz** [comment] 2024-10-22 22:16
For those looking for a solution to using both 'click' AND 'focus' together which does not work with bootstrap's JS, you can manually watch the `focusout` event to achieve the intuitive result of the full set of `click to open`, `click to close` AND `click away to close`:

```js
const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]')
        popoverTriggerList.forEach(
            popoverTriggerEl => {
                const popover = new bootstrap.Popover(popoverTriggerEl, {
                    trigger: "click",
                })
                popoverTriggerEl.addEventListener('focusout', (e) => {
                    popover.hide()
                })
            }
        )
```
