### ISSUE TITLE
Request: Add media query breakpoints as variables to variables.less

### ISSUE THREAD

**Issue by fatcrobat** [twbs/bootstrap#15850] opened 2015-02-20 07:43 UTC
Is it possible to add the following to variables.less, it makes media query handling much more compfortable. 

```
@xs: ~"(max-width: @{screen-xs-max})";
@sm: ~"(min-width: @{screen-sm-min}) and (max-width: @{screen-sm-max})";
@md: ~"(min-width: @{screen-md-min}) and (max-width: @{screen-md-max})";
@lg: ~"(min-width: @{screen-lg-min})";

@sm-min: ~"(min-width: @{screen-sm-min})";
@md-min: ~"(min-width: @{screen-md-min})";
@lg-min: ~"(min-width: @{screen-lg-min})";

@xs-max: @xs;
@sm-max: ~"(max-width: @{screen-sm-max})";
@md-max: ~"(max-width: @{screen-md-max})";
```

Usage example:
```
@media @xs{
.container{
  padding-left: 0;
  padding-right: 0;
}
}
```

Thanks for having bootstrap. :+1:

**Comment by cvrebert** [comment] 2015-02-20 08:49
Approximate duplicate of #13014, a variation of which is already part of Bootstrap v4's code.

**Closed by cvrebert** 2015-02-20 08:49 UTC
Labels: css, feature
