### ISSUE TITLE
Display headings in FireFox on macOS are thinner

### ISSUE THREAD

**Issue by mdevan** [twbs/bootstrap#24784] opened 2017-11-15 15:22 UTC
Display headings (https://getbootstrap.com/docs/4.0/content/typography/#display-headings) in FireFox appear thinner than Chrome and Safari on macOS 10.12.6. Regular headings are OK. Bootstrap v4.0.0-beta.2 

![display-headings-across-browsers-mac](https://user-images.githubusercontent.com/15809/32843728-7a0f5874-ca46-11e7-9b44-45b12cd1ad12.png)

**Comment by XhmikosR** [comment] 2017-11-16 12:50
Not sure what we can do; it's something that's inevitable since we use the OS stack, thus not every font has every font weight we use.

**Comment by MargateSteve** [comment] 2017-11-23 14:57
This is not a macOS issue or a display class issue. All <h> tags look a lot thinner in FF and get even worse when using the applying a custom font size. The attached is on Windows with FF on the left and Chrome on the right using <h1 class="title">Home Page</h1> where .title has a font-size of 3.5rem.
![ff_v_chrome](https://user-images.githubusercontent.com/13920439/33178581-935f7886-d05e-11e7-835c-04eb91ece8b2.PNG)

**Comment by patrickhlauke** [comment] 2017-11-23 15:28
it seems that the problem is actually that Chrome is a bit overzealous with its font weight. The currently used `font-weight:500` renders far bolder/fatter in Chrome/Blink than in FF, Edge, IE...

![edge-ie](https://user-images.githubusercontent.com/895831/33179875-d016ebe8-d062-11e7-96f9-391a1e423eab.PNG)
![cx-vs-ff](https://user-images.githubusercontent.com/895831/33179876-d031df52-d062-11e7-9ebc-165e276dc06d.jpg)

Using just Firefox, it seems Chrome's interpretation of `font-weight:500` is closer to what other browsers would use in the case of `font-weight:600`.

**Comment by patrickhlauke** [comment] 2017-11-23 15:30
Not sure there's a clean solution here, as changes one way to try and make one browser more consistent to another may well result in making things worse in other combinations...

**Comment by XhmikosR** [comment] 2017-11-25 00:56
I doubt we can do anything here.

/CC @mdo

**Comment by mdo** [comment] 2017-11-25 02:11
Closing as a won't/can't fix.

**Closed by mdo** 2017-11-25 02:11 UTC
Labels: css, v4
