### ISSUE TITLE
display heading classes don't scale based on font-size-base

### ISSUE THREAD

**Issue by davethegr8** [twbs/bootstrap#26746] opened 2018-06-22 17:38 UTC
I've noticed that while customizing bootstrap themes for my sites that the display classes don't scale their size based on the `$font-size-base` value, which can lead to some strange situations and the need for additional customization. Example:

![screen shot 2018-06-22 at 10 34 06 am](https://user-images.githubusercontent.com/55392/41790564-d46b13ae-7607-11e8-9718-3064210b7952.png)

The fix for this seems to be relatively straightforward but I am not sure if it's intentional or if there's other side effects. Or, if there's other parts that _should_ scale as well such as the navbar padding in the example above. I'd be happy to open a PR if you'd like.

**Comment by mdo** [comment] 2018-06-23 03:48
Duplicate of #22104.

**Closed by mdo** 2018-06-23 03:48 UTC

**Comment by davethegr8** [comment] 2018-06-23 03:55
Ah, good deal, I didn't see the dupes when I searched. Cheers!
