### ISSUE TITLE
Every version of the docs say "latest" in the dropdown

### ISSUE THREAD

**Issue by remram44** [twbs/bootstrap#37014] opened 2022-08-24 01:28 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When I view the documentation, whether from running the server locally or on getbootstrap.com, there is a version dropdown in the top right. It shows "Latest (5.2.x)" as well as other versions.

If I select another version and click on the dropdown again, it will present that version as latest.

The docs for 4.6 even shows "5.1.x" as an option, but "4.6.x" is described as "latest" (5.2.x is not in that dropdown)

![screenshot of 5.2](https://user-images.githubusercontent.com/426784/186297394-9dfbe886-41a6-4234-837d-986ff0746d41.png)
![screenshot of 5.1](https://user-images.githubusercontent.com/426784/186297398-db8ccbd5-e385-426c-8e52-c5acabf8f8ff.png)
![screenshot of 4.6](https://user-images.githubusercontent.com/426784/186297399-d3237dc1-7bfd-47b2-8d64-51d5f1dac671.png)

### Reduced test cases

Go to https://getbootstrap.com/docs/5.2/ and follow the links in the version dropdown.

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Firefox

### What version of Bootstrap are you using?

v5.2.0, v5.1.3, v4.6

**Comment by mdo** [comment] 2022-08-24 13:25
Duplicate of #36990.

**Closed by mdo** 2022-08-24 13:25 UTC
Labels: docs, v4, v5
