### ISSUE TITLE
Popovers (focus) are buggy!

### ISSUE THREAD

**Issue by gregblass** [twbs/bootstrap#19788] opened 2016-04-23 06:14 UTC
The documentation says to use focus on popovers in order to have them close when clicking outside. This fails on an iPhone.

If I change it to click, it will fire, but then not close when tapping outside.

All I want is for the popover to work with a click or tap - and close on another click or tap anywhere else on the page. This should be the standard/default functionality.

Has anyone had any success implementing them this way?

**Comment by cvrebert** [comment] 2016-04-23 06:42
Duplicate of #16028.
Blame WebKit (in part): https://bugs.webkit.org/show_bug.cgi?id=151933

**Closed by cvrebert** 2016-04-23 06:42 UTC
Labels: js, v3

**Comment by gregblass** [comment] 2016-04-23 06:48
Here's my attempt at accomplishing this:

```
  $('[data-toggle="popover"]').popover({html: true});
  function closePopovers() {
    $('.popover').popover('hide');
    $("html").unbind("click", closePopovers); 
  };
  $('[data-toggle="popover"]').on('shown.bs.popover', function () {
    setTimeout(function() {
      $("html").bind("click", closePopovers); 
    }, 0);
  })
```

But now apparently there is also a bug where hiding a popover requires you to click twice to open it again? Gotta be kidding me :( 👎

**Comment by gregblass** [comment] 2016-04-23 06:48
Cool! I'll tell my clients to blame webkit when my app doesn't work, that should work just great.

**Comment by gregblass** [comment] 2016-04-23 06:50
Sorry, that was incredibly snarky. Its a bit late. Well, thanks for the update/info.

**Comment by gregblass** [comment] 2016-04-23 06:57
To be honest...what I posted above isn't the end of the world. If the user taps once, then is at least able to tap outside to close it, they've already seen what they need to see. 

A double tap to open it again isn't the worst thing ever. At least a tap outside of the tooltip closes it. I bet that takes care of most cases.

Thanks for the prompt response and info @cvrebert - If you know of any workarounds to the double click/tap to open after a hide is called? I imagine there is another issue open for that?

**Comment by gregblass** [comment] 2016-04-23 07:08
This has some good insight, I'll check it out tomorrow: http://stackoverflow.com/questions/32581987/need-click-twice-after-hide-a-shown-bootstrap-popover

**Comment by cvrebert** [comment] 2016-04-23 07:15
Thank you for revising your comment to remove the snark. 😄  Bootstrap isn't corporate-backed and the Core Team is few in number, thus we don't always have the time or resources to fix every issue as quickly as we'd like to. Bootstrap is largely a labor of love. Thus we greatly appreciate the community's patience and understanding.

> If you know of any workarounds to the double click/tap to open after a hide is called? I imagine there is another issue open for that?

Yep, #16732.
