### ISSUE TITLE
Maybe a problem with searches

### ISSUE THREAD

**Issue by frederikhors** [twbs/bootstrap#29665] opened 2019-11-12 19:24 UTC
I think something is broken with search module in docs.

If I search for `text-dark` it doesn't list the `Colors` page:

![image](https://user-images.githubusercontent.com/41120635/68703116-3c173100-058a-11ea-9a3e-743acf32400a.png)

Is this a problem or am I wrong?

**Comment by mdo** [comment] 2019-11-14 00:20
I think the problem is we're not indexing the example code, which is where the text classes are all listed. Any ideas from the team if it's something else causing problems?

**Comment by Mrxx99** [comment] 2019-11-26 21:24
For me the search is not showing any results at all on Firefox, Chrome & Edge. It only shows "No results found for query ..."

**Comment by mdo** [comment] 2019-12-03 06:35
The search is working as intended. You might have some scripts blocked or perhaps what you're searching for doesn't exist. Closing out for now though. If you have more feedback on Algolia's search, please direct it to them :).

**Closed by mdo** 2019-12-03 06:35 UTC

**Comment by frederikhors** [comment] 2019-12-17 01:34
> You might have some scripts blocked or perhaps what you're searching for doesn't exist.

@mdo, I'm sorry. I do respect your job, but the problem persists.

Example: I search for "media-breakpoint"...

![image](https://user-images.githubusercontent.com/41120635/70957138-6e2e1e00-2075-11ea-8e2a-1261fcd0e78f.png)

No result is right.

The page I was looking for is: https://getbootstrap.com/docs/4.4/layout/overview/#responsive-breakpoints.

Am I wrong?
