### ISSUE TITLE
.col-{1-12} has priority over .col-md

### ISSUE THREAD

**Issue by lkaisers** [twbs/bootstrap#34618] opened 2021-07-29 14:55 UTC
I encountered an issue that I didn't have with Bootstrap v4. I always used the combination "col-12 col-md" to stretch the row on small devices and arrange them with others evenly divided on medium devices. This doesn't work anymore, because the rule "col-md" gets ignored and it seems that this is a bug for me.

![Bildschirmfoto 2021-07-29 um 16 40 45](https://user-images.githubusercontent.com/34108423/127514076-fd664ab3-f31f-4464-a7bc-592f3d169a2e.png)

Framework used on: https://meisterplan.com/
Operating System: macOS 11.4
Browser: Chrome v92

**Comment by mdo** [comment] 2021-07-29 15:55
Duplicate of #34611 and since fixed in `main`. Will be released next week.

**Closed by mdo** 2021-07-29 15:55 UTC
