### ISSUE TITLE
.table-responsive fails with .d-flex.flex-row ancestor

### ISSUE THREAD

**Issue by mrlife** [twbs/bootstrap#31216] opened 2020-06-30 22:46 UTC
I'm working with the Blazor template, that is built with Bootstrap 4.5, that comes out of the box with a new Blazor project. I noticed that `.table-responsive` doesn't work due to:
- `.d-flex.flex-row` in the outermost `div`, and
-  the `.table-responsive` has a `div` between it and the outmost `div`

Removing either of those functional pieces fixes the scroll issue, but I can't tell if this is a bug with how the `.table-responsive` is coded or something else.

Here is a reduced test case: https://www.codeply.com/p/sohA2Q2ojS

Environment

- macOS 10.15.5
- Safari 13.1.1, Chrome 83

**Comment by psimyn** [comment] 2020-07-03 12:57
I think the outer div should have `col` so its width is constrained, responsive-table can't do much about the it's parent element

```
<div class="d-flex flex-row">
  <div>Left item</div>
  <div class="col">
    <div class="table-responsive">
```

**Comment by mrlife** [comment] 2020-07-07 21:03
@psimyn I see what you're going for there, and it makes sense. I think my actual use case is more complicated than the reduced test case since adding the `col` or a fixed width to the parent doesn't seem to fix it.

Namely, as the browser width is reduced (and scrollable responsive table width is reduced), there is what looks like a right margin on the `body` that grows inversely proportional to the shrinking of the responsive table. It is not a margin or anything according to the browser tools, it's just a white column to the right of the body that causes the browser window to scroll.

I'll circle back when I have time to produce another reduced test case.

If you have any other thoughts in the meantime, please share!

**Comment by mrlife** [comment] 2020-07-21 16:09
Here is a more specific reduced test case, which just uses the `overflow-x: auto;` that `.table-responsive` uses.

Note that if you open this link and reduce your browser to the smallest width, the table scrolls but the browser window also still scrolls.

Is it an issue with `flex-direction: row;`?

https://www.codeply.com/v/njwJ5mDjAn

**Comment by ffoodd** [comment] 2020-08-18 14:22
@mrlife Your latest example has a body scroll because you set a `width` larger than the window. It allows to scroll the table (which needs a constraint to work). You can work around this by usin `max-width: 500px;` and `min-width: calc(100vw - 100px);` —100px being your sidebar width, approximatively.

Your first example sure is interesting but to make this pattern using Bootstrap, you should use `.row` and `.col-*` classes for your layout. This would handle flexbox model and widths appropriately and allow your table to work fine.

Since this is not a bug in Bootstrap (but more likely a misunderstanding about tables behaviour in a flex container), I'm closing this as won't fix.

**Closed by ffoodd** 2020-08-18 14:22 UTC

**Comment by mrlife** [comment] 2020-08-18 15:02
@ffoodd Thanks. Hopefully there will be an official fix for this soon.

Discussion at https://github.com/w3c/csswg-drafts/issues/865
