### ISSUE TITLE
Tooltip misplaced 

### ISSUE THREAD

**Issue by VigneshPalanisamy** [twbs/bootstrap#16825] opened 2015-07-15 01:17 UTC
Hi, 
    I had Table which contains more than 25 columns. And i had a button with tooltip at the end of the
table. In that case my tooltip was misplaced.

Thanks,

**Comment by VigneshPalanisamy** [comment] 2015-07-15 01:28
![tootip](https://cloud.githubusercontent.com/assets/2246927/8688895/dfe70350-2ad3-11e5-9113-634254f4f84b.png)

**Comment by kkirsche** [comment] 2015-07-15 01:34
Please post a JSBin demonstrating the problem as we can't diagnose the issue from a picture. Also please state operating system and browser version.

**Comment by VigneshPalanisamy** [comment] 2015-07-15 03:27
HI,
 This is the JSBin link https://output.jsbin.com/bisofenuba

Browser Firefox 39.0
OS Mac

**Comment by DanielApt** [comment] 2015-07-28 13:26
I think that the tooltip does not take the window's `scrollLeft` in to account. When you place the search button to the left of the screen, you don't see this issue happen.

Also noticing this bug on Chrome 44. Mac OSX.

**Comment by VigneshPalanisamy** [comment] 2015-07-29 01:33
Yes Daniel, you are correct. If the button in left corner it won't happen. But my requirement is to be in top right corner of table. And this bug is seen in all browser. 

Is there any workaround to solve this?

**Comment by DanielApt** [comment] 2015-07-29 11:10
@VigneshPalanisamy Yes, there actually is. 

Wrap your `table` in an element, and give it the following styling:
`width: 100%; overflow-y: scroll;`

This prevents the body from getting horizontal scroll-bar.

You'll also have to change your tooltip call to:
`  $('.search').tooltip({ 'placement': 'top', 'container':'body'});`

You can see the workaround in action [here](https://jsbin.com/magociciga/edit?html,css,output).

PS: I do think this should be fixed in the library itself, but at least you have a workaround now.

**Comment by VigneshPalanisamy** [comment] 2015-07-30 00:47
Thanks a lot @DanielApt .

**Comment by cvrebert** [comment] 2015-10-05 23:32
Duplicate of #15590.

**Closed by cvrebert** 2015-10-05 23:32 UTC
Labels: confirmed, js, v3
