### ISSUE TITLE
Bootstrap SCSS Bug With The SCSS abs() Function

### ISSUE THREAD

**Issue by cakadi190** [twbs/bootstrap#39072] opened 2023-08-19 11:35 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [x] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

Hi everyone! I just found this bug at the Bootstrap `v5.3.1` with the scss code. Here's the error.

``` sh
 cakadi190 on  C:/laragon/www/cakadi
# pnpm dev

> @ dev C:\laragon\www\cakadi
> vite


  VITE v4.4.9  ready in 1451 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help

  LARAVEL v10.19.0  plugin v0.8.0

  ➜  APP_URL: http://localhost
Deprecation Warning: Passing percentage units to the global abs() function is deprecated.
In the future, this will emit a CSS abs() function to be resolved by the browser.
To preserve current behavior: math.abs(100%)
To emit a CSS abs() now: abs(#{100%})
More info: https://sass-lang.com/d/abs-percent

   ╷
57 │   $dividend: abs($dividend);
   │              ^^^^^^^^^^^^^^
   ╵
    node_modules\.pnpm\bootstrap@5.3.1_@popperjs+core@2.11.8\node_modules\bootstrap\scss\vendor\_rfs.scss 57:14         divide()
    node_modules\.pnpm\bootstrap@5.3.1_@popperjs+core@2.11.8\node_modules\bootstrap\scss\mixins\_grid.scss 59:12        row-cols()
    node_modules\.pnpm\bootstrap@5.3.1_@popperjs+core@2.11.8\node_modules\bootstrap\scss\mixins\_grid.scss 85:13        @content
    node_modules\.pnpm\bootstrap@5.3.1_@popperjs+core@2.11.8\node_modules\bootstrap\scss\mixins\_breakpoints.scss 68:5  media-breakpoint-up()
    node_modules\.pnpm\bootstrap@5.3.1_@popperjs+core@2.11.8\node_modules\bootstrap\scss\mixins\_grid.scss 72:5         make-grid-columns()
    node_modules\.pnpm\bootstrap@5.3.1_@popperjs+core@2.11.8\node_modules\bootstrap\scss\_grid.scss 38:3                @import
    resources\scss\core\app.scss 20:9                                                                                   root stylesheet
```

The stack i use it :
1. Bootstrap `v5.3.1`
2. SASS `^1.66.1`
3. NodeJS `v18.8.0`
4. PNPM `v8.6.12`

I hope the core bootstrap dev team can solve this problem. And also I open this discussion for all, Thank you!

### Reduced test cases

The app.scss (Main File)

``` scss
@import "bootstrap/scss/mixins/banner";
@include bsBanner("");


// scss-docs-start import-stack
// Configuration
@import "bootstrap/scss/functions";
@import "bootstrap/scss/variables";
@import "bootstrap/scss/variables-dark";
@import "bootstrap/scss/maps";
@import "bootstrap/scss/mixins";
@import "bootstrap/scss/utilities";

// Layout & components
@import "bootstrap/scss/root";
@import "bootstrap/scss/reboot";
@import "bootstrap/scss/type";
@import "bootstrap/scss/images";
@import "bootstrap/scss/containers";
@import "bootstrap/scss/grid";
@import "bootstrap/scss/tables";
@import "bootstrap/scss/forms";
@import "bootstrap/scss/buttons";
@import "bootstrap/scss/transitions";
@import "bootstrap/scss/dropdown";
@import "bootstrap/scss/button-group";
@import "bootstrap/scss/nav";
@import "bootstrap/scss/navbar";
@import "bootstrap/scss/card";
@import "bootstrap/scss/accordion";
@import "bootstrap/scss/breadcrumb";
@import "bootstrap/scss/pagination";
@import "bootstrap/scss/badge";
@import "bootstrap/scss/alert";
@import "bootstrap/scss/progress";
@import "bootstrap/scss/list-group";
@import "bootstrap/scss/close";
@import "bootstrap/scss/toasts";
@import "bootstrap/scss/modal";
@import "bootstrap/scss/tooltip";
@import "bootstrap/scss/popover";
@import "bootstrap/scss/carousel";
@import "bootstrap/scss/spinners";
@import "bootstrap/scss/offcanvas";
@import "bootstrap/scss/placeholders";

// Helpers
@import "bootstrap/scss/helpers";

// Utilities
@import "bootstrap/scss/utilities/api";
// scss-docs-end import-stack
```

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome

### What version of Bootstrap are you using?

v5.3.1

**Comment by Stefaminator** [comment] 2023-08-19 13:15
Same here for Boostrap v4.6.2 (latest-4)

**Comment by blankse** [comment] 2023-08-20 07:18
Duplicate of https://github.com/twbs/bootstrap/issues/39028

**Comment by louismaximepiton** [comment] 2023-08-21 08:09
As said by blankse, duplicate so closing in favor of #39028.

**Closed by louismaximepiton** 2023-08-21 08:09 UTC
