### ISSUE TITLE
Independent from jQuery

### ISSUE THREAD

**Issue by kennywangjin** [twbs/bootstrap#19036] opened 2016-01-27 05:09 UTC
is it possible that bootstrap could be separated from jquery?
sometimes we do not need jquery but have to import it when we use bootstrap.
Please consider to implement bootstap plugins using pure javascript or typescript which could be translated to pure javascript.

**Comment by monokrome** [comment] 2016-01-27 06:20
:+1:

**Comment by cvrebert** [comment] 2016-01-27 07:01
Duplicate of #17378.

**Closed by cvrebert** 2016-01-27 07:01 UTC
Labels: js, meta, v4
