### ISSUE TITLE
.btn-secondary-outline looks disabled

### ISSUE THREAD

**Issue by svicalifornia** [twbs/bootstrap#20079] opened 2016-06-06 02:41 UTC
The font size is far too faint, and makes the button appear disabled. Users should not have to hover over such buttons to discover whether they are clickable; that should be apparent from their appearance.

IMO the secondary outline button should look exactly like the secondary button, since the latter already has outline style.

**Comment by patrickhlauke** [comment] 2016-06-06 06:40
Duplicate of https://github.com/twbs/bootstrap/issues/17286 - @mdo, can we get a decision soon on https://github.com/twbs/bootstrap/pull/19693 (specifically see https://github.com/twbs/bootstrap/pull/19693#issuecomment-221509115) which should finally address this?

**Closed by patrickhlauke** 2016-06-06 06:40 UTC
Labels: css, v4

**Comment by svicalifornia** [comment] 2016-06-06 07:35
Sorry for the dupe. Thanks for responding.
