### ISSUE TITLE
Too many undefined variable on compiled CSS

### ISSUE THREAD

**Issue by mRizvandi** [twbs/bootstrap#37046] opened 2022-08-29 11:31 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

I found too many undefined problem on compiled css,
There are too many variable on compiled css, that not have value:
check the lines of compiled css:
2809
3522
3636
3810
4184
4189
4190
4191
4198
4499
5207
5273
5287
5565
6110
all of this line, has variable without value.

### Reduced test cases

I remove all undefined variables, but its need to remove property that use this variables.

### What operating system(s) are you seeing the problem on?

Windows

### What version of Bootstrap are you using?

5.2

**Comment by julien-deramond** [comment] 2022-08-29 11:41
Duplicate of #36595

**Comment by mRizvandi** [comment] 2022-08-29 11:46
I found too many variables that not used. I think have to change the compiler to create a correct css compiled files.

**Comment by julien-deramond** [comment] 2022-08-29 11:52
The CSS compiled file is correct. Empty CSS variables can exist, it is valid.
However, we're going to try remove them when unused in order to lighten the file a little bit.

**Closed** 2022-08-29 17:38 UTC
