### ISSUE TITLE
bg-variant() alternative?

### ISSUE THREAD

**Issue by Arquiel** [twbs/bootstrap#29923] opened 2019-12-27 21:12 UTC
My code currently leverages bg-variant(). What is the suggested alternative? (Bootstrap v4.4.1)

**Comment by florianlacreuse** [comment] 2019-12-28 12:55
Duplicate of #29895?

**Comment by Arquiel** [comment] 2019-12-28 12:58
@florianlacreuse no, that issue had to do with big-variant() parameters, but did not discuss the suggested alternative.

**Comment by mdo** [comment] 2019-12-28 18:21
Backgrounds are generated by the new utility API coming in v5. You'll want to use that API to make changes to what background utilities are generated. Alternatively, you can create your own mixins that extend these.

**Closed by mdo** 2019-12-28 18:21 UTC

**Comment by lmajowka** [comment] 2020-02-24 09:39
Why is it so hard to post a link or explanation? Now I get this annoying warning and need to spend a lot of time figuring out what to do

**Comment by Arquiel** [comment] 2020-02-24 15:12
@mdo This should’ve been deprecated in V5 since your proposed solution requires V5. If we have to do something differently for the interim, please please provide some additional explanation.

**Comment by archy-bold** [comment] 2020-10-06 10:58
in v 4.5, the mixin takes a third argument `$ignore-warning`. Simply set this to true to ignore the warning if you're not planning to upgrade to Bootstrap 5.

```scss
@mixin bg-variant($parent, $color, $ignore-warning: false)
```
