### ISSUE TITLE
Carousel with Drag and Swipe support

### ISSUE THREAD

**Issue by kirantheprince** [twbs/bootstrap#17750] opened 2015-10-01 13:39 UTC
Carousel should be able to be dragged and swiped on the Touch devices. This seems to be a important and extremely serious issue right now with the carousel. It  is to be include in the next version atleast.

**Comment by starise** [comment] 2015-10-01 16:28
Since you're talking about it, Carousel should be deprecated imho. There are much more powerful and flexible plugins out there with its purpose that it looks just a waste of space in the code to me.

**Comment by cvrebert** [comment] 2015-10-01 17:21
This is already on the v4 roadmap (#17021):
> ## Carousel
> * Swipe support #8907 and #12881

**Comment by zacechola** [comment] 2015-10-07 13:40
Also a dupe of #17118

**Closed** 2015-10-07 14:02 UTC
Labels: feature, js, v4

**Comment by odahcam** [comment] 2018-01-08 19:31
I agree with @starise, a carousel is a too big JavaScript feature to be written inside Bootstrap. (imho)
