### ISSUE TITLE
V5 Tooltip Left Direction: The arrow does not stay in the middle

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#34906] opened 2021-09-04 11:25 UTC
![Image](https://i.imgur.com/DSO0MST.jpg)

**Comment by ffoodd** [comment] 2021-09-04 18:56
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by alecpl** [comment] 2021-09-06 12:41
Maybe a duplicate of #34595.

**Closed** 2021-09-06 12:48 UTC
Labels: awaiting-reply
