### ISSUE TITLE
Card deck no responsive

### ISSUE THREAD

**Issue by ph1823** [twbs/bootstrap#28357] opened 2019-02-25 19:55 UTC
Hello, I found a problem of responsive with the card-deck, here are two images with a different size:

[Width > 460 px & < 1180](https://image.noelshack.com/fichiers/2019/09/1/1551124335-1.png) <= This is not responsive
[Width < 460 px](https://image.noelshack.com/fichiers/2019/09/1/1551124335-2.png)
(I was no found the scss to edit the properties manually)
how to solve problem? Thank you for your reply !

**Comment by mdo** [comment] 2019-02-25 20:20
Please search next time—duplicate of #20321.

**Closed by mdo** 2019-02-25 20:20 UTC
