### ISSUE TITLE
v5 Accordion border bug at 150% zoom

### ISSUE THREAD

**Issue by vdolek** [twbs/bootstrap#33146] opened 2021-02-18 14:51 UTC
New accordeon component has weird dubbled border in inner panels (not first and not last). It is visible only in some page zooms. For me its even in 100%. I have 4k display and 150% system scale setting (Windows). It is reproducible in Chrome 88.0.4324.182 and Opera 74.0.3911.107. I have not tested other browsers. The screen is from official example (https://getbootstrap.com/docs/5.0/components/accordion/).

![image](https://user-images.githubusercontent.com/361441/108373846-9f1d5c00-7200-11eb-8aeb-489d51f131d8.png)

**Comment by XhmikosR** [comment] 2021-02-18 22:31
I feel like this is the usual rounding issues we have with browsers :/ I cannot reproduce here with 175% DPI on Windows 10.

**Comment by mdo** [comment] 2021-03-24 06:28
Closing since Beta 3 revamped some borders here. Will never be perfect with all zoom levels but should be improved.

**Closed by mdo** 2021-03-24 06:28 UTC
Labels: css, v5
