### ISSUE TITLE
Module not found: Error: Cannot resolve module 'bootstrap'

### ISSUE THREAD

**Issue by wzup** [twbs/bootstrap#20414] opened 2016-07-30 10:03 UTC
http://v4-alpha.getbootstrap.com/getting-started/download/#npm:

> `require('bootstrap')` will load all of Bootstrap’s jQuery plugins onto the jQuery object.

File:
```
const bs = require('bootstrap');
```

Doesn't require. Error thrown:
```
ERROR in . / assets / js / index.js
Module not found: Error: Cannot resolve module 'bootstrap' in C: \Users\ user\ sbox\ node\ app\ assets\ js
resolve module bootstrap in C: \Users\ user\ sbox\ node\ app\ assets\ js
looking for modules in C: \Users\ user\ node_modules
C: \Users\ user\ node_modules\ bootstrap doesn 't exist (module as directory)
resolve 'file'
bootstrap in C: \Users\ user\ node_modules
resolve file
C: \Users\ user\ node_modules\ bootstrap doesn 't exist
C: \Users\ user\ node_modules\ bootstrap.js doesn 't exist
C: \Users\ user\ node_modules\ bootstrap.jsx doesn 't exist
C: \Users\ user\ node_modules\ bootstrap.react doesn 't exist

```

**Comment by rafalp** [comment] 2016-07-30 12:54
Could you please confirm if this is same issue as one below?
https://github.com/twbs/bootstrap/issues/20385

**Comment by mdo** [comment] 2016-07-30 17:48
If this is the same as #20385, #20418 should fix it.

**Comment by cvrebert** [comment] 2016-07-30 20:07
Duplicate of #20383 or #20385.

**Closed by cvrebert** 2016-07-30 20:07 UTC
Labels: js, v4
