### ISSUE TITLE
Why is there no body.fixed-top-nav-bar rule?

### ISSUE THREAD

**Issue by mark0978** [twbs/bootstrap#29054] opened 2019-07-16 13:01 UTC
If I'm using a `<nav ... fixed-top>` navigation system, I have to go add break pointed padding to the body tag.

```
body {
  padding-top: 60px;   // For me this # is 56px
}
@media (max-width: 979px) {
  body {
    padding-top: 0px;
  }
}
```

It seems like this should be included in bootstrap as classes that could be applied to the body, and it seems so obvious needed that I'm wondering if it is impossible to do.  I'm not the only one that seems to think it should be built in [based on this SO question and answer and comments](https://stackoverflow.com/a/11008050/147562)

I'm thinking something similar to:

```
body.fixed-nav-bar {
  padding-top: 60px;  // Actual size computed based on variables from the navbar
}
@media (max-width: 979px) {
  body.fixed-nav-bar-expand-md {
    padding-top: 0px;
  }
}
...
```

Seems like the variables could be introduced so that as the navbar height is adjusted over time, they would track the padding at the top of the window.  I think we might need different `-md, -xl, -sm` variants for where the menubar hiding takes place.  Has this been tried and abandoned?  Not wanting to waste time implementing it if it has already been proven impossible to do.

One other show stopper here is that the `navbar` height does not appear to be specified at all, which of course complicates things....

The best alternative I've found is:

```
  <nav class="navbar navbar-expand-md" aria-hidden="true">
    <a class="navbar-brand" href="#">Navbar</a>
  </nav>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Navbar</a>
```
This causes a "shadow" `navbar` to be under the fixed-top `navbar`.

Where this fails is with screen readers which will now present 2 navbar-brand elements. This points at the need for a not-for-sr class to prevent that element from showing up for screen readers. However that class does not exist [for screen readers](https://getbootstrap.com/docs/4.0/utilities/screenreaders/)

I've tried to compensate for the screen reader issue with aria-hidden="true" but [this guide](https://www.accessibility-developer-guide.com/examples/sensible-aria-usage/hidden/) seems to indicate this will probably not work when the screen reader is in focus mode which is of course the only time you actually need it to work...

**Comment by andresgalante** [comment] 2019-07-19 14:43
Hi @mark0978, I think you have a good point. To me, it's a bit more complicated. 

The navbar doesn't have a `height` by design. If we set up a fixed `height ` size then it would break when text string on the navigation items are too long causing text wrapping. As a general rule, to build a flexible UI no component should have a `height`.

Since the Bootstrap doesn't know how high the navbar is, then I don't see how we could calculate the body class you are suggesting just with CSS.

In [the docs](https://getbootstrap.com/docs/4.3/components/navbar/#placement) there is a note about adding the padding to the body:

>>>  Fixed navbars use position: fixed, meaning they’re pulled from the normal flow of the DOM and may require custom CSS (e.g., padding-top on the <body>) to prevent overlap with other elements.

**Comment by florianlacreuse** [comment] 2019-07-22 19:49
In our apps, we use [`.sticky-top`](https://getbootstrap.com/docs/4.3/utilities/position/#sticky-top) because we don't want to deal with a header with a fixed `height`. However, it only works with browsers that support the `sticky` position, no stickiness for old browers like IE10 or IE11.

**Comment by mdo** [comment] 2019-08-29 03:49
Closing as a won't fix for now.

**Closed by mdo** 2019-08-29 03:49 UTC
Labels: css

**Comment by md-wasim-123** [comment] 2024-03-16 23:50
thanks 😍😍😍😍😍😍😍😍
