### ISSUE TITLE
touch events support

### ISSUE THREAD

**Issue by PopoApple** [twbs/bootstrap#17128] opened 2015-08-20 12:59 UTC
can it have touch events support on mobile device?

**Comment by kkirsche** [comment] 2015-08-20 13:03
Google translate: Supports touch events on a mobile device?

Not sure I understand the question. Bootstrap does support touch events on iOS, Android and I believe Windows Phone

**Comment by PopoApple** [comment] 2015-08-20 13:07
i say the carousel，i think it may support swipe to change pages on mobile device

**Comment by kkirsche** [comment] 2015-08-20 13:09
I believe this is a duplicate of #17118

**Comment by hnrch02** [comment] 2015-08-20 13:50
Closing as a duplicate of #17118.

**Closed by hnrch02** 2015-08-20 13:50 UTC
