### ISSUE TITLE
Links are not working on handy view

### ISSUE THREAD

**Issue by aiturria-spain** [twbs/bootstrap#33878] opened 2021-05-07 14:06 UTC
Hi all

I'm using Bootstrap V4.6 for a Typo3 project. The pages work fine with PC or Tablet. When I use a small device like a handy, the links from normal navigation do not work correctly. Only the first time when I click on the menu the page is displayed. For the next click on the menu nothing happens...  :-(

I don't receive any error messages in the console from browser.

I have built the menu exactly like described in documentation. I have only one level of submenues..

Do you have an idea what the problem could be? In the configuration of my Typo3 I use the "bootstrap.bundle.min.js" and the "bootstrap.min.css" version 4.6.0

Thanks a lot for your help.

Kind regards

Alberto

**Comment by ffoodd** [comment] 2021-05-07 14:43
Bug reports must include a **live demo** of the issue. Per our [contributing guidelines](https://github.com/twbs/bootstrap/blob/master/.github/CONTRIBUTING.md), please create a reduced test case via [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/) and report back with your link, Bootstrap version, and specific browser and operating system details.

---
_This is a saved reply._

**Comment by aiturria-spain** [comment] 2021-05-07 15:26
Hi Gael

Thanks a lot four your fast response.

The Link for the page is the following:

https://development.enz.com.46-231-206-156.mc18yx1804.vpsflex.net/en/home

It's a previewlink from a copy of the original web site. I couldn't test with the productive site..

I use the bootstrap version 4.6.0, the web is running on CENT-OS 8, the typo3 version is 10.4.14

If you need more information please reply..

Many thanks

Alberto

**Comment by neralex** [comment] 2021-05-07 15:46
I have exactly the same issues with the dropdowns on all devices since I updated from bs5beta3 to bs5stable. If I switched back to bs5beta3, then is all back in service. Unfortunately I'm not able to reproduce it with the public CDN-links, which are provided in the bs5stable docs.

**Comment by aiturria-spain** [comment] 2021-05-07 15:51
Hi,

thank your for the message. This Issue happens also with Bootstrap 4.6.0..

The web is normally working fine. But if I take a handy the the links don't work as expected..

I built the menues exactly like the documentation..

Kind regards

Alberto

**Comment by aiturria-spain** [comment] 2021-05-07 16:17
> 
> 
> I have exactly the same issues with the dropdowns on all devices since I updated from bs5beta3 to bs5stable. If I switched back to bs5beta3, then is all back in service. Unfortunately I'm not able to reproduce it with the public CDN-links, which are provided in the bs5stable docs.
> 
> Edit: In my case the class "show" will be only toggled on the first element with the class "dropdown-menu", which I used after the page-load. All clicks on another dropdown-toggle anchors will not toggle the class "show" on their related elements with the class "dropdown-menu".

Hi,

thank your for the message. This Issue happens also with Bootstrap 4.6.0..

The web is normally working fine. But if I take a handy the the links don't work as expected..

I built the menues exactly like the documentation..

Kind regards

Alberto

**Comment by mdo** [comment] 2021-05-07 20:29
That URL doesn't work for us—we'll need something else to help reproduce it if there's indeed a problem in Bootstrap. I don't think there actually is based on the description here. Closing until we get a Codepen or similar.

**Closed by mdo** 2021-05-07 20:29 UTC
Labels: awaiting-reply
