### ISSUE TITLE
Docs navbar is shifted to left in Edge

### ISSUE THREAD

**Issue by Studio384** [twbs/bootstrap#23290] opened 2017-08-11 07:58 UTC
![capture](https://user-images.githubusercontent.com/1693592/29205168-723b7414-7e7b-11e7-9546-8193caf0a047.PNG)

The navbar in the Bootstrap 4 docs is partially off screen in Edge 16 and the click targets do not line up with what is displayed (the click targets appear to still be on the place they should be).

Disabling ```position: sticky``` and ```z-index: 1071``` on ```.bd-navbar``` seems to fix it, but obviously comes with its own issues.

**Comment by XhmikosR** [comment] 2017-08-11 08:24
I don't understand what the issue is exactly. What is off-screen exactly?

**Comment by XhmikosR** [comment] 2017-08-11 08:26
OK, I just noticed what you mean.

Doesn't happen with Edge v15 which is the version that ships with Windows 10 stable.

![2017-08-11_11-25-19](https://user-images.githubusercontent.com/349621/29205869-f36800c8-7e87-11e7-91fd-146e4189d5f2.jpg)

**Comment by XhmikosR** [comment] 2017-08-11 08:27
Someone should report the issue to Microsoft.

**Comment by Studio384** [comment] 2017-08-11 22:05
Just noticed that the navbar will also move down (the grey bar is the bottom of the favorites bar):

<img width="1920" alt="naamloos" src="https://user-images.githubusercontent.com/1693592/29233536-a8dbaf36-7ef1-11e7-8ba3-14c2759f10e6.png">

Also note where Edge says the element actually is.

I know that beta software usually isn't a priority to support, but depending on where the issue lays, this should be reported to Microsoft, fixed in Edge and a workaround included in Bootstrap or fixed in Bootstrap. Edge 16 is close to finishing now.

**Comment by hanakin** [comment] 2017-08-14 20:50
similar issue on mac chrome 56

<img width="1677" alt="screenshot 2017-08-14 16 47 59" src="https://user-images.githubusercontent.com/73081/29291149-9fbecda4-8110-11e7-95fe-9d982a70d23e.png">

**Comment by XhmikosR** [comment] 2017-08-14 20:54
Chrome 56 is old. Works fine with latest Chrome. And we had an issue for that, which I closed for this exact reason.

**Comment by hanakin** [comment] 2017-08-14 22:37
not sure what criteria you are using in the justification seeing as how it was only released this year? I would not call it old... Yes its falling off but I am willing to bet that if its failing in 56 it might be failing in 49 & 58 which will stick around for quite awhile as they are used by several government/organizations still based on security compliance evaluations

1 year: http://gs.statcounter.com/browser-version-market-share/desktop/worldwide/#monthly-201607-201707-bar
3 mon: http://gs.statcounter.com/browser-version-market-share/desktop/worldwide/#monthly-201705-201707-bar

**Comment by XhmikosR** [comment] 2017-08-15 05:15
The criteria is they are evergreen browsers and that no one can fix something broken in a browser.

**Comment by mdo** [comment] 2017-08-15 05:49
Just as an aside, that issue with Chrome 56 is that their sticky implementation counts the `box-shadow`. I don't have any plans to fix it though—it'd require some severe hacking of HTML to account for it. It's also only present on non-retina screens as I recall.

Worked on this at GitHub for the toolbar on diff tabs :).

**Comment by XhmikosR** [comment] 2017-10-18 21:24
This doesn't seem to happen with Microsoft Edge 41.16299.15.0 either.

There's some weird shifting while scrolling the page in the left sidebar, but I think it's due to the wrong use of scrollspy which is removed in v4-dev. We'll see when beta2 is out.

**Comment by XhmikosR** [comment] 2017-11-01 14:36
Closing since I can't reproduce with the Edge stable version.

**Closed by XhmikosR** 2017-11-01 14:36 UTC
Labels: browser bug, docs, v4
