### ISSUE TITLE
Changing theme-color map not changing for hover

### ISSUE THREAD

**Issue by iSteveZissou** [twbs/bootstrap#27749] opened 2018-11-30 16:29 UTC
Not sure how to best explain.

I'm compiling the custom.scss with a new theme-color map (among other changes) eg. 
```
$theme-colors: (
"primary ":#ead1dc,
"secondary ":rgb(111, 168, 220),
"success ":rgb(75, 191, 115),
"danger ":rgb(153, 0, 0),
"warning ":rgb(240, 173, 78),
"info ":rgb(31, 155, 207)
);

```

While the color correctly changes all buttons, alert, navbar etc, hovering over a button or selecting a checkbox option is still the default color and hasn't been updated.

I'm setting the variable first then importing the bootstrap scss files.

Any pointers or help would be much appreciated. Thanks!

**Comment by rafalp** [comment] 2018-11-30 17:00
Duplicate of #27338

**Comment by iSteveZissou** [comment] 2018-11-30 17:18
> Duplicate of #27338

Not sure how this is a duplicate - this issue mentions the $link-color variable?

I can set the $link--hover-color without issue.

My problem is I don't know how to update button hover colors after using a custom $theme-colors map. All button change color accordingly but hovering darkens slightly based on the default color map not my custom one. For example - say I set the "primary" to pink - the button is indeed pink but when I hover the button turns blue - I'd like it to darken based on the color of the button (pink in this case).

**Comment by mdo** [comment] 2018-11-30 18:18
Might need to see an example of your HTML with the custom compiled CSS, @iSteveZissou. Could be a problem on either side.

**Comment by iSteveZissou** [comment] 2018-11-30 18:49
> Might need to see an example of your HTML with the custom compiled CSS, @iSteveZissou. Could be a problem on either side.

Thanks @mdo  - I've actually just got it sorted.

It seems the issue only happens when using $theme-colors map - as I mentioned above, more or less everything changes correctly other than hover, focus etc

If I use the variables on their own instead eg:

```
$primary:#ff00ff;
$secondary:#999999;
$success:#9fc5e8;
$danger:#cc0000;
$warning:#e69138;
$info:#93c47d;

```

hover and focus on buttons now correctly darken the color for each. So this only seems to be an issue when using the $theme-color map. Not sure why this makes a difference but solves the issue for now.
Cheers

**Comment by ysds** [comment] 2018-12-01 12:15
Hi @iSteveZissou 

I created a pen including all bootstrap SCSS and your custom SCSS.

https://codepen.io/fellows3/pen/jQdVem

Can you reproduce the problem using it?

**Comment by MartijnCuppens** [comment] 2019-01-13 19:32
This was fixed in https://github.com/twbs/bootstrap/pull/27848.

**Closed by MartijnCuppens** 2019-01-13 19:32 UTC
Labels: awaiting reply, css
