### ISSUE TITLE
Dotted border issue in firefox

### ISSUE THREAD

**Issue by Hemanth089** [twbs/bootstrap#17006] opened 2015-08-18 11:16 UTC
When click happens in all elements a dotted border is added in firefox browser? Can you add necessary css to fix this?

**Comment by kkirsche** [comment] 2015-08-18 11:30
What version of Firefox, what operating system and version, and would you be able to post a isolated example on JSBin

**Comment by Hemanth089** [comment] 2015-08-18 12:37
I'm using Firefox 39.0.3. In JSBin it is working correctly. But in my local it shows the dotted border. I'm using bootstrap  v3.3.5.

**Comment by Hemanth089** [comment] 2015-08-18 12:42
Check out the output in JsBin example in firefox 39.0.3 browser 

http://output.jsbin.com/cokiyavogo

**Comment by patrickhlauke** [comment] 2015-08-18 12:57
This is standard behavior for focused elements in Firefox and Internet Explorer. Chrome tries to do some trickery in not applying outlines on focusable elements as a result of a mouse interaction, but it used to behave exactly the same way. In fact, the `outline` property is explicitly defined for focused links and `.btn` elements in the CSS. In short, this is the intended behavior.

**Comment by patrickhlauke** [comment] 2015-08-18 13:03
We may look at working around this some more in Bootstrap v4 (off the top of my head, a fix for this is to NOT specifiy an explicit `a:focus, .btn:focus { outline:dotted; }` and to leave it up to the browser to do its own standard outline, which it can then optimize for mouse use), but for v3, we're not likely to make any changes to this I'm afraid.

**Closed by patrickhlauke** 2015-08-18 13:03 UTC
