### ISSUE TITLE
.hidden-sm-down not hiding until viewport is 766px wide

### ISSUE THREAD

**Issue by succli** [twbs/bootstrap#18578] opened 2015-12-15 08:56 UTC
I'm working on a site, where in the header I have a logo in the left and a menu in the right. In small size I want to hide the menu and put in the hambuger menu. I use hidden-sm-down for it, but the class hides the menu one pixel down. So my small size starts at 767px, but the hidden class only effects at 766px. It's a problem because my logo's container is 12 unit wide in small size, therefore in 767px it push the visible menu a row under. Am I using this class wrong or there is a bug in the grid?

**Comment by cvrebert** [comment] 2015-12-15 09:19
That sounds like a bug in the grid. I can't reproduce the misbehavior you're describing though.
* Please ensure that you're using either the `v4.0.0-alpha.2` release or the `v4-dev` branch.
* What OS and browser are you using?

**Comment by succli** [comment] 2015-12-15 09:50
I'm using v4.0.0-alpha, can this be the source of the problem?
OS: Windows 10
Browser: Mozilla Firefox 42.0

**Comment by cvrebert** [comment] 2015-12-15 09:56
@succli Very much so. Please upgrade and re-test.

**Comment by NandoTh** [comment] 2015-12-15 13:23
This happened in:  v4.0.0-alpha. Due to the this code:
```javascript
@media (max-width: 47.9em) {
  .hidden-sm-down {
    display: none !important;
  }
}

@media (min-width: 48em) {
  .hidden-md-up {
    display: none !important;
  }
}
```
767px is 47.9375em. The latest version of v4.0.0-alpha.2 under the v4-dev branch has it changed to: max-width: 767px and min-width: 768px. 

Note: I checked the bootstrap.css file under /dist/css. I'm not sure whether this file is generated and the bug may still exist.

**Comment by cvrebert** [comment] 2015-12-15 20:22
Assuming this is a duplicate of #17388.
If upgrading to the 2nd Alpha doesn't fix it, let me know.

**Closed by cvrebert** 2015-12-15 20:22 UTC
Labels: awaiting reply, css, v4

**Comment by cvrebert** [comment] 2015-12-15 20:23
For the record, all the files under `/dist` are generated; this is the purpose of that directory.
