### ISSUE TITLE
width value has number of decimal problem

### ISSUE THREAD

**Issue by huang-x-h** [twbs/bootstrap#20584] opened 2016-08-26 07:16 UTC
- Window7
- Chrome51
- [JSBin Example](http://jsbin.com/powape/edit?html,output)

In form, when use `form-control` and `input-group`, sometimes when the `form-control` element width has number of decimal, it will large than the `input-group` element

![qq 20160826151438](https://cloud.githubusercontent.com/assets/381860/17997233/e1dc9d7e-6b9f-11e6-8081-6e193c7adaa4.png)

**Comment by bardiharborow** [comment] 2016-08-26 08:09
I can't reproduce on `Mac OS X 10.11.5 Chrome 53.0.2785.80` using the JSBin provided.

**Comment by huang-x-h** [comment] 2016-08-26 08:15
@bardiharborow you must resize the window to change `form-control` width, see

![untitled](https://cloud.githubusercontent.com/assets/381860/17998677/307ce3c8-6ba8-11e6-99ea-fd1b195f154c.png)

**Comment by bardiharborow** [comment] 2016-08-26 08:38
Ah, it was unclear. I can reproduce now.

**Comment by cvrebert** [comment] 2016-08-26 22:03
Presumably this is due to lack of subpixel table layout on Chrome, i.e. https://bugs.chromium.org/p/chromium/issues/detail?id=534750
Please re-test in Firefox to confirm.

**Comment by bardiharborow** [comment] 2016-08-27 05:11
@cvrebert, I am unable to reproduce on `Mac 10.11.5 Firefox 49.0b7`, so you are probably correct. Is there a way Bootstrap could work around this, or do we have to wait for a Chrome fix?

**Comment by cvrebert** [comment] 2016-08-27 06:46
Closing as a duplicate then.

**Closed by cvrebert** 2016-08-27 06:46 UTC
Labels: browser bug, css, v3

**Comment by huang-x-h** [comment] 2016-08-29 05:41
Yes, Firefox is ok, when change bootstrap v4 flex mode it's ok in chrome
