### ISSUE TITLE
jQueryUI.datepicker is shown behind modal in case of using input group

### ISSUE THREAD

**Issue by Rikijs** [twbs/bootstrap#37669] opened 2022-12-18 17:19 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

jQueryUI.datepicker is shown behind modal in case of using an input group.

Created CodePen and tested in `current Chrome`, `current Firefox`, `current Opera` and `current Edge` (on Windows 10 Pro).
The outcome is the same - if using input group - the jQueryUI date picker is below Bootstrap modal,

I attempted to override `z-index` with CSS, but it did not work.

![image](https://user-images.githubusercontent.com/18629166/208310630-5dde6254-8508-45c2-bc8a-4ccb31982bd6.png)

### Reduced test cases

CodePen demostrating the problem
https://codepen.io/Rikijs/pen/NWBWKJd

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Opera

### What version of Bootstrap are you using?

v5.2

**Comment by julien-deramond** [comment] 2022-12-18 19:50
IDK if this is the right solution but you can try
```css
.ui-datepicker {
  z-index: 99999 !important;
}
```
with `.ui-datepicker` as selector instead of `.datepicker`

**Comment by mdo** [comment] 2022-12-18 21:29
Closing as not a bug in Bootstrap :).

**Closed by mdo** 2022-12-18 21:29 UTC
Labels: awaiting-reply

**Comment by Rikijs** [comment] 2022-12-19 14:08
Yes, `.ui-datepicker` works all right.
Sorry for embarrassing mis-judgement on my part.
