### ISSUE TITLE
Outline checkbox button has incorrect focus state

### ISSUE THREAD

**Issue by LocalHeroPro** [twbs/bootstrap#36502] opened 2022-06-04 17:12 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

When we use Checkbox with outlined style
https://getbootstrap.com/docs/5.2/forms/checks-radios/#outlined-styles
When checkbox is selected and we click on that checkbox to unselect it, selecting color still appear and to see changes - no color inside button - we need to click somewhere else. 
If wee still clicking on same checkbox, we have selected color inside checkbox. No changes appears.
It's annoying.

### Reduced test cases

<input type="checkbox" class="btn-check" id="btn-check-outlined" autocomplete="off">
<label class="btn btn-outline-primary" for="btn-check-outlined">Single toggle</label><br>

### What operating system(s) are you seeing the problem on?

Linux

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Opera

### What version of Bootstrap are you using?

5.2

**Comment by RedHeadphone** [comment] 2022-06-14 11:21
The issue is with :focus in .btn-check right?

**Comment by mdo** [comment] 2022-06-14 14:27
Duplicate of #31149.

**Comment by RedHeadphone** [comment] 2022-06-14 14:55
@mdo but this issue is related to :focus and not :hover

**Comment by mdo** [comment] 2022-06-14 14:58
Ah yup, sorry! Will review again, I think I found when and why this bug/change was introduced thanks to your PR.

**Comment by RedHeadphone** [comment] 2022-06-17 06:23
Do I move back specific CSS for `.btn-*` and `.btn-outline-*` back to mixin? or is there better way to do it?

**Comment by Aliyosign** [comment] 2022-08-11 12:08
hey 
am interested in this task , how do l go ahead?

**Comment by florianlacreuse** [comment] 2022-08-11 12:42
You should read the readme and the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md).

**Closed** 2022-09-04 16:59 UTC
Labels: css, confirmed, v5
