### ISSUE TITLE
v4 - Broken popovers / tooltips on Firefox

### ISSUE THREAD

**Issue by jorditarrida** [twbs/bootstrap#17097] opened 2015-08-20 06:40 UTC
Hi,
Thanks for all the good work in Bootstrap.
However, popovers and tooltips seem to be broken on Firefox 40 on Windows 7.
Here's some screenshots:
- Title not working on popovers
![popover1](https://cloud.githubusercontent.com/assets/4738498/9377186/b595e31e-4716-11e5-89bb-d66d30e3ad24.PNG)
- Tooltips are not displaying text and arrows properly
![tooltip](https://cloud.githubusercontent.com/assets/4738498/9377225/1ea94f76-4717-11e5-8508-782ebb84ded3.PNG)

Cheers :)
J

**Comment by zacechola** [comment] 2015-08-20 18:24
Re. the titles, the issue isn't that they're not working, it's that the JS inserts an `<h3>` even when there isn't a title present.

[Test case example](http://jsbin.com/tepequ/edit?html,output)

**Comment by cvrebert** [comment] 2015-08-20 21:45
The tooltip unit test suite seems to be failing on Firefox on all platforms:
https://saucelabs.com/jobs/e6801b06a94e456eb32562200581d6b4
CC: @fat

**Comment by vejersele** [comment] 2015-08-24 12:23
innerText isn't supported on firefox ... http://stackoverflow.com/questions/1359469/innertext-works-in-ie-but-not-in-firefox

**Comment by cvrebert** [comment] 2015-08-26 08:26
Fixed by #17330.

**Closed by cvrebert** 2015-08-26 08:26 UTC
Labels: confirmed, js, v4
