### ISSUE TITLE
Module not found for v4-alpha.3

### ISSUE THREAD

**Issue by havvg** [twbs/bootstrap#20471] opened 2016-08-05 19:58 UTC
I just upgraded to v4-alpha.3 from v4-alpha.2

`require('bootstrap')` stopped working with the following error message:
> Module not found: Error: Cannot resolve module 'bootstrap' in ..

Environment:
* node v6.3.1
* npm v3.10.3
* webpack v1.13.1

**Comment by cvrebert** [comment] 2016-08-06 00:47
Duplicate of #20383.

**Closed by cvrebert** 2016-08-06 00:47 UTC
