### ISSUE TITLE
Collapse (accordion?) animation error when using styled button click handler in collapse

### ISSUE THREAD

**Issue by bobvandevijver** [twbs/bootstrap#33881] opened 2021-05-07 22:31 UTC
Bootstrap: 5.0.0
OS: Windows 10 20H2
Browser: Both Edge 90 & Firefox 88
Reproduction: https://codepen.io/bobvandevijver/pen/abJzjgM for an example

When a bootstrap styled button is used to close a collapsible panel (either programmatically or using the data attribute), the close animation doesn't behave as expected (the collapsible closes with almost no animation). The animation is correct when a default non-styled button is used, or when the collapse header is used to toggle.

In the reproduction I added both type of buttons: you can move the class around between (collapse one to two), the issue moves with it.

It looks like the animation on the button itself is the problem. When you keep the button pressed to wait for that animation to finish and then let it go, the close animation of the collapsible looks a bit better.

**Comment by rohit2sharma95** [comment] 2021-05-08 13:48
Quick fix :smile:
```css
.accordion-body .btn {
  transition: none !important;
}
```

**Comment by alpadev** [comment] 2021-05-08 18:36
Duplicate of https://github.com/twbs/bootstrap/issues/33682

**Closed by alpadev** 2021-05-08 18:36 UTC
Labels: css
