### ISSUE TITLE
Bootstrap Dark Mode

### ISSUE THREAD

**Issue by devhoussam** [twbs/bootstrap#32493] opened 2020-12-15 11:14 UTC
I hope **Bootstrap** team add the **dark mode** like T**ailwind CSS** it will be something special for every developer who use Bootstrap in his projects.

in fact for me I wait this feature soon as possible I love **Bootstrap** it make life easier

thank you to all **bootstrap teams** for this creative framework

**Comment by florianlacreuse** [comment] 2020-12-15 13:25
I would also like Bootstrap to support dark / light mode using `prefers-color-scheme`.

But this is a duplicate of #27514.

**Comment by XhmikosR** [comment] 2020-12-15 14:10
Duplicate of #27514.

**Closed by XhmikosR** 2020-12-15 14:10 UTC
Labels: duplicate, feature
