### ISSUE TITLE
Feature request - Right To Left layout

### ISSUE THREAD

**Issue by ppp999** [twbs/bootstrap#19703] opened 2016-04-10 13:55 UTC
Please consider to make a RTL version of Bootstrap. 

I know that there are some RTL forks, but it doesn't support well, and they not update for each version of Bootstrap.

Hope you will make that.

**Comment by hebbet** [comment] 2016-04-10 13:57
see [19545#comment](https://github.com/twbs/bootstrap/issues/19545#issuecomment-196990781)

**Comment by ppp999** [comment] 2016-04-10 14:02
Thanks

**Comment by cvrebert** [comment] 2016-04-10 18:44
Nope.

**Comment by cvrebert** [comment] 2016-04-10 18:44
Duplicate of #19555.

**Closed by cvrebert** 2016-04-10 18:44 UTC

**Comment by parsmizban** [comment] 2017-03-18 15:02
Hi,
You can use this patch for full RTL compatibility for both Bootstrap 3.3.7 and 4.0.0-alpha.6
https://github.com/parsmizban/RTL-Bootstrap
If you have any pre designed theme, You can use this path to make your template RTL very easy
Good luck
