### ISSUE TITLE
Bootstrap v4: Tooltip and window.Tether

### ISSUE THREAD

**Issue by n3ssi3** [twbs/bootstrap#18647] opened 2015-12-23 12:29 UTC
While playing around with ReactJS, BS4 and webpack, I ran into an issue with Tether.
Usually I would use `import Tether from 'tether'` and `import Bootstrap from 'bootstrap'` but since you use window.Tether I couldn't do that. Now I have to use `window.Tether = require('tether')`.
When mixing import and require that actually affects the loading order. Import seems to be loaded before require, no matter the order in the file. So I have to switch also Bootstrap to require.

Is there a way, we can remove window here?
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L19

Or do you have a better idea how to solve this issue?

**Comment by cvrebert** [comment] 2015-12-23 18:27
Approximate duplicate of #17201 / #17325.

**Closed by cvrebert** 2015-12-23 18:27 UTC
Labels: js, v4

**Comment by jaredramirez** [comment] 2016-06-07 19:03
Realized issue is closed but seeing at [#17325](https://github.com/twbs/bootstrap/issues/17325) is locked to all except collaborators , and [#17201](https://github.com/twbs/bootstrap/issues/17201) wasn't webpack specific, I thought I'd post my solution here. 

Rather than remove `if (window.Tether === undefined)`, try making the Tether variable a global variable using webpack. 

`module: {
      loaders: [
        { test: /tether\.js$/, loader: "expose?Tether" }.
        //other config here
      ]
    }`

**Comment by karolyi** [comment] 2016-09-18 21:34
+1, why is this issue closed?

using webpack, because of bootstrap, I had to make jQuery a global variable, *BUT* then, tether is still looked up in `window`, in `tooltip.js`, so the following webpack config snippet, exposing Tether as a global variable for `tooltip.js`, doesn't help:

```javascript
      {
        // Transpile ES6 to ES5 in Bootstrap V4
        test: /bootstrap\/js\/src\/.*\.js$/,
        loaders: [
          'imports?jQuery=jquery,Tether=tether',
          'babel?babelrc=true',
        ],
      },
```

please guys, if you really need us to globally expose variables for bootstrap, at least make it consistent.

**Comment by cvrebert** [comment] 2016-09-18 21:52
> why is this issue closed?

See https://github.com/twbs/bootstrap/issues/18647#issuecomment-166963846
