### ISSUE TITLE
v4.0.0-alpha.6 - Activating tooltips breaks modals (stuck "transitioning")

### ISSUE THREAD

**Issue by METACEO** [twbs/bootstrap#21607] opened 2017-01-08 10:38 UTC
Operating systems and browsers:
- Windows; Firefox 50.1.0, Internet Explorer 11, Tor Browser 6.0.8 (Firefox 45.6.0)
- Android 5.0.1 (Galaxy S4); Firefox 40.0.3, Chrome 45.0.2454.84, Stock Browser 2.1.34.19

Launch [the demo modal with tooltips](https://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers) in the component's documentation, activate a tooltip, then try and exit the modal - nothing expected appears to happen. [I have reproduced this outside the documentation](https://jsfiddle.net/6yy600a8/) ~~while I have not yet tried to reproduce this outside the documentation~~, across all of my devices, this seems to be a show-stopping bug - freezing the user's interface and preventing any other interaction.

I'm logging two different errors in my console:
- closing the modal logs `Error: Modal is transitioning`
- activating a tooltip logs `Error: Tooltip is transitioning`.

**Comment by METACEO** [comment] 2017-01-08 10:51
I just [reproduced this in](https://jsfiddle.net/6yy600a8/) JSFiddle.

**Comment by JD-Robbs** [comment] 2017-01-08 11:12
Similar for me. Perhaps related: #21600

**Comment by Paladinium** [comment] 2017-01-08 16:07
Temporary workaround is to remove the 'fade' class on modals.

**Comment by Johann-S** [comment] 2017-01-08 16:14
It's due to those lines : https://github.com/twbs/bootstrap/blob/v4-dev/js/src/tooltip.js#L473-L476

Because we check if a tooltip is wrapped into a modal but not if the tooltip is visible or not and called ``hide`` twice instead of one call

**Comment by ghiscoding** [comment] 2017-01-08 18:50
Nice to know that I'm not the only one seeing this problem. However in my case I have a page with multiple elements and Tooltips (no modal in play) and after doing a few mouse hovering, I start seeing the 

`Error: Tooltip is transitioning`. 

@Johann-S will your code change also fix when using Tooltip only (not in Modal)?

**Comment by Johann-S** [comment] 2017-01-08 19:11
@ghiscoding not sure of that but if you can produce a reduce test case I can check that

**Comment by ghiscoding** [comment] 2017-01-08 19:56
I can reproduce it on the [Tooltip Doc](https://v4-alpha.getbootstrap.com/components/tooltips/) page. It takes a few hover over to get the errors to show up in the console, I usually can see them appearing after 15-20 times of doing hover over the Toolips. I can reproduce in both Chrome and Firefox.

Created a JSFiddle account and tried forking with unminified `bootstrap.js` code to know which line throws the error and this is what came up (again saying, this is after 15-20 times of doing hover over):
```javascript
Uncaught Error: Tooltip is transitioning
    at Tooltip.show (bootstrap.js:2946)
    at Tooltip._enter (bootstrap.js:3187)
    at HTMLButtonElement.<anonymous> (bootstrap.js:3134)
    at HTMLButtonElement.handle (jquery-3.1.1.min.js:3)
    at HTMLButtonElement.dispatch (jquery-3.1.1.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.1.1.min.js:3)
```
Try the [JSFiddle](https://jsfiddle.net/Lnckrj3y/6/), hope it works for you

**Comment by Johann-S** [comment] 2017-01-08 20:15
It's due to this PR : https://github.com/twbs/bootstrap/pull/17823

My PR https://github.com/twbs/bootstrap/issues/21613 wont fix what you report

**Comment by ghiscoding** [comment] 2017-01-08 20:26
Do you need me to open another issue, since it might need another PR, or do we leave it all in here?

**Comment by JD-Robbs** [comment] 2017-01-08 20:48
@ghiscoding maybe extend on what I noted in #21600.

**Comment by 2Fwebd** [comment] 2017-01-12 15:33
Same here, Tooltips are working just fine but whenever we scroll the error shows up: 
<img width="1427" alt="banners_and_alerts_and_connections_ _wp_dev" src="https://cloud.githubusercontent.com/assets/5446124/21895909/c4cf465c-d8e4-11e6-82bb-d7e3fd0ddf11.png">
I can send you more details if you are having trouble reproducing it :)

**Comment by vanduynslagerp** [comment] 2017-01-14 22:50
Ref #21727

**Comment by dons20** [comment] 2017-01-18 07:50
Had the same issue, fixed by adding `data-animation="false"` to my html elements.

**Comment by jaketoolson** [comment] 2017-01-28 04:50
This is annoying... There seems to be no real fix, yet I see lots of issues opened about this and a lot of run-around.

**Comment by vanduynslagerp** [comment] 2017-01-28 04:52
Here is the issue aim at centralizing all the problems: #21727
Here is a PR to fix it there: #21743

**Comment by feng-xiao** [comment] 2017-03-12 18:41
please bring back old tooltip plugin

**Comment by ghiscoding** [comment] 2017-03-12 20:04
@feng-xiao I believe that v3 is not under development anymore.

**Comment by feng-xiao** [comment] 2017-03-12 20:40
what I meant is to bring the tooltip plugin in v3 to v4. The tooltip plugin (using tether js) in v4 is buggy, and it's missing most important feature I need - **'auto'** placement. I have a tooltip that is defined in left side of screen, when the tooltip is shown the content is cut off. I'm using 'auto' placement in v3, that is automatically adjusting position

**BS v4**
![image](https://cloud.githubusercontent.com/assets/3407775/23835694/4e6d2308-0742-11e7-8ae6-9402faf3e1b6.png)

**BS v3**
![image](https://cloud.githubusercontent.com/assets/3407775/23835708/794d8d92-0742-11e7-9988-996dd6b167d1.png)

**Comment by adeodevs** [comment] 2017-03-14 12:53
data-animation="false" on the elements having the data-toggle attribute solved the issue. Ref: @dons20

**Comment by niftylettuce** [comment] 2017-03-14 18:53
What is the solution?  I have the same error here - occurred when I updated from v4 alpha 4 to v4 alpha 6.

**Comment by METACEO** [comment] 2017-03-14 19:10
Until the solution #21743 is merged, you'll have to find and use one the temporary solutions as a patch.

**Comment by kotmatpockuh** [comment] 2017-03-16 13:33
@METACEO any news, when build#7 release was planned?

**Comment by ghiscoding** [comment] 2017-03-16 17:53
@kotmatpockuh the next release is actually `Beta (0)` and since this is open source there is no planned date, it could be next month or in few months. I suggest you to follow the [Bootstrap Milestones](https://github.com/twbs/bootstrap/milestones) to see the progress (it currently sits at 59% complete.

**Comment by cvkps6971h** [comment] 2017-03-18 10:23
There is solution of it. make sure animation properties is false
```
$('body').popover({
            placement: 'bottom',
            container: 'body',
            trigger: 'hover',
            html: true,
            animation: false,
            selector: '[data-toggle="popover"]'
        });
```

**Comment by METACEO** [comment] 2017-03-19 00:29
@cvkps6971h it's more of a work-around just to get by, an actual solution is being worked on.

**Comment by bsbak** [comment] 2017-03-26 16:17
here the some problem:
1. focusin input
2. click on label for that input

in the console you will see error

[JSFIDDLE](https://jsfiddle.net/4t9ovvvx/)

**Comment by kamilo81** [comment] 2017-03-29 11:22
this works for me
`
setTimeout(function () { 
                $modal.modal('hide');
        })
`

**Comment by Johann-S** [comment] 2017-03-29 11:24
Close due to the merge of https://github.com/twbs/bootstrap/pull/21743

**Closed by Johann-S** 2017-03-29 11:24 UTC
Labels: js, v4

**Comment by d4rkd0s** [comment] 2017-04-25 18:13
@Paladinium `Temporary workaround is to remove the 'fade' class on modals.`

Removing `fade` from `class="modal fade"` causes my modals to no longer open/work

**Comment by d4rkd0s** [comment] 2017-04-25 18:14
@dons20 `Had the same issue, fixed by adding data-animation="false" to my html elements.`

I've added this to my modal `<div>`'s and its not working. Still getting `Modal is transitioning`

**Comment by d4rkd0s** [comment] 2017-04-25 18:21
@Paladinium `Temporary workaround is to remove the 'fade' class on modals.`
You must also verify that the modal div doesn't have `aria-hidden="true"`

Then this fix works for Modals.

**Comment by TomFoyster** [comment] 2017-05-18 11:45
Having the same issue (Error: Tooltip is transitioning) - I'm not using Modals though, 

Any update on the progress of this fix?

**Comment by Johann-S** [comment] 2017-05-18 11:55
This fix will be available on our next release

**Comment by git-it-2020** [comment] 2017-05-18 18:50
hi johann-s will u please provide a conservative estimate for the next twbs release?  2 weeks, 6 weeks, 12 weeks, etc?  I want to set up a reminder on my calendar to add back the 'fade' class after the issue has been fixed

**Comment by Johann-S** [comment] 2017-05-18 19:50
Sorry @git-it-2020 but the answer is when all the openned issues target by the beta release will be closed

**Comment by rawzone** [comment] 2017-05-24 18:34
Anyone got a workaround until that huge amount of issues is closed and next beta release is out?
(Not problem om modals, simple tooltips breaking JS execution).

**Comment by isapir** [comment] 2017-05-24 19:20
Why is this issue closed?  

I still see it happening in the Bootstrap-4-alpha-6 documentation page:
https://v4-alpha.getbootstrap.com/components/modal/#tooltips-and-popovers

**Comment by ghiscoding** [comment] 2017-05-24 19:33
@isapir this was fixed in `Beta 1` version (not the `Alpha 6`), however this version is still in development and not yet released. 

@rawzone you should read the entire post, I believe that a few quick fixes were posted in here already

**Comment by JackZeled0n** [comment] 2017-06-20 03:22
As @cvkps6971h made it, but I'm using tooltip on mdbootstrap, 
$('body').tooltip({
            placement: 'right',
            container: 'body',
            trigger: 'hover',
            html: true,
            animation: false,
            selector: '[data-toggle="tooltip"]'        
});

**Comment by lianglee** [comment] 2017-07-16 16:58
Using boostrap alpha-6

```
bootstrap.min.js:7 Uncaught Error: Tooltip is transitioning
    at h.hide (bootstrap.min.js:7)
    at h._leave (bootstrap.min.js:7)
    at HTMLImageElement.<anonymous> (bootstrap.min.js:7)
    at HTMLImageElement.handle (jquery-1.11.1.min.js:3)
    at HTMLImageElement.dispatch (jquery-1.11.1.min.js:3)
    at HTMLImageElement.r.handle (jquery-1.11.1.min.js:3)
```

**Comment by rafalp** [comment] 2017-07-16 18:45
@lianglee this is fixed on master that wasn't released yet. This fix will hit as part of beta 1

**Comment by lianglee** [comment] 2017-07-17 18:01
Sure, thanks

**Comment by samirmammadhasanov** [comment] 2017-08-26 13:39
I'm still getting this error. Waiting for fix.

**Comment by Johann-S** [comment] 2017-08-26 13:58
The beta 1 is out so you just have to update your release of Bootstrap @samirmammadhasanov

**Comment by samirmammadhasanov** [comment] 2017-08-26 15:43
I thought i was using beta1. But actually it was alpha. It working now. Thanks @Johann-S

**Comment by Sreng-S** [comment] 2017-09-18 08:25
I can see this error;
Uncaught Error: Modal is transitioning
    at h.hide (bootstrap.min.js:6)
    at HTMLDivElement.<anonymous> (bootstrap.min.js:6)
    at HTMLDivElement.dispatch (app.js:31839)
    at HTMLDivElement.elemData.handle (app.js:31651)

**Comment by dons20** [comment] 2017-09-18 14:05
@Sreng-S it has already been fixed in beta 1.

**Comment by leotinoco** [comment] 2017-11-17 03:52
Add `data-animation="false"` in addition to the `data-toggle="tooltip"` on everyone element
