### ISSUE TITLE
Add a Sidebar component

### ISSUE THREAD

**Issue by JThompson1123** [twbs/bootstrap#19345] opened 2016-02-28 15:39 UTC
Many Frameworks have Sidebars available out of the box.

What about a customisable sidebar? It seems to be the only thing i have an issue with is creating my own sidebar.

Great for people building admin panels, one less thing to create / worry about.

allow, items, sub-menus, headers etc.

**Comment by ZakariaRidouh** [comment] 2016-02-28 19:53
This is actually a really good idea, @mdo any plans about this?

**Comment by yasinkocak** [comment] 2016-02-29 13:49
:+1:

**Comment by cvrebert** [comment] 2016-03-01 00:55
@JThompson1123 To clarify, do you mean a vanilla sidebar, or an off-canvas sidebar (#17502)?

**Comment by JThompson1123** [comment] 2016-03-04 08:36
@cvrebert Sorry, i've been busy. What exactly do you mean by vanilla or off-canvas?

My example would be like a sidebar in an admin panel, you click a button in the navbar and it slides in etc. It has sub-menus etc.

**Comment by cvrebert** [comment] 2016-03-04 08:42
> it slides in etc.

Okay, so off-canvas then. A "vanilla"/normal/static sidebar would always be visible.

**Comment by cvrebert** [comment] 2016-03-04 08:43
Duplicate of #17502.

**Closed by cvrebert** 2016-03-04 08:43 UTC
Labels: css, feature, v4
