### ISSUE TITLE
Double border when having button/dropdown to the left of an input in input-group.

### ISSUE THREAD

**Issue by jarekwg** [twbs/bootstrap#20801] opened 2016-09-28 00:48 UTC
Happens when button/dropdown is to the left of an input, but doesn't happen when it's to the right.
![Kink](https://d17oy1vhnax1f7.cloudfront.net/items/0P2R1x203w1g3t1c2a1g/Image%202016-09-28%20at%2010.31.38%20AM.png?v=dc39753e)
![Kink2](https://d17oy1vhnax1f7.cloudfront.net/items/0u280c2P3K403C2b1g15/Image%202016-09-28%20at%2010.33.01%20AM.png?v=83a3231a)
(screenshots from the [bootstrap4 demo website](http://v4-alpha.getbootstrap.com/components/input-group/#buttons-with-dropdowns))
You might need to zoom in a little to see what I mean.

Happens on OSX Chrome Version 53.0.2785.101 (64-bit)

I also tested it on OSX firefox and that one rendered correctly.

**Comment by cvrebert** [comment] 2016-09-28 06:30
Duplicate of #17438.
It's a bug in Chrome: https://crbug.com/534750 / https://crbug.com/568691

**Closed by cvrebert** 2016-09-28 06:30 UTC
