### ISSUE TITLE
Right border of <textarea> is overlapped by scrollbar in Chrome

### ISSUE THREAD

**Issue by OlexandrPopov** [twbs/bootstrap#19804] opened 2016-04-26 08:51 UTC
Steps to reproduce:

1. Open this url http://getbootstrap.com/css/#forms-controls
2. Find the textarea control and type a few text lines into it
3. The right border is overlapped. See the screenshot below.
![no_right_norder](https://cloud.githubusercontent.com/assets/1233052/14812268/1cbe61a8-0ba5-11e6-9c27-db94eac17487.PNG)

Platform: Windows 10, Chrome 50.0.2661.87 m, Bootstrap 3.3.5

**Comment by RyanZim** [comment] 2016-04-26 13:23
@OlexandrPopov: Correction: Bootstrap is currently at version 3.3.6.

I made a JSFiddle, and am unable to reproduce: https://jsfiddle.net/1k9d9s2s/ (Windows 7, same version of Chrome.). I see what you are describing on getbootstrap.com though.

**Comment by OlexandrPopov** [comment] 2016-04-26 13:41
I'm unable to reproduce the issue with your jsfiddle too. However it appears in my project and on getbootstrap.com. Tried to use bootstrap 3.3.5 and 3.3.6.

**Comment by RyanZim** [comment] 2016-04-26 13:54
Elusive Bug. Sometimes Pastebins don't reproduce issues, so I tried copying the code to a separate file; still can't reproduce.

CC: @cvrebert Any insight?

**Comment by OlexandrPopov** [comment] 2016-04-27 16:56
I managed to reproduce it on jsfiddle. I set `class="col-xs-9"` for the column that contains textarea. Here is the updated jsfiddle [jsfiddle](https://jsfiddle.net/1k9d9s2s/3/). Try to resize the window and you will notice that the right border is blinking.

**Comment by RyanZim** [comment] 2016-04-28 17:46
@OlexandrPopov I still can't reproduce on JSFiddle.

**Comment by Seika85** [comment] 2016-05-10 13:02
@OlexandrPopov: I can confirm that issue with Bootstrap 3.3.6 (using Chrome 50 on Windows 7). Even in the Fiddle posted by @RyanZim, I see the rounded border overlapped by the scroll-bar.

Wierd is, that when I add `width: calc(100% - .5px);` to the texarea the right border is visible again. So I assume it has something to do with rendering percentage widths resolving to float-values in pixel. (.col-md-9 is shown as 847.5px wide in Chromes Developer Tools)

**Comment by mdo** [comment] 2016-09-05 22:34
[**Bootstrap 3 is no longer being officially developed or supported.**](https://github.com/twbs/bootstrap/issues/20631)

All work has moved onto our next major release, v4. As such, this issue or pull request is being closed as a "won't fix." For additional help and support, we recommend [utilizing our community resources](https://github.com/twbs/bootstrap/blob/master/README.md#community). Thanks for your understanding, and see you on the other side of v4!

<3,
@mdo and team

**Closed by mdo** 2016-09-05 22:34 UTC
Labels: css, v3

**Comment by ciarancolgan** [comment] 2017-08-02 14:48
Anyone who still wants a fix for this - put the border on an outer container element with some padding. Put the overflow-y on an inner element (with fixed height). Voila - scrollbar doesn't overlap border.
