### ISSUE TITLE
input-group-btn

### ISSUE THREAD

**Issue by marvin1023** [twbs/bootstrap#17604] opened 2015-09-15 14:58 UTC
![image](https://cloud.githubusercontent.com/assets/1264591/9880181/280ca57c-5bfd-11e5-850d-eb5951a59913.png)

the left `margin-right: -1px` can't solve the problem, we can see 2 borders.

**Comment by smajl** [comment] 2015-09-15 15:03
All recent versions of major browsers are displaying this fine. So this seems like your browser specific edge case? Then target that browser with some override...

**Comment by marvin1023** [comment] 2015-09-15 15:35
![image](https://cloud.githubusercontent.com/assets/1264591/9881418/5a7ec224-5c02-11e5-932a-90ca9dd476e1.png)

chrome 45.0.2454.85 (64-bit)   mac pro

**Comment by cvrebert** [comment] 2015-09-15 18:30
Duplicate of #14237.
See also #17438.

**Closed by cvrebert** 2015-09-15 18:30 UTC
