### ISSUE TITLE
Right to Left support for Twitter Bootstrap 3.3.2?

### ISSUE THREAD

**Issue by mappedinn** [twbs/bootstrap#16052] opened 2015-03-12 16:10 UTC
One quick question: **does Twitter Bootstrap 3.3.2 support Right to Left website?**

Thanks,

**Comment by kkirsche** [comment] 2015-03-12 16:14
I don't believe so yet. Maybe for V4?

**Comment by cvrebert** [comment] 2015-03-12 16:15
Negative.

Duplicate of #14510. Please search next time!
See also #15509.

**Closed by cvrebert** 2015-03-12 16:15 UTC
