### ISSUE TITLE
[v4 beta-3] input-group-prepend and textarea with multiple rows

### ISSUE THREAD

**Issue by qvarting** [twbs/bootstrap#25245] opened 2018-01-09 16:10 UTC
Code:
```
<div class="input-group">
  <div class="input-group-prepend">
    <span class="input-group-text"><i class="fa fa-quote-left" aria-hidden="true"></i></span>
  </div>
  <textarea class="form-control" name="comment" rows="3"></textarea>
</div>
```

Result:
![text-area-group](https://user-images.githubusercontent.com/5320404/34730322-571fb2de-f55f-11e7-8419-642c363c60cd.PNG)

In beta 2 and earlier the input-group-addon was as high as the textarea.

Cheers

**Comment by mdo** [comment] 2018-01-09 17:29
Please search next time. Duplicate of #25102, fixed by #25152.

**Closed by mdo** 2018-01-09 17:29 UTC
