### ISSUE TITLE
Semicolon warnings in Firefox 40

### ISSUE THREAD

**Issue by zbjornson** [twbs/bootstrap#16251] opened 2015-04-07 18:36 UTC
Not to open the can of semicolon worms again... but Firefox 40+ now issues a warning about every semicolon-less `return`. (See https://bugzilla.mozilla.org/show_bug.cgi?id=1005110) Consequently there are dozens of warnings when non-minified bootstrap is used. Yes, they're "just" warnings, and yes, people shouldn't be using non-minified boostrap in production, but "warnings are errors" and at least in development the console is now quite noisy.

**Comment by cvrebert** [comment] 2015-04-07 18:54
Follow-up bug about addressing the false-positives: https://bugzilla.mozilla.org/show_bug.cgi?id=1151931

**Comment by RevanProdigalKnight** [comment] 2015-04-08 15:35
Isn't it considered good coding practice to always use semicolons at the end of a line anyways?

**Comment by zacechola** [comment] 2015-04-08 16:01
@RevanProdigalKnight It's a style *preference*. Let's not start this argument again, please. It's been hashed over many times. Here's what JSHint has to say about ASI:

>This option suppresses warnings about missing semicolons. There is a lot of FUD about semicolon spread by quite a few people in the community. The common myths are that semicolons are required all the time (they are not) and that they are unreliable. JavaScript has rules about semicolons which are followed by all browsers so it is up to you to decide whether you should or should not use semicolons in your code.

>For more information about semicolons in JavaScript read [An Open Letter to JavaScript Leaders Regarding Semicolons](http://blog.izs.me/post/2353458699/an-open-letter-to-javascript-leaders-regarding) by Isaac Schlueter and [JavaScript Semicolon Insertion](http://inimino.org/~inimino/blog/javascript_semicolons).

Interop is important, though, so I'm interested to see what direction the Mozilla folks want to go with this. The issue isn't so much the semi-colon insertion, but the false-positive that gets flagged. Firefox can reach the code using ASI rules, but the warning mechanism still flags this instance.

**Comment by cvrebert** [comment] 2015-04-21 23:05
Closing this in favor of [Mozilla bug #1151931](https://bugzilla.mozilla.org/show_bug.cgi?id=1151931), which is being actively worked on and which should eliminate the false-positive warnings.
Let's not reopen the ASI can of worms, especially this late in Bootstrap v3's lifecycle.

**Closed by cvrebert** 2015-04-21 23:05 UTC
Labels: js

**Comment by cvrebert** [comment] 2015-04-28 20:12
The bug has been fixed in Firefox 40: https://bugzilla.mozilla.org/show_bug.cgi?id=1151931#c24
