### ISSUE TITLE
disabled btn-link button has a different style on hover

### ISSUE THREAD

**Issue by kosl90** [twbs/bootstrap#21415] opened 2016-12-23 15:57 UTC
- Operating system and version : Windows 7
- Browser and version : Google Chrome 55.0.2883.87 m (64-bit)
- Reduced test cases and potential fixes using [JS Bin](https://jsbin.com)
https://jsbin.com/yetixexohi/edit?html,output

potential fixes with:

.btn-link:disabled {
    color: #818a91;
    text-decoration: none;
}

**Comment by mdo** [comment] 2016-12-26 21:55
Dupe of #21235.

**Closed by mdo** 2016-12-26 21:55 UTC
Labels: css, v4

**Comment by mdo** [comment] 2016-12-26 21:57
(Not an exact dupe, but counting it as similar given the disabled stuff. Revisiting that now...)

**Comment by kosl90** [comment] 2016-12-27 00:34
I had looked into that, you guys did a great job again :+1:
