### ISSUE TITLE
Bootstrapt sass import issue

### ISSUE THREAD

**Issue by medeepaksaini** [twbs/bootstrap#31630] opened 2020-09-10 11:29 UTC
hello, i'm trying to import bootstrap function using @import '~bootstrap/scss/functions'; but getting error
@import '~bootstrap/scss/functions';

Can you please tell me why we use ~

**Comment by patrickhlauke** [comment] 2020-09-10 11:34
dupe of https://github.com/twbs/bootstrap/discussions/31629

**Closed by patrickhlauke** 2020-09-10 11:34 UTC
