### ISSUE TITLE
Multistep Form Component.

### ISSUE THREAD

**Issue by suchislife801** [twbs/bootstrap#31227] opened 2020-07-02 20:15 UTC
Search google for the title. I am confident you will find this extremely useful component in many other frameworks but this one.

**Comment by mdo** [comment] 2020-07-02 22:43
Duplicate of #31017 

_As an aside, please do a little more work to present your feature request other than telling us to Google it. We don't implement things simply because someone else has them._

**Closed by mdo** 2020-07-02 22:43 UTC
Labels: feature

**Comment by suchislife801** [comment] 2020-07-03 02:18
My apologies for the lack of additional info.
