### ISSUE TITLE
CSS-Grid g-row classes

### ISSUE THREAD

**Issue by Jonas-Seiler-Wave** [twbs/bootstrap#35944] opened 2022-03-03 14:50 UTC
### Prerequisites

- [X] I have [searched](https://github.com/twbs/bootstrap/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed feature requests
- [X] I have read the [contributing guidelines](https://github.com/twbs/bootstrap/blob/main/.github/CONTRIBUTING.md)

### Proposal

I think there should be responsive classes to govern how much vertical space an element should take up within a CSS grid container as an analogue to the already existing g-col-\* and g-\*-col-* classes.

### Motivation and context

I want to configure my styling such that below the md breakpoint I have this layout
![image](https://user-images.githubusercontent.com/91057137/156587151-8073a415-c2cc-43e7-8273-9be8c9a30595.png)
and above it I have this
![image](https://user-images.githubusercontent.com/91057137/156587471-36054476-8dcf-43b9-ab45-c5f2b356ea4d.png)

I am not aware of a currently working method that doesn't work via two separate blocks like this:
```html
<div class="d-md-none">
    <div class="grid" style="--bs-rows: 2; --bs-columns: 2; --bs-gap: 0;">
        <div class="g-col-1  bg-danger  text-center text-light" style="grid-row: 1 / span 2;">Red</div>
        <div class="g-col-1  bg-success text-center text-light">Green</div>
        <div class="g-col-1  bg-primary text-center text-light">Blue</div>
    </div>
</div>

<div class="d-md-block d-none">
    <div class="grid" style="--bs-rows: 2; --bs-columns: 2; --bs-gap: 0;">
        <div class="g-col-1  bg-danger  text-center text-light">Red</div>
        <div class="g-col-1  bg-success text-center text-light">Green</div>
        <div class="g-col-2  bg-primary text-center text-light">Blue</div>
    </div>
</div>
```

What I would like to be able to do is something akin to this:
```html
<div class="grid" style="--bs-rows: 2; --bs-columns: 2; --bs-gap: 0;">
    <div class="g-col-1 g-row-2  g-row-md-1  bg-danger  text-center text-light">Red</div>
    <div class="g-col-1 g-row-1              bg-success text-center text-light">Green</div>
    <div class="g-col-1 g-row-1  g-col-md-2  bg-primary text-center text-light">Blue</div>
</div>
```

**Comment by WinterSilence** [comment] 2022-03-11 17:52
https://github.com/twbs/bootstrap/discussions/35999 scss in Codepen example

**Comment by mdo** [comment] 2022-04-12 20:11
Duplicate of #35737.

**Closed by mdo** 2022-04-12 20:11 UTC
Labels: feature
