### ISSUE TITLE
Form input type=number with class="form-control" behaves erratically while selecting (in chrome) 

### ISSUE THREAD

**Issue by mverdaguer** [twbs/bootstrap#29528] opened 2019-10-16 02:53 UTC
**Description:**
When you try to select / move the keyboard caret using the mouse inside an `input` having `type=number` and class `form-control` it does not select the text properly. (Only in Chrome).

It seems to work fine when the `input` does not have the `form-control` class, it also works fine in other browsers such as Firefox.

**Minimal case:**
[https://codepen.io/verdegang/pen/ExxyKRK](https://codepen.io/verdegang/pen/ExxyKRK)

**Steps to reproduce:**
Just try to select a subpart of the number inside the `input`, or to change the caret position using the mouse. You'll notice that it behaves erratically.

**Environment:**
Device: MSI laptop using .
OS: Ubuntu 18.04.3 LTS (The same happens using a macOS with el Capitan).
Browser: Chrome
Version: 77.0.3865.90
Bootstrap version: v4.3.1

**Comment by tmorehouse** [comment] 2019-10-16 12:45
Input type `search` also has similar issues with trying to position the insertion point at the beginning of the input using the mouse.

**Comment by swaibat** [comment] 2019-10-26 07:19
true @tmorehouse  becouse i tested and found a similar issue

**Comment by MartijnCuppens** [comment] 2019-12-08 12:56
Is this still an issue, can't seem to reproduce this in `78.0.3904.108`?

**Comment by MartijnCuppens** [comment] 2020-01-09 18:53
Seems to be fixed, closing this

**Closed by MartijnCuppens** 2020-01-09 18:53 UTC
