### ISSUE TITLE
iPad modal scrolling sometimes fail when initial-scale=1 not specified in viewport meta tag

### ISSUE THREAD

**Issue by howardlo** [twbs/bootstrap#15936] opened 2015-02-26 12:22 UTC
When you specify the viewport meta tag in the header without the initial-scale attribute sometimes the modal touch scrolling scrolls the content underneath the modal instead of scrolling the modal. But it's fine if you add "initial-scale=1". This happens in 3.3.1 and 3.3.2

 &lt;meta name="viewport" content="width=device-width"&gt; &lt;!-- modal scroll issue --&gt;

&lt;meta name="viewport" content="width=device-width, initial-scale=1"&gt;  &lt;!-- works fine --&gt;

You can access a test at (try opening the modal and scroll several times).

http://visitview.com/etc/test-modal3.html

**Comment by cvrebert** [comment] 2015-02-26 12:26
* What version of iOS?
* Are you sure you're not describing the caveat documented on http://getbootstrap.com/getting-started/#support-fixed-position-keyboards ?

**Comment by howardlo** [comment] 2015-02-26 13:18
Hi Chris,

 

It is IOS 8.1.3

 

It’s not the issue in the caveat but could be related. Try clicking on “Show My Modal” and then scroll. You may have to do it several times as it isn’t always repeatable. If I knew how to do a video capture on the ipad, I would send it to you.

 

http://visitview.com/etc/test-modal3.html 

 

It drove me nuts for the last several days and piece by piece narrowed it down to the meta tag. I’ve since added the initial-scale=1 but seeing other posts and hacked solutions, I wondered if perhaps other people might have had this settings that caused their problem.

 

Thank you very much,

Howard

**Comment by howardlo** [comment] 2015-02-26 15:30
Hi Chris,

 

I apologize for not thinking of this before. If initial-scale=1 is not set, it seems that Safari sets the zoom scale to fill the screen. In the “Launch demo modal” on  http://getbootstrap.com/javascript/, if one zooms the problem that I described manifests. Thus the Browser zooming caveat applies. It would still be nice if it modal scrolling can work reliably when zoomed.

 

Thanks,

Howard

 

From: Howard Lo [mailto:hloworld@gmail.com] 
Sent: Thursday, February 26, 2015 7:18 AM
To: 'twbs/bootstrap'; 'twbs/bootstrap'
Subject: RE: [bootstrap] iPad modal scrolling sometimes fail when initial-scale=1 not specified in viewport meta tag (#15936)

 

Hi Chris,

 

It is IOS 8.1.3

 

It’s not the issue in the caveat but could be related. Try clicking on “Show My Modal” and then scroll. You may have to do it several times as it isn’t always repeatable. If I knew how to do a video capture on the ipad, I would send it to you.

 

http://visitview.com/etc/test-modal3.html 

 

It drove me nuts for the last several days and piece by piece narrowed it down to the meta tag. I’ve since added the initial-scale=1 but seeing other posts and hacked solutions, I wondered if perhaps other people might have had this settings that caused their problem.

 

Thank you very much,

Howard

**Comment by kkirsche** [comment] 2015-02-26 18:44
Not sure I understand what the issue is here .

On my iPad 3 with iOS 8.1.3 the modal scrolls fine and I can get the background to scroll as well once I hit the end of the modal.

**Comment by howardlo** [comment] 2015-02-26 19:15
Sometime when I try to scroll the modal the modal remains fixed but the background scrolls. Try a pinch zoom and then scroll the modal.

**Comment by kkirsche** [comment] 2015-02-26 19:20
@howardlo yes zooming causes issues on the iPad, but I think that Bootstrap has said multiple times that zooming generally breaks most things on the internet. With that said, if I don't do any zooming it works fine. Once I start zooming and unzooming things freeze up.

Not sure though their opinion of zooming on tablets and ensuring modals remain fully functional after user interactions like this.

**Comment by kkirsche** [comment] 2015-02-26 19:23
Follow up that this may be an instance of what's documented at: http://getbootstrap.com/getting-started/#support-browser-zooming

**Comment by howardlo** [comment] 2015-02-26 19:49
Hi Kevin,

 

It was a trivial (so I thought) header setting (below) that triggered the issue and the posting. It was in a template of an application that I’m moving to bootstrap and for several days I couldn’t figure out why modal scrolling was breaking in IOS. In any case, I finally figured out that adding initial-scale=1 to the meta tag fixed the problem.  Initially it didn’t appear to me to be a zooming issue but after subsequent analysis it looks like IOS applied a zooming factor greater than one if initial scale wasn’t specified.

 

    <meta name="viewport" content="width=device-width" />

 

It would still be nice if modal zoom works but I understand your priorities.

 

Thank you very much,

Howard

**Comment by cvrebert** [comment] 2015-02-26 20:14
@kkirsche That note is meant to cover page zooming on desktop browsers, not pinch-zooming on mobile devices.

**Comment by cvrebert** [comment] 2015-02-26 20:20
Anyway, our docs already recommend setting `initial-scale=1`, with the exception of the non-responsive example which is probably going away in v4, so this bug isn't that high on our priorities list.

**Comment by kkirsche** [comment] 2015-02-26 20:21
Ok. Thanks @cvrebert for clarification :)

**Comment by howardlo** [comment] 2015-02-26 21:08
Ok, Thanks

**Comment by cvrebert** [comment] 2015-03-02 04:00
@twbs/team I propose closing this as WontFix since using `<meta name="viewport" content="width=device-width, initial-scale=1">` is best-practice for supporting tablets anyway. Any objections?

**Comment by hnrch02** [comment] 2015-03-02 10:42
@cvrebert Nope.

**Comment by XhmikosR** [comment] 2015-03-02 10:46
Agreed.

**Closed** 2015-03-02 10:55 UTC
Labels: css

**Comment by howardlo** [comment] 2015-03-02 11:26
That’s fine.

 

Thanks,

Howard
