### ISSUE TITLE
Odd behavior with Carousel when Win Chrome browser tab is inactive

### ISSUE THREAD

**Issue by skibulk** [twbs/bootstrap#15298] opened 2014-12-04 21:48 UTC
I'm using the built in JS carousel a rotating header on my site. The problem occurs while using tabs in the latest version of Chrome.

First open a page with a carousel on it. Then open a new tab (same window). After a few slides would have gone by, switch back to the carousel. The current slide/next slide transition should be broken for one iteration. For example, the current slide image isn't shown until the next slide takes its place. Also the transition times seem to be off. After the one broken iteration, the carousel works as normal.

Maybe this is something that Chrome is doing to save CPU?

**Comment by cvrebert** [comment] 2015-01-05 23:29
Just for the record, I can't seem to repro on Mac Chrome.

**Comment by cvrebert** [comment] 2015-01-05 23:32
@XhmikosR Could you try to repro this?

**Comment by XhmikosR** [comment] 2015-01-06 06:11
I can't seem to reproduce either on the /components page.

**Comment by cvrebert** [comment] 2015-01-06 06:19
@juthilo @hnrch02 Mind giving this a try?

**Comment by juthilo** [comment] 2015-01-06 06:53
I should be able to check this out later today, sure

**Comment by dhampik** [comment] 2015-01-08 17:37
Can reproduce it on http://getbootstrap.com/javascript/#carousel
Ubuntu 14.10 x64 Google Chrome 39.0.2171.95 (64-bit)

**Comment by cvrebert** [comment] 2015-01-08 17:51
@juthilo Any luck?

**Comment by juthilo** [comment] 2015-01-08 18:55
Sorry for the delay. I **can reproduce** on Windows 8.1 using Chrome 39.2171.95.

**Comment by cvrebert** [comment] 2015-01-14 00:22
@juthilo Could you file a Chromium bug?

Only workaround I can think of would be to make use of the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API) to stop the carousel when the tab isn't visible and hope that that would avoid/minimize the problem.

**Comment by cvrebert** [comment] 2015-01-14 00:57
Made a POC for using the visibility API. @juthilo Does the bug repro on http://jsbin.com/yigazi/3 ? (Fingers-crossed that it doesn't..)

**Comment by twbs-lmvtfy** [comment] 2015-01-14 00:57
Hi @cvrebert!

You appear to have posted a live example (http://jsbin.com/yigazi/3/edit), which is always a good first step. However, according to [the HTML5 validator](http://html5.validator.nu), **your example has some validation errors**, which might potentially be causing your issue:
* line 148, column 121: Element ```` img ```` is missing required attribute ```` src ````.
* line 156, column 121: Element ```` img ```` is missing required attribute ```` src ````.
* line 172, column 121: Element ```` img ```` is missing required attribute ```` src ````.

You'll need to **fix these errors** and post a revised example before we can proceed further.
Thanks!

(*Please note that this is a [fully automated](https://github.com/cvrebert/lmvtfy) comment.*)

**Comment by juthilo** [comment] 2015-01-14 18:24
@cvrebert :+1: Can't reproduce using your JS Bin. I did a direct comparison of the live docs and your Bin to be sure.

I'll file the Chromium bug later today.

**Comment by cvrebert** [comment] 2015-01-14 18:30
Cool! Thanks :smile: 
Slight issue with my fix is that CSSComb appears to currently barf on `@supports`; will need to raise an issue with them.

**Comment by juthilo** [comment] 2015-01-15 17:08
Et voilà, the Chromium issue: https://code.google.com/p/chromium/issues/detail?id=449180

**Comment by cvrebert** [comment] 2015-02-17 04:42
Closing as a bug in the browser itself that we can't directly address.
#15566 would have offered an indirect workaround, but has been punted to Bootstrap v4.

**Closed by cvrebert** 2015-02-17 04:42 UTC
Labels: browser bug, confirmed, js
