### ISSUE TITLE
List group flush, first item still has top border

### ISSUE THREAD

**Issue by milosa** [twbs/bootstrap#26961] opened 2018-07-25 09:06 UTC
The manual [shows](https://getbootstrap.com/docs/4.1/components/list-group/#flush) that the first item doesn't have a top border. 
[This piece](https://github.com/twbs/bootstrap/blob/v4-dev/scss/_list-group.scss#L94-L98) is supposed to remove it.

But in this example it has a border:
https://codepen.io/anon/pen/NBgYNo

**Comment by mdo** [comment] 2018-07-25 15:45
This is by design, though I imagine the docs could be clearer. When you place this in a `.card`, the expectation is that you'll want a border at the top to separate the previous bit of content.

**Comment by helmut** [comment] 2018-07-29 22:08
This one caught me as well. In one component the border was there, and then for some unknown reason in another component it was gone! It makes sense now @mdo that you explained it. Thanks! For what it's worth, I'd be inclined to let people add the top border manually. It's not hard to just put a .border-top on the list group when you have content above it.

**Comment by philmayfield** [comment] 2018-09-26 21:12
I ran into this today as well.  Just wanted to throw in my two cents that it the top border on the first li when the parent is not the first child feels wrong given the intent of the modifier class.

That being said an easy workaround is to wrap the ul in a div, but that feels a little wasteful.

**Comment by XhmikosR** [comment] 2018-10-21 08:13
PRs welcome to clarify the docs.

**Comment by kvlsrg** [comment] 2019-01-08 11:07
We really need this top border? As for me it is not clear in case e.g. if some `<p>` is above:
![1](https://user-images.githubusercontent.com/17578344/50827135-53700700-1346-11e9-962b-f1494400bd68.png)

**Comment by milosa** [comment] 2019-01-09 10:14
I just fixed it with some custom CSS. 

`.list-group-flush li:first-child { border-top: none; }`

**Comment by kvlsrg** [comment] 2019-01-09 10:37
@milosa Yes, thanks. But my point here is to ask if this behavior is really expected.

**Comment by xsrvmy** [comment] 2019-02-11 04:49
Here is another example DOM that causes this issue, using Angular 7, without cards:
```
<div _ngcontent-c1="" class="list-group list-group-flush"><!--bindings={
  "ng-reflect-ng-for-of": "0"
}--><button _ngcontent-c1="" app-todo-list-item="" class="list-group-item list-group-item-action" _nghost-c2="" ng-reflect-todo-key="0"><!--bindings={
  "ng-reflect-ng-if": "true"
}--><!---->Hi<!--bindings={
  "ng-reflect-ng-if": "false"
}--><button _ngcontent-c2="" class="close"> ×
</button></button></div>
```

**Comment by itunc1980** [comment] 2019-05-26 01:02
When the .list-group-flush class is added in the List groups, the top line of the first element of the list is still displayed. When I look at the Boostrap.css document

[Before]
Line: 5503
.list-group-flush: first-child .list-group-item: first-child {
  border-top: 0;
}
After adding a comma after .list-group-flush: first-child, the problem is fixing.

[After]
.list-group-flush:first-child, .list-group-item:first-child {
  border-top: 0;
}

**Comment by MartijnCuppens** [comment] 2020-04-15 17:30
Closed by https://github.com/twbs/bootstrap/pull/30497
See https://codepen.io/MartijnCuppens/pen/ExVPXqB

**Closed** 2020-04-15 17:31 UTC
Labels: css, docs, help wanted, v4
