### ISSUE TITLE
Input group addon right corner becomes square when adding a validation element 

### ISSUE THREAD

**Issue by jeffreymeng** [twbs/bootstrap#25946] opened 2018-03-27 00:14 UTC
It seems that when I add a `invalid-feedback` class to a input-group, the corners on the right stop being rounded.

I made a JSFiddle [here](https://jsfiddle.net/jmeng/uvbek5aj/).
It also dosen't work on the bootstrap docs [here](https://getbootstrap.com/docs/4.0/components/forms/#custom-styles) (Click submit while the `username` field is empty and the username field's corners are cut off too).

#### Not working
![2018-03-26_16-56-50](https://user-images.githubusercontent.com/15185258/37939593-80ccddb0-3118-11e8-8143-2316d32445cf.png)

```html
<label for="name">Short Link:</label>
<div class="input-group mb-3">
	<div class="input-group-prepend">
		<span class="input-group-text" id="name-addon">https://jkmls.tk/</span>
	</div>
	<input type="text" class="form-control is-invalid" id="name" aria-describedby="name-addon">
	<div class="input-group-append">
		<button class="btn btn-primary" type="button">Random</button>
	</div>

	<div class="invalid-feedback" id="name-validation">
		Please choose a username.
	</div>
</div>
```

#### Working

![2018-03-26_16-58-09](https://user-images.githubusercontent.com/15185258/37939307-edd6850c-3116-11e8-871b-ce2fa8071fb4.png)

All i did was comment out the validation text:

```html
<!--<div class="invalid-feedback" id="name-validation">
	Please choose a username.
</div>-->
```

**Comment by mdo** [comment] 2018-03-28 02:29
Duplicate of #25110.

**Closed by mdo** 2018-03-28 02:29 UTC
