### ISSUE TITLE
Automaticaly adding .active class on checked radio buttons when DOM is fully loaded

### ISSUE THREAD

**Issue by lafabriqueavisuels** [twbs/bootstrap#28373] opened 2019-02-28 06:20 UTC
## Problem

When an user has checked a radio button and refresh the page, the button is still checked on the DOM but don't have the .active class. In that case, the user don't know the state of the button even if it is already checked

## Solution 

Add the .active class when the DOM is fully loaded

```
// Add active class if input radio checked before loading
$(function() {
  $('.btn-group-toggle').find('input[type=radio]').each(function() {
    if ($(this).is(':checked')) {
      $(this).parent().addClass('active');
    }
  });
});
```

**Comment by ysds** [comment] 2019-03-08 17:42
Duplicate of #25122?

**Comment by Johann-S** [comment] 2019-03-11 13:53
agree with @ysds 👍 

Duplicate of #25122

**Closed by Johann-S** 2019-03-11 13:53 UTC
Labels: js
