### ISSUE TITLE
List of required static and dynamic classes per component to ease the use of tools like uncss

### ISSUE THREAD

**Issue by pamtbaau** [twbs/bootstrap#25941] opened 2018-03-26 09:07 UTC
I would like to cleanup unused classes by using tools like [uncss](https://github.com/uncss/uncss). Required classes can be manually added to uncss and will be ignored and not removed from the stylesheet. 

'Static' classed that should be ignored by uncss can easily be spotted when looking at the bootstrap code.

For some required styling, bootstrap uses dynamically added classes. For example. '.collapsing' is added to '.navbar-collapse' dynamically to smooth the transition of opening/closing dropdown of the navbar. These dynamic classes are not that easily spotted.

Is there a list per component of all required static and dynamic classes?

**Comment by Johann-S** [comment] 2018-03-26 13:06
No, but that's something we should provide in our documentation

**Comment by mdo** [comment] 2018-12-17 22:01
If anyone wants to take a pass at listing out the classes for each relevant component, that'd be awesome! We could easily add a section to each docs page.

**Comment by aapljack** [comment] 2019-03-15 23:47
@mdo / @Johann-S  I would like to take this on. 

To make sure I am going down the right path, I created this list of classes for `alert`. This includes the classes used to build an alert and the classes needed to give it added dynamic functionality. Is this what we are looking for here?

### Alert Classes:
**Static**
alert
alert-primary
alert-secondary
alert-success
alert-danger
alert-warning
alert-info
alert-light
alert-dark
alert-link
alert-heading
alert-dismissible

**Dynamic (adds functionality)**
fade
show

**Comment by mdo** [comment] 2022-04-12 03:41
Duplicate of #22764.

**Closed by mdo** 2022-04-12 03:41 UTC
Labels: docs, help wanted, v4
