### ISSUE TITLE
Npm package for 4.0.0-alpha.3 seems to be missing the JS source files. 

### ISSUE THREAD

**Issue by bobdenotter** [twbs/bootstrap#20479] opened 2016-08-07 12:19 UTC
When doing `npm install bootstrap@4.0.0-alpha.3`, I get a structure like this: 

```
$ tree -d node_modules/bootstrap          
             
node_modules/bootstrap
├── dist
│   ├── css
│   └── js
├── grunt
│   └── bs-sass-compile
└── scss
    ├── mixins
    └── utilities
```

I'd expect the folder `node_modules/bootstrap` to contain a `js/` folder, with the source Javascript files, and not just the compiled one in `dist/js/`. 

Is this an oversight in the packaging? Or an undocumented change?

**Comment by SahAssar** [comment] 2016-08-07 12:25
If I understand this correctly the issue is that the `files` part in v4-npm still says `js/*.js`, while the correct one (`js/**/*.js`) is only in v4-dev.

**Comment by cvrebert** [comment] 2016-08-07 16:47
Duplicate of #20385

**Closed by cvrebert** 2016-08-07 16:47 UTC
