### ISSUE TITLE
.collapse on <table> does not animate

### ISSUE THREAD

**Issue by jennifer-mann** [twbs/bootstrap#16006] opened 2015-03-05 19:59 UTC
If the collapse target element is a `table`, the collapse does not animate. Currently I can make this animation work only by wrapping the `table` in a `div` and making that the collapse target. See jsfiddle.

https://jsfiddle.net/05uvxxgb/

**Comment by cvrebert** [comment] 2015-03-05 22:15
Duplicate of #15672. Please search more in the future.

**Closed by cvrebert** 2015-03-05 22:15 UTC
Labels: css
