### ISSUE TITLE
Popover getContent() being called multiple times

### ISSUE THREAD

**Issue by bardware** [twbs/bootstrap#16695] opened 2015-06-24 07:53 UTC
I have a popover with no title but simple content returned by the `content` member of the structure I pass to the constructor
```
$("body").popover({
  selector: '.clsPop'
  trigger: 'click'
  content: function() {
    var a = 'mycontent';
    return a;
  }
});
```
When I click on an element with the specified class bootstrap first calls
```
  Popover.prototype.hasContent = function () {
    return this.getTitle() || this.getContent()
  }
```
As no title is present the content member is invoked as a function.
Later bootstrap calls 
```
  Popover.prototype.setContent = function () {
    var $tip    = this.tip()
    var title   = this.getTitle()
    var content = this.getContent()
```
Content function is being called another time.
I might have an AJAX call in my `content` function.
Can you probably modify the detection of the presence of `title` and `content` to either work that it does not execute the respective functions or to pass a parameter I can handle and not execute expensive work?

**Comment by cvrebert** [comment] 2015-06-24 10:14
Duplicate of #12563. Please search more next time.

**Closed by cvrebert** 2015-06-24 10:14 UTC
