### ISSUE TITLE
Official site got redirect loop

### ISSUE THREAD

**Issue by ShinyChang** [twbs/bootstrap#17019] opened 2015-08-19 11:15 UTC
I access `http://getbootstrap.com/` or `http://twitter.github.com/bootstrap/`, it redirect to `http://twitter.github.com/bootstrap/2.3.2/`.

see image below:
![image](https://cloud.githubusercontent.com/assets/1590707/9354821/2bf2627e-46a6-11e5-8af7-05b8af61fe38.png)

**Comment by tel8618217223380** [comment] 2015-08-19 11:16
I also encountered this situation.

**Comment by alexmocanu** [comment] 2015-08-19 11:26
Confirmed 

Going to getbootstrap.com redirects to http://twitter.github.com/bootstrap/2.3.2/ and then enters a redirect loop

**Comment by ShinyChang** [comment] 2015-08-19 11:38
```
Request URL: http://twitter.github.com/bootstrap/2.3.2/
307 Location: https://twitter.github.com/bootstrap/2.3.2/
301 Location: http://twitter.github.com/bootstrap/2.3.2/
301 Location: http://getbootstrap.com/2.3.2/
301 Location: http://twitter.github.com/bootstrap/2.3.2/
307 Location: https://twitter.github.com/bootstrap/2.3.2/
...

**Comment by raoul2000** [comment] 2015-08-19 11:39
same here

**Comment by ktimothy** [comment] 2015-08-19 12:19
Confirmed. My work is blocked =)

**Comment by ollietreend** [comment] 2015-08-19 12:48
For those trying to access the docs, [try this mirror](https://bootstrapdocs.com/v3.3.5/docs/).

**Comment by hnrch02** [comment] 2015-08-19 13:15
Try clearing your browser cache, the problem seems to be resolved.

**Comment by ShinyChang** [comment] 2015-08-19 13:47
@hnrch02 
I flush my dns and browser cache, and it looks not work.
Still redirect loop. :cry:

**Comment by mkurz** [comment] 2015-08-19 13:52
Works for me now.

**Comment by mkurz** [comment] 2015-08-19 13:52
@ShinyChang Try ctrl+f5

**Comment by ShinyChang** [comment] 2015-08-19 13:58
@mkurz 
It looks like AP cached.
I connected VPN, and it fixed. :+1:

**Comment by hnrch02** [comment] 2015-08-19 14:00
@twbs/team The 64.13.192.106 A record (not a GH Pages IP) on getbootstrap.com redirects to http://twitter.github.com/bootstrap/. Anyone able to fix that?

**Comment by ShinyChang** [comment] 2015-08-19 14:04
@hnrch02 
It works.

**Comment by hnrch02** [comment] 2015-08-19 14:07
@ShinyChang Yes, but only sometimes. I can reproduce using `curl -Lv http://getbootstrap.com` and it gets stuck in a redirect loop when 64.13.192.106 is selected.

**Comment by mdo** [comment] 2015-08-19 15:06
Working on it! DNS takes forever to resolve, so lingering problems will be expected.

**Comment by hnrch02** [comment] 2015-08-19 15:17
Nice, http://zone.vision/#/getbootstrap.com shows that it is gone - should take about 3 hours to fully propagate. I can't remember what the TTL of the faulty A record was though. @mdo Maybe send out another tweet advising people to flush their DNS cache if they are having troubles?

**Comment by mdo** [comment] 2015-08-19 15:19
Yeah I've cleared the record, we'll see if that takes care of it all. The fact that it's an Apache 301 redirect has me suspicious of something else going on, too. Will continue trying to talk to some folks on the GitHub ops team about it.

**Comment by hnrch02** [comment] 2015-08-19 15:23
Well, the Apache server was the one at 64.13.192.106 which is a MediaTemple server, AFAICT.

**Comment by mdo** [comment] 2015-08-19 15:23
Yeah, but GitHub had set up a special redirect two years ago when we moved orgs :). Just want to make sure that's not causing any problems, too.

**Comment by mdo** [comment] 2015-08-19 16:29
Looks to be getting resolved. Closing for now. <3

**Comment by mdo** [comment] 2015-08-19 16:29
Also hiiiiiii @hnrch02! <3

**Closed by mdo** 2015-08-19 16:29 UTC
Labels: confirmed
