### ISSUE TITLE
Steal

### ISSUE THREAD

**Issue by MarcGodard** [twbs/bootstrap#20687] opened 2016-09-09 12:30 UTC
Using StealJS https://stealjs.com/ (dependency loader)

When `import 'bootstrap';`

![screen shot 2016-09-09 at 8 21 50 am](https://cloud.githubusercontent.com/assets/5016637/18386783/1b81328e-7667-11e6-9fbe-8653f37c7a1a.png)

All code is current version.

**Comment by Avcajaraville** [comment] 2016-09-09 12:33
Did you include Tether ? Because thats the error thats popping in. 

Include jQuery, then Tether, then Bootstrap.

**Comment by MarcGodard** [comment] 2016-09-09 12:41
That is the error, bootstrap should be dealing with its own dependencies.

**Comment by Avcajaraville** [comment] 2016-09-09 12:53
Well its not, you might or not wanting to use tooltips, you might build it in another way. Also, its is stated on the documents, and as a last thing, you are dealing with an ALPHA version, so, problems are expected :)

But glad it helped you :)

**Comment by MarcGodard** [comment] 2016-09-09 12:57
How does this being an alpha version change anything? Wouldn't you want people to report their issues? 

However, if NPM installs the dependencies, the library should be dealing with it when you import it. That is all I am saying. If this wasn't the case, I would need to import hundreds of dependencies. This is the reason libraries should be dealing with their own dependencies.

But glad you understand that :)

**Comment by chimericdream** [comment] 2016-09-09 13:36
I don't think the alpha status of the project matters in this context. However, I agree that Bootstrap should not compile its dependencies directly into the build. As @Avcajaraville said, people might not use all of the components, or they might want to include different versions of the dependencies, or any number of other common possibilities. jQuery and Tether are not build-time dependencies of Bootstrap, but rather runtime _peer_ dependencies. They are not required in order to use a great deal of Bootstrap's core functionality. If you need or want to use the JavaScript components, include your preferred (and compatible) version of jQuery. If you specifically want to use popovers or tooltips, include a compatible version of Tether in your project.

It's a deliberate design choice. I can understand the minor frustration of having to include the deps explicitly, but ultimately I think Bootstrap is immensely more flexible because of it.

**Comment by zacechola** [comment] 2016-09-09 19:12
Duplicate of #17201, I believe.

**Comment by cvrebert** [comment] 2016-09-10 00:17
What @zacechola said. The code is still in an in-between state between the ES5 jQuery plugin paradigm and the ES6 paradigm.

**Closed by cvrebert** 2016-09-10 00:17 UTC
