### ISSUE TITLE
Glyphicon shows up but IE11 throws CSS3111 error

### ISSUE THREAD

**Issue by seahrh** [twbs/bootstrap#16500] opened 2015-05-18 09:26 UTC
Bootstrap glyphicon shows up fine but IE11 console reports CSS3111: @font-face encountered unknown error for these files:
 - glyphicons-halflings-regular.eot
 - glyphicons-halflings-regular.woff
 - glyphicons-halflings-regular.ttf

![ie11_fontface](https://cloud.githubusercontent.com/assets/4428622/7677880/583562b8-fd82-11e4-84e0-bba405b8a325.JPG)

This is the Bootstrap override in my stylesheet (only the URL paths were changed):

```
@font-face {
    font-family: 'Glyphicons Halflings';
    src: url('../../vendor/bootstrap/fonts/glyphicons-halflings-regular.eot');
    src: url('../../vendor/bootstrap/fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'),
        url('../../vendor/bootstrap/fonts/glyphicons-halflings-regular.woff2') format('woff2'), 
        url('../../vendor/bootstrap/fonts/glyphicons-halflings-regular.woff') format('woff'), 
        url('../../vendor/bootstrap/fonts/glyphicons-halflings-regular.ttf') format('truetype'), 
        url('../../vendor/bootstrap/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

Side note: If I add `!important` after the first `src` url, then the icon **doesn't show up**.

```
@font-face {
    font-family: 'Glyphicons Halflings';
    src: url('../../vendor/bootstrap/fonts/glyphicons-halflings-regular.eot') !important;
...}
```

Using Bootstrap 3.3.4, IE 11.0.9600.17801

How do I get rid of the errors?

My [SO question](http://stackoverflow.com/questions/30255546/bootstrap-glyphicon-shows-up-but-ie11-throws-css3111-error)

This [other answer on SO](http://stackoverflow.com/a/14092444/519951) suggests that CSS3111 error could be caused by the font's binary source (.EOT file) that somehow does not comply with Microsoft's standards. Wondering if this is related?

**Comment by kkirsche** [comment] 2015-05-18 12:40
@seahrh can you post a JSBin showing this example?

My understanding is that JSBin implements all of this so if it doesn't happen on JSBin it's an implementation issue on your end that would need to be solved on StackOverflow.

**Comment by cvrebert** [comment] 2015-05-19 01:32
I am unable to reproduce with http://output.jsbin.com/zakusi/2 on Win 8.1 IE 11.0.9600.17278 via Sauce Labs.

**Comment by kkirsche** [comment] 2015-05-19 01:36
@cvrebert I'm installing IE 11 on Windows 8.1 via Parallels. Once it's done I'll check if I can reproduce it on that

**Comment by kkirsche** [comment] 2015-05-19 01:56
Cannot reproduce on IE 11.0.9600.17031 or 11.0.10011.0 via https://remote.modern.ie

the later did have a 404 for https://output.jsbin.com/zakusi/2/bootstrap.css.map but no other warnings or errors

**Comment by cvrebert** [comment] 2015-05-19 02:08
Closing as not reproducible then. Presumably this is a personal server/app setup problem, which is out of scope for this bug tracker; see https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#using-the-issue-tracker

**Closed by cvrebert** 2015-05-19 02:08 UTC
Labels: css

**Comment by RitchieD** [comment] 2015-09-28 18:15
I get the same issue,

**Comment by cvrebert** [comment] 2015-09-28 18:26
@RitchieD Does the problem also occur on http://output.jsbin.com/zakusi/2 ?

**Comment by RitchieD** [comment] 2015-09-28 18:31
http://output.jsbin.com/zakusi/2 ? That site is blocked for me.

**Comment by RitchieD** [comment] 2015-09-28 18:33
I downloaded new copy of fonts from https://github.com/twbs/bootstrap/tree/master/fonts
and problem went away
