### ISSUE TITLE
Tooltip & Popover don't use container setting

### ISSUE THREAD

**Issue by erikosterholm83** [twbs/bootstrap#20746] opened 2016-09-19 06:51 UTC
I want to place a popover inside a specific element but i can't get it working by using container setting. (and i can't see the container setting is used anywhere in the code)

http://v4-alpha.getbootstrap.com/components/popovers/

$(this).popover({
     html: true,
     trigger: 'manual',
     placement: 'top',
     container : '.page'
});

**Comment by zacechola** [comment] 2016-09-19 15:55
Could you please include a [reduced test case](https://css-tricks.com/reduced-test-cases/) as an example? Thank you.

**Comment by zacechola** [comment] 2016-09-19 15:57
Ah, nevermind. This appears to be a duplicate of #17755.

**Closed** 2016-09-19 16:54 UTC
